## Multi-protocol CNN Raw CSI Experiments

This notebook runs the fixed-capacity CNN across block, LOVO, and cross-session protocols with one independent run per configured seed.

In [1]:
from __future__ import annotations

import pandas as pd
import torch

from utils.config import (
    ANCHOR_GROUPS,
    ARCHITECTURE,
    BANDS_TO_RUN,
    DATA_DIR,
    DEFAULT_CNN_PARAMS,
    DEFAULT_OVERLAP_SIZE,
    DEFAULT_WINDOW_SIZE,
    EXPECTED_ANCHORS,
    EXPECTED_SUBCARRIERS,
    SEEDS,
)
from utils.DL.dl_pipeline import (
    create_position_label_encoder,
    get_cache_path,
    get_results_path,
    prepare_dl_data,
    print_torch_environment,
    run_dl_experiments,
    show_dl_results,
)

### Configuration

In [2]:
CALIBRATION_MODE = "rssi"    # ("none", "packet_norm", "rssi")

CSV_PROCESSING_OPTIONS = {
    "max_workers": 1,
    "cache_dir": None,
    "use_cache": True,
    "force_reprocess": False,
    "min_rssi_dbm": -95.0,
}

MAGNITUDE_PROCESSING_OPTIONS = {
    "normalization": "empty_baseline",  # none | zscore | minmax | packet_minmax | empty_baseline
    "epsilon": 1e-8,
}
NORMALIZATION_BASELINE_SCOPE = "per_session"

FEATURE_EXTRACTION_OPTIONS = {
    "window_size": DEFAULT_WINDOW_SIZE,
    "overlap_size": DEFAULT_OVERLAP_SIZE,
    "require_all_esps": False,
}

BLOCK_COUNT = 10
TEST_SIZE = 0.30
VALIDATION_SIZE = 0.15
RANDOM_STATE = 42
FORCE_RETRAIN = False
SPLIT_MODES = ("lovo",)

CNN_PARAMS = {
    **DEFAULT_CNN_PARAMS,
    "model_label": "CNN",
    "epochs": 70,
    "patience": 15,
    "lr": 1e-3,
    "weight_decay": 1e-4,
    "random_state": RANDOM_STATE,
    "test_size": TEST_SIZE,
    "validation_size": VALIDATION_SIZE,
    "n_blocks": BLOCK_COUNT,
    "anchor_groups": ANCHOR_GROUPS,
    "torch_version": torch.__version__,
}

preproc_opts = dict(MAGNITUDE_PROCESSING_OPTIONS)
preproc_opts["baseline_scope"] = NORMALIZATION_BASELINE_SCOPE
feat_opts = dict(FEATURE_EXTRACTION_OPTIONS)

feature_cache_dir = get_cache_path(preproc_opts, feat_opts)
results_dir = get_results_path()
plots_dir = results_dir / "plots"
for directory in (plots_dir, results_dir / "predictions", results_dir / "tables"):
    directory.mkdir(parents=True, exist_ok=True)

print(f"Feature cache path: {feature_cache_dir}")
print(f"Results path: {results_dir}")

Feature cache path: /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/.cache/dataframes/preproc=norm-empty_baseline_scope-per_session/feat=win60-step0
Results path: /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results

### Environment

In [3]:
DEVICE = print_torch_environment(require_cuda=True)

torch.__version__: 2.11.0+cu128
torch.version.cuda: 12.8
torch.cuda.get_device_name(0): NVIDIA RTX PRO 6000 Blackwell Max-Q Workstation Edition
torch.cuda.get_device_capability(0): (12, 0)
CUDA matmul smoke test result: [[0.0, 1.0, 2.0, 3.0], [4.0, 5.0, 6.0, 7.0], [8.0, 9.0, 10.0, 11.0], [12.0, 13.0, 14.0, 15.0]] (PASS)

### Data

In [4]:
processed_magnitude_data, feature_dataframes, csv_diagnostics, magnitude_summary = prepare_dl_data(
    DATA_DIR,
    calibration_mode=CALIBRATION_MODE,
    csv_options=CSV_PROCESSING_OPTIONS,
    preproc_opts=preproc_opts,
    feat_opts=feat_opts,
)
display(magnitude_summary.head())

Scenarios present: 1
Locations: 53 | Users: 6 | ESPs: 19
[Z-0 inventory]
  total Z-0 files found: 171
  Z-0 count per (user, trial):
    (user=01, trial=01): 19
    (user=01, trial=02): 19
    (user=02, trial=01): 19
    (user=03, trial=01): 19
    (user=03, trial=02): 19
    (user=04, trial=01): 19
    (user=05, trial=01): 19
    (user=05, trial=02): 19
    (user=06, trial=01): 19
  breakdown by user / esp / trial:
    user=01 esp=01 trial=01: 1
    user=01 esp=01 trial=02: 1
    user=01 esp=02 trial=01: 1
    user=01 esp=02 trial=02: 1
    user=01 esp=03 trial=01: 1
    user=01 esp=03 trial=02: 1
    user=01 esp=04 trial=01: 1
    user=01 esp=04 trial=02: 1
    user=01 esp=05 trial=01: 1
    user=01 esp=05 trial=02: 1
    user=01 esp=07 trial=01: 1
    user=01 esp=07 trial=02: 1
    user=01 esp=08 trial=01: 1
    user=01 esp=08 trial=02: 1
    user=01 esp=09 trial=01: 1
    user=01 esp=09 trial=02: 1
    user=01 esp=10 trial=01: 1
    user=01 esp=10 trial=02: 1
    user=01 esp=11 trial=01: 1
    user=01 esp=11 trial=02: 1
    user=01 esp=12 trial=01: 1
    user=01 esp=12 trial=02: 1
    user=01 esp=13 trial=01: 1
    user=01 esp=13 trial=02: 1
    user=01 esp=14 trial=01: 1
    user=01 esp=14 trial=02: 1
    user=01 esp=15 trial=01: 1
    user=01 esp=15 trial=02: 1
    user=01 esp=16 trial=01: 1
    user=01 esp=16 trial=02: 1
    user=01 esp=17 trial=01: 1
    user=01 esp=17 trial=02: 1
    user=01 esp=18 trial=01: 1
    user=01 esp=18 trial=02: 1
    user=01 esp=19 trial=01: 1
    user=01 esp=19 trial=02: 1
    user=01 esp=20 trial=01: 1
    user=01 esp=20 trial=02: 1
    user=02 esp=01 trial=01: 1
    user=02 esp=02 trial=01: 1
    user=02 esp=03 trial=01: 1
    user=02 esp=04 trial=01: 1
    user=02 esp=05 trial=01: 1
    user=02 esp=07 trial=01: 1
    user=02 esp=08 trial=01: 1
    user=02 esp=09 trial=01: 1
    user=02 esp=10 trial=01: 1
    user=02 esp=11 trial=01: 1
    user=02 esp=12 trial=01: 1
    user=02 esp=13 trial=01: 1
    user=02 esp=14 trial=01: 1
    user=02 esp=15 trial=01: 1
    user=02 esp=16 trial=01: 1
    user=02 esp=17 trial=01: 1
    user=02 esp=18 trial=01: 1
    user=02 esp=19 trial=01: 1
    user=02 esp=20 trial=01: 1
    user=03 esp=01 trial=01: 1
    user=03 esp=01 trial=02: 1
    user=03 esp=02 trial=01: 1
    user=03 esp=02 trial=02: 1
    user=03 esp=03 trial=01: 1
    user=03 esp=03 trial=02: 1
    user=03 esp=04 trial=01: 1
    user=03 esp=04 trial=02: 1
    user=03 esp=05 trial=01: 1
    user=03 esp=05 trial=02: 1
    user=03 esp=07 trial=01: 1
    user=03 esp=07 trial=02: 1
    user=03 esp=08 trial=01: 1
    user=03 esp=08 trial=02: 1
    user=03 esp=09 trial=01: 1
    user=03 esp=09 trial=02: 1
    user=03 esp=10 trial=01: 1
    user=03 esp=10 trial=02: 1
    user=03 esp=11 trial=01: 1
    user=03 esp=11 trial=02: 1
    user=03 esp=12 trial=01: 1
    user=03 esp=12 trial=02: 1
    user=03 esp=13 trial=01: 1
    user=03 esp=13 trial=02: 1
    user=03 esp=14 trial=01: 1
    user=03 esp=14 trial=02: 1
    user=03 esp=15 trial=01: 1
    user=03 esp=15 trial=02: 1
    user=03 esp=16 trial=01: 1
    user=03 esp=16 trial=02: 1
    user=03 esp=17 trial=01: 1
    user=03 esp=17 trial=02: 1
    user=03 esp=18 trial=01: 1
    user=03 esp=18 trial=02: 1
    user=03 esp=19 trial=01: 1
    user=03 esp=19 trial=02: 1
    user=03 esp=20 trial=01: 1
    user=03 esp=20 trial=02: 1
    user=04 esp=01 trial=01: 1
    user=04 esp=02 trial=01: 1
    user=04 esp=03 trial=01: 1
    user=04 esp=04 trial=01: 1
    user=04 esp=05 trial=01: 1
    user=04 esp=07 trial=01: 1
    user=04 esp=08 trial=01: 1
    user=04 esp=09 trial=01: 1
    user=04 esp=10 trial=01: 1
    user=04 esp=11 trial=01: 1
    user=04 esp=12 trial=01: 1
    user=04 esp=13 trial=01: 1
    user=04 esp=14 trial=01: 1
    user=04 esp=15 trial=01: 1
    user=04 esp=16 trial=01: 1
    user=04 esp=17 trial=01: 1
    user=04 esp=18 trial=01: 1
    user=04 esp=19 trial=01: 1
    user=04 esp=20 trial=01: 1
    user=05 esp=01 trial=01: 1
    user=05 esp=01 trial=02: 1
    user=05 esp=02 trial=01: 1
    user=05 esp=02 trial=02: 1
    user=05 esp=03 trial=01: 1
    user=05 esp=03 trial=02: 1
    user=05 esp=04 trial=01: 1
    user=05 esp=04 trial=02: 1
    user=05 esp=05 trial=01: 1
    user=05 esp=05 trial=02: 1
    user=05 esp=07 trial=01: 1
    user=05 esp=07 trial=02: 1
    user=05 esp=08 trial=01: 1
    user=05 esp=08 trial=02: 1
    user=05 esp=09 trial=01: 1
    user=05 esp=09 trial=02: 1
    user=05 esp=10 trial=01: 1
    user=05 esp=10 trial=02: 1
    user=05 esp=11 trial=01: 1
    user=05 esp=11 trial=02: 1
    user=05 esp=12 trial=01: 1
    user=05 esp=12 trial=02: 1
    user=05 esp=13 trial=01: 1
    user=05 esp=13 trial=02: 1
    user=05 esp=14 trial=01: 1
    user=05 esp=14 trial=02: 1
    user=05 esp=15 trial=01: 1
    user=05 esp=15 trial=02: 1
    user=05 esp=16 trial=01: 1
    user=05 esp=16 trial=02: 1
    user=05 esp=17 trial=01: 1
    user=05 esp=17 trial=02: 1
    user=05 esp=18 trial=01: 1
    user=05 esp=18 trial=02: 1
    user=05 esp=19 trial=01: 1
    user=05 esp=19 trial=02: 1
    user=05 esp=20 trial=01: 1
    user=05 esp=20 trial=02: 1
    user=06 esp=01 trial=01: 1
    user=06 esp=02 trial=01: 1
    user=06 esp=03 trial=01: 1
    user=06 esp=04 trial=01: 1
    user=06 esp=05 trial=01: 1
    user=06 esp=07 trial=01: 1
    user=06 esp=08 trial=01: 1
    user=06 esp=09 trial=01: 1
    user=06 esp=10 trial=01: 1
    user=06 esp=11 trial=01: 1
    user=06 esp=12 trial=01: 1
    user=06 esp=13 trial=01: 1
    user=06 esp=14 trial=01: 1
    user=06 esp=15 trial=01: 1
    user=06 esp=16 trial=01: 1
    user=06 esp=17 trial=01: 1
    user=06 esp=18 trial=01: 1
    user=06 esp=19 trial=01: 1
    user=06 esp=20 trial=01: 1
  baseline coverage for occupied recordings:
    user=01 trial=01 esp=01: yes
    user=01 trial=01 esp=02: yes
    user=01 trial=01 esp=03: yes
    user=01 trial=01 esp=04: yes
    user=01 trial=01 esp=05: yes
    user=01 trial=01 esp=07: yes
    user=01 trial=01 esp=08: yes
    user=01 trial=01 esp=09: yes
    user=01 trial=01 esp=10: yes
    user=01 trial=01 esp=11: yes
    user=01 trial=01 esp=12: yes
    user=01 trial=01 esp=13: yes
    user=01 trial=01 esp=14: yes
    user=01 trial=01 esp=15: yes
    user=01 trial=01 esp=16: yes
    user=01 trial=01 esp=17: yes
    user=01 trial=01 esp=18: yes
    user=01 trial=01 esp=19: yes
    user=01 trial=01 esp=20: yes
    user=01 trial=02 esp=01: yes
    user=01 trial=02 esp=02: yes
    user=01 trial=02 esp=03: yes
    user=01 trial=02 esp=04: yes
    user=01 trial=02 esp=05: yes
    user=01 trial=02 esp=07: yes
    user=01 trial=02 esp=08: yes
    user=01 trial=02 esp=09: yes
    user=01 trial=02 esp=10: yes
    user=01 trial=02 esp=11: yes
    user=01 trial=02 esp=12: yes
    user=01 trial=02 esp=13: yes
    user=01 trial=02 esp=14: yes
    user=01 trial=02 esp=15: yes
    user=01 trial=02 esp=16: yes
    user=01 trial=02 esp=17: yes
    user=01 trial=02 esp=18: yes
    user=01 trial=02 esp=19: yes
    user=01 trial=02 esp=20: yes
    user=02 trial=01 esp=01: yes
    user=02 trial=01 esp=02: yes
    user=02 trial=01 esp=03: yes
    user=02 trial=01 esp=04: yes
    user=02 trial=01 esp=05: yes
    user=02 trial=01 esp=07: yes
    user=02 trial=01 esp=08: yes
    user=02 trial=01 esp=09: yes
    user=02 trial=01 esp=10: yes
    user=02 trial=01 esp=11: yes
    user=02 trial=01 esp=12: yes
    user=02 trial=01 esp=13: yes
    user=02 trial=01 esp=14: yes
    user=02 trial=01 esp=15: yes
    user=02 trial=01 esp=16: yes
    user=02 trial=01 esp=17: yes
    user=02 trial=01 esp=18: yes
    user=02 trial=01 esp=19: yes
    user=02 trial=01 esp=20: yes
    user=03 trial=01 esp=01: yes
    user=03 trial=01 esp=02: yes
    user=03 trial=01 esp=03: yes
    user=03 trial=01 esp=04: yes
    user=03 trial=01 esp=05: yes
    user=03 trial=01 esp=07: yes
    user=03 trial=01 esp=08: yes
    user=03 trial=01 esp=09: yes
    user=03 trial=01 esp=10: yes
    user=03 trial=01 esp=11: yes
    user=03 trial=01 esp=12: yes
    user=03 trial=01 esp=13: yes
    user=03 trial=01 esp=14: yes
    user=03 trial=01 esp=15: yes
    user=03 trial=01 esp=16: yes
    user=03 trial=01 esp=17: yes
    user=03 trial=01 esp=18: yes
    user=03 trial=01 esp=19: yes
    user=03 trial=01 esp=20: yes
    user=03 trial=02 esp=01: yes
    user=03 trial=02 esp=02: yes
    user=03 trial=02 esp=03: yes
    user=03 trial=02 esp=04: yes
    user=03 trial=02 esp=05: yes
    user=03 trial=02 esp=07: yes
    user=03 trial=02 esp=08: yes
    user=03 trial=02 esp=09: yes
    user=03 trial=02 esp=10: yes
    user=03 trial=02 esp=11: yes
    user=03 trial=02 esp=12: yes
    user=03 trial=02 esp=13: yes
    user=03 trial=02 esp=14: yes
    user=03 trial=02 esp=15: yes
    user=03 trial=02 esp=16: yes
    user=03 trial=02 esp=17: yes
    user=03 trial=02 esp=18: yes
    user=03 trial=02 esp=19: yes
    user=03 trial=02 esp=20: yes
    user=04 trial=01 esp=01: yes
    user=04 trial=01 esp=02: yes
    user=04 trial=01 esp=03: yes
    user=04 trial=01 esp=04: yes
    user=04 trial=01 esp=05: yes
    user=04 trial=01 esp=07: yes
    user=04 trial=01 esp=08: yes
    user=04 trial=01 esp=09: yes
    user=04 trial=01 esp=10: yes
    user=04 trial=01 esp=11: yes
    user=04 trial=01 esp=12: yes
    user=04 trial=01 esp=13: yes
    user=04 trial=01 esp=14: yes
    user=04 trial=01 esp=15: yes
    user=04 trial=01 esp=16: yes
    user=04 trial=01 esp=17: yes
    user=04 trial=01 esp=18: yes
    user=04 trial=01 esp=19: yes
    user=04 trial=01 esp=20: yes
    user=05 trial=01 esp=01: yes
    user=05 trial=01 esp=02: yes
    user=05 trial=01 esp=03: yes
    user=05 trial=01 esp=04: yes
    user=05 trial=01 esp=05: yes
    user=05 trial=01 esp=07: yes
    user=05 trial=01 esp=08: yes
    user=05 trial=01 esp=09: yes
    user=05 trial=01 esp=10: yes
    user=05 trial=01 esp=11: yes
    user=05 trial=01 esp=12: yes
    user=05 trial=01 esp=13: yes
    user=05 trial=01 esp=14: yes
    user=05 trial=01 esp=15: yes
    user=05 trial=01 esp=16: yes
    user=05 trial=01 esp=17: yes
    user=05 trial=01 esp=18: yes
    user=05 trial=01 esp=19: yes
    user=05 trial=01 esp=20: yes
    user=05 trial=02 esp=01: yes
    user=05 trial=02 esp=02: yes
    user=05 trial=02 esp=03: yes
    user=05 trial=02 esp=04: yes
    user=05 trial=02 esp=05: yes
    user=05 trial=02 esp=07: yes
    user=05 trial=02 esp=08: yes
    user=05 trial=02 esp=09: yes
    user=05 trial=02 esp=10: yes
    user=05 trial=02 esp=11: yes
    user=05 trial=02 esp=12: yes
    user=05 trial=02 esp=13: yes
    user=05 trial=02 esp=14: yes
    user=05 trial=02 esp=15: yes
    user=05 trial=02 esp=16: yes
    user=05 trial=02 esp=17: yes
    user=05 trial=02 esp=18: yes
    user=05 trial=02 esp=19: yes
    user=05 trial=02 esp=20: yes
    user=06 trial=01 esp=01: yes
    user=06 trial=01 esp=02: yes
    user=06 trial=01 esp=03: yes
    user=06 trial=01 esp=04: yes
    user=06 trial=01 esp=05: yes
    user=06 trial=01 esp=07: yes
    user=06 trial=01 esp=08: yes
    user=06 trial=01 esp=09: yes
    user=06 trial=01 esp=10: yes
    user=06 trial=01 esp=11: yes
    user=06 trial=01 esp=12: yes
    user=06 trial=01 esp=13: yes
    user=06 trial=01 esp=14: yes
    user=06 trial=01 esp=15: yes
    user=06 trial=01 esp=16: yes
    user=06 trial=01 esp=17: yes
    user=06 trial=01 esp=18: yes
    user=06 trial=01 esp=19: yes
    user=06 trial=01 esp=20: yes
  per_session scope fully satisfiable: yes
  deep-fade clipped subcarriers:
    user=01 trial=01 esp=01: 1
    user=01 trial=01 esp=02: 1
    user=01 trial=01 esp=03: 1
    user=01 trial=01 esp=04: 1
    user=01 trial=01 esp=05: 1
    user=01 trial=01 esp=07: 1
    user=01 trial=01 esp=08: 1
    user=01 trial=01 esp=09: 1
    user=01 trial=01 esp=10: 0
    user=01 trial=01 esp=11: 1
    user=01 trial=01 esp=12: 1
    user=01 trial=01 esp=13: 1
    user=01 trial=01 esp=14: 1
    user=01 trial=01 esp=15: 1
    user=01 trial=01 esp=16: 1
    user=01 trial=01 esp=17: 1
    user=01 trial=01 esp=18: 1
    user=01 trial=01 esp=19: 1
    user=01 trial=01 esp=20: 1
    user=01 trial=02 esp=01: 1
    user=01 trial=02 esp=02: 1
    user=01 trial=02 esp=03: 1
    user=01 trial=02 esp=04: 1
    user=01 trial=02 esp=05: 1
    user=01 trial=02 esp=07: 1
    user=01 trial=02 esp=08: 1
    user=01 trial=02 esp=09: 1
    user=01 trial=02 esp=10: 1
    user=01 trial=02 esp=11: 1
    user=01 trial=02 esp=12: 1
    user=01 trial=02 esp=13: 1
    user=01 trial=02 esp=14: 1
    user=01 trial=02 esp=15: 1
    user=01 trial=02 esp=16: 1
    user=01 trial=02 esp=17: 1
    user=01 trial=02 esp=18: 1
    user=01 trial=02 esp=19: 1
    user=01 trial=02 esp=20: 1
    user=02 trial=01 esp=01: 1
    user=02 trial=01 esp=02: 1
    user=02 trial=01 esp=03: 1
    user=02 trial=01 esp=04: 1
    user=02 trial=01 esp=05: 1
    user=02 trial=01 esp=07: 1
    user=02 trial=01 esp=08: 1
    user=02 trial=01 esp=09: 1
    user=02 trial=01 esp=10: 0
    user=02 trial=01 esp=11: 1
    user=02 trial=01 esp=12: 1
    user=02 trial=01 esp=13: 1
    user=02 trial=01 esp=14: 1
    user=02 trial=01 esp=15: 1
    user=02 trial=01 esp=16: 1
    user=02 trial=01 esp=17: 1
    user=02 trial=01 esp=18: 1
    user=02 trial=01 esp=19: 1
    user=02 trial=01 esp=20: 1
    user=03 trial=01 esp=01: 1
    user=03 trial=01 esp=02: 1
    user=03 trial=01 esp=03: 1
    user=03 trial=01 esp=04: 1
    user=03 trial=01 esp=05: 1
    user=03 trial=01 esp=07: 0
    user=03 trial=01 esp=08: 1
    user=03 trial=01 esp=09: 1
    user=03 trial=01 esp=10: 1
    user=03 trial=01 esp=11: 1
    user=03 trial=01 esp=12: 1
    user=03 trial=01 esp=13: 1
    user=03 trial=01 esp=14: 1
    user=03 trial=01 esp=15: 1
    user=03 trial=01 esp=16: 1
    user=03 trial=01 esp=17: 1
    user=03 trial=01 esp=18: 1
    user=03 trial=01 esp=19: 1
    user=03 trial=01 esp=20: 1
    user=03 trial=02 esp=01: 1
    user=03 trial=02 esp=02: 1
    user=03 trial=02 esp=03: 1
    user=03 trial=02 esp=04: 1
    user=03 trial=02 esp=05: 1
    user=03 trial=02 esp=07: 1
    user=03 trial=02 esp=08: 1
    user=03 trial=02 esp=09: 0
    user=03 trial=02 esp=10: 0
    user=03 trial=02 esp=11: 1
    user=03 trial=02 esp=12: 1
    user=03 trial=02 esp=13: 1
    user=03 trial=02 esp=14: 1
    user=03 trial=02 esp=15: 1
    user=03 trial=02 esp=16: 1
    user=03 trial=02 esp=17: 1
    user=03 trial=02 esp=18: 1
    user=03 trial=02 esp=19: 1
    user=03 trial=02 esp=20: 1
    user=04 trial=01 esp=01: 1
    user=04 trial=01 esp=02: 1
    user=04 trial=01 esp=03: 1
    user=04 trial=01 esp=04: 1
    user=04 trial=01 esp=05: 1
    user=04 trial=01 esp=07: 1
    user=04 trial=01 esp=08: 1
    user=04 trial=01 esp=09: 1
    user=04 trial=01 esp=10: 1
    user=04 trial=01 esp=11: 1
    user=04 trial=01 esp=12: 1
    user=04 trial=01 esp=13: 1
    user=04 trial=01 esp=14: 1
    user=04 trial=01 esp=15: 1
    user=04 trial=01 esp=16: 1
    user=04 trial=01 esp=17: 1
    user=04 trial=01 esp=18: 1
    user=04 trial=01 esp=19: 1
    user=04 trial=01 esp=20: 1
    user=05 trial=01 esp=01: 1
    user=05 trial=01 esp=02: 1
    user=05 trial=01 esp=03: 0
    user=05 trial=01 esp=04: 1
    user=05 trial=01 esp=05: 1
    user=05 trial=01 esp=07: 1
    user=05 trial=01 esp=08: 1
    user=05 trial=01 esp=09: 1
    user=05 trial=01 esp=10: 0
    user=05 trial=01 esp=11: 1
    user=05 trial=01 esp=12: 1
    user=05 trial=01 esp=13: 1
    user=05 trial=01 esp=14: 1
    user=05 trial=01 esp=15: 1
    user=05 trial=01 esp=16: 1
    user=05 trial=01 esp=17: 1
    user=05 trial=01 esp=18: 1
    user=05 trial=01 esp=19: 1
    user=05 trial=01 esp=20: 1
    user=05 trial=02 esp=01: 1
    user=05 trial=02 esp=02: 1
    user=05 trial=02 esp=03: 1
    user=05 trial=02 esp=04: 1
    user=05 trial=02 esp=05: 1
    user=05 trial=02 esp=07: 1
    user=05 trial=02 esp=08: 1
    user=05 trial=02 esp=09: 1
    user=05 trial=02 esp=10: 1
    user=05 trial=02 esp=11: 1
    user=05 trial=02 esp=12: 1
    user=05 trial=02 esp=13: 1
    user=05 trial=02 esp=14: 1
    user=05 trial=02 esp=15: 0
    user=05 trial=02 esp=16: 0
    user=05 trial=02 esp=17: 1
    user=05 trial=02 esp=18: 1
    user=05 trial=02 esp=19: 0
    user=05 trial=02 esp=20: 1
    user=06 trial=01 esp=01: 1
    user=06 trial=01 esp=02: 1
    user=06 trial=01 esp=03: 1
    user=06 trial=01 esp=04: 1
    user=06 trial=01 esp=05: 1
    user=06 trial=01 esp=07: 1
    user=06 trial=01 esp=08: 1
    user=06 trial=01 esp=09: 1
    user=06 trial=01 esp=10: 1
    user=06 trial=01 esp=11: 1
    user=06 trial=01 esp=12: 1
    user=06 trial=01 esp=13: 1
    user=06 trial=01 esp=14: 1
    user=06 trial=01 esp=15: 1
    user=06 trial=01 esp=16: 1
    user=06 trial=01 esp=17: 1
    user=06 trial=01 esp=18: 1
    user=06 trial=01 esp=19: 1
    user=06 trial=01 esp=20: 1
[cache hit] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/.cache/dataframes/preproc=norm-empty_baseline_scope-per_session/feat=win60-step0/2_4ghz.parquet
[cache hit] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/.cache/dataframes/preproc=norm-empty_baseline_scope-per_session/feat=win60-step0/5ghz.parquet
[cache hit] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/.cache/dataframes/preproc=norm-empty_baseline_scope-per_session/feat=win60-step0/fusion.parquet

,scenario,location,user,esp,trial,samples,subcarriers,normalization,baseline_scope
0,1,C-1,06,16,01,2088,56,empty_baseline,per_session
1,1,C-1,06,15,01,1942,56,empty_baseline,per_session
2,1,C-1,06,09,01,1689,50,empty_baseline,per_session
3,1,C-1,06,07,01,1965,50,empty_baseline,per_session
4,1,C-1,06,04,01,1913,50,empty_baseline,per_session

In [5]:
for band in BANDS_TO_RUN:
    df = feature_dataframes[band]
    print(f"{band}: {df.shape[0]} windows, {df.shape[1]} columns")
    print(f"{band} dataframe hash: {pd.util.hash_pandas_object(df, index=True).sum()}")

2.4 GHz: 13588 windows, 2708 columns
2.4 GHz dataframe hash: 12830868654705884127
5 GHz: 14478 windows, 3368 columns
5 GHz dataframe hash: 5016803871464446121
Fusion: 13568 windows, 6068 columns
Fusion dataframe hash: 3976504561903335248

In [6]:
label_encoder = create_position_label_encoder(
    feature_dataframes,
    results_dir=results_dir,
    expected_classes=52,
)
print(label_encoder.classes_)

[CNN] label classes saved to /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/manifests/cnn_label_classes.json
['A-1' 'A-13' 'A-14' 'A-2' 'A-5' 'B-1' 'B-10' 'B-11' 'B-12' 'B-13' 'B-14'
 'B-2' 'B-5' 'B-8' 'C-1' 'C-10' 'C-11' 'C-14' 'C-2' 'C-3' 'C-4' 'C-5'
 'C-6' 'C-7' 'C-8' 'C-9' 'D-1' 'D-2' 'D-3' 'D-4' 'D-5' 'D-6' 'D-7' 'D-8'
 'E-1' 'E-10' 'E-11' 'E-12' 'E-13' 'E-2' 'E-3' 'E-4' 'E-5' 'E-6' 'E-7'
 'E-8' 'F-10' 'F-11' 'F-12' 'F-13' 'F-5' 'F-8']

### Train And Evaluate

In [7]:
cnn_runs = run_dl_experiments(
    processed_magnitude_data,
    feature_dataframes,
    bands=BANDS_TO_RUN,
    split_modes=SPLIT_MODES,
    label_encoder=label_encoder,
    device=DEVICE,
    results_dir=results_dir,
    plots_dir=plots_dir,
    params=CNN_PARAMS,
    preproc_opts=preproc_opts,
    feat_opts=feat_opts,
    expected_subcarriers=EXPECTED_SUBCARRIERS,
    expected_anchors=EXPECTED_ANCHORS,
    architecture=ARCHITECTURE,
    seeds=SEEDS,
    test_size=TEST_SIZE,
    random_state=RANDOM_STATE,
    n_blocks=BLOCK_COUNT,
    val_size=VALIDATION_SIZE,
    force_retrain=FORCE_RETRAIN,
)

=== Fusion ===
[window arrays] cache path: /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/.cache/dataframes/preproc=norm-empty_baseline_scope-per_session/feat=win60-step0/window_arrays/fusion
[window arrays cache hit] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/.cache/dataframes/preproc=norm-empty_baseline_scope-per_session/feat=win60-step0/window_arrays/fusion
[window arrays] 2.4 GHz: shape=(13568, 9, 50, 60), dtype=float16
[window arrays] 2.4 GHz anchors: ['esp_01', 'esp_02', 'esp_03', 'esp_04', 'esp_05', 'esp_07', 'esp_08', 'esp_09', 'esp_10']
[window arrays] 5 GHz: shape=(13568, 10, 56, 60), dtype=float16
[window arrays] 5 GHz anchors: ['esp_11', 'esp_12', 'esp_13', 'esp_14', 'esp_15', 'esp_16', 'esp_17', 'esp_18', 'esp_19', 'esp_20']
[room window arrays] padding rows=2, derived from first-conv kernel_size - 1 (3 - 1).
[room window arrays] cache path: /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/.cache/dataframes/preproc=norm-empty_baseline_scope-per_session/feat=win60-step0/window_arrays/room_stacked__7fa0a1ac7d8f
[room window arrays] Room 1: shape=(13568, 4, 108, 60), dtype=float16
[room window arrays] Room 1 anchor pairs: [['esp_07', 'esp_17'], ['esp_08', 'esp_18'], ['esp_09', 'esp_19'], ['esp_10', 'esp_20']]
[room window arrays] Room 2: shape=(13568, 3, 108, 60), dtype=float16
[room window arrays] Room 2 anchor pairs: [['esp_01', 'esp_11'], ['esp_02', 'esp_12'], ['esp_03', 'esp_13']]
[room window arrays] Room 3: shape=(13568, 2, 108, 60), dtype=float16
[room window arrays] Room 3 anchor pairs: [['esp_04', 'esp_14'], ['esp_05', 'esp_15']]
WINDOW IDENTITY PASS: Fusion (13568 windows)
[trial filter] split=lovo trials=['01'] kept=8889/13568
[trial filter] split=lovo trials=['01'] kept=8889/8889
[protocol] split=lovo fold=01 trials_used=['01'] n_train=7331 n_test=1558 users=['01', '02', '03', '04', '05', '06'] train_users=['02', '03', '04', '05', '06'] test_users=['01']
[protocol] split=lovo fold=02 trials_used=['01'] n_train=7478 n_test=1411 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '03', '04', '05', '06'] test_users=['02']
[protocol] split=lovo fold=03 trials_used=['01'] n_train=7303 n_test=1586 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '04', '05', '06'] test_users=['03']
[protocol] split=lovo fold=04 trials_used=['01'] n_train=7330 n_test=1559 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '05', '06'] test_users=['04']
[protocol] split=lovo fold=05 trials_used=['01'] n_train=7403 n_test=1486 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '06'] test_users=['05']
[protocol] split=lovo fold=06 trials_used=['01'] n_train=7600 n_test=1289 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05'] test_users=['06']
[trial filter] split=lovo trials=['01'] kept=8889/13568
[trial filter] split=lovo trials=['01'] kept=8889/8889
[protocol] split=lovo fold=01 trials_used=['01'] n_train=7331 n_test=1558 users=['01', '02', '03', '04', '05', '06'] train_users=['02', '03', '04', '05', '06'] test_users=['01']
[protocol] split=lovo fold=02 trials_used=['01'] n_train=7478 n_test=1411 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '03', '04', '05', '06'] test_users=['02']
[protocol] split=lovo fold=03 trials_used=['01'] n_train=7303 n_test=1586 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '04', '05', '06'] test_users=['03']
[protocol] split=lovo fold=04 trials_used=['01'] n_train=7330 n_test=1559 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '05', '06'] test_users=['04']
[protocol] split=lovo fold=05 trials_used=['01'] n_train=7403 n_test=1486 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '06'] test_users=['05']
[protocol] split=lovo fold=06 trials_used=['01'] n_train=7600 n_test=1289 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05'] test_users=['06']
SPLIT IDENTITY PASS: Fusion/lovo fold=1 train=7331 test=1558
SPLIT IDENTITY PASS: Fusion/lovo fold=2 train=7478 test=1411
SPLIT IDENTITY PASS: Fusion/lovo fold=3 train=7303 test=1586
SPLIT IDENTITY PASS: Fusion/lovo fold=4 train=7330 test=1559
SPLIT IDENTITY PASS: Fusion/lovo fold=5 train=7403 test=1486
SPLIT IDENTITY PASS: Fusion/lovo fold=6 train=7600 test=1289
Seeds: random=42, numpy=42, torch=42
[trial filter] split=lovo trials=['01'] kept=8889/13568
[trial filter] split=lovo trials=['01'] kept=8889/8889
[protocol] split=lovo fold=01 trials_used=['01'] n_train=7331 n_test=1558 users=['01', '02', '03', '04', '05', '06'] train_users=['02', '03', '04', '05', '06'] test_users=['01']
[protocol] split=lovo fold=02 trials_used=['01'] n_train=7478 n_test=1411 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '03', '04', '05', '06'] test_users=['02']
[protocol] split=lovo fold=03 trials_used=['01'] n_train=7303 n_test=1586 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '04', '05', '06'] test_users=['03']
[protocol] split=lovo fold=04 trials_used=['01'] n_train=7330 n_test=1559 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '05', '06'] test_users=['04']
[protocol] split=lovo fold=05 trials_used=['01'] n_train=7403 n_test=1486 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '06'] test_users=['05']
[protocol] split=lovo fold=06 trials_used=['01'] n_train=7600 n_test=1289 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05'] test_users=['06']
[DL LOVO] held_out_user=01 validation_user=06 (entire user, deterministic rotation)
[CNN_room] Fusion/lovo fold=01 parameters=195636
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN_room] Fusion/lovo fold=01 epoch 01/70: train_loss=3.7457 train_acc=0.0927 val_loss=3.7637 val_acc=0.0908 seconds=4.5
[CNN_room] Fusion/lovo fold=01 epoch 02/70: train_loss=3.0615 train_acc=0.1796 val_loss=3.4108 val_acc=0.1621 seconds=1.3
[CNN_room] Fusion/lovo fold=01 epoch 03/70: train_loss=2.6146 train_acc=0.2536 val_loss=3.6376 val_acc=0.1466 seconds=1.2
[CNN_room] Fusion/lovo fold=01 epoch 04/70: train_loss=2.3882 train_acc=0.2877 val_loss=3.5196 val_acc=0.1528 seconds=1.0
[CNN_room] Fusion/lovo fold=01 epoch 05/70: train_loss=2.2275 train_acc=0.3338 val_loss=3.6866 val_acc=0.1652 seconds=1.0
[CNN_room] Fusion/lovo fold=01 epoch 06/70: train_loss=2.1102 train_acc=0.3679 val_loss=4.0067 val_acc=0.1412 seconds=1.0
[CNN_room] Fusion/lovo fold=01 epoch 07/70: train_loss=1.9919 train_acc=0.3942 val_loss=3.9873 val_acc=0.1404 seconds=1.0
[CNN_room] Fusion/lovo fold=01 epoch 08/70: train_loss=1.8870 train_acc=0.4237 val_loss=4.1775 val_acc=0.1350 seconds=1.0
[CNN_room] Fusion/lovo fold=01 epoch 09/70: train_loss=1.8085 train_acc=0.4421 val_loss=4.2728 val_acc=0.1420 seconds=0.9
[CNN_room] Fusion/lovo fold=01 epoch 10/70: train_loss=1.7128 train_acc=0.4681 val_loss=4.4394 val_acc=0.1389 seconds=0.9
[CNN_room] Fusion/lovo fold=01 epoch 11/70: train_loss=1.6333 train_acc=0.4926 val_loss=4.7013 val_acc=0.1389 seconds=1.0
[CNN_room] Fusion/lovo fold=01 epoch 12/70: train_loss=1.5530 train_acc=0.5179 val_loss=4.8838 val_acc=0.1280 seconds=1.0
[CNN_room] Fusion/lovo fold=01 epoch 13/70: train_loss=1.4721 train_acc=0.5382 val_loss=4.6951 val_acc=0.1404 seconds=1.0
[CNN_room] Fusion/lovo fold=01 epoch 14/70: train_loss=1.4065 train_acc=0.5649 val_loss=5.1928 val_acc=0.1288 seconds=1.0
[CNN_room] Fusion/lovo fold=01 epoch 15/70: train_loss=1.3355 train_acc=0.5847 val_loss=5.2087 val_acc=0.1257 seconds=0.9
[CNN_room] Fusion/lovo fold=01 epoch 16/70: train_loss=1.2759 train_acc=0.6041 val_loss=5.6920 val_acc=0.1404 seconds=0.9
[CNN_room] Fusion/lovo fold=01 epoch 17/70: train_loss=1.2443 train_acc=0.6061 val_loss=5.6789 val_acc=0.1319 seconds=1.0
[CNN_room] Fusion/lovo fold=01 epoch 18/70: train_loss=1.1820 train_acc=0.6279 val_loss=5.7770 val_acc=0.1396 seconds=0.9
[CNN_room] Fusion/lovo fold=01 epoch 19/70: train_loss=1.1271 train_acc=0.6511 val_loss=6.0987 val_acc=0.1567 seconds=0.9
[CNN_room] Fusion/lovo fold=01 epoch 20/70: train_loss=1.0840 train_acc=0.6544 val_loss=6.2096 val_acc=0.1249 seconds=0.9
[CNN_room] early stopping at epoch 20; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn_room__fusion__lovo__ebl-session__s42__dc4ee3__fold-01.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn_room__fusion__lovo__ebl-session__s42__dc4ee3/training_curves__fold-01.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=02 validation_user=01 (entire user, deterministic rotation)
[CNN_room] Fusion/lovo fold=02 parameters=195636
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN_room] Fusion/lovo fold=02 epoch 01/70: train_loss=3.7344 train_acc=0.0831 val_loss=3.8148 val_acc=0.0796 seconds=3.4
[CNN_room] Fusion/lovo fold=02 epoch 02/70: train_loss=3.0239 train_acc=0.1931 val_loss=4.9759 val_acc=0.0796 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 03/70: train_loss=2.5963 train_acc=0.2503 val_loss=6.5463 val_acc=0.1091 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 04/70: train_loss=2.3615 train_acc=0.3025 val_loss=7.1608 val_acc=0.1078 seconds=1.1
[CNN_room] Fusion/lovo fold=02 epoch 05/70: train_loss=2.1881 train_acc=0.3429 val_loss=6.5437 val_acc=0.1181 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 06/70: train_loss=2.0625 train_acc=0.3740 val_loss=7.3872 val_acc=0.0854 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 07/70: train_loss=1.9626 train_acc=0.4020 val_loss=7.2629 val_acc=0.0963 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 08/70: train_loss=1.8649 train_acc=0.4343 val_loss=7.5656 val_acc=0.1072 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 09/70: train_loss=1.7956 train_acc=0.4439 val_loss=8.3191 val_acc=0.0899 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 10/70: train_loss=1.7006 train_acc=0.4801 val_loss=7.6443 val_acc=0.1059 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 11/70: train_loss=1.5992 train_acc=0.5098 val_loss=8.4198 val_acc=0.0982 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 12/70: train_loss=1.5502 train_acc=0.5211 val_loss=7.9999 val_acc=0.0988 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 13/70: train_loss=1.4996 train_acc=0.5409 val_loss=8.8023 val_acc=0.1008 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 14/70: train_loss=1.4119 train_acc=0.5676 val_loss=8.7650 val_acc=0.0995 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 15/70: train_loss=1.3658 train_acc=0.5735 val_loss=8.4929 val_acc=0.1232 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 16/70: train_loss=1.2917 train_acc=0.5956 val_loss=7.9678 val_acc=0.1258 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 17/70: train_loss=1.2448 train_acc=0.6047 val_loss=8.6432 val_acc=0.1316 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 18/70: train_loss=1.1690 train_acc=0.6378 val_loss=10.1172 val_acc=0.1008 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 19/70: train_loss=1.1359 train_acc=0.6451 val_loss=8.2595 val_acc=0.1354 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 20/70: train_loss=1.0719 train_acc=0.6573 val_loss=8.8826 val_acc=0.1181 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 21/70: train_loss=1.0492 train_acc=0.6649 val_loss=9.4944 val_acc=0.1168 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 22/70: train_loss=1.0302 train_acc=0.6728 val_loss=9.6639 val_acc=0.1374 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 23/70: train_loss=0.9392 train_acc=0.7029 val_loss=9.5818 val_acc=0.1264 seconds=1.1
[CNN_room] Fusion/lovo fold=02 epoch 24/70: train_loss=0.9237 train_acc=0.7057 val_loss=10.1860 val_acc=0.1155 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 25/70: train_loss=0.8870 train_acc=0.7209 val_loss=9.4610 val_acc=0.1380 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 26/70: train_loss=0.8691 train_acc=0.7262 val_loss=10.2468 val_acc=0.1207 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 27/70: train_loss=0.8387 train_acc=0.7302 val_loss=9.4882 val_acc=0.1418 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 28/70: train_loss=0.8161 train_acc=0.7314 val_loss=10.2230 val_acc=0.1322 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 29/70: train_loss=0.7729 train_acc=0.7426 val_loss=9.6445 val_acc=0.1239 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 30/70: train_loss=0.7670 train_acc=0.7480 val_loss=10.0838 val_acc=0.1232 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 31/70: train_loss=0.7268 train_acc=0.7627 val_loss=10.9476 val_acc=0.1200 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 32/70: train_loss=0.7058 train_acc=0.7708 val_loss=9.9632 val_acc=0.1245 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 33/70: train_loss=0.6989 train_acc=0.7772 val_loss=11.1087 val_acc=0.1290 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 34/70: train_loss=0.6927 train_acc=0.7784 val_loss=9.9283 val_acc=0.1316 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 35/70: train_loss=0.6458 train_acc=0.7910 val_loss=12.0551 val_acc=0.1252 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 36/70: train_loss=0.6388 train_acc=0.7902 val_loss=11.3083 val_acc=0.1309 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 37/70: train_loss=0.6353 train_acc=0.7907 val_loss=10.6491 val_acc=0.1412 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 38/70: train_loss=0.6269 train_acc=0.7968 val_loss=11.2249 val_acc=0.1098 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 39/70: train_loss=0.6107 train_acc=0.8022 val_loss=10.6022 val_acc=0.1573 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 40/70: train_loss=0.5945 train_acc=0.8118 val_loss=11.4531 val_acc=0.1361 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 41/70: train_loss=0.5667 train_acc=0.8125 val_loss=11.4204 val_acc=0.1303 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 42/70: train_loss=0.5589 train_acc=0.8179 val_loss=11.7821 val_acc=0.1297 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 43/70: train_loss=0.5426 train_acc=0.8220 val_loss=10.9980 val_acc=0.1348 seconds=1.1
[CNN_room] Fusion/lovo fold=02 epoch 44/70: train_loss=0.5548 train_acc=0.8169 val_loss=10.7283 val_acc=0.1367 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 45/70: train_loss=0.5346 train_acc=0.8265 val_loss=11.3764 val_acc=0.1303 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 46/70: train_loss=0.5063 train_acc=0.8358 val_loss=11.8795 val_acc=0.1226 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 47/70: train_loss=0.4941 train_acc=0.8416 val_loss=11.0058 val_acc=0.1380 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 48/70: train_loss=0.5046 train_acc=0.8394 val_loss=11.1565 val_acc=0.1476 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 49/70: train_loss=0.4672 train_acc=0.8483 val_loss=11.4343 val_acc=0.1483 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 50/70: train_loss=0.4607 train_acc=0.8507 val_loss=11.2768 val_acc=0.1463 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 51/70: train_loss=0.4709 train_acc=0.8426 val_loss=12.6034 val_acc=0.1303 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 52/70: train_loss=0.4429 train_acc=0.8583 val_loss=11.1928 val_acc=0.1367 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 53/70: train_loss=0.4386 train_acc=0.8532 val_loss=12.6211 val_acc=0.1213 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 54/70: train_loss=0.4427 train_acc=0.8559 val_loss=12.2903 val_acc=0.1297 seconds=1.0
[CNN_room] early stopping at epoch 54; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn_room__fusion__lovo__ebl-session__s42__dc4ee3__fold-02.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn_room__fusion__lovo__ebl-session__s42__dc4ee3/training_curves__fold-02.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=03 validation_user=02 (entire user, deterministic rotation)
[CNN_room] Fusion/lovo fold=03 parameters=195636
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN_room] Fusion/lovo fold=03 epoch 01/70: train_loss=3.7341 train_acc=0.1078 val_loss=3.7997 val_acc=0.0411 seconds=4.0
[CNN_room] Fusion/lovo fold=03 epoch 02/70: train_loss=3.0491 train_acc=0.1850 val_loss=3.8856 val_acc=0.0751 seconds=0.9
[CNN_room] Fusion/lovo fold=03 epoch 03/70: train_loss=2.6446 train_acc=0.2517 val_loss=4.2444 val_acc=0.0539 seconds=1.0
[CNN_room] Fusion/lovo fold=03 epoch 04/70: train_loss=2.4233 train_acc=0.2955 val_loss=4.4729 val_acc=0.0560 seconds=1.0
[CNN_room] Fusion/lovo fold=03 epoch 05/70: train_loss=2.2304 train_acc=0.3254 val_loss=4.7539 val_acc=0.0574 seconds=0.9
[CNN_room] Fusion/lovo fold=03 epoch 06/70: train_loss=2.1743 train_acc=0.3489 val_loss=4.8769 val_acc=0.0539 seconds=0.9
[CNN_room] Fusion/lovo fold=03 epoch 07/70: train_loss=2.0090 train_acc=0.3900 val_loss=5.0877 val_acc=0.0624 seconds=0.9
[CNN_room] Fusion/lovo fold=03 epoch 08/70: train_loss=1.9092 train_acc=0.4165 val_loss=5.6526 val_acc=0.0595 seconds=1.0
[CNN_room] Fusion/lovo fold=03 epoch 09/70: train_loss=1.8390 train_acc=0.4396 val_loss=5.6935 val_acc=0.0588 seconds=0.9
[CNN_room] Fusion/lovo fold=03 epoch 10/70: train_loss=1.7446 train_acc=0.4695 val_loss=6.0449 val_acc=0.0560 seconds=0.9
[CNN_room] Fusion/lovo fold=03 epoch 11/70: train_loss=1.6534 train_acc=0.4939 val_loss=6.3024 val_acc=0.0730 seconds=0.9
[CNN_room] Fusion/lovo fold=03 epoch 12/70: train_loss=1.5672 train_acc=0.5170 val_loss=6.5936 val_acc=0.0553 seconds=0.9
[CNN_room] Fusion/lovo fold=03 epoch 13/70: train_loss=1.4985 train_acc=0.5312 val_loss=6.6856 val_acc=0.0546 seconds=0.9
[CNN_room] Fusion/lovo fold=03 epoch 14/70: train_loss=1.4683 train_acc=0.5419 val_loss=7.1587 val_acc=0.0454 seconds=0.9
[CNN_room] Fusion/lovo fold=03 epoch 15/70: train_loss=1.4294 train_acc=0.5507 val_loss=6.9146 val_acc=0.0595 seconds=0.9
[CNN_room] Fusion/lovo fold=03 epoch 16/70: train_loss=1.3349 train_acc=0.5821 val_loss=7.3243 val_acc=0.0574 seconds=0.9
[CNN_room] Fusion/lovo fold=03 epoch 17/70: train_loss=1.3990 train_acc=0.5613 val_loss=7.9423 val_acc=0.0624 seconds=0.9
[CNN_room] early stopping at epoch 17; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn_room__fusion__lovo__ebl-session__s42__dc4ee3__fold-03.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn_room__fusion__lovo__ebl-session__s42__dc4ee3/training_curves__fold-03.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=04 validation_user=03 (entire user, deterministic rotation)
[CNN_room] Fusion/lovo fold=04 parameters=195636
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN_room] Fusion/lovo fold=04 epoch 01/70: train_loss=3.7792 train_acc=0.0810 val_loss=3.8081 val_acc=0.0631 seconds=4.0
[CNN_room] Fusion/lovo fold=04 epoch 02/70: train_loss=3.1386 train_acc=0.1574 val_loss=3.4671 val_acc=0.1185 seconds=1.0
[CNN_room] Fusion/lovo fold=04 epoch 03/70: train_loss=2.7008 train_acc=0.2329 val_loss=3.4655 val_acc=0.1280 seconds=1.0
[CNN_room] Fusion/lovo fold=04 epoch 04/70: train_loss=2.4473 train_acc=0.2805 val_loss=3.8122 val_acc=0.1337 seconds=1.0
[CNN_room] Fusion/lovo fold=04 epoch 05/70: train_loss=2.2574 train_acc=0.3334 val_loss=3.9262 val_acc=0.1343 seconds=1.0
[CNN_room] Fusion/lovo fold=04 epoch 06/70: train_loss=2.0973 train_acc=0.3693 val_loss=3.9136 val_acc=0.1400 seconds=1.0
[CNN_room] Fusion/lovo fold=04 epoch 07/70: train_loss=1.9749 train_acc=0.4022 val_loss=4.0827 val_acc=0.1463 seconds=0.9
[CNN_room] Fusion/lovo fold=04 epoch 08/70: train_loss=1.8459 train_acc=0.4380 val_loss=4.4179 val_acc=0.1375 seconds=0.9
[CNN_room] Fusion/lovo fold=04 epoch 09/70: train_loss=1.7407 train_acc=0.4708 val_loss=4.3511 val_acc=0.1356 seconds=0.9
[CNN_room] Fusion/lovo fold=04 epoch 10/70: train_loss=1.6349 train_acc=0.4986 val_loss=4.4084 val_acc=0.1311 seconds=1.0
[CNN_room] Fusion/lovo fold=04 epoch 11/70: train_loss=1.5713 train_acc=0.5172 val_loss=4.9223 val_acc=0.1305 seconds=0.9
[CNN_room] Fusion/lovo fold=04 epoch 12/70: train_loss=1.4918 train_acc=0.5409 val_loss=5.1411 val_acc=0.1293 seconds=0.9
[CNN_room] Fusion/lovo fold=04 epoch 13/70: train_loss=1.4073 train_acc=0.5660 val_loss=4.9512 val_acc=0.1248 seconds=1.0
[CNN_room] Fusion/lovo fold=04 epoch 14/70: train_loss=1.3195 train_acc=0.5911 val_loss=5.4235 val_acc=0.1211 seconds=0.9
[CNN_room] Fusion/lovo fold=04 epoch 15/70: train_loss=1.2816 train_acc=0.6015 val_loss=5.4196 val_acc=0.1204 seconds=1.0
[CNN_room] Fusion/lovo fold=04 epoch 16/70: train_loss=1.2034 train_acc=0.6191 val_loss=5.6258 val_acc=0.1236 seconds=1.0
[CNN_room] Fusion/lovo fold=04 epoch 17/70: train_loss=1.1635 train_acc=0.6339 val_loss=5.8943 val_acc=0.1135 seconds=1.0
[CNN_room] Fusion/lovo fold=04 epoch 18/70: train_loss=1.1145 train_acc=0.6431 val_loss=6.0785 val_acc=0.1267 seconds=0.9
[CNN_room] Fusion/lovo fold=04 epoch 19/70: train_loss=1.0330 train_acc=0.6788 val_loss=5.8899 val_acc=0.1160 seconds=1.0
[CNN_room] Fusion/lovo fold=04 epoch 20/70: train_loss=1.0078 train_acc=0.6774 val_loss=6.4702 val_acc=0.1135 seconds=1.0
[CNN_room] Fusion/lovo fold=04 epoch 21/70: train_loss=0.9768 train_acc=0.6905 val_loss=6.5897 val_acc=0.1173 seconds=1.0
[CNN_room] Fusion/lovo fold=04 epoch 22/70: train_loss=0.9355 train_acc=0.6983 val_loss=7.1510 val_acc=0.1173 seconds=1.0
[CNN_room] early stopping at epoch 22; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn_room__fusion__lovo__ebl-session__s42__dc4ee3__fold-04.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn_room__fusion__lovo__ebl-session__s42__dc4ee3/training_curves__fold-04.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=05 validation_user=04 (entire user, deterministic rotation)
[CNN_room] Fusion/lovo fold=05 parameters=195636
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN_room] Fusion/lovo fold=05 epoch 01/70: train_loss=3.7443 train_acc=0.0758 val_loss=3.8605 val_acc=0.0398 seconds=3.8
[CNN_room] Fusion/lovo fold=05 epoch 02/70: train_loss=3.1093 train_acc=0.1537 val_loss=3.9027 val_acc=0.0821 seconds=0.9
[CNN_room] Fusion/lovo fold=05 epoch 03/70: train_loss=2.7238 train_acc=0.2192 val_loss=3.8377 val_acc=0.1046 seconds=1.0
[CNN_room] Fusion/lovo fold=05 epoch 04/70: train_loss=2.5046 train_acc=0.2586 val_loss=3.8733 val_acc=0.1148 seconds=1.0
[CNN_room] Fusion/lovo fold=05 epoch 05/70: train_loss=2.3207 train_acc=0.3084 val_loss=4.1403 val_acc=0.1110 seconds=1.0
[CNN_room] Fusion/lovo fold=05 epoch 06/70: train_loss=2.2054 train_acc=0.3378 val_loss=4.0417 val_acc=0.1353 seconds=1.0
[CNN_room] Fusion/lovo fold=05 epoch 07/70: train_loss=2.0666 train_acc=0.3722 val_loss=4.2871 val_acc=0.1212 seconds=0.9
[CNN_room] Fusion/lovo fold=05 epoch 08/70: train_loss=1.9673 train_acc=0.4026 val_loss=4.3382 val_acc=0.1360 seconds=0.9
[CNN_room] Fusion/lovo fold=05 epoch 09/70: train_loss=1.8650 train_acc=0.4247 val_loss=4.3763 val_acc=0.1251 seconds=0.9
[CNN_room] Fusion/lovo fold=05 epoch 10/70: train_loss=1.7673 train_acc=0.4600 val_loss=4.5889 val_acc=0.1206 seconds=0.9
[CNN_room] Fusion/lovo fold=05 epoch 11/70: train_loss=1.6715 train_acc=0.4819 val_loss=4.6724 val_acc=0.1328 seconds=0.9
[CNN_room] Fusion/lovo fold=05 epoch 12/70: train_loss=1.5970 train_acc=0.4985 val_loss=4.7327 val_acc=0.1328 seconds=0.9
[CNN_room] Fusion/lovo fold=05 epoch 13/70: train_loss=1.5370 train_acc=0.5241 val_loss=4.5701 val_acc=0.1289 seconds=0.9
[CNN_room] Fusion/lovo fold=05 epoch 14/70: train_loss=1.4746 train_acc=0.5416 val_loss=4.7194 val_acc=0.1450 seconds=0.9
[CNN_room] Fusion/lovo fold=05 epoch 15/70: train_loss=1.4195 train_acc=0.5573 val_loss=4.9458 val_acc=0.1289 seconds=0.9
[CNN_room] Fusion/lovo fold=05 epoch 16/70: train_loss=1.3487 train_acc=0.5773 val_loss=5.2419 val_acc=0.1366 seconds=1.0
[CNN_room] Fusion/lovo fold=05 epoch 17/70: train_loss=1.2896 train_acc=0.5965 val_loss=4.8732 val_acc=0.1475 seconds=0.9
[CNN_room] Fusion/lovo fold=05 epoch 18/70: train_loss=1.2431 train_acc=0.6136 val_loss=4.9777 val_acc=0.1462 seconds=0.9
[CNN_room] Fusion/lovo fold=05 epoch 19/70: train_loss=1.2000 train_acc=0.6246 val_loss=5.3920 val_acc=0.1437 seconds=0.9
[CNN_room] Fusion/lovo fold=05 epoch 20/70: train_loss=1.1579 train_acc=0.6312 val_loss=5.5263 val_acc=0.1495 seconds=0.9
[CNN_room] Fusion/lovo fold=05 epoch 21/70: train_loss=1.1249 train_acc=0.6441 val_loss=5.6623 val_acc=0.1264 seconds=0.9
[CNN_room] Fusion/lovo fold=05 epoch 22/70: train_loss=1.0529 train_acc=0.6716 val_loss=5.6158 val_acc=0.1398 seconds=0.9
[CNN_room] Fusion/lovo fold=05 epoch 23/70: train_loss=1.0445 train_acc=0.6715 val_loss=6.0004 val_acc=0.1135 seconds=1.0
[CNN_room] Fusion/lovo fold=05 epoch 24/70: train_loss=1.0142 train_acc=0.6798 val_loss=5.8371 val_acc=0.1379 seconds=1.0
[CNN_room] Fusion/lovo fold=05 epoch 25/70: train_loss=0.9658 train_acc=0.6905 val_loss=5.9014 val_acc=0.1405 seconds=1.0
[CNN_room] Fusion/lovo fold=05 epoch 26/70: train_loss=0.9344 train_acc=0.7093 val_loss=5.9172 val_acc=0.1264 seconds=1.0
[CNN_room] Fusion/lovo fold=05 epoch 27/70: train_loss=0.9156 train_acc=0.7059 val_loss=6.2445 val_acc=0.1475 seconds=1.0
[CNN_room] Fusion/lovo fold=05 epoch 28/70: train_loss=0.9063 train_acc=0.7074 val_loss=6.2536 val_acc=0.1373 seconds=1.0
[CNN_room] Fusion/lovo fold=05 epoch 29/70: train_loss=0.8533 train_acc=0.7228 val_loss=6.5419 val_acc=0.1353 seconds=0.9
[CNN_room] Fusion/lovo fold=05 epoch 30/70: train_loss=0.8400 train_acc=0.7329 val_loss=6.3361 val_acc=0.1398 seconds=1.0
[CNN_room] Fusion/lovo fold=05 epoch 31/70: train_loss=0.8063 train_acc=0.7418 val_loss=6.1230 val_acc=0.1334 seconds=1.0
[CNN_room] Fusion/lovo fold=05 epoch 32/70: train_loss=0.8001 train_acc=0.7418 val_loss=6.1502 val_acc=0.1386 seconds=1.0
[CNN_room] Fusion/lovo fold=05 epoch 33/70: train_loss=0.7788 train_acc=0.7464 val_loss=6.3506 val_acc=0.1386 seconds=1.0
[CNN_room] Fusion/lovo fold=05 epoch 34/70: train_loss=0.7388 train_acc=0.7604 val_loss=6.2526 val_acc=0.1437 seconds=1.0
[CNN_room] Fusion/lovo fold=05 epoch 35/70: train_loss=0.7195 train_acc=0.7678 val_loss=6.7706 val_acc=0.1283 seconds=1.0
[CNN_room] early stopping at epoch 35; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn_room__fusion__lovo__ebl-session__s42__dc4ee3__fold-05.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn_room__fusion__lovo__ebl-session__s42__dc4ee3/training_curves__fold-05.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=06 validation_user=05 (entire user, deterministic rotation)
[CNN_room] Fusion/lovo fold=06 parameters=195636
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN_room] Fusion/lovo fold=06 epoch 01/70: train_loss=3.7526 train_acc=0.0797 val_loss=3.9069 val_acc=0.0599 seconds=3.5
[CNN_room] Fusion/lovo fold=06 epoch 02/70: train_loss=3.1020 train_acc=0.1551 val_loss=3.8110 val_acc=0.1380 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 03/70: train_loss=2.7537 train_acc=0.2143 val_loss=3.7217 val_acc=0.1555 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 04/70: train_loss=2.5441 train_acc=0.2599 val_loss=3.3520 val_acc=0.1898 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 05/70: train_loss=2.3698 train_acc=0.2965 val_loss=3.2859 val_acc=0.2106 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 06/70: train_loss=2.2269 train_acc=0.3297 val_loss=3.3451 val_acc=0.1817 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 07/70: train_loss=2.1118 train_acc=0.3685 val_loss=3.0504 val_acc=0.2308 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 08/70: train_loss=1.9976 train_acc=0.4027 val_loss=3.1501 val_acc=0.1851 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 09/70: train_loss=1.8826 train_acc=0.4199 val_loss=3.2930 val_acc=0.2201 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 10/70: train_loss=1.7878 train_acc=0.4534 val_loss=3.2653 val_acc=0.2207 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 11/70: train_loss=1.7075 train_acc=0.4738 val_loss=3.4704 val_acc=0.1999 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 12/70: train_loss=1.6152 train_acc=0.5126 val_loss=3.2012 val_acc=0.2174 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 13/70: train_loss=1.5331 train_acc=0.5268 val_loss=3.4419 val_acc=0.2133 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 14/70: train_loss=1.4697 train_acc=0.5499 val_loss=3.2996 val_acc=0.2248 seconds=0.9
[CNN_room] Fusion/lovo fold=06 epoch 15/70: train_loss=1.3944 train_acc=0.5648 val_loss=3.5438 val_acc=0.2100 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 16/70: train_loss=1.3496 train_acc=0.5738 val_loss=3.9507 val_acc=0.2335 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 17/70: train_loss=1.3106 train_acc=0.5962 val_loss=3.6070 val_acc=0.2369 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 18/70: train_loss=1.2318 train_acc=0.6119 val_loss=3.8458 val_acc=0.2369 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 19/70: train_loss=1.1716 train_acc=0.6330 val_loss=3.5191 val_acc=0.2638 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 20/70: train_loss=1.1519 train_acc=0.6376 val_loss=4.0301 val_acc=0.2389 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 21/70: train_loss=1.0857 train_acc=0.6618 val_loss=4.4603 val_acc=0.2201 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 22/70: train_loss=1.0701 train_acc=0.6631 val_loss=4.3512 val_acc=0.2207 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 23/70: train_loss=0.9964 train_acc=0.6804 val_loss=3.9493 val_acc=0.2584 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 24/70: train_loss=0.9501 train_acc=0.6997 val_loss=4.4031 val_acc=0.2268 seconds=1.1
[CNN_room] Fusion/lovo fold=06 epoch 25/70: train_loss=0.9238 train_acc=0.7082 val_loss=3.9620 val_acc=0.2443 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 26/70: train_loss=0.9096 train_acc=0.7071 val_loss=4.7445 val_acc=0.2362 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 27/70: train_loss=0.8722 train_acc=0.7198 val_loss=4.2908 val_acc=0.2463 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 28/70: train_loss=0.8418 train_acc=0.7319 val_loss=4.2768 val_acc=0.2429 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 29/70: train_loss=0.8215 train_acc=0.7368 val_loss=5.2358 val_acc=0.2140 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 30/70: train_loss=0.7893 train_acc=0.7494 val_loss=4.4858 val_acc=0.2254 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 31/70: train_loss=0.7626 train_acc=0.7516 val_loss=4.7213 val_acc=0.2369 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 32/70: train_loss=0.7432 train_acc=0.7645 val_loss=4.7088 val_acc=0.2510 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 33/70: train_loss=0.7088 train_acc=0.7720 val_loss=5.2295 val_acc=0.2207 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 34/70: train_loss=0.7044 train_acc=0.7710 val_loss=5.0568 val_acc=0.2423 seconds=1.0
[CNN_room] early stopping at epoch 34; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn_room__fusion__lovo__ebl-session__s42__dc4ee3__fold-06.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn_room__fusion__lovo__ebl-session__s42__dc4ee3/training_curves__fold-06.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn_room__fusion__lovo__ebl-session__s42__dc4ee3.parquet
[results upsert] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/runs_folds.csv: 60 row(s)
[DL LOVO] seed=42 fold mean position_accuracy=0.1207 +/- 0.0518; pooled=0.1222
[DL GPU] run_id=dl__cnn_room__fusion__lovo__ebl-session__s42__dc4ee3 peak_cuda_memory_bytes=2685729792
[results upsert] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/runs.csv: 40 row(s)
Seeds: random=43, numpy=43, torch=43
[trial filter] split=lovo trials=['01'] kept=8889/13568
[trial filter] split=lovo trials=['01'] kept=8889/8889
[protocol] split=lovo fold=01 trials_used=['01'] n_train=7331 n_test=1558 users=['01', '02', '03', '04', '05', '06'] train_users=['02', '03', '04', '05', '06'] test_users=['01']
[protocol] split=lovo fold=02 trials_used=['01'] n_train=7478 n_test=1411 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '03', '04', '05', '06'] test_users=['02']
[protocol] split=lovo fold=03 trials_used=['01'] n_train=7303 n_test=1586 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '04', '05', '06'] test_users=['03']
[protocol] split=lovo fold=04 trials_used=['01'] n_train=7330 n_test=1559 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '05', '06'] test_users=['04']
[protocol] split=lovo fold=05 trials_used=['01'] n_train=7403 n_test=1486 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '06'] test_users=['05']
[protocol] split=lovo fold=06 trials_used=['01'] n_train=7600 n_test=1289 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05'] test_users=['06']
[DL LOVO] held_out_user=01 validation_user=06 (entire user, deterministic rotation)
[CNN_room] Fusion/lovo fold=01 parameters=195636
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN_room] Fusion/lovo fold=01 epoch 01/70: train_loss=3.7814 train_acc=0.0846 val_loss=3.7940 val_acc=0.0659 seconds=3.3
[CNN_room] Fusion/lovo fold=01 epoch 02/70: train_loss=3.0989 train_acc=0.1802 val_loss=3.4128 val_acc=0.1086 seconds=1.0
[CNN_room] Fusion/lovo fold=01 epoch 03/70: train_loss=2.6271 train_acc=0.2479 val_loss=3.3113 val_acc=0.1567 seconds=1.0
[CNN_room] Fusion/lovo fold=01 epoch 04/70: train_loss=2.3907 train_acc=0.3024 val_loss=3.2598 val_acc=0.1746 seconds=1.0
[CNN_room] Fusion/lovo fold=01 epoch 05/70: train_loss=2.2237 train_acc=0.3279 val_loss=3.4410 val_acc=0.1458 seconds=1.0
[CNN_room] Fusion/lovo fold=01 epoch 06/70: train_loss=2.1020 train_acc=0.3649 val_loss=3.4616 val_acc=0.1575 seconds=1.0
[CNN_room] Fusion/lovo fold=01 epoch 07/70: train_loss=1.9771 train_acc=0.3954 val_loss=3.6772 val_acc=0.1389 seconds=1.0
[CNN_room] Fusion/lovo fold=01 epoch 08/70: train_loss=1.8842 train_acc=0.4280 val_loss=3.9254 val_acc=0.1474 seconds=0.9
[CNN_room] Fusion/lovo fold=01 epoch 09/70: train_loss=1.7856 train_acc=0.4573 val_loss=4.0931 val_acc=0.1652 seconds=1.0
[CNN_room] Fusion/lovo fold=01 epoch 10/70: train_loss=1.7186 train_acc=0.4634 val_loss=4.1173 val_acc=0.1536 seconds=1.0
[CNN_room] Fusion/lovo fold=01 epoch 11/70: train_loss=1.6299 train_acc=0.4904 val_loss=4.4085 val_acc=0.1342 seconds=0.9
[CNN_room] Fusion/lovo fold=01 epoch 12/70: train_loss=1.5279 train_acc=0.5266 val_loss=4.6620 val_acc=0.1575 seconds=1.0
[CNN_room] Fusion/lovo fold=01 epoch 13/70: train_loss=1.4895 train_acc=0.5362 val_loss=4.6066 val_acc=0.1164 seconds=0.9
[CNN_room] Fusion/lovo fold=01 epoch 14/70: train_loss=1.4072 train_acc=0.5631 val_loss=5.0393 val_acc=0.1389 seconds=1.0
[CNN_room] Fusion/lovo fold=01 epoch 15/70: train_loss=1.3500 train_acc=0.5710 val_loss=5.1638 val_acc=0.1148 seconds=1.0
[CNN_room] Fusion/lovo fold=01 epoch 16/70: train_loss=1.2832 train_acc=0.5978 val_loss=5.0233 val_acc=0.1365 seconds=1.0
[CNN_room] Fusion/lovo fold=01 epoch 17/70: train_loss=1.2333 train_acc=0.6170 val_loss=5.6146 val_acc=0.1404 seconds=1.0
[CNN_room] Fusion/lovo fold=01 epoch 18/70: train_loss=1.1912 train_acc=0.6235 val_loss=5.4603 val_acc=0.1342 seconds=1.0
[CNN_room] Fusion/lovo fold=01 epoch 19/70: train_loss=1.1266 train_acc=0.6493 val_loss=5.4549 val_acc=0.1319 seconds=1.0
[CNN_room] early stopping at epoch 19; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn_room__fusion__lovo__ebl-session__s43__08cc8f__fold-01.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn_room__fusion__lovo__ebl-session__s43__08cc8f/training_curves__fold-01.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=02 validation_user=01 (entire user, deterministic rotation)
[CNN_room] Fusion/lovo fold=02 parameters=195636
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN_room] Fusion/lovo fold=02 epoch 01/70: train_loss=3.7375 train_acc=0.1052 val_loss=3.8574 val_acc=0.0353 seconds=3.7
[CNN_room] Fusion/lovo fold=02 epoch 02/70: train_loss=2.9604 train_acc=0.2110 val_loss=5.1737 val_acc=0.0905 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 03/70: train_loss=2.5024 train_acc=0.2774 val_loss=6.3451 val_acc=0.1040 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 04/70: train_loss=2.2765 train_acc=0.3187 val_loss=6.4922 val_acc=0.1245 seconds=0.9
[CNN_room] Fusion/lovo fold=02 epoch 05/70: train_loss=2.1473 train_acc=0.3522 val_loss=7.3043 val_acc=0.1175 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 06/70: train_loss=2.0135 train_acc=0.3872 val_loss=8.1810 val_acc=0.1136 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 07/70: train_loss=1.9074 train_acc=0.4123 val_loss=7.3689 val_acc=0.1393 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 08/70: train_loss=1.8013 train_acc=0.4529 val_loss=7.7843 val_acc=0.1329 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 09/70: train_loss=1.7380 train_acc=0.4666 val_loss=7.7930 val_acc=0.1271 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 10/70: train_loss=1.6338 train_acc=0.4944 val_loss=7.4885 val_acc=0.1354 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 11/70: train_loss=1.5340 train_acc=0.5301 val_loss=8.1670 val_acc=0.1245 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 12/70: train_loss=1.4936 train_acc=0.5377 val_loss=7.7502 val_acc=0.1309 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 13/70: train_loss=1.4104 train_acc=0.5618 val_loss=8.4768 val_acc=0.1335 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 14/70: train_loss=1.3542 train_acc=0.5750 val_loss=8.6966 val_acc=0.1335 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 15/70: train_loss=1.2846 train_acc=0.5946 val_loss=7.7281 val_acc=0.1463 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 16/70: train_loss=1.2674 train_acc=0.5971 val_loss=8.8633 val_acc=0.1412 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 17/70: train_loss=1.1744 train_acc=0.6260 val_loss=9.3600 val_acc=0.1341 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 18/70: train_loss=1.1622 train_acc=0.6323 val_loss=9.7605 val_acc=0.1354 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 19/70: train_loss=1.0775 train_acc=0.6556 val_loss=9.8365 val_acc=0.1271 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 20/70: train_loss=1.0310 train_acc=0.6785 val_loss=9.6560 val_acc=0.1341 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 21/70: train_loss=0.9797 train_acc=0.6905 val_loss=11.1972 val_acc=0.1284 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 22/70: train_loss=0.9618 train_acc=0.6919 val_loss=9.7400 val_acc=0.1290 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 23/70: train_loss=0.9169 train_acc=0.7083 val_loss=9.7596 val_acc=0.1502 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 24/70: train_loss=0.8858 train_acc=0.7088 val_loss=10.4386 val_acc=0.1361 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 25/70: train_loss=0.8976 train_acc=0.7130 val_loss=10.2277 val_acc=0.1290 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 26/70: train_loss=0.8581 train_acc=0.7226 val_loss=10.5639 val_acc=0.1297 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 27/70: train_loss=0.8212 train_acc=0.7345 val_loss=10.0814 val_acc=0.1412 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 28/70: train_loss=0.7912 train_acc=0.7443 val_loss=10.1701 val_acc=0.1361 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 29/70: train_loss=0.7799 train_acc=0.7465 val_loss=11.0023 val_acc=0.1361 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 30/70: train_loss=0.8040 train_acc=0.7443 val_loss=10.5739 val_acc=0.1386 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 31/70: train_loss=0.7212 train_acc=0.7627 val_loss=12.0215 val_acc=0.1252 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 32/70: train_loss=0.7190 train_acc=0.7676 val_loss=11.0905 val_acc=0.1329 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 33/70: train_loss=0.6878 train_acc=0.7767 val_loss=11.0882 val_acc=0.1425 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 34/70: train_loss=0.6920 train_acc=0.7792 val_loss=10.3285 val_acc=0.1483 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 35/70: train_loss=0.6406 train_acc=0.7895 val_loss=10.3351 val_acc=0.1463 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 36/70: train_loss=0.6305 train_acc=0.7970 val_loss=10.1721 val_acc=0.1496 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 37/70: train_loss=0.6194 train_acc=0.8002 val_loss=10.9748 val_acc=0.1431 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 38/70: train_loss=0.5967 train_acc=0.8020 val_loss=11.1862 val_acc=0.1534 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 39/70: train_loss=0.6267 train_acc=0.7971 val_loss=11.9157 val_acc=0.1425 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 40/70: train_loss=0.5976 train_acc=0.8052 val_loss=10.7507 val_acc=0.1483 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 41/70: train_loss=0.5778 train_acc=0.8117 val_loss=11.9802 val_acc=0.1412 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 42/70: train_loss=0.5577 train_acc=0.8203 val_loss=10.8226 val_acc=0.1386 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 43/70: train_loss=0.5274 train_acc=0.8279 val_loss=12.0187 val_acc=0.1393 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 44/70: train_loss=0.5247 train_acc=0.8270 val_loss=10.8075 val_acc=0.1451 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 45/70: train_loss=0.5213 train_acc=0.8326 val_loss=11.2464 val_acc=0.1431 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 46/70: train_loss=0.5221 train_acc=0.8270 val_loss=11.1334 val_acc=0.1560 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 47/70: train_loss=0.4966 train_acc=0.8400 val_loss=12.2477 val_acc=0.1393 seconds=0.9
[CNN_room] Fusion/lovo fold=02 epoch 48/70: train_loss=0.5269 train_acc=0.8294 val_loss=10.7654 val_acc=0.1560 seconds=0.9
[CNN_room] Fusion/lovo fold=02 epoch 49/70: train_loss=0.5201 train_acc=0.8341 val_loss=12.2017 val_acc=0.1489 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 50/70: train_loss=0.4780 train_acc=0.8448 val_loss=12.5013 val_acc=0.1354 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 51/70: train_loss=0.4619 train_acc=0.8483 val_loss=12.0031 val_acc=0.1444 seconds=0.9
[CNN_room] Fusion/lovo fold=02 epoch 52/70: train_loss=0.4440 train_acc=0.8551 val_loss=12.4850 val_acc=0.1489 seconds=0.9
[CNN_room] Fusion/lovo fold=02 epoch 53/70: train_loss=0.4381 train_acc=0.8544 val_loss=11.8537 val_acc=0.1502 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 54/70: train_loss=0.4435 train_acc=0.8557 val_loss=11.8545 val_acc=0.1457 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 55/70: train_loss=0.4354 train_acc=0.8576 val_loss=11.9344 val_acc=0.1393 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 56/70: train_loss=0.4268 train_acc=0.8571 val_loss=11.7836 val_acc=0.1534 seconds=0.9
[CNN_room] Fusion/lovo fold=02 epoch 57/70: train_loss=0.4027 train_acc=0.8671 val_loss=12.9843 val_acc=0.1425 seconds=0.9
[CNN_room] Fusion/lovo fold=02 epoch 58/70: train_loss=0.4515 train_acc=0.8497 val_loss=12.5915 val_acc=0.1444 seconds=0.9
[CNN_room] Fusion/lovo fold=02 epoch 59/70: train_loss=0.4230 train_acc=0.8601 val_loss=13.3627 val_acc=0.1489 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 60/70: train_loss=0.4031 train_acc=0.8660 val_loss=13.0252 val_acc=0.1438 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 61/70: train_loss=0.3724 train_acc=0.8765 val_loss=13.2254 val_acc=0.1489 seconds=1.0
[CNN_room] early stopping at epoch 61; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn_room__fusion__lovo__ebl-session__s43__08cc8f__fold-02.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn_room__fusion__lovo__ebl-session__s43__08cc8f/training_curves__fold-02.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=03 validation_user=02 (entire user, deterministic rotation)
[CNN_room] Fusion/lovo fold=03 parameters=195636
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN_room] Fusion/lovo fold=03 epoch 01/70: train_loss=3.7374 train_acc=0.0988 val_loss=3.7252 val_acc=0.0822 seconds=3.7
[CNN_room] Fusion/lovo fold=03 epoch 02/70: train_loss=3.0695 train_acc=0.1835 val_loss=3.8350 val_acc=0.0560 seconds=1.0
[CNN_room] Fusion/lovo fold=03 epoch 03/70: train_loss=2.6709 train_acc=0.2396 val_loss=4.2620 val_acc=0.0539 seconds=1.0
[CNN_room] Fusion/lovo fold=03 epoch 04/70: train_loss=2.4443 train_acc=0.2929 val_loss=4.3378 val_acc=0.0695 seconds=1.0
[CNN_room] Fusion/lovo fold=03 epoch 05/70: train_loss=2.2594 train_acc=0.3286 val_loss=4.8930 val_acc=0.0652 seconds=0.9
[CNN_room] Fusion/lovo fold=03 epoch 06/70: train_loss=2.1542 train_acc=0.3508 val_loss=4.8208 val_acc=0.0673 seconds=1.0
[CNN_room] Fusion/lovo fold=03 epoch 07/70: train_loss=2.0654 train_acc=0.3736 val_loss=5.3147 val_acc=0.0624 seconds=1.0
[CNN_room] Fusion/lovo fold=03 epoch 08/70: train_loss=2.0032 train_acc=0.3987 val_loss=5.8346 val_acc=0.0581 seconds=1.0
[CNN_room] Fusion/lovo fold=03 epoch 09/70: train_loss=1.8968 train_acc=0.4262 val_loss=5.6382 val_acc=0.0574 seconds=1.0
[CNN_room] Fusion/lovo fold=03 epoch 10/70: train_loss=1.7892 train_acc=0.4552 val_loss=6.0621 val_acc=0.0524 seconds=1.0
[CNN_room] Fusion/lovo fold=03 epoch 11/70: train_loss=1.7645 train_acc=0.4506 val_loss=6.2069 val_acc=0.0560 seconds=1.0
[CNN_room] Fusion/lovo fold=03 epoch 12/70: train_loss=1.6680 train_acc=0.4876 val_loss=6.4106 val_acc=0.0532 seconds=1.0
[CNN_room] Fusion/lovo fold=03 epoch 13/70: train_loss=1.5581 train_acc=0.5231 val_loss=6.7165 val_acc=0.0517 seconds=1.0
[CNN_room] Fusion/lovo fold=03 epoch 14/70: train_loss=1.5069 train_acc=0.5380 val_loss=6.4541 val_acc=0.0539 seconds=1.0
[CNN_room] Fusion/lovo fold=03 epoch 15/70: train_loss=1.4974 train_acc=0.5343 val_loss=6.8012 val_acc=0.0546 seconds=1.0
[CNN_room] Fusion/lovo fold=03 epoch 16/70: train_loss=1.3996 train_acc=0.5684 val_loss=6.8078 val_acc=0.0631 seconds=1.0
[CNN_room] early stopping at epoch 16; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn_room__fusion__lovo__ebl-session__s43__08cc8f__fold-03.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn_room__fusion__lovo__ebl-session__s43__08cc8f/training_curves__fold-03.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=04 validation_user=03 (entire user, deterministic rotation)
[CNN_room] Fusion/lovo fold=04 parameters=195636
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN_room] Fusion/lovo fold=04 epoch 01/70: train_loss=3.7945 train_acc=0.0763 val_loss=3.8092 val_acc=0.0750 seconds=3.6
[CNN_room] Fusion/lovo fold=04 epoch 02/70: train_loss=3.1686 train_acc=0.1586 val_loss=3.3653 val_acc=0.1356 seconds=1.0
[CNN_room] Fusion/lovo fold=04 epoch 03/70: train_loss=2.7315 train_acc=0.2140 val_loss=3.5109 val_acc=0.1198 seconds=0.9
[CNN_room] Fusion/lovo fold=04 epoch 04/70: train_loss=2.4686 train_acc=0.2794 val_loss=3.7343 val_acc=0.1330 seconds=1.0
[CNN_room] Fusion/lovo fold=04 epoch 05/70: train_loss=2.2775 train_acc=0.3261 val_loss=3.8778 val_acc=0.1154 seconds=0.9
[CNN_room] Fusion/lovo fold=04 epoch 06/70: train_loss=2.0976 train_acc=0.3684 val_loss=4.0804 val_acc=0.1242 seconds=1.0
[CNN_room] Fusion/lovo fold=04 epoch 07/70: train_loss=1.9570 train_acc=0.4131 val_loss=4.2974 val_acc=0.1211 seconds=1.0
[CNN_room] Fusion/lovo fold=04 epoch 08/70: train_loss=1.8313 train_acc=0.4474 val_loss=4.5510 val_acc=0.1116 seconds=0.9
[CNN_room] Fusion/lovo fold=04 epoch 09/70: train_loss=1.7409 train_acc=0.4702 val_loss=4.7072 val_acc=0.1009 seconds=1.0
[CNN_room] Fusion/lovo fold=04 epoch 10/70: train_loss=1.6140 train_acc=0.5092 val_loss=4.7875 val_acc=0.1135 seconds=0.9
[CNN_room] Fusion/lovo fold=04 epoch 11/70: train_loss=1.5307 train_acc=0.5339 val_loss=5.0399 val_acc=0.1223 seconds=0.9
[CNN_room] Fusion/lovo fold=04 epoch 12/70: train_loss=1.4599 train_acc=0.5487 val_loss=5.2843 val_acc=0.1154 seconds=1.0
[CNN_room] Fusion/lovo fold=04 epoch 13/70: train_loss=1.3952 train_acc=0.5616 val_loss=5.1882 val_acc=0.1179 seconds=1.0
[CNN_room] Fusion/lovo fold=04 epoch 14/70: train_loss=1.3108 train_acc=0.5935 val_loss=5.3224 val_acc=0.1179 seconds=0.9
[CNN_room] Fusion/lovo fold=04 epoch 15/70: train_loss=1.2454 train_acc=0.6109 val_loss=5.3712 val_acc=0.1154 seconds=0.9
[CNN_room] Fusion/lovo fold=04 epoch 16/70: train_loss=1.1767 train_acc=0.6294 val_loss=5.7904 val_acc=0.1154 seconds=1.0
[CNN_room] Fusion/lovo fold=04 epoch 17/70: train_loss=1.1419 train_acc=0.6495 val_loss=5.6856 val_acc=0.1122 seconds=0.9
[CNN_room] early stopping at epoch 17; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn_room__fusion__lovo__ebl-session__s43__08cc8f__fold-04.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn_room__fusion__lovo__ebl-session__s43__08cc8f/training_curves__fold-04.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=05 validation_user=04 (entire user, deterministic rotation)
[CNN_room] Fusion/lovo fold=05 parameters=195636
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN_room] Fusion/lovo fold=05 epoch 01/70: train_loss=3.7475 train_acc=0.0717 val_loss=3.8874 val_acc=0.0738 seconds=3.6
[CNN_room] Fusion/lovo fold=05 epoch 02/70: train_loss=3.0849 train_acc=0.1526 val_loss=3.8717 val_acc=0.0943 seconds=1.0
[CNN_room] Fusion/lovo fold=05 epoch 03/70: train_loss=2.7407 train_acc=0.2148 val_loss=3.6027 val_acc=0.1058 seconds=1.0
[CNN_room] Fusion/lovo fold=05 epoch 04/70: train_loss=2.5248 train_acc=0.2640 val_loss=3.8561 val_acc=0.1167 seconds=1.0
[CNN_room] Fusion/lovo fold=05 epoch 05/70: train_loss=2.3651 train_acc=0.2969 val_loss=4.0126 val_acc=0.1289 seconds=0.9
[CNN_room] Fusion/lovo fold=05 epoch 06/70: train_loss=2.2162 train_acc=0.3350 val_loss=4.1695 val_acc=0.1212 seconds=1.0
[CNN_room] Fusion/lovo fold=05 epoch 07/70: train_loss=2.0973 train_acc=0.3626 val_loss=4.1570 val_acc=0.1386 seconds=0.9
[CNN_room] Fusion/lovo fold=05 epoch 08/70: train_loss=1.9836 train_acc=0.3948 val_loss=4.3035 val_acc=0.1373 seconds=1.0
[CNN_room] Fusion/lovo fold=05 epoch 09/70: train_loss=1.8796 train_acc=0.4194 val_loss=4.5268 val_acc=0.1264 seconds=1.0
[CNN_room] Fusion/lovo fold=05 epoch 10/70: train_loss=1.8098 train_acc=0.4425 val_loss=4.4795 val_acc=0.1309 seconds=1.0
[CNN_room] Fusion/lovo fold=05 epoch 11/70: train_loss=1.7003 train_acc=0.4689 val_loss=4.7093 val_acc=0.1495 seconds=1.0
[CNN_room] Fusion/lovo fold=05 epoch 12/70: train_loss=1.6072 train_acc=0.5005 val_loss=4.6198 val_acc=0.1424 seconds=1.0
[CNN_room] Fusion/lovo fold=05 epoch 13/70: train_loss=1.5465 train_acc=0.5284 val_loss=4.9971 val_acc=0.1398 seconds=1.0
[CNN_room] Fusion/lovo fold=05 epoch 14/70: train_loss=1.4620 train_acc=0.5459 val_loss=5.0830 val_acc=0.1495 seconds=1.0
[CNN_room] Fusion/lovo fold=05 epoch 15/70: train_loss=1.3818 train_acc=0.5741 val_loss=5.1674 val_acc=0.1437 seconds=1.0
[CNN_room] Fusion/lovo fold=05 epoch 16/70: train_loss=1.3285 train_acc=0.5837 val_loss=5.2869 val_acc=0.1488 seconds=1.0
[CNN_room] Fusion/lovo fold=05 epoch 17/70: train_loss=1.2922 train_acc=0.5849 val_loss=5.2733 val_acc=0.1443 seconds=1.0
[CNN_room] Fusion/lovo fold=05 epoch 18/70: train_loss=1.2317 train_acc=0.6165 val_loss=5.8270 val_acc=0.1193 seconds=1.0
[CNN_room] Fusion/lovo fold=05 epoch 19/70: train_loss=1.1941 train_acc=0.6261 val_loss=5.7463 val_acc=0.1321 seconds=1.0
[CNN_room] Fusion/lovo fold=05 epoch 20/70: train_loss=1.1320 train_acc=0.6465 val_loss=5.5992 val_acc=0.1296 seconds=1.0
[CNN_room] Fusion/lovo fold=05 epoch 21/70: train_loss=1.0658 train_acc=0.6643 val_loss=6.1214 val_acc=0.1212 seconds=1.0
[CNN_room] Fusion/lovo fold=05 epoch 22/70: train_loss=1.0462 train_acc=0.6602 val_loss=6.0069 val_acc=0.1206 seconds=1.0
[CNN_room] Fusion/lovo fold=05 epoch 23/70: train_loss=1.0033 train_acc=0.6831 val_loss=6.4763 val_acc=0.1309 seconds=1.0
[CNN_room] Fusion/lovo fold=05 epoch 24/70: train_loss=0.9789 train_acc=0.6875 val_loss=5.9242 val_acc=0.1386 seconds=0.9
[CNN_room] Fusion/lovo fold=05 epoch 25/70: train_loss=0.9228 train_acc=0.7067 val_loss=6.2385 val_acc=0.1309 seconds=0.9
[CNN_room] Fusion/lovo fold=05 epoch 26/70: train_loss=0.9033 train_acc=0.7125 val_loss=6.4258 val_acc=0.1244 seconds=1.0
[CNN_room] early stopping at epoch 26; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn_room__fusion__lovo__ebl-session__s43__08cc8f__fold-05.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn_room__fusion__lovo__ebl-session__s43__08cc8f/training_curves__fold-05.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=06 validation_user=05 (entire user, deterministic rotation)
[CNN_room] Fusion/lovo fold=06 parameters=195636
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN_room] Fusion/lovo fold=06 epoch 01/70: train_loss=3.7387 train_acc=0.0720 val_loss=3.8528 val_acc=0.0572 seconds=3.7
[CNN_room] Fusion/lovo fold=06 epoch 02/70: train_loss=3.0665 train_acc=0.1688 val_loss=3.6512 val_acc=0.1548 seconds=0.9
[CNN_room] Fusion/lovo fold=06 epoch 03/70: train_loss=2.6922 train_acc=0.2208 val_loss=3.3256 val_acc=0.1770 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 04/70: train_loss=2.4756 train_acc=0.2686 val_loss=3.3310 val_acc=0.1925 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 05/70: train_loss=2.3108 train_acc=0.3104 val_loss=2.9165 val_acc=0.2066 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 06/70: train_loss=2.1731 train_acc=0.3451 val_loss=2.9526 val_acc=0.2241 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 07/70: train_loss=2.0527 train_acc=0.3798 val_loss=2.9683 val_acc=0.2153 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 08/70: train_loss=1.9393 train_acc=0.4099 val_loss=3.1575 val_acc=0.2100 seconds=1.1
[CNN_room] Fusion/lovo fold=06 epoch 09/70: train_loss=1.8604 train_acc=0.4310 val_loss=3.0188 val_acc=0.2086 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 10/70: train_loss=1.7658 train_acc=0.4621 val_loss=3.1194 val_acc=0.2066 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 11/70: train_loss=1.6590 train_acc=0.4938 val_loss=3.8359 val_acc=0.1824 seconds=0.9
[CNN_room] Fusion/lovo fold=06 epoch 12/70: train_loss=1.5847 train_acc=0.5168 val_loss=3.4571 val_acc=0.2079 seconds=0.9
[CNN_room] Fusion/lovo fold=06 epoch 13/70: train_loss=1.5227 train_acc=0.5288 val_loss=3.4861 val_acc=0.1952 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 14/70: train_loss=1.4488 train_acc=0.5465 val_loss=3.6446 val_acc=0.2012 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 15/70: train_loss=1.3757 train_acc=0.5744 val_loss=3.7199 val_acc=0.1978 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 16/70: train_loss=1.2978 train_acc=0.5998 val_loss=3.3374 val_acc=0.1965 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 17/70: train_loss=1.2545 train_acc=0.6070 val_loss=3.9319 val_acc=0.1878 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 18/70: train_loss=1.2040 train_acc=0.6243 val_loss=3.8444 val_acc=0.2201 seconds=0.9
[CNN_room] Fusion/lovo fold=06 epoch 19/70: train_loss=1.1976 train_acc=0.6181 val_loss=4.0984 val_acc=0.1864 seconds=0.9
[CNN_room] Fusion/lovo fold=06 epoch 20/70: train_loss=1.1221 train_acc=0.6510 val_loss=3.9571 val_acc=0.2214 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 21/70: train_loss=1.0931 train_acc=0.6528 val_loss=4.3136 val_acc=0.1999 seconds=1.0
[CNN_room] early stopping at epoch 21; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn_room__fusion__lovo__ebl-session__s43__08cc8f__fold-06.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn_room__fusion__lovo__ebl-session__s43__08cc8f/training_curves__fold-06.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn_room__fusion__lovo__ebl-session__s43__08cc8f.parquet
[results upsert] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/runs_folds.csv: 66 row(s)
[DL LOVO] seed=43 fold mean position_accuracy=0.1067 +/- 0.0395; pooled=0.1070
[DL GPU] run_id=dl__cnn_room__fusion__lovo__ebl-session__s43__08cc8f peak_cuda_memory_bytes=2685729792
[results upsert] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/runs.csv: 41 row(s)
Seeds: random=44, numpy=44, torch=44
[trial filter] split=lovo trials=['01'] kept=8889/13568
[trial filter] split=lovo trials=['01'] kept=8889/8889
[protocol] split=lovo fold=01 trials_used=['01'] n_train=7331 n_test=1558 users=['01', '02', '03', '04', '05', '06'] train_users=['02', '03', '04', '05', '06'] test_users=['01']
[protocol] split=lovo fold=02 trials_used=['01'] n_train=7478 n_test=1411 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '03', '04', '05', '06'] test_users=['02']
[protocol] split=lovo fold=03 trials_used=['01'] n_train=7303 n_test=1586 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '04', '05', '06'] test_users=['03']
[protocol] split=lovo fold=04 trials_used=['01'] n_train=7330 n_test=1559 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '05', '06'] test_users=['04']
[protocol] split=lovo fold=05 trials_used=['01'] n_train=7403 n_test=1486 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '06'] test_users=['05']
[protocol] split=lovo fold=06 trials_used=['01'] n_train=7600 n_test=1289 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05'] test_users=['06']
[DL LOVO] held_out_user=01 validation_user=06 (entire user, deterministic rotation)
[CNN_room] Fusion/lovo fold=01 parameters=195636
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN_room] Fusion/lovo fold=01 epoch 01/70: train_loss=3.7494 train_acc=0.0884 val_loss=3.7670 val_acc=0.0434 seconds=3.7
[CNN_room] Fusion/lovo fold=01 epoch 02/70: train_loss=3.0664 train_acc=0.1807 val_loss=3.4750 val_acc=0.0939 seconds=1.0
[CNN_room] Fusion/lovo fold=01 epoch 03/70: train_loss=2.6067 train_acc=0.2521 val_loss=3.6910 val_acc=0.1094 seconds=1.0
[CNN_room] Fusion/lovo fold=01 epoch 04/70: train_loss=2.3796 train_acc=0.2986 val_loss=3.6667 val_acc=0.1063 seconds=1.0
[CNN_room] Fusion/lovo fold=01 epoch 05/70: train_loss=2.2197 train_acc=0.3375 val_loss=3.7800 val_acc=0.1396 seconds=1.0
[CNN_room] Fusion/lovo fold=01 epoch 06/70: train_loss=2.0885 train_acc=0.3737 val_loss=3.7317 val_acc=0.1234 seconds=1.0
[CNN_room] Fusion/lovo fold=01 epoch 07/70: train_loss=1.9784 train_acc=0.3967 val_loss=3.8859 val_acc=0.1559 seconds=1.0
[CNN_room] Fusion/lovo fold=01 epoch 08/70: train_loss=1.8946 train_acc=0.4232 val_loss=4.1039 val_acc=0.1327 seconds=1.0
[CNN_room] Fusion/lovo fold=01 epoch 09/70: train_loss=1.7911 train_acc=0.4490 val_loss=3.9372 val_acc=0.1505 seconds=1.0
[CNN_room] Fusion/lovo fold=01 epoch 10/70: train_loss=1.6933 train_acc=0.4788 val_loss=4.2751 val_acc=0.1443 seconds=1.0
[CNN_room] Fusion/lovo fold=01 epoch 11/70: train_loss=1.6145 train_acc=0.5036 val_loss=4.2081 val_acc=0.1358 seconds=1.0
[CNN_room] Fusion/lovo fold=01 epoch 12/70: train_loss=1.5459 train_acc=0.5230 val_loss=4.1570 val_acc=0.1808 seconds=1.0
[CNN_room] Fusion/lovo fold=01 epoch 13/70: train_loss=1.4544 train_acc=0.5468 val_loss=4.8541 val_acc=0.1427 seconds=1.0
[CNN_room] Fusion/lovo fold=01 epoch 14/70: train_loss=1.4084 train_acc=0.5607 val_loss=4.8245 val_acc=0.1133 seconds=1.0
[CNN_room] Fusion/lovo fold=01 epoch 15/70: train_loss=1.3453 train_acc=0.5834 val_loss=4.7572 val_acc=0.1241 seconds=0.9
[CNN_room] Fusion/lovo fold=01 epoch 16/70: train_loss=1.2887 train_acc=0.5965 val_loss=5.1401 val_acc=0.1187 seconds=0.9
[CNN_room] Fusion/lovo fold=01 epoch 17/70: train_loss=1.2324 train_acc=0.6210 val_loss=4.9797 val_acc=0.1497 seconds=0.9
[CNN_room] Fusion/lovo fold=01 epoch 18/70: train_loss=1.1916 train_acc=0.6193 val_loss=5.0674 val_acc=0.1342 seconds=0.9
[CNN_room] Fusion/lovo fold=01 epoch 19/70: train_loss=1.1454 train_acc=0.6344 val_loss=5.3889 val_acc=0.1350 seconds=0.9
[CNN_room] Fusion/lovo fold=01 epoch 20/70: train_loss=1.0973 train_acc=0.6594 val_loss=5.3108 val_acc=0.1420 seconds=0.9
[CNN_room] Fusion/lovo fold=01 epoch 21/70: train_loss=1.0490 train_acc=0.6660 val_loss=5.2932 val_acc=0.1358 seconds=0.9
[CNN_room] Fusion/lovo fold=01 epoch 22/70: train_loss=1.0147 train_acc=0.6768 val_loss=5.8385 val_acc=0.1257 seconds=0.9
[CNN_room] Fusion/lovo fold=01 epoch 23/70: train_loss=0.9925 train_acc=0.6816 val_loss=5.6146 val_acc=0.1303 seconds=0.9
[CNN_room] Fusion/lovo fold=01 epoch 24/70: train_loss=0.9598 train_acc=0.6979 val_loss=6.0761 val_acc=0.1373 seconds=0.9
[CNN_room] Fusion/lovo fold=01 epoch 25/70: train_loss=0.9246 train_acc=0.7003 val_loss=5.8614 val_acc=0.1505 seconds=0.9
[CNN_room] Fusion/lovo fold=01 epoch 26/70: train_loss=0.9044 train_acc=0.7167 val_loss=6.1463 val_acc=0.1319 seconds=0.9
[CNN_room] Fusion/lovo fold=01 epoch 27/70: train_loss=0.8527 train_acc=0.7261 val_loss=6.3498 val_acc=0.1241 seconds=1.0
[CNN_room] early stopping at epoch 27; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn_room__fusion__lovo__ebl-session__s44__5ccebc__fold-01.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn_room__fusion__lovo__ebl-session__s44__5ccebc/training_curves__fold-01.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=02 validation_user=01 (entire user, deterministic rotation)
[CNN_room] Fusion/lovo fold=02 parameters=195636
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN_room] Fusion/lovo fold=02 epoch 01/70: train_loss=3.6987 train_acc=0.0983 val_loss=3.7901 val_acc=0.0571 seconds=3.8
[CNN_room] Fusion/lovo fold=02 epoch 02/70: train_loss=2.9376 train_acc=0.2046 val_loss=5.5924 val_acc=0.0937 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 03/70: train_loss=2.5322 train_acc=0.2601 val_loss=6.2929 val_acc=0.1168 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 04/70: train_loss=2.2826 train_acc=0.3248 val_loss=7.0992 val_acc=0.1142 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 05/70: train_loss=2.1490 train_acc=0.3466 val_loss=7.8405 val_acc=0.1142 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 06/70: train_loss=2.0095 train_acc=0.3887 val_loss=8.1381 val_acc=0.1130 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 07/70: train_loss=1.9254 train_acc=0.4101 val_loss=6.7554 val_acc=0.1181 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 08/70: train_loss=1.8451 train_acc=0.4363 val_loss=7.0392 val_acc=0.1239 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 09/70: train_loss=1.7432 train_acc=0.4593 val_loss=6.9879 val_acc=0.1284 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 10/70: train_loss=1.6790 train_acc=0.4774 val_loss=8.6976 val_acc=0.1001 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 11/70: train_loss=1.6068 train_acc=0.4993 val_loss=8.1016 val_acc=0.1239 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 12/70: train_loss=1.5291 train_acc=0.5245 val_loss=8.8200 val_acc=0.0969 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 13/70: train_loss=1.4491 train_acc=0.5556 val_loss=9.1095 val_acc=0.1168 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 14/70: train_loss=1.4008 train_acc=0.5541 val_loss=9.3837 val_acc=0.1277 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 15/70: train_loss=1.3449 train_acc=0.5840 val_loss=8.9962 val_acc=0.1322 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 16/70: train_loss=1.3282 train_acc=0.5882 val_loss=9.0304 val_acc=0.1374 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 17/70: train_loss=1.1986 train_acc=0.6252 val_loss=9.7298 val_acc=0.1329 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 18/70: train_loss=1.1638 train_acc=0.6338 val_loss=9.5452 val_acc=0.1162 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 19/70: train_loss=1.1217 train_acc=0.6429 val_loss=8.5866 val_acc=0.1354 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 20/70: train_loss=1.1039 train_acc=0.6522 val_loss=10.0855 val_acc=0.1367 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 21/70: train_loss=1.0488 train_acc=0.6605 val_loss=9.8073 val_acc=0.1316 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 22/70: train_loss=1.0062 train_acc=0.6819 val_loss=10.2608 val_acc=0.1386 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 23/70: train_loss=0.9590 train_acc=0.6939 val_loss=10.4082 val_acc=0.1418 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 24/70: train_loss=0.9109 train_acc=0.7073 val_loss=11.1409 val_acc=0.1412 seconds=1.1
[CNN_room] Fusion/lovo fold=02 epoch 25/70: train_loss=0.8787 train_acc=0.7233 val_loss=10.6111 val_acc=0.1232 seconds=1.1
[CNN_room] Fusion/lovo fold=02 epoch 26/70: train_loss=0.8533 train_acc=0.7285 val_loss=10.7454 val_acc=0.1335 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 27/70: train_loss=0.8383 train_acc=0.7304 val_loss=11.5131 val_acc=0.1303 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 28/70: train_loss=0.8192 train_acc=0.7334 val_loss=10.5138 val_acc=0.1367 seconds=1.1
[CNN_room] Fusion/lovo fold=02 epoch 29/70: train_loss=0.8063 train_acc=0.7503 val_loss=11.1659 val_acc=0.1412 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 30/70: train_loss=0.7659 train_acc=0.7497 val_loss=11.4874 val_acc=0.1213 seconds=0.9
[CNN_room] Fusion/lovo fold=02 epoch 31/70: train_loss=0.7594 train_acc=0.7547 val_loss=10.8137 val_acc=0.1220 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 32/70: train_loss=0.7555 train_acc=0.7508 val_loss=10.5031 val_acc=0.1412 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 33/70: train_loss=0.6976 train_acc=0.7767 val_loss=11.1178 val_acc=0.1425 seconds=1.1
[CNN_room] Fusion/lovo fold=02 epoch 34/70: train_loss=0.6837 train_acc=0.7760 val_loss=11.1061 val_acc=0.1431 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 35/70: train_loss=0.6627 train_acc=0.7877 val_loss=11.6410 val_acc=0.1367 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 36/70: train_loss=0.6332 train_acc=0.7889 val_loss=11.9739 val_acc=0.1341 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 37/70: train_loss=0.6321 train_acc=0.7917 val_loss=11.5043 val_acc=0.1399 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 38/70: train_loss=0.6181 train_acc=0.8008 val_loss=12.1472 val_acc=0.1483 seconds=1.1
[CNN_room] Fusion/lovo fold=02 epoch 39/70: train_loss=0.5925 train_acc=0.8041 val_loss=11.5063 val_acc=0.1399 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 40/70: train_loss=0.5809 train_acc=0.8079 val_loss=11.4800 val_acc=0.1457 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 41/70: train_loss=0.5830 train_acc=0.8041 val_loss=12.1611 val_acc=0.1502 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 42/70: train_loss=0.5595 train_acc=0.8191 val_loss=13.4708 val_acc=0.1252 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 43/70: train_loss=0.5766 train_acc=0.8057 val_loss=12.1256 val_acc=0.1489 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 44/70: train_loss=0.5255 train_acc=0.8250 val_loss=12.4497 val_acc=0.1496 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 45/70: train_loss=0.5321 train_acc=0.8262 val_loss=11.8167 val_acc=0.1528 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 46/70: train_loss=0.5016 train_acc=0.8389 val_loss=12.1187 val_acc=0.1643 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 47/70: train_loss=0.5111 train_acc=0.8389 val_loss=13.1868 val_acc=0.1451 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 48/70: train_loss=0.4913 train_acc=0.8424 val_loss=12.5591 val_acc=0.1489 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 49/70: train_loss=0.4825 train_acc=0.8419 val_loss=13.4984 val_acc=0.1297 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 50/70: train_loss=0.4920 train_acc=0.8314 val_loss=13.1637 val_acc=0.1361 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 51/70: train_loss=0.4750 train_acc=0.8458 val_loss=12.5079 val_acc=0.1451 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 52/70: train_loss=0.4600 train_acc=0.8478 val_loss=12.0365 val_acc=0.1406 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 53/70: train_loss=0.4860 train_acc=0.8361 val_loss=13.1114 val_acc=0.1418 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 54/70: train_loss=0.4690 train_acc=0.8412 val_loss=11.6589 val_acc=0.1451 seconds=0.9
[CNN_room] Fusion/lovo fold=02 epoch 55/70: train_loss=0.4590 train_acc=0.8483 val_loss=14.1221 val_acc=0.1245 seconds=0.9
[CNN_room] Fusion/lovo fold=02 epoch 56/70: train_loss=0.4282 train_acc=0.8571 val_loss=14.2305 val_acc=0.1431 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 57/70: train_loss=0.4578 train_acc=0.8465 val_loss=14.3956 val_acc=0.1367 seconds=0.9
[CNN_room] Fusion/lovo fold=02 epoch 58/70: train_loss=0.4407 train_acc=0.8534 val_loss=13.1792 val_acc=0.1425 seconds=1.0
[CNN_room] Fusion/lovo fold=02 epoch 59/70: train_loss=0.4408 train_acc=0.8551 val_loss=12.2565 val_acc=0.1540 seconds=0.9
[CNN_room] Fusion/lovo fold=02 epoch 60/70: train_loss=0.4312 train_acc=0.8571 val_loss=13.3656 val_acc=0.1393 seconds=0.9
[CNN_room] Fusion/lovo fold=02 epoch 61/70: train_loss=0.4079 train_acc=0.8630 val_loss=13.6823 val_acc=0.1380 seconds=1.0
[CNN_room] early stopping at epoch 61; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn_room__fusion__lovo__ebl-session__s44__5ccebc__fold-02.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn_room__fusion__lovo__ebl-session__s44__5ccebc/training_curves__fold-02.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=03 validation_user=02 (entire user, deterministic rotation)
[CNN_room] Fusion/lovo fold=03 parameters=195636
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN_room] Fusion/lovo fold=03 epoch 01/70: train_loss=3.7390 train_acc=0.0883 val_loss=3.7264 val_acc=0.0517 seconds=3.2
[CNN_room] Fusion/lovo fold=03 epoch 02/70: train_loss=3.0934 train_acc=0.1714 val_loss=3.9180 val_acc=0.0595 seconds=1.0
[CNN_room] Fusion/lovo fold=03 epoch 03/70: train_loss=2.6692 train_acc=0.2424 val_loss=4.2437 val_acc=0.0709 seconds=0.9
[CNN_room] Fusion/lovo fold=03 epoch 04/70: train_loss=2.4425 train_acc=0.2892 val_loss=4.5507 val_acc=0.0758 seconds=0.9
[CNN_room] Fusion/lovo fold=03 epoch 05/70: train_loss=2.2745 train_acc=0.3169 val_loss=5.0136 val_acc=0.0829 seconds=1.0
[CNN_room] Fusion/lovo fold=03 epoch 06/70: train_loss=2.1439 train_acc=0.3512 val_loss=5.2717 val_acc=0.0928 seconds=0.9
[CNN_room] Fusion/lovo fold=03 epoch 07/70: train_loss=2.0201 train_acc=0.3849 val_loss=5.2801 val_acc=0.0758 seconds=0.9
[CNN_room] Fusion/lovo fold=03 epoch 08/70: train_loss=1.9469 train_acc=0.4011 val_loss=5.6885 val_acc=0.0773 seconds=0.9
[CNN_room] Fusion/lovo fold=03 epoch 09/70: train_loss=1.8185 train_acc=0.4462 val_loss=5.5660 val_acc=0.0680 seconds=1.0
[CNN_room] Fusion/lovo fold=03 epoch 10/70: train_loss=1.7757 train_acc=0.4545 val_loss=6.2067 val_acc=0.0758 seconds=0.9
[CNN_room] Fusion/lovo fold=03 epoch 11/70: train_loss=1.6551 train_acc=0.4859 val_loss=6.1130 val_acc=0.0695 seconds=0.9
[CNN_room] Fusion/lovo fold=03 epoch 12/70: train_loss=1.5885 train_acc=0.5098 val_loss=6.5199 val_acc=0.0744 seconds=0.9
[CNN_room] Fusion/lovo fold=03 epoch 13/70: train_loss=1.5133 train_acc=0.5299 val_loss=7.1045 val_acc=0.0687 seconds=0.9
[CNN_room] Fusion/lovo fold=03 epoch 14/70: train_loss=1.4813 train_acc=0.5362 val_loss=6.9729 val_acc=0.0773 seconds=0.9
[CNN_room] Fusion/lovo fold=03 epoch 15/70: train_loss=1.4353 train_acc=0.5524 val_loss=7.6244 val_acc=0.0780 seconds=0.9
[CNN_room] Fusion/lovo fold=03 epoch 16/70: train_loss=1.3930 train_acc=0.5681 val_loss=6.8391 val_acc=0.0624 seconds=0.9
[CNN_room] Fusion/lovo fold=03 epoch 17/70: train_loss=1.3501 train_acc=0.5767 val_loss=8.0600 val_acc=0.0758 seconds=0.9
[CNN_room] Fusion/lovo fold=03 epoch 18/70: train_loss=1.2694 train_acc=0.6135 val_loss=7.4863 val_acc=0.0730 seconds=0.9
[CNN_room] Fusion/lovo fold=03 epoch 19/70: train_loss=1.2417 train_acc=0.6147 val_loss=7.8482 val_acc=0.0709 seconds=1.0
[CNN_room] Fusion/lovo fold=03 epoch 20/70: train_loss=1.2128 train_acc=0.6168 val_loss=8.1691 val_acc=0.0744 seconds=1.0
[CNN_room] Fusion/lovo fold=03 epoch 21/70: train_loss=1.1723 train_acc=0.6341 val_loss=7.6287 val_acc=0.0695 seconds=1.0
[CNN_room] early stopping at epoch 21; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn_room__fusion__lovo__ebl-session__s44__5ccebc__fold-03.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn_room__fusion__lovo__ebl-session__s44__5ccebc/training_curves__fold-03.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=04 validation_user=03 (entire user, deterministic rotation)
[CNN_room] Fusion/lovo fold=04 parameters=195636
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN_room] Fusion/lovo fold=04 epoch 01/70: train_loss=3.7907 train_acc=0.0714 val_loss=3.7988 val_acc=0.0542 seconds=3.7
[CNN_room] Fusion/lovo fold=04 epoch 02/70: train_loss=3.2159 train_acc=0.1516 val_loss=3.5325 val_acc=0.1217 seconds=0.9
[CNN_room] Fusion/lovo fold=04 epoch 03/70: train_loss=2.7777 train_acc=0.2101 val_loss=3.4147 val_acc=0.1444 seconds=0.9
[CNN_room] Fusion/lovo fold=04 epoch 04/70: train_loss=2.5063 train_acc=0.2667 val_loss=3.6436 val_acc=0.1330 seconds=0.9
[CNN_room] Fusion/lovo fold=04 epoch 05/70: train_loss=2.3082 train_acc=0.3137 val_loss=3.6299 val_acc=0.1488 seconds=0.9
[CNN_room] Fusion/lovo fold=04 epoch 06/70: train_loss=2.1467 train_acc=0.3522 val_loss=3.8340 val_acc=0.1356 seconds=0.9
[CNN_room] Fusion/lovo fold=04 epoch 07/70: train_loss=2.0213 train_acc=0.3879 val_loss=4.2793 val_acc=0.1337 seconds=0.9
[CNN_room] Fusion/lovo fold=04 epoch 08/70: train_loss=1.8926 train_acc=0.4217 val_loss=4.5744 val_acc=0.1488 seconds=1.0
[CNN_room] Fusion/lovo fold=04 epoch 09/70: train_loss=1.7846 train_acc=0.4560 val_loss=4.5435 val_acc=0.1305 seconds=0.9
[CNN_room] Fusion/lovo fold=04 epoch 10/70: train_loss=1.6783 train_acc=0.4842 val_loss=4.7341 val_acc=0.1305 seconds=1.0
[CNN_room] Fusion/lovo fold=04 epoch 11/70: train_loss=1.5649 train_acc=0.5148 val_loss=5.3372 val_acc=0.1305 seconds=0.9
[CNN_room] Fusion/lovo fold=04 epoch 12/70: train_loss=1.5102 train_acc=0.5324 val_loss=5.2484 val_acc=0.1267 seconds=1.0
[CNN_room] Fusion/lovo fold=04 epoch 13/70: train_loss=1.4228 train_acc=0.5550 val_loss=5.4889 val_acc=0.1242 seconds=0.9
[CNN_room] Fusion/lovo fold=04 epoch 14/70: train_loss=1.3535 train_acc=0.5728 val_loss=5.5896 val_acc=0.1248 seconds=1.0
[CNN_room] Fusion/lovo fold=04 epoch 15/70: train_loss=1.2774 train_acc=0.6072 val_loss=5.8138 val_acc=0.1286 seconds=0.9
[CNN_room] Fusion/lovo fold=04 epoch 16/70: train_loss=1.2195 train_acc=0.6259 val_loss=6.1089 val_acc=0.1223 seconds=0.9
[CNN_room] Fusion/lovo fold=04 epoch 17/70: train_loss=1.1723 train_acc=0.6328 val_loss=6.0863 val_acc=0.1110 seconds=0.9
[CNN_room] Fusion/lovo fold=04 epoch 18/70: train_loss=1.1099 train_acc=0.6499 val_loss=6.2173 val_acc=0.1129 seconds=0.9
[CNN_room] Fusion/lovo fold=04 epoch 19/70: train_loss=1.0459 train_acc=0.6687 val_loss=6.5472 val_acc=0.1248 seconds=1.0
[CNN_room] Fusion/lovo fold=04 epoch 20/70: train_loss=1.0209 train_acc=0.6734 val_loss=6.3769 val_acc=0.1122 seconds=0.9
[CNN_room] early stopping at epoch 20; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn_room__fusion__lovo__ebl-session__s44__5ccebc__fold-04.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn_room__fusion__lovo__ebl-session__s44__5ccebc/training_curves__fold-04.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=05 validation_user=04 (entire user, deterministic rotation)
[CNN_room] Fusion/lovo fold=05 parameters=195636
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN_room] Fusion/lovo fold=05 epoch 01/70: train_loss=3.7756 train_acc=0.0691 val_loss=3.8526 val_acc=0.0699 seconds=3.7
[CNN_room] Fusion/lovo fold=05 epoch 02/70: train_loss=3.1194 train_acc=0.1437 val_loss=4.0428 val_acc=0.0757 seconds=1.0
[CNN_room] Fusion/lovo fold=05 epoch 03/70: train_loss=2.7476 train_acc=0.2014 val_loss=3.8306 val_acc=0.0988 seconds=0.9
[CNN_room] Fusion/lovo fold=05 epoch 04/70: train_loss=2.5194 train_acc=0.2582 val_loss=3.7389 val_acc=0.1309 seconds=0.9
[CNN_room] Fusion/lovo fold=05 epoch 05/70: train_loss=2.3513 train_acc=0.3053 val_loss=3.9655 val_acc=0.1270 seconds=1.0
[CNN_room] Fusion/lovo fold=05 epoch 06/70: train_loss=2.2161 train_acc=0.3316 val_loss=4.2189 val_acc=0.1257 seconds=0.9
[CNN_room] Fusion/lovo fold=05 epoch 07/70: train_loss=2.0949 train_acc=0.3669 val_loss=4.2468 val_acc=0.1328 seconds=1.0
[CNN_room] Fusion/lovo fold=05 epoch 08/70: train_loss=1.9857 train_acc=0.4073 val_loss=4.5945 val_acc=0.1238 seconds=1.0
[CNN_room] Fusion/lovo fold=05 epoch 09/70: train_loss=1.8793 train_acc=0.4170 val_loss=4.4301 val_acc=0.1430 seconds=0.9
[CNN_room] Fusion/lovo fold=05 epoch 10/70: train_loss=1.7853 train_acc=0.4560 val_loss=4.3657 val_acc=0.1616 seconds=1.0
[CNN_room] Fusion/lovo fold=05 epoch 11/70: train_loss=1.6853 train_acc=0.4790 val_loss=4.5809 val_acc=0.1366 seconds=1.0
[CNN_room] Fusion/lovo fold=05 epoch 12/70: train_loss=1.6099 train_acc=0.5092 val_loss=4.9231 val_acc=0.1379 seconds=1.0
[CNN_room] Fusion/lovo fold=05 epoch 13/70: train_loss=1.5393 train_acc=0.5236 val_loss=5.0282 val_acc=0.1424 seconds=1.0
[CNN_room] Fusion/lovo fold=05 epoch 14/70: train_loss=1.4773 train_acc=0.5332 val_loss=4.8450 val_acc=0.1418 seconds=1.0
[CNN_room] Fusion/lovo fold=05 epoch 15/70: train_loss=1.4017 train_acc=0.5520 val_loss=4.8637 val_acc=0.1450 seconds=0.9
[CNN_room] Fusion/lovo fold=05 epoch 16/70: train_loss=1.3313 train_acc=0.5897 val_loss=4.9603 val_acc=0.1347 seconds=1.0
[CNN_room] Fusion/lovo fold=05 epoch 17/70: train_loss=1.2425 train_acc=0.6042 val_loss=5.3593 val_acc=0.1283 seconds=1.0
[CNN_room] Fusion/lovo fold=05 epoch 18/70: train_loss=1.2208 train_acc=0.6138 val_loss=5.0802 val_acc=0.1405 seconds=1.0
[CNN_room] Fusion/lovo fold=05 epoch 19/70: train_loss=1.1774 train_acc=0.6289 val_loss=5.4632 val_acc=0.1482 seconds=1.0
[CNN_room] Fusion/lovo fold=05 epoch 20/70: train_loss=1.1367 train_acc=0.6473 val_loss=5.4257 val_acc=0.1225 seconds=1.0
[CNN_room] Fusion/lovo fold=05 epoch 21/70: train_loss=1.0828 train_acc=0.6595 val_loss=5.7665 val_acc=0.1309 seconds=1.0
[CNN_room] Fusion/lovo fold=05 epoch 22/70: train_loss=1.0393 train_acc=0.6696 val_loss=5.8408 val_acc=0.1456 seconds=1.0
[CNN_room] Fusion/lovo fold=05 epoch 23/70: train_loss=1.0032 train_acc=0.6805 val_loss=6.2899 val_acc=0.1386 seconds=0.9
[CNN_room] Fusion/lovo fold=05 epoch 24/70: train_loss=0.9863 train_acc=0.6894 val_loss=5.6277 val_acc=0.1373 seconds=1.0
[CNN_room] Fusion/lovo fold=05 epoch 25/70: train_loss=0.9422 train_acc=0.7038 val_loss=6.5832 val_acc=0.1379 seconds=1.0
[CNN_room] early stopping at epoch 25; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn_room__fusion__lovo__ebl-session__s44__5ccebc__fold-05.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn_room__fusion__lovo__ebl-session__s44__5ccebc/training_curves__fold-05.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=06 validation_user=05 (entire user, deterministic rotation)
[CNN_room] Fusion/lovo fold=06 parameters=195636
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN_room] Fusion/lovo fold=06 epoch 01/70: train_loss=3.7286 train_acc=0.0780 val_loss=3.9653 val_acc=0.0397 seconds=4.2
[CNN_room] Fusion/lovo fold=06 epoch 02/70: train_loss=3.1016 train_acc=0.1585 val_loss=3.7713 val_acc=0.1285 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 03/70: train_loss=2.7539 train_acc=0.2146 val_loss=3.4653 val_acc=0.1467 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 04/70: train_loss=2.5356 train_acc=0.2578 val_loss=3.2329 val_acc=0.1676 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 05/70: train_loss=2.3698 train_acc=0.3054 val_loss=3.2062 val_acc=0.1958 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 06/70: train_loss=2.2219 train_acc=0.3328 val_loss=3.1586 val_acc=0.2127 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 07/70: train_loss=2.0986 train_acc=0.3636 val_loss=3.0397 val_acc=0.2241 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 08/70: train_loss=1.9976 train_acc=0.3903 val_loss=3.0376 val_acc=0.2153 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 09/70: train_loss=1.8870 train_acc=0.4289 val_loss=3.1737 val_acc=0.1931 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 10/70: train_loss=1.7979 train_acc=0.4495 val_loss=3.0528 val_acc=0.2140 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 11/70: train_loss=1.7323 train_acc=0.4727 val_loss=3.0020 val_acc=0.2113 seconds=0.9
[CNN_room] Fusion/lovo fold=06 epoch 12/70: train_loss=1.6608 train_acc=0.5008 val_loss=3.2322 val_acc=0.2086 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 13/70: train_loss=1.5869 train_acc=0.5079 val_loss=3.1658 val_acc=0.2093 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 14/70: train_loss=1.4995 train_acc=0.5412 val_loss=3.3707 val_acc=0.2241 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 15/70: train_loss=1.4483 train_acc=0.5579 val_loss=3.3240 val_acc=0.2268 seconds=0.9
[CNN_room] Fusion/lovo fold=06 epoch 16/70: train_loss=1.4008 train_acc=0.5682 val_loss=3.3947 val_acc=0.2409 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 17/70: train_loss=1.3533 train_acc=0.5769 val_loss=3.4509 val_acc=0.2308 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 18/70: train_loss=1.2731 train_acc=0.6086 val_loss=3.4426 val_acc=0.2429 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 19/70: train_loss=1.2288 train_acc=0.6238 val_loss=3.6352 val_acc=0.2416 seconds=0.9
[CNN_room] Fusion/lovo fold=06 epoch 20/70: train_loss=1.1999 train_acc=0.6246 val_loss=3.3950 val_acc=0.2261 seconds=0.9
[CNN_room] Fusion/lovo fold=06 epoch 21/70: train_loss=1.1502 train_acc=0.6465 val_loss=3.6185 val_acc=0.2362 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 22/70: train_loss=1.1119 train_acc=0.6529 val_loss=3.8692 val_acc=0.2342 seconds=0.9
[CNN_room] Fusion/lovo fold=06 epoch 23/70: train_loss=1.0733 train_acc=0.6658 val_loss=3.8550 val_acc=0.2100 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 24/70: train_loss=1.0349 train_acc=0.6806 val_loss=4.3044 val_acc=0.2086 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 25/70: train_loss=0.9992 train_acc=0.6807 val_loss=4.1350 val_acc=0.1999 seconds=0.9
[CNN_room] Fusion/lovo fold=06 epoch 26/70: train_loss=0.9752 train_acc=0.6905 val_loss=4.0966 val_acc=0.2167 seconds=0.9
[CNN_room] Fusion/lovo fold=06 epoch 27/70: train_loss=0.9371 train_acc=0.6941 val_loss=4.3695 val_acc=0.2261 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 28/70: train_loss=0.9141 train_acc=0.7123 val_loss=3.8327 val_acc=0.2402 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 29/70: train_loss=0.8912 train_acc=0.7116 val_loss=3.9259 val_acc=0.2436 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 30/70: train_loss=0.8585 train_acc=0.7241 val_loss=4.1719 val_acc=0.2389 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 31/70: train_loss=0.8279 train_acc=0.7380 val_loss=4.0269 val_acc=0.2349 seconds=0.9
[CNN_room] Fusion/lovo fold=06 epoch 32/70: train_loss=0.8238 train_acc=0.7344 val_loss=4.1399 val_acc=0.2308 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 33/70: train_loss=0.7896 train_acc=0.7542 val_loss=4.1708 val_acc=0.2369 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 34/70: train_loss=0.7748 train_acc=0.7537 val_loss=4.7163 val_acc=0.2261 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 35/70: train_loss=0.7512 train_acc=0.7556 val_loss=4.5456 val_acc=0.1965 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 36/70: train_loss=0.7481 train_acc=0.7584 val_loss=4.7442 val_acc=0.2113 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 37/70: train_loss=0.7111 train_acc=0.7697 val_loss=4.8404 val_acc=0.2301 seconds=0.9
[CNN_room] Fusion/lovo fold=06 epoch 38/70: train_loss=0.7016 train_acc=0.7699 val_loss=4.7129 val_acc=0.2073 seconds=0.9
[CNN_room] Fusion/lovo fold=06 epoch 39/70: train_loss=0.6789 train_acc=0.7787 val_loss=4.7650 val_acc=0.2106 seconds=0.9
[CNN_room] Fusion/lovo fold=06 epoch 40/70: train_loss=0.6783 train_acc=0.7836 val_loss=4.6208 val_acc=0.2106 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 41/70: train_loss=0.6439 train_acc=0.7936 val_loss=4.7880 val_acc=0.2180 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 42/70: train_loss=0.6151 train_acc=0.8001 val_loss=4.9006 val_acc=0.1958 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 43/70: train_loss=0.6029 train_acc=0.8059 val_loss=4.8283 val_acc=0.2207 seconds=1.0
[CNN_room] Fusion/lovo fold=06 epoch 44/70: train_loss=0.5959 train_acc=0.8055 val_loss=4.7451 val_acc=0.2261 seconds=1.0
[CNN_room] early stopping at epoch 44; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn_room__fusion__lovo__ebl-session__s44__5ccebc__fold-06.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn_room__fusion__lovo__ebl-session__s44__5ccebc/training_curves__fold-06.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn_room__fusion__lovo__ebl-session__s44__5ccebc.parquet
[results upsert] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/runs_folds.csv: 72 row(s)
[DL LOVO] seed=44 fold mean position_accuracy=0.1263 +/- 0.0399; pooled=0.1275
[DL GPU] run_id=dl__cnn_room__fusion__lovo__ebl-session__s44__5ccebc peak_cuda_memory_bytes=2685729792
[results upsert] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/runs.csv: 42 row(s)
[DL seeds] mean +/- std across seeds written to tables/seed_summary; LOVO uses each seed's fold mean and keeps within-seed fold std separate.

In [8]:
cnn_summary, test_accuracy_comparison = show_dl_results(results_dir)
display(cnn_summary)

display(test_accuracy_comparison)

,run_id,timestamp,family,model,band,split,seed,normalization,baseline_scope,window_size,...,best_epoch_std,mean_seconds_per_epoch,mean_seconds_per_epoch_mean,mean_seconds_per_epoch_std,stopped_epoch,patience_triggered,peak_cuda_memory_bytes,device,sklearn_version,numpy_version
3,dl__cnn__2_4ghz__block__ebl-session__s42__df21ec,2026-07-22T18:36:31.182108+00:00,dl,cnn,2_4ghz,block,42,empty_baseline,session,60,...,NaN,0.282136,NaN,NaN,44.0,1.0,5.147146e+08,cuda,1.9.0,2.5.1
4,dl__cnn__2_4ghz__block__ebl-session__s43__210c56,2026-07-22T18:36:47.242239+00:00,dl,cnn,2_4ghz,block,43,empty_baseline,session,60,...,NaN,0.251184,NaN,NaN,50.0,0.0,5.147146e+08,cuda,1.9.0,2.5.1
5,dl__cnn__2_4ghz__block__ebl-session__s44__86f94f,2026-07-22T18:37:03.908150+00:00,dl,cnn,2_4ghz,block,44,empty_baseline,session,60,...,NaN,0.255270,NaN,NaN,50.0,0.0,5.147146e+08,cuda,1.9.0,2.5.1
6,dl__cnn__5ghz__block__ebl-session__s42__df21ec,2026-07-22T18:37:26.695344+00:00,dl,cnn,5ghz,block,42,empty_baseline,session,60,...,NaN,0.345880,NaN,NaN,40.0,1.0,5.790833e+08,cuda,1.9.0,2.5.1
7,dl__cnn__5ghz__block__ebl-session__s43__210c56,2026-07-22T18:37:44.903111+00:00,dl,cnn,5ghz,block,43,empty_baseline,session,60,...,NaN,0.327006,NaN,NaN,44.0,1.0,5.790833e+08,cuda,1.9.0,2.5.1
8,dl__cnn__5ghz__block__ebl-session__s44__86f94f,2026-07-22T18:38:04.402553+00:00,dl,cnn,5ghz,block,44,empty_baseline,session,60,...,NaN,0.312220,NaN,NaN,50.0,0.0,5.790833e+08,cuda,1.9.0,2.5.1
9,dl__cnn__fusion__block__ebl-session__s42__df21ec,2026-07-22T18:38:41.941273+00:00,dl,cnn,fusion,block,42,empty_baseline,session,60,...,NaN,0.463929,NaN,NaN,50.0,0.0,9.784187e+08,cuda,1.9.0,2.5.1
10,dl__cnn__fusion__block__ebl-session__s43__210c56,2026-07-22T18:39:07.169167+00:00,dl,cnn,fusion,block,43,empty_baseline,session,60,...,NaN,0.432133,NaN,NaN,50.0,0.0,9.784187e+08,cuda,1.9.0,2.5.1
11,dl__cnn__fusion__block__ebl-session__s44__86f94f,2026-07-22T18:39:27.186644+00:00,dl,cnn,fusion,block,44,empty_baseline,session,60,...,NaN,0.452285,NaN,NaN,36.0,1.0,9.784187e+08,cuda,1.9.0,2.5.1
12,dl__cnn__2_4ghz__block__ebl-session__s42__eb2083,2026-07-22T22:25:24.462285+00:00,dl,cnn,2_4ghz,block,42,empty_baseline,session,60,...,NaN,0.291731,NaN,NaN,50.0,0.0,5.147146e+08,cuda,1.9.0,2.5.1
13,dl__cnn__2_4ghz__block__ebl-session__s43__7d42d1,2026-07-22T22:25:41.299487+00:00,dl,cnn,2_4ghz,block,43,empty_baseline,session,60,...,NaN,0.271714,NaN,NaN,50.0,0.0,5.147146e+08,cuda,1.9.0,2.5.1
14,dl__cnn__2_4ghz__block__ebl-session__s44__3f1421,2026-07-22T22:25:57.650859+00:00,dl,cnn,2_4ghz,block,44,empty_baseline,session,60,...,NaN,0.271407,NaN,NaN,50.0,0.0,5.147146e+08,cuda,1.9.0,2.5.1
15,dl__cnn__5ghz__block__ebl-session__s42__eb2083,2026-07-22T22:26:18.424778+00:00,dl,cnn,5ghz,block,42,empty_baseline,session,60,...,NaN,0.351592,NaN,NaN,50.0,0.0,5.790833e+08,cuda,1.9.0,2.5.1
16,dl__cnn__5ghz__block__ebl-session__s43__7d42d1,2026-07-22T22:26:38.575420+00:00,dl,cnn,5ghz,block,43,empty_baseline,session,60,...,NaN,0.348412,NaN,NaN,50.0,0.0,5.790833e+08,cuda,1.9.0,2.5.1
17,dl__cnn__5ghz__block__ebl-session__s44__3f1421,2026-07-22T22:26:58.653328+00:00,dl,cnn,5ghz,block,44,empty_baseline,session,60,...,NaN,0.346380,NaN,NaN,50.0,0.0,5.790833e+08,cuda,1.9.0,2.5.1
18,dl__cnn__fusion__block__ebl-session__s42__eb2083,2026-07-22T22:27:28.062797+00:00,dl,cnn,fusion,block,42,empty_baseline,session,60,...,NaN,0.512262,NaN,NaN,50.0,0.0,9.784187e+08,cuda,1.9.0,2.5.1
19,dl__cnn__fusion__block__ebl-session__s43__7d42d1,2026-07-22T22:27:57.119251+00:00,dl,cnn,fusion,block,43,empty_baseline,session,60,...,NaN,0.520320,NaN,NaN,50.0,0.0,9.784187e+08,cuda,1.9.0,2.5.1
20,dl__cnn__fusion__block__ebl-session__s44__3f1421,2026-07-22T22:28:25.104041+00:00,dl,cnn,fusion,block,44,empty_baseline,session,60,...,NaN,0.498056,NaN,NaN,50.0,0.0,9.784187e+08,cuda,1.9.0,2.5.1
24,dl__cnn__2_4ghz__lovo__ebl-session__s42__9b1404,2026-07-23T13:48:02.786457+00:00,dl,cnn,2_4ghz,lovo,42,empty_baseline,session,60,...,12.956337,0.470346,0.470346,0.045645,NaN,NaN,5.147146e+08,cuda,1.9.0,2.5.1
25,dl__cnn__2_4ghz__lovo__ebl-session__s43__a89b5d,2026-07-23T13:49:57.671381+00:00,dl,cnn,2_4ghz,lovo,43,empty_baseline,session,60,...,15.587388,0.463850,0.463850,0.038593,NaN,NaN,5.147146e+08,cuda,1.9.0,2.5.1
26,dl__cnn__2_4ghz__lovo__ebl-session__s44__7b9bf2,2026-07-23T13:51:31.436316+00:00,dl,cnn,2_4ghz,lovo,44,empty_baseline,session,60,...,10.966616,0.498135,0.498135,0.034860,NaN,NaN,5.147146e+08,cuda,1.9.0,2.5.1
27,dl__cnn__5ghz__lovo__ebl-session__s42__9b1404,2026-07-23T13:53:57.387552+00:00,dl,cnn,5ghz,lovo,42,empty_baseline,session,60,...,22.618576,0.589029,0.589029,0.054417,NaN,NaN,5.790833e+08,cuda,1.9.0,2.5.1
28,dl__cnn__5ghz__lovo__ebl-session__s43__a89b5d,2026-07-23T13:55:51.186055+00:00,dl,cnn,5ghz,lovo,43,empty_baseline,session,60,...,7.685484,0.598899,0.598899,0.042237,NaN,NaN,5.790833e+08,cuda,1.9.0,2.5.1
29,dl__cnn__5ghz__lovo__ebl-session__s44__7b9bf2,2026-07-23T13:57:58.923697+00:00,dl,cnn,5ghz,lovo,44,empty_baseline,session,60,...,15.033296,0.583697,0.583697,0.031769,NaN,NaN,5.790833e+08,cuda,1.9.0,2.5.1
30,dl__cnn__fusion__lovo__ebl-session__s42__9b1404,2026-07-23T14:00:58.465944+00:00,dl,cnn,fusion,lovo,42,empty_baseline,session,60,...,9.852242,0.884760,0.884760,0.043593,NaN,NaN,9.784187e+08,cuda,1.9.0,2.5.1
31,dl__cnn__fusion__lovo__ebl-session__s43__a89b5d,2026-07-23T14:04:09.091103+00:00,dl,cnn,fusion,lovo,43,empty_baseline,session,60,...,13.023056,0.877289,0.877289,0.027092,NaN,NaN,9.784187e+08,cuda,1.9.0,2.5.1
32,dl__cnn__fusion__lovo__ebl-session__s44__7b9bf2,2026-07-23T14:08:05.305960+00:00,dl,cnn,fusion,lovo,44,empty_baseline,session,60,...,13.155480,0.859873,0.859873,0.020100,NaN,NaN,9.784187e+08,cuda,1.9.0,2.5.1
39,dl__cnn_room__fusion__lovo__ebl-session__s42__...,2026-07-24T11:05:15.109337+00:00,dl,cnn_room,fusion,lovo,42,empty_baseline,session,60,...,13.779211,1.092870,1.092870,0.043795,NaN,NaN,2.685730e+09,cuda,1.9.0,2.5.1
40,dl__cnn_room__fusion__lovo__ebl-session__s43__...,2026-07-24T11:08:25.003152+00:00,dl,cnn_room,fusion,lovo,43,empty_baseline,session,60,...,17.189144,1.095378,1.095378,0.043565,NaN,NaN,2.685730e+09,cuda,1.9.0,2.5.1
41,dl__cnn_room__fusion__lovo__ebl-session__s44__...,2026-07-24T11:12:11.839497+00:00,dl,cnn_room,fusion,lovo,44,empty_baseline,session,60,...,16.235763,1.054616,1.054616,0.017014,NaN,NaN,2.685730e+09,cuda,1.9.0,2.5.1

      band model  seed  position_accuracy  parameter_count
3   2_4ghz   cnn    42           0.248563          76020.0
12  2_4ghz   cnn    42           0.286101          76020.0
4   2_4ghz   cnn    43           0.316092          76020.0
13  2_4ghz   cnn    43           0.276036          76020.0
5   2_4ghz   cnn    44           0.320402          76020.0
14  2_4ghz   cnn    44           0.293457          76020.0
6     5ghz   cnn    42           0.290049          76308.0
15    5ghz   cnn    42           0.298067          76308.0
7     5ghz   cnn    43           0.307039          76308.0
16    5ghz   cnn    43           0.296661          76308.0
8     5ghz   cnn    44           0.324636          76308.0
17    5ghz   cnn    44           0.297012          76308.0
9   fusion   cnn    42           0.489193         138708.0
18  fusion   cnn    42           0.404965         138708.0
10  fusion   cnn    43           0.462536         138708.0
19  fusion   cnn    43           0.378588         138708.0
11  fusion   cnn    44           0.398415         138708.0
20  fusion   cnn    44           0.410396         138708.0