## Multi-protocol CNN Raw CSI Experiments

This notebook runs the fixed-capacity CNN across block, LOVO, and cross-session protocols with one independent run per configured seed.

In [1]:
from __future__ import annotations

import pandas as pd
import torch

from utils.config import (
    ANCHOR_GROUPS,
    ARCHITECTURE,
    BANDS_TO_RUN,
    DATA_DIR,
    DEFAULT_CNN_PARAMS,
    DEFAULT_OVERLAP_SIZE,
    DEFAULT_WINDOW_SIZE,
    EXPECTED_ANCHORS,
    EXPECTED_SUBCARRIERS,
    SEEDS,
)
from utils.DL.dl_pipeline import (
    create_position_label_encoder,
    get_cache_path,
    get_results_path,
    prepare_dl_data,
    print_torch_environment,
    run_dl_experiments,
    show_dl_results,
)

### Configuration

In [ ]:
CALIBRATION_MODE = "rssi"    # ("none", "packet_norm", "rssi")

CSV_PROCESSING_OPTIONS = {
    "max_workers": 1,
    "cache_dir": None,
    "use_cache": True,
    "force_reprocess": False,
    "min_rssi_dbm": -95.0,
}

MAGNITUDE_PROCESSING_OPTIONS = {
    "normalization": "empty_baseline",  # none | zscore | minmax | packet_minmax | empty_baseline
    "epsilon": 1e-8,
}
NORMALIZATION_BASELINE_SCOPE = "per_session"

FEATURE_EXTRACTION_OPTIONS = {
    "window_size": DEFAULT_WINDOW_SIZE,
    "overlap_size": DEFAULT_OVERLAP_SIZE,
    "require_all_esps": False,
}

BLOCK_COUNT = 10
TEST_SIZE = 0.30
VALIDATION_SIZE = 0.15
RANDOM_STATE = 42
FORCE_RETRAIN = False
SPLIT_MODES = ("block", "lovo")

CNN_PARAMS = {
    **DEFAULT_CNN_PARAMS,
    "model_label": "CNN",
    "epochs": 70,
    "patience": 15,
    "lr": 1e-3,
    "weight_decay": 1e-4,
    "random_state": RANDOM_STATE,
    "test_size": TEST_SIZE,
    "validation_size": VALIDATION_SIZE,
    "n_blocks": BLOCK_COUNT,
    "anchor_groups": ANCHOR_GROUPS,
    "torch_version": torch.__version__,
}

preproc_opts = dict(MAGNITUDE_PROCESSING_OPTIONS)
preproc_opts["baseline_scope"] = NORMALIZATION_BASELINE_SCOPE
feat_opts = dict(FEATURE_EXTRACTION_OPTIONS)

feature_cache_dir = get_cache_path(preproc_opts, feat_opts)
results_dir = get_results_path()
plots_dir = results_dir / "plots"
for directory in (plots_dir, results_dir / "predictions", results_dir / "tables"):
    directory.mkdir(parents=True, exist_ok=True)

print(f"Feature cache path: {feature_cache_dir}")
print(f"Results path: {results_dir}")

Feature cache path: /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/.cache/dataframes/preproc=norm-none/feat=win60-step0
Results path: /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results

### Environment

In [3]:
DEVICE = print_torch_environment(require_cuda=True)

torch.__version__: 2.11.0+cu128
torch.version.cuda: 12.8
torch.cuda.get_device_name(0): NVIDIA RTX PRO 6000 Blackwell Max-Q Workstation Edition
torch.cuda.get_device_capability(0): (12, 0)
CUDA matmul smoke test result: [[0.0, 1.0, 2.0, 3.0], [4.0, 5.0, 6.0, 7.0], [8.0, 9.0, 10.0, 11.0], [12.0, 13.0, 14.0, 15.0]] (PASS)

### Data

In [4]:
processed_magnitude_data, feature_dataframes, csv_diagnostics, magnitude_summary = prepare_dl_data(
    DATA_DIR,
    calibration_mode=CALIBRATION_MODE,
    csv_options=CSV_PROCESSING_OPTIONS,
    preproc_opts=preproc_opts,
    feat_opts=feat_opts,
)
display(magnitude_summary.head())

Scenarios present: 1
Locations: 53 | Users: 6 | ESPs: 19
[cache hit] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/.cache/dataframes/preproc=norm-none/feat=win60-step0/2_4ghz.parquet
[cache hit] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/.cache/dataframes/preproc=norm-none/feat=win60-step0/5ghz.parquet
[cache hit] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/.cache/dataframes/preproc=norm-none/feat=win60-step0/fusion.parquet

,scenario,location,user,esp,trial,samples,subcarriers,normalization,baseline_scope
0,1,C-1,06,16,01,2088,56,none,
1,1,C-1,06,15,01,1942,56,none,
2,1,C-1,06,09,01,1689,50,none,
3,1,C-1,06,07,01,1965,50,none,
4,1,C-1,06,04,01,1913,50,none,

In [5]:
for band in BANDS_TO_RUN:
    df = feature_dataframes[band]
    print(f"{band}: {df.shape[0]} windows, {df.shape[1]} columns")
    print(f"{band} dataframe hash: {pd.util.hash_pandas_object(df, index=True).sum()}")

2.4 GHz: 13588 windows, 2708 columns
2.4 GHz dataframe hash: 12901719627776270762
5 GHz: 14478 windows, 3368 columns
5 GHz dataframe hash: 4746810533186240626
Fusion: 13568 windows, 6068 columns
Fusion dataframe hash: 10770637710876130155

In [6]:
label_encoder = create_position_label_encoder(
    feature_dataframes,
    results_dir=results_dir,
    expected_classes=52,
)
print(label_encoder.classes_)

[CNN] label classes saved to /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/manifests/cnn_label_classes.json
['A-1' 'A-13' 'A-14' 'A-2' 'A-5' 'B-1' 'B-10' 'B-11' 'B-12' 'B-13' 'B-14'
 'B-2' 'B-5' 'B-8' 'C-1' 'C-10' 'C-11' 'C-14' 'C-2' 'C-3' 'C-4' 'C-5'
 'C-6' 'C-7' 'C-8' 'C-9' 'D-1' 'D-2' 'D-3' 'D-4' 'D-5' 'D-6' 'D-7' 'D-8'
 'E-1' 'E-10' 'E-11' 'E-12' 'E-13' 'E-2' 'E-3' 'E-4' 'E-5' 'E-6' 'E-7'
 'E-8' 'F-10' 'F-11' 'F-12' 'F-13' 'F-5' 'F-8']

### Train And Evaluate

In [7]:
cnn_runs = run_dl_experiments(
    processed_magnitude_data,
    feature_dataframes,
    bands=BANDS_TO_RUN,
    split_modes=SPLIT_MODES,
    label_encoder=label_encoder,
    device=DEVICE,
    results_dir=results_dir,
    plots_dir=plots_dir,
    params=CNN_PARAMS,
    preproc_opts=preproc_opts,
    feat_opts=feat_opts,
    expected_subcarriers=EXPECTED_SUBCARRIERS,
    expected_anchors=EXPECTED_ANCHORS,
    architecture=ARCHITECTURE,
    seeds=SEEDS,
    test_size=TEST_SIZE,
    random_state=RANDOM_STATE,
    n_blocks=BLOCK_COUNT,
    val_size=VALIDATION_SIZE,
    force_retrain=FORCE_RETRAIN,
)

=== 2.4 GHz ===
[window arrays] cache path: /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/.cache/dataframes/preproc=norm-none/feat=win60-step0/window_arrays/2_4ghz
[window arrays] 2.4 GHz: shape=(13588, 9, 50, 60), dtype=float16
[window arrays] 2.4 GHz anchors: ['esp_01', 'esp_02', 'esp_03', 'esp_04', 'esp_05', 'esp_07', 'esp_08', 'esp_09', 'esp_10']
2.4 GHz: anchors=9, subcarriers=50, windows=13588
WINDOW IDENTITY PASS: 2.4 GHz (13588 windows)
[trial filter] split=block trials=['01'] kept=8906/13588
[protocol] split=block trials_used=['01'] n_train=4947 n_test=1392 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05', '06'] test_users=['01', '02', '03', '04', '05', '06']
[trial filter] split=block trials=['01'] kept=8906/13588
[protocol] split=block trials_used=['01'] n_train=4947 n_test=1392 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05', '06'] test_users=['01', '02', '03', '04', '05', '06']
SPLIT IDENTITY PASS: 2.4 GHz/block fold=1 train=4947 test=1392
Seeds: random=42, numpy=42, torch=42
[trial filter] split=block trials=['01'] kept=8906/13588
[protocol] split=block trials_used=['01'] n_train=4947 n_test=1392 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05', '06'] test_users=['01', '02', '03', '04', '05', '06']
[trial filter] split=block trials=['01'] kept=4947/4947
[protocol] split=block trials_used=['01'] n_train=3014 n_test=150 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05', '06'] test_users=['01', '02', '03', '04', '05', '06']
[CNN] 2.4 GHz/block fold=single parameters=76020
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] 2.4 GHz/block fold=single epoch 01/70: train_loss=3.9517 train_acc=0.0219 val_loss=3.9561 val_acc=0.0133 seconds=2.8
[CNN] 2.4 GHz/block fold=single epoch 02/70: train_loss=3.9246 train_acc=0.0448 val_loss=3.9158 val_acc=0.0467 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 03/70: train_loss=3.8795 train_acc=0.0617 val_loss=3.8619 val_acc=0.0467 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 04/70: train_loss=3.7768 train_acc=0.0674 val_loss=3.9595 val_acc=0.0200 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 05/70: train_loss=3.6241 train_acc=0.0873 val_loss=3.6483 val_acc=0.0800 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 06/70: train_loss=3.4931 train_acc=0.1052 val_loss=3.7341 val_acc=0.0467 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 07/70: train_loss=3.3754 train_acc=0.1171 val_loss=3.5176 val_acc=0.1267 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 08/70: train_loss=3.2694 train_acc=0.1397 val_loss=3.5005 val_acc=0.1200 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 09/70: train_loss=3.1562 train_acc=0.1632 val_loss=4.4309 val_acc=0.0400 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 10/70: train_loss=3.0747 train_acc=0.1742 val_loss=4.1794 val_acc=0.0467 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 11/70: train_loss=2.9735 train_acc=0.1934 val_loss=3.8174 val_acc=0.0800 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 12/70: train_loss=2.8934 train_acc=0.2210 val_loss=5.2682 val_acc=0.0333 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 13/70: train_loss=2.8101 train_acc=0.2210 val_loss=3.6922 val_acc=0.0933 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 14/70: train_loss=2.7135 train_acc=0.2522 val_loss=3.7709 val_acc=0.1067 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 15/70: train_loss=2.6379 train_acc=0.2787 val_loss=4.8971 val_acc=0.0533 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 16/70: train_loss=2.5941 train_acc=0.2820 val_loss=3.8751 val_acc=0.1267 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 17/70: train_loss=2.5386 train_acc=0.2890 val_loss=4.4106 val_acc=0.1000 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 18/70: train_loss=2.4645 train_acc=0.3042 val_loss=3.1017 val_acc=0.2333 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 19/70: train_loss=2.4113 train_acc=0.3188 val_loss=3.0043 val_acc=0.1733 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 20/70: train_loss=2.3385 train_acc=0.3318 val_loss=3.4126 val_acc=0.1667 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 21/70: train_loss=2.2804 train_acc=0.3543 val_loss=3.4480 val_acc=0.1600 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 22/70: train_loss=2.2177 train_acc=0.3703 val_loss=2.9448 val_acc=0.2267 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 23/70: train_loss=2.2048 train_acc=0.3766 val_loss=3.3262 val_acc=0.1733 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 24/70: train_loss=2.1406 train_acc=0.3912 val_loss=2.6518 val_acc=0.2667 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 25/70: train_loss=2.0749 train_acc=0.4171 val_loss=2.5720 val_acc=0.2733 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 26/70: train_loss=2.0195 train_acc=0.4230 val_loss=3.7611 val_acc=0.1200 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 27/70: train_loss=2.0028 train_acc=0.4313 val_loss=3.5351 val_acc=0.1933 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 28/70: train_loss=1.9716 train_acc=0.4313 val_loss=5.3393 val_acc=0.0800 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 29/70: train_loss=1.9328 train_acc=0.4502 val_loss=3.5768 val_acc=0.1800 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 30/70: train_loss=1.9151 train_acc=0.4463 val_loss=2.8294 val_acc=0.2067 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 31/70: train_loss=1.8785 train_acc=0.4559 val_loss=2.8331 val_acc=0.2400 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 32/70: train_loss=1.8379 train_acc=0.4672 val_loss=3.0564 val_acc=0.2067 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 33/70: train_loss=1.7708 train_acc=0.4877 val_loss=4.0941 val_acc=0.1400 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 34/70: train_loss=1.7777 train_acc=0.4814 val_loss=3.5877 val_acc=0.1867 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 35/70: train_loss=1.7568 train_acc=0.4864 val_loss=2.6539 val_acc=0.2600 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 36/70: train_loss=1.7108 train_acc=0.4993 val_loss=4.8906 val_acc=0.0800 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 37/70: train_loss=1.6727 train_acc=0.5033 val_loss=2.7205 val_acc=0.3267 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 38/70: train_loss=1.6489 train_acc=0.5083 val_loss=3.6448 val_acc=0.2133 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 39/70: train_loss=1.6465 train_acc=0.5126 val_loss=3.2914 val_acc=0.2067 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 40/70: train_loss=1.6157 train_acc=0.5269 val_loss=2.8424 val_acc=0.2733 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 41/70: train_loss=1.5985 train_acc=0.5269 val_loss=4.8620 val_acc=0.1333 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 42/70: train_loss=1.5751 train_acc=0.5365 val_loss=4.8681 val_acc=0.0933 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 43/70: train_loss=1.5169 train_acc=0.5597 val_loss=3.3314 val_acc=0.1933 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 44/70: train_loss=1.4969 train_acc=0.5614 val_loss=2.8349 val_acc=0.2200 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 45/70: train_loss=1.4828 train_acc=0.5650 val_loss=4.2220 val_acc=0.1867 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 46/70: train_loss=1.4855 train_acc=0.5561 val_loss=2.5480 val_acc=0.3400 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 47/70: train_loss=1.4110 train_acc=0.5693 val_loss=3.8822 val_acc=0.1667 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 48/70: train_loss=1.4058 train_acc=0.5770 val_loss=4.5911 val_acc=0.1467 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 49/70: train_loss=1.4111 train_acc=0.5760 val_loss=2.8301 val_acc=0.3000 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 50/70: train_loss=1.3514 train_acc=0.5922 val_loss=3.6981 val_acc=0.2133 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 51/70: train_loss=1.3309 train_acc=0.6042 val_loss=3.3387 val_acc=0.2733 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 52/70: train_loss=1.3302 train_acc=0.6048 val_loss=4.6486 val_acc=0.1600 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 53/70: train_loss=1.3039 train_acc=0.6052 val_loss=2.5191 val_acc=0.3667 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 54/70: train_loss=1.3010 train_acc=0.6145 val_loss=4.2954 val_acc=0.1733 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 55/70: train_loss=1.2792 train_acc=0.6019 val_loss=3.3095 val_acc=0.2667 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 56/70: train_loss=1.2867 train_acc=0.6108 val_loss=4.2156 val_acc=0.1867 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 57/70: train_loss=1.2781 train_acc=0.6105 val_loss=3.3481 val_acc=0.2600 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 58/70: train_loss=1.2240 train_acc=0.6277 val_loss=3.4681 val_acc=0.2467 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 59/70: train_loss=1.1855 train_acc=0.6413 val_loss=3.2247 val_acc=0.2333 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 60/70: train_loss=1.1990 train_acc=0.6337 val_loss=4.5316 val_acc=0.2667 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 61/70: train_loss=1.1692 train_acc=0.6496 val_loss=5.1611 val_acc=0.1467 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 62/70: train_loss=1.1600 train_acc=0.6593 val_loss=3.4334 val_acc=0.2600 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 63/70: train_loss=1.1461 train_acc=0.6569 val_loss=5.5294 val_acc=0.1467 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 64/70: train_loss=1.1292 train_acc=0.6453 val_loss=2.6486 val_acc=0.3467 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 65/70: train_loss=1.0886 train_acc=0.6772 val_loss=3.7627 val_acc=0.2800 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 66/70: train_loss=1.0973 train_acc=0.6715 val_loss=2.8598 val_acc=0.3533 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 67/70: train_loss=1.0705 train_acc=0.6762 val_loss=2.8906 val_acc=0.3133 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 68/70: train_loss=1.0509 train_acc=0.6825 val_loss=3.2832 val_acc=0.2667 seconds=0.2
[CNN] early stopping at epoch 68; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__2_4ghz__block__none__s42__a8e3cb.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__2_4ghz__block__none__s42__a8e3cb/training_curves.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL GPU] run_id=dl__cnn__2_4ghz__block__none__s42__a8e3cb peak_cuda_memory_bytes=514714624
[results upsert] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/runs.csv: 71 row(s)
Seeds: random=43, numpy=43, torch=43
[trial filter] split=block trials=['01'] kept=8906/13588
[protocol] split=block trials_used=['01'] n_train=4947 n_test=1392 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05', '06'] test_users=['01', '02', '03', '04', '05', '06']
[trial filter] split=block trials=['01'] kept=4947/4947
[protocol] split=block trials_used=['01'] n_train=3014 n_test=150 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05', '06'] test_users=['01', '02', '03', '04', '05', '06']
[CNN] 2.4 GHz/block fold=single parameters=76020
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] 2.4 GHz/block fold=single epoch 01/70: train_loss=3.9493 train_acc=0.0209 val_loss=3.9351 val_acc=0.0133 seconds=2.1
[CNN] 2.4 GHz/block fold=single epoch 02/70: train_loss=3.9241 train_acc=0.0421 val_loss=3.9147 val_acc=0.0400 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 03/70: train_loss=3.8826 train_acc=0.0617 val_loss=3.8920 val_acc=0.0533 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 04/70: train_loss=3.8082 train_acc=0.0683 val_loss=3.7921 val_acc=0.0467 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 05/70: train_loss=3.6693 train_acc=0.0932 val_loss=3.6878 val_acc=0.0800 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 06/70: train_loss=3.5088 train_acc=0.1038 val_loss=3.6167 val_acc=0.0667 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 07/70: train_loss=3.3604 train_acc=0.1238 val_loss=3.8536 val_acc=0.0467 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 08/70: train_loss=3.2190 train_acc=0.1546 val_loss=4.5541 val_acc=0.0333 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 09/70: train_loss=3.1028 train_acc=0.1682 val_loss=3.6898 val_acc=0.1133 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 10/70: train_loss=2.9830 train_acc=0.1865 val_loss=3.2743 val_acc=0.0867 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 11/70: train_loss=2.8780 train_acc=0.2160 val_loss=5.6127 val_acc=0.0333 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 12/70: train_loss=2.7885 train_acc=0.2266 val_loss=3.5875 val_acc=0.1067 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 13/70: train_loss=2.7198 train_acc=0.2532 val_loss=4.5150 val_acc=0.0867 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 14/70: train_loss=2.6247 train_acc=0.2734 val_loss=3.4451 val_acc=0.1267 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 15/70: train_loss=2.5776 train_acc=0.2843 val_loss=3.8108 val_acc=0.1467 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 16/70: train_loss=2.4840 train_acc=0.3042 val_loss=3.3292 val_acc=0.1067 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 17/70: train_loss=2.3972 train_acc=0.3321 val_loss=4.0487 val_acc=0.1200 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 18/70: train_loss=2.3828 train_acc=0.3368 val_loss=3.7413 val_acc=0.1467 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 19/70: train_loss=2.2978 train_acc=0.3603 val_loss=3.1070 val_acc=0.1867 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 20/70: train_loss=2.2429 train_acc=0.3686 val_loss=4.3216 val_acc=0.1200 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 21/70: train_loss=2.1968 train_acc=0.3762 val_loss=3.0421 val_acc=0.2267 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 22/70: train_loss=2.1112 train_acc=0.4021 val_loss=2.8918 val_acc=0.2400 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 23/70: train_loss=2.0811 train_acc=0.3991 val_loss=3.4214 val_acc=0.1933 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 24/70: train_loss=2.0778 train_acc=0.4001 val_loss=3.9350 val_acc=0.1467 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 25/70: train_loss=2.0365 train_acc=0.4180 val_loss=5.9341 val_acc=0.0600 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 26/70: train_loss=1.9820 train_acc=0.4303 val_loss=4.1354 val_acc=0.1267 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 27/70: train_loss=1.9139 train_acc=0.4536 val_loss=3.6084 val_acc=0.1733 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 28/70: train_loss=1.8791 train_acc=0.4393 val_loss=3.8968 val_acc=0.1600 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 29/70: train_loss=1.8429 train_acc=0.4695 val_loss=3.4304 val_acc=0.1733 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 30/70: train_loss=1.8009 train_acc=0.4751 val_loss=4.2473 val_acc=0.1267 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 31/70: train_loss=1.7801 train_acc=0.4764 val_loss=4.1838 val_acc=0.0867 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 32/70: train_loss=1.7716 train_acc=0.4841 val_loss=5.9518 val_acc=0.1067 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 33/70: train_loss=1.7119 train_acc=0.5010 val_loss=4.7703 val_acc=0.1133 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 34/70: train_loss=1.6957 train_acc=0.5010 val_loss=3.5831 val_acc=0.1200 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 35/70: train_loss=1.7000 train_acc=0.4964 val_loss=5.0337 val_acc=0.0933 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 36/70: train_loss=1.6421 train_acc=0.5212 val_loss=2.7710 val_acc=0.2800 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 37/70: train_loss=1.6077 train_acc=0.5232 val_loss=4.0738 val_acc=0.1467 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 38/70: train_loss=1.5971 train_acc=0.5255 val_loss=5.1539 val_acc=0.1067 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 39/70: train_loss=1.5647 train_acc=0.5285 val_loss=3.4062 val_acc=0.2200 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 40/70: train_loss=1.5504 train_acc=0.5325 val_loss=4.8389 val_acc=0.1400 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 41/70: train_loss=1.5215 train_acc=0.5445 val_loss=4.5709 val_acc=0.1467 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 42/70: train_loss=1.5151 train_acc=0.5474 val_loss=2.7401 val_acc=0.2400 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 43/70: train_loss=1.4714 train_acc=0.5587 val_loss=2.8271 val_acc=0.2533 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 44/70: train_loss=1.4555 train_acc=0.5657 val_loss=3.9231 val_acc=0.1600 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 45/70: train_loss=1.4164 train_acc=0.5683 val_loss=4.2996 val_acc=0.1533 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 46/70: train_loss=1.4149 train_acc=0.5743 val_loss=3.4180 val_acc=0.2200 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 47/70: train_loss=1.4076 train_acc=0.5707 val_loss=3.7853 val_acc=0.2267 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 48/70: train_loss=1.3857 train_acc=0.5800 val_loss=2.5503 val_acc=0.3733 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 49/70: train_loss=1.3524 train_acc=0.5995 val_loss=2.8646 val_acc=0.3133 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 50/70: train_loss=1.3244 train_acc=0.5972 val_loss=3.1980 val_acc=0.2533 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 51/70: train_loss=1.2929 train_acc=0.6148 val_loss=2.6998 val_acc=0.3267 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 52/70: train_loss=1.2863 train_acc=0.6058 val_loss=3.2527 val_acc=0.1933 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 53/70: train_loss=1.2908 train_acc=0.6075 val_loss=2.7088 val_acc=0.2800 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 54/70: train_loss=1.2499 train_acc=0.6184 val_loss=3.6827 val_acc=0.2733 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 55/70: train_loss=1.2128 train_acc=0.6337 val_loss=3.4304 val_acc=0.2600 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 56/70: train_loss=1.1831 train_acc=0.6427 val_loss=4.0744 val_acc=0.2067 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 57/70: train_loss=1.1899 train_acc=0.6304 val_loss=3.7550 val_acc=0.1800 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 58/70: train_loss=1.1613 train_acc=0.6500 val_loss=3.0999 val_acc=0.2667 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 59/70: train_loss=1.1683 train_acc=0.6553 val_loss=5.4441 val_acc=0.1333 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 60/70: train_loss=1.1788 train_acc=0.6380 val_loss=4.9068 val_acc=0.1067 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 61/70: train_loss=1.1616 train_acc=0.6417 val_loss=3.3787 val_acc=0.2333 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 62/70: train_loss=1.1640 train_acc=0.6367 val_loss=3.8179 val_acc=0.2800 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 63/70: train_loss=1.1522 train_acc=0.6486 val_loss=3.8524 val_acc=0.2400 seconds=0.2
[CNN] early stopping at epoch 63; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__2_4ghz__block__none__s43__89f1a2.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__2_4ghz__block__none__s43__89f1a2/training_curves.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL GPU] run_id=dl__cnn__2_4ghz__block__none__s43__89f1a2 peak_cuda_memory_bytes=514714624
[results upsert] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/runs.csv: 72 row(s)
Seeds: random=44, numpy=44, torch=44
[trial filter] split=block trials=['01'] kept=8906/13588
[protocol] split=block trials_used=['01'] n_train=4947 n_test=1392 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05', '06'] test_users=['01', '02', '03', '04', '05', '06']
[trial filter] split=block trials=['01'] kept=4947/4947
[protocol] split=block trials_used=['01'] n_train=3014 n_test=150 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05', '06'] test_users=['01', '02', '03', '04', '05', '06']
[CNN] 2.4 GHz/block fold=single parameters=76020
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] 2.4 GHz/block fold=single epoch 01/70: train_loss=3.9512 train_acc=0.0199 val_loss=3.9375 val_acc=0.0200 seconds=2.2
[CNN] 2.4 GHz/block fold=single epoch 02/70: train_loss=3.9270 train_acc=0.0358 val_loss=3.9169 val_acc=0.0267 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 03/70: train_loss=3.8859 train_acc=0.0521 val_loss=3.8621 val_acc=0.0400 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 04/70: train_loss=3.8006 train_acc=0.0617 val_loss=3.7801 val_acc=0.0533 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 05/70: train_loss=3.6575 train_acc=0.0743 val_loss=3.6738 val_acc=0.0733 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 06/70: train_loss=3.4973 train_acc=0.1072 val_loss=3.9843 val_acc=0.0400 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 07/70: train_loss=3.3656 train_acc=0.1181 val_loss=3.7993 val_acc=0.0800 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 08/70: train_loss=3.2444 train_acc=0.1486 val_loss=3.8806 val_acc=0.0867 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 09/70: train_loss=3.1058 train_acc=0.1802 val_loss=3.4727 val_acc=0.1267 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 10/70: train_loss=3.0113 train_acc=0.1948 val_loss=3.6478 val_acc=0.1400 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 11/70: train_loss=2.9139 train_acc=0.2031 val_loss=3.8830 val_acc=0.0867 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 12/70: train_loss=2.8164 train_acc=0.2432 val_loss=3.9499 val_acc=0.1267 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 13/70: train_loss=2.7467 train_acc=0.2475 val_loss=4.3365 val_acc=0.0933 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 14/70: train_loss=2.6617 train_acc=0.2691 val_loss=4.2076 val_acc=0.0600 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 15/70: train_loss=2.6136 train_acc=0.2817 val_loss=3.5467 val_acc=0.1533 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 16/70: train_loss=2.5563 train_acc=0.2926 val_loss=4.0963 val_acc=0.0867 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 17/70: train_loss=2.4870 train_acc=0.3089 val_loss=3.2753 val_acc=0.1733 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 18/70: train_loss=2.4018 train_acc=0.3251 val_loss=3.8953 val_acc=0.1200 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 19/70: train_loss=2.3350 train_acc=0.3414 val_loss=3.8520 val_acc=0.1133 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 20/70: train_loss=2.3105 train_acc=0.3520 val_loss=3.5338 val_acc=0.1133 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 21/70: train_loss=2.2318 train_acc=0.3623 val_loss=4.1740 val_acc=0.0933 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 22/70: train_loss=2.2081 train_acc=0.3809 val_loss=2.7764 val_acc=0.2133 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 23/70: train_loss=2.1395 train_acc=0.3816 val_loss=3.6308 val_acc=0.1467 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 24/70: train_loss=2.1187 train_acc=0.4035 val_loss=3.2826 val_acc=0.2000 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 25/70: train_loss=2.0983 train_acc=0.3968 val_loss=3.8138 val_acc=0.1800 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 26/70: train_loss=2.0500 train_acc=0.4044 val_loss=2.9035 val_acc=0.2133 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 27/70: train_loss=1.9870 train_acc=0.4253 val_loss=4.5989 val_acc=0.1800 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 28/70: train_loss=1.9233 train_acc=0.4453 val_loss=3.1932 val_acc=0.2267 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 29/70: train_loss=1.9113 train_acc=0.4443 val_loss=3.0820 val_acc=0.2000 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 30/70: train_loss=1.8572 train_acc=0.4635 val_loss=3.5709 val_acc=0.1400 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 31/70: train_loss=1.8142 train_acc=0.4784 val_loss=3.9177 val_acc=0.1333 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 32/70: train_loss=1.7663 train_acc=0.4834 val_loss=5.6780 val_acc=0.0800 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 33/70: train_loss=1.7718 train_acc=0.4940 val_loss=2.8397 val_acc=0.2800 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 34/70: train_loss=1.7195 train_acc=0.5007 val_loss=2.9213 val_acc=0.2667 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 35/70: train_loss=1.6609 train_acc=0.5202 val_loss=3.1783 val_acc=0.2267 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 36/70: train_loss=1.6431 train_acc=0.5216 val_loss=4.0420 val_acc=0.1667 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 37/70: train_loss=1.6192 train_acc=0.5255 val_loss=3.5377 val_acc=0.2467 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 38/70: train_loss=1.5980 train_acc=0.5398 val_loss=2.9893 val_acc=0.2867 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 39/70: train_loss=1.5724 train_acc=0.5305 val_loss=4.4357 val_acc=0.1533 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 40/70: train_loss=1.5311 train_acc=0.5541 val_loss=3.0466 val_acc=0.2400 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 41/70: train_loss=1.4975 train_acc=0.5627 val_loss=2.2643 val_acc=0.3533 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 42/70: train_loss=1.4586 train_acc=0.5693 val_loss=3.3334 val_acc=0.2600 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 43/70: train_loss=1.4779 train_acc=0.5511 val_loss=2.8734 val_acc=0.2400 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 44/70: train_loss=1.4378 train_acc=0.5687 val_loss=5.5621 val_acc=0.1267 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 45/70: train_loss=1.4309 train_acc=0.5790 val_loss=3.0104 val_acc=0.2667 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 46/70: train_loss=1.3901 train_acc=0.5972 val_loss=3.0414 val_acc=0.2667 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 47/70: train_loss=1.3618 train_acc=0.5999 val_loss=2.8802 val_acc=0.3067 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 48/70: train_loss=1.3318 train_acc=0.6009 val_loss=2.4373 val_acc=0.4133 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 49/70: train_loss=1.3294 train_acc=0.6022 val_loss=3.6874 val_acc=0.2533 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 50/70: train_loss=1.2860 train_acc=0.6111 val_loss=2.9141 val_acc=0.2533 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 51/70: train_loss=1.2621 train_acc=0.6241 val_loss=2.8294 val_acc=0.2467 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 52/70: train_loss=1.2521 train_acc=0.6115 val_loss=3.0235 val_acc=0.3333 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 53/70: train_loss=1.2648 train_acc=0.6175 val_loss=5.2372 val_acc=0.1467 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 54/70: train_loss=1.2380 train_acc=0.6301 val_loss=4.0706 val_acc=0.2400 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 55/70: train_loss=1.2206 train_acc=0.6274 val_loss=2.6911 val_acc=0.3133 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 56/70: train_loss=1.1847 train_acc=0.6470 val_loss=3.5167 val_acc=0.2067 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 57/70: train_loss=1.1537 train_acc=0.6559 val_loss=5.6929 val_acc=0.1533 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 58/70: train_loss=1.1469 train_acc=0.6520 val_loss=2.6394 val_acc=0.3733 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 59/70: train_loss=1.1272 train_acc=0.6606 val_loss=4.0901 val_acc=0.2467 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 60/70: train_loss=1.1086 train_acc=0.6619 val_loss=2.7864 val_acc=0.3000 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 61/70: train_loss=1.0950 train_acc=0.6619 val_loss=3.6944 val_acc=0.2867 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 62/70: train_loss=1.1002 train_acc=0.6626 val_loss=3.4200 val_acc=0.2800 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 63/70: train_loss=1.0581 train_acc=0.6722 val_loss=3.2998 val_acc=0.2867 seconds=0.2
[CNN] early stopping at epoch 63; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__2_4ghz__block__none__s44__d87d56.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__2_4ghz__block__none__s44__d87d56/training_curves.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL GPU] run_id=dl__cnn__2_4ghz__block__none__s44__d87d56 peak_cuda_memory_bytes=514714624
[results upsert] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/runs.csv: 73 row(s)
[DL seeds] mean +/- std across seeds written to tables/seed_summary; LOVO uses each seed's fold mean and keeps within-seed fold std separate.

=== 5 GHz ===
[window arrays] cache path: /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/.cache/dataframes/preproc=norm-none/feat=win60-step0/window_arrays/5ghz
[window arrays] 5 GHz: shape=(14478, 10, 56, 60), dtype=float16
[window arrays] 5 GHz anchors: ['esp_11', 'esp_12', 'esp_13', 'esp_14', 'esp_15', 'esp_16', 'esp_17', 'esp_18', 'esp_19', 'esp_20']
5 GHz: anchors=10, subcarriers=56, windows=14478
WINDOW IDENTITY PASS: 5 GHz (14478 windows)
[trial filter] split=block trials=['01'] kept=9695/14478
[protocol] split=block trials_used=['01'] n_train=5477 n_test=1648 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05', '06'] test_users=['01', '02', '03', '04', '05', '06']
[trial filter] split=block trials=['01'] kept=9695/14478
[protocol] split=block trials_used=['01'] n_train=5477 n_test=1648 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05', '06'] test_users=['01', '02', '03', '04', '05', '06']
SPLIT IDENTITY PASS: 5 GHz/block fold=1 train=5477 test=1648
Seeds: random=42, numpy=42, torch=42
[trial filter] split=block trials=['01'] kept=9695/14478
[protocol] split=block trials_used=['01'] n_train=5477 n_test=1648 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05', '06'] test_users=['01', '02', '03', '04', '05', '06']
[trial filter] split=block trials=['01'] kept=5477/5477
[protocol] split=block trials_used=['01'] n_train=3396 n_test=179 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05', '06'] test_users=['01', '02', '03', '04', '05', '06']
[CNN] 5 GHz/block fold=single parameters=76308
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] 5 GHz/block fold=single epoch 01/70: train_loss=3.9437 train_acc=0.0221 val_loss=3.9085 val_acc=0.0615 seconds=2.5
[CNN] 5 GHz/block fold=single epoch 02/70: train_loss=3.8596 train_acc=0.0718 val_loss=3.7868 val_acc=0.0782 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 03/70: train_loss=3.7000 train_acc=0.0875 val_loss=3.6913 val_acc=0.0894 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 04/70: train_loss=3.5154 train_acc=0.1078 val_loss=3.6838 val_acc=0.1117 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 05/70: train_loss=3.3627 train_acc=0.1266 val_loss=3.3864 val_acc=0.1676 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 06/70: train_loss=3.2509 train_acc=0.1511 val_loss=3.2948 val_acc=0.1397 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 07/70: train_loss=3.1591 train_acc=0.1555 val_loss=3.2566 val_acc=0.1508 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 08/70: train_loss=3.0725 train_acc=0.1711 val_loss=3.2579 val_acc=0.1732 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 09/70: train_loss=2.9894 train_acc=0.1826 val_loss=3.1677 val_acc=0.1676 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 10/70: train_loss=2.9272 train_acc=0.1964 val_loss=3.2089 val_acc=0.2067 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 11/70: train_loss=2.8686 train_acc=0.2064 val_loss=3.1651 val_acc=0.1732 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 12/70: train_loss=2.8126 train_acc=0.2117 val_loss=3.1462 val_acc=0.1620 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 13/70: train_loss=2.7460 train_acc=0.2359 val_loss=3.1162 val_acc=0.1732 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 14/70: train_loss=2.7141 train_acc=0.2376 val_loss=3.1445 val_acc=0.2067 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 15/70: train_loss=2.6733 train_acc=0.2494 val_loss=3.3328 val_acc=0.1788 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 16/70: train_loss=2.6021 train_acc=0.2562 val_loss=2.9657 val_acc=0.2011 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 17/70: train_loss=2.5661 train_acc=0.2665 val_loss=2.9725 val_acc=0.2346 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 18/70: train_loss=2.5167 train_acc=0.2797 val_loss=3.7726 val_acc=0.1788 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 19/70: train_loss=2.4823 train_acc=0.2824 val_loss=3.2352 val_acc=0.2011 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 20/70: train_loss=2.4337 train_acc=0.3024 val_loss=3.0147 val_acc=0.1899 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 21/70: train_loss=2.3628 train_acc=0.3163 val_loss=3.3402 val_acc=0.1732 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 22/70: train_loss=2.3536 train_acc=0.3227 val_loss=2.8882 val_acc=0.2179 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 23/70: train_loss=2.3054 train_acc=0.3363 val_loss=2.8272 val_acc=0.2123 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 24/70: train_loss=2.2845 train_acc=0.3357 val_loss=2.9633 val_acc=0.2402 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 25/70: train_loss=2.2201 train_acc=0.3569 val_loss=3.0811 val_acc=0.2067 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 26/70: train_loss=2.1790 train_acc=0.3701 val_loss=3.0958 val_acc=0.2458 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 27/70: train_loss=2.1864 train_acc=0.3654 val_loss=3.0811 val_acc=0.2235 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 28/70: train_loss=2.1311 train_acc=0.3693 val_loss=3.1365 val_acc=0.2235 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 29/70: train_loss=2.1145 train_acc=0.3698 val_loss=2.8981 val_acc=0.2402 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 30/70: train_loss=2.0676 train_acc=0.3916 val_loss=2.9709 val_acc=0.2570 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 31/70: train_loss=2.0341 train_acc=0.3925 val_loss=2.7926 val_acc=0.2793 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 32/70: train_loss=2.0169 train_acc=0.4087 val_loss=2.7659 val_acc=0.2849 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 33/70: train_loss=1.9755 train_acc=0.4143 val_loss=2.9210 val_acc=0.2514 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 34/70: train_loss=1.9248 train_acc=0.4267 val_loss=3.1016 val_acc=0.1899 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 35/70: train_loss=1.9441 train_acc=0.4234 val_loss=2.9572 val_acc=0.2682 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 36/70: train_loss=1.9184 train_acc=0.4252 val_loss=3.3898 val_acc=0.2235 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 37/70: train_loss=1.8667 train_acc=0.4499 val_loss=2.9603 val_acc=0.2626 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 38/70: train_loss=1.8552 train_acc=0.4547 val_loss=3.0427 val_acc=0.2737 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 39/70: train_loss=1.8225 train_acc=0.4564 val_loss=2.8638 val_acc=0.2737 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 40/70: train_loss=1.8043 train_acc=0.4594 val_loss=2.9202 val_acc=0.2402 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 41/70: train_loss=1.8116 train_acc=0.4505 val_loss=2.9305 val_acc=0.2458 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 42/70: train_loss=1.7798 train_acc=0.4726 val_loss=3.2455 val_acc=0.2346 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 43/70: train_loss=1.7839 train_acc=0.4658 val_loss=2.7044 val_acc=0.3017 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 44/70: train_loss=1.7056 train_acc=0.5003 val_loss=2.6949 val_acc=0.2737 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 45/70: train_loss=1.6869 train_acc=0.4965 val_loss=2.8509 val_acc=0.2682 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 46/70: train_loss=1.6950 train_acc=0.4862 val_loss=3.3865 val_acc=0.2402 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 47/70: train_loss=1.6610 train_acc=0.4979 val_loss=2.7122 val_acc=0.3017 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 48/70: train_loss=1.6926 train_acc=0.4838 val_loss=2.8687 val_acc=0.2961 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 49/70: train_loss=1.6681 train_acc=0.4915 val_loss=2.9385 val_acc=0.2961 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 50/70: train_loss=1.6021 train_acc=0.5168 val_loss=2.6677 val_acc=0.3073 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 51/70: train_loss=1.6147 train_acc=0.5027 val_loss=3.1400 val_acc=0.2737 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 52/70: train_loss=1.5967 train_acc=0.5168 val_loss=3.4583 val_acc=0.1955 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 53/70: train_loss=1.5906 train_acc=0.5174 val_loss=2.8783 val_acc=0.2793 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 54/70: train_loss=1.5511 train_acc=0.5321 val_loss=3.2384 val_acc=0.2514 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 55/70: train_loss=1.5205 train_acc=0.5415 val_loss=2.8953 val_acc=0.2961 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 56/70: train_loss=1.4854 train_acc=0.5477 val_loss=2.6682 val_acc=0.3631 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 57/70: train_loss=1.4921 train_acc=0.5451 val_loss=2.8865 val_acc=0.3073 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 58/70: train_loss=1.4974 train_acc=0.5439 val_loss=2.7934 val_acc=0.3128 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 59/70: train_loss=1.4970 train_acc=0.5400 val_loss=3.0858 val_acc=0.3128 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 60/70: train_loss=1.4938 train_acc=0.5353 val_loss=2.7660 val_acc=0.3520 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 61/70: train_loss=1.4938 train_acc=0.5489 val_loss=3.4350 val_acc=0.2402 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 62/70: train_loss=1.4420 train_acc=0.5592 val_loss=2.7204 val_acc=0.3687 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 63/70: train_loss=1.4140 train_acc=0.5648 val_loss=2.8063 val_acc=0.3352 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 64/70: train_loss=1.3903 train_acc=0.5822 val_loss=2.7686 val_acc=0.3464 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 65/70: train_loss=1.3842 train_acc=0.5710 val_loss=2.8798 val_acc=0.3073 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 66/70: train_loss=1.3704 train_acc=0.5742 val_loss=2.7259 val_acc=0.3799 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 67/70: train_loss=1.3552 train_acc=0.5851 val_loss=2.7721 val_acc=0.3184 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 68/70: train_loss=1.3561 train_acc=0.5845 val_loss=2.8697 val_acc=0.3408 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 69/70: train_loss=1.3723 train_acc=0.5701 val_loss=2.9035 val_acc=0.3128 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 70/70: train_loss=1.4057 train_acc=0.5624 val_loss=2.9903 val_acc=0.3296 seconds=0.3

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__5ghz__block__none__s42__a8e3cb.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__5ghz__block__none__s42__a8e3cb/training_curves.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL GPU] run_id=dl__cnn__5ghz__block__none__s42__a8e3cb peak_cuda_memory_bytes=579083264
[results upsert] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/runs.csv: 74 row(s)
Seeds: random=43, numpy=43, torch=43
[trial filter] split=block trials=['01'] kept=9695/14478
[protocol] split=block trials_used=['01'] n_train=5477 n_test=1648 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05', '06'] test_users=['01', '02', '03', '04', '05', '06']
[trial filter] split=block trials=['01'] kept=5477/5477
[protocol] split=block trials_used=['01'] n_train=3396 n_test=179 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05', '06'] test_users=['01', '02', '03', '04', '05', '06']
[CNN] 5 GHz/block fold=single parameters=76308
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] 5 GHz/block fold=single epoch 01/70: train_loss=3.9429 train_acc=0.0303 val_loss=3.8999 val_acc=0.0782 seconds=2.2
[CNN] 5 GHz/block fold=single epoch 02/70: train_loss=3.8519 train_acc=0.0701 val_loss=3.7889 val_acc=0.1061 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 03/70: train_loss=3.6954 train_acc=0.0816 val_loss=3.6517 val_acc=0.0950 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 04/70: train_loss=3.5197 train_acc=0.1048 val_loss=3.5916 val_acc=0.0894 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 05/70: train_loss=3.3755 train_acc=0.1184 val_loss=3.4614 val_acc=0.1285 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 06/70: train_loss=3.2623 train_acc=0.1313 val_loss=3.4500 val_acc=0.1173 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 07/70: train_loss=3.1668 train_acc=0.1552 val_loss=3.2935 val_acc=0.1453 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 08/70: train_loss=3.0870 train_acc=0.1614 val_loss=3.3885 val_acc=0.1397 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 09/70: train_loss=3.0210 train_acc=0.1782 val_loss=3.1592 val_acc=0.1899 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 10/70: train_loss=2.9600 train_acc=0.1920 val_loss=3.2845 val_acc=0.1453 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 11/70: train_loss=2.9007 train_acc=0.2067 val_loss=3.2843 val_acc=0.1564 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 12/70: train_loss=2.8645 train_acc=0.2123 val_loss=3.3495 val_acc=0.1508 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 13/70: train_loss=2.8050 train_acc=0.2217 val_loss=3.2205 val_acc=0.1676 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 14/70: train_loss=2.7350 train_acc=0.2423 val_loss=3.0402 val_acc=0.1676 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 15/70: train_loss=2.6830 train_acc=0.2412 val_loss=3.2190 val_acc=0.1788 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 16/70: train_loss=2.6805 train_acc=0.2512 val_loss=3.0865 val_acc=0.1844 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 17/70: train_loss=2.5953 train_acc=0.2541 val_loss=3.0358 val_acc=0.1788 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 18/70: train_loss=2.5586 train_acc=0.2671 val_loss=3.1212 val_acc=0.2067 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 19/70: train_loss=2.5137 train_acc=0.2836 val_loss=3.0100 val_acc=0.1676 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 20/70: train_loss=2.4928 train_acc=0.2856 val_loss=2.9139 val_acc=0.2402 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 21/70: train_loss=2.4144 train_acc=0.3027 val_loss=3.0994 val_acc=0.2011 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 22/70: train_loss=2.3746 train_acc=0.3213 val_loss=3.1515 val_acc=0.2067 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 23/70: train_loss=2.3496 train_acc=0.3230 val_loss=2.9006 val_acc=0.2626 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 24/70: train_loss=2.2950 train_acc=0.3375 val_loss=3.1796 val_acc=0.2011 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 25/70: train_loss=2.2982 train_acc=0.3369 val_loss=3.1367 val_acc=0.2179 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 26/70: train_loss=2.2734 train_acc=0.3451 val_loss=2.9723 val_acc=0.2291 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 27/70: train_loss=2.1957 train_acc=0.3501 val_loss=2.9013 val_acc=0.2346 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 28/70: train_loss=2.1874 train_acc=0.3566 val_loss=2.9002 val_acc=0.2570 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 29/70: train_loss=2.1169 train_acc=0.3751 val_loss=3.0696 val_acc=0.2123 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 30/70: train_loss=2.0861 train_acc=0.3922 val_loss=2.9065 val_acc=0.2737 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 31/70: train_loss=2.1010 train_acc=0.3793 val_loss=2.8789 val_acc=0.2402 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 32/70: train_loss=2.0748 train_acc=0.3875 val_loss=2.9255 val_acc=0.2905 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 33/70: train_loss=2.0176 train_acc=0.4111 val_loss=2.9141 val_acc=0.2682 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 34/70: train_loss=1.9851 train_acc=0.4111 val_loss=2.8686 val_acc=0.2682 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 35/70: train_loss=1.9947 train_acc=0.4105 val_loss=2.8597 val_acc=0.2514 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 36/70: train_loss=1.9471 train_acc=0.4155 val_loss=2.9222 val_acc=0.3128 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 37/70: train_loss=1.9480 train_acc=0.4240 val_loss=3.0000 val_acc=0.2737 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 38/70: train_loss=1.9126 train_acc=0.4302 val_loss=2.8090 val_acc=0.2570 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 39/70: train_loss=1.8643 train_acc=0.4396 val_loss=3.1079 val_acc=0.2235 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 40/70: train_loss=1.8583 train_acc=0.4473 val_loss=2.9098 val_acc=0.2961 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 41/70: train_loss=1.8137 train_acc=0.4711 val_loss=2.8404 val_acc=0.2961 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 42/70: train_loss=1.8220 train_acc=0.4432 val_loss=3.1570 val_acc=0.2570 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 43/70: train_loss=1.8040 train_acc=0.4535 val_loss=3.2706 val_acc=0.2179 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 44/70: train_loss=1.7740 train_acc=0.4614 val_loss=2.9500 val_acc=0.2682 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 45/70: train_loss=1.7786 train_acc=0.4573 val_loss=2.8485 val_acc=0.3073 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 46/70: train_loss=1.7685 train_acc=0.4750 val_loss=2.9668 val_acc=0.2793 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 47/70: train_loss=1.7046 train_acc=0.4841 val_loss=2.9160 val_acc=0.2905 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 48/70: train_loss=1.6658 train_acc=0.5009 val_loss=3.1283 val_acc=0.2570 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 49/70: train_loss=1.6802 train_acc=0.4894 val_loss=3.0355 val_acc=0.2905 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 50/70: train_loss=1.6499 train_acc=0.5047 val_loss=3.2576 val_acc=0.2458 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 51/70: train_loss=1.7001 train_acc=0.4870 val_loss=3.2536 val_acc=0.2737 seconds=0.2
[CNN] early stopping at epoch 51; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__5ghz__block__none__s43__89f1a2.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__5ghz__block__none__s43__89f1a2/training_curves.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL GPU] run_id=dl__cnn__5ghz__block__none__s43__89f1a2 peak_cuda_memory_bytes=579083264
[results upsert] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/runs.csv: 75 row(s)
Seeds: random=44, numpy=44, torch=44
[trial filter] split=block trials=['01'] kept=9695/14478
[protocol] split=block trials_used=['01'] n_train=5477 n_test=1648 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05', '06'] test_users=['01', '02', '03', '04', '05', '06']
[trial filter] split=block trials=['01'] kept=5477/5477
[protocol] split=block trials_used=['01'] n_train=3396 n_test=179 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05', '06'] test_users=['01', '02', '03', '04', '05', '06']
[CNN] 5 GHz/block fold=single parameters=76308
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] 5 GHz/block fold=single epoch 01/70: train_loss=3.9415 train_acc=0.0244 val_loss=3.9016 val_acc=0.0615 seconds=2.4
[CNN] 5 GHz/block fold=single epoch 02/70: train_loss=3.8612 train_acc=0.0618 val_loss=3.8066 val_acc=0.0559 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 03/70: train_loss=3.7047 train_acc=0.0771 val_loss=3.6370 val_acc=0.0894 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 04/70: train_loss=3.5032 train_acc=0.1054 val_loss=3.5349 val_acc=0.1453 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 05/70: train_loss=3.3821 train_acc=0.1134 val_loss=3.5013 val_acc=0.0726 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 06/70: train_loss=3.2899 train_acc=0.1357 val_loss=3.4291 val_acc=0.1006 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 07/70: train_loss=3.1866 train_acc=0.1405 val_loss=3.3202 val_acc=0.1173 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 08/70: train_loss=3.0905 train_acc=0.1711 val_loss=3.3624 val_acc=0.1061 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 09/70: train_loss=3.0305 train_acc=0.1770 val_loss=3.2818 val_acc=0.1285 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 10/70: train_loss=2.9673 train_acc=0.1835 val_loss=3.5636 val_acc=0.0894 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 11/70: train_loss=2.9026 train_acc=0.1979 val_loss=3.2822 val_acc=0.1341 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 12/70: train_loss=2.8370 train_acc=0.2067 val_loss=3.1481 val_acc=0.1732 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 13/70: train_loss=2.7834 train_acc=0.2182 val_loss=3.5153 val_acc=0.1397 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 14/70: train_loss=2.7234 train_acc=0.2317 val_loss=3.0511 val_acc=0.1899 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 15/70: train_loss=2.6510 train_acc=0.2556 val_loss=3.2990 val_acc=0.1564 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 16/70: train_loss=2.6063 train_acc=0.2518 val_loss=3.1227 val_acc=0.2011 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 17/70: train_loss=2.5428 train_acc=0.2700 val_loss=3.1094 val_acc=0.1844 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 18/70: train_loss=2.5425 train_acc=0.2765 val_loss=3.1161 val_acc=0.1732 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 19/70: train_loss=2.4660 train_acc=0.2880 val_loss=3.3233 val_acc=0.1788 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 20/70: train_loss=2.4067 train_acc=0.3039 val_loss=2.9680 val_acc=0.2179 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 21/70: train_loss=2.3895 train_acc=0.3065 val_loss=2.9307 val_acc=0.2346 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 22/70: train_loss=2.3420 train_acc=0.3195 val_loss=2.8330 val_acc=0.2458 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 23/70: train_loss=2.3088 train_acc=0.3165 val_loss=2.9018 val_acc=0.2291 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 24/70: train_loss=2.2536 train_acc=0.3333 val_loss=2.8936 val_acc=0.2514 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 25/70: train_loss=2.2319 train_acc=0.3445 val_loss=2.9216 val_acc=0.2793 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 26/70: train_loss=2.2501 train_acc=0.3372 val_loss=2.9175 val_acc=0.2793 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 27/70: train_loss=2.1793 train_acc=0.3598 val_loss=2.8130 val_acc=0.2514 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 28/70: train_loss=2.1231 train_acc=0.3622 val_loss=2.8366 val_acc=0.2402 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 29/70: train_loss=2.0919 train_acc=0.3749 val_loss=2.9064 val_acc=0.2626 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 30/70: train_loss=2.1042 train_acc=0.3701 val_loss=2.8792 val_acc=0.2346 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 31/70: train_loss=2.0759 train_acc=0.3754 val_loss=2.9063 val_acc=0.2458 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 32/70: train_loss=2.0255 train_acc=0.3849 val_loss=2.9940 val_acc=0.2235 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 33/70: train_loss=2.0024 train_acc=0.4072 val_loss=2.7501 val_acc=0.2849 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 34/70: train_loss=1.9914 train_acc=0.4014 val_loss=3.0349 val_acc=0.2402 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 35/70: train_loss=1.9484 train_acc=0.4211 val_loss=2.7738 val_acc=0.2961 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 36/70: train_loss=1.9137 train_acc=0.4314 val_loss=2.6665 val_acc=0.2793 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 37/70: train_loss=1.8836 train_acc=0.4320 val_loss=3.2314 val_acc=0.2067 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 38/70: train_loss=1.8475 train_acc=0.4455 val_loss=2.6868 val_acc=0.3017 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 39/70: train_loss=1.8469 train_acc=0.4464 val_loss=2.7103 val_acc=0.2849 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 40/70: train_loss=1.8378 train_acc=0.4373 val_loss=2.8857 val_acc=0.2849 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 41/70: train_loss=1.7949 train_acc=0.4573 val_loss=2.7477 val_acc=0.2849 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 42/70: train_loss=1.8275 train_acc=0.4455 val_loss=3.0222 val_acc=0.2737 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 43/70: train_loss=1.7875 train_acc=0.4547 val_loss=2.9719 val_acc=0.2682 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 44/70: train_loss=1.7509 train_acc=0.4661 val_loss=2.7615 val_acc=0.2961 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 45/70: train_loss=1.7206 train_acc=0.4761 val_loss=2.9570 val_acc=0.2458 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 46/70: train_loss=1.6931 train_acc=0.4962 val_loss=3.1011 val_acc=0.2682 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 47/70: train_loss=1.6676 train_acc=0.4935 val_loss=2.9323 val_acc=0.2905 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 48/70: train_loss=1.6673 train_acc=0.4894 val_loss=2.7729 val_acc=0.3073 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 49/70: train_loss=1.6616 train_acc=0.4971 val_loss=2.8626 val_acc=0.3128 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 50/70: train_loss=1.6421 train_acc=0.5082 val_loss=3.1937 val_acc=0.2570 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 51/70: train_loss=1.6516 train_acc=0.4991 val_loss=2.9360 val_acc=0.2682 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 52/70: train_loss=1.6163 train_acc=0.5029 val_loss=2.9324 val_acc=0.2682 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 53/70: train_loss=1.5578 train_acc=0.5277 val_loss=2.8411 val_acc=0.3184 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 54/70: train_loss=1.5953 train_acc=0.5118 val_loss=3.6562 val_acc=0.2402 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 55/70: train_loss=1.6068 train_acc=0.5065 val_loss=3.0676 val_acc=0.2849 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 56/70: train_loss=1.5182 train_acc=0.5524 val_loss=2.8177 val_acc=0.3017 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 57/70: train_loss=1.5050 train_acc=0.5350 val_loss=3.0503 val_acc=0.2961 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 58/70: train_loss=1.5257 train_acc=0.5271 val_loss=2.8430 val_acc=0.2961 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 59/70: train_loss=1.4848 train_acc=0.5451 val_loss=2.8738 val_acc=0.3240 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 60/70: train_loss=1.4882 train_acc=0.5501 val_loss=2.8195 val_acc=0.3128 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 61/70: train_loss=1.4563 train_acc=0.5545 val_loss=2.9532 val_acc=0.3073 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 62/70: train_loss=1.4633 train_acc=0.5486 val_loss=3.3993 val_acc=0.2514 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 63/70: train_loss=1.4349 train_acc=0.5645 val_loss=2.9186 val_acc=0.2961 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 64/70: train_loss=1.4135 train_acc=0.5663 val_loss=2.8303 val_acc=0.3575 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 65/70: train_loss=1.4364 train_acc=0.5589 val_loss=3.0515 val_acc=0.2961 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 66/70: train_loss=1.4090 train_acc=0.5565 val_loss=2.9360 val_acc=0.3073 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 67/70: train_loss=1.3815 train_acc=0.5727 val_loss=2.8368 val_acc=0.3352 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 68/70: train_loss=1.3509 train_acc=0.5754 val_loss=3.0070 val_acc=0.3017 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 69/70: train_loss=1.3644 train_acc=0.5833 val_loss=2.9099 val_acc=0.3296 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 70/70: train_loss=1.3272 train_acc=0.5954 val_loss=3.2715 val_acc=0.2570 seconds=0.2

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__5ghz__block__none__s44__d87d56.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__5ghz__block__none__s44__d87d56/training_curves.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL GPU] run_id=dl__cnn__5ghz__block__none__s44__d87d56 peak_cuda_memory_bytes=579083264
[results upsert] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/runs.csv: 76 row(s)
[DL seeds] mean +/- std across seeds written to tables/seed_summary; LOVO uses each seed's fold mean and keeps within-seed fold std separate.

=== Fusion ===
[window arrays] cache path: /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/.cache/dataframes/preproc=norm-none/feat=win60-step0/window_arrays/fusion
[window arrays cache hit] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/.cache/dataframes/preproc=norm-none/feat=win60-step0/window_arrays/fusion
[window arrays] 2.4 GHz: shape=(13568, 9, 50, 60), dtype=float16
[window arrays] 2.4 GHz anchors: ['esp_01', 'esp_02', 'esp_03', 'esp_04', 'esp_05', 'esp_07', 'esp_08', 'esp_09', 'esp_10']
[window arrays] 5 GHz: shape=(13568, 10, 56, 60), dtype=float16
[window arrays] 5 GHz anchors: ['esp_11', 'esp_12', 'esp_13', 'esp_14', 'esp_15', 'esp_16', 'esp_17', 'esp_18', 'esp_19', 'esp_20']
2.4 GHz: anchors=9, subcarriers=50, windows=13568
5 GHz: anchors=10, subcarriers=56, windows=13568
Fusion N PASS: 13568 windows
WINDOW IDENTITY PASS: Fusion (13568 windows)
[trial filter] split=block trials=['01'] kept=8889/13568
[protocol] split=block trials_used=['01'] n_train=4934 n_test=1388 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05', '06'] test_users=['01', '02', '03', '04', '05', '06']
[trial filter] split=block trials=['01'] kept=8889/13568
[protocol] split=block trials_used=['01'] n_train=4934 n_test=1388 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05', '06'] test_users=['01', '02', '03', '04', '05', '06']
SPLIT IDENTITY PASS: Fusion/block fold=1 train=4934 test=1388
Seeds: random=42, numpy=42, torch=42
[trial filter] split=block trials=['01'] kept=8889/13568
[protocol] split=block trials_used=['01'] n_train=4934 n_test=1388 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05', '06'] test_users=['01', '02', '03', '04', '05', '06']
[trial filter] split=block trials=['01'] kept=4934/4934
[protocol] split=block trials_used=['01'] n_train=3003 n_test=150 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05', '06'] test_users=['01', '02', '03', '04', '05', '06']
[CNN] Fusion/block fold=single parameters=138708
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] Fusion/block fold=single epoch 01/70: train_loss=3.9444 train_acc=0.0263 val_loss=3.9273 val_acc=0.0333 seconds=2.5
[CNN] Fusion/block fold=single epoch 02/70: train_loss=3.8561 train_acc=0.0829 val_loss=3.8535 val_acc=0.0667 seconds=0.3
[CNN] Fusion/block fold=single epoch 03/70: train_loss=3.6991 train_acc=0.1002 val_loss=3.7131 val_acc=0.0867 seconds=0.3
[CNN] Fusion/block fold=single epoch 04/70: train_loss=3.4822 train_acc=0.1275 val_loss=3.4785 val_acc=0.1133 seconds=0.3
[CNN] Fusion/block fold=single epoch 05/70: train_loss=3.2490 train_acc=0.1552 val_loss=3.3816 val_acc=0.1467 seconds=0.3
[CNN] Fusion/block fold=single epoch 06/70: train_loss=3.0437 train_acc=0.1858 val_loss=3.3282 val_acc=0.1133 seconds=0.4
[CNN] Fusion/block fold=single epoch 07/70: train_loss=2.8718 train_acc=0.2261 val_loss=3.2356 val_acc=0.1600 seconds=0.3
[CNN] Fusion/block fold=single epoch 08/70: train_loss=2.7396 train_acc=0.2501 val_loss=3.0733 val_acc=0.1333 seconds=0.3
[CNN] Fusion/block fold=single epoch 09/70: train_loss=2.5952 train_acc=0.2840 val_loss=3.6532 val_acc=0.1200 seconds=0.4
[CNN] Fusion/block fold=single epoch 10/70: train_loss=2.4920 train_acc=0.3120 val_loss=3.0984 val_acc=0.1400 seconds=0.4
[CNN] Fusion/block fold=single epoch 11/70: train_loss=2.3384 train_acc=0.3510 val_loss=2.8212 val_acc=0.1867 seconds=0.4
[CNN] Fusion/block fold=single epoch 12/70: train_loss=2.2260 train_acc=0.3706 val_loss=2.7816 val_acc=0.2333 seconds=0.4
[CNN] Fusion/block fold=single epoch 13/70: train_loss=2.1449 train_acc=0.3896 val_loss=3.3677 val_acc=0.1600 seconds=0.3
[CNN] Fusion/block fold=single epoch 14/70: train_loss=2.0401 train_acc=0.4169 val_loss=3.0030 val_acc=0.2067 seconds=0.3
[CNN] Fusion/block fold=single epoch 15/70: train_loss=1.9512 train_acc=0.4439 val_loss=2.8270 val_acc=0.2267 seconds=0.4
[CNN] Fusion/block fold=single epoch 16/70: train_loss=1.8754 train_acc=0.4569 val_loss=2.4967 val_acc=0.3133 seconds=0.3
[CNN] Fusion/block fold=single epoch 17/70: train_loss=1.8069 train_acc=0.4772 val_loss=3.4712 val_acc=0.1467 seconds=0.4
[CNN] Fusion/block fold=single epoch 18/70: train_loss=1.7319 train_acc=0.4888 val_loss=2.6773 val_acc=0.2067 seconds=0.4
[CNN] Fusion/block fold=single epoch 19/70: train_loss=1.6832 train_acc=0.5035 val_loss=2.4096 val_acc=0.3000 seconds=0.4
[CNN] Fusion/block fold=single epoch 20/70: train_loss=1.6225 train_acc=0.5152 val_loss=2.6722 val_acc=0.2333 seconds=0.4
[CNN] Fusion/block fold=single epoch 21/70: train_loss=1.5171 train_acc=0.5598 val_loss=2.6891 val_acc=0.3067 seconds=0.3
[CNN] Fusion/block fold=single epoch 22/70: train_loss=1.4764 train_acc=0.5614 val_loss=2.7233 val_acc=0.2733 seconds=0.3
[CNN] Fusion/block fold=single epoch 23/70: train_loss=1.4292 train_acc=0.5748 val_loss=2.5518 val_acc=0.3467 seconds=0.3
[CNN] Fusion/block fold=single epoch 24/70: train_loss=1.3528 train_acc=0.5954 val_loss=3.6381 val_acc=0.2200 seconds=0.3
[CNN] Fusion/block fold=single epoch 25/70: train_loss=1.2960 train_acc=0.6057 val_loss=3.6896 val_acc=0.1933 seconds=0.4
[CNN] Fusion/block fold=single epoch 26/70: train_loss=1.2471 train_acc=0.6337 val_loss=2.5844 val_acc=0.3267 seconds=0.4
[CNN] Fusion/block fold=single epoch 27/70: train_loss=1.1856 train_acc=0.6454 val_loss=2.8668 val_acc=0.2733 seconds=0.3
[CNN] Fusion/block fold=single epoch 28/70: train_loss=1.1585 train_acc=0.6487 val_loss=2.6560 val_acc=0.3133 seconds=0.4
[CNN] Fusion/block fold=single epoch 29/70: train_loss=1.1123 train_acc=0.6633 val_loss=2.4320 val_acc=0.3000 seconds=0.3
[CNN] Fusion/block fold=single epoch 30/70: train_loss=1.0617 train_acc=0.6780 val_loss=3.1709 val_acc=0.2600 seconds=0.4
[CNN] Fusion/block fold=single epoch 31/70: train_loss=1.0164 train_acc=0.6940 val_loss=2.7039 val_acc=0.2933 seconds=0.3
[CNN] Fusion/block fold=single epoch 32/70: train_loss=0.9657 train_acc=0.7136 val_loss=3.4390 val_acc=0.2533 seconds=0.4
[CNN] Fusion/block fold=single epoch 33/70: train_loss=0.9239 train_acc=0.7276 val_loss=2.0441 val_acc=0.4133 seconds=0.4
[CNN] Fusion/block fold=single epoch 34/70: train_loss=0.9222 train_acc=0.7239 val_loss=2.8277 val_acc=0.3200 seconds=0.4
[CNN] Fusion/block fold=single epoch 35/70: train_loss=0.8969 train_acc=0.7289 val_loss=2.3506 val_acc=0.3333 seconds=0.4
[CNN] Fusion/block fold=single epoch 36/70: train_loss=0.8831 train_acc=0.7273 val_loss=2.1354 val_acc=0.4000 seconds=0.4
[CNN] Fusion/block fold=single epoch 37/70: train_loss=0.8268 train_acc=0.7572 val_loss=2.0491 val_acc=0.4800 seconds=0.4
[CNN] Fusion/block fold=single epoch 38/70: train_loss=0.7944 train_acc=0.7682 val_loss=2.2132 val_acc=0.4000 seconds=0.4
[CNN] Fusion/block fold=single epoch 39/70: train_loss=0.7482 train_acc=0.7742 val_loss=2.2520 val_acc=0.4067 seconds=0.4
[CNN] Fusion/block fold=single epoch 40/70: train_loss=0.7355 train_acc=0.7752 val_loss=2.3692 val_acc=0.4200 seconds=0.4
[CNN] Fusion/block fold=single epoch 41/70: train_loss=0.6996 train_acc=0.7922 val_loss=2.2221 val_acc=0.4133 seconds=0.4
[CNN] Fusion/block fold=single epoch 42/70: train_loss=0.7114 train_acc=0.7822 val_loss=3.0797 val_acc=0.3200 seconds=0.4
[CNN] Fusion/block fold=single epoch 43/70: train_loss=0.7008 train_acc=0.7899 val_loss=5.8929 val_acc=0.1800 seconds=0.3
[CNN] Fusion/block fold=single epoch 44/70: train_loss=0.6584 train_acc=0.8079 val_loss=2.2384 val_acc=0.4067 seconds=0.4
[CNN] Fusion/block fold=single epoch 45/70: train_loss=0.6289 train_acc=0.8198 val_loss=2.9512 val_acc=0.3067 seconds=0.4
[CNN] Fusion/block fold=single epoch 46/70: train_loss=0.6414 train_acc=0.8015 val_loss=2.6526 val_acc=0.3933 seconds=0.4
[CNN] Fusion/block fold=single epoch 47/70: train_loss=0.6046 train_acc=0.8212 val_loss=2.9072 val_acc=0.3533 seconds=0.4
[CNN] Fusion/block fold=single epoch 48/70: train_loss=0.5861 train_acc=0.8228 val_loss=2.2970 val_acc=0.4133 seconds=0.4
[CNN] Fusion/block fold=single epoch 49/70: train_loss=0.5778 train_acc=0.8318 val_loss=4.1736 val_acc=0.2333 seconds=0.4
[CNN] Fusion/block fold=single epoch 50/70: train_loss=0.5413 train_acc=0.8348 val_loss=2.1061 val_acc=0.4933 seconds=0.4
[CNN] Fusion/block fold=single epoch 51/70: train_loss=0.5293 train_acc=0.8465 val_loss=3.1856 val_acc=0.3200 seconds=0.4
[CNN] Fusion/block fold=single epoch 52/70: train_loss=0.5054 train_acc=0.8448 val_loss=2.5647 val_acc=0.4133 seconds=0.4
[CNN] Fusion/block fold=single epoch 53/70: train_loss=0.4950 train_acc=0.8518 val_loss=3.0801 val_acc=0.3267 seconds=0.4
[CNN] Fusion/block fold=single epoch 54/70: train_loss=0.4485 train_acc=0.8735 val_loss=2.1861 val_acc=0.4600 seconds=0.4
[CNN] Fusion/block fold=single epoch 55/70: train_loss=0.4574 train_acc=0.8638 val_loss=3.2994 val_acc=0.3133 seconds=0.4
[CNN] Fusion/block fold=single epoch 56/70: train_loss=0.4277 train_acc=0.8831 val_loss=2.3782 val_acc=0.4467 seconds=0.4
[CNN] Fusion/block fold=single epoch 57/70: train_loss=0.4335 train_acc=0.8668 val_loss=2.5884 val_acc=0.3733 seconds=0.4
[CNN] Fusion/block fold=single epoch 58/70: train_loss=0.4219 train_acc=0.8768 val_loss=2.7221 val_acc=0.3667 seconds=0.3
[CNN] Fusion/block fold=single epoch 59/70: train_loss=0.4010 train_acc=0.8858 val_loss=3.1732 val_acc=0.3267 seconds=0.4
[CNN] Fusion/block fold=single epoch 60/70: train_loss=0.4154 train_acc=0.8755 val_loss=3.6672 val_acc=0.3200 seconds=0.4
[CNN] Fusion/block fold=single epoch 61/70: train_loss=0.3927 train_acc=0.8801 val_loss=2.2341 val_acc=0.4800 seconds=0.4
[CNN] Fusion/block fold=single epoch 62/70: train_loss=0.3941 train_acc=0.8728 val_loss=2.9400 val_acc=0.3200 seconds=0.4
[CNN] Fusion/block fold=single epoch 63/70: train_loss=0.3647 train_acc=0.9001 val_loss=2.2095 val_acc=0.4467 seconds=0.4
[CNN] Fusion/block fold=single epoch 64/70: train_loss=0.3533 train_acc=0.8974 val_loss=2.2591 val_acc=0.4733 seconds=0.4
[CNN] Fusion/block fold=single epoch 65/70: train_loss=0.3749 train_acc=0.8864 val_loss=2.5957 val_acc=0.4267 seconds=0.4
[CNN] early stopping at epoch 65; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__fusion__block__none__s42__a8e3cb.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__fusion__block__none__s42__a8e3cb/training_curves.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL GPU] run_id=dl__cnn__fusion__block__none__s42__a8e3cb peak_cuda_memory_bytes=978418688
[results upsert] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/runs.csv: 77 row(s)
Seeds: random=43, numpy=43, torch=43
[trial filter] split=block trials=['01'] kept=8889/13568
[protocol] split=block trials_used=['01'] n_train=4934 n_test=1388 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05', '06'] test_users=['01', '02', '03', '04', '05', '06']
[trial filter] split=block trials=['01'] kept=4934/4934
[protocol] split=block trials_used=['01'] n_train=3003 n_test=150 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05', '06'] test_users=['01', '02', '03', '04', '05', '06']
[CNN] Fusion/block fold=single parameters=138708
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] Fusion/block fold=single epoch 01/70: train_loss=3.9437 train_acc=0.0343 val_loss=3.9039 val_acc=0.0467 seconds=2.4
[CNN] Fusion/block fold=single epoch 02/70: train_loss=3.8625 train_acc=0.0736 val_loss=3.8068 val_acc=0.0333 seconds=0.4
[CNN] Fusion/block fold=single epoch 03/70: train_loss=3.7021 train_acc=0.0919 val_loss=3.6180 val_acc=0.1133 seconds=0.3
[CNN] Fusion/block fold=single epoch 04/70: train_loss=3.4806 train_acc=0.1269 val_loss=3.4168 val_acc=0.1533 seconds=0.4
[CNN] Fusion/block fold=single epoch 05/70: train_loss=3.2476 train_acc=0.1608 val_loss=3.3513 val_acc=0.1533 seconds=0.4
[CNN] Fusion/block fold=single epoch 06/70: train_loss=3.0446 train_acc=0.1921 val_loss=3.0806 val_acc=0.2133 seconds=0.4
[CNN] Fusion/block fold=single epoch 07/70: train_loss=2.8318 train_acc=0.2361 val_loss=3.0205 val_acc=0.1867 seconds=0.4
[CNN] Fusion/block fold=single epoch 08/70: train_loss=2.6781 train_acc=0.2561 val_loss=3.1299 val_acc=0.1733 seconds=0.4
[CNN] Fusion/block fold=single epoch 09/70: train_loss=2.5313 train_acc=0.2900 val_loss=3.4542 val_acc=0.1400 seconds=0.3
[CNN] Fusion/block fold=single epoch 10/70: train_loss=2.4075 train_acc=0.3217 val_loss=2.6487 val_acc=0.2867 seconds=0.4
[CNN] Fusion/block fold=single epoch 11/70: train_loss=2.2879 train_acc=0.3580 val_loss=2.7662 val_acc=0.2333 seconds=0.4
[CNN] Fusion/block fold=single epoch 12/70: train_loss=2.1755 train_acc=0.3876 val_loss=3.0148 val_acc=0.2333 seconds=0.4
[CNN] Fusion/block fold=single epoch 13/70: train_loss=2.0342 train_acc=0.4169 val_loss=4.5293 val_acc=0.1333 seconds=0.3
[CNN] Fusion/block fold=single epoch 14/70: train_loss=1.9596 train_acc=0.4232 val_loss=2.6139 val_acc=0.2667 seconds=0.3
[CNN] Fusion/block fold=single epoch 15/70: train_loss=1.8815 train_acc=0.4552 val_loss=2.9783 val_acc=0.2333 seconds=0.4
[CNN] Fusion/block fold=single epoch 16/70: train_loss=1.7847 train_acc=0.4772 val_loss=2.7292 val_acc=0.2133 seconds=0.4
[CNN] Fusion/block fold=single epoch 17/70: train_loss=1.7249 train_acc=0.4918 val_loss=4.1550 val_acc=0.1333 seconds=0.4
[CNN] Fusion/block fold=single epoch 18/70: train_loss=1.6426 train_acc=0.5198 val_loss=2.5935 val_acc=0.3133 seconds=0.4
[CNN] Fusion/block fold=single epoch 19/70: train_loss=1.5573 train_acc=0.5311 val_loss=3.8909 val_acc=0.1400 seconds=0.4
[CNN] Fusion/block fold=single epoch 20/70: train_loss=1.5125 train_acc=0.5541 val_loss=2.7656 val_acc=0.2600 seconds=0.4
[CNN] Fusion/block fold=single epoch 21/70: train_loss=1.4352 train_acc=0.5794 val_loss=2.8470 val_acc=0.2533 seconds=0.4
[CNN] Fusion/block fold=single epoch 22/70: train_loss=1.4046 train_acc=0.5764 val_loss=2.9484 val_acc=0.2533 seconds=0.4
[CNN] Fusion/block fold=single epoch 23/70: train_loss=1.3144 train_acc=0.6154 val_loss=2.2584 val_acc=0.4133 seconds=0.4
[CNN] Fusion/block fold=single epoch 24/70: train_loss=1.2832 train_acc=0.6210 val_loss=2.4471 val_acc=0.3400 seconds=0.4
[CNN] Fusion/block fold=single epoch 25/70: train_loss=1.2289 train_acc=0.6307 val_loss=2.7876 val_acc=0.3133 seconds=0.4
[CNN] Fusion/block fold=single epoch 26/70: train_loss=1.1642 train_acc=0.6573 val_loss=3.3533 val_acc=0.2200 seconds=0.4
[CNN] Fusion/block fold=single epoch 27/70: train_loss=1.1355 train_acc=0.6580 val_loss=3.0139 val_acc=0.2533 seconds=0.4
[CNN] Fusion/block fold=single epoch 28/70: train_loss=1.0647 train_acc=0.6730 val_loss=3.2537 val_acc=0.2267 seconds=0.4
[CNN] Fusion/block fold=single epoch 29/70: train_loss=1.0333 train_acc=0.6986 val_loss=2.3739 val_acc=0.4000 seconds=0.4
[CNN] Fusion/block fold=single epoch 30/70: train_loss=0.9877 train_acc=0.7083 val_loss=2.9793 val_acc=0.2600 seconds=0.4
[CNN] Fusion/block fold=single epoch 31/70: train_loss=0.9528 train_acc=0.7103 val_loss=3.3490 val_acc=0.2200 seconds=0.4
[CNN] Fusion/block fold=single epoch 32/70: train_loss=0.9324 train_acc=0.7196 val_loss=2.5325 val_acc=0.3467 seconds=0.4
[CNN] Fusion/block fold=single epoch 33/70: train_loss=0.8917 train_acc=0.7376 val_loss=2.5623 val_acc=0.3667 seconds=0.4
[CNN] Fusion/block fold=single epoch 34/70: train_loss=0.8505 train_acc=0.7502 val_loss=2.5307 val_acc=0.3733 seconds=0.4
[CNN] Fusion/block fold=single epoch 35/70: train_loss=0.8411 train_acc=0.7566 val_loss=2.4721 val_acc=0.3467 seconds=0.3
[CNN] Fusion/block fold=single epoch 36/70: train_loss=0.8066 train_acc=0.7589 val_loss=4.1024 val_acc=0.1933 seconds=0.3
[CNN] Fusion/block fold=single epoch 37/70: train_loss=0.7729 train_acc=0.7716 val_loss=2.7791 val_acc=0.3000 seconds=0.3
[CNN] Fusion/block fold=single epoch 38/70: train_loss=0.7531 train_acc=0.7749 val_loss=2.2860 val_acc=0.4267 seconds=0.4
[CNN] Fusion/block fold=single epoch 39/70: train_loss=0.7220 train_acc=0.7889 val_loss=2.2887 val_acc=0.4467 seconds=0.4
[CNN] Fusion/block fold=single epoch 40/70: train_loss=0.6767 train_acc=0.8052 val_loss=2.3242 val_acc=0.3400 seconds=0.4
[CNN] Fusion/block fold=single epoch 41/70: train_loss=0.6615 train_acc=0.8009 val_loss=2.3305 val_acc=0.3933 seconds=0.4
[CNN] Fusion/block fold=single epoch 42/70: train_loss=0.6455 train_acc=0.8055 val_loss=2.2744 val_acc=0.4200 seconds=0.4
[CNN] Fusion/block fold=single epoch 43/70: train_loss=0.6384 train_acc=0.8072 val_loss=2.4754 val_acc=0.4067 seconds=0.4
[CNN] Fusion/block fold=single epoch 44/70: train_loss=0.6021 train_acc=0.8195 val_loss=3.0324 val_acc=0.3267 seconds=0.4
[CNN] Fusion/block fold=single epoch 45/70: train_loss=0.5902 train_acc=0.8265 val_loss=3.8913 val_acc=0.2667 seconds=0.4
[CNN] Fusion/block fold=single epoch 46/70: train_loss=0.5561 train_acc=0.8378 val_loss=2.9545 val_acc=0.3200 seconds=0.4
[CNN] Fusion/block fold=single epoch 47/70: train_loss=0.5221 train_acc=0.8535 val_loss=2.2262 val_acc=0.4533 seconds=0.4
[CNN] Fusion/block fold=single epoch 48/70: train_loss=0.5146 train_acc=0.8531 val_loss=3.1595 val_acc=0.3533 seconds=0.4
[CNN] Fusion/block fold=single epoch 49/70: train_loss=0.5112 train_acc=0.8518 val_loss=3.8058 val_acc=0.2467 seconds=0.4
[CNN] Fusion/block fold=single epoch 50/70: train_loss=0.5022 train_acc=0.8515 val_loss=2.2609 val_acc=0.4400 seconds=0.4
[CNN] Fusion/block fold=single epoch 51/70: train_loss=0.5061 train_acc=0.8465 val_loss=3.2778 val_acc=0.3200 seconds=0.4
[CNN] Fusion/block fold=single epoch 52/70: train_loss=0.5129 train_acc=0.8435 val_loss=2.7961 val_acc=0.3667 seconds=0.4
[CNN] Fusion/block fold=single epoch 53/70: train_loss=0.4710 train_acc=0.8575 val_loss=2.5707 val_acc=0.4133 seconds=0.4
[CNN] Fusion/block fold=single epoch 54/70: train_loss=0.4601 train_acc=0.8595 val_loss=2.2708 val_acc=0.4467 seconds=0.4
[CNN] Fusion/block fold=single epoch 55/70: train_loss=0.4323 train_acc=0.8785 val_loss=2.4457 val_acc=0.4333 seconds=0.4
[CNN] Fusion/block fold=single epoch 56/70: train_loss=0.4189 train_acc=0.8751 val_loss=2.1477 val_acc=0.4733 seconds=0.4
[CNN] Fusion/block fold=single epoch 57/70: train_loss=0.4040 train_acc=0.8838 val_loss=2.9293 val_acc=0.3867 seconds=0.4
[CNN] Fusion/block fold=single epoch 58/70: train_loss=0.3994 train_acc=0.8815 val_loss=3.1466 val_acc=0.3467 seconds=0.4
[CNN] Fusion/block fold=single epoch 59/70: train_loss=0.3879 train_acc=0.8864 val_loss=2.4698 val_acc=0.4400 seconds=0.4
[CNN] Fusion/block fold=single epoch 60/70: train_loss=0.3761 train_acc=0.8918 val_loss=2.3123 val_acc=0.4533 seconds=0.4
[CNN] Fusion/block fold=single epoch 61/70: train_loss=0.3485 train_acc=0.9008 val_loss=2.3245 val_acc=0.4267 seconds=0.4
[CNN] Fusion/block fold=single epoch 62/70: train_loss=0.3736 train_acc=0.8931 val_loss=3.4774 val_acc=0.2933 seconds=0.4
[CNN] Fusion/block fold=single epoch 63/70: train_loss=0.3566 train_acc=0.8918 val_loss=2.5587 val_acc=0.4400 seconds=0.4
[CNN] Fusion/block fold=single epoch 64/70: train_loss=0.3386 train_acc=0.9004 val_loss=2.4910 val_acc=0.4333 seconds=0.4
[CNN] Fusion/block fold=single epoch 65/70: train_loss=0.3156 train_acc=0.9101 val_loss=3.0784 val_acc=0.3667 seconds=0.4
[CNN] Fusion/block fold=single epoch 66/70: train_loss=0.3232 train_acc=0.9114 val_loss=2.4251 val_acc=0.4733 seconds=0.4
[CNN] Fusion/block fold=single epoch 67/70: train_loss=0.3229 train_acc=0.9094 val_loss=2.5217 val_acc=0.4000 seconds=0.4
[CNN] Fusion/block fold=single epoch 68/70: train_loss=0.3281 train_acc=0.9104 val_loss=2.7284 val_acc=0.4267 seconds=0.4
[CNN] Fusion/block fold=single epoch 69/70: train_loss=0.3062 train_acc=0.9074 val_loss=2.6427 val_acc=0.4400 seconds=0.4
[CNN] Fusion/block fold=single epoch 70/70: train_loss=0.2972 train_acc=0.9108 val_loss=3.2757 val_acc=0.3600 seconds=0.4

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__fusion__block__none__s43__89f1a2.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__fusion__block__none__s43__89f1a2/training_curves.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL GPU] run_id=dl__cnn__fusion__block__none__s43__89f1a2 peak_cuda_memory_bytes=978418688
[results upsert] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/runs.csv: 78 row(s)
Seeds: random=44, numpy=44, torch=44
[trial filter] split=block trials=['01'] kept=8889/13568
[protocol] split=block trials_used=['01'] n_train=4934 n_test=1388 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05', '06'] test_users=['01', '02', '03', '04', '05', '06']
[trial filter] split=block trials=['01'] kept=4934/4934
[protocol] split=block trials_used=['01'] n_train=3003 n_test=150 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05', '06'] test_users=['01', '02', '03', '04', '05', '06']
[CNN] Fusion/block fold=single parameters=138708
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] Fusion/block fold=single epoch 01/70: train_loss=3.9389 train_acc=0.0246 val_loss=3.8995 val_acc=0.0533 seconds=2.3
[CNN] Fusion/block fold=single epoch 02/70: train_loss=3.8453 train_acc=0.0776 val_loss=3.7608 val_acc=0.0600 seconds=0.4
[CNN] Fusion/block fold=single epoch 03/70: train_loss=3.6640 train_acc=0.0932 val_loss=3.6726 val_acc=0.0867 seconds=0.4
[CNN] Fusion/block fold=single epoch 04/70: train_loss=3.4436 train_acc=0.1375 val_loss=3.5036 val_acc=0.1533 seconds=0.4
[CNN] Fusion/block fold=single epoch 05/70: train_loss=3.2554 train_acc=0.1612 val_loss=3.3146 val_acc=0.1133 seconds=0.4
[CNN] Fusion/block fold=single epoch 06/70: train_loss=3.0794 train_acc=0.1785 val_loss=3.1399 val_acc=0.1400 seconds=0.4
[CNN] Fusion/block fold=single epoch 07/70: train_loss=2.8596 train_acc=0.2401 val_loss=3.4676 val_acc=0.1000 seconds=0.3
[CNN] Fusion/block fold=single epoch 08/70: train_loss=2.6990 train_acc=0.2604 val_loss=3.5592 val_acc=0.1333 seconds=0.4
[CNN] Fusion/block fold=single epoch 09/70: train_loss=2.5236 train_acc=0.3094 val_loss=2.9644 val_acc=0.1600 seconds=0.4
[CNN] Fusion/block fold=single epoch 10/70: train_loss=2.4086 train_acc=0.3270 val_loss=2.8958 val_acc=0.1867 seconds=0.3
[CNN] Fusion/block fold=single epoch 11/70: train_loss=2.2944 train_acc=0.3560 val_loss=2.6899 val_acc=0.2333 seconds=0.3
[CNN] Fusion/block fold=single epoch 12/70: train_loss=2.1764 train_acc=0.3879 val_loss=2.7073 val_acc=0.1800 seconds=0.4
[CNN] Fusion/block fold=single epoch 13/70: train_loss=2.0648 train_acc=0.4103 val_loss=2.7543 val_acc=0.2733 seconds=0.4
[CNN] Fusion/block fold=single epoch 14/70: train_loss=1.9586 train_acc=0.4409 val_loss=3.4342 val_acc=0.1933 seconds=0.3
[CNN] Fusion/block fold=single epoch 15/70: train_loss=1.8962 train_acc=0.4469 val_loss=2.8183 val_acc=0.2733 seconds=0.4
[CNN] Fusion/block fold=single epoch 16/70: train_loss=1.8065 train_acc=0.4719 val_loss=2.8511 val_acc=0.1933 seconds=0.4
[CNN] Fusion/block fold=single epoch 17/70: train_loss=1.7277 train_acc=0.4962 val_loss=2.5479 val_acc=0.2733 seconds=0.4
[CNN] Fusion/block fold=single epoch 18/70: train_loss=1.6608 train_acc=0.5082 val_loss=2.5463 val_acc=0.2867 seconds=0.4
[CNN] Fusion/block fold=single epoch 19/70: train_loss=1.5823 train_acc=0.5325 val_loss=2.5949 val_acc=0.2533 seconds=0.4
[CNN] Fusion/block fold=single epoch 20/70: train_loss=1.5210 train_acc=0.5431 val_loss=3.0587 val_acc=0.2267 seconds=0.4
[CNN] Fusion/block fold=single epoch 21/70: train_loss=1.4337 train_acc=0.5724 val_loss=2.4088 val_acc=0.3067 seconds=0.4
[CNN] Fusion/block fold=single epoch 22/70: train_loss=1.3858 train_acc=0.5897 val_loss=2.6622 val_acc=0.3267 seconds=0.4
[CNN] Fusion/block fold=single epoch 23/70: train_loss=1.3455 train_acc=0.5927 val_loss=2.6588 val_acc=0.2933 seconds=0.4
[CNN] Fusion/block fold=single epoch 24/70: train_loss=1.2668 train_acc=0.6144 val_loss=2.4174 val_acc=0.3067 seconds=0.3
[CNN] Fusion/block fold=single epoch 25/70: train_loss=1.2136 train_acc=0.6310 val_loss=2.1483 val_acc=0.3933 seconds=0.4
[CNN] Fusion/block fold=single epoch 26/70: train_loss=1.1769 train_acc=0.6404 val_loss=2.4496 val_acc=0.3200 seconds=0.4
[CNN] Fusion/block fold=single epoch 27/70: train_loss=1.1592 train_acc=0.6500 val_loss=2.0759 val_acc=0.3933 seconds=0.4
[CNN] Fusion/block fold=single epoch 28/70: train_loss=1.0937 train_acc=0.6747 val_loss=2.5723 val_acc=0.3533 seconds=0.4
[CNN] Fusion/block fold=single epoch 29/70: train_loss=1.0571 train_acc=0.6853 val_loss=2.1224 val_acc=0.4267 seconds=0.4
[CNN] Fusion/block fold=single epoch 30/70: train_loss=1.0061 train_acc=0.6896 val_loss=2.7338 val_acc=0.3133 seconds=0.4
[CNN] Fusion/block fold=single epoch 31/70: train_loss=0.9617 train_acc=0.7073 val_loss=3.3653 val_acc=0.2467 seconds=0.4
[CNN] Fusion/block fold=single epoch 32/70: train_loss=0.9337 train_acc=0.7249 val_loss=2.6971 val_acc=0.3333 seconds=0.4
[CNN] Fusion/block fold=single epoch 33/70: train_loss=0.9082 train_acc=0.7236 val_loss=2.5274 val_acc=0.3067 seconds=0.4
[CNN] Fusion/block fold=single epoch 34/70: train_loss=0.8704 train_acc=0.7343 val_loss=3.6781 val_acc=0.2467 seconds=0.4
[CNN] Fusion/block fold=single epoch 35/70: train_loss=0.8842 train_acc=0.7366 val_loss=4.7315 val_acc=0.2000 seconds=0.4
[CNN] Fusion/block fold=single epoch 36/70: train_loss=0.8765 train_acc=0.7283 val_loss=3.5076 val_acc=0.2333 seconds=0.4
[CNN] Fusion/block fold=single epoch 37/70: train_loss=0.8272 train_acc=0.7582 val_loss=4.0168 val_acc=0.2333 seconds=0.4
[CNN] Fusion/block fold=single epoch 38/70: train_loss=0.7671 train_acc=0.7776 val_loss=3.6454 val_acc=0.2667 seconds=0.4
[CNN] Fusion/block fold=single epoch 39/70: train_loss=0.7477 train_acc=0.7652 val_loss=2.1002 val_acc=0.4333 seconds=0.3
[CNN] Fusion/block fold=single epoch 40/70: train_loss=0.7126 train_acc=0.7852 val_loss=2.1544 val_acc=0.4533 seconds=0.3
[CNN] Fusion/block fold=single epoch 41/70: train_loss=0.6797 train_acc=0.8035 val_loss=2.7197 val_acc=0.3200 seconds=0.4
[CNN] Fusion/block fold=single epoch 42/70: train_loss=0.6729 train_acc=0.7902 val_loss=3.2864 val_acc=0.3200 seconds=0.4
[CNN] Fusion/block fold=single epoch 43/70: train_loss=0.6256 train_acc=0.8152 val_loss=3.7135 val_acc=0.2933 seconds=0.3
[CNN] Fusion/block fold=single epoch 44/70: train_loss=0.6167 train_acc=0.8145 val_loss=2.1798 val_acc=0.4467 seconds=0.4
[CNN] Fusion/block fold=single epoch 45/70: train_loss=0.5908 train_acc=0.8262 val_loss=2.3491 val_acc=0.4200 seconds=0.4
[CNN] Fusion/block fold=single epoch 46/70: train_loss=0.5695 train_acc=0.8348 val_loss=2.3265 val_acc=0.4333 seconds=0.4
[CNN] Fusion/block fold=single epoch 47/70: train_loss=0.5601 train_acc=0.8302 val_loss=4.3328 val_acc=0.2200 seconds=0.4
[CNN] Fusion/block fold=single epoch 48/70: train_loss=0.5564 train_acc=0.8378 val_loss=2.9094 val_acc=0.3400 seconds=0.3
[CNN] Fusion/block fold=single epoch 49/70: train_loss=0.5094 train_acc=0.8528 val_loss=1.9233 val_acc=0.4533 seconds=0.4
[CNN] Fusion/block fold=single epoch 50/70: train_loss=0.5103 train_acc=0.8515 val_loss=2.3609 val_acc=0.4333 seconds=0.4
[CNN] Fusion/block fold=single epoch 51/70: train_loss=0.4921 train_acc=0.8531 val_loss=2.5434 val_acc=0.4133 seconds=0.4
[CNN] Fusion/block fold=single epoch 52/70: train_loss=0.4883 train_acc=0.8601 val_loss=3.1801 val_acc=0.3200 seconds=0.4
[CNN] Fusion/block fold=single epoch 53/70: train_loss=0.4734 train_acc=0.8611 val_loss=2.8501 val_acc=0.3400 seconds=0.3
[CNN] Fusion/block fold=single epoch 54/70: train_loss=0.4777 train_acc=0.8535 val_loss=2.7438 val_acc=0.4000 seconds=0.3
[CNN] Fusion/block fold=single epoch 55/70: train_loss=0.4576 train_acc=0.8645 val_loss=2.2784 val_acc=0.4467 seconds=0.4
[CNN] early stopping at epoch 55; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:329: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__fusion__block__none__s44__d87d56.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__fusion__block__none__s44__d87d56/training_curves.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL GPU] run_id=dl__cnn__fusion__block__none__s44__d87d56 peak_cuda_memory_bytes=978418688
[results upsert] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/runs.csv: 79 row(s)
[DL seeds] mean +/- std across seeds written to tables/seed_summary; LOVO uses each seed's fold mean and keeps within-seed fold std separate.

In [8]:
cnn_summary, test_accuracy_comparison = show_dl_results(results_dir)
display(cnn_summary)

display(test_accuracy_comparison)

,run_id,timestamp,family,model,band,split,seed,normalization,baseline_scope,window_size,...,p90_distance_error_max,samples_mean,samples_std,samples_min,samples_max,majority_position_accuracy_min,majority_position_accuracy_max,majority_room_accuracy_min,majority_room_accuracy_max,n_test_windows
3,dl__cnn__2_4ghz__block__ebl-session__s42__df21ec,2026-07-22T18:36:31.182108+00:00,dl,cnn,2_4ghz,block,42.0,empty_baseline,session,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,dl__cnn__2_4ghz__block__ebl-session__s43__210c56,2026-07-22T18:36:47.242239+00:00,dl,cnn,2_4ghz,block,43.0,empty_baseline,session,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,dl__cnn__2_4ghz__block__ebl-session__s44__86f94f,2026-07-22T18:37:03.908150+00:00,dl,cnn,2_4ghz,block,44.0,empty_baseline,session,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,dl__cnn__5ghz__block__ebl-session__s42__df21ec,2026-07-22T18:37:26.695344+00:00,dl,cnn,5ghz,block,42.0,empty_baseline,session,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,dl__cnn__5ghz__block__ebl-session__s43__210c56,2026-07-22T18:37:44.903111+00:00,dl,cnn,5ghz,block,43.0,empty_baseline,session,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,dl__cnn__5ghz__block__ebl-session__s44__86f94f,2026-07-22T18:38:04.402553+00:00,dl,cnn,5ghz,block,44.0,empty_baseline,session,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,dl__cnn__fusion__block__ebl-session__s42__df21ec,2026-07-22T18:38:41.941273+00:00,dl,cnn,fusion,block,42.0,empty_baseline,session,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,dl__cnn__fusion__block__ebl-session__s43__210c56,2026-07-22T18:39:07.169167+00:00,dl,cnn,fusion,block,43.0,empty_baseline,session,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,dl__cnn__fusion__block__ebl-session__s44__86f94f,2026-07-22T18:39:27.186644+00:00,dl,cnn,fusion,block,44.0,empty_baseline,session,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,dl__cnn__2_4ghz__block__ebl-session__s42__eb2083,2026-07-22T22:25:24.462285+00:00,dl,cnn,2_4ghz,block,42.0,empty_baseline,session,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,dl__cnn__2_4ghz__block__ebl-session__s43__7d42d1,2026-07-22T22:25:41.299487+00:00,dl,cnn,2_4ghz,block,43.0,empty_baseline,session,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,dl__cnn__2_4ghz__block__ebl-session__s44__3f1421,2026-07-22T22:25:57.650859+00:00,dl,cnn,2_4ghz,block,44.0,empty_baseline,session,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,dl__cnn__5ghz__block__ebl-session__s42__eb2083,2026-07-22T22:26:18.424778+00:00,dl,cnn,5ghz,block,42.0,empty_baseline,session,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,dl__cnn__5ghz__block__ebl-session__s43__7d42d1,2026-07-22T22:26:38.575420+00:00,dl,cnn,5ghz,block,43.0,empty_baseline,session,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,dl__cnn__5ghz__block__ebl-session__s44__3f1421,2026-07-22T22:26:58.653328+00:00,dl,cnn,5ghz,block,44.0,empty_baseline,session,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,dl__cnn__fusion__block__ebl-session__s42__eb2083,2026-07-22T22:27:28.062797+00:00,dl,cnn,fusion,block,42.0,empty_baseline,session,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,dl__cnn__fusion__block__ebl-session__s43__7d42d1,2026-07-22T22:27:57.119251+00:00,dl,cnn,fusion,block,43.0,empty_baseline,session,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,dl__cnn__fusion__block__ebl-session__s44__3f1421,2026-07-22T22:28:25.104041+00:00,dl,cnn,fusion,block,44.0,empty_baseline,session,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,dl__cnn__2_4ghz__lovo__ebl-session__s42__9b1404,2026-07-23T13:48:02.786457+00:00,dl,cnn,2_4ghz,lovo,42.0,empty_baseline,session,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,dl__cnn__2_4ghz__lovo__ebl-session__s43__a89b5d,2026-07-23T13:49:57.671381+00:00,dl,cnn,2_4ghz,lovo,43.0,empty_baseline,session,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,dl__cnn__2_4ghz__lovo__ebl-session__s44__7b9bf2,2026-07-23T13:51:31.436316+00:00,dl,cnn,2_4ghz,lovo,44.0,empty_baseline,session,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,dl__cnn__5ghz__lovo__ebl-session__s42__9b1404,2026-07-23T13:53:57.387552+00:00,dl,cnn,5ghz,lovo,42.0,empty_baseline,session,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,dl__cnn__5ghz__lovo__ebl-session__s43__a89b5d,2026-07-23T13:55:51.186055+00:00,dl,cnn,5ghz,lovo,43.0,empty_baseline,session,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,dl__cnn__5ghz__lovo__ebl-session__s44__7b9bf2,2026-07-23T13:57:58.923697+00:00,dl,cnn,5ghz,lovo,44.0,empty_baseline,session,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,dl__cnn__fusion__lovo__ebl-session__s42__9b1404,2026-07-23T14:00:58.465944+00:00,dl,cnn,fusion,lovo,42.0,empty_baseline,session,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,dl__cnn__fusion__lovo__ebl-session__s43__a89b5d,2026-07-23T14:04:09.091103+00:00,dl,cnn,fusion,lovo,43.0,empty_baseline,session,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,dl__cnn__fusion__lovo__ebl-session__s44__7b9bf2,2026-07-23T14:08:05.305960+00:00,dl,cnn,fusion,lovo,44.0,empty_baseline,session,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,dl__cnn_room__fusion__lovo__ebl-session__s42__...,2026-07-24T11:05:15.109337+00:00,dl,cnn_room,fusion,lovo,42.0,empty_baseline,session,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,dl__cnn_room__fusion__lovo__ebl-session__s43__...,2026-07-24T11:08:25.003152+00:00,dl,cnn_room,fusion,lovo,43.0,empty_baseline,session,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,dl__cnn_room__fusion__lovo__ebl-session__s44__...,2026-07-24T11:12:11.839497+00:00,dl,cnn_room,fusion,lovo,44.0,empty_baseline,session,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,dl__cnn_room__fusion__lovo__none__s42__06abf8,2026-08-19T23:31:59.771277+00:00,dl,cnn_room,fusion,lovo,42.0,none,session,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,dl__cnn__2_4ghz__block__none__s42__fba578,2026-08-19T23:37:45.858038+00:00,dl,cnn,2_4ghz,block,42.0,none,session,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,dl__cnn__2_4ghz__block__none__s43__6f820c,2026-08-19T23:37:55.949196+00:00,dl,cnn,2_4ghz,block,43.0,none,session,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,dl__cnn__2_4ghz__block__none__s44__f8dec9,2026-08-19T23:38:04.043023+00:00,dl,cnn,2_4ghz,block,44.0,none,session,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,dl__cnn__5ghz__block__none__s42__fba578,2026-08-19T23:38:17.304209+00:00,dl,cnn,5ghz,block,42.0,none,session,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,dl__cnn__5ghz__block__none__s43__6f820c,2026-08-19T23:38:28.288379+00:00,dl,cnn,5ghz,block,43.0,none,session,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,dl__cnn__5ghz__block__none__s44__f8dec9,2026-08-19T23:38:37.072163+00:00,dl,cnn,5ghz,block,44.0,none,session,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,dl__cnn__fusion__block__none__s42__fba578,2026-08-19T23:39:14.313374+00:00,dl,cnn,fusion,block,42.0,none,session,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,dl__cnn__fusion__block__none__s43__6f820c,2026-08-19T23:39:27.400363+00:00,dl,cnn,fusion,block,43.0,none,session,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,dl__cnn__fusion__block__none__s44__f8dec9,2026-08-19T23:39:46.861363+00:00,dl,cnn,fusion,block,44.0,none,session,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,dl__cnn__2_4ghz__block__none__s42__a8e3cb,2026-08-19T23:49:38.292585+00:00,dl,cnn,2_4ghz,block,42.0,none,session,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,dl__cnn__2_4ghz__block__none__s43__89f1a2,2026-08-19T23:49:53.414671+00:00,dl,cnn,2_4ghz,block,43.0,none,session,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,dl__cnn__2_4ghz__block__none__s44__d87d56,2026-08-19T23:50:08.872315+00:00,dl,cnn,2_4ghz,block,44.0,none,session,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,dl__cnn__5ghz__block__none__s42__a8e3cb,2026-08-19T23:50:36.055814+00:00,dl,cnn,5ghz,block,42.0,none,session,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,dl__cnn__5ghz__block__none__s43__89f1a2,2026-08-19T23:50:53.004088+00:00,dl,cnn,5ghz,block,43.0,none,session,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,dl__cnn__5ghz__block__none__s44__d87d56,2026-08-19T23:51:14.328354+00:00,dl,cnn,5ghz,block,44.0,none,session,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,dl__cnn__fusion__block__none__s42__a8e3cb,2026-08-19T23:51:43.102369+00:00,dl,cnn,fusion,block,42.0,none,session,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,dl__cnn__fusion__block__none__s43__89f1a2,2026-08-19T23:52:14.165223+00:00,dl,cnn,fusion,block,43.0,none,session,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,dl__cnn__fusion__block__none__s44__d87d56,2026-08-19T23:52:38.915020+00:00,dl,cnn,fusion,block,44.0,none,session,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

      band model  seed  position_accuracy  parameter_count
3   2_4ghz   cnn  42.0           0.248563          76020.0
12  2_4ghz   cnn  42.0           0.286101          76020.0
61  2_4ghz   cnn  42.0           0.082927          76020.0
70  2_4ghz   cnn  42.0           0.307471          76020.0
4   2_4ghz   cnn  43.0           0.316092          76020.0
13  2_4ghz   cnn  43.0           0.276036          76020.0
62  2_4ghz   cnn  43.0           0.100000          76020.0
71  2_4ghz   cnn  43.0           0.272989          76020.0
5   2_4ghz   cnn  44.0           0.320402          76020.0
14  2_4ghz   cnn  44.0           0.293457          76020.0
63  2_4ghz   cnn  44.0           0.017073          76020.0
72  2_4ghz   cnn  44.0           0.307471          76020.0
42  2_4ghz    rf  42.0           0.834770              NaN
6     5ghz   cnn  42.0           0.290049          76308.0
15    5ghz   cnn  42.0           0.298067          76308.0
64    5ghz   cnn  42.0           0.026144          76308.0
73    5ghz   cnn  42.0           0.311286          76308.0
7     5ghz   cnn  43.0           0.307039          76308.0
16    5ghz   cnn  43.0           0.296661          76308.0
65    5ghz   cnn  43.0           0.156863          76308.0
74    5ghz   cnn  43.0           0.253641          76308.0
8     5ghz   cnn  44.0           0.324636          76308.0
17    5ghz   cnn  44.0           0.297012          76308.0
66    5ghz   cnn  44.0           0.021786          76308.0
75    5ghz   cnn  44.0           0.309466          76308.0
45    5ghz    rf  42.0           0.822209              NaN
9   fusion   cnn  42.0           0.489193         138708.0
18  fusion   cnn  42.0           0.404965         138708.0
67  fusion   cnn  42.0           0.279412         138708.0
76  fusion   cnn  42.0           0.448847         138708.0
10  fusion   cnn  43.0           0.462536         138708.0
19  fusion   cnn  43.0           0.378588         138708.0
68  fusion   cnn  43.0           0.029412         138708.0
77  fusion   cnn  43.0           0.457493         138708.0
11  fusion   cnn  44.0           0.398415         138708.0
20  fusion   cnn  44.0           0.410396         138708.0
69  fusion   cnn  44.0           0.220588         138708.0
78  fusion   cnn  44.0           0.400576         138708.0
48  fusion    rf  42.0           0.902017              NaN