## Multi-protocol CNN Raw CSI Experiments

This notebook runs the fixed-capacity CNN across block, LOVO, and cross-session protocols with one independent run per configured seed.

In [1]:
from __future__ import annotations

import pandas as pd
import torch

from utils.config import (
    ANCHOR_GROUPS,
    BANDS_TO_RUN,
    DATA_DIR,
    DEFAULT_CNN_PARAMS,
    DEFAULT_OVERLAP_SIZE,
    DEFAULT_WINDOW_SIZE,
    EXPECTED_ANCHORS,
    EXPECTED_SUBCARRIERS,
    SEEDS,
)
from utils.DL.dl_pipeline import (
    create_position_label_encoder,
    get_cache_path,
    get_results_path,
    prepare_dl_data,
    print_torch_environment,
    run_dl_experiments,
    show_dl_results,
)

### Configuration

In [8]:
CALIBRATION_MODE = "none"    # ("none", "packet_norm", "rssi")

CSV_PROCESSING_OPTIONS = {
    "max_workers": 1,
    "cache_dir": None,
    "use_cache": True,
    "force_reprocess": False,
    "min_rssi_dbm": -95.0,
}

MAGNITUDE_PROCESSING_OPTIONS = {
    "normalization": "empty_baseline",  # none | zscore | minmax | packet_minmax | empty_baseline
    "epsilon": 1e-8,
}
NORMALIZATION_BASELINE_SCOPE = "per_session"

FEATURE_EXTRACTION_OPTIONS = {
    "window_size": DEFAULT_WINDOW_SIZE,
    "overlap_size": DEFAULT_OVERLAP_SIZE,
    "require_all_esps": False,
}

BLOCK_COUNT = 10
TEST_SIZE = 0.30
VALIDATION_SIZE = 0.15
RANDOM_STATE = 42
FORCE_RETRAIN = False
SPLIT_MODES = ("block",)

CNN_PARAMS = {
    **DEFAULT_CNN_PARAMS,
    "model_label": "CNN",
    "epochs": 50,
    "patience": 15,
    "lr": 1e-3,
    "weight_decay": 1e-4,
    "random_state": RANDOM_STATE,
    "test_size": TEST_SIZE,
    "validation_size": VALIDATION_SIZE,
    "n_blocks": BLOCK_COUNT,
    "anchor_groups": ANCHOR_GROUPS,
    "torch_version": torch.__version__,
}

preproc_opts = dict(MAGNITUDE_PROCESSING_OPTIONS)
preproc_opts["baseline_scope"] = NORMALIZATION_BASELINE_SCOPE
feat_opts = dict(FEATURE_EXTRACTION_OPTIONS)

feature_cache_dir = get_cache_path(preproc_opts, feat_opts)
results_dir = get_results_path()
plots_dir = results_dir / "plots"
for directory in (plots_dir, results_dir / "predictions", results_dir / "tables"):
    directory.mkdir(parents=True, exist_ok=True)

print(f"Feature cache path: {feature_cache_dir}")
print(f"Results path: {results_dir}")

Feature cache path: /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/.cache/dataframes/preproc=norm-empty_baseline_scope-per_session/feat=win60-step0
Results path: /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results

### Environment

In [9]:
DEVICE = print_torch_environment(require_cuda=True)

torch.__version__: 2.11.0+cu128
torch.version.cuda: 12.8
torch.cuda.get_device_name(0): NVIDIA RTX PRO 6000 Blackwell Max-Q Workstation Edition
torch.cuda.get_device_capability(0): (12, 0)
CUDA matmul smoke test result: [[0.0, 1.0, 2.0, 3.0], [4.0, 5.0, 6.0, 7.0], [8.0, 9.0, 10.0, 11.0], [12.0, 13.0, 14.0, 15.0]] (PASS)

### Data

In [10]:
processed_magnitude_data, feature_dataframes, csv_diagnostics, magnitude_summary = prepare_dl_data(
    DATA_DIR,
    calibration_mode=CALIBRATION_MODE,
    csv_options=CSV_PROCESSING_OPTIONS,
    preproc_opts=preproc_opts,
    feat_opts=feat_opts,
)
display(magnitude_summary.head())

Scenarios present: 1
Locations: 53 | Users: 6 | ESPs: 19
[Z-0 inventory]
  total Z-0 files found: 171
  Z-0 count per (user, trial):
    (user=01, trial=01): 19
    (user=01, trial=02): 19
    (user=02, trial=01): 19
    (user=03, trial=01): 19
    (user=03, trial=02): 19
    (user=04, trial=01): 19
    (user=05, trial=01): 19
    (user=05, trial=02): 19
    (user=06, trial=01): 19
  breakdown by user / esp / trial:
    user=01 esp=01 trial=01: 1
    user=01 esp=01 trial=02: 1
    user=01 esp=02 trial=01: 1
    user=01 esp=02 trial=02: 1
    user=01 esp=03 trial=01: 1
    user=01 esp=03 trial=02: 1
    user=01 esp=04 trial=01: 1
    user=01 esp=04 trial=02: 1
    user=01 esp=05 trial=01: 1
    user=01 esp=05 trial=02: 1
    user=01 esp=07 trial=01: 1
    user=01 esp=07 trial=02: 1
    user=01 esp=08 trial=01: 1
    user=01 esp=08 trial=02: 1
    user=01 esp=09 trial=01: 1
    user=01 esp=09 trial=02: 1
    user=01 esp=10 trial=01: 1
    user=01 esp=10 trial=02: 1
    user=01 esp=11 trial=01: 1
    user=01 esp=11 trial=02: 1
    user=01 esp=12 trial=01: 1
    user=01 esp=12 trial=02: 1
    user=01 esp=13 trial=01: 1
    user=01 esp=13 trial=02: 1
    user=01 esp=14 trial=01: 1
    user=01 esp=14 trial=02: 1
    user=01 esp=15 trial=01: 1
    user=01 esp=15 trial=02: 1
    user=01 esp=16 trial=01: 1
    user=01 esp=16 trial=02: 1
    user=01 esp=17 trial=01: 1
    user=01 esp=17 trial=02: 1
    user=01 esp=18 trial=01: 1
    user=01 esp=18 trial=02: 1
    user=01 esp=19 trial=01: 1
    user=01 esp=19 trial=02: 1
    user=01 esp=20 trial=01: 1
    user=01 esp=20 trial=02: 1
    user=02 esp=01 trial=01: 1
    user=02 esp=02 trial=01: 1
    user=02 esp=03 trial=01: 1
    user=02 esp=04 trial=01: 1
    user=02 esp=05 trial=01: 1
    user=02 esp=07 trial=01: 1
    user=02 esp=08 trial=01: 1
    user=02 esp=09 trial=01: 1
    user=02 esp=10 trial=01: 1
    user=02 esp=11 trial=01: 1
    user=02 esp=12 trial=01: 1
    user=02 esp=13 trial=01: 1
    user=02 esp=14 trial=01: 1
    user=02 esp=15 trial=01: 1
    user=02 esp=16 trial=01: 1
    user=02 esp=17 trial=01: 1
    user=02 esp=18 trial=01: 1
    user=02 esp=19 trial=01: 1
    user=02 esp=20 trial=01: 1
    user=03 esp=01 trial=01: 1
    user=03 esp=01 trial=02: 1
    user=03 esp=02 trial=01: 1
    user=03 esp=02 trial=02: 1
    user=03 esp=03 trial=01: 1
    user=03 esp=03 trial=02: 1
    user=03 esp=04 trial=01: 1
    user=03 esp=04 trial=02: 1
    user=03 esp=05 trial=01: 1
    user=03 esp=05 trial=02: 1
    user=03 esp=07 trial=01: 1
    user=03 esp=07 trial=02: 1
    user=03 esp=08 trial=01: 1
    user=03 esp=08 trial=02: 1
    user=03 esp=09 trial=01: 1
    user=03 esp=09 trial=02: 1
    user=03 esp=10 trial=01: 1
    user=03 esp=10 trial=02: 1
    user=03 esp=11 trial=01: 1
    user=03 esp=11 trial=02: 1
    user=03 esp=12 trial=01: 1
    user=03 esp=12 trial=02: 1
    user=03 esp=13 trial=01: 1
    user=03 esp=13 trial=02: 1
    user=03 esp=14 trial=01: 1
    user=03 esp=14 trial=02: 1
    user=03 esp=15 trial=01: 1
    user=03 esp=15 trial=02: 1
    user=03 esp=16 trial=01: 1
    user=03 esp=16 trial=02: 1
    user=03 esp=17 trial=01: 1
    user=03 esp=17 trial=02: 1
    user=03 esp=18 trial=01: 1
    user=03 esp=18 trial=02: 1
    user=03 esp=19 trial=01: 1
    user=03 esp=19 trial=02: 1
    user=03 esp=20 trial=01: 1
    user=03 esp=20 trial=02: 1
    user=04 esp=01 trial=01: 1
    user=04 esp=02 trial=01: 1
    user=04 esp=03 trial=01: 1
    user=04 esp=04 trial=01: 1
    user=04 esp=05 trial=01: 1
    user=04 esp=07 trial=01: 1
    user=04 esp=08 trial=01: 1
    user=04 esp=09 trial=01: 1
    user=04 esp=10 trial=01: 1
    user=04 esp=11 trial=01: 1
    user=04 esp=12 trial=01: 1
    user=04 esp=13 trial=01: 1
    user=04 esp=14 trial=01: 1
    user=04 esp=15 trial=01: 1
    user=04 esp=16 trial=01: 1
    user=04 esp=17 trial=01: 1
    user=04 esp=18 trial=01: 1
    user=04 esp=19 trial=01: 1
    user=04 esp=20 trial=01: 1
    user=05 esp=01 trial=01: 1
    user=05 esp=01 trial=02: 1
    user=05 esp=02 trial=01: 1
    user=05 esp=02 trial=02: 1
    user=05 esp=03 trial=01: 1
    user=05 esp=03 trial=02: 1
    user=05 esp=04 trial=01: 1
    user=05 esp=04 trial=02: 1
    user=05 esp=05 trial=01: 1
    user=05 esp=05 trial=02: 1
    user=05 esp=07 trial=01: 1
    user=05 esp=07 trial=02: 1
    user=05 esp=08 trial=01: 1
    user=05 esp=08 trial=02: 1
    user=05 esp=09 trial=01: 1
    user=05 esp=09 trial=02: 1
    user=05 esp=10 trial=01: 1
    user=05 esp=10 trial=02: 1
    user=05 esp=11 trial=01: 1
    user=05 esp=11 trial=02: 1
    user=05 esp=12 trial=01: 1
    user=05 esp=12 trial=02: 1
    user=05 esp=13 trial=01: 1
    user=05 esp=13 trial=02: 1
    user=05 esp=14 trial=01: 1
    user=05 esp=14 trial=02: 1
    user=05 esp=15 trial=01: 1
    user=05 esp=15 trial=02: 1
    user=05 esp=16 trial=01: 1
    user=05 esp=16 trial=02: 1
    user=05 esp=17 trial=01: 1
    user=05 esp=17 trial=02: 1
    user=05 esp=18 trial=01: 1
    user=05 esp=18 trial=02: 1
    user=05 esp=19 trial=01: 1
    user=05 esp=19 trial=02: 1
    user=05 esp=20 trial=01: 1
    user=05 esp=20 trial=02: 1
    user=06 esp=01 trial=01: 1
    user=06 esp=02 trial=01: 1
    user=06 esp=03 trial=01: 1
    user=06 esp=04 trial=01: 1
    user=06 esp=05 trial=01: 1
    user=06 esp=07 trial=01: 1
    user=06 esp=08 trial=01: 1
    user=06 esp=09 trial=01: 1
    user=06 esp=10 trial=01: 1
    user=06 esp=11 trial=01: 1
    user=06 esp=12 trial=01: 1
    user=06 esp=13 trial=01: 1
    user=06 esp=14 trial=01: 1
    user=06 esp=15 trial=01: 1
    user=06 esp=16 trial=01: 1
    user=06 esp=17 trial=01: 1
    user=06 esp=18 trial=01: 1
    user=06 esp=19 trial=01: 1
    user=06 esp=20 trial=01: 1
  baseline coverage for occupied recordings:
    user=01 trial=01 esp=01: yes
    user=01 trial=01 esp=02: yes
    user=01 trial=01 esp=03: yes
    user=01 trial=01 esp=04: yes
    user=01 trial=01 esp=05: yes
    user=01 trial=01 esp=07: yes
    user=01 trial=01 esp=08: yes
    user=01 trial=01 esp=09: yes
    user=01 trial=01 esp=10: yes
    user=01 trial=01 esp=11: yes
    user=01 trial=01 esp=12: yes
    user=01 trial=01 esp=13: yes
    user=01 trial=01 esp=14: yes
    user=01 trial=01 esp=15: yes
    user=01 trial=01 esp=16: yes
    user=01 trial=01 esp=17: yes
    user=01 trial=01 esp=18: yes
    user=01 trial=01 esp=19: yes
    user=01 trial=01 esp=20: yes
    user=01 trial=02 esp=01: yes
    user=01 trial=02 esp=02: yes
    user=01 trial=02 esp=03: yes
    user=01 trial=02 esp=04: yes
    user=01 trial=02 esp=05: yes
    user=01 trial=02 esp=07: yes
    user=01 trial=02 esp=08: yes
    user=01 trial=02 esp=09: yes
    user=01 trial=02 esp=10: yes
    user=01 trial=02 esp=11: yes
    user=01 trial=02 esp=12: yes
    user=01 trial=02 esp=13: yes
    user=01 trial=02 esp=14: yes
    user=01 trial=02 esp=15: yes
    user=01 trial=02 esp=16: yes
    user=01 trial=02 esp=17: yes
    user=01 trial=02 esp=18: yes
    user=01 trial=02 esp=19: yes
    user=01 trial=02 esp=20: yes
    user=02 trial=01 esp=01: yes
    user=02 trial=01 esp=02: yes
    user=02 trial=01 esp=03: yes
    user=02 trial=01 esp=04: yes
    user=02 trial=01 esp=05: yes
    user=02 trial=01 esp=07: yes
    user=02 trial=01 esp=08: yes
    user=02 trial=01 esp=09: yes
    user=02 trial=01 esp=10: yes
    user=02 trial=01 esp=11: yes
    user=02 trial=01 esp=12: yes
    user=02 trial=01 esp=13: yes
    user=02 trial=01 esp=14: yes
    user=02 trial=01 esp=15: yes
    user=02 trial=01 esp=16: yes
    user=02 trial=01 esp=17: yes
    user=02 trial=01 esp=18: yes
    user=02 trial=01 esp=19: yes
    user=02 trial=01 esp=20: yes
    user=03 trial=01 esp=01: yes
    user=03 trial=01 esp=02: yes
    user=03 trial=01 esp=03: yes
    user=03 trial=01 esp=04: yes
    user=03 trial=01 esp=05: yes
    user=03 trial=01 esp=07: yes
    user=03 trial=01 esp=08: yes
    user=03 trial=01 esp=09: yes
    user=03 trial=01 esp=10: yes
    user=03 trial=01 esp=11: yes
    user=03 trial=01 esp=12: yes
    user=03 trial=01 esp=13: yes
    user=03 trial=01 esp=14: yes
    user=03 trial=01 esp=15: yes
    user=03 trial=01 esp=16: yes
    user=03 trial=01 esp=17: yes
    user=03 trial=01 esp=18: yes
    user=03 trial=01 esp=19: yes
    user=03 trial=01 esp=20: yes
    user=03 trial=02 esp=01: yes
    user=03 trial=02 esp=02: yes
    user=03 trial=02 esp=03: yes
    user=03 trial=02 esp=04: yes
    user=03 trial=02 esp=05: yes
    user=03 trial=02 esp=07: yes
    user=03 trial=02 esp=08: yes
    user=03 trial=02 esp=09: yes
    user=03 trial=02 esp=10: yes
    user=03 trial=02 esp=11: yes
    user=03 trial=02 esp=12: yes
    user=03 trial=02 esp=13: yes
    user=03 trial=02 esp=14: yes
    user=03 trial=02 esp=15: yes
    user=03 trial=02 esp=16: yes
    user=03 trial=02 esp=17: yes
    user=03 trial=02 esp=18: yes
    user=03 trial=02 esp=19: yes
    user=03 trial=02 esp=20: yes
    user=04 trial=01 esp=01: yes
    user=04 trial=01 esp=02: yes
    user=04 trial=01 esp=03: yes
    user=04 trial=01 esp=04: yes
    user=04 trial=01 esp=05: yes
    user=04 trial=01 esp=07: yes
    user=04 trial=01 esp=08: yes
    user=04 trial=01 esp=09: yes
    user=04 trial=01 esp=10: yes
    user=04 trial=01 esp=11: yes
    user=04 trial=01 esp=12: yes
    user=04 trial=01 esp=13: yes
    user=04 trial=01 esp=14: yes
    user=04 trial=01 esp=15: yes
    user=04 trial=01 esp=16: yes
    user=04 trial=01 esp=17: yes
    user=04 trial=01 esp=18: yes
    user=04 trial=01 esp=19: yes
    user=04 trial=01 esp=20: yes
    user=05 trial=01 esp=01: yes
    user=05 trial=01 esp=02: yes
    user=05 trial=01 esp=03: yes
    user=05 trial=01 esp=04: yes
    user=05 trial=01 esp=05: yes
    user=05 trial=01 esp=07: yes
    user=05 trial=01 esp=08: yes
    user=05 trial=01 esp=09: yes
    user=05 trial=01 esp=10: yes
    user=05 trial=01 esp=11: yes
    user=05 trial=01 esp=12: yes
    user=05 trial=01 esp=13: yes
    user=05 trial=01 esp=14: yes
    user=05 trial=01 esp=15: yes
    user=05 trial=01 esp=16: yes
    user=05 trial=01 esp=17: yes
    user=05 trial=01 esp=18: yes
    user=05 trial=01 esp=19: yes
    user=05 trial=01 esp=20: yes
    user=05 trial=02 esp=01: yes
    user=05 trial=02 esp=02: yes
    user=05 trial=02 esp=03: yes
    user=05 trial=02 esp=04: yes
    user=05 trial=02 esp=05: yes
    user=05 trial=02 esp=07: yes
    user=05 trial=02 esp=08: yes
    user=05 trial=02 esp=09: yes
    user=05 trial=02 esp=10: yes
    user=05 trial=02 esp=11: yes
    user=05 trial=02 esp=12: yes
    user=05 trial=02 esp=13: yes
    user=05 trial=02 esp=14: yes
    user=05 trial=02 esp=15: yes
    user=05 trial=02 esp=16: yes
    user=05 trial=02 esp=17: yes
    user=05 trial=02 esp=18: yes
    user=05 trial=02 esp=19: yes
    user=05 trial=02 esp=20: yes
    user=06 trial=01 esp=01: yes
    user=06 trial=01 esp=02: yes
    user=06 trial=01 esp=03: yes
    user=06 trial=01 esp=04: yes
    user=06 trial=01 esp=05: yes
    user=06 trial=01 esp=07: yes
    user=06 trial=01 esp=08: yes
    user=06 trial=01 esp=09: yes
    user=06 trial=01 esp=10: yes
    user=06 trial=01 esp=11: yes
    user=06 trial=01 esp=12: yes
    user=06 trial=01 esp=13: yes
    user=06 trial=01 esp=14: yes
    user=06 trial=01 esp=15: yes
    user=06 trial=01 esp=16: yes
    user=06 trial=01 esp=17: yes
    user=06 trial=01 esp=18: yes
    user=06 trial=01 esp=19: yes
    user=06 trial=01 esp=20: yes
  per_session scope fully satisfiable: yes
  deep-fade clipped subcarriers:
    user=01 trial=01 esp=01: 1
    user=01 trial=01 esp=02: 1
    user=01 trial=01 esp=03: 1
    user=01 trial=01 esp=04: 1
    user=01 trial=01 esp=05: 1
    user=01 trial=01 esp=07: 1
    user=01 trial=01 esp=08: 0
    user=01 trial=01 esp=09: 1
    user=01 trial=01 esp=10: 1
    user=01 trial=01 esp=11: 1
    user=01 trial=01 esp=12: 1
    user=01 trial=01 esp=13: 1
    user=01 trial=01 esp=14: 1
    user=01 trial=01 esp=15: 1
    user=01 trial=01 esp=16: 1
    user=01 trial=01 esp=17: 1
    user=01 trial=01 esp=18: 0
    user=01 trial=01 esp=19: 0
    user=01 trial=01 esp=20: 1
    user=01 trial=02 esp=01: 1
    user=01 trial=02 esp=02: 1
    user=01 trial=02 esp=03: 1
    user=01 trial=02 esp=04: 1
    user=01 trial=02 esp=05: 1
    user=01 trial=02 esp=07: 0
    user=01 trial=02 esp=08: 1
    user=01 trial=02 esp=09: 1
    user=01 trial=02 esp=10: 1
    user=01 trial=02 esp=11: 1
    user=01 trial=02 esp=12: 1
    user=01 trial=02 esp=13: 1
    user=01 trial=02 esp=14: 1
    user=01 trial=02 esp=15: 1
    user=01 trial=02 esp=16: 1
    user=01 trial=02 esp=17: 1
    user=01 trial=02 esp=18: 1
    user=01 trial=02 esp=19: 1
    user=01 trial=02 esp=20: 1
    user=02 trial=01 esp=01: 0
    user=02 trial=01 esp=02: 1
    user=02 trial=01 esp=03: 1
    user=02 trial=01 esp=04: 1
    user=02 trial=01 esp=05: 1
    user=02 trial=01 esp=07: 1
    user=02 trial=01 esp=08: 1
    user=02 trial=01 esp=09: 1
    user=02 trial=01 esp=10: 1
    user=02 trial=01 esp=11: 1
    user=02 trial=01 esp=12: 1
    user=02 trial=01 esp=13: 1
    user=02 trial=01 esp=14: 1
    user=02 trial=01 esp=15: 1
    user=02 trial=01 esp=16: 1
    user=02 trial=01 esp=17: 1
    user=02 trial=01 esp=18: 1
    user=02 trial=01 esp=19: 1
    user=02 trial=01 esp=20: 1
    user=03 trial=01 esp=01: 1
    user=03 trial=01 esp=02: 1
    user=03 trial=01 esp=03: 1
    user=03 trial=01 esp=04: 0
    user=03 trial=01 esp=05: 1
    user=03 trial=01 esp=07: 1
    user=03 trial=01 esp=08: 1
    user=03 trial=01 esp=09: 1
    user=03 trial=01 esp=10: 1
    user=03 trial=01 esp=11: 1
    user=03 trial=01 esp=12: 1
    user=03 trial=01 esp=13: 1
    user=03 trial=01 esp=14: 1
    user=03 trial=01 esp=15: 1
    user=03 trial=01 esp=16: 1
    user=03 trial=01 esp=17: 1
    user=03 trial=01 esp=18: 1
    user=03 trial=01 esp=19: 1
    user=03 trial=01 esp=20: 1
    user=03 trial=02 esp=01: 1
    user=03 trial=02 esp=02: 1
    user=03 trial=02 esp=03: 1
    user=03 trial=02 esp=04: 1
    user=03 trial=02 esp=05: 0
    user=03 trial=02 esp=07: 1
    user=03 trial=02 esp=08: 1
    user=03 trial=02 esp=09: 1
    user=03 trial=02 esp=10: 1
    user=03 trial=02 esp=11: 1
    user=03 trial=02 esp=12: 1
    user=03 trial=02 esp=13: 1
    user=03 trial=02 esp=14: 1
    user=03 trial=02 esp=15: 1
    user=03 trial=02 esp=16: 1
    user=03 trial=02 esp=17: 1
    user=03 trial=02 esp=18: 1
    user=03 trial=02 esp=19: 1
    user=03 trial=02 esp=20: 1
    user=04 trial=01 esp=01: 0
    user=04 trial=01 esp=02: 1
    user=04 trial=01 esp=03: 1
    user=04 trial=01 esp=04: 1
    user=04 trial=01 esp=05: 1
    user=04 trial=01 esp=07: 1
    user=04 trial=01 esp=08: 1
    user=04 trial=01 esp=09: 1
    user=04 trial=01 esp=10: 1
    user=04 trial=01 esp=11: 1
    user=04 trial=01 esp=12: 1
    user=04 trial=01 esp=13: 1
    user=04 trial=01 esp=14: 1
    user=04 trial=01 esp=15: 1
    user=04 trial=01 esp=16: 1
    user=04 trial=01 esp=17: 1
    user=04 trial=01 esp=18: 1
    user=04 trial=01 esp=19: 0
    user=04 trial=01 esp=20: 1
    user=05 trial=01 esp=01: 1
    user=05 trial=01 esp=02: 1
    user=05 trial=01 esp=03: 1
    user=05 trial=01 esp=04: 1
    user=05 trial=01 esp=05: 1
    user=05 trial=01 esp=07: 1
    user=05 trial=01 esp=08: 1
    user=05 trial=01 esp=09: 1
    user=05 trial=01 esp=10: 1
    user=05 trial=01 esp=11: 1
    user=05 trial=01 esp=12: 1
    user=05 trial=01 esp=13: 1
    user=05 trial=01 esp=14: 1
    user=05 trial=01 esp=15: 1
    user=05 trial=01 esp=16: 1
    user=05 trial=01 esp=17: 1
    user=05 trial=01 esp=18: 1
    user=05 trial=01 esp=19: 0
    user=05 trial=01 esp=20: 1
    user=05 trial=02 esp=01: 0
    user=05 trial=02 esp=02: 1
    user=05 trial=02 esp=03: 1
    user=05 trial=02 esp=04: 1
    user=05 trial=02 esp=05: 1
    user=05 trial=02 esp=07: 1
    user=05 trial=02 esp=08: 1
    user=05 trial=02 esp=09: 1
    user=05 trial=02 esp=10: 0
    user=05 trial=02 esp=11: 1
    user=05 trial=02 esp=12: 0
    user=05 trial=02 esp=13: 1
    user=05 trial=02 esp=14: 1
    user=05 trial=02 esp=15: 1
    user=05 trial=02 esp=16: 1
    user=05 trial=02 esp=17: 1
    user=05 trial=02 esp=18: 1
    user=05 trial=02 esp=19: 1
    user=05 trial=02 esp=20: 1
    user=06 trial=01 esp=01: 1
    user=06 trial=01 esp=02: 1
    user=06 trial=01 esp=03: 1
    user=06 trial=01 esp=04: 1
    user=06 trial=01 esp=05: 1
    user=06 trial=01 esp=07: 1
    user=06 trial=01 esp=08: 1
    user=06 trial=01 esp=09: 1
    user=06 trial=01 esp=10: 1
    user=06 trial=01 esp=11: 1
    user=06 trial=01 esp=12: 1
    user=06 trial=01 esp=13: 1
    user=06 trial=01 esp=14: 1
    user=06 trial=01 esp=15: 1
    user=06 trial=01 esp=16: 1
    user=06 trial=01 esp=17: 1
    user=06 trial=01 esp=18: 1
    user=06 trial=01 esp=19: 1
    user=06 trial=01 esp=20: 1
[cache hit] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/.cache/dataframes/preproc=norm-empty_baseline_scope-per_session/feat=win60-step0/2_4ghz.parquet
[cache hit] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/.cache/dataframes/preproc=norm-empty_baseline_scope-per_session/feat=win60-step0/5ghz.parquet
[cache hit] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/.cache/dataframes/preproc=norm-empty_baseline_scope-per_session/feat=win60-step0/fusion.parquet

,scenario,location,user,esp,trial,samples,subcarriers,normalization,baseline_scope
0,1,C-1,06,16,01,2088,56,empty_baseline,per_session
1,1,C-1,06,15,01,1942,56,empty_baseline,per_session
2,1,C-1,06,09,01,1689,50,empty_baseline,per_session
3,1,C-1,06,07,01,1965,50,empty_baseline,per_session
4,1,C-1,06,04,01,1913,50,empty_baseline,per_session

In [11]:
for band in BANDS_TO_RUN:
    df = feature_dataframes[band]
    print(f"{band}: {df.shape[0]} windows, {df.shape[1]} columns")
    print(f"{band} dataframe hash: {pd.util.hash_pandas_object(df, index=True).sum()}")

2.4 GHz: 13588 windows, 2708 columns
2.4 GHz dataframe hash: 12830868654705884127
5 GHz: 14478 windows, 3368 columns
5 GHz dataframe hash: 5016803871464446121
Fusion: 13568 windows, 6068 columns
Fusion dataframe hash: 3976504561903335248

In [12]:
label_encoder = create_position_label_encoder(
    feature_dataframes,
    results_dir=results_dir,
    expected_classes=52,
)
print(label_encoder.classes_)

[CNN] label classes saved to /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/manifests/cnn_label_classes.json
['A-1' 'A-13' 'A-14' 'A-2' 'A-5' 'B-1' 'B-10' 'B-11' 'B-12' 'B-13' 'B-14'
 'B-2' 'B-5' 'B-8' 'C-1' 'C-10' 'C-11' 'C-14' 'C-2' 'C-3' 'C-4' 'C-5'
 'C-6' 'C-7' 'C-8' 'C-9' 'D-1' 'D-2' 'D-3' 'D-4' 'D-5' 'D-6' 'D-7' 'D-8'
 'E-1' 'E-10' 'E-11' 'E-12' 'E-13' 'E-2' 'E-3' 'E-4' 'E-5' 'E-6' 'E-7'
 'E-8' 'F-10' 'F-11' 'F-12' 'F-13' 'F-5' 'F-8']

### Train And Evaluate

In [13]:
cnn_runs = run_dl_experiments(
    processed_magnitude_data,
    feature_dataframes,
    bands=BANDS_TO_RUN,
    split_modes=SPLIT_MODES,
    label_encoder=label_encoder,
    device=DEVICE,
    results_dir=results_dir,
    plots_dir=plots_dir,
    params=CNN_PARAMS,
    preproc_opts=preproc_opts,
    feat_opts=feat_opts,
    expected_subcarriers=EXPECTED_SUBCARRIERS,
    expected_anchors=EXPECTED_ANCHORS,
    seeds=SEEDS,
    test_size=TEST_SIZE,
    random_state=RANDOM_STATE,
    n_blocks=BLOCK_COUNT,
    val_size=VALIDATION_SIZE,
    force_retrain=FORCE_RETRAIN,
)

=== 2.4 GHz ===
[window arrays] cache path: /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/.cache/dataframes/preproc=norm-empty_baseline_scope-per_session/feat=win60-step0/window_arrays/2_4ghz
[window arrays cache hit] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/.cache/dataframes/preproc=norm-empty_baseline_scope-per_session/feat=win60-step0/window_arrays/2_4ghz
[window arrays] 2.4 GHz: shape=(13588, 9, 50, 60), dtype=float16
[window arrays] 2.4 GHz anchors: ['esp_01', 'esp_02', 'esp_03', 'esp_04', 'esp_05', 'esp_07', 'esp_08', 'esp_09', 'esp_10']
2.4 GHz: anchors=9, subcarriers=50, windows=13588
WINDOW IDENTITY PASS: 2.4 GHz (13588 windows)
[trial filter] split=block trials=['01'] kept=8906/13588
[protocol] split=block trials_used=['01'] n_train=4947 n_test=1392 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05', '06'] test_users=['01', '02', '03', '04', '05', '06']
[trial filter] split=block trials=['01'] kept=8906/13588
[protocol] split=block trials_used=['01'] n_train=4947 n_test=1392 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05', '06'] test_users=['01', '02', '03', '04', '05', '06']
SPLIT IDENTITY PASS: 2.4 GHz/block fold=1 train=4947 test=1392
Seeds: random=42, numpy=42, torch=42
[trial filter] split=block trials=['01'] kept=8906/13588
[protocol] split=block trials_used=['01'] n_train=4947 n_test=1392 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05', '06'] test_users=['01', '02', '03', '04', '05', '06']
[trial filter] split=block trials=['01'] kept=4947/4947
[protocol] split=block trials_used=['01'] n_train=3014 n_test=150 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05', '06'] test_users=['01', '02', '03', '04', '05', '06']
[CNN] 2.4 GHz/block fold=single parameters=76020
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] 2.4 GHz/block fold=single epoch 01/50: train_loss=3.9417 train_acc=0.0252 val_loss=3.9464 val_acc=0.0133 seconds=3.9
[CNN] 2.4 GHz/block fold=single epoch 02/50: train_loss=3.8693 train_acc=0.0528 val_loss=3.9144 val_acc=0.0267 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 03/50: train_loss=3.7323 train_acc=0.0657 val_loss=3.8122 val_acc=0.0400 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 04/50: train_loss=3.5493 train_acc=0.0962 val_loss=3.6035 val_acc=0.0800 seconds=0.5
[CNN] 2.4 GHz/block fold=single epoch 05/50: train_loss=3.3919 train_acc=0.1171 val_loss=3.4332 val_acc=0.1200 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 06/50: train_loss=3.2635 train_acc=0.1307 val_loss=3.2548 val_acc=0.1400 seconds=0.4
[CNN] 2.4 GHz/block fold=single epoch 07/50: train_loss=3.1572 train_acc=0.1440 val_loss=3.2418 val_acc=0.1467 seconds=0.4
[CNN] 2.4 GHz/block fold=single epoch 08/50: train_loss=3.0520 train_acc=0.1762 val_loss=3.0273 val_acc=0.2133 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 09/50: train_loss=2.9388 train_acc=0.1938 val_loss=3.0709 val_acc=0.2000 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 10/50: train_loss=2.8591 train_acc=0.2097 val_loss=3.0215 val_acc=0.1867 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 11/50: train_loss=2.7809 train_acc=0.2233 val_loss=2.8733 val_acc=0.2267 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 12/50: train_loss=2.7135 train_acc=0.2322 val_loss=3.0261 val_acc=0.1800 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 13/50: train_loss=2.6499 train_acc=0.2571 val_loss=2.9638 val_acc=0.1667 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 14/50: train_loss=2.5550 train_acc=0.2714 val_loss=2.8233 val_acc=0.2600 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 15/50: train_loss=2.5145 train_acc=0.2833 val_loss=2.7847 val_acc=0.2400 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 16/50: train_loss=2.4512 train_acc=0.2916 val_loss=2.7575 val_acc=0.2400 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 17/50: train_loss=2.4032 train_acc=0.3112 val_loss=2.9085 val_acc=0.2133 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 18/50: train_loss=2.3616 train_acc=0.3179 val_loss=2.7435 val_acc=0.2533 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 19/50: train_loss=2.3007 train_acc=0.3311 val_loss=2.7383 val_acc=0.2600 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 20/50: train_loss=2.2401 train_acc=0.3427 val_loss=2.7584 val_acc=0.2733 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 21/50: train_loss=2.1906 train_acc=0.3613 val_loss=2.7840 val_acc=0.2533 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 22/50: train_loss=2.1437 train_acc=0.3726 val_loss=2.6431 val_acc=0.2867 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 23/50: train_loss=2.1314 train_acc=0.3666 val_loss=2.7033 val_acc=0.2667 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 24/50: train_loss=2.0661 train_acc=0.3991 val_loss=2.9616 val_acc=0.1867 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 25/50: train_loss=2.0080 train_acc=0.4104 val_loss=2.6052 val_acc=0.2800 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 26/50: train_loss=1.9786 train_acc=0.4137 val_loss=2.6326 val_acc=0.2733 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 27/50: train_loss=1.9220 train_acc=0.4360 val_loss=2.5810 val_acc=0.3200 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 28/50: train_loss=1.8926 train_acc=0.4373 val_loss=2.6656 val_acc=0.3000 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 29/50: train_loss=1.8754 train_acc=0.4443 val_loss=2.6016 val_acc=0.3267 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 30/50: train_loss=1.8715 train_acc=0.4360 val_loss=2.6042 val_acc=0.2667 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 31/50: train_loss=1.8312 train_acc=0.4608 val_loss=2.8818 val_acc=0.2200 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 32/50: train_loss=1.7727 train_acc=0.4738 val_loss=2.7690 val_acc=0.3000 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 33/50: train_loss=1.7487 train_acc=0.4834 val_loss=2.6422 val_acc=0.2600 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 34/50: train_loss=1.7451 train_acc=0.4798 val_loss=2.4997 val_acc=0.2933 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 35/50: train_loss=1.6753 train_acc=0.5023 val_loss=2.6209 val_acc=0.2800 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 36/50: train_loss=1.6339 train_acc=0.5272 val_loss=2.6010 val_acc=0.2600 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 37/50: train_loss=1.6074 train_acc=0.5252 val_loss=2.6459 val_acc=0.3267 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 38/50: train_loss=1.5893 train_acc=0.5292 val_loss=2.7962 val_acc=0.2800 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 39/50: train_loss=1.5738 train_acc=0.5302 val_loss=2.5248 val_acc=0.3067 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 40/50: train_loss=1.5453 train_acc=0.5325 val_loss=2.6684 val_acc=0.3000 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 41/50: train_loss=1.5274 train_acc=0.5411 val_loss=2.3641 val_acc=0.2800 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 42/50: train_loss=1.5187 train_acc=0.5471 val_loss=2.5133 val_acc=0.3000 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 43/50: train_loss=1.4956 train_acc=0.5518 val_loss=3.4042 val_acc=0.2267 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 44/50: train_loss=1.4446 train_acc=0.5773 val_loss=2.9246 val_acc=0.2667 seconds=0.2
[CNN] early stopping at epoch 44; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__2_4ghz__block__ebl-session__s42__df21ec.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__2_4ghz__block__ebl-session__s42__df21ec/training_curves.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL GPU] run_id=dl__cnn__2_4ghz__block__ebl-session__s42__df21ec peak_cuda_memory_bytes=514714624
[results upsert] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/runs.csv: 4 row(s)
Seeds: random=43, numpy=43, torch=43
[trial filter] split=block trials=['01'] kept=8906/13588
[protocol] split=block trials_used=['01'] n_train=4947 n_test=1392 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05', '06'] test_users=['01', '02', '03', '04', '05', '06']
[trial filter] split=block trials=['01'] kept=4947/4947
[protocol] split=block trials_used=['01'] n_train=3014 n_test=150 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05', '06'] test_users=['01', '02', '03', '04', '05', '06']
[CNN] 2.4 GHz/block fold=single parameters=76020
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] 2.4 GHz/block fold=single epoch 01/50: train_loss=3.9365 train_acc=0.0305 val_loss=3.9430 val_acc=0.0200 seconds=3.5
[CNN] 2.4 GHz/block fold=single epoch 02/50: train_loss=3.8636 train_acc=0.0610 val_loss=3.9226 val_acc=0.0133 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 03/50: train_loss=3.7342 train_acc=0.0740 val_loss=3.8347 val_acc=0.0400 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 04/50: train_loss=3.5808 train_acc=0.0816 val_loss=3.6304 val_acc=0.0800 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 05/50: train_loss=3.4272 train_acc=0.1108 val_loss=3.4182 val_acc=0.1267 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 06/50: train_loss=3.2755 train_acc=0.1304 val_loss=3.3159 val_acc=0.1867 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 07/50: train_loss=3.1604 train_acc=0.1387 val_loss=3.4470 val_acc=0.1467 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 08/50: train_loss=3.0536 train_acc=0.1612 val_loss=3.2393 val_acc=0.2000 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 09/50: train_loss=2.9632 train_acc=0.1838 val_loss=3.1745 val_acc=0.1933 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 10/50: train_loss=2.8741 train_acc=0.2120 val_loss=3.0154 val_acc=0.2467 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 11/50: train_loss=2.7868 train_acc=0.2293 val_loss=3.0037 val_acc=0.2267 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 12/50: train_loss=2.7041 train_acc=0.2459 val_loss=2.8903 val_acc=0.2267 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 13/50: train_loss=2.6480 train_acc=0.2498 val_loss=2.7866 val_acc=0.2400 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 14/50: train_loss=2.5703 train_acc=0.2790 val_loss=3.0416 val_acc=0.2267 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 15/50: train_loss=2.5084 train_acc=0.2827 val_loss=2.7273 val_acc=0.2667 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 16/50: train_loss=2.4260 train_acc=0.3145 val_loss=2.7303 val_acc=0.2600 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 17/50: train_loss=2.3764 train_acc=0.3162 val_loss=3.0011 val_acc=0.2133 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 18/50: train_loss=2.3405 train_acc=0.3188 val_loss=2.6938 val_acc=0.2867 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 19/50: train_loss=2.2814 train_acc=0.3461 val_loss=3.1701 val_acc=0.1667 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 20/50: train_loss=2.2213 train_acc=0.3517 val_loss=2.6155 val_acc=0.2867 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 21/50: train_loss=2.1693 train_acc=0.3660 val_loss=3.0327 val_acc=0.2267 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 22/50: train_loss=2.1265 train_acc=0.3743 val_loss=2.6023 val_acc=0.2933 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 23/50: train_loss=2.0718 train_acc=0.3889 val_loss=2.8344 val_acc=0.2600 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 24/50: train_loss=2.0727 train_acc=0.3902 val_loss=2.6059 val_acc=0.2600 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 25/50: train_loss=2.0264 train_acc=0.4107 val_loss=2.5511 val_acc=0.3000 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 26/50: train_loss=1.9925 train_acc=0.4164 val_loss=2.5384 val_acc=0.3000 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 27/50: train_loss=1.9362 train_acc=0.4217 val_loss=2.4472 val_acc=0.3000 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 28/50: train_loss=1.8729 train_acc=0.4383 val_loss=2.7979 val_acc=0.2800 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 29/50: train_loss=1.8410 train_acc=0.4648 val_loss=2.5004 val_acc=0.2867 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 30/50: train_loss=1.8105 train_acc=0.4688 val_loss=2.4511 val_acc=0.3200 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 31/50: train_loss=1.7880 train_acc=0.4718 val_loss=2.7299 val_acc=0.2667 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 32/50: train_loss=1.7854 train_acc=0.4678 val_loss=2.6892 val_acc=0.2867 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 33/50: train_loss=1.7468 train_acc=0.4808 val_loss=2.9484 val_acc=0.2600 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 34/50: train_loss=1.7228 train_acc=0.4857 val_loss=2.4278 val_acc=0.3200 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 35/50: train_loss=1.6845 train_acc=0.4973 val_loss=2.3729 val_acc=0.3333 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 36/50: train_loss=1.6551 train_acc=0.4967 val_loss=2.6251 val_acc=0.3067 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 37/50: train_loss=1.6127 train_acc=0.5083 val_loss=2.4890 val_acc=0.3467 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 38/50: train_loss=1.6040 train_acc=0.5219 val_loss=2.6703 val_acc=0.3067 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 39/50: train_loss=1.5755 train_acc=0.5295 val_loss=2.5940 val_acc=0.3067 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 40/50: train_loss=1.5596 train_acc=0.5272 val_loss=2.4181 val_acc=0.3533 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 41/50: train_loss=1.4990 train_acc=0.5537 val_loss=2.4749 val_acc=0.3000 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 42/50: train_loss=1.5012 train_acc=0.5358 val_loss=2.4715 val_acc=0.3133 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 43/50: train_loss=1.4645 train_acc=0.5614 val_loss=2.5404 val_acc=0.3333 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 44/50: train_loss=1.4419 train_acc=0.5620 val_loss=2.6719 val_acc=0.2933 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 45/50: train_loss=1.4247 train_acc=0.5707 val_loss=2.8570 val_acc=0.2600 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 46/50: train_loss=1.3802 train_acc=0.5823 val_loss=2.5218 val_acc=0.3267 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 47/50: train_loss=1.3919 train_acc=0.5760 val_loss=2.7402 val_acc=0.3000 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 48/50: train_loss=1.4034 train_acc=0.5577 val_loss=2.6185 val_acc=0.3000 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 49/50: train_loss=1.3845 train_acc=0.5730 val_loss=2.6770 val_acc=0.3000 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 50/50: train_loss=1.3323 train_acc=0.5946 val_loss=2.5918 val_acc=0.3200 seconds=0.2

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__2_4ghz__block__ebl-session__s43__210c56.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__2_4ghz__block__ebl-session__s43__210c56/training_curves.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL GPU] run_id=dl__cnn__2_4ghz__block__ebl-session__s43__210c56 peak_cuda_memory_bytes=514714624
[results upsert] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/runs.csv: 5 row(s)
Seeds: random=44, numpy=44, torch=44
[trial filter] split=block trials=['01'] kept=8906/13588
[protocol] split=block trials_used=['01'] n_train=4947 n_test=1392 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05', '06'] test_users=['01', '02', '03', '04', '05', '06']
[trial filter] split=block trials=['01'] kept=4947/4947
[protocol] split=block trials_used=['01'] n_train=3014 n_test=150 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05', '06'] test_users=['01', '02', '03', '04', '05', '06']
[CNN] 2.4 GHz/block fold=single parameters=76020
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] 2.4 GHz/block fold=single epoch 01/50: train_loss=3.9409 train_acc=0.0325 val_loss=3.9420 val_acc=0.0400 seconds=3.8
[CNN] 2.4 GHz/block fold=single epoch 02/50: train_loss=3.8720 train_acc=0.0484 val_loss=3.9186 val_acc=0.0267 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 03/50: train_loss=3.7593 train_acc=0.0687 val_loss=3.8333 val_acc=0.0333 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 04/50: train_loss=3.6095 train_acc=0.0873 val_loss=3.6200 val_acc=0.1200 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 05/50: train_loss=3.4543 train_acc=0.1062 val_loss=3.3882 val_acc=0.1333 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 06/50: train_loss=3.3191 train_acc=0.1214 val_loss=3.2738 val_acc=0.1000 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 07/50: train_loss=3.1925 train_acc=0.1460 val_loss=3.2059 val_acc=0.1933 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 08/50: train_loss=3.0636 train_acc=0.1775 val_loss=3.1568 val_acc=0.2000 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 09/50: train_loss=2.9414 train_acc=0.2031 val_loss=3.0251 val_acc=0.1867 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 10/50: train_loss=2.8491 train_acc=0.2090 val_loss=3.0714 val_acc=0.2000 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 11/50: train_loss=2.7566 train_acc=0.2372 val_loss=2.9454 val_acc=0.2067 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 12/50: train_loss=2.6684 train_acc=0.2595 val_loss=2.9940 val_acc=0.2333 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 13/50: train_loss=2.5975 train_acc=0.2721 val_loss=2.8991 val_acc=0.2533 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 14/50: train_loss=2.5274 train_acc=0.2923 val_loss=2.9997 val_acc=0.1800 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 15/50: train_loss=2.4923 train_acc=0.2847 val_loss=2.7647 val_acc=0.1933 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 16/50: train_loss=2.4284 train_acc=0.3086 val_loss=2.9435 val_acc=0.1933 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 17/50: train_loss=2.3480 train_acc=0.3255 val_loss=2.7063 val_acc=0.2400 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 18/50: train_loss=2.2846 train_acc=0.3451 val_loss=2.8387 val_acc=0.1933 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 19/50: train_loss=2.2294 train_acc=0.3616 val_loss=2.8300 val_acc=0.2133 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 20/50: train_loss=2.1878 train_acc=0.3626 val_loss=2.6287 val_acc=0.2467 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 21/50: train_loss=2.1544 train_acc=0.3799 val_loss=2.7654 val_acc=0.1933 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 22/50: train_loss=2.0862 train_acc=0.3995 val_loss=2.6364 val_acc=0.2200 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 23/50: train_loss=2.0462 train_acc=0.3918 val_loss=2.6708 val_acc=0.2400 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 24/50: train_loss=2.0200 train_acc=0.4015 val_loss=2.7249 val_acc=0.2200 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 25/50: train_loss=1.9992 train_acc=0.4154 val_loss=2.6634 val_acc=0.2467 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 26/50: train_loss=1.9365 train_acc=0.4346 val_loss=2.7699 val_acc=0.2333 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 27/50: train_loss=1.8845 train_acc=0.4350 val_loss=2.5117 val_acc=0.2600 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 28/50: train_loss=1.8545 train_acc=0.4423 val_loss=2.5060 val_acc=0.2533 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 29/50: train_loss=1.8249 train_acc=0.4701 val_loss=2.7239 val_acc=0.2800 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 30/50: train_loss=1.8082 train_acc=0.4602 val_loss=2.8669 val_acc=0.2467 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 31/50: train_loss=1.7488 train_acc=0.4688 val_loss=2.6612 val_acc=0.2667 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 32/50: train_loss=1.7210 train_acc=0.4861 val_loss=2.7528 val_acc=0.2267 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 33/50: train_loss=1.7050 train_acc=0.4970 val_loss=2.5213 val_acc=0.2667 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 34/50: train_loss=1.6453 train_acc=0.4983 val_loss=2.4650 val_acc=0.3067 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 35/50: train_loss=1.6158 train_acc=0.5173 val_loss=2.5817 val_acc=0.2667 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 36/50: train_loss=1.5846 train_acc=0.5265 val_loss=2.6672 val_acc=0.2333 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 37/50: train_loss=1.5799 train_acc=0.5126 val_loss=2.5182 val_acc=0.3067 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 38/50: train_loss=1.5712 train_acc=0.5279 val_loss=2.4467 val_acc=0.2800 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 39/50: train_loss=1.5092 train_acc=0.5435 val_loss=3.1608 val_acc=0.2000 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 40/50: train_loss=1.4642 train_acc=0.5577 val_loss=3.0146 val_acc=0.2267 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 41/50: train_loss=1.4526 train_acc=0.5647 val_loss=2.4270 val_acc=0.3267 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 42/50: train_loss=1.4105 train_acc=0.5790 val_loss=2.6405 val_acc=0.2667 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 43/50: train_loss=1.3923 train_acc=0.5730 val_loss=2.4244 val_acc=0.3067 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 44/50: train_loss=1.3965 train_acc=0.5660 val_loss=2.5426 val_acc=0.3000 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 45/50: train_loss=1.3874 train_acc=0.5687 val_loss=2.7068 val_acc=0.2467 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 46/50: train_loss=1.3706 train_acc=0.5756 val_loss=2.6165 val_acc=0.3333 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 47/50: train_loss=1.3383 train_acc=0.5982 val_loss=2.6700 val_acc=0.3000 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 48/50: train_loss=1.3149 train_acc=0.6075 val_loss=2.4582 val_acc=0.3267 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 49/50: train_loss=1.3098 train_acc=0.6012 val_loss=2.8932 val_acc=0.3000 seconds=0.2
[CNN] 2.4 GHz/block fold=single epoch 50/50: train_loss=1.3128 train_acc=0.6098 val_loss=2.5310 val_acc=0.3467 seconds=0.2

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__2_4ghz__block__ebl-session__s44__86f94f.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__2_4ghz__block__ebl-session__s44__86f94f/training_curves.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL GPU] run_id=dl__cnn__2_4ghz__block__ebl-session__s44__86f94f peak_cuda_memory_bytes=514714624
[results upsert] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/runs.csv: 6 row(s)
[DL seeds] mean +/- std across seeds written to tables/seed_summary; LOVO uses each seed's fold mean and keeps within-seed fold std separate.

=== 5 GHz ===
[window arrays] cache path: /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/.cache/dataframes/preproc=norm-empty_baseline_scope-per_session/feat=win60-step0/window_arrays/5ghz
[window arrays] 5 GHz: shape=(14478, 10, 56, 60), dtype=float16
[window arrays] 5 GHz anchors: ['esp_11', 'esp_12', 'esp_13', 'esp_14', 'esp_15', 'esp_16', 'esp_17', 'esp_18', 'esp_19', 'esp_20']
5 GHz: anchors=10, subcarriers=56, windows=14478
WINDOW IDENTITY PASS: 5 GHz (14478 windows)
[trial filter] split=block trials=['01'] kept=9695/14478
[protocol] split=block trials_used=['01'] n_train=5477 n_test=1648 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05', '06'] test_users=['01', '02', '03', '04', '05', '06']
[trial filter] split=block trials=['01'] kept=9695/14478
[protocol] split=block trials_used=['01'] n_train=5477 n_test=1648 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05', '06'] test_users=['01', '02', '03', '04', '05', '06']
SPLIT IDENTITY PASS: 5 GHz/block fold=1 train=5477 test=1648
Seeds: random=42, numpy=42, torch=42
[trial filter] split=block trials=['01'] kept=9695/14478
[protocol] split=block trials_used=['01'] n_train=5477 n_test=1648 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05', '06'] test_users=['01', '02', '03', '04', '05', '06']
[trial filter] split=block trials=['01'] kept=5477/5477
[protocol] split=block trials_used=['01'] n_train=3396 n_test=179 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05', '06'] test_users=['01', '02', '03', '04', '05', '06']
[CNN] 5 GHz/block fold=single parameters=76308
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] 5 GHz/block fold=single epoch 01/50: train_loss=3.9206 train_acc=0.0409 val_loss=3.9043 val_acc=0.0726 seconds=3.9
[CNN] 5 GHz/block fold=single epoch 02/50: train_loss=3.7303 train_acc=0.0998 val_loss=3.6249 val_acc=0.1397 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 03/50: train_loss=3.4449 train_acc=0.1098 val_loss=3.3397 val_acc=0.1564 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 04/50: train_loss=3.2302 train_acc=0.1452 val_loss=3.1638 val_acc=0.1564 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 05/50: train_loss=3.0664 train_acc=0.1667 val_loss=3.0494 val_acc=0.1788 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 06/50: train_loss=2.9403 train_acc=0.1843 val_loss=2.9889 val_acc=0.2067 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 07/50: train_loss=2.8230 train_acc=0.2014 val_loss=2.9077 val_acc=0.2067 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 08/50: train_loss=2.7338 train_acc=0.2197 val_loss=2.8436 val_acc=0.1955 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 09/50: train_loss=2.6481 train_acc=0.2359 val_loss=2.7850 val_acc=0.2402 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 10/50: train_loss=2.6066 train_acc=0.2391 val_loss=2.7699 val_acc=0.2346 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 11/50: train_loss=2.5307 train_acc=0.2647 val_loss=2.7282 val_acc=0.2626 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 12/50: train_loss=2.4763 train_acc=0.2703 val_loss=2.7279 val_acc=0.2291 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 13/50: train_loss=2.4264 train_acc=0.2924 val_loss=2.6484 val_acc=0.2402 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 14/50: train_loss=2.3729 train_acc=0.2962 val_loss=2.6722 val_acc=0.2514 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 15/50: train_loss=2.3218 train_acc=0.3101 val_loss=2.6808 val_acc=0.2458 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 16/50: train_loss=2.2679 train_acc=0.3230 val_loss=2.6111 val_acc=0.2570 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 17/50: train_loss=2.2098 train_acc=0.3422 val_loss=2.5589 val_acc=0.2905 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 18/50: train_loss=2.1467 train_acc=0.3572 val_loss=2.6204 val_acc=0.2570 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 19/50: train_loss=2.1106 train_acc=0.3648 val_loss=2.5831 val_acc=0.2849 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 20/50: train_loss=2.0951 train_acc=0.3701 val_loss=2.5797 val_acc=0.2961 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 21/50: train_loss=2.0434 train_acc=0.3872 val_loss=2.6039 val_acc=0.2793 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 22/50: train_loss=1.9933 train_acc=0.4046 val_loss=2.5720 val_acc=0.2961 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 23/50: train_loss=1.9704 train_acc=0.3996 val_loss=2.6205 val_acc=0.3128 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 24/50: train_loss=1.9279 train_acc=0.4143 val_loss=2.5999 val_acc=0.2514 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 25/50: train_loss=1.8897 train_acc=0.4279 val_loss=2.5743 val_acc=0.3296 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 26/50: train_loss=1.8598 train_acc=0.4308 val_loss=2.6068 val_acc=0.2793 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 27/50: train_loss=1.8288 train_acc=0.4452 val_loss=2.7046 val_acc=0.3017 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 28/50: train_loss=1.7913 train_acc=0.4591 val_loss=2.5796 val_acc=0.3017 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 29/50: train_loss=1.7827 train_acc=0.4523 val_loss=2.5373 val_acc=0.3073 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 30/50: train_loss=1.7299 train_acc=0.4750 val_loss=2.5791 val_acc=0.3240 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 31/50: train_loss=1.7448 train_acc=0.4661 val_loss=2.5575 val_acc=0.3296 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 32/50: train_loss=1.6909 train_acc=0.4714 val_loss=2.5601 val_acc=0.3240 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 33/50: train_loss=1.6383 train_acc=0.4965 val_loss=2.5835 val_acc=0.3017 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 34/50: train_loss=1.6267 train_acc=0.4873 val_loss=2.5874 val_acc=0.3296 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 35/50: train_loss=1.6264 train_acc=0.4900 val_loss=2.6418 val_acc=0.2961 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 36/50: train_loss=1.6016 train_acc=0.5068 val_loss=2.6192 val_acc=0.3073 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 37/50: train_loss=1.5945 train_acc=0.4979 val_loss=2.5805 val_acc=0.3296 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 38/50: train_loss=1.5458 train_acc=0.5200 val_loss=2.5801 val_acc=0.3184 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 39/50: train_loss=1.5040 train_acc=0.5306 val_loss=2.6807 val_acc=0.3128 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 40/50: train_loss=1.4760 train_acc=0.5421 val_loss=2.5652 val_acc=0.2905 seconds=0.3
[CNN] early stopping at epoch 40; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__5ghz__block__ebl-session__s42__df21ec.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__5ghz__block__ebl-session__s42__df21ec/training_curves.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL GPU] run_id=dl__cnn__5ghz__block__ebl-session__s42__df21ec peak_cuda_memory_bytes=579083264
[results upsert] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/runs.csv: 7 row(s)
Seeds: random=43, numpy=43, torch=43
[trial filter] split=block trials=['01'] kept=9695/14478
[protocol] split=block trials_used=['01'] n_train=5477 n_test=1648 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05', '06'] test_users=['01', '02', '03', '04', '05', '06']
[trial filter] split=block trials=['01'] kept=5477/5477
[protocol] split=block trials_used=['01'] n_train=3396 n_test=179 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05', '06'] test_users=['01', '02', '03', '04', '05', '06']
[CNN] 5 GHz/block fold=single parameters=76308
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] 5 GHz/block fold=single epoch 01/50: train_loss=3.9162 train_acc=0.0459 val_loss=3.9089 val_acc=0.0950 seconds=3.5
[CNN] 5 GHz/block fold=single epoch 02/50: train_loss=3.7121 train_acc=0.0951 val_loss=3.6232 val_acc=0.1397 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 03/50: train_loss=3.4465 train_acc=0.0975 val_loss=3.3549 val_acc=0.1453 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 04/50: train_loss=3.2558 train_acc=0.1243 val_loss=3.1979 val_acc=0.1620 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 05/50: train_loss=3.0960 train_acc=0.1543 val_loss=3.0866 val_acc=0.1844 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 06/50: train_loss=2.9496 train_acc=0.1793 val_loss=2.9821 val_acc=0.2067 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 07/50: train_loss=2.8462 train_acc=0.1982 val_loss=2.8755 val_acc=0.1844 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 08/50: train_loss=2.7481 train_acc=0.2167 val_loss=2.8422 val_acc=0.2402 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 09/50: train_loss=2.6785 train_acc=0.2256 val_loss=2.7400 val_acc=0.2291 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 10/50: train_loss=2.5994 train_acc=0.2491 val_loss=2.6478 val_acc=0.2737 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 11/50: train_loss=2.5209 train_acc=0.2580 val_loss=2.6560 val_acc=0.2402 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 12/50: train_loss=2.4811 train_acc=0.2688 val_loss=2.6038 val_acc=0.2682 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 13/50: train_loss=2.3947 train_acc=0.2942 val_loss=2.6078 val_acc=0.2793 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 14/50: train_loss=2.3348 train_acc=0.3180 val_loss=2.5742 val_acc=0.2570 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 15/50: train_loss=2.2918 train_acc=0.3201 val_loss=2.5832 val_acc=0.2402 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 16/50: train_loss=2.2485 train_acc=0.3322 val_loss=2.5581 val_acc=0.2570 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 17/50: train_loss=2.2295 train_acc=0.3313 val_loss=2.5528 val_acc=0.2961 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 18/50: train_loss=2.1589 train_acc=0.3592 val_loss=2.5011 val_acc=0.3017 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 19/50: train_loss=2.1289 train_acc=0.3604 val_loss=2.5173 val_acc=0.2905 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 20/50: train_loss=2.0736 train_acc=0.3781 val_loss=2.5298 val_acc=0.2849 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 21/50: train_loss=2.0276 train_acc=0.3857 val_loss=2.4931 val_acc=0.3184 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 22/50: train_loss=1.9734 train_acc=0.3966 val_loss=2.4735 val_acc=0.3073 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 23/50: train_loss=1.9430 train_acc=0.4158 val_loss=2.4591 val_acc=0.3240 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 24/50: train_loss=1.9020 train_acc=0.4226 val_loss=2.5007 val_acc=0.3073 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 25/50: train_loss=1.9127 train_acc=0.4140 val_loss=2.5318 val_acc=0.3017 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 26/50: train_loss=1.8981 train_acc=0.4223 val_loss=2.6198 val_acc=0.3184 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 27/50: train_loss=1.8142 train_acc=0.4399 val_loss=2.5348 val_acc=0.3464 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 28/50: train_loss=1.7947 train_acc=0.4547 val_loss=2.5500 val_acc=0.2905 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 29/50: train_loss=1.7740 train_acc=0.4547 val_loss=2.4126 val_acc=0.3687 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 30/50: train_loss=1.7506 train_acc=0.4614 val_loss=2.4957 val_acc=0.3240 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 31/50: train_loss=1.7083 train_acc=0.4794 val_loss=2.4646 val_acc=0.3296 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 32/50: train_loss=1.7130 train_acc=0.4703 val_loss=2.4735 val_acc=0.3296 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 33/50: train_loss=1.6666 train_acc=0.4829 val_loss=2.5364 val_acc=0.3240 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 34/50: train_loss=1.6353 train_acc=0.4929 val_loss=2.4853 val_acc=0.3184 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 35/50: train_loss=1.6112 train_acc=0.5077 val_loss=2.4524 val_acc=0.3520 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 36/50: train_loss=1.5937 train_acc=0.5183 val_loss=2.5508 val_acc=0.3240 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 37/50: train_loss=1.5697 train_acc=0.5130 val_loss=2.4648 val_acc=0.3464 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 38/50: train_loss=1.5540 train_acc=0.5300 val_loss=2.5121 val_acc=0.3408 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 39/50: train_loss=1.5073 train_acc=0.5271 val_loss=2.5124 val_acc=0.3408 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 40/50: train_loss=1.5272 train_acc=0.5203 val_loss=2.5345 val_acc=0.3240 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 41/50: train_loss=1.4878 train_acc=0.5415 val_loss=2.5410 val_acc=0.3073 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 42/50: train_loss=1.4694 train_acc=0.5312 val_loss=2.5511 val_acc=0.3296 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 43/50: train_loss=1.4537 train_acc=0.5433 val_loss=2.5084 val_acc=0.3128 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 44/50: train_loss=1.4084 train_acc=0.5680 val_loss=2.5197 val_acc=0.3296 seconds=0.2
[CNN] early stopping at epoch 44; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__5ghz__block__ebl-session__s43__210c56.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__5ghz__block__ebl-session__s43__210c56/training_curves.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL GPU] run_id=dl__cnn__5ghz__block__ebl-session__s43__210c56 peak_cuda_memory_bytes=579083264
[results upsert] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/runs.csv: 8 row(s)
Seeds: random=44, numpy=44, torch=44
[trial filter] split=block trials=['01'] kept=9695/14478
[protocol] split=block trials_used=['01'] n_train=5477 n_test=1648 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05', '06'] test_users=['01', '02', '03', '04', '05', '06']
[trial filter] split=block trials=['01'] kept=5477/5477
[protocol] split=block trials_used=['01'] n_train=3396 n_test=179 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05', '06'] test_users=['01', '02', '03', '04', '05', '06']
[CNN] 5 GHz/block fold=single parameters=76308
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] 5 GHz/block fold=single epoch 01/50: train_loss=3.9120 train_acc=0.0392 val_loss=3.9106 val_acc=0.0447 seconds=3.6
[CNN] 5 GHz/block fold=single epoch 02/50: train_loss=3.7049 train_acc=0.0819 val_loss=3.6267 val_acc=0.1061 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 03/50: train_loss=3.4465 train_acc=0.0992 val_loss=3.3644 val_acc=0.1229 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 04/50: train_loss=3.2678 train_acc=0.1343 val_loss=3.2246 val_acc=0.1341 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 05/50: train_loss=3.1401 train_acc=0.1428 val_loss=3.0985 val_acc=0.1620 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 06/50: train_loss=3.0171 train_acc=0.1787 val_loss=3.0423 val_acc=0.1732 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 07/50: train_loss=2.9066 train_acc=0.1911 val_loss=2.9100 val_acc=0.1676 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 08/50: train_loss=2.8052 train_acc=0.2167 val_loss=2.8982 val_acc=0.1844 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 09/50: train_loss=2.7196 train_acc=0.2261 val_loss=2.8778 val_acc=0.2123 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 10/50: train_loss=2.6521 train_acc=0.2320 val_loss=2.8091 val_acc=0.2067 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 11/50: train_loss=2.5847 train_acc=0.2544 val_loss=2.7652 val_acc=0.2235 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 12/50: train_loss=2.5207 train_acc=0.2609 val_loss=2.7282 val_acc=0.2458 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 13/50: train_loss=2.4688 train_acc=0.2762 val_loss=2.6925 val_acc=0.2737 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 14/50: train_loss=2.3978 train_acc=0.3042 val_loss=2.6750 val_acc=0.2626 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 15/50: train_loss=2.3440 train_acc=0.3080 val_loss=2.6417 val_acc=0.2346 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 16/50: train_loss=2.2973 train_acc=0.3189 val_loss=2.6737 val_acc=0.2626 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 17/50: train_loss=2.2567 train_acc=0.3313 val_loss=2.6752 val_acc=0.2346 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 18/50: train_loss=2.2171 train_acc=0.3469 val_loss=2.6146 val_acc=0.3073 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 19/50: train_loss=2.1540 train_acc=0.3534 val_loss=2.6613 val_acc=0.2737 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 20/50: train_loss=2.1026 train_acc=0.3766 val_loss=2.6846 val_acc=0.2682 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 21/50: train_loss=2.1024 train_acc=0.3645 val_loss=2.5457 val_acc=0.3073 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 22/50: train_loss=2.0344 train_acc=0.3893 val_loss=2.5581 val_acc=0.3073 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 23/50: train_loss=2.0124 train_acc=0.3981 val_loss=2.5811 val_acc=0.2905 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 24/50: train_loss=1.9738 train_acc=0.4052 val_loss=2.5690 val_acc=0.3352 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 25/50: train_loss=1.9278 train_acc=0.4211 val_loss=2.5644 val_acc=0.2905 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 26/50: train_loss=1.9170 train_acc=0.4258 val_loss=2.5132 val_acc=0.2961 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 27/50: train_loss=1.8626 train_acc=0.4541 val_loss=2.5350 val_acc=0.3408 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 28/50: train_loss=1.8339 train_acc=0.4420 val_loss=2.5649 val_acc=0.3408 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 29/50: train_loss=1.8022 train_acc=0.4541 val_loss=2.5241 val_acc=0.3017 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 30/50: train_loss=1.7939 train_acc=0.4514 val_loss=2.5608 val_acc=0.3128 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 31/50: train_loss=1.7521 train_acc=0.4717 val_loss=2.4672 val_acc=0.3184 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 32/50: train_loss=1.7158 train_acc=0.4779 val_loss=2.4970 val_acc=0.3520 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 33/50: train_loss=1.6916 train_acc=0.4841 val_loss=2.4595 val_acc=0.3184 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 34/50: train_loss=1.6766 train_acc=0.4909 val_loss=2.5245 val_acc=0.3520 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 35/50: train_loss=1.6449 train_acc=0.4950 val_loss=2.5225 val_acc=0.3408 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 36/50: train_loss=1.6317 train_acc=0.5115 val_loss=2.5426 val_acc=0.3296 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 37/50: train_loss=1.5805 train_acc=0.5250 val_loss=2.5202 val_acc=0.3520 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 38/50: train_loss=1.5500 train_acc=0.5230 val_loss=2.4786 val_acc=0.3296 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 39/50: train_loss=1.5687 train_acc=0.5233 val_loss=2.5182 val_acc=0.3687 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 40/50: train_loss=1.5196 train_acc=0.5327 val_loss=2.5109 val_acc=0.3128 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 41/50: train_loss=1.5069 train_acc=0.5398 val_loss=2.5120 val_acc=0.3128 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 42/50: train_loss=1.5099 train_acc=0.5339 val_loss=2.5402 val_acc=0.3240 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 43/50: train_loss=1.4646 train_acc=0.5501 val_loss=2.5004 val_acc=0.2793 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 44/50: train_loss=1.4536 train_acc=0.5504 val_loss=2.5753 val_acc=0.3184 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 45/50: train_loss=1.4366 train_acc=0.5568 val_loss=2.5190 val_acc=0.3687 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 46/50: train_loss=1.3851 train_acc=0.5760 val_loss=2.5288 val_acc=0.3296 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 47/50: train_loss=1.3967 train_acc=0.5707 val_loss=2.5641 val_acc=0.3575 seconds=0.2
[CNN] 5 GHz/block fold=single epoch 48/50: train_loss=1.3832 train_acc=0.5707 val_loss=2.6212 val_acc=0.3296 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 49/50: train_loss=1.3614 train_acc=0.5848 val_loss=2.5293 val_acc=0.3240 seconds=0.3
[CNN] 5 GHz/block fold=single epoch 50/50: train_loss=1.3497 train_acc=0.5895 val_loss=2.5639 val_acc=0.3464 seconds=0.2

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__5ghz__block__ebl-session__s44__86f94f.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__5ghz__block__ebl-session__s44__86f94f/training_curves.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL GPU] run_id=dl__cnn__5ghz__block__ebl-session__s44__86f94f peak_cuda_memory_bytes=579083264
[results upsert] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/runs.csv: 9 row(s)
[DL seeds] mean +/- std across seeds written to tables/seed_summary; LOVO uses each seed's fold mean and keeps within-seed fold std separate.

=== Fusion ===
[window arrays] cache path: /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/.cache/dataframes/preproc=norm-empty_baseline_scope-per_session/feat=win60-step0/window_arrays/fusion
[window arrays] 2.4 GHz: shape=(13568, 9, 50, 60), dtype=float16
[window arrays] 2.4 GHz anchors: ['esp_01', 'esp_02', 'esp_03', 'esp_04', 'esp_05', 'esp_07', 'esp_08', 'esp_09', 'esp_10']
[window arrays] 5 GHz: shape=(13568, 10, 56, 60), dtype=float16
[window arrays] 5 GHz anchors: ['esp_11', 'esp_12', 'esp_13', 'esp_14', 'esp_15', 'esp_16', 'esp_17', 'esp_18', 'esp_19', 'esp_20']
2.4 GHz: anchors=9, subcarriers=50, windows=13568
5 GHz: anchors=10, subcarriers=56, windows=13568
Fusion N PASS: 13568 windows
WINDOW IDENTITY PASS: Fusion (13568 windows)
[trial filter] split=block trials=['01'] kept=8889/13568
[protocol] split=block trials_used=['01'] n_train=4934 n_test=1388 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05', '06'] test_users=['01', '02', '03', '04', '05', '06']
[trial filter] split=block trials=['01'] kept=8889/13568
[protocol] split=block trials_used=['01'] n_train=4934 n_test=1388 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05', '06'] test_users=['01', '02', '03', '04', '05', '06']
SPLIT IDENTITY PASS: Fusion/block fold=1 train=4934 test=1388
Seeds: random=42, numpy=42, torch=42
[trial filter] split=block trials=['01'] kept=8889/13568
[protocol] split=block trials_used=['01'] n_train=4934 n_test=1388 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05', '06'] test_users=['01', '02', '03', '04', '05', '06']
[trial filter] split=block trials=['01'] kept=4934/4934
[protocol] split=block trials_used=['01'] n_train=3003 n_test=150 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05', '06'] test_users=['01', '02', '03', '04', '05', '06']
[CNN] Fusion/block fold=single parameters=138708
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] Fusion/block fold=single epoch 01/50: train_loss=3.9134 train_acc=0.0436 val_loss=3.9248 val_acc=0.0733 seconds=4.4
[CNN] Fusion/block fold=single epoch 02/50: train_loss=3.7049 train_acc=0.1092 val_loss=3.7327 val_acc=0.0400 seconds=0.4
[CNN] Fusion/block fold=single epoch 03/50: train_loss=3.3861 train_acc=0.1538 val_loss=3.4079 val_acc=0.0933 seconds=0.4
[CNN] Fusion/block fold=single epoch 04/50: train_loss=3.0519 train_acc=0.1841 val_loss=3.1364 val_acc=0.1533 seconds=0.3
[CNN] Fusion/block fold=single epoch 05/50: train_loss=2.8067 train_acc=0.2231 val_loss=2.8274 val_acc=0.1733 seconds=0.4
[CNN] Fusion/block fold=single epoch 06/50: train_loss=2.6119 train_acc=0.2577 val_loss=2.8187 val_acc=0.1933 seconds=0.4
[CNN] Fusion/block fold=single epoch 07/50: train_loss=2.4410 train_acc=0.2967 val_loss=2.5752 val_acc=0.2267 seconds=0.4
[CNN] Fusion/block fold=single epoch 08/50: train_loss=2.3327 train_acc=0.3140 val_loss=2.4866 val_acc=0.2600 seconds=0.4
[CNN] Fusion/block fold=single epoch 09/50: train_loss=2.2031 train_acc=0.3447 val_loss=2.4153 val_acc=0.2733 seconds=0.4
[CNN] Fusion/block fold=single epoch 10/50: train_loss=2.0966 train_acc=0.3800 val_loss=2.3894 val_acc=0.2533 seconds=0.4
[CNN] Fusion/block fold=single epoch 11/50: train_loss=1.9862 train_acc=0.4056 val_loss=2.3492 val_acc=0.3067 seconds=0.4
[CNN] Fusion/block fold=single epoch 12/50: train_loss=1.8821 train_acc=0.4366 val_loss=2.2241 val_acc=0.3467 seconds=0.4
[CNN] Fusion/block fold=single epoch 13/50: train_loss=1.8178 train_acc=0.4625 val_loss=2.2089 val_acc=0.3133 seconds=0.4
[CNN] Fusion/block fold=single epoch 14/50: train_loss=1.7386 train_acc=0.4755 val_loss=2.3373 val_acc=0.3333 seconds=0.4
[CNN] Fusion/block fold=single epoch 15/50: train_loss=1.6609 train_acc=0.5045 val_loss=2.1117 val_acc=0.3867 seconds=0.4
[CNN] Fusion/block fold=single epoch 16/50: train_loss=1.6033 train_acc=0.5105 val_loss=2.1078 val_acc=0.3600 seconds=0.4
[CNN] Fusion/block fold=single epoch 17/50: train_loss=1.5322 train_acc=0.5455 val_loss=2.0654 val_acc=0.3800 seconds=0.4
[CNN] Fusion/block fold=single epoch 18/50: train_loss=1.4641 train_acc=0.5698 val_loss=2.2087 val_acc=0.3600 seconds=0.4
[CNN] Fusion/block fold=single epoch 19/50: train_loss=1.4084 train_acc=0.5768 val_loss=2.1069 val_acc=0.4000 seconds=0.4
[CNN] Fusion/block fold=single epoch 20/50: train_loss=1.3314 train_acc=0.5994 val_loss=2.1741 val_acc=0.3600 seconds=0.4
[CNN] Fusion/block fold=single epoch 21/50: train_loss=1.2794 train_acc=0.6154 val_loss=2.0637 val_acc=0.3867 seconds=0.4
[CNN] Fusion/block fold=single epoch 22/50: train_loss=1.2653 train_acc=0.6161 val_loss=2.0379 val_acc=0.3867 seconds=0.4
[CNN] Fusion/block fold=single epoch 23/50: train_loss=1.1997 train_acc=0.6390 val_loss=2.1036 val_acc=0.4133 seconds=0.4
[CNN] Fusion/block fold=single epoch 24/50: train_loss=1.1288 train_acc=0.6633 val_loss=2.0274 val_acc=0.4067 seconds=0.4
[CNN] Fusion/block fold=single epoch 25/50: train_loss=1.0941 train_acc=0.6707 val_loss=2.0007 val_acc=0.4200 seconds=0.4
[CNN] Fusion/block fold=single epoch 26/50: train_loss=1.0454 train_acc=0.6833 val_loss=1.9998 val_acc=0.4533 seconds=0.4
[CNN] Fusion/block fold=single epoch 27/50: train_loss=1.0127 train_acc=0.6903 val_loss=2.1102 val_acc=0.3867 seconds=0.4
[CNN] Fusion/block fold=single epoch 28/50: train_loss=0.9733 train_acc=0.7063 val_loss=1.9995 val_acc=0.4800 seconds=0.4
[CNN] Fusion/block fold=single epoch 29/50: train_loss=0.9654 train_acc=0.7063 val_loss=2.0409 val_acc=0.4000 seconds=0.4
[CNN] Fusion/block fold=single epoch 30/50: train_loss=0.9118 train_acc=0.7179 val_loss=2.0946 val_acc=0.4467 seconds=0.4
[CNN] Fusion/block fold=single epoch 31/50: train_loss=0.8846 train_acc=0.7313 val_loss=2.0654 val_acc=0.4600 seconds=0.4
[CNN] Fusion/block fold=single epoch 32/50: train_loss=0.8287 train_acc=0.7429 val_loss=2.1490 val_acc=0.4200 seconds=0.4
[CNN] Fusion/block fold=single epoch 33/50: train_loss=0.7919 train_acc=0.7679 val_loss=1.9954 val_acc=0.4733 seconds=0.4
[CNN] Fusion/block fold=single epoch 34/50: train_loss=0.7705 train_acc=0.7649 val_loss=2.1646 val_acc=0.4267 seconds=0.4
[CNN] Fusion/block fold=single epoch 35/50: train_loss=0.7514 train_acc=0.7679 val_loss=1.9791 val_acc=0.4800 seconds=0.4
[CNN] Fusion/block fold=single epoch 36/50: train_loss=0.7456 train_acc=0.7709 val_loss=2.4106 val_acc=0.3867 seconds=0.4
[CNN] Fusion/block fold=single epoch 37/50: train_loss=0.6997 train_acc=0.7912 val_loss=2.0861 val_acc=0.4533 seconds=0.4
[CNN] Fusion/block fold=single epoch 38/50: train_loss=0.6933 train_acc=0.7882 val_loss=2.2278 val_acc=0.4267 seconds=0.4
[CNN] Fusion/block fold=single epoch 39/50: train_loss=0.6638 train_acc=0.8032 val_loss=2.1659 val_acc=0.4467 seconds=0.4
[CNN] Fusion/block fold=single epoch 40/50: train_loss=0.6391 train_acc=0.8072 val_loss=2.1354 val_acc=0.4867 seconds=0.4
[CNN] Fusion/block fold=single epoch 41/50: train_loss=0.6129 train_acc=0.8092 val_loss=2.0663 val_acc=0.4667 seconds=0.4
[CNN] Fusion/block fold=single epoch 42/50: train_loss=0.6041 train_acc=0.8165 val_loss=2.0190 val_acc=0.4867 seconds=0.4
[CNN] Fusion/block fold=single epoch 43/50: train_loss=0.5805 train_acc=0.8228 val_loss=2.1726 val_acc=0.4667 seconds=0.4
[CNN] Fusion/block fold=single epoch 44/50: train_loss=0.5547 train_acc=0.8342 val_loss=2.0795 val_acc=0.4933 seconds=0.4
[CNN] Fusion/block fold=single epoch 45/50: train_loss=0.5125 train_acc=0.8435 val_loss=2.1531 val_acc=0.4333 seconds=0.4
[CNN] Fusion/block fold=single epoch 46/50: train_loss=0.5142 train_acc=0.8508 val_loss=2.4115 val_acc=0.4267 seconds=0.4
[CNN] Fusion/block fold=single epoch 47/50: train_loss=0.5002 train_acc=0.8445 val_loss=2.3928 val_acc=0.4267 seconds=0.4
[CNN] Fusion/block fold=single epoch 48/50: train_loss=0.4901 train_acc=0.8472 val_loss=2.1488 val_acc=0.4600 seconds=0.4
[CNN] Fusion/block fold=single epoch 49/50: train_loss=0.4476 train_acc=0.8695 val_loss=2.2276 val_acc=0.4733 seconds=0.4
[CNN] Fusion/block fold=single epoch 50/50: train_loss=0.4346 train_acc=0.8701 val_loss=2.1911 val_acc=0.4933 seconds=0.4

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__fusion__block__ebl-session__s42__df21ec.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__fusion__block__ebl-session__s42__df21ec/training_curves.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL GPU] run_id=dl__cnn__fusion__block__ebl-session__s42__df21ec peak_cuda_memory_bytes=978418688
[results upsert] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/runs.csv: 10 row(s)
Seeds: random=43, numpy=43, torch=43
[trial filter] split=block trials=['01'] kept=8889/13568
[protocol] split=block trials_used=['01'] n_train=4934 n_test=1388 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05', '06'] test_users=['01', '02', '03', '04', '05', '06']
[trial filter] split=block trials=['01'] kept=4934/4934
[protocol] split=block trials_used=['01'] n_train=3003 n_test=150 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05', '06'] test_users=['01', '02', '03', '04', '05', '06']
[CNN] Fusion/block fold=single parameters=138708
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] Fusion/block fold=single epoch 01/50: train_loss=3.9093 train_acc=0.0480 val_loss=3.9143 val_acc=0.0467 seconds=3.8
[CNN] Fusion/block fold=single epoch 02/50: train_loss=3.7003 train_acc=0.1092 val_loss=3.7295 val_acc=0.0533 seconds=0.4
[CNN] Fusion/block fold=single epoch 03/50: train_loss=3.3816 train_acc=0.1459 val_loss=3.3970 val_acc=0.1267 seconds=0.4
[CNN] Fusion/block fold=single epoch 04/50: train_loss=3.0565 train_acc=0.1845 val_loss=3.0499 val_acc=0.1733 seconds=0.4
[CNN] Fusion/block fold=single epoch 05/50: train_loss=2.7843 train_acc=0.2354 val_loss=2.8672 val_acc=0.1733 seconds=0.3
[CNN] Fusion/block fold=single epoch 06/50: train_loss=2.6221 train_acc=0.2584 val_loss=2.6310 val_acc=0.2333 seconds=0.3
[CNN] Fusion/block fold=single epoch 07/50: train_loss=2.4405 train_acc=0.2950 val_loss=2.4384 val_acc=0.3067 seconds=0.3
[CNN] Fusion/block fold=single epoch 08/50: train_loss=2.3211 train_acc=0.3287 val_loss=2.3884 val_acc=0.2200 seconds=0.4
[CNN] Fusion/block fold=single epoch 09/50: train_loss=2.1893 train_acc=0.3580 val_loss=2.3361 val_acc=0.2867 seconds=0.4
[CNN] Fusion/block fold=single epoch 10/50: train_loss=2.0919 train_acc=0.3846 val_loss=2.3036 val_acc=0.2733 seconds=0.3
[CNN] Fusion/block fold=single epoch 11/50: train_loss=1.9754 train_acc=0.4202 val_loss=2.1653 val_acc=0.3467 seconds=0.4
[CNN] Fusion/block fold=single epoch 12/50: train_loss=1.8855 train_acc=0.4422 val_loss=2.0943 val_acc=0.3333 seconds=0.4
[CNN] Fusion/block fold=single epoch 13/50: train_loss=1.7751 train_acc=0.4665 val_loss=2.0433 val_acc=0.3733 seconds=0.3
[CNN] Fusion/block fold=single epoch 14/50: train_loss=1.7295 train_acc=0.4822 val_loss=2.0225 val_acc=0.3867 seconds=0.4
[CNN] Fusion/block fold=single epoch 15/50: train_loss=1.6385 train_acc=0.5122 val_loss=2.0097 val_acc=0.3533 seconds=0.4
[CNN] Fusion/block fold=single epoch 16/50: train_loss=1.5510 train_acc=0.5308 val_loss=2.0748 val_acc=0.3333 seconds=0.4
[CNN] Fusion/block fold=single epoch 17/50: train_loss=1.5096 train_acc=0.5415 val_loss=2.0370 val_acc=0.3533 seconds=0.4
[CNN] Fusion/block fold=single epoch 18/50: train_loss=1.4496 train_acc=0.5721 val_loss=2.0349 val_acc=0.3800 seconds=0.4
[CNN] Fusion/block fold=single epoch 19/50: train_loss=1.3669 train_acc=0.5801 val_loss=1.8826 val_acc=0.4200 seconds=0.4
[CNN] Fusion/block fold=single epoch 20/50: train_loss=1.3223 train_acc=0.5921 val_loss=1.9490 val_acc=0.4333 seconds=0.4
[CNN] Fusion/block fold=single epoch 21/50: train_loss=1.2631 train_acc=0.6267 val_loss=1.9151 val_acc=0.4267 seconds=0.4
[CNN] Fusion/block fold=single epoch 22/50: train_loss=1.1905 train_acc=0.6327 val_loss=2.0414 val_acc=0.3933 seconds=0.4
[CNN] Fusion/block fold=single epoch 23/50: train_loss=1.1749 train_acc=0.6370 val_loss=1.9517 val_acc=0.4000 seconds=0.4
[CNN] Fusion/block fold=single epoch 24/50: train_loss=1.1278 train_acc=0.6537 val_loss=1.9615 val_acc=0.4133 seconds=0.4
[CNN] Fusion/block fold=single epoch 25/50: train_loss=1.0968 train_acc=0.6540 val_loss=1.9395 val_acc=0.4333 seconds=0.4
[CNN] Fusion/block fold=single epoch 26/50: train_loss=1.0289 train_acc=0.6850 val_loss=1.9325 val_acc=0.4133 seconds=0.4
[CNN] Fusion/block fold=single epoch 27/50: train_loss=1.0074 train_acc=0.6913 val_loss=1.9077 val_acc=0.4333 seconds=0.4
[CNN] Fusion/block fold=single epoch 28/50: train_loss=0.9449 train_acc=0.7103 val_loss=1.9437 val_acc=0.4200 seconds=0.4
[CNN] Fusion/block fold=single epoch 29/50: train_loss=0.9029 train_acc=0.7263 val_loss=1.8983 val_acc=0.4667 seconds=0.3
[CNN] Fusion/block fold=single epoch 30/50: train_loss=0.8721 train_acc=0.7366 val_loss=1.9929 val_acc=0.4267 seconds=0.4
[CNN] Fusion/block fold=single epoch 31/50: train_loss=0.8431 train_acc=0.7473 val_loss=1.9077 val_acc=0.4800 seconds=0.3
[CNN] Fusion/block fold=single epoch 32/50: train_loss=0.8317 train_acc=0.7446 val_loss=2.0405 val_acc=0.4200 seconds=0.4
[CNN] Fusion/block fold=single epoch 33/50: train_loss=0.7881 train_acc=0.7566 val_loss=1.8904 val_acc=0.4400 seconds=0.3
[CNN] Fusion/block fold=single epoch 34/50: train_loss=0.7688 train_acc=0.7662 val_loss=1.9530 val_acc=0.4533 seconds=0.4
[CNN] Fusion/block fold=single epoch 35/50: train_loss=0.7379 train_acc=0.7709 val_loss=1.9691 val_acc=0.4400 seconds=0.3
[CNN] Fusion/block fold=single epoch 36/50: train_loss=0.6976 train_acc=0.7995 val_loss=2.0118 val_acc=0.4600 seconds=0.3
[CNN] Fusion/block fold=single epoch 37/50: train_loss=0.6849 train_acc=0.7969 val_loss=2.0030 val_acc=0.4400 seconds=0.4
[CNN] Fusion/block fold=single epoch 38/50: train_loss=0.6610 train_acc=0.8059 val_loss=1.9158 val_acc=0.4600 seconds=0.4
[CNN] Fusion/block fold=single epoch 39/50: train_loss=0.6394 train_acc=0.7999 val_loss=2.0971 val_acc=0.4200 seconds=0.4
[CNN] Fusion/block fold=single epoch 40/50: train_loss=0.6093 train_acc=0.8142 val_loss=1.9553 val_acc=0.4600 seconds=0.4
[CNN] Fusion/block fold=single epoch 41/50: train_loss=0.5983 train_acc=0.8142 val_loss=2.0637 val_acc=0.4333 seconds=0.4
[CNN] Fusion/block fold=single epoch 42/50: train_loss=0.5899 train_acc=0.8242 val_loss=2.0005 val_acc=0.4400 seconds=0.3
[CNN] Fusion/block fold=single epoch 43/50: train_loss=0.5501 train_acc=0.8295 val_loss=1.9857 val_acc=0.4867 seconds=0.3
[CNN] Fusion/block fold=single epoch 44/50: train_loss=0.5391 train_acc=0.8365 val_loss=2.0644 val_acc=0.4400 seconds=0.4
[CNN] Fusion/block fold=single epoch 45/50: train_loss=0.5232 train_acc=0.8482 val_loss=2.1586 val_acc=0.4400 seconds=0.4
[CNN] Fusion/block fold=single epoch 46/50: train_loss=0.4984 train_acc=0.8488 val_loss=2.2075 val_acc=0.4400 seconds=0.4
[CNN] Fusion/block fold=single epoch 47/50: train_loss=0.4740 train_acc=0.8611 val_loss=2.1149 val_acc=0.4800 seconds=0.4
[CNN] Fusion/block fold=single epoch 48/50: train_loss=0.4841 train_acc=0.8508 val_loss=2.1833 val_acc=0.4600 seconds=0.4
[CNN] Fusion/block fold=single epoch 49/50: train_loss=0.4751 train_acc=0.8565 val_loss=2.0306 val_acc=0.4800 seconds=0.4
[CNN] Fusion/block fold=single epoch 50/50: train_loss=0.4490 train_acc=0.8688 val_loss=2.1834 val_acc=0.4467 seconds=0.4

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__fusion__block__ebl-session__s43__210c56.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__fusion__block__ebl-session__s43__210c56/training_curves.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL GPU] run_id=dl__cnn__fusion__block__ebl-session__s43__210c56 peak_cuda_memory_bytes=978418688
[results upsert] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/runs.csv: 11 row(s)
Seeds: random=44, numpy=44, torch=44
[trial filter] split=block trials=['01'] kept=8889/13568
[protocol] split=block trials_used=['01'] n_train=4934 n_test=1388 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05', '06'] test_users=['01', '02', '03', '04', '05', '06']
[trial filter] split=block trials=['01'] kept=4934/4934
[protocol] split=block trials_used=['01'] n_train=3003 n_test=150 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05', '06'] test_users=['01', '02', '03', '04', '05', '06']
[CNN] Fusion/block fold=single parameters=138708
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] Fusion/block fold=single epoch 01/50: train_loss=3.9090 train_acc=0.0496 val_loss=3.9250 val_acc=0.0533 seconds=3.7
[CNN] Fusion/block fold=single epoch 02/50: train_loss=3.6801 train_acc=0.1142 val_loss=3.7050 val_acc=0.0867 seconds=0.4
[CNN] Fusion/block fold=single epoch 03/50: train_loss=3.3413 train_acc=0.1489 val_loss=3.3887 val_acc=0.1000 seconds=0.3
[CNN] Fusion/block fold=single epoch 04/50: train_loss=3.0295 train_acc=0.1812 val_loss=2.9856 val_acc=0.1800 seconds=0.4
[CNN] Fusion/block fold=single epoch 05/50: train_loss=2.7953 train_acc=0.2211 val_loss=2.7671 val_acc=0.2267 seconds=0.3
[CNN] Fusion/block fold=single epoch 06/50: train_loss=2.6331 train_acc=0.2557 val_loss=2.6164 val_acc=0.2333 seconds=0.3
[CNN] Fusion/block fold=single epoch 07/50: train_loss=2.4489 train_acc=0.2977 val_loss=2.4470 val_acc=0.2867 seconds=0.4
[CNN] Fusion/block fold=single epoch 08/50: train_loss=2.3327 train_acc=0.3160 val_loss=2.4472 val_acc=0.2400 seconds=0.4
[CNN] Fusion/block fold=single epoch 09/50: train_loss=2.2013 train_acc=0.3576 val_loss=2.2943 val_acc=0.3133 seconds=0.4
[CNN] Fusion/block fold=single epoch 10/50: train_loss=2.0769 train_acc=0.3833 val_loss=2.2469 val_acc=0.3533 seconds=0.3
[CNN] Fusion/block fold=single epoch 11/50: train_loss=1.9824 train_acc=0.4159 val_loss=2.1770 val_acc=0.3467 seconds=0.3
[CNN] Fusion/block fold=single epoch 12/50: train_loss=1.8780 train_acc=0.4376 val_loss=2.1443 val_acc=0.3533 seconds=0.3
[CNN] Fusion/block fold=single epoch 13/50: train_loss=1.7872 train_acc=0.4655 val_loss=2.1424 val_acc=0.3400 seconds=0.4
[CNN] Fusion/block fold=single epoch 14/50: train_loss=1.7030 train_acc=0.4902 val_loss=2.0714 val_acc=0.3933 seconds=0.3
[CNN] Fusion/block fold=single epoch 15/50: train_loss=1.6322 train_acc=0.5185 val_loss=2.0886 val_acc=0.3600 seconds=0.3
[CNN] Fusion/block fold=single epoch 16/50: train_loss=1.5506 train_acc=0.5458 val_loss=1.9992 val_acc=0.4200 seconds=0.3
[CNN] Fusion/block fold=single epoch 17/50: train_loss=1.4784 train_acc=0.5485 val_loss=2.0254 val_acc=0.3800 seconds=0.4
[CNN] Fusion/block fold=single epoch 18/50: train_loss=1.4382 train_acc=0.5718 val_loss=2.0484 val_acc=0.4133 seconds=0.4
[CNN] Fusion/block fold=single epoch 19/50: train_loss=1.3771 train_acc=0.5951 val_loss=2.0460 val_acc=0.4067 seconds=0.3
[CNN] Fusion/block fold=single epoch 20/50: train_loss=1.3044 train_acc=0.6144 val_loss=1.9749 val_acc=0.4200 seconds=0.4
[CNN] Fusion/block fold=single epoch 21/50: train_loss=1.2410 train_acc=0.6217 val_loss=1.9121 val_acc=0.4867 seconds=0.4
[CNN] Fusion/block fold=single epoch 22/50: train_loss=1.1815 train_acc=0.6467 val_loss=2.1122 val_acc=0.4067 seconds=0.3
[CNN] Fusion/block fold=single epoch 23/50: train_loss=1.1490 train_acc=0.6507 val_loss=1.8770 val_acc=0.4667 seconds=0.4
[CNN] Fusion/block fold=single epoch 24/50: train_loss=1.1098 train_acc=0.6613 val_loss=1.9747 val_acc=0.4400 seconds=0.4
[CNN] Fusion/block fold=single epoch 25/50: train_loss=1.0661 train_acc=0.6703 val_loss=1.9972 val_acc=0.4067 seconds=0.3
[CNN] Fusion/block fold=single epoch 26/50: train_loss=1.0178 train_acc=0.6940 val_loss=2.0576 val_acc=0.4067 seconds=0.3
[CNN] Fusion/block fold=single epoch 27/50: train_loss=0.9996 train_acc=0.6943 val_loss=2.1122 val_acc=0.4133 seconds=0.3
[CNN] Fusion/block fold=single epoch 28/50: train_loss=0.9245 train_acc=0.7319 val_loss=1.9607 val_acc=0.4733 seconds=0.3
[CNN] Fusion/block fold=single epoch 29/50: train_loss=0.9243 train_acc=0.7130 val_loss=2.1671 val_acc=0.4600 seconds=0.3
[CNN] Fusion/block fold=single epoch 30/50: train_loss=0.8677 train_acc=0.7436 val_loss=2.0630 val_acc=0.4533 seconds=0.4
[CNN] Fusion/block fold=single epoch 31/50: train_loss=0.8629 train_acc=0.7363 val_loss=2.0350 val_acc=0.4200 seconds=0.4
[CNN] Fusion/block fold=single epoch 32/50: train_loss=0.8333 train_acc=0.7522 val_loss=2.0133 val_acc=0.4200 seconds=0.4
[CNN] Fusion/block fold=single epoch 33/50: train_loss=0.7711 train_acc=0.7699 val_loss=2.1050 val_acc=0.4533 seconds=0.4
[CNN] Fusion/block fold=single epoch 34/50: train_loss=0.7621 train_acc=0.7669 val_loss=2.0408 val_acc=0.4267 seconds=0.4
[CNN] Fusion/block fold=single epoch 35/50: train_loss=0.7260 train_acc=0.7829 val_loss=2.1196 val_acc=0.4533 seconds=0.4
[CNN] Fusion/block fold=single epoch 36/50: train_loss=0.7305 train_acc=0.7736 val_loss=2.1610 val_acc=0.4533 seconds=0.4
[CNN] early stopping at epoch 36; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__fusion__block__ebl-session__s44__86f94f.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__fusion__block__ebl-session__s44__86f94f/training_curves.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL GPU] run_id=dl__cnn__fusion__block__ebl-session__s44__86f94f peak_cuda_memory_bytes=978418688
[results upsert] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/runs.csv: 12 row(s)
[DL seeds] mean +/- std across seeds written to tables/seed_summary; LOVO uses each seed's fold mean and keeps within-seed fold std separate.

In [14]:
cnn_summary, test_accuracy_comparison = show_dl_results(results_dir)
display(cnn_summary)

display(test_accuracy_comparison)

,run_id,timestamp,family,model,band,split,seed,normalization,baseline_scope,window_size,...,best_epoch_std,mean_seconds_per_epoch,mean_seconds_per_epoch_mean,mean_seconds_per_epoch_std,stopped_epoch,patience_triggered,peak_cuda_memory_bytes,device,sklearn_version,numpy_version
3,dl__cnn__2_4ghz__block__ebl-session__s42__df21ec,2026-07-22T18:36:31.182108+00:00,dl,cnn,2_4ghz,block,42,empty_baseline,session,60,...,NaN,0.282136,NaN,NaN,44.0,1.0,514714624.0,cuda,1.9.0,2.5.1
4,dl__cnn__2_4ghz__block__ebl-session__s43__210c56,2026-07-22T18:36:47.242239+00:00,dl,cnn,2_4ghz,block,43,empty_baseline,session,60,...,NaN,0.251184,NaN,NaN,50.0,0.0,514714624.0,cuda,1.9.0,2.5.1
5,dl__cnn__2_4ghz__block__ebl-session__s44__86f94f,2026-07-22T18:37:03.908150+00:00,dl,cnn,2_4ghz,block,44,empty_baseline,session,60,...,NaN,0.255270,NaN,NaN,50.0,0.0,514714624.0,cuda,1.9.0,2.5.1
6,dl__cnn__5ghz__block__ebl-session__s42__df21ec,2026-07-22T18:37:26.695344+00:00,dl,cnn,5ghz,block,42,empty_baseline,session,60,...,NaN,0.345880,NaN,NaN,40.0,1.0,579083264.0,cuda,1.9.0,2.5.1
7,dl__cnn__5ghz__block__ebl-session__s43__210c56,2026-07-22T18:37:44.903111+00:00,dl,cnn,5ghz,block,43,empty_baseline,session,60,...,NaN,0.327006,NaN,NaN,44.0,1.0,579083264.0,cuda,1.9.0,2.5.1
8,dl__cnn__5ghz__block__ebl-session__s44__86f94f,2026-07-22T18:38:04.402553+00:00,dl,cnn,5ghz,block,44,empty_baseline,session,60,...,NaN,0.312220,NaN,NaN,50.0,0.0,579083264.0,cuda,1.9.0,2.5.1
9,dl__cnn__fusion__block__ebl-session__s42__df21ec,2026-07-22T18:38:41.941273+00:00,dl,cnn,fusion,block,42,empty_baseline,session,60,...,NaN,0.463929,NaN,NaN,50.0,0.0,978418688.0,cuda,1.9.0,2.5.1
10,dl__cnn__fusion__block__ebl-session__s43__210c56,2026-07-22T18:39:07.169167+00:00,dl,cnn,fusion,block,43,empty_baseline,session,60,...,NaN,0.432133,NaN,NaN,50.0,0.0,978418688.0,cuda,1.9.0,2.5.1
11,dl__cnn__fusion__block__ebl-session__s44__86f94f,2026-07-22T18:39:27.186644+00:00,dl,cnn,fusion,block,44,empty_baseline,session,60,...,NaN,0.452285,NaN,NaN,36.0,1.0,978418688.0,cuda,1.9.0,2.5.1

      band model  seed  position_accuracy  parameter_count
3   2_4ghz   cnn    42           0.248563          76020.0
4   2_4ghz   cnn    43           0.316092          76020.0
5   2_4ghz   cnn    44           0.320402          76020.0
6     5ghz   cnn    42           0.290049          76308.0
7     5ghz   cnn    43           0.307039          76308.0
8     5ghz   cnn    44           0.324636          76308.0
9   fusion   cnn    42           0.489193         138708.0
10  fusion   cnn    43           0.462536         138708.0
11  fusion   cnn    44           0.398415         138708.0