## Multi-protocol CNN Raw CSI Experiments

This notebook runs the fixed-capacity CNN across block, LOVO, and cross-session protocols with one independent run per configured seed.

In [1]:
from __future__ import annotations

import pandas as pd
import torch

from utils.config import (
    ANCHOR_GROUPS,
    BANDS_TO_RUN,
    DATA_DIR,
    DEFAULT_CNN_PARAMS,
    DEFAULT_OVERLAP_SIZE,
    DEFAULT_WINDOW_SIZE,
    EXPECTED_ANCHORS,
    EXPECTED_SUBCARRIERS,
    SEEDS,
)
from utils.DL.dl_pipeline import (
    create_position_label_encoder,
    get_cache_path,
    get_results_path,
    prepare_dl_data,
    print_torch_environment,
    run_dl_experiments,
    show_dl_results,
)

### Configuration

In [2]:
CALIBRATION_MODE = "rssi"    # ("none", "packet_norm", "rssi")

CSV_PROCESSING_OPTIONS = {
    "max_workers": 1,
    "cache_dir": None,
    "use_cache": True,
    "force_reprocess": False,
    "min_rssi_dbm": -95.0,
}

MAGNITUDE_PROCESSING_OPTIONS = {
    "normalization": "empty_baseline",  # none | zscore | minmax | packet_minmax | empty_baseline
    "epsilon": 1e-8,
}
NORMALIZATION_BASELINE_SCOPE = "per_session"

FEATURE_EXTRACTION_OPTIONS = {
    "window_size": DEFAULT_WINDOW_SIZE,
    "overlap_size": DEFAULT_OVERLAP_SIZE,
    "require_all_esps": False,
}

BLOCK_COUNT = 10
TEST_SIZE = 0.30
VALIDATION_SIZE = 0.15
RANDOM_STATE = 42
FORCE_RETRAIN = False
SPLIT_MODES = ("lovo",)

CNN_PARAMS = {
    **DEFAULT_CNN_PARAMS,
    "model_label": "CNN",
    "epochs": 70,
    "patience": 15,
    "lr": 1e-3,
    "weight_decay": 1e-4,
    "random_state": RANDOM_STATE,
    "test_size": TEST_SIZE,
    "validation_size": VALIDATION_SIZE,
    "n_blocks": BLOCK_COUNT,
    "anchor_groups": ANCHOR_GROUPS,
    "torch_version": torch.__version__,
}

preproc_opts = dict(MAGNITUDE_PROCESSING_OPTIONS)
preproc_opts["baseline_scope"] = NORMALIZATION_BASELINE_SCOPE
feat_opts = dict(FEATURE_EXTRACTION_OPTIONS)

feature_cache_dir = get_cache_path(preproc_opts, feat_opts)
results_dir = get_results_path()
plots_dir = results_dir / "plots"
for directory in (plots_dir, results_dir / "predictions", results_dir / "tables"):
    directory.mkdir(parents=True, exist_ok=True)

print(f"Feature cache path: {feature_cache_dir}")
print(f"Results path: {results_dir}")

Feature cache path: /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/.cache/dataframes/preproc=norm-empty_baseline_scope-per_session/feat=win60-step0
Results path: /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results

### Environment

In [3]:
DEVICE = print_torch_environment(require_cuda=True)

torch.__version__: 2.11.0+cu128
torch.version.cuda: 12.8
torch.cuda.get_device_name(0): NVIDIA RTX PRO 6000 Blackwell Max-Q Workstation Edition
torch.cuda.get_device_capability(0): (12, 0)
CUDA matmul smoke test result: [[0.0, 1.0, 2.0, 3.0], [4.0, 5.0, 6.0, 7.0], [8.0, 9.0, 10.0, 11.0], [12.0, 13.0, 14.0, 15.0]] (PASS)

### Data

In [4]:
processed_magnitude_data, feature_dataframes, csv_diagnostics, magnitude_summary = prepare_dl_data(
    DATA_DIR,
    calibration_mode=CALIBRATION_MODE,
    csv_options=CSV_PROCESSING_OPTIONS,
    preproc_opts=preproc_opts,
    feat_opts=feat_opts,
)
display(magnitude_summary.head())

Scenarios present: 1
Locations: 53 | Users: 6 | ESPs: 19
[Z-0 inventory]
  total Z-0 files found: 171
  Z-0 count per (user, trial):
    (user=01, trial=01): 19
    (user=01, trial=02): 19
    (user=02, trial=01): 19
    (user=03, trial=01): 19
    (user=03, trial=02): 19
    (user=04, trial=01): 19
    (user=05, trial=01): 19
    (user=05, trial=02): 19
    (user=06, trial=01): 19
  breakdown by user / esp / trial:
    user=01 esp=01 trial=01: 1
    user=01 esp=01 trial=02: 1
    user=01 esp=02 trial=01: 1
    user=01 esp=02 trial=02: 1
    user=01 esp=03 trial=01: 1
    user=01 esp=03 trial=02: 1
    user=01 esp=04 trial=01: 1
    user=01 esp=04 trial=02: 1
    user=01 esp=05 trial=01: 1
    user=01 esp=05 trial=02: 1
    user=01 esp=07 trial=01: 1
    user=01 esp=07 trial=02: 1
    user=01 esp=08 trial=01: 1
    user=01 esp=08 trial=02: 1
    user=01 esp=09 trial=01: 1
    user=01 esp=09 trial=02: 1
    user=01 esp=10 trial=01: 1
    user=01 esp=10 trial=02: 1
    user=01 esp=11 trial=01: 1
    user=01 esp=11 trial=02: 1
    user=01 esp=12 trial=01: 1
    user=01 esp=12 trial=02: 1
    user=01 esp=13 trial=01: 1
    user=01 esp=13 trial=02: 1
    user=01 esp=14 trial=01: 1
    user=01 esp=14 trial=02: 1
    user=01 esp=15 trial=01: 1
    user=01 esp=15 trial=02: 1
    user=01 esp=16 trial=01: 1
    user=01 esp=16 trial=02: 1
    user=01 esp=17 trial=01: 1
    user=01 esp=17 trial=02: 1
    user=01 esp=18 trial=01: 1
    user=01 esp=18 trial=02: 1
    user=01 esp=19 trial=01: 1
    user=01 esp=19 trial=02: 1
    user=01 esp=20 trial=01: 1
    user=01 esp=20 trial=02: 1
    user=02 esp=01 trial=01: 1
    user=02 esp=02 trial=01: 1
    user=02 esp=03 trial=01: 1
    user=02 esp=04 trial=01: 1
    user=02 esp=05 trial=01: 1
    user=02 esp=07 trial=01: 1
    user=02 esp=08 trial=01: 1
    user=02 esp=09 trial=01: 1
    user=02 esp=10 trial=01: 1
    user=02 esp=11 trial=01: 1
    user=02 esp=12 trial=01: 1
    user=02 esp=13 trial=01: 1
    user=02 esp=14 trial=01: 1
    user=02 esp=15 trial=01: 1
    user=02 esp=16 trial=01: 1
    user=02 esp=17 trial=01: 1
    user=02 esp=18 trial=01: 1
    user=02 esp=19 trial=01: 1
    user=02 esp=20 trial=01: 1
    user=03 esp=01 trial=01: 1
    user=03 esp=01 trial=02: 1
    user=03 esp=02 trial=01: 1
    user=03 esp=02 trial=02: 1
    user=03 esp=03 trial=01: 1
    user=03 esp=03 trial=02: 1
    user=03 esp=04 trial=01: 1
    user=03 esp=04 trial=02: 1
    user=03 esp=05 trial=01: 1
    user=03 esp=05 trial=02: 1
    user=03 esp=07 trial=01: 1
    user=03 esp=07 trial=02: 1
    user=03 esp=08 trial=01: 1
    user=03 esp=08 trial=02: 1
    user=03 esp=09 trial=01: 1
    user=03 esp=09 trial=02: 1
    user=03 esp=10 trial=01: 1
    user=03 esp=10 trial=02: 1
    user=03 esp=11 trial=01: 1
    user=03 esp=11 trial=02: 1
    user=03 esp=12 trial=01: 1
    user=03 esp=12 trial=02: 1
    user=03 esp=13 trial=01: 1
    user=03 esp=13 trial=02: 1
    user=03 esp=14 trial=01: 1
    user=03 esp=14 trial=02: 1
    user=03 esp=15 trial=01: 1
    user=03 esp=15 trial=02: 1
    user=03 esp=16 trial=01: 1
    user=03 esp=16 trial=02: 1
    user=03 esp=17 trial=01: 1
    user=03 esp=17 trial=02: 1
    user=03 esp=18 trial=01: 1
    user=03 esp=18 trial=02: 1
    user=03 esp=19 trial=01: 1
    user=03 esp=19 trial=02: 1
    user=03 esp=20 trial=01: 1
    user=03 esp=20 trial=02: 1
    user=04 esp=01 trial=01: 1
    user=04 esp=02 trial=01: 1
    user=04 esp=03 trial=01: 1
    user=04 esp=04 trial=01: 1
    user=04 esp=05 trial=01: 1
    user=04 esp=07 trial=01: 1
    user=04 esp=08 trial=01: 1
    user=04 esp=09 trial=01: 1
    user=04 esp=10 trial=01: 1
    user=04 esp=11 trial=01: 1
    user=04 esp=12 trial=01: 1
    user=04 esp=13 trial=01: 1
    user=04 esp=14 trial=01: 1
    user=04 esp=15 trial=01: 1
    user=04 esp=16 trial=01: 1
    user=04 esp=17 trial=01: 1
    user=04 esp=18 trial=01: 1
    user=04 esp=19 trial=01: 1
    user=04 esp=20 trial=01: 1
    user=05 esp=01 trial=01: 1
    user=05 esp=01 trial=02: 1
    user=05 esp=02 trial=01: 1
    user=05 esp=02 trial=02: 1
    user=05 esp=03 trial=01: 1
    user=05 esp=03 trial=02: 1
    user=05 esp=04 trial=01: 1
    user=05 esp=04 trial=02: 1
    user=05 esp=05 trial=01: 1
    user=05 esp=05 trial=02: 1
    user=05 esp=07 trial=01: 1
    user=05 esp=07 trial=02: 1
    user=05 esp=08 trial=01: 1
    user=05 esp=08 trial=02: 1
    user=05 esp=09 trial=01: 1
    user=05 esp=09 trial=02: 1
    user=05 esp=10 trial=01: 1
    user=05 esp=10 trial=02: 1
    user=05 esp=11 trial=01: 1
    user=05 esp=11 trial=02: 1
    user=05 esp=12 trial=01: 1
    user=05 esp=12 trial=02: 1
    user=05 esp=13 trial=01: 1
    user=05 esp=13 trial=02: 1
    user=05 esp=14 trial=01: 1
    user=05 esp=14 trial=02: 1
    user=05 esp=15 trial=01: 1
    user=05 esp=15 trial=02: 1
    user=05 esp=16 trial=01: 1
    user=05 esp=16 trial=02: 1
    user=05 esp=17 trial=01: 1
    user=05 esp=17 trial=02: 1
    user=05 esp=18 trial=01: 1
    user=05 esp=18 trial=02: 1
    user=05 esp=19 trial=01: 1
    user=05 esp=19 trial=02: 1
    user=05 esp=20 trial=01: 1
    user=05 esp=20 trial=02: 1
    user=06 esp=01 trial=01: 1
    user=06 esp=02 trial=01: 1
    user=06 esp=03 trial=01: 1
    user=06 esp=04 trial=01: 1
    user=06 esp=05 trial=01: 1
    user=06 esp=07 trial=01: 1
    user=06 esp=08 trial=01: 1
    user=06 esp=09 trial=01: 1
    user=06 esp=10 trial=01: 1
    user=06 esp=11 trial=01: 1
    user=06 esp=12 trial=01: 1
    user=06 esp=13 trial=01: 1
    user=06 esp=14 trial=01: 1
    user=06 esp=15 trial=01: 1
    user=06 esp=16 trial=01: 1
    user=06 esp=17 trial=01: 1
    user=06 esp=18 trial=01: 1
    user=06 esp=19 trial=01: 1
    user=06 esp=20 trial=01: 1
  baseline coverage for occupied recordings:
    user=01 trial=01 esp=01: yes
    user=01 trial=01 esp=02: yes
    user=01 trial=01 esp=03: yes
    user=01 trial=01 esp=04: yes
    user=01 trial=01 esp=05: yes
    user=01 trial=01 esp=07: yes
    user=01 trial=01 esp=08: yes
    user=01 trial=01 esp=09: yes
    user=01 trial=01 esp=10: yes
    user=01 trial=01 esp=11: yes
    user=01 trial=01 esp=12: yes
    user=01 trial=01 esp=13: yes
    user=01 trial=01 esp=14: yes
    user=01 trial=01 esp=15: yes
    user=01 trial=01 esp=16: yes
    user=01 trial=01 esp=17: yes
    user=01 trial=01 esp=18: yes
    user=01 trial=01 esp=19: yes
    user=01 trial=01 esp=20: yes
    user=01 trial=02 esp=01: yes
    user=01 trial=02 esp=02: yes
    user=01 trial=02 esp=03: yes
    user=01 trial=02 esp=04: yes
    user=01 trial=02 esp=05: yes
    user=01 trial=02 esp=07: yes
    user=01 trial=02 esp=08: yes
    user=01 trial=02 esp=09: yes
    user=01 trial=02 esp=10: yes
    user=01 trial=02 esp=11: yes
    user=01 trial=02 esp=12: yes
    user=01 trial=02 esp=13: yes
    user=01 trial=02 esp=14: yes
    user=01 trial=02 esp=15: yes
    user=01 trial=02 esp=16: yes
    user=01 trial=02 esp=17: yes
    user=01 trial=02 esp=18: yes
    user=01 trial=02 esp=19: yes
    user=01 trial=02 esp=20: yes
    user=02 trial=01 esp=01: yes
    user=02 trial=01 esp=02: yes
    user=02 trial=01 esp=03: yes
    user=02 trial=01 esp=04: yes
    user=02 trial=01 esp=05: yes
    user=02 trial=01 esp=07: yes
    user=02 trial=01 esp=08: yes
    user=02 trial=01 esp=09: yes
    user=02 trial=01 esp=10: yes
    user=02 trial=01 esp=11: yes
    user=02 trial=01 esp=12: yes
    user=02 trial=01 esp=13: yes
    user=02 trial=01 esp=14: yes
    user=02 trial=01 esp=15: yes
    user=02 trial=01 esp=16: yes
    user=02 trial=01 esp=17: yes
    user=02 trial=01 esp=18: yes
    user=02 trial=01 esp=19: yes
    user=02 trial=01 esp=20: yes
    user=03 trial=01 esp=01: yes
    user=03 trial=01 esp=02: yes
    user=03 trial=01 esp=03: yes
    user=03 trial=01 esp=04: yes
    user=03 trial=01 esp=05: yes
    user=03 trial=01 esp=07: yes
    user=03 trial=01 esp=08: yes
    user=03 trial=01 esp=09: yes
    user=03 trial=01 esp=10: yes
    user=03 trial=01 esp=11: yes
    user=03 trial=01 esp=12: yes
    user=03 trial=01 esp=13: yes
    user=03 trial=01 esp=14: yes
    user=03 trial=01 esp=15: yes
    user=03 trial=01 esp=16: yes
    user=03 trial=01 esp=17: yes
    user=03 trial=01 esp=18: yes
    user=03 trial=01 esp=19: yes
    user=03 trial=01 esp=20: yes
    user=03 trial=02 esp=01: yes
    user=03 trial=02 esp=02: yes
    user=03 trial=02 esp=03: yes
    user=03 trial=02 esp=04: yes
    user=03 trial=02 esp=05: yes
    user=03 trial=02 esp=07: yes
    user=03 trial=02 esp=08: yes
    user=03 trial=02 esp=09: yes
    user=03 trial=02 esp=10: yes
    user=03 trial=02 esp=11: yes
    user=03 trial=02 esp=12: yes
    user=03 trial=02 esp=13: yes
    user=03 trial=02 esp=14: yes
    user=03 trial=02 esp=15: yes
    user=03 trial=02 esp=16: yes
    user=03 trial=02 esp=17: yes
    user=03 trial=02 esp=18: yes
    user=03 trial=02 esp=19: yes
    user=03 trial=02 esp=20: yes
    user=04 trial=01 esp=01: yes
    user=04 trial=01 esp=02: yes
    user=04 trial=01 esp=03: yes
    user=04 trial=01 esp=04: yes
    user=04 trial=01 esp=05: yes
    user=04 trial=01 esp=07: yes
    user=04 trial=01 esp=08: yes
    user=04 trial=01 esp=09: yes
    user=04 trial=01 esp=10: yes
    user=04 trial=01 esp=11: yes
    user=04 trial=01 esp=12: yes
    user=04 trial=01 esp=13: yes
    user=04 trial=01 esp=14: yes
    user=04 trial=01 esp=15: yes
    user=04 trial=01 esp=16: yes
    user=04 trial=01 esp=17: yes
    user=04 trial=01 esp=18: yes
    user=04 trial=01 esp=19: yes
    user=04 trial=01 esp=20: yes
    user=05 trial=01 esp=01: yes
    user=05 trial=01 esp=02: yes
    user=05 trial=01 esp=03: yes
    user=05 trial=01 esp=04: yes
    user=05 trial=01 esp=05: yes
    user=05 trial=01 esp=07: yes
    user=05 trial=01 esp=08: yes
    user=05 trial=01 esp=09: yes
    user=05 trial=01 esp=10: yes
    user=05 trial=01 esp=11: yes
    user=05 trial=01 esp=12: yes
    user=05 trial=01 esp=13: yes
    user=05 trial=01 esp=14: yes
    user=05 trial=01 esp=15: yes
    user=05 trial=01 esp=16: yes
    user=05 trial=01 esp=17: yes
    user=05 trial=01 esp=18: yes
    user=05 trial=01 esp=19: yes
    user=05 trial=01 esp=20: yes
    user=05 trial=02 esp=01: yes
    user=05 trial=02 esp=02: yes
    user=05 trial=02 esp=03: yes
    user=05 trial=02 esp=04: yes
    user=05 trial=02 esp=05: yes
    user=05 trial=02 esp=07: yes
    user=05 trial=02 esp=08: yes
    user=05 trial=02 esp=09: yes
    user=05 trial=02 esp=10: yes
    user=05 trial=02 esp=11: yes
    user=05 trial=02 esp=12: yes
    user=05 trial=02 esp=13: yes
    user=05 trial=02 esp=14: yes
    user=05 trial=02 esp=15: yes
    user=05 trial=02 esp=16: yes
    user=05 trial=02 esp=17: yes
    user=05 trial=02 esp=18: yes
    user=05 trial=02 esp=19: yes
    user=05 trial=02 esp=20: yes
    user=06 trial=01 esp=01: yes
    user=06 trial=01 esp=02: yes
    user=06 trial=01 esp=03: yes
    user=06 trial=01 esp=04: yes
    user=06 trial=01 esp=05: yes
    user=06 trial=01 esp=07: yes
    user=06 trial=01 esp=08: yes
    user=06 trial=01 esp=09: yes
    user=06 trial=01 esp=10: yes
    user=06 trial=01 esp=11: yes
    user=06 trial=01 esp=12: yes
    user=06 trial=01 esp=13: yes
    user=06 trial=01 esp=14: yes
    user=06 trial=01 esp=15: yes
    user=06 trial=01 esp=16: yes
    user=06 trial=01 esp=17: yes
    user=06 trial=01 esp=18: yes
    user=06 trial=01 esp=19: yes
    user=06 trial=01 esp=20: yes
  per_session scope fully satisfiable: yes
  deep-fade clipped subcarriers:
    user=01 trial=01 esp=01: 1
    user=01 trial=01 esp=02: 1
    user=01 trial=01 esp=03: 1
    user=01 trial=01 esp=04: 1
    user=01 trial=01 esp=05: 1
    user=01 trial=01 esp=07: 1
    user=01 trial=01 esp=08: 1
    user=01 trial=01 esp=09: 1
    user=01 trial=01 esp=10: 0
    user=01 trial=01 esp=11: 1
    user=01 trial=01 esp=12: 1
    user=01 trial=01 esp=13: 1
    user=01 trial=01 esp=14: 1
    user=01 trial=01 esp=15: 1
    user=01 trial=01 esp=16: 1
    user=01 trial=01 esp=17: 1
    user=01 trial=01 esp=18: 1
    user=01 trial=01 esp=19: 1
    user=01 trial=01 esp=20: 1
    user=01 trial=02 esp=01: 1
    user=01 trial=02 esp=02: 1
    user=01 trial=02 esp=03: 1
    user=01 trial=02 esp=04: 1
    user=01 trial=02 esp=05: 1
    user=01 trial=02 esp=07: 1
    user=01 trial=02 esp=08: 1
    user=01 trial=02 esp=09: 1
    user=01 trial=02 esp=10: 1
    user=01 trial=02 esp=11: 1
    user=01 trial=02 esp=12: 1
    user=01 trial=02 esp=13: 1
    user=01 trial=02 esp=14: 1
    user=01 trial=02 esp=15: 1
    user=01 trial=02 esp=16: 1
    user=01 trial=02 esp=17: 1
    user=01 trial=02 esp=18: 1
    user=01 trial=02 esp=19: 1
    user=01 trial=02 esp=20: 1
    user=02 trial=01 esp=01: 1
    user=02 trial=01 esp=02: 1
    user=02 trial=01 esp=03: 1
    user=02 trial=01 esp=04: 1
    user=02 trial=01 esp=05: 1
    user=02 trial=01 esp=07: 1
    user=02 trial=01 esp=08: 1
    user=02 trial=01 esp=09: 1
    user=02 trial=01 esp=10: 0
    user=02 trial=01 esp=11: 1
    user=02 trial=01 esp=12: 1
    user=02 trial=01 esp=13: 1
    user=02 trial=01 esp=14: 1
    user=02 trial=01 esp=15: 1
    user=02 trial=01 esp=16: 1
    user=02 trial=01 esp=17: 1
    user=02 trial=01 esp=18: 1
    user=02 trial=01 esp=19: 1
    user=02 trial=01 esp=20: 1
    user=03 trial=01 esp=01: 1
    user=03 trial=01 esp=02: 1
    user=03 trial=01 esp=03: 1
    user=03 trial=01 esp=04: 1
    user=03 trial=01 esp=05: 1
    user=03 trial=01 esp=07: 0
    user=03 trial=01 esp=08: 1
    user=03 trial=01 esp=09: 1
    user=03 trial=01 esp=10: 1
    user=03 trial=01 esp=11: 1
    user=03 trial=01 esp=12: 1
    user=03 trial=01 esp=13: 1
    user=03 trial=01 esp=14: 1
    user=03 trial=01 esp=15: 1
    user=03 trial=01 esp=16: 1
    user=03 trial=01 esp=17: 1
    user=03 trial=01 esp=18: 1
    user=03 trial=01 esp=19: 1
    user=03 trial=01 esp=20: 1
    user=03 trial=02 esp=01: 1
    user=03 trial=02 esp=02: 1
    user=03 trial=02 esp=03: 1
    user=03 trial=02 esp=04: 1
    user=03 trial=02 esp=05: 1
    user=03 trial=02 esp=07: 1
    user=03 trial=02 esp=08: 1
    user=03 trial=02 esp=09: 0
    user=03 trial=02 esp=10: 0
    user=03 trial=02 esp=11: 1
    user=03 trial=02 esp=12: 1
    user=03 trial=02 esp=13: 1
    user=03 trial=02 esp=14: 1
    user=03 trial=02 esp=15: 1
    user=03 trial=02 esp=16: 1
    user=03 trial=02 esp=17: 1
    user=03 trial=02 esp=18: 1
    user=03 trial=02 esp=19: 1
    user=03 trial=02 esp=20: 1
    user=04 trial=01 esp=01: 1
    user=04 trial=01 esp=02: 1
    user=04 trial=01 esp=03: 1
    user=04 trial=01 esp=04: 1
    user=04 trial=01 esp=05: 1
    user=04 trial=01 esp=07: 1
    user=04 trial=01 esp=08: 1
    user=04 trial=01 esp=09: 1
    user=04 trial=01 esp=10: 1
    user=04 trial=01 esp=11: 1
    user=04 trial=01 esp=12: 1
    user=04 trial=01 esp=13: 1
    user=04 trial=01 esp=14: 1
    user=04 trial=01 esp=15: 1
    user=04 trial=01 esp=16: 1
    user=04 trial=01 esp=17: 1
    user=04 trial=01 esp=18: 1
    user=04 trial=01 esp=19: 1
    user=04 trial=01 esp=20: 1
    user=05 trial=01 esp=01: 1
    user=05 trial=01 esp=02: 1
    user=05 trial=01 esp=03: 0
    user=05 trial=01 esp=04: 1
    user=05 trial=01 esp=05: 1
    user=05 trial=01 esp=07: 1
    user=05 trial=01 esp=08: 1
    user=05 trial=01 esp=09: 1
    user=05 trial=01 esp=10: 0
    user=05 trial=01 esp=11: 1
    user=05 trial=01 esp=12: 1
    user=05 trial=01 esp=13: 1
    user=05 trial=01 esp=14: 1
    user=05 trial=01 esp=15: 1
    user=05 trial=01 esp=16: 1
    user=05 trial=01 esp=17: 1
    user=05 trial=01 esp=18: 1
    user=05 trial=01 esp=19: 1
    user=05 trial=01 esp=20: 1
    user=05 trial=02 esp=01: 1
    user=05 trial=02 esp=02: 1
    user=05 trial=02 esp=03: 1
    user=05 trial=02 esp=04: 1
    user=05 trial=02 esp=05: 1
    user=05 trial=02 esp=07: 1
    user=05 trial=02 esp=08: 1
    user=05 trial=02 esp=09: 1
    user=05 trial=02 esp=10: 1
    user=05 trial=02 esp=11: 1
    user=05 trial=02 esp=12: 1
    user=05 trial=02 esp=13: 1
    user=05 trial=02 esp=14: 1
    user=05 trial=02 esp=15: 0
    user=05 trial=02 esp=16: 0
    user=05 trial=02 esp=17: 1
    user=05 trial=02 esp=18: 1
    user=05 trial=02 esp=19: 0
    user=05 trial=02 esp=20: 1
    user=06 trial=01 esp=01: 1
    user=06 trial=01 esp=02: 1
    user=06 trial=01 esp=03: 1
    user=06 trial=01 esp=04: 1
    user=06 trial=01 esp=05: 1
    user=06 trial=01 esp=07: 1
    user=06 trial=01 esp=08: 1
    user=06 trial=01 esp=09: 1
    user=06 trial=01 esp=10: 1
    user=06 trial=01 esp=11: 1
    user=06 trial=01 esp=12: 1
    user=06 trial=01 esp=13: 1
    user=06 trial=01 esp=14: 1
    user=06 trial=01 esp=15: 1
    user=06 trial=01 esp=16: 1
    user=06 trial=01 esp=17: 1
    user=06 trial=01 esp=18: 1
    user=06 trial=01 esp=19: 1
    user=06 trial=01 esp=20: 1
[cache hit] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/.cache/dataframes/preproc=norm-empty_baseline_scope-per_session/feat=win60-step0/2_4ghz.parquet
[cache hit] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/.cache/dataframes/preproc=norm-empty_baseline_scope-per_session/feat=win60-step0/5ghz.parquet
[cache hit] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/.cache/dataframes/preproc=norm-empty_baseline_scope-per_session/feat=win60-step0/fusion.parquet

,scenario,location,user,esp,trial,samples,subcarriers,normalization,baseline_scope
0,1,C-1,06,16,01,2088,56,empty_baseline,per_session
1,1,C-1,06,15,01,1942,56,empty_baseline,per_session
2,1,C-1,06,09,01,1689,50,empty_baseline,per_session
3,1,C-1,06,07,01,1965,50,empty_baseline,per_session
4,1,C-1,06,04,01,1913,50,empty_baseline,per_session

In [5]:
for band in BANDS_TO_RUN:
    df = feature_dataframes[band]
    print(f"{band}: {df.shape[0]} windows, {df.shape[1]} columns")
    print(f"{band} dataframe hash: {pd.util.hash_pandas_object(df, index=True).sum()}")

2.4 GHz: 13588 windows, 2708 columns
2.4 GHz dataframe hash: 12830868654705884127
5 GHz: 14478 windows, 3368 columns
5 GHz dataframe hash: 5016803871464446121
Fusion: 13568 windows, 6068 columns
Fusion dataframe hash: 3976504561903335248

In [6]:
label_encoder = create_position_label_encoder(
    feature_dataframes,
    results_dir=results_dir,
    expected_classes=52,
)
print(label_encoder.classes_)

[CNN] label classes saved to /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/manifests/cnn_label_classes.json
['A-1' 'A-13' 'A-14' 'A-2' 'A-5' 'B-1' 'B-10' 'B-11' 'B-12' 'B-13' 'B-14'
 'B-2' 'B-5' 'B-8' 'C-1' 'C-10' 'C-11' 'C-14' 'C-2' 'C-3' 'C-4' 'C-5'
 'C-6' 'C-7' 'C-8' 'C-9' 'D-1' 'D-2' 'D-3' 'D-4' 'D-5' 'D-6' 'D-7' 'D-8'
 'E-1' 'E-10' 'E-11' 'E-12' 'E-13' 'E-2' 'E-3' 'E-4' 'E-5' 'E-6' 'E-7'
 'E-8' 'F-10' 'F-11' 'F-12' 'F-13' 'F-5' 'F-8']

### Train And Evaluate

In [7]:
cnn_runs = run_dl_experiments(
    processed_magnitude_data,
    feature_dataframes,
    bands=BANDS_TO_RUN,
    split_modes=SPLIT_MODES,
    label_encoder=label_encoder,
    device=DEVICE,
    results_dir=results_dir,
    plots_dir=plots_dir,
    params=CNN_PARAMS,
    preproc_opts=preproc_opts,
    feat_opts=feat_opts,
    expected_subcarriers=EXPECTED_SUBCARRIERS,
    expected_anchors=EXPECTED_ANCHORS,
    seeds=SEEDS,
    test_size=TEST_SIZE,
    random_state=RANDOM_STATE,
    n_blocks=BLOCK_COUNT,
    val_size=VALIDATION_SIZE,
    force_retrain=FORCE_RETRAIN,
)

=== 2.4 GHz ===
[window arrays] cache path: /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/.cache/dataframes/preproc=norm-empty_baseline_scope-per_session/feat=win60-step0/window_arrays/2_4ghz
[window arrays cache hit] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/.cache/dataframes/preproc=norm-empty_baseline_scope-per_session/feat=win60-step0/window_arrays/2_4ghz
[window arrays] 2.4 GHz: shape=(13588, 9, 50, 60), dtype=float16
[window arrays] 2.4 GHz anchors: ['esp_01', 'esp_02', 'esp_03', 'esp_04', 'esp_05', 'esp_07', 'esp_08', 'esp_09', 'esp_10']
2.4 GHz: anchors=9, subcarriers=50, windows=13588
WINDOW IDENTITY PASS: 2.4 GHz (13588 windows)
[trial filter] split=lovo trials=['01'] kept=8906/13588
[trial filter] split=lovo trials=['01'] kept=8906/8906
[protocol] split=lovo fold=01 trials_used=['01'] n_train=7336 n_test=1570 users=['01', '02', '03', '04', '05', '06'] train_users=['02', '03', '04', '05', '06'] test_users=['01']
[protocol] split=lovo fold=02 trials_used=['01'] n_train=7492 n_test=1414 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '03', '04', '05', '06'] test_users=['02']
[protocol] split=lovo fold=03 trials_used=['01'] n_train=7319 n_test=1587 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '04', '05', '06'] test_users=['03']
[protocol] split=lovo fold=04 trials_used=['01'] n_train=7346 n_test=1560 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '05', '06'] test_users=['04']
[protocol] split=lovo fold=05 trials_used=['01'] n_train=7420 n_test=1486 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '06'] test_users=['05']
[protocol] split=lovo fold=06 trials_used=['01'] n_train=7617 n_test=1289 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05'] test_users=['06']
[trial filter] split=lovo trials=['01'] kept=8906/13588
[trial filter] split=lovo trials=['01'] kept=8906/8906
[protocol] split=lovo fold=01 trials_used=['01'] n_train=7336 n_test=1570 users=['01', '02', '03', '04', '05', '06'] train_users=['02', '03', '04', '05', '06'] test_users=['01']
[protocol] split=lovo fold=02 trials_used=['01'] n_train=7492 n_test=1414 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '03', '04', '05', '06'] test_users=['02']
[protocol] split=lovo fold=03 trials_used=['01'] n_train=7319 n_test=1587 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '04', '05', '06'] test_users=['03']
[protocol] split=lovo fold=04 trials_used=['01'] n_train=7346 n_test=1560 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '05', '06'] test_users=['04']
[protocol] split=lovo fold=05 trials_used=['01'] n_train=7420 n_test=1486 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '06'] test_users=['05']
[protocol] split=lovo fold=06 trials_used=['01'] n_train=7617 n_test=1289 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05'] test_users=['06']
SPLIT IDENTITY PASS: 2.4 GHz/lovo fold=1 train=7336 test=1570
SPLIT IDENTITY PASS: 2.4 GHz/lovo fold=2 train=7492 test=1414
SPLIT IDENTITY PASS: 2.4 GHz/lovo fold=3 train=7319 test=1587
SPLIT IDENTITY PASS: 2.4 GHz/lovo fold=4 train=7346 test=1560
SPLIT IDENTITY PASS: 2.4 GHz/lovo fold=5 train=7420 test=1486
SPLIT IDENTITY PASS: 2.4 GHz/lovo fold=6 train=7617 test=1289
Seeds: random=42, numpy=42, torch=42
[trial filter] split=lovo trials=['01'] kept=8906/13588
[trial filter] split=lovo trials=['01'] kept=8906/8906
[protocol] split=lovo fold=01 trials_used=['01'] n_train=7336 n_test=1570 users=['01', '02', '03', '04', '05', '06'] train_users=['02', '03', '04', '05', '06'] test_users=['01']
[protocol] split=lovo fold=02 trials_used=['01'] n_train=7492 n_test=1414 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '03', '04', '05', '06'] test_users=['02']
[protocol] split=lovo fold=03 trials_used=['01'] n_train=7319 n_test=1587 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '04', '05', '06'] test_users=['03']
[protocol] split=lovo fold=04 trials_used=['01'] n_train=7346 n_test=1560 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '05', '06'] test_users=['04']
[protocol] split=lovo fold=05 trials_used=['01'] n_train=7420 n_test=1486 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '06'] test_users=['05']
[protocol] split=lovo fold=06 trials_used=['01'] n_train=7617 n_test=1289 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05'] test_users=['06']
[DL LOVO] held_out_user=01 validation_user=06 (entire user, deterministic rotation)
[CNN] 2.4 GHz/lovo fold=01 parameters=76020
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] 2.4 GHz/lovo fold=01 epoch 01/70: train_loss=3.8999 train_acc=0.0422 val_loss=3.9634 val_acc=0.0178 seconds=3.5
[CNN] 2.4 GHz/lovo fold=01 epoch 02/70: train_loss=3.6155 train_acc=0.0802 val_loss=4.0553 val_acc=0.0411 seconds=0.4
[CNN] 2.4 GHz/lovo fold=01 epoch 03/70: train_loss=3.2635 train_acc=0.1349 val_loss=4.1982 val_acc=0.0512 seconds=0.4
[CNN] 2.4 GHz/lovo fold=01 epoch 04/70: train_loss=3.0241 train_acc=0.1786 val_loss=4.4765 val_acc=0.0318 seconds=0.7
[CNN] 2.4 GHz/lovo fold=01 epoch 05/70: train_loss=2.8129 train_acc=0.2163 val_loss=4.3958 val_acc=0.0489 seconds=0.6
[CNN] 2.4 GHz/lovo fold=01 epoch 06/70: train_loss=2.6342 train_acc=0.2507 val_loss=4.2981 val_acc=0.0551 seconds=0.3
[CNN] 2.4 GHz/lovo fold=01 epoch 07/70: train_loss=2.4851 train_acc=0.2772 val_loss=4.6290 val_acc=0.0497 seconds=0.4
[CNN] 2.4 GHz/lovo fold=01 epoch 08/70: train_loss=2.3652 train_acc=0.3137 val_loss=4.9720 val_acc=0.0481 seconds=0.4
[CNN] 2.4 GHz/lovo fold=01 epoch 09/70: train_loss=2.2582 train_acc=0.3362 val_loss=5.5117 val_acc=0.0434 seconds=0.7
[CNN] 2.4 GHz/lovo fold=01 epoch 10/70: train_loss=2.1822 train_acc=0.3436 val_loss=4.7339 val_acc=0.0465 seconds=0.4
[CNN] 2.4 GHz/lovo fold=01 epoch 11/70: train_loss=2.0938 train_acc=0.3810 val_loss=5.4595 val_acc=0.0372 seconds=0.4
[CNN] 2.4 GHz/lovo fold=01 epoch 12/70: train_loss=2.0249 train_acc=0.3873 val_loss=5.4457 val_acc=0.0434 seconds=0.4
[CNN] 2.4 GHz/lovo fold=01 epoch 13/70: train_loss=1.9537 train_acc=0.4141 val_loss=5.4647 val_acc=0.0458 seconds=0.4
[CNN] 2.4 GHz/lovo fold=01 epoch 14/70: train_loss=1.8841 train_acc=0.4305 val_loss=5.8582 val_acc=0.0458 seconds=0.4
[CNN] 2.4 GHz/lovo fold=01 epoch 15/70: train_loss=1.8111 train_acc=0.4460 val_loss=5.7535 val_acc=0.0388 seconds=0.4
[CNN] 2.4 GHz/lovo fold=01 epoch 16/70: train_loss=1.7488 train_acc=0.4617 val_loss=6.2139 val_acc=0.0450 seconds=0.3
[CNN] 2.4 GHz/lovo fold=01 epoch 17/70: train_loss=1.7018 train_acc=0.4778 val_loss=6.4576 val_acc=0.0489 seconds=0.4
[CNN] 2.4 GHz/lovo fold=01 epoch 18/70: train_loss=1.6488 train_acc=0.4930 val_loss=6.6406 val_acc=0.0489 seconds=0.4
[CNN] 2.4 GHz/lovo fold=01 epoch 19/70: train_loss=1.5896 train_acc=0.5055 val_loss=6.3760 val_acc=0.0427 seconds=0.4
[CNN] 2.4 GHz/lovo fold=01 epoch 20/70: train_loss=1.5571 train_acc=0.5214 val_loss=7.1069 val_acc=0.0442 seconds=0.4
[CNN] 2.4 GHz/lovo fold=01 epoch 21/70: train_loss=1.5083 train_acc=0.5313 val_loss=7.2043 val_acc=0.0411 seconds=0.3
[CNN] early stopping at epoch 21; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__2_4ghz__lovo__ebl-session__s42__9b1404__fold-01.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__2_4ghz__lovo__ebl-session__s42__9b1404/training_curves__fold-01.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=02 validation_user=01 (entire user, deterministic rotation)
[CNN] 2.4 GHz/lovo fold=02 parameters=76020
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] 2.4 GHz/lovo fold=02 epoch 01/70: train_loss=3.8880 train_acc=0.0535 val_loss=3.9155 val_acc=0.0223 seconds=2.6
[CNN] 2.4 GHz/lovo fold=02 epoch 02/70: train_loss=3.5602 train_acc=0.0861 val_loss=3.7389 val_acc=0.0484 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 03/70: train_loss=3.2209 train_acc=0.1364 val_loss=4.1177 val_acc=0.0357 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 04/70: train_loss=2.9337 train_acc=0.1778 val_loss=4.4964 val_acc=0.0242 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 05/70: train_loss=2.7045 train_acc=0.2214 val_loss=4.6512 val_acc=0.0490 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 06/70: train_loss=2.5274 train_acc=0.2617 val_loss=4.7945 val_acc=0.0503 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 07/70: train_loss=2.3640 train_acc=0.3114 val_loss=5.0213 val_acc=0.0439 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 08/70: train_loss=2.2572 train_acc=0.3276 val_loss=5.2350 val_acc=0.0452 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 09/70: train_loss=2.1374 train_acc=0.3571 val_loss=5.3781 val_acc=0.0459 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 10/70: train_loss=2.0609 train_acc=0.3828 val_loss=5.9711 val_acc=0.0459 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 11/70: train_loss=1.9928 train_acc=0.3961 val_loss=6.0269 val_acc=0.0548 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 12/70: train_loss=1.9121 train_acc=0.4176 val_loss=6.2158 val_acc=0.0484 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 13/70: train_loss=1.8642 train_acc=0.4323 val_loss=6.0348 val_acc=0.0439 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 14/70: train_loss=1.7747 train_acc=0.4586 val_loss=5.8972 val_acc=0.0427 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 15/70: train_loss=1.7311 train_acc=0.4704 val_loss=5.8134 val_acc=0.0490 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 16/70: train_loss=1.6637 train_acc=0.4894 val_loss=6.0840 val_acc=0.0446 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 17/70: train_loss=1.6667 train_acc=0.4865 val_loss=7.0222 val_acc=0.0306 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 18/70: train_loss=1.5857 train_acc=0.5076 val_loss=8.5868 val_acc=0.0414 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 19/70: train_loss=1.5591 train_acc=0.5245 val_loss=6.7531 val_acc=0.0433 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 20/70: train_loss=1.5048 train_acc=0.5468 val_loss=7.3468 val_acc=0.0389 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 21/70: train_loss=1.4353 train_acc=0.5513 val_loss=7.2943 val_acc=0.0516 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 22/70: train_loss=1.4003 train_acc=0.5696 val_loss=7.2911 val_acc=0.0484 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 23/70: train_loss=1.3714 train_acc=0.5805 val_loss=7.1620 val_acc=0.0452 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 24/70: train_loss=1.3317 train_acc=0.5890 val_loss=8.4128 val_acc=0.0363 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 25/70: train_loss=1.2979 train_acc=0.6005 val_loss=7.0011 val_acc=0.0605 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 26/70: train_loss=1.2793 train_acc=0.6071 val_loss=8.1330 val_acc=0.0433 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 27/70: train_loss=1.2338 train_acc=0.6180 val_loss=7.2288 val_acc=0.0541 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 28/70: train_loss=1.2174 train_acc=0.6202 val_loss=8.7227 val_acc=0.0643 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 29/70: train_loss=1.1641 train_acc=0.6369 val_loss=7.6927 val_acc=0.0522 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 30/70: train_loss=1.1637 train_acc=0.6425 val_loss=7.4618 val_acc=0.0541 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 31/70: train_loss=1.1396 train_acc=0.6434 val_loss=7.8376 val_acc=0.0510 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 32/70: train_loss=1.1120 train_acc=0.6513 val_loss=8.3959 val_acc=0.0643 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 33/70: train_loss=1.0864 train_acc=0.6672 val_loss=8.3892 val_acc=0.0662 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 34/70: train_loss=1.1135 train_acc=0.6511 val_loss=8.5142 val_acc=0.0382 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 35/70: train_loss=1.0535 train_acc=0.6751 val_loss=9.3758 val_acc=0.0363 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 36/70: train_loss=1.0164 train_acc=0.6868 val_loss=8.3685 val_acc=0.0567 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 37/70: train_loss=0.9956 train_acc=0.6935 val_loss=8.1205 val_acc=0.0535 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 38/70: train_loss=0.9736 train_acc=0.7018 val_loss=8.7473 val_acc=0.0471 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 39/70: train_loss=0.9586 train_acc=0.7009 val_loss=9.3050 val_acc=0.0490 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 40/70: train_loss=0.9718 train_acc=0.6935 val_loss=9.6077 val_acc=0.0325 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 41/70: train_loss=0.9455 train_acc=0.7099 val_loss=9.2302 val_acc=0.0471 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 42/70: train_loss=0.9037 train_acc=0.7183 val_loss=9.5288 val_acc=0.0433 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 43/70: train_loss=0.8751 train_acc=0.7263 val_loss=9.4179 val_acc=0.0554 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 44/70: train_loss=0.9208 train_acc=0.7084 val_loss=11.1924 val_acc=0.0459 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 45/70: train_loss=0.9168 train_acc=0.7106 val_loss=8.3793 val_acc=0.0522 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 46/70: train_loss=0.8590 train_acc=0.7302 val_loss=10.0680 val_acc=0.0242 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 47/70: train_loss=0.8361 train_acc=0.7344 val_loss=9.4617 val_acc=0.0395 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 48/70: train_loss=0.8131 train_acc=0.7501 val_loss=10.2264 val_acc=0.0529 seconds=0.4
[CNN] early stopping at epoch 48; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__2_4ghz__lovo__ebl-session__s42__9b1404__fold-02.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__2_4ghz__lovo__ebl-session__s42__9b1404/training_curves__fold-02.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=03 validation_user=02 (entire user, deterministic rotation)
[CNN] 2.4 GHz/lovo fold=03 parameters=76020
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] 2.4 GHz/lovo fold=03 epoch 01/70: train_loss=3.8724 train_acc=0.0515 val_loss=3.9557 val_acc=0.0141 seconds=2.9
[CNN] 2.4 GHz/lovo fold=03 epoch 02/70: train_loss=3.5184 train_acc=0.0920 val_loss=4.1504 val_acc=0.0233 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 03/70: train_loss=3.1747 train_acc=0.1260 val_loss=4.4959 val_acc=0.0417 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 04/70: train_loss=2.9515 train_acc=0.1746 val_loss=4.5267 val_acc=0.0177 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 05/70: train_loss=2.7574 train_acc=0.2157 val_loss=4.6599 val_acc=0.0212 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 06/70: train_loss=2.5848 train_acc=0.2483 val_loss=4.9356 val_acc=0.0248 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 07/70: train_loss=2.4672 train_acc=0.2815 val_loss=4.9311 val_acc=0.0205 seconds=0.3
[CNN] 2.4 GHz/lovo fold=03 epoch 08/70: train_loss=2.3128 train_acc=0.3238 val_loss=5.2443 val_acc=0.0276 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 09/70: train_loss=2.2156 train_acc=0.3519 val_loss=5.4079 val_acc=0.0269 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 10/70: train_loss=2.1105 train_acc=0.3649 val_loss=5.8102 val_acc=0.0354 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 11/70: train_loss=2.0186 train_acc=0.3992 val_loss=6.0186 val_acc=0.0276 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 12/70: train_loss=1.9787 train_acc=0.4080 val_loss=5.9979 val_acc=0.0255 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 13/70: train_loss=1.8924 train_acc=0.4366 val_loss=5.8590 val_acc=0.0325 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 14/70: train_loss=1.8198 train_acc=0.4493 val_loss=6.0244 val_acc=0.0311 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 15/70: train_loss=1.7189 train_acc=0.4870 val_loss=6.2797 val_acc=0.0311 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 16/70: train_loss=1.6998 train_acc=0.4837 val_loss=6.2714 val_acc=0.0403 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 17/70: train_loss=1.6918 train_acc=0.4870 val_loss=6.7187 val_acc=0.0255 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 18/70: train_loss=1.5905 train_acc=0.5189 val_loss=6.2497 val_acc=0.0467 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 19/70: train_loss=1.5577 train_acc=0.5257 val_loss=6.1737 val_acc=0.0474 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 20/70: train_loss=1.5203 train_acc=0.5373 val_loss=6.3653 val_acc=0.0467 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 21/70: train_loss=1.5153 train_acc=0.5402 val_loss=6.8715 val_acc=0.0311 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 22/70: train_loss=1.4139 train_acc=0.5665 val_loss=7.0518 val_acc=0.0311 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 23/70: train_loss=1.4877 train_acc=0.5441 val_loss=6.7907 val_acc=0.0354 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 24/70: train_loss=1.3591 train_acc=0.5856 val_loss=7.3406 val_acc=0.0276 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 25/70: train_loss=1.3575 train_acc=0.5846 val_loss=7.2640 val_acc=0.0347 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 26/70: train_loss=1.2893 train_acc=0.6052 val_loss=6.7954 val_acc=0.0495 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 27/70: train_loss=1.2682 train_acc=0.6107 val_loss=7.1162 val_acc=0.0332 seconds=0.3
[CNN] 2.4 GHz/lovo fold=03 epoch 28/70: train_loss=1.2422 train_acc=0.6239 val_loss=7.3407 val_acc=0.0424 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 29/70: train_loss=1.2744 train_acc=0.6139 val_loss=7.0055 val_acc=0.0417 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 30/70: train_loss=1.1914 train_acc=0.6323 val_loss=7.2257 val_acc=0.0417 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 31/70: train_loss=1.1746 train_acc=0.6408 val_loss=7.2684 val_acc=0.0495 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 32/70: train_loss=1.1398 train_acc=0.6525 val_loss=7.9627 val_acc=0.0375 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 33/70: train_loss=1.1702 train_acc=0.6383 val_loss=7.5882 val_acc=0.0354 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 34/70: train_loss=1.0937 train_acc=0.6625 val_loss=7.3814 val_acc=0.0389 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 35/70: train_loss=1.0676 train_acc=0.6713 val_loss=7.9155 val_acc=0.0332 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 36/70: train_loss=1.0983 train_acc=0.6671 val_loss=8.5571 val_acc=0.0226 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 37/70: train_loss=1.0250 train_acc=0.6811 val_loss=7.2664 val_acc=0.0502 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 38/70: train_loss=1.0063 train_acc=0.6947 val_loss=8.1787 val_acc=0.0509 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 39/70: train_loss=1.0058 train_acc=0.6947 val_loss=7.8504 val_acc=0.0488 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 40/70: train_loss=1.0329 train_acc=0.6838 val_loss=8.1414 val_acc=0.0375 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 41/70: train_loss=0.9788 train_acc=0.7026 val_loss=7.7998 val_acc=0.0403 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 42/70: train_loss=0.9285 train_acc=0.7224 val_loss=8.4147 val_acc=0.0375 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 43/70: train_loss=0.9572 train_acc=0.7057 val_loss=8.3026 val_acc=0.0502 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 44/70: train_loss=0.8958 train_acc=0.7243 val_loss=8.1613 val_acc=0.0453 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 45/70: train_loss=0.8985 train_acc=0.7226 val_loss=8.9525 val_acc=0.0389 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 46/70: train_loss=0.8733 train_acc=0.7372 val_loss=8.5403 val_acc=0.0481 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 47/70: train_loss=0.8630 train_acc=0.7321 val_loss=8.2215 val_acc=0.0410 seconds=0.3
[CNN] 2.4 GHz/lovo fold=03 epoch 48/70: train_loss=0.9034 train_acc=0.7280 val_loss=8.6655 val_acc=0.0354 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 49/70: train_loss=0.8401 train_acc=0.7404 val_loss=8.5846 val_acc=0.0354 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 50/70: train_loss=0.8699 train_acc=0.7390 val_loss=8.9420 val_acc=0.0410 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 51/70: train_loss=0.8397 train_acc=0.7414 val_loss=8.5692 val_acc=0.0382 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 52/70: train_loss=0.7960 train_acc=0.7575 val_loss=9.0582 val_acc=0.0417 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 53/70: train_loss=0.7818 train_acc=0.7610 val_loss=8.6284 val_acc=0.0502 seconds=0.3
[CNN] early stopping at epoch 53; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__2_4ghz__lovo__ebl-session__s42__9b1404__fold-03.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__2_4ghz__lovo__ebl-session__s42__9b1404/training_curves__fold-03.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=04 validation_user=03 (entire user, deterministic rotation)
[CNN] 2.4 GHz/lovo fold=04 parameters=76020
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] 2.4 GHz/lovo fold=04 epoch 01/70: train_loss=3.8990 train_acc=0.0514 val_loss=3.9782 val_acc=0.0189 seconds=2.9
[CNN] 2.4 GHz/lovo fold=04 epoch 02/70: train_loss=3.6187 train_acc=0.0846 val_loss=4.2535 val_acc=0.0208 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 03/70: train_loss=3.2519 train_acc=0.1297 val_loss=5.6015 val_acc=0.0126 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 04/70: train_loss=2.9940 train_acc=0.1657 val_loss=5.0197 val_acc=0.0284 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 05/70: train_loss=2.7834 train_acc=0.2134 val_loss=5.3717 val_acc=0.0334 seconds=0.3
[CNN] 2.4 GHz/lovo fold=04 epoch 06/70: train_loss=2.6084 train_acc=0.2554 val_loss=5.2377 val_acc=0.0347 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 07/70: train_loss=2.4550 train_acc=0.2870 val_loss=5.6279 val_acc=0.0435 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 08/70: train_loss=2.3573 train_acc=0.3054 val_loss=7.2610 val_acc=0.0428 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 09/70: train_loss=2.2496 train_acc=0.3289 val_loss=5.7498 val_acc=0.0422 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 10/70: train_loss=2.1518 train_acc=0.3662 val_loss=7.0215 val_acc=0.0397 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 11/70: train_loss=2.0827 train_acc=0.3737 val_loss=7.0309 val_acc=0.0441 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 12/70: train_loss=1.9969 train_acc=0.4039 val_loss=6.7774 val_acc=0.0428 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 13/70: train_loss=1.9262 train_acc=0.4235 val_loss=7.7704 val_acc=0.0384 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 14/70: train_loss=1.8382 train_acc=0.4504 val_loss=7.1780 val_acc=0.0479 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 15/70: train_loss=1.7971 train_acc=0.4641 val_loss=7.6359 val_acc=0.0460 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 16/70: train_loss=1.7349 train_acc=0.4799 val_loss=7.7892 val_acc=0.0422 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 17/70: train_loss=1.6679 train_acc=0.4912 val_loss=8.0090 val_acc=0.0485 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 18/70: train_loss=1.6266 train_acc=0.5053 val_loss=7.5669 val_acc=0.0523 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 19/70: train_loss=1.5742 train_acc=0.5181 val_loss=8.0325 val_acc=0.0636 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 20/70: train_loss=1.5401 train_acc=0.5275 val_loss=8.4124 val_acc=0.0580 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 21/70: train_loss=1.4863 train_acc=0.5485 val_loss=9.8103 val_acc=0.0447 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 22/70: train_loss=1.4625 train_acc=0.5529 val_loss=10.5102 val_acc=0.0435 seconds=0.3
[CNN] 2.4 GHz/lovo fold=04 epoch 23/70: train_loss=1.4318 train_acc=0.5572 val_loss=8.8396 val_acc=0.0573 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 24/70: train_loss=1.3962 train_acc=0.5756 val_loss=9.1164 val_acc=0.0529 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 25/70: train_loss=1.3523 train_acc=0.5836 val_loss=10.5155 val_acc=0.0397 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 26/70: train_loss=1.3179 train_acc=0.5933 val_loss=11.9462 val_acc=0.0391 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 27/70: train_loss=1.2677 train_acc=0.6133 val_loss=10.1215 val_acc=0.0410 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 28/70: train_loss=1.2726 train_acc=0.6128 val_loss=11.1173 val_acc=0.0460 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 29/70: train_loss=1.2195 train_acc=0.6251 val_loss=11.8507 val_acc=0.0428 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 30/70: train_loss=1.1904 train_acc=0.6341 val_loss=10.0972 val_acc=0.0510 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 31/70: train_loss=1.1797 train_acc=0.6331 val_loss=11.7384 val_acc=0.0397 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 32/70: train_loss=1.1613 train_acc=0.6409 val_loss=9.5431 val_acc=0.0491 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 33/70: train_loss=1.1179 train_acc=0.6524 val_loss=11.5001 val_acc=0.0422 seconds=0.3
[CNN] 2.4 GHz/lovo fold=04 epoch 34/70: train_loss=1.0863 train_acc=0.6645 val_loss=12.5323 val_acc=0.0422 seconds=0.4
[CNN] early stopping at epoch 34; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__2_4ghz__lovo__ebl-session__s42__9b1404__fold-04.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__2_4ghz__lovo__ebl-session__s42__9b1404/training_curves__fold-04.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=05 validation_user=04 (entire user, deterministic rotation)
[CNN] 2.4 GHz/lovo fold=05 parameters=76020
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] 2.4 GHz/lovo fold=05 epoch 01/70: train_loss=3.9157 train_acc=0.0382 val_loss=3.9717 val_acc=0.0192 seconds=2.7
[CNN] 2.4 GHz/lovo fold=05 epoch 02/70: train_loss=3.6738 train_acc=0.0773 val_loss=4.2777 val_acc=0.0263 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 03/70: train_loss=3.3058 train_acc=0.1275 val_loss=4.5745 val_acc=0.0288 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 04/70: train_loss=3.0459 train_acc=0.1638 val_loss=4.0960 val_acc=0.0558 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 05/70: train_loss=2.8507 train_acc=0.2005 val_loss=4.4898 val_acc=0.0359 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 06/70: train_loss=2.6981 train_acc=0.2270 val_loss=4.7156 val_acc=0.0308 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 07/70: train_loss=2.5571 train_acc=0.2611 val_loss=4.8246 val_acc=0.0378 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 08/70: train_loss=2.4360 train_acc=0.2887 val_loss=4.4917 val_acc=0.0724 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 09/70: train_loss=2.3094 train_acc=0.3242 val_loss=4.8450 val_acc=0.0474 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 10/70: train_loss=2.2181 train_acc=0.3483 val_loss=5.7032 val_acc=0.0538 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 11/70: train_loss=2.1298 train_acc=0.3659 val_loss=5.6714 val_acc=0.0468 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 12/70: train_loss=2.0627 train_acc=0.3860 val_loss=6.1438 val_acc=0.0269 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 13/70: train_loss=1.9657 train_acc=0.4140 val_loss=5.5199 val_acc=0.0436 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 14/70: train_loss=1.9189 train_acc=0.4230 val_loss=5.5951 val_acc=0.0429 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 15/70: train_loss=1.8441 train_acc=0.4449 val_loss=5.2448 val_acc=0.0564 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 16/70: train_loss=1.7794 train_acc=0.4596 val_loss=5.3375 val_acc=0.0590 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 17/70: train_loss=1.7259 train_acc=0.4753 val_loss=5.6018 val_acc=0.0513 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 18/70: train_loss=1.6742 train_acc=0.4995 val_loss=6.2270 val_acc=0.0577 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 19/70: train_loss=1.6374 train_acc=0.5082 val_loss=6.3297 val_acc=0.0423 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 20/70: train_loss=1.5739 train_acc=0.5183 val_loss=6.5465 val_acc=0.0308 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 21/70: train_loss=1.5464 train_acc=0.5294 val_loss=6.4689 val_acc=0.0417 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 22/70: train_loss=1.4828 train_acc=0.5555 val_loss=7.0100 val_acc=0.0346 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 23/70: train_loss=1.4608 train_acc=0.5529 val_loss=6.3634 val_acc=0.0654 seconds=0.4
[CNN] early stopping at epoch 23; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__2_4ghz__lovo__ebl-session__s42__9b1404__fold-05.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__2_4ghz__lovo__ebl-session__s42__9b1404/training_curves__fold-05.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=06 validation_user=05 (entire user, deterministic rotation)
[CNN] 2.4 GHz/lovo fold=06 parameters=76020
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] 2.4 GHz/lovo fold=06 epoch 01/70: train_loss=3.9097 train_acc=0.0349 val_loss=3.9411 val_acc=0.0195 seconds=3.2
[CNN] 2.4 GHz/lovo fold=06 epoch 02/70: train_loss=3.6724 train_acc=0.0723 val_loss=3.7071 val_acc=0.0532 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 03/70: train_loss=3.3455 train_acc=0.1145 val_loss=3.6154 val_acc=0.0619 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 04/70: train_loss=3.1028 train_acc=0.1492 val_loss=3.8010 val_acc=0.0707 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 05/70: train_loss=2.9276 train_acc=0.1877 val_loss=4.0433 val_acc=0.0700 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 06/70: train_loss=2.7788 train_acc=0.2173 val_loss=4.1465 val_acc=0.0700 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 07/70: train_loss=2.6616 train_acc=0.2308 val_loss=4.2480 val_acc=0.0693 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 08/70: train_loss=2.5320 train_acc=0.2737 val_loss=4.5751 val_acc=0.0747 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 09/70: train_loss=2.4330 train_acc=0.2931 val_loss=4.8934 val_acc=0.0700 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 10/70: train_loss=2.3566 train_acc=0.3141 val_loss=4.8170 val_acc=0.0787 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 11/70: train_loss=2.2663 train_acc=0.3336 val_loss=4.7026 val_acc=0.0707 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 12/70: train_loss=2.1761 train_acc=0.3636 val_loss=4.9829 val_acc=0.0707 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 13/70: train_loss=2.1050 train_acc=0.3753 val_loss=5.1496 val_acc=0.0747 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 14/70: train_loss=2.0233 train_acc=0.3968 val_loss=5.3338 val_acc=0.0915 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 15/70: train_loss=1.9515 train_acc=0.4145 val_loss=5.6082 val_acc=0.0747 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 16/70: train_loss=1.8935 train_acc=0.4270 val_loss=6.0730 val_acc=0.0606 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 17/70: train_loss=1.8550 train_acc=0.4417 val_loss=5.7666 val_acc=0.0760 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 18/70: train_loss=1.7753 train_acc=0.4715 val_loss=5.7152 val_acc=0.0908 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 19/70: train_loss=1.7215 train_acc=0.4865 val_loss=5.6878 val_acc=0.0828 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 20/70: train_loss=1.6615 train_acc=0.4936 val_loss=6.0069 val_acc=0.0915 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 21/70: train_loss=1.6216 train_acc=0.5143 val_loss=6.5028 val_acc=0.0821 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 22/70: train_loss=1.5793 train_acc=0.5241 val_loss=6.1152 val_acc=0.0787 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 23/70: train_loss=1.5278 train_acc=0.5399 val_loss=6.2887 val_acc=0.0895 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 24/70: train_loss=1.5293 train_acc=0.5400 val_loss=6.3492 val_acc=0.1036 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 25/70: train_loss=1.4708 train_acc=0.5523 val_loss=6.7732 val_acc=0.0606 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 26/70: train_loss=1.4321 train_acc=0.5614 val_loss=6.0873 val_acc=0.0949 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 27/70: train_loss=1.3855 train_acc=0.5816 val_loss=7.1706 val_acc=0.0841 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 28/70: train_loss=1.3503 train_acc=0.5895 val_loss=6.6643 val_acc=0.0882 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 29/70: train_loss=1.3258 train_acc=0.5916 val_loss=7.0515 val_acc=0.0808 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 30/70: train_loss=1.3012 train_acc=0.6038 val_loss=7.1647 val_acc=0.0882 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 31/70: train_loss=1.2515 train_acc=0.6191 val_loss=7.0305 val_acc=0.0868 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 32/70: train_loss=1.2407 train_acc=0.6177 val_loss=7.1233 val_acc=0.1036 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 33/70: train_loss=1.2350 train_acc=0.6169 val_loss=7.2626 val_acc=0.0949 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 34/70: train_loss=1.1913 train_acc=0.6376 val_loss=7.2527 val_acc=0.0895 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 35/70: train_loss=1.1646 train_acc=0.6496 val_loss=7.2703 val_acc=0.0962 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 36/70: train_loss=1.1321 train_acc=0.6462 val_loss=7.8600 val_acc=0.0814 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 37/70: train_loss=1.1143 train_acc=0.6583 val_loss=7.9174 val_acc=0.0868 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 38/70: train_loss=1.0841 train_acc=0.6656 val_loss=7.3722 val_acc=0.0949 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 39/70: train_loss=1.0777 train_acc=0.6638 val_loss=8.7619 val_acc=0.0720 seconds=0.4
[CNN] early stopping at epoch 39; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__2_4ghz__lovo__ebl-session__s42__9b1404__fold-06.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__2_4ghz__lovo__ebl-session__s42__9b1404/training_curves__fold-06.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__2_4ghz__lovo__ebl-session__s42__9b1404.parquet
[results upsert] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/runs_folds.csv: 6 row(s)
[DL LOVO] seed=42 fold mean position_accuracy=0.0602 +/- 0.0237; pooled=0.0606
[DL GPU] run_id=dl__cnn__2_4ghz__lovo__ebl-session__s42__9b1404 peak_cuda_memory_bytes=514714624
[results upsert] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/runs.csv: 25 row(s)
Seeds: random=43, numpy=43, torch=43
[trial filter] split=lovo trials=['01'] kept=8906/13588
[trial filter] split=lovo trials=['01'] kept=8906/8906
[protocol] split=lovo fold=01 trials_used=['01'] n_train=7336 n_test=1570 users=['01', '02', '03', '04', '05', '06'] train_users=['02', '03', '04', '05', '06'] test_users=['01']
[protocol] split=lovo fold=02 trials_used=['01'] n_train=7492 n_test=1414 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '03', '04', '05', '06'] test_users=['02']
[protocol] split=lovo fold=03 trials_used=['01'] n_train=7319 n_test=1587 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '04', '05', '06'] test_users=['03']
[protocol] split=lovo fold=04 trials_used=['01'] n_train=7346 n_test=1560 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '05', '06'] test_users=['04']
[protocol] split=lovo fold=05 trials_used=['01'] n_train=7420 n_test=1486 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '06'] test_users=['05']
[protocol] split=lovo fold=06 trials_used=['01'] n_train=7617 n_test=1289 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05'] test_users=['06']
[DL LOVO] held_out_user=01 validation_user=06 (entire user, deterministic rotation)
[CNN] 2.4 GHz/lovo fold=01 parameters=76020
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] 2.4 GHz/lovo fold=01 epoch 01/70: train_loss=3.9059 train_acc=0.0460 val_loss=3.9564 val_acc=0.0178 seconds=2.7
[CNN] 2.4 GHz/lovo fold=01 epoch 02/70: train_loss=3.6415 train_acc=0.0881 val_loss=3.8745 val_acc=0.0450 seconds=0.4
[CNN] 2.4 GHz/lovo fold=01 epoch 03/70: train_loss=3.2649 train_acc=0.1313 val_loss=4.0442 val_acc=0.0582 seconds=0.4
[CNN] 2.4 GHz/lovo fold=01 epoch 04/70: train_loss=2.9972 train_acc=0.1726 val_loss=4.1118 val_acc=0.0706 seconds=0.4
[CNN] 2.4 GHz/lovo fold=01 epoch 05/70: train_loss=2.7871 train_acc=0.2166 val_loss=4.1267 val_acc=0.0574 seconds=0.4
[CNN] 2.4 GHz/lovo fold=01 epoch 06/70: train_loss=2.6133 train_acc=0.2538 val_loss=4.5962 val_acc=0.0675 seconds=0.4
[CNN] 2.4 GHz/lovo fold=01 epoch 07/70: train_loss=2.4608 train_acc=0.2922 val_loss=4.5769 val_acc=0.0784 seconds=0.4
[CNN] 2.4 GHz/lovo fold=01 epoch 08/70: train_loss=2.3448 train_acc=0.3132 val_loss=5.0940 val_acc=0.0628 seconds=0.4
[CNN] 2.4 GHz/lovo fold=01 epoch 09/70: train_loss=2.2204 train_acc=0.3431 val_loss=5.8158 val_acc=0.0706 seconds=0.4
[CNN] 2.4 GHz/lovo fold=01 epoch 10/70: train_loss=2.1338 train_acc=0.3603 val_loss=5.7405 val_acc=0.0520 seconds=0.4
[CNN] 2.4 GHz/lovo fold=01 epoch 11/70: train_loss=2.0136 train_acc=0.3937 val_loss=5.9050 val_acc=0.0574 seconds=0.4
[CNN] 2.4 GHz/lovo fold=01 epoch 12/70: train_loss=1.9422 train_acc=0.4191 val_loss=6.1640 val_acc=0.0512 seconds=0.4
[CNN] 2.4 GHz/lovo fold=01 epoch 13/70: train_loss=1.8815 train_acc=0.4245 val_loss=6.2251 val_acc=0.0465 seconds=0.4
[CNN] 2.4 GHz/lovo fold=01 epoch 14/70: train_loss=1.7986 train_acc=0.4472 val_loss=6.8149 val_acc=0.0636 seconds=0.4
[CNN] 2.4 GHz/lovo fold=01 epoch 15/70: train_loss=1.7284 train_acc=0.4685 val_loss=7.1498 val_acc=0.0504 seconds=0.3
[CNN] 2.4 GHz/lovo fold=01 epoch 16/70: train_loss=1.6667 train_acc=0.4860 val_loss=7.6092 val_acc=0.0489 seconds=0.4
[CNN] 2.4 GHz/lovo fold=01 epoch 17/70: train_loss=1.6516 train_acc=0.4754 val_loss=7.7505 val_acc=0.0349 seconds=0.4
[CNN] 2.4 GHz/lovo fold=01 epoch 18/70: train_loss=1.5873 train_acc=0.5087 val_loss=7.3606 val_acc=0.0559 seconds=0.3
[CNN] 2.4 GHz/lovo fold=01 epoch 19/70: train_loss=1.5491 train_acc=0.5191 val_loss=7.6669 val_acc=0.0372 seconds=0.4
[CNN] 2.4 GHz/lovo fold=01 epoch 20/70: train_loss=1.5030 train_acc=0.5277 val_loss=8.1412 val_acc=0.0403 seconds=0.4
[CNN] 2.4 GHz/lovo fold=01 epoch 21/70: train_loss=1.4657 train_acc=0.5424 val_loss=7.3898 val_acc=0.0574 seconds=0.4
[CNN] 2.4 GHz/lovo fold=01 epoch 22/70: train_loss=1.4234 train_acc=0.5520 val_loss=8.6847 val_acc=0.0582 seconds=0.4
[CNN] early stopping at epoch 22; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__2_4ghz__lovo__ebl-session__s43__a89b5d__fold-01.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__2_4ghz__lovo__ebl-session__s43__a89b5d/training_curves__fold-01.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=02 validation_user=01 (entire user, deterministic rotation)
[CNN] 2.4 GHz/lovo fold=02 parameters=76020
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] 2.4 GHz/lovo fold=02 epoch 01/70: train_loss=3.8825 train_acc=0.0485 val_loss=3.9287 val_acc=0.0248 seconds=3.1
[CNN] 2.4 GHz/lovo fold=02 epoch 02/70: train_loss=3.5482 train_acc=0.0809 val_loss=3.7640 val_acc=0.0471 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 03/70: train_loss=3.1824 train_acc=0.1326 val_loss=4.1586 val_acc=0.0554 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 04/70: train_loss=2.8915 train_acc=0.1903 val_loss=4.3450 val_acc=0.0490 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 05/70: train_loss=2.6990 train_acc=0.2246 val_loss=4.4740 val_acc=0.0344 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 06/70: train_loss=2.5423 train_acc=0.2595 val_loss=4.8826 val_acc=0.0420 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 07/70: train_loss=2.4215 train_acc=0.2886 val_loss=5.0060 val_acc=0.0529 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 08/70: train_loss=2.2949 train_acc=0.3158 val_loss=5.5620 val_acc=0.0465 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 09/70: train_loss=2.1929 train_acc=0.3457 val_loss=5.4420 val_acc=0.0688 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 10/70: train_loss=2.1176 train_acc=0.3604 val_loss=5.7318 val_acc=0.0439 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 11/70: train_loss=2.0310 train_acc=0.3818 val_loss=5.3424 val_acc=0.0382 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 12/70: train_loss=1.9536 train_acc=0.4132 val_loss=6.1550 val_acc=0.0510 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 13/70: train_loss=1.8667 train_acc=0.4227 val_loss=6.3799 val_acc=0.0592 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 14/70: train_loss=1.8375 train_acc=0.4336 val_loss=6.0332 val_acc=0.0427 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 15/70: train_loss=1.7650 train_acc=0.4573 val_loss=7.0733 val_acc=0.0433 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 16/70: train_loss=1.7076 train_acc=0.4764 val_loss=6.8818 val_acc=0.0618 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 17/70: train_loss=1.6870 train_acc=0.4786 val_loss=6.8742 val_acc=0.0490 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 18/70: train_loss=1.6081 train_acc=0.5008 val_loss=6.3255 val_acc=0.0433 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 19/70: train_loss=1.5640 train_acc=0.5191 val_loss=7.1768 val_acc=0.0503 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 20/70: train_loss=1.5308 train_acc=0.5317 val_loss=8.4202 val_acc=0.0535 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 21/70: train_loss=1.4926 train_acc=0.5439 val_loss=6.3019 val_acc=0.0541 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 22/70: train_loss=1.4736 train_acc=0.5447 val_loss=7.8321 val_acc=0.0490 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 23/70: train_loss=1.3978 train_acc=0.5670 val_loss=7.4300 val_acc=0.0599 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 24/70: train_loss=1.3393 train_acc=0.5905 val_loss=6.9360 val_acc=0.0605 seconds=0.4
[CNN] early stopping at epoch 24; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__2_4ghz__lovo__ebl-session__s43__a89b5d__fold-02.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__2_4ghz__lovo__ebl-session__s43__a89b5d/training_curves__fold-02.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=03 validation_user=02 (entire user, deterministic rotation)
[CNN] 2.4 GHz/lovo fold=03 parameters=76020
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] 2.4 GHz/lovo fold=03 epoch 01/70: train_loss=3.8590 train_acc=0.0434 val_loss=3.9535 val_acc=0.0198 seconds=2.7
[CNN] 2.4 GHz/lovo fold=03 epoch 02/70: train_loss=3.5400 train_acc=0.0711 val_loss=4.0980 val_acc=0.0184 seconds=0.3
[CNN] 2.4 GHz/lovo fold=03 epoch 03/70: train_loss=3.2508 train_acc=0.1311 val_loss=4.2143 val_acc=0.0198 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 04/70: train_loss=2.9705 train_acc=0.1744 val_loss=4.5365 val_acc=0.0325 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 05/70: train_loss=2.7805 train_acc=0.2102 val_loss=4.8615 val_acc=0.0198 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 06/70: train_loss=2.5899 train_acc=0.2622 val_loss=4.5756 val_acc=0.0431 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 07/70: train_loss=2.4536 train_acc=0.2874 val_loss=4.8193 val_acc=0.0424 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 08/70: train_loss=2.3138 train_acc=0.3284 val_loss=5.1738 val_acc=0.0325 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 09/70: train_loss=2.1993 train_acc=0.3511 val_loss=5.3595 val_acc=0.0297 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 10/70: train_loss=2.1233 train_acc=0.3646 val_loss=5.1580 val_acc=0.0396 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 11/70: train_loss=2.0403 train_acc=0.3992 val_loss=5.5967 val_acc=0.0354 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 12/70: train_loss=1.9856 train_acc=0.4093 val_loss=5.5257 val_acc=0.0375 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 13/70: train_loss=1.9150 train_acc=0.4312 val_loss=5.6816 val_acc=0.0446 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 14/70: train_loss=1.8601 train_acc=0.4417 val_loss=5.8967 val_acc=0.0304 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 15/70: train_loss=1.7840 train_acc=0.4576 val_loss=6.0951 val_acc=0.0304 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 16/70: train_loss=1.7505 train_acc=0.4693 val_loss=6.5522 val_acc=0.0290 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 17/70: train_loss=1.6764 train_acc=0.4950 val_loss=6.2776 val_acc=0.0410 seconds=0.3
[CNN] 2.4 GHz/lovo fold=03 epoch 18/70: train_loss=1.6345 train_acc=0.5086 val_loss=6.5660 val_acc=0.0460 seconds=0.3
[CNN] 2.4 GHz/lovo fold=03 epoch 19/70: train_loss=1.6458 train_acc=0.5030 val_loss=6.7969 val_acc=0.0297 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 20/70: train_loss=1.5522 train_acc=0.5363 val_loss=6.7246 val_acc=0.0431 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 21/70: train_loss=1.5080 train_acc=0.5411 val_loss=6.9148 val_acc=0.0375 seconds=0.3
[CNN] 2.4 GHz/lovo fold=03 epoch 22/70: train_loss=1.4747 train_acc=0.5522 val_loss=6.7174 val_acc=0.0347 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 23/70: train_loss=1.4278 train_acc=0.5704 val_loss=7.0867 val_acc=0.0318 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 24/70: train_loss=1.3808 train_acc=0.5766 val_loss=7.0967 val_acc=0.0240 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 25/70: train_loss=1.3775 train_acc=0.5817 val_loss=6.9062 val_acc=0.0424 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 26/70: train_loss=1.3136 train_acc=0.6039 val_loss=7.1894 val_acc=0.0368 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 27/70: train_loss=1.3001 train_acc=0.6063 val_loss=6.9024 val_acc=0.0368 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 28/70: train_loss=1.2549 train_acc=0.6168 val_loss=6.8772 val_acc=0.0424 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 29/70: train_loss=1.2660 train_acc=0.6195 val_loss=7.6267 val_acc=0.0467 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 30/70: train_loss=1.2602 train_acc=0.6139 val_loss=7.1097 val_acc=0.0339 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 31/70: train_loss=1.1768 train_acc=0.6413 val_loss=7.7879 val_acc=0.0347 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 32/70: train_loss=1.1664 train_acc=0.6417 val_loss=7.8971 val_acc=0.0297 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 33/70: train_loss=1.1391 train_acc=0.6491 val_loss=7.2881 val_acc=0.0481 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 34/70: train_loss=1.1087 train_acc=0.6508 val_loss=7.7864 val_acc=0.0290 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 35/70: train_loss=1.0624 train_acc=0.6787 val_loss=7.4493 val_acc=0.0438 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 36/70: train_loss=1.0562 train_acc=0.6730 val_loss=7.6278 val_acc=0.0354 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 37/70: train_loss=1.0448 train_acc=0.6789 val_loss=7.4919 val_acc=0.0325 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 38/70: train_loss=1.1108 train_acc=0.6562 val_loss=8.3682 val_acc=0.0318 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 39/70: train_loss=1.0335 train_acc=0.6816 val_loss=8.5911 val_acc=0.0311 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 40/70: train_loss=1.0020 train_acc=0.6972 val_loss=7.8912 val_acc=0.0332 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 41/70: train_loss=0.9749 train_acc=0.7003 val_loss=8.1858 val_acc=0.0375 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 42/70: train_loss=0.9552 train_acc=0.7053 val_loss=8.2898 val_acc=0.0276 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 43/70: train_loss=0.9458 train_acc=0.7106 val_loss=8.9052 val_acc=0.0248 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 44/70: train_loss=0.9353 train_acc=0.7074 val_loss=7.9822 val_acc=0.0587 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 45/70: train_loss=0.8762 train_acc=0.7306 val_loss=8.7962 val_acc=0.0396 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 46/70: train_loss=0.8753 train_acc=0.7306 val_loss=8.4594 val_acc=0.0354 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 47/70: train_loss=0.8708 train_acc=0.7307 val_loss=8.5323 val_acc=0.0382 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 48/70: train_loss=0.8677 train_acc=0.7309 val_loss=8.3674 val_acc=0.0375 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 49/70: train_loss=0.8466 train_acc=0.7336 val_loss=8.3684 val_acc=0.0382 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 50/70: train_loss=0.8194 train_acc=0.7470 val_loss=8.9015 val_acc=0.0212 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 51/70: train_loss=0.8062 train_acc=0.7450 val_loss=8.9049 val_acc=0.0347 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 52/70: train_loss=0.8575 train_acc=0.7296 val_loss=8.4013 val_acc=0.0417 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 53/70: train_loss=0.8076 train_acc=0.7480 val_loss=8.4117 val_acc=0.0417 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 54/70: train_loss=0.8008 train_acc=0.7473 val_loss=8.1267 val_acc=0.0396 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 55/70: train_loss=0.7419 train_acc=0.7690 val_loss=8.4663 val_acc=0.0332 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 56/70: train_loss=0.7574 train_acc=0.7621 val_loss=8.8402 val_acc=0.0417 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 57/70: train_loss=0.8043 train_acc=0.7473 val_loss=8.7257 val_acc=0.0361 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 58/70: train_loss=0.7701 train_acc=0.7570 val_loss=8.8937 val_acc=0.0311 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 59/70: train_loss=0.7275 train_acc=0.7773 val_loss=8.8403 val_acc=0.0325 seconds=0.4
[CNN] early stopping at epoch 59; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__2_4ghz__lovo__ebl-session__s43__a89b5d__fold-03.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__2_4ghz__lovo__ebl-session__s43__a89b5d/training_curves__fold-03.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=04 validation_user=03 (entire user, deterministic rotation)
[CNN] 2.4 GHz/lovo fold=04 parameters=76020
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] 2.4 GHz/lovo fold=04 epoch 01/70: train_loss=3.9014 train_acc=0.0438 val_loss=3.9899 val_acc=0.0176 seconds=2.7
[CNN] 2.4 GHz/lovo fold=04 epoch 02/70: train_loss=3.6309 train_acc=0.0677 val_loss=4.6110 val_acc=0.0195 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 03/70: train_loss=3.3008 train_acc=0.1130 val_loss=5.3577 val_acc=0.0214 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 04/70: train_loss=3.0755 train_acc=0.1544 val_loss=5.2406 val_acc=0.0214 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 05/70: train_loss=2.9026 train_acc=0.1907 val_loss=4.8439 val_acc=0.0265 seconds=0.3
[CNN] 2.4 GHz/lovo fold=04 epoch 06/70: train_loss=2.7231 train_acc=0.2247 val_loss=6.0534 val_acc=0.0227 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 07/70: train_loss=2.5631 train_acc=0.2612 val_loss=5.3007 val_acc=0.0239 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 08/70: train_loss=2.4273 train_acc=0.2907 val_loss=6.8081 val_acc=0.0233 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 09/70: train_loss=2.2734 train_acc=0.3356 val_loss=6.2878 val_acc=0.0246 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 10/70: train_loss=2.2083 train_acc=0.3416 val_loss=6.6110 val_acc=0.0227 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 11/70: train_loss=2.1212 train_acc=0.3646 val_loss=6.5201 val_acc=0.0302 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 12/70: train_loss=2.0183 train_acc=0.3923 val_loss=7.3769 val_acc=0.0239 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 13/70: train_loss=1.9543 train_acc=0.4098 val_loss=6.7659 val_acc=0.0302 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 14/70: train_loss=1.8923 train_acc=0.4195 val_loss=8.3315 val_acc=0.0227 seconds=0.3
[CNN] 2.4 GHz/lovo fold=04 epoch 15/70: train_loss=1.8275 train_acc=0.4468 val_loss=8.4168 val_acc=0.0227 seconds=0.3
[CNN] 2.4 GHz/lovo fold=04 epoch 16/70: train_loss=1.7574 train_acc=0.4624 val_loss=7.5971 val_acc=0.0321 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 17/70: train_loss=1.7194 train_acc=0.4810 val_loss=8.1615 val_acc=0.0271 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 18/70: train_loss=1.7056 train_acc=0.4810 val_loss=9.1999 val_acc=0.0246 seconds=0.3
[CNN] 2.4 GHz/lovo fold=04 epoch 19/70: train_loss=1.6411 train_acc=0.4978 val_loss=9.5768 val_acc=0.0246 seconds=0.3
[CNN] 2.4 GHz/lovo fold=04 epoch 20/70: train_loss=1.5712 train_acc=0.5157 val_loss=10.9349 val_acc=0.0233 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 21/70: train_loss=1.5277 train_acc=0.5267 val_loss=9.7914 val_acc=0.0271 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 22/70: train_loss=1.4987 train_acc=0.5326 val_loss=11.0320 val_acc=0.0258 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 23/70: train_loss=1.4574 train_acc=0.5478 val_loss=11.8344 val_acc=0.0233 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 24/70: train_loss=1.4418 train_acc=0.5553 val_loss=10.1149 val_acc=0.0290 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 25/70: train_loss=1.3753 train_acc=0.5742 val_loss=10.3042 val_acc=0.0271 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 26/70: train_loss=1.3246 train_acc=0.5965 val_loss=10.4183 val_acc=0.0296 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 27/70: train_loss=1.2882 train_acc=0.6098 val_loss=9.2599 val_acc=0.0315 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 28/70: train_loss=1.3018 train_acc=0.6031 val_loss=10.5913 val_acc=0.0353 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 29/70: train_loss=1.2646 train_acc=0.6178 val_loss=10.1727 val_acc=0.0372 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 30/70: train_loss=1.2270 train_acc=0.6185 val_loss=11.6890 val_acc=0.0284 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 31/70: train_loss=1.2179 train_acc=0.6187 val_loss=11.2358 val_acc=0.0284 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 32/70: train_loss=1.1755 train_acc=0.6347 val_loss=11.1114 val_acc=0.0353 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 33/70: train_loss=1.1622 train_acc=0.6380 val_loss=10.2513 val_acc=0.0416 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 34/70: train_loss=1.0999 train_acc=0.6668 val_loss=10.3895 val_acc=0.0328 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 35/70: train_loss=1.0743 train_acc=0.6670 val_loss=12.6279 val_acc=0.0328 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 36/70: train_loss=1.0898 train_acc=0.6578 val_loss=11.2620 val_acc=0.0441 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 37/70: train_loss=1.0548 train_acc=0.6708 val_loss=12.6392 val_acc=0.0359 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 38/70: train_loss=1.0166 train_acc=0.6864 val_loss=13.6512 val_acc=0.0233 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 39/70: train_loss=0.9876 train_acc=0.6864 val_loss=14.4241 val_acc=0.0277 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 40/70: train_loss=0.9858 train_acc=0.6991 val_loss=15.0397 val_acc=0.0208 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 41/70: train_loss=0.9867 train_acc=0.6881 val_loss=13.8408 val_acc=0.0284 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 42/70: train_loss=0.9761 train_acc=0.6972 val_loss=12.5008 val_acc=0.0284 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 43/70: train_loss=0.9294 train_acc=0.7081 val_loss=14.5794 val_acc=0.0296 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 44/70: train_loss=0.9242 train_acc=0.7131 val_loss=13.6162 val_acc=0.0353 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 45/70: train_loss=0.8964 train_acc=0.7177 val_loss=12.7962 val_acc=0.0391 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 46/70: train_loss=0.8943 train_acc=0.7159 val_loss=13.0765 val_acc=0.0353 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 47/70: train_loss=0.8774 train_acc=0.7237 val_loss=14.1157 val_acc=0.0296 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 48/70: train_loss=0.8768 train_acc=0.7184 val_loss=12.2745 val_acc=0.0378 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 49/70: train_loss=0.8475 train_acc=0.7267 val_loss=14.4541 val_acc=0.0378 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 50/70: train_loss=0.8105 train_acc=0.7494 val_loss=14.0660 val_acc=0.0328 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 51/70: train_loss=0.7913 train_acc=0.7536 val_loss=13.9663 val_acc=0.0372 seconds=0.4
[CNN] early stopping at epoch 51; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__2_4ghz__lovo__ebl-session__s43__a89b5d__fold-04.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__2_4ghz__lovo__ebl-session__s43__a89b5d/training_curves__fold-04.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=05 validation_user=04 (entire user, deterministic rotation)
[CNN] 2.4 GHz/lovo fold=05 parameters=76020
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] 2.4 GHz/lovo fold=05 epoch 01/70: train_loss=3.9168 train_acc=0.0358 val_loss=3.9547 val_acc=0.0244 seconds=3.0
[CNN] 2.4 GHz/lovo fold=05 epoch 02/70: train_loss=3.6941 train_acc=0.0782 val_loss=4.2256 val_acc=0.0378 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 03/70: train_loss=3.3165 train_acc=0.1287 val_loss=5.0191 val_acc=0.0654 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 04/70: train_loss=3.0231 train_acc=0.1681 val_loss=5.0009 val_acc=0.0481 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 05/70: train_loss=2.8267 train_acc=0.2060 val_loss=5.0985 val_acc=0.0564 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 06/70: train_loss=2.6634 train_acc=0.2382 val_loss=4.5601 val_acc=0.0603 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 07/70: train_loss=2.5250 train_acc=0.2753 val_loss=5.4930 val_acc=0.0603 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 08/70: train_loss=2.4060 train_acc=0.3085 val_loss=5.0604 val_acc=0.0596 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 09/70: train_loss=2.3078 train_acc=0.3210 val_loss=5.0508 val_acc=0.0429 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 10/70: train_loss=2.2401 train_acc=0.3399 val_loss=4.7127 val_acc=0.0712 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 11/70: train_loss=2.1304 train_acc=0.3735 val_loss=5.3945 val_acc=0.0429 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 12/70: train_loss=2.0741 train_acc=0.3829 val_loss=5.1376 val_acc=0.0647 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 13/70: train_loss=1.9914 train_acc=0.4022 val_loss=5.5507 val_acc=0.0647 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 14/70: train_loss=1.9070 train_acc=0.4302 val_loss=5.4446 val_acc=0.0513 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 15/70: train_loss=1.8416 train_acc=0.4466 val_loss=6.0130 val_acc=0.0494 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 16/70: train_loss=1.7792 train_acc=0.4601 val_loss=6.1406 val_acc=0.0391 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 17/70: train_loss=1.7389 train_acc=0.4753 val_loss=5.7676 val_acc=0.0667 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 18/70: train_loss=1.6909 train_acc=0.4794 val_loss=5.9941 val_acc=0.0571 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 19/70: train_loss=1.6563 train_acc=0.4939 val_loss=6.5744 val_acc=0.0532 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 20/70: train_loss=1.6076 train_acc=0.5082 val_loss=6.4690 val_acc=0.0654 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 21/70: train_loss=1.5620 train_acc=0.5208 val_loss=6.5614 val_acc=0.0558 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 22/70: train_loss=1.5016 train_acc=0.5437 val_loss=6.2724 val_acc=0.0564 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 23/70: train_loss=1.4913 train_acc=0.5428 val_loss=6.7905 val_acc=0.0571 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 24/70: train_loss=1.4696 train_acc=0.5457 val_loss=6.3346 val_acc=0.0647 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 25/70: train_loss=1.3986 train_acc=0.5696 val_loss=7.1332 val_acc=0.0571 seconds=0.4
[CNN] early stopping at epoch 25; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__2_4ghz__lovo__ebl-session__s43__a89b5d__fold-05.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__2_4ghz__lovo__ebl-session__s43__a89b5d/training_curves__fold-05.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=06 validation_user=05 (entire user, deterministic rotation)
[CNN] 2.4 GHz/lovo fold=06 parameters=76020
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] 2.4 GHz/lovo fold=06 epoch 01/70: train_loss=3.8993 train_acc=0.0360 val_loss=3.9434 val_acc=0.0202 seconds=2.8
[CNN] 2.4 GHz/lovo fold=06 epoch 02/70: train_loss=3.6728 train_acc=0.0680 val_loss=3.7627 val_acc=0.0444 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 03/70: train_loss=3.3479 train_acc=0.1194 val_loss=3.8814 val_acc=0.0431 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 04/70: train_loss=3.0780 train_acc=0.1540 val_loss=3.9587 val_acc=0.0740 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 05/70: train_loss=2.8847 train_acc=0.1923 val_loss=4.3400 val_acc=0.0659 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 06/70: train_loss=2.7124 train_acc=0.2310 val_loss=4.0719 val_acc=0.0680 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 07/70: train_loss=2.5997 train_acc=0.2479 val_loss=4.4901 val_acc=0.0734 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 08/70: train_loss=2.4891 train_acc=0.2801 val_loss=4.7851 val_acc=0.0686 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 09/70: train_loss=2.3920 train_acc=0.2978 val_loss=4.7732 val_acc=0.0713 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 10/70: train_loss=2.2906 train_acc=0.3241 val_loss=4.9492 val_acc=0.0861 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 11/70: train_loss=2.2017 train_acc=0.3479 val_loss=5.0025 val_acc=0.0895 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 12/70: train_loss=2.1234 train_acc=0.3735 val_loss=5.0387 val_acc=0.0929 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 13/70: train_loss=2.0379 train_acc=0.3990 val_loss=5.1792 val_acc=0.0908 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 14/70: train_loss=1.9760 train_acc=0.4125 val_loss=5.0767 val_acc=0.0935 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 15/70: train_loss=1.9369 train_acc=0.4167 val_loss=5.3395 val_acc=0.0989 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 16/70: train_loss=1.8424 train_acc=0.4335 val_loss=5.4197 val_acc=0.0875 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 17/70: train_loss=1.7782 train_acc=0.4582 val_loss=5.4643 val_acc=0.0754 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 18/70: train_loss=1.7308 train_acc=0.4732 val_loss=5.4048 val_acc=0.0983 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 19/70: train_loss=1.6677 train_acc=0.4950 val_loss=5.8190 val_acc=0.0861 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 20/70: train_loss=1.6416 train_acc=0.5055 val_loss=5.7944 val_acc=0.0834 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 21/70: train_loss=1.5996 train_acc=0.5122 val_loss=5.7778 val_acc=0.1003 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 22/70: train_loss=1.5570 train_acc=0.5167 val_loss=6.4614 val_acc=0.0518 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 23/70: train_loss=1.5232 train_acc=0.5288 val_loss=5.7988 val_acc=0.0895 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 24/70: train_loss=1.4728 train_acc=0.5508 val_loss=6.0082 val_acc=0.0808 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 25/70: train_loss=1.4265 train_acc=0.5656 val_loss=6.6361 val_acc=0.0814 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 26/70: train_loss=1.3813 train_acc=0.5715 val_loss=6.2648 val_acc=0.0848 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 27/70: train_loss=1.3486 train_acc=0.5820 val_loss=6.2129 val_acc=0.0828 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 28/70: train_loss=1.3359 train_acc=0.5860 val_loss=6.8069 val_acc=0.0902 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 29/70: train_loss=1.3052 train_acc=0.5931 val_loss=6.6172 val_acc=0.0841 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 30/70: train_loss=1.2514 train_acc=0.6092 val_loss=6.3591 val_acc=0.0888 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 31/70: train_loss=1.2336 train_acc=0.6169 val_loss=6.9017 val_acc=0.0720 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 32/70: train_loss=1.2227 train_acc=0.6185 val_loss=7.8277 val_acc=0.0639 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 33/70: train_loss=1.1825 train_acc=0.6262 val_loss=6.5838 val_acc=0.0882 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 34/70: train_loss=1.1631 train_acc=0.6390 val_loss=7.3863 val_acc=0.0781 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 35/70: train_loss=1.1360 train_acc=0.6479 val_loss=7.2787 val_acc=0.0814 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 36/70: train_loss=1.1062 train_acc=0.6505 val_loss=7.1283 val_acc=0.0794 seconds=0.4
[CNN] early stopping at epoch 36; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__2_4ghz__lovo__ebl-session__s43__a89b5d__fold-06.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__2_4ghz__lovo__ebl-session__s43__a89b5d/training_curves__fold-06.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__2_4ghz__lovo__ebl-session__s43__a89b5d.parquet
[results upsert] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/runs_folds.csv: 12 row(s)
[DL LOVO] seed=43 fold mean position_accuracy=0.0497 +/- 0.0095; pooled=0.0495
[DL GPU] run_id=dl__cnn__2_4ghz__lovo__ebl-session__s43__a89b5d peak_cuda_memory_bytes=514714624
[results upsert] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/runs.csv: 26 row(s)
Seeds: random=44, numpy=44, torch=44
[trial filter] split=lovo trials=['01'] kept=8906/13588
[trial filter] split=lovo trials=['01'] kept=8906/8906
[protocol] split=lovo fold=01 trials_used=['01'] n_train=7336 n_test=1570 users=['01', '02', '03', '04', '05', '06'] train_users=['02', '03', '04', '05', '06'] test_users=['01']
[protocol] split=lovo fold=02 trials_used=['01'] n_train=7492 n_test=1414 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '03', '04', '05', '06'] test_users=['02']
[protocol] split=lovo fold=03 trials_used=['01'] n_train=7319 n_test=1587 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '04', '05', '06'] test_users=['03']
[protocol] split=lovo fold=04 trials_used=['01'] n_train=7346 n_test=1560 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '05', '06'] test_users=['04']
[protocol] split=lovo fold=05 trials_used=['01'] n_train=7420 n_test=1486 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '06'] test_users=['05']
[protocol] split=lovo fold=06 trials_used=['01'] n_train=7617 n_test=1289 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05'] test_users=['06']
[DL LOVO] held_out_user=01 validation_user=06 (entire user, deterministic rotation)
[CNN] 2.4 GHz/lovo fold=01 parameters=76020
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] 2.4 GHz/lovo fold=01 epoch 01/70: train_loss=3.8975 train_acc=0.0480 val_loss=3.9409 val_acc=0.0194 seconds=3.0
[CNN] 2.4 GHz/lovo fold=01 epoch 02/70: train_loss=3.6405 train_acc=0.0895 val_loss=3.8366 val_acc=0.0543 seconds=0.4
[CNN] 2.4 GHz/lovo fold=01 epoch 03/70: train_loss=3.3061 train_acc=0.1263 val_loss=4.0333 val_acc=0.0551 seconds=0.4
[CNN] 2.4 GHz/lovo fold=01 epoch 04/70: train_loss=3.0429 train_acc=0.1634 val_loss=4.2180 val_acc=0.0566 seconds=0.4
[CNN] 2.4 GHz/lovo fold=01 epoch 05/70: train_loss=2.8373 train_acc=0.2061 val_loss=4.2316 val_acc=0.0807 seconds=0.4
[CNN] 2.4 GHz/lovo fold=01 epoch 06/70: train_loss=2.6343 train_acc=0.2515 val_loss=4.6466 val_acc=0.0644 seconds=0.4
[CNN] 2.4 GHz/lovo fold=01 epoch 07/70: train_loss=2.4932 train_acc=0.2833 val_loss=5.5032 val_acc=0.0403 seconds=0.4
[CNN] 2.4 GHz/lovo fold=01 epoch 08/70: train_loss=2.3612 train_acc=0.3114 val_loss=5.0312 val_acc=0.0504 seconds=0.4
[CNN] 2.4 GHz/lovo fold=01 epoch 09/70: train_loss=2.2282 train_acc=0.3498 val_loss=4.8813 val_acc=0.0853 seconds=0.4
[CNN] 2.4 GHz/lovo fold=01 epoch 10/70: train_loss=2.1531 train_acc=0.3594 val_loss=5.5457 val_acc=0.0721 seconds=0.4
[CNN] 2.4 GHz/lovo fold=01 epoch 11/70: train_loss=2.0493 train_acc=0.3944 val_loss=5.1514 val_acc=0.0822 seconds=0.4
[CNN] 2.4 GHz/lovo fold=01 epoch 12/70: train_loss=1.9818 train_acc=0.4086 val_loss=6.0684 val_acc=0.0683 seconds=0.4
[CNN] 2.4 GHz/lovo fold=01 epoch 13/70: train_loss=1.9133 train_acc=0.4277 val_loss=6.0244 val_acc=0.0745 seconds=0.4
[CNN] 2.4 GHz/lovo fold=01 epoch 14/70: train_loss=1.8315 train_acc=0.4420 val_loss=6.9175 val_acc=0.0543 seconds=0.4
[CNN] 2.4 GHz/lovo fold=01 epoch 15/70: train_loss=1.7855 train_acc=0.4528 val_loss=6.0046 val_acc=0.0543 seconds=0.4
[CNN] 2.4 GHz/lovo fold=01 epoch 16/70: train_loss=1.7129 train_acc=0.4824 val_loss=6.8983 val_acc=0.0706 seconds=0.4
[CNN] 2.4 GHz/lovo fold=01 epoch 17/70: train_loss=1.6674 train_acc=0.4857 val_loss=6.4080 val_acc=0.0605 seconds=0.4
[CNN] 2.4 GHz/lovo fold=01 epoch 18/70: train_loss=1.6038 train_acc=0.5057 val_loss=7.0977 val_acc=0.0512 seconds=0.4
[CNN] 2.4 GHz/lovo fold=01 epoch 19/70: train_loss=1.5742 train_acc=0.5150 val_loss=6.4781 val_acc=0.0621 seconds=0.4
[CNN] 2.4 GHz/lovo fold=01 epoch 20/70: train_loss=1.5281 train_acc=0.5275 val_loss=6.5717 val_acc=0.0753 seconds=0.4
[CNN] 2.4 GHz/lovo fold=01 epoch 21/70: train_loss=1.4778 train_acc=0.5474 val_loss=7.0903 val_acc=0.0590 seconds=0.4
[CNN] 2.4 GHz/lovo fold=01 epoch 22/70: train_loss=1.4362 train_acc=0.5575 val_loss=7.5196 val_acc=0.0628 seconds=0.4
[CNN] 2.4 GHz/lovo fold=01 epoch 23/70: train_loss=1.4348 train_acc=0.5505 val_loss=7.1909 val_acc=0.0706 seconds=0.3
[CNN] 2.4 GHz/lovo fold=01 epoch 24/70: train_loss=1.3645 train_acc=0.5710 val_loss=7.1069 val_acc=0.0667 seconds=0.4
[CNN] early stopping at epoch 24; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__2_4ghz__lovo__ebl-session__s44__7b9bf2__fold-01.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__2_4ghz__lovo__ebl-session__s44__7b9bf2/training_curves__fold-01.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=02 validation_user=01 (entire user, deterministic rotation)
[CNN] 2.4 GHz/lovo fold=02 parameters=76020
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] 2.4 GHz/lovo fold=02 epoch 01/70: train_loss=3.8912 train_acc=0.0446 val_loss=3.9269 val_acc=0.0261 seconds=2.8
[CNN] 2.4 GHz/lovo fold=02 epoch 02/70: train_loss=3.5648 train_acc=0.0863 val_loss=3.7386 val_acc=0.0624 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 03/70: train_loss=3.1686 train_acc=0.1371 val_loss=4.1222 val_acc=0.0497 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 04/70: train_loss=2.8821 train_acc=0.2008 val_loss=4.5640 val_acc=0.0414 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 05/70: train_loss=2.6837 train_acc=0.2367 val_loss=4.8199 val_acc=0.0439 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 06/70: train_loss=2.5127 train_acc=0.2791 val_loss=4.9911 val_acc=0.0369 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 07/70: train_loss=2.3672 train_acc=0.3050 val_loss=5.0062 val_acc=0.0395 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 08/70: train_loss=2.2345 train_acc=0.3377 val_loss=5.4187 val_acc=0.0401 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 09/70: train_loss=2.1209 train_acc=0.3728 val_loss=5.8427 val_acc=0.0357 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 10/70: train_loss=2.0136 train_acc=0.3919 val_loss=5.5219 val_acc=0.0478 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 11/70: train_loss=1.9389 train_acc=0.4080 val_loss=6.5214 val_acc=0.0408 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 12/70: train_loss=1.8743 train_acc=0.4318 val_loss=6.6422 val_acc=0.0427 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 13/70: train_loss=1.7957 train_acc=0.4527 val_loss=6.3961 val_acc=0.0516 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 14/70: train_loss=1.7418 train_acc=0.4661 val_loss=6.5487 val_acc=0.0459 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 15/70: train_loss=1.6685 train_acc=0.4843 val_loss=6.7224 val_acc=0.0580 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 16/70: train_loss=1.6299 train_acc=0.4944 val_loss=7.2041 val_acc=0.0599 seconds=0.4
[CNN] 2.4 GHz/lovo fold=02 epoch 17/70: train_loss=1.5760 train_acc=0.5133 val_loss=7.1537 val_acc=0.0554 seconds=0.4
[CNN] early stopping at epoch 17; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__2_4ghz__lovo__ebl-session__s44__7b9bf2__fold-02.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__2_4ghz__lovo__ebl-session__s44__7b9bf2/training_curves__fold-02.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=03 validation_user=02 (entire user, deterministic rotation)
[CNN] 2.4 GHz/lovo fold=03 parameters=76020
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] 2.4 GHz/lovo fold=03 epoch 01/70: train_loss=3.8755 train_acc=0.0430 val_loss=3.9706 val_acc=0.0219 seconds=2.9
[CNN] 2.4 GHz/lovo fold=03 epoch 02/70: train_loss=3.5641 train_acc=0.0843 val_loss=4.1660 val_acc=0.0467 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 03/70: train_loss=3.2365 train_acc=0.1324 val_loss=4.1011 val_acc=0.0156 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 04/70: train_loss=2.9861 train_acc=0.1668 val_loss=4.3702 val_acc=0.0191 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 05/70: train_loss=2.8116 train_acc=0.2073 val_loss=4.5740 val_acc=0.0191 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 06/70: train_loss=2.6810 train_acc=0.2315 val_loss=4.8294 val_acc=0.0205 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 07/70: train_loss=2.5501 train_acc=0.2654 val_loss=4.8669 val_acc=0.0226 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 08/70: train_loss=2.4266 train_acc=0.2845 val_loss=5.2605 val_acc=0.0219 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 09/70: train_loss=2.3130 train_acc=0.3160 val_loss=5.2015 val_acc=0.0198 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 10/70: train_loss=2.2004 train_acc=0.3482 val_loss=5.1498 val_acc=0.0240 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 11/70: train_loss=2.1051 train_acc=0.3775 val_loss=5.7979 val_acc=0.0438 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 12/70: train_loss=2.0014 train_acc=0.4037 val_loss=5.6522 val_acc=0.0304 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 13/70: train_loss=1.9357 train_acc=0.4269 val_loss=5.9861 val_acc=0.0332 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 14/70: train_loss=1.8693 train_acc=0.4395 val_loss=5.8607 val_acc=0.0311 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 15/70: train_loss=1.8032 train_acc=0.4530 val_loss=5.8321 val_acc=0.0297 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 16/70: train_loss=1.7755 train_acc=0.4598 val_loss=7.0110 val_acc=0.0262 seconds=0.4
[CNN] 2.4 GHz/lovo fold=03 epoch 17/70: train_loss=1.7144 train_acc=0.4765 val_loss=6.6260 val_acc=0.0269 seconds=0.4
[CNN] early stopping at epoch 17; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__2_4ghz__lovo__ebl-session__s44__7b9bf2__fold-03.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__2_4ghz__lovo__ebl-session__s44__7b9bf2/training_curves__fold-03.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=04 validation_user=03 (entire user, deterministic rotation)
[CNN] 2.4 GHz/lovo fold=04 parameters=76020
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] 2.4 GHz/lovo fold=04 epoch 01/70: train_loss=3.9024 train_acc=0.0396 val_loss=3.9666 val_acc=0.0189 seconds=3.2
[CNN] 2.4 GHz/lovo fold=04 epoch 02/70: train_loss=3.6186 train_acc=0.0761 val_loss=4.3765 val_acc=0.0202 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 03/70: train_loss=3.2625 train_acc=0.1158 val_loss=5.2156 val_acc=0.0258 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 04/70: train_loss=3.0430 train_acc=0.1514 val_loss=5.1343 val_acc=0.0214 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 05/70: train_loss=2.8372 train_acc=0.1894 val_loss=5.6624 val_acc=0.0151 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 06/70: train_loss=2.6670 train_acc=0.2283 val_loss=5.8101 val_acc=0.0265 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 07/70: train_loss=2.5045 train_acc=0.2671 val_loss=6.1272 val_acc=0.0290 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 08/70: train_loss=2.3974 train_acc=0.2938 val_loss=6.9954 val_acc=0.0221 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 09/70: train_loss=2.2905 train_acc=0.3254 val_loss=6.6177 val_acc=0.0252 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 10/70: train_loss=2.1929 train_acc=0.3443 val_loss=7.0608 val_acc=0.0195 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 11/70: train_loss=2.1282 train_acc=0.3617 val_loss=7.0690 val_acc=0.0378 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 12/70: train_loss=2.0562 train_acc=0.3829 val_loss=6.3436 val_acc=0.0334 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 13/70: train_loss=2.0028 train_acc=0.4002 val_loss=8.7873 val_acc=0.0246 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 14/70: train_loss=1.9227 train_acc=0.4237 val_loss=10.3011 val_acc=0.0246 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 15/70: train_loss=1.8683 train_acc=0.4386 val_loss=8.0782 val_acc=0.0183 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 16/70: train_loss=1.8016 train_acc=0.4542 val_loss=8.3456 val_acc=0.0195 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 17/70: train_loss=1.7529 train_acc=0.4706 val_loss=8.5309 val_acc=0.0214 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 18/70: train_loss=1.6876 train_acc=0.4989 val_loss=8.6084 val_acc=0.0277 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 19/70: train_loss=1.6499 train_acc=0.5011 val_loss=9.0754 val_acc=0.0315 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 20/70: train_loss=1.6224 train_acc=0.5046 val_loss=7.7642 val_acc=0.0290 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 21/70: train_loss=1.5723 train_acc=0.5249 val_loss=9.7480 val_acc=0.0208 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 22/70: train_loss=1.5082 train_acc=0.5399 val_loss=8.9205 val_acc=0.0403 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 23/70: train_loss=1.4684 train_acc=0.5480 val_loss=9.4485 val_acc=0.0428 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 24/70: train_loss=1.4721 train_acc=0.5518 val_loss=8.8416 val_acc=0.0309 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 25/70: train_loss=1.3901 train_acc=0.5787 val_loss=10.1010 val_acc=0.0315 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 26/70: train_loss=1.3671 train_acc=0.5812 val_loss=8.8745 val_acc=0.0410 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 27/70: train_loss=1.3841 train_acc=0.5730 val_loss=9.5486 val_acc=0.0422 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 28/70: train_loss=1.3421 train_acc=0.5847 val_loss=12.3226 val_acc=0.0315 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 29/70: train_loss=1.2992 train_acc=0.5989 val_loss=11.0587 val_acc=0.0277 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 30/70: train_loss=1.2740 train_acc=0.6088 val_loss=10.4666 val_acc=0.0340 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 31/70: train_loss=1.2222 train_acc=0.6265 val_loss=12.0629 val_acc=0.0252 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 32/70: train_loss=1.1876 train_acc=0.6364 val_loss=11.1762 val_acc=0.0315 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 33/70: train_loss=1.1581 train_acc=0.6437 val_loss=10.4013 val_acc=0.0284 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 34/70: train_loss=1.1339 train_acc=0.6512 val_loss=11.0327 val_acc=0.0410 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 35/70: train_loss=1.1071 train_acc=0.6532 val_loss=11.6775 val_acc=0.0290 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 36/70: train_loss=1.0785 train_acc=0.6675 val_loss=12.2646 val_acc=0.0321 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 37/70: train_loss=1.0581 train_acc=0.6709 val_loss=12.1130 val_acc=0.0422 seconds=0.4
[CNN] 2.4 GHz/lovo fold=04 epoch 38/70: train_loss=1.0604 train_acc=0.6718 val_loss=12.4414 val_acc=0.0221 seconds=0.4
[CNN] early stopping at epoch 38; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__2_4ghz__lovo__ebl-session__s44__7b9bf2__fold-04.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__2_4ghz__lovo__ebl-session__s44__7b9bf2/training_curves__fold-04.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=05 validation_user=04 (entire user, deterministic rotation)
[CNN] 2.4 GHz/lovo fold=05 parameters=76020
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] 2.4 GHz/lovo fold=05 epoch 01/70: train_loss=3.9174 train_acc=0.0358 val_loss=3.9572 val_acc=0.0288 seconds=3.0
[CNN] 2.4 GHz/lovo fold=05 epoch 02/70: train_loss=3.6950 train_acc=0.0805 val_loss=4.3696 val_acc=0.0333 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 03/70: train_loss=3.3524 train_acc=0.1070 val_loss=5.0524 val_acc=0.0346 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 04/70: train_loss=3.0800 train_acc=0.1587 val_loss=4.7659 val_acc=0.0436 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 05/70: train_loss=2.8909 train_acc=0.1829 val_loss=4.4665 val_acc=0.0506 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 06/70: train_loss=2.7078 train_acc=0.2205 val_loss=4.2590 val_acc=0.0487 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 07/70: train_loss=2.5878 train_acc=0.2502 val_loss=4.7484 val_acc=0.0404 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 08/70: train_loss=2.4305 train_acc=0.2829 val_loss=4.7057 val_acc=0.0385 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 09/70: train_loss=2.3134 train_acc=0.3235 val_loss=5.6369 val_acc=0.0269 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 10/70: train_loss=2.1986 train_acc=0.3485 val_loss=5.2178 val_acc=0.0224 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 11/70: train_loss=2.1322 train_acc=0.3652 val_loss=5.1896 val_acc=0.0256 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 12/70: train_loss=2.0424 train_acc=0.3840 val_loss=6.2648 val_acc=0.0314 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 13/70: train_loss=1.9987 train_acc=0.3983 val_loss=6.5698 val_acc=0.0199 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 14/70: train_loss=1.9277 train_acc=0.4249 val_loss=5.7083 val_acc=0.0308 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 15/70: train_loss=1.8606 train_acc=0.4403 val_loss=5.6347 val_acc=0.0327 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 16/70: train_loss=1.7818 train_acc=0.4664 val_loss=6.1949 val_acc=0.0391 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 17/70: train_loss=1.7349 train_acc=0.4746 val_loss=6.2269 val_acc=0.0333 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 18/70: train_loss=1.6733 train_acc=0.4933 val_loss=7.1097 val_acc=0.0468 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 19/70: train_loss=1.6347 train_acc=0.5032 val_loss=6.1816 val_acc=0.0417 seconds=0.4
[CNN] 2.4 GHz/lovo fold=05 epoch 20/70: train_loss=1.5771 train_acc=0.5230 val_loss=6.2887 val_acc=0.0378 seconds=0.4
[CNN] early stopping at epoch 20; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__2_4ghz__lovo__ebl-session__s44__7b9bf2__fold-05.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__2_4ghz__lovo__ebl-session__s44__7b9bf2/training_curves__fold-05.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=06 validation_user=05 (entire user, deterministic rotation)
[CNN] 2.4 GHz/lovo fold=06 parameters=76020
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] 2.4 GHz/lovo fold=06 epoch 01/70: train_loss=3.9043 train_acc=0.0409 val_loss=3.9576 val_acc=0.0195 seconds=3.1
[CNN] 2.4 GHz/lovo fold=06 epoch 02/70: train_loss=3.6623 train_acc=0.0804 val_loss=3.7678 val_acc=0.0592 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 03/70: train_loss=3.3604 train_acc=0.1191 val_loss=3.7124 val_acc=0.0626 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 04/70: train_loss=3.1593 train_acc=0.1479 val_loss=3.7996 val_acc=0.0599 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 05/70: train_loss=2.9616 train_acc=0.1876 val_loss=4.0320 val_acc=0.0626 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 06/70: train_loss=2.7999 train_acc=0.2143 val_loss=4.3410 val_acc=0.0747 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 07/70: train_loss=2.6438 train_acc=0.2461 val_loss=4.4008 val_acc=0.0787 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 08/70: train_loss=2.5349 train_acc=0.2696 val_loss=4.5431 val_acc=0.0727 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 09/70: train_loss=2.4165 train_acc=0.2977 val_loss=5.1952 val_acc=0.0713 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 10/70: train_loss=2.3159 train_acc=0.3225 val_loss=4.6577 val_acc=0.0787 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 11/70: train_loss=2.2153 train_acc=0.3427 val_loss=4.8409 val_acc=0.0747 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 12/70: train_loss=2.1137 train_acc=0.3747 val_loss=5.0598 val_acc=0.0868 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 13/70: train_loss=2.0636 train_acc=0.3822 val_loss=5.6357 val_acc=0.0653 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 14/70: train_loss=1.9737 train_acc=0.4096 val_loss=5.5617 val_acc=0.0767 seconds=0.3
[CNN] 2.4 GHz/lovo fold=06 epoch 15/70: train_loss=1.8978 train_acc=0.4317 val_loss=5.3358 val_acc=0.0693 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 16/70: train_loss=1.8356 train_acc=0.4432 val_loss=5.6630 val_acc=0.0787 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 17/70: train_loss=1.7544 train_acc=0.4683 val_loss=5.6820 val_acc=0.0855 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 18/70: train_loss=1.7110 train_acc=0.4733 val_loss=6.0887 val_acc=0.0713 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 19/70: train_loss=1.6707 train_acc=0.4849 val_loss=6.0881 val_acc=0.0713 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 20/70: train_loss=1.6365 train_acc=0.4986 val_loss=6.2877 val_acc=0.0760 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 21/70: train_loss=1.5732 train_acc=0.5170 val_loss=6.2188 val_acc=0.0727 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 22/70: train_loss=1.5179 train_acc=0.5360 val_loss=6.5765 val_acc=0.0828 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 23/70: train_loss=1.5010 train_acc=0.5351 val_loss=6.3975 val_acc=0.0767 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 24/70: train_loss=1.4717 train_acc=0.5503 val_loss=6.6145 val_acc=0.0727 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 25/70: train_loss=1.4089 train_acc=0.5684 val_loss=7.2838 val_acc=0.0659 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 26/70: train_loss=1.4055 train_acc=0.5643 val_loss=7.2784 val_acc=0.0740 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 27/70: train_loss=1.3558 train_acc=0.5834 val_loss=6.8645 val_acc=0.0942 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 28/70: train_loss=1.3198 train_acc=0.5906 val_loss=7.4151 val_acc=0.0821 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 29/70: train_loss=1.3169 train_acc=0.5908 val_loss=6.8728 val_acc=0.0902 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 30/70: train_loss=1.2942 train_acc=0.6004 val_loss=7.1766 val_acc=0.0633 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 31/70: train_loss=1.2374 train_acc=0.6115 val_loss=7.3999 val_acc=0.0585 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 32/70: train_loss=1.2117 train_acc=0.6219 val_loss=7.3768 val_acc=0.0646 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 33/70: train_loss=1.1962 train_acc=0.6320 val_loss=7.5052 val_acc=0.0754 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 34/70: train_loss=1.1798 train_acc=0.6342 val_loss=7.7774 val_acc=0.0760 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 35/70: train_loss=1.1654 train_acc=0.6431 val_loss=7.7753 val_acc=0.0653 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 36/70: train_loss=1.1185 train_acc=0.6493 val_loss=7.8391 val_acc=0.0774 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 37/70: train_loss=1.1017 train_acc=0.6541 val_loss=7.6925 val_acc=0.0727 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 38/70: train_loss=1.0821 train_acc=0.6622 val_loss=7.6228 val_acc=0.0707 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 39/70: train_loss=1.0733 train_acc=0.6658 val_loss=9.3023 val_acc=0.0572 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 40/70: train_loss=1.0566 train_acc=0.6645 val_loss=8.2456 val_acc=0.0673 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 41/70: train_loss=1.0552 train_acc=0.6664 val_loss=8.2497 val_acc=0.0619 seconds=0.4
[CNN] 2.4 GHz/lovo fold=06 epoch 42/70: train_loss=0.9960 train_acc=0.6847 val_loss=9.0402 val_acc=0.0599 seconds=0.4
[CNN] early stopping at epoch 42; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__2_4ghz__lovo__ebl-session__s44__7b9bf2__fold-06.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__2_4ghz__lovo__ebl-session__s44__7b9bf2/training_curves__fold-06.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__2_4ghz__lovo__ebl-session__s44__7b9bf2.parquet
[results upsert] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/runs_folds.csv: 18 row(s)
[DL LOVO] seed=44 fold mean position_accuracy=0.0543 +/- 0.0184; pooled=0.0542
[DL GPU] run_id=dl__cnn__2_4ghz__lovo__ebl-session__s44__7b9bf2 peak_cuda_memory_bytes=514714624
[results upsert] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/runs.csv: 27 row(s)
[DL seeds] mean +/- std across seeds written to tables/seed_summary; LOVO uses each seed's fold mean and keeps within-seed fold std separate.

=== 5 GHz ===
[window arrays] cache path: /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/.cache/dataframes/preproc=norm-empty_baseline_scope-per_session/feat=win60-step0/window_arrays/5ghz
[window arrays cache hit] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/.cache/dataframes/preproc=norm-empty_baseline_scope-per_session/feat=win60-step0/window_arrays/5ghz
[window arrays] 5 GHz: shape=(14478, 10, 56, 60), dtype=float16
[window arrays] 5 GHz anchors: ['esp_11', 'esp_12', 'esp_13', 'esp_14', 'esp_15', 'esp_16', 'esp_17', 'esp_18', 'esp_19', 'esp_20']
5 GHz: anchors=10, subcarriers=56, windows=14478
WINDOW IDENTITY PASS: 5 GHz (14478 windows)
[trial filter] split=lovo trials=['01'] kept=9695/14478
[trial filter] split=lovo trials=['01'] kept=9695/9695
[protocol] split=lovo fold=01 trials_used=['01'] n_train=8067 n_test=1628 users=['01', '02', '03', '04', '05', '06'] train_users=['02', '03', '04', '05', '06'] test_users=['01']
[protocol] split=lovo fold=02 trials_used=['01'] n_train=8097 n_test=1598 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '03', '04', '05', '06'] test_users=['02']
[protocol] split=lovo fold=03 trials_used=['01'] n_train=8081 n_test=1614 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '04', '05', '06'] test_users=['03']
[protocol] split=lovo fold=04 trials_used=['01'] n_train=8060 n_test=1635 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '05', '06'] test_users=['04']
[protocol] split=lovo fold=05 trials_used=['01'] n_train=8082 n_test=1613 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '06'] test_users=['05']
[protocol] split=lovo fold=06 trials_used=['01'] n_train=8088 n_test=1607 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05'] test_users=['06']
[trial filter] split=lovo trials=['01'] kept=9695/14478
[trial filter] split=lovo trials=['01'] kept=9695/9695
[protocol] split=lovo fold=01 trials_used=['01'] n_train=8067 n_test=1628 users=['01', '02', '03', '04', '05', '06'] train_users=['02', '03', '04', '05', '06'] test_users=['01']
[protocol] split=lovo fold=02 trials_used=['01'] n_train=8097 n_test=1598 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '03', '04', '05', '06'] test_users=['02']
[protocol] split=lovo fold=03 trials_used=['01'] n_train=8081 n_test=1614 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '04', '05', '06'] test_users=['03']
[protocol] split=lovo fold=04 trials_used=['01'] n_train=8060 n_test=1635 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '05', '06'] test_users=['04']
[protocol] split=lovo fold=05 trials_used=['01'] n_train=8082 n_test=1613 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '06'] test_users=['05']
[protocol] split=lovo fold=06 trials_used=['01'] n_train=8088 n_test=1607 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05'] test_users=['06']
SPLIT IDENTITY PASS: 5 GHz/lovo fold=1 train=8067 test=1628
SPLIT IDENTITY PASS: 5 GHz/lovo fold=2 train=8097 test=1598
SPLIT IDENTITY PASS: 5 GHz/lovo fold=3 train=8081 test=1614
SPLIT IDENTITY PASS: 5 GHz/lovo fold=4 train=8060 test=1635
SPLIT IDENTITY PASS: 5 GHz/lovo fold=5 train=8082 test=1613
SPLIT IDENTITY PASS: 5 GHz/lovo fold=6 train=8088 test=1607
Seeds: random=42, numpy=42, torch=42
[trial filter] split=lovo trials=['01'] kept=9695/14478
[trial filter] split=lovo trials=['01'] kept=9695/9695
[protocol] split=lovo fold=01 trials_used=['01'] n_train=8067 n_test=1628 users=['01', '02', '03', '04', '05', '06'] train_users=['02', '03', '04', '05', '06'] test_users=['01']
[protocol] split=lovo fold=02 trials_used=['01'] n_train=8097 n_test=1598 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '03', '04', '05', '06'] test_users=['02']
[protocol] split=lovo fold=03 trials_used=['01'] n_train=8081 n_test=1614 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '04', '05', '06'] test_users=['03']
[protocol] split=lovo fold=04 trials_used=['01'] n_train=8060 n_test=1635 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '05', '06'] test_users=['04']
[protocol] split=lovo fold=05 trials_used=['01'] n_train=8082 n_test=1613 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '06'] test_users=['05']
[protocol] split=lovo fold=06 trials_used=['01'] n_train=8088 n_test=1607 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05'] test_users=['06']
[DL LOVO] held_out_user=01 validation_user=06 (entire user, deterministic rotation)
[CNN] 5 GHz/lovo fold=01 parameters=76308
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] 5 GHz/lovo fold=01 epoch 01/70: train_loss=3.8317 train_acc=0.0585 val_loss=3.7974 val_acc=0.0753 seconds=3.3
[CNN] 5 GHz/lovo fold=01 epoch 02/70: train_loss=3.3451 train_acc=0.1223 val_loss=3.8774 val_acc=0.0672 seconds=0.6
[CNN] 5 GHz/lovo fold=01 epoch 03/70: train_loss=2.9489 train_acc=0.1831 val_loss=4.3238 val_acc=0.1052 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 04/70: train_loss=2.7383 train_acc=0.2087 val_loss=4.6150 val_acc=0.1039 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 05/70: train_loss=2.5747 train_acc=0.2467 val_loss=5.1498 val_acc=0.0859 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 06/70: train_loss=2.4547 train_acc=0.2762 val_loss=5.0780 val_acc=0.0927 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 07/70: train_loss=2.3393 train_acc=0.3006 val_loss=5.3094 val_acc=0.0927 seconds=0.4
[CNN] 5 GHz/lovo fold=01 epoch 08/70: train_loss=2.2628 train_acc=0.3184 val_loss=5.4146 val_acc=0.1045 seconds=0.4
[CNN] 5 GHz/lovo fold=01 epoch 09/70: train_loss=2.1788 train_acc=0.3387 val_loss=5.4782 val_acc=0.1008 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 10/70: train_loss=2.1146 train_acc=0.3559 val_loss=5.7329 val_acc=0.0989 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 11/70: train_loss=2.0629 train_acc=0.3619 val_loss=5.7374 val_acc=0.1039 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 12/70: train_loss=1.9852 train_acc=0.3820 val_loss=5.5033 val_acc=0.1052 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 13/70: train_loss=1.9381 train_acc=0.3988 val_loss=6.1613 val_acc=0.0859 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 14/70: train_loss=1.8668 train_acc=0.4184 val_loss=5.8967 val_acc=0.1077 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 15/70: train_loss=1.8333 train_acc=0.4232 val_loss=6.2192 val_acc=0.1039 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 16/70: train_loss=1.7860 train_acc=0.4353 val_loss=6.5807 val_acc=0.1045 seconds=0.4
[CNN] 5 GHz/lovo fold=01 epoch 17/70: train_loss=1.7689 train_acc=0.4444 val_loss=6.4138 val_acc=0.1027 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 18/70: train_loss=1.7165 train_acc=0.4601 val_loss=6.3599 val_acc=0.1014 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 19/70: train_loss=1.6687 train_acc=0.4749 val_loss=6.5694 val_acc=0.1145 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 20/70: train_loss=1.6527 train_acc=0.4737 val_loss=7.1691 val_acc=0.0983 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 21/70: train_loss=1.6208 train_acc=0.4870 val_loss=7.2191 val_acc=0.0871 seconds=0.4
[CNN] 5 GHz/lovo fold=01 epoch 22/70: train_loss=1.5730 train_acc=0.5015 val_loss=6.5457 val_acc=0.1176 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 23/70: train_loss=1.5610 train_acc=0.5028 val_loss=7.2030 val_acc=0.1058 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 24/70: train_loss=1.5291 train_acc=0.5118 val_loss=7.3411 val_acc=0.1058 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 25/70: train_loss=1.4932 train_acc=0.5274 val_loss=7.2827 val_acc=0.1164 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 26/70: train_loss=1.4657 train_acc=0.5322 val_loss=7.8648 val_acc=0.0940 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 27/70: train_loss=1.4592 train_acc=0.5274 val_loss=7.7160 val_acc=0.1108 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 28/70: train_loss=1.4355 train_acc=0.5389 val_loss=7.0325 val_acc=0.1182 seconds=0.4
[CNN] 5 GHz/lovo fold=01 epoch 29/70: train_loss=1.4096 train_acc=0.5412 val_loss=8.0108 val_acc=0.1077 seconds=0.4
[CNN] 5 GHz/lovo fold=01 epoch 30/70: train_loss=1.3925 train_acc=0.5491 val_loss=8.1347 val_acc=0.1039 seconds=0.4
[CNN] 5 GHz/lovo fold=01 epoch 31/70: train_loss=1.3844 train_acc=0.5557 val_loss=8.3427 val_acc=0.1027 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 32/70: train_loss=1.3709 train_acc=0.5613 val_loss=7.5897 val_acc=0.1133 seconds=0.4
[CNN] 5 GHz/lovo fold=01 epoch 33/70: train_loss=1.3246 train_acc=0.5717 val_loss=8.0413 val_acc=0.1064 seconds=0.4
[CNN] 5 GHz/lovo fold=01 epoch 34/70: train_loss=1.2957 train_acc=0.5839 val_loss=8.5219 val_acc=0.1089 seconds=0.4
[CNN] 5 GHz/lovo fold=01 epoch 35/70: train_loss=1.2809 train_acc=0.5845 val_loss=8.2731 val_acc=0.1126 seconds=0.4
[CNN] 5 GHz/lovo fold=01 epoch 36/70: train_loss=1.2811 train_acc=0.5839 val_loss=8.7669 val_acc=0.1014 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 37/70: train_loss=1.2846 train_acc=0.5904 val_loss=8.4805 val_acc=0.1077 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 38/70: train_loss=1.2392 train_acc=0.5977 val_loss=9.2572 val_acc=0.1014 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 39/70: train_loss=1.2061 train_acc=0.6101 val_loss=8.7588 val_acc=0.1114 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 40/70: train_loss=1.2261 train_acc=0.6080 val_loss=8.5380 val_acc=0.1189 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 41/70: train_loss=1.1960 train_acc=0.6085 val_loss=8.7047 val_acc=0.1114 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 42/70: train_loss=1.1885 train_acc=0.6124 val_loss=9.3466 val_acc=0.0989 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 43/70: train_loss=1.1852 train_acc=0.6141 val_loss=8.7206 val_acc=0.1095 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 44/70: train_loss=1.1392 train_acc=0.6268 val_loss=8.8165 val_acc=0.1133 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 45/70: train_loss=1.1546 train_acc=0.6246 val_loss=9.6177 val_acc=0.1014 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 46/70: train_loss=1.1526 train_acc=0.6198 val_loss=10.0238 val_acc=0.1108 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 47/70: train_loss=1.1419 train_acc=0.6331 val_loss=9.3900 val_acc=0.0983 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 48/70: train_loss=1.1177 train_acc=0.6320 val_loss=9.6476 val_acc=0.1133 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 49/70: train_loss=1.1065 train_acc=0.6337 val_loss=9.6063 val_acc=0.1083 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 50/70: train_loss=1.0955 train_acc=0.6432 val_loss=9.9098 val_acc=0.1133 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 51/70: train_loss=1.0657 train_acc=0.6463 val_loss=9.4163 val_acc=0.1164 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 52/70: train_loss=1.0682 train_acc=0.6440 val_loss=9.7375 val_acc=0.1027 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 53/70: train_loss=1.0495 train_acc=0.6500 val_loss=9.6399 val_acc=0.1176 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 54/70: train_loss=1.0531 train_acc=0.6511 val_loss=9.9551 val_acc=0.1114 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 55/70: train_loss=1.0286 train_acc=0.6649 val_loss=9.6645 val_acc=0.1064 seconds=0.5
[CNN] early stopping at epoch 55; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__5ghz__lovo__ebl-session__s42__9b1404__fold-01.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__5ghz__lovo__ebl-session__s42__9b1404/training_curves__fold-01.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=02 validation_user=01 (entire user, deterministic rotation)
[CNN] 5 GHz/lovo fold=02 parameters=76308
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] 5 GHz/lovo fold=02 epoch 01/70: train_loss=3.8105 train_acc=0.0592 val_loss=3.7774 val_acc=0.0700 seconds=3.5
[CNN] 5 GHz/lovo fold=02 epoch 02/70: train_loss=3.3040 train_acc=0.1183 val_loss=3.7975 val_acc=0.0614 seconds=0.5
[CNN] 5 GHz/lovo fold=02 epoch 03/70: train_loss=2.9217 train_acc=0.1778 val_loss=4.3588 val_acc=0.0688 seconds=0.5
[CNN] 5 GHz/lovo fold=02 epoch 04/70: train_loss=2.6731 train_acc=0.2186 val_loss=4.6752 val_acc=0.0700 seconds=0.5
[CNN] 5 GHz/lovo fold=02 epoch 05/70: train_loss=2.5105 train_acc=0.2639 val_loss=5.3048 val_acc=0.0762 seconds=0.5
[CNN] 5 GHz/lovo fold=02 epoch 06/70: train_loss=2.3642 train_acc=0.2960 val_loss=5.9286 val_acc=0.0639 seconds=0.5
[CNN] 5 GHz/lovo fold=02 epoch 07/70: train_loss=2.2354 train_acc=0.3303 val_loss=6.4724 val_acc=0.0491 seconds=0.5
[CNN] 5 GHz/lovo fold=02 epoch 08/70: train_loss=2.1345 train_acc=0.3449 val_loss=6.9880 val_acc=0.0651 seconds=0.5
[CNN] 5 GHz/lovo fold=02 epoch 09/70: train_loss=2.0266 train_acc=0.3790 val_loss=7.4595 val_acc=0.0676 seconds=0.5
[CNN] 5 GHz/lovo fold=02 epoch 10/70: train_loss=1.9562 train_acc=0.3948 val_loss=7.1005 val_acc=0.0700 seconds=0.5
[CNN] 5 GHz/lovo fold=02 epoch 11/70: train_loss=1.8836 train_acc=0.4205 val_loss=7.7360 val_acc=0.0645 seconds=0.5
[CNN] 5 GHz/lovo fold=02 epoch 12/70: train_loss=1.8115 train_acc=0.4386 val_loss=8.1550 val_acc=0.0663 seconds=0.5
[CNN] 5 GHz/lovo fold=02 epoch 13/70: train_loss=1.7559 train_acc=0.4495 val_loss=9.1187 val_acc=0.0620 seconds=0.5
[CNN] 5 GHz/lovo fold=02 epoch 14/70: train_loss=1.7031 train_acc=0.4770 val_loss=9.0685 val_acc=0.0608 seconds=0.5
[CNN] 5 GHz/lovo fold=02 epoch 15/70: train_loss=1.6427 train_acc=0.4945 val_loss=9.3355 val_acc=0.0602 seconds=0.5
[CNN] 5 GHz/lovo fold=02 epoch 16/70: train_loss=1.6277 train_acc=0.4976 val_loss=9.4330 val_acc=0.0639 seconds=0.5
[CNN] 5 GHz/lovo fold=02 epoch 17/70: train_loss=1.5607 train_acc=0.5100 val_loss=9.2404 val_acc=0.0620 seconds=0.5
[CNN] 5 GHz/lovo fold=02 epoch 18/70: train_loss=1.5110 train_acc=0.5253 val_loss=10.9365 val_acc=0.0614 seconds=0.5
[CNN] 5 GHz/lovo fold=02 epoch 19/70: train_loss=1.4930 train_acc=0.5214 val_loss=9.5173 val_acc=0.0676 seconds=0.5
[CNN] 5 GHz/lovo fold=02 epoch 20/70: train_loss=1.4603 train_acc=0.5372 val_loss=11.1820 val_acc=0.0608 seconds=0.5
[CNN] early stopping at epoch 20; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__5ghz__lovo__ebl-session__s42__9b1404__fold-02.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__5ghz__lovo__ebl-session__s42__9b1404/training_curves__fold-02.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=03 validation_user=02 (entire user, deterministic rotation)
[CNN] 5 GHz/lovo fold=03 parameters=76308
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] 5 GHz/lovo fold=03 epoch 01/70: train_loss=3.7778 train_acc=0.0688 val_loss=3.7651 val_acc=0.0419 seconds=3.4
[CNN] 5 GHz/lovo fold=03 epoch 02/70: train_loss=3.2476 train_acc=0.1313 val_loss=4.4454 val_acc=0.0463 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 03/70: train_loss=2.8800 train_acc=0.1866 val_loss=4.9680 val_acc=0.0313 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 04/70: train_loss=2.6698 train_acc=0.2329 val_loss=5.5460 val_acc=0.0388 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 05/70: train_loss=2.4800 train_acc=0.2695 val_loss=6.0945 val_acc=0.0332 seconds=0.4
[CNN] 5 GHz/lovo fold=03 epoch 06/70: train_loss=2.3431 train_acc=0.2979 val_loss=6.2676 val_acc=0.0332 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 07/70: train_loss=2.2195 train_acc=0.3247 val_loss=7.0726 val_acc=0.0350 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 08/70: train_loss=2.1088 train_acc=0.3589 val_loss=7.2887 val_acc=0.0401 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 09/70: train_loss=2.0495 train_acc=0.3702 val_loss=7.1214 val_acc=0.0338 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 10/70: train_loss=1.9446 train_acc=0.4014 val_loss=7.3435 val_acc=0.0357 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 11/70: train_loss=1.8750 train_acc=0.4149 val_loss=7.8758 val_acc=0.0407 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 12/70: train_loss=1.8243 train_acc=0.4297 val_loss=8.0981 val_acc=0.0432 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 13/70: train_loss=1.7546 train_acc=0.4523 val_loss=8.4054 val_acc=0.0407 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 14/70: train_loss=1.6607 train_acc=0.4806 val_loss=8.6046 val_acc=0.0444 seconds=0.4
[CNN] 5 GHz/lovo fold=03 epoch 15/70: train_loss=1.6243 train_acc=0.4901 val_loss=9.0715 val_acc=0.0432 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 16/70: train_loss=1.6015 train_acc=0.4954 val_loss=9.4872 val_acc=0.0488 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 17/70: train_loss=1.5432 train_acc=0.5109 val_loss=9.8733 val_acc=0.0482 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 18/70: train_loss=1.5051 train_acc=0.5220 val_loss=9.8632 val_acc=0.0476 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 19/70: train_loss=1.4635 train_acc=0.5399 val_loss=9.9638 val_acc=0.0463 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 20/70: train_loss=1.4149 train_acc=0.5542 val_loss=10.2781 val_acc=0.0513 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 21/70: train_loss=1.3927 train_acc=0.5573 val_loss=11.0877 val_acc=0.0482 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 22/70: train_loss=1.3486 train_acc=0.5744 val_loss=10.6459 val_acc=0.0476 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 23/70: train_loss=1.3057 train_acc=0.5846 val_loss=11.1647 val_acc=0.0488 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 24/70: train_loss=1.3285 train_acc=0.5696 val_loss=10.7499 val_acc=0.0594 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 25/70: train_loss=1.3023 train_acc=0.5809 val_loss=11.3283 val_acc=0.0538 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 26/70: train_loss=1.2453 train_acc=0.5991 val_loss=11.4012 val_acc=0.0501 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 27/70: train_loss=1.2071 train_acc=0.6114 val_loss=11.8309 val_acc=0.0538 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 28/70: train_loss=1.1858 train_acc=0.6185 val_loss=12.1843 val_acc=0.0501 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 29/70: train_loss=1.1458 train_acc=0.6293 val_loss=11.8883 val_acc=0.0576 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 30/70: train_loss=1.1359 train_acc=0.6358 val_loss=12.5801 val_acc=0.0519 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 31/70: train_loss=1.1390 train_acc=0.6333 val_loss=13.1430 val_acc=0.0551 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 32/70: train_loss=1.0945 train_acc=0.6516 val_loss=12.8044 val_acc=0.0551 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 33/70: train_loss=1.0871 train_acc=0.6509 val_loss=12.6925 val_acc=0.0526 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 34/70: train_loss=1.0638 train_acc=0.6614 val_loss=13.1045 val_acc=0.0526 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 35/70: train_loss=1.0594 train_acc=0.6599 val_loss=14.1781 val_acc=0.0507 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 36/70: train_loss=1.0185 train_acc=0.6682 val_loss=13.3135 val_acc=0.0551 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 37/70: train_loss=1.0110 train_acc=0.6716 val_loss=13.1559 val_acc=0.0563 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 38/70: train_loss=0.9917 train_acc=0.6781 val_loss=13.8037 val_acc=0.0532 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 39/70: train_loss=0.9849 train_acc=0.6875 val_loss=13.8858 val_acc=0.0563 seconds=0.5
[CNN] early stopping at epoch 39; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__5ghz__lovo__ebl-session__s42__9b1404__fold-03.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__5ghz__lovo__ebl-session__s42__9b1404/training_curves__fold-03.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=04 validation_user=03 (entire user, deterministic rotation)
[CNN] 5 GHz/lovo fold=04 parameters=76308
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] 5 GHz/lovo fold=04 epoch 01/70: train_loss=3.8049 train_acc=0.0593 val_loss=3.7518 val_acc=0.0471 seconds=3.0
[CNN] 5 GHz/lovo fold=04 epoch 02/70: train_loss=3.3480 train_acc=0.1190 val_loss=3.6994 val_acc=0.0991 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 03/70: train_loss=3.0231 train_acc=0.1683 val_loss=4.1220 val_acc=0.1004 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 04/70: train_loss=2.8016 train_acc=0.2082 val_loss=4.5818 val_acc=0.0948 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 05/70: train_loss=2.6152 train_acc=0.2476 val_loss=4.6269 val_acc=0.1041 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 06/70: train_loss=2.4994 train_acc=0.2794 val_loss=4.8927 val_acc=0.0898 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 07/70: train_loss=2.3920 train_acc=0.3019 val_loss=4.8231 val_acc=0.1004 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 08/70: train_loss=2.2952 train_acc=0.3236 val_loss=4.9786 val_acc=0.0929 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 09/70: train_loss=2.2044 train_acc=0.3453 val_loss=5.2118 val_acc=0.0948 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 10/70: train_loss=2.1080 train_acc=0.3712 val_loss=5.1653 val_acc=0.1022 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 11/70: train_loss=2.0331 train_acc=0.3919 val_loss=5.6491 val_acc=0.0929 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 12/70: train_loss=1.9763 train_acc=0.4044 val_loss=5.5737 val_acc=0.0948 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 13/70: train_loss=1.9144 train_acc=0.4223 val_loss=5.3217 val_acc=0.1047 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 14/70: train_loss=1.8610 train_acc=0.4401 val_loss=5.5943 val_acc=0.1128 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 15/70: train_loss=1.8015 train_acc=0.4575 val_loss=5.5008 val_acc=0.1041 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 16/70: train_loss=1.7568 train_acc=0.4663 val_loss=5.9283 val_acc=0.1016 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 17/70: train_loss=1.7286 train_acc=0.4685 val_loss=5.8276 val_acc=0.1053 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 18/70: train_loss=1.6625 train_acc=0.4918 val_loss=5.9210 val_acc=0.1152 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 19/70: train_loss=1.6270 train_acc=0.4936 val_loss=5.7716 val_acc=0.1190 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 20/70: train_loss=1.5923 train_acc=0.5102 val_loss=6.0214 val_acc=0.1245 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 21/70: train_loss=1.5464 train_acc=0.5164 val_loss=6.1325 val_acc=0.1140 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 22/70: train_loss=1.5325 train_acc=0.5301 val_loss=6.0952 val_acc=0.1239 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 23/70: train_loss=1.4786 train_acc=0.5385 val_loss=6.3961 val_acc=0.1121 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 24/70: train_loss=1.4646 train_acc=0.5419 val_loss=6.3795 val_acc=0.1264 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 25/70: train_loss=1.4147 train_acc=0.5603 val_loss=6.5121 val_acc=0.1233 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 26/70: train_loss=1.4093 train_acc=0.5551 val_loss=6.6625 val_acc=0.1171 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 27/70: train_loss=1.3838 train_acc=0.5700 val_loss=6.5157 val_acc=0.1252 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 28/70: train_loss=1.3575 train_acc=0.5763 val_loss=6.7922 val_acc=0.1252 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 29/70: train_loss=1.3236 train_acc=0.5835 val_loss=6.6347 val_acc=0.1121 seconds=0.6
[CNN] 5 GHz/lovo fold=04 epoch 30/70: train_loss=1.3199 train_acc=0.5852 val_loss=6.6851 val_acc=0.1276 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 31/70: train_loss=1.2937 train_acc=0.5895 val_loss=6.7916 val_acc=0.1270 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 32/70: train_loss=1.2736 train_acc=0.5954 val_loss=7.0133 val_acc=0.1283 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 33/70: train_loss=1.2424 train_acc=0.6083 val_loss=6.7634 val_acc=0.1233 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 34/70: train_loss=1.2287 train_acc=0.6021 val_loss=7.1797 val_acc=0.1276 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 35/70: train_loss=1.2020 train_acc=0.6198 val_loss=7.1661 val_acc=0.1314 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 36/70: train_loss=1.1856 train_acc=0.6235 val_loss=7.3452 val_acc=0.1252 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 37/70: train_loss=1.2073 train_acc=0.6111 val_loss=6.9692 val_acc=0.1301 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 38/70: train_loss=1.1551 train_acc=0.6244 val_loss=7.4781 val_acc=0.1344 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 39/70: train_loss=1.1842 train_acc=0.6218 val_loss=7.5994 val_acc=0.1252 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 40/70: train_loss=1.1511 train_acc=0.6337 val_loss=7.3506 val_acc=0.1283 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 41/70: train_loss=1.1162 train_acc=0.6454 val_loss=7.5526 val_acc=0.1258 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 42/70: train_loss=1.1032 train_acc=0.6464 val_loss=7.4937 val_acc=0.1326 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 43/70: train_loss=1.0727 train_acc=0.6488 val_loss=7.6516 val_acc=0.1332 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 44/70: train_loss=1.0606 train_acc=0.6579 val_loss=8.6129 val_acc=0.1351 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 45/70: train_loss=1.0926 train_acc=0.6514 val_loss=8.0322 val_acc=0.1314 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 46/70: train_loss=1.0340 train_acc=0.6665 val_loss=7.8909 val_acc=0.1326 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 47/70: train_loss=1.0151 train_acc=0.6665 val_loss=8.0987 val_acc=0.1375 seconds=0.4
[CNN] 5 GHz/lovo fold=04 epoch 48/70: train_loss=1.0309 train_acc=0.6603 val_loss=8.2036 val_acc=0.1301 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 49/70: train_loss=1.0253 train_acc=0.6691 val_loss=8.2621 val_acc=0.1214 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 50/70: train_loss=1.0231 train_acc=0.6660 val_loss=8.1605 val_acc=0.1388 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 51/70: train_loss=0.9877 train_acc=0.6871 val_loss=8.2164 val_acc=0.1369 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 52/70: train_loss=0.9808 train_acc=0.6852 val_loss=8.6789 val_acc=0.1388 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 53/70: train_loss=0.9566 train_acc=0.6894 val_loss=8.5012 val_acc=0.1363 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 54/70: train_loss=0.9306 train_acc=0.6970 val_loss=8.7746 val_acc=0.1419 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 55/70: train_loss=0.9415 train_acc=0.6913 val_loss=8.9678 val_acc=0.1369 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 56/70: train_loss=0.9217 train_acc=0.7004 val_loss=9.0481 val_acc=0.1382 seconds=0.4
[CNN] 5 GHz/lovo fold=04 epoch 57/70: train_loss=0.9215 train_acc=0.6953 val_loss=9.4893 val_acc=0.1307 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 58/70: train_loss=0.9146 train_acc=0.7023 val_loss=9.0101 val_acc=0.1314 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 59/70: train_loss=0.8822 train_acc=0.7124 val_loss=9.2789 val_acc=0.1425 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 60/70: train_loss=0.8919 train_acc=0.7113 val_loss=8.9734 val_acc=0.1369 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 61/70: train_loss=0.8853 train_acc=0.7085 val_loss=9.1760 val_acc=0.1375 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 62/70: train_loss=0.8671 train_acc=0.7189 val_loss=9.1284 val_acc=0.1394 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 63/70: train_loss=0.8776 train_acc=0.7146 val_loss=9.3519 val_acc=0.1338 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 64/70: train_loss=0.8494 train_acc=0.7212 val_loss=9.3926 val_acc=0.1338 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 65/70: train_loss=0.8646 train_acc=0.7191 val_loss=9.1134 val_acc=0.1338 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 66/70: train_loss=0.8422 train_acc=0.7242 val_loss=10.0304 val_acc=0.1344 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 67/70: train_loss=0.8515 train_acc=0.7223 val_loss=9.7303 val_acc=0.1406 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 68/70: train_loss=0.8281 train_acc=0.7262 val_loss=9.9022 val_acc=0.1301 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 69/70: train_loss=0.8296 train_acc=0.7338 val_loss=9.8185 val_acc=0.1344 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 70/70: train_loss=0.8188 train_acc=0.7263 val_loss=9.6582 val_acc=0.1264 seconds=0.5

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__5ghz__lovo__ebl-session__s42__9b1404__fold-04.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__5ghz__lovo__ebl-session__s42__9b1404/training_curves__fold-04.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=05 validation_user=04 (entire user, deterministic rotation)
[CNN] 5 GHz/lovo fold=05 parameters=76308
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] 5 GHz/lovo fold=05 epoch 01/70: train_loss=3.7725 train_acc=0.0594 val_loss=3.8561 val_acc=0.0569 seconds=3.3
[CNN] 5 GHz/lovo fold=05 epoch 02/70: train_loss=3.2368 train_acc=0.1156 val_loss=3.9606 val_acc=0.0807 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 03/70: train_loss=2.9693 train_acc=0.1663 val_loss=3.9477 val_acc=0.0887 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 04/70: train_loss=2.8004 train_acc=0.1922 val_loss=4.2468 val_acc=0.0942 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 05/70: train_loss=2.6436 train_acc=0.2255 val_loss=4.1494 val_acc=0.1034 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 06/70: train_loss=2.5055 train_acc=0.2691 val_loss=4.6157 val_acc=0.0875 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 07/70: train_loss=2.4191 train_acc=0.2839 val_loss=4.7004 val_acc=0.0911 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 08/70: train_loss=2.3235 train_acc=0.3048 val_loss=4.7035 val_acc=0.0942 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 09/70: train_loss=2.2273 train_acc=0.3309 val_loss=4.7435 val_acc=0.0942 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 10/70: train_loss=2.1749 train_acc=0.3364 val_loss=4.7910 val_acc=0.0936 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 11/70: train_loss=2.1084 train_acc=0.3631 val_loss=5.0476 val_acc=0.0942 seconds=0.4
[CNN] 5 GHz/lovo fold=05 epoch 12/70: train_loss=2.0374 train_acc=0.3757 val_loss=5.0245 val_acc=0.0936 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 13/70: train_loss=1.9873 train_acc=0.3934 val_loss=5.0014 val_acc=0.0966 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 14/70: train_loss=1.9038 train_acc=0.4163 val_loss=5.1879 val_acc=0.0795 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 15/70: train_loss=1.8711 train_acc=0.4236 val_loss=5.3832 val_acc=0.0881 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 16/70: train_loss=1.8142 train_acc=0.4456 val_loss=5.6427 val_acc=0.0905 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 17/70: train_loss=1.7629 train_acc=0.4577 val_loss=5.5989 val_acc=0.0875 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 18/70: train_loss=1.7390 train_acc=0.4647 val_loss=5.3838 val_acc=0.0777 seconds=0.4
[CNN] 5 GHz/lovo fold=05 epoch 19/70: train_loss=1.7004 train_acc=0.4731 val_loss=5.6784 val_acc=0.0887 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 20/70: train_loss=1.6642 train_acc=0.4832 val_loss=5.7014 val_acc=0.0881 seconds=0.5
[CNN] early stopping at epoch 20; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__5ghz__lovo__ebl-session__s42__9b1404__fold-05.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__5ghz__lovo__ebl-session__s42__9b1404/training_curves__fold-05.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=06 validation_user=05 (entire user, deterministic rotation)
[CNN] 5 GHz/lovo fold=06 parameters=76308
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] 5 GHz/lovo fold=06 epoch 01/70: train_loss=3.7746 train_acc=0.0652 val_loss=3.9564 val_acc=0.0508 seconds=3.4
[CNN] 5 GHz/lovo fold=06 epoch 02/70: train_loss=3.2215 train_acc=0.1285 val_loss=4.2398 val_acc=0.0862 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 03/70: train_loss=2.9147 train_acc=0.1768 val_loss=4.1735 val_acc=0.0992 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 04/70: train_loss=2.7328 train_acc=0.2142 val_loss=4.0751 val_acc=0.0973 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 05/70: train_loss=2.6006 train_acc=0.2360 val_loss=4.4744 val_acc=0.1004 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 06/70: train_loss=2.4781 train_acc=0.2624 val_loss=4.5140 val_acc=0.0899 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 07/70: train_loss=2.3864 train_acc=0.2837 val_loss=4.5740 val_acc=0.0887 seconds=0.4
[CNN] 5 GHz/lovo fold=06 epoch 08/70: train_loss=2.2970 train_acc=0.3042 val_loss=4.5382 val_acc=0.0955 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 09/70: train_loss=2.2275 train_acc=0.3246 val_loss=4.6667 val_acc=0.0936 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 10/70: train_loss=2.1424 train_acc=0.3515 val_loss=4.9734 val_acc=0.0942 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 11/70: train_loss=2.0810 train_acc=0.3622 val_loss=4.6081 val_acc=0.0862 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 12/70: train_loss=2.0313 train_acc=0.3799 val_loss=5.0295 val_acc=0.0800 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 13/70: train_loss=1.9722 train_acc=0.3915 val_loss=5.0938 val_acc=0.0794 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 14/70: train_loss=1.9407 train_acc=0.3986 val_loss=5.5413 val_acc=0.0911 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 15/70: train_loss=1.8907 train_acc=0.4128 val_loss=5.4731 val_acc=0.0787 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 16/70: train_loss=1.8551 train_acc=0.4208 val_loss=5.2466 val_acc=0.0837 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 17/70: train_loss=1.7984 train_acc=0.4429 val_loss=5.6542 val_acc=0.0818 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 18/70: train_loss=1.7729 train_acc=0.4446 val_loss=5.5846 val_acc=0.0806 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 19/70: train_loss=1.7458 train_acc=0.4522 val_loss=5.3991 val_acc=0.0880 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 20/70: train_loss=1.6960 train_acc=0.4744 val_loss=6.0603 val_acc=0.0843 seconds=0.5
[CNN] early stopping at epoch 20; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__5ghz__lovo__ebl-session__s42__9b1404__fold-06.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__5ghz__lovo__ebl-session__s42__9b1404/training_curves__fold-06.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__5ghz__lovo__ebl-session__s42__9b1404.parquet
[results upsert] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/runs_folds.csv: 24 row(s)
[DL LOVO] seed=42 fold mean position_accuracy=0.0829 +/- 0.0266; pooled=0.0830
[DL GPU] run_id=dl__cnn__5ghz__lovo__ebl-session__s42__9b1404 peak_cuda_memory_bytes=579083264
[results upsert] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/runs.csv: 28 row(s)
Seeds: random=43, numpy=43, torch=43
[trial filter] split=lovo trials=['01'] kept=9695/14478
[trial filter] split=lovo trials=['01'] kept=9695/9695
[protocol] split=lovo fold=01 trials_used=['01'] n_train=8067 n_test=1628 users=['01', '02', '03', '04', '05', '06'] train_users=['02', '03', '04', '05', '06'] test_users=['01']
[protocol] split=lovo fold=02 trials_used=['01'] n_train=8097 n_test=1598 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '03', '04', '05', '06'] test_users=['02']
[protocol] split=lovo fold=03 trials_used=['01'] n_train=8081 n_test=1614 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '04', '05', '06'] test_users=['03']
[protocol] split=lovo fold=04 trials_used=['01'] n_train=8060 n_test=1635 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '05', '06'] test_users=['04']
[protocol] split=lovo fold=05 trials_used=['01'] n_train=8082 n_test=1613 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '06'] test_users=['05']
[protocol] split=lovo fold=06 trials_used=['01'] n_train=8088 n_test=1607 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05'] test_users=['06']
[DL LOVO] held_out_user=01 validation_user=06 (entire user, deterministic rotation)
[CNN] 5 GHz/lovo fold=01 parameters=76308
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] 5 GHz/lovo fold=01 epoch 01/70: train_loss=3.8421 train_acc=0.0599 val_loss=3.7965 val_acc=0.0890 seconds=2.9
[CNN] 5 GHz/lovo fold=01 epoch 02/70: train_loss=3.3802 train_acc=0.1184 val_loss=3.6691 val_acc=0.0915 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 03/70: train_loss=2.9952 train_acc=0.1763 val_loss=4.4131 val_acc=0.0734 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 04/70: train_loss=2.7595 train_acc=0.2115 val_loss=4.4204 val_acc=0.0921 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 05/70: train_loss=2.5777 train_acc=0.2525 val_loss=4.8199 val_acc=0.0977 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 06/70: train_loss=2.4525 train_acc=0.2805 val_loss=5.1106 val_acc=0.0933 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 07/70: train_loss=2.3542 train_acc=0.2988 val_loss=5.5303 val_acc=0.0747 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 08/70: train_loss=2.2530 train_acc=0.3229 val_loss=5.2844 val_acc=0.0859 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 09/70: train_loss=2.1726 train_acc=0.3488 val_loss=5.6353 val_acc=0.0902 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 10/70: train_loss=2.1134 train_acc=0.3594 val_loss=5.9880 val_acc=0.0871 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 11/70: train_loss=2.0287 train_acc=0.3859 val_loss=5.8978 val_acc=0.0958 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 12/70: train_loss=1.9675 train_acc=0.4040 val_loss=6.1979 val_acc=0.0703 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 13/70: train_loss=1.9247 train_acc=0.4147 val_loss=6.3787 val_acc=0.0946 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 14/70: train_loss=1.8610 train_acc=0.4276 val_loss=6.7588 val_acc=0.0653 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 15/70: train_loss=1.8070 train_acc=0.4450 val_loss=6.1640 val_acc=0.0933 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 16/70: train_loss=1.7605 train_acc=0.4553 val_loss=6.3196 val_acc=0.0965 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 17/70: train_loss=1.7290 train_acc=0.4562 val_loss=6.5258 val_acc=0.0952 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 18/70: train_loss=1.6660 train_acc=0.4782 val_loss=6.5530 val_acc=0.0846 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 19/70: train_loss=1.6489 train_acc=0.4887 val_loss=7.1581 val_acc=0.0784 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 20/70: train_loss=1.6203 train_acc=0.4985 val_loss=6.9699 val_acc=0.0946 seconds=0.5
[CNN] early stopping at epoch 20; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__5ghz__lovo__ebl-session__s43__a89b5d__fold-01.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__5ghz__lovo__ebl-session__s43__a89b5d/training_curves__fold-01.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=02 validation_user=01 (entire user, deterministic rotation)
[CNN] 5 GHz/lovo fold=02 parameters=76308
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] 5 GHz/lovo fold=02 epoch 01/70: train_loss=3.7871 train_acc=0.0677 val_loss=3.7652 val_acc=0.0866 seconds=3.2
[CNN] 5 GHz/lovo fold=02 epoch 02/70: train_loss=3.3171 train_acc=0.1297 val_loss=4.0922 val_acc=0.0608 seconds=0.5
[CNN] 5 GHz/lovo fold=02 epoch 03/70: train_loss=2.9662 train_acc=0.1733 val_loss=4.6814 val_acc=0.0645 seconds=0.5
[CNN] 5 GHz/lovo fold=02 epoch 04/70: train_loss=2.6731 train_acc=0.2343 val_loss=5.6568 val_acc=0.0780 seconds=0.5
[CNN] 5 GHz/lovo fold=02 epoch 05/70: train_loss=2.4905 train_acc=0.2756 val_loss=6.3904 val_acc=0.0676 seconds=0.5
[CNN] 5 GHz/lovo fold=02 epoch 06/70: train_loss=2.3350 train_acc=0.3075 val_loss=7.2907 val_acc=0.0614 seconds=0.5
[CNN] 5 GHz/lovo fold=02 epoch 07/70: train_loss=2.2281 train_acc=0.3314 val_loss=6.6834 val_acc=0.0682 seconds=0.5
[CNN] 5 GHz/lovo fold=02 epoch 08/70: train_loss=2.1356 train_acc=0.3603 val_loss=7.6171 val_acc=0.0541 seconds=0.5
[CNN] 5 GHz/lovo fold=02 epoch 09/70: train_loss=2.0625 train_acc=0.3707 val_loss=7.8340 val_acc=0.0657 seconds=0.5
[CNN] 5 GHz/lovo fold=02 epoch 10/70: train_loss=1.9709 train_acc=0.4007 val_loss=8.5407 val_acc=0.0608 seconds=0.5
[CNN] 5 GHz/lovo fold=02 epoch 11/70: train_loss=1.8790 train_acc=0.4263 val_loss=8.5264 val_acc=0.0657 seconds=0.5
[CNN] 5 GHz/lovo fold=02 epoch 12/70: train_loss=1.8227 train_acc=0.4365 val_loss=7.9430 val_acc=0.0663 seconds=0.5
[CNN] 5 GHz/lovo fold=02 epoch 13/70: train_loss=1.7436 train_acc=0.4545 val_loss=8.8800 val_acc=0.0584 seconds=0.4
[CNN] 5 GHz/lovo fold=02 epoch 14/70: train_loss=1.7124 train_acc=0.4755 val_loss=9.3575 val_acc=0.0590 seconds=0.5
[CNN] 5 GHz/lovo fold=02 epoch 15/70: train_loss=1.6416 train_acc=0.4910 val_loss=9.1479 val_acc=0.0620 seconds=0.5
[CNN] 5 GHz/lovo fold=02 epoch 16/70: train_loss=1.5971 train_acc=0.5039 val_loss=9.1943 val_acc=0.0608 seconds=0.5
[CNN] early stopping at epoch 16; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__5ghz__lovo__ebl-session__s43__a89b5d__fold-02.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__5ghz__lovo__ebl-session__s43__a89b5d/training_curves__fold-02.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=03 validation_user=02 (entire user, deterministic rotation)
[CNN] 5 GHz/lovo fold=03 parameters=76308
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] 5 GHz/lovo fold=03 epoch 01/70: train_loss=3.8033 train_acc=0.0722 val_loss=3.7674 val_acc=0.0476 seconds=2.8
[CNN] 5 GHz/lovo fold=03 epoch 02/70: train_loss=3.2638 train_acc=0.1285 val_loss=4.2662 val_acc=0.0526 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 03/70: train_loss=2.9079 train_acc=0.1865 val_loss=4.9996 val_acc=0.0519 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 04/70: train_loss=2.6846 train_acc=0.2269 val_loss=5.6339 val_acc=0.0557 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 05/70: train_loss=2.5267 train_acc=0.2585 val_loss=6.0342 val_acc=0.0538 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 06/70: train_loss=2.3964 train_acc=0.2909 val_loss=6.6322 val_acc=0.0463 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 07/70: train_loss=2.2589 train_acc=0.3187 val_loss=6.8349 val_acc=0.0469 seconds=0.6
[CNN] 5 GHz/lovo fold=03 epoch 08/70: train_loss=2.1560 train_acc=0.3508 val_loss=7.0716 val_acc=0.0432 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 09/70: train_loss=2.0620 train_acc=0.3731 val_loss=7.4840 val_acc=0.0463 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 10/70: train_loss=1.9738 train_acc=0.3921 val_loss=8.2661 val_acc=0.0432 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 11/70: train_loss=1.9048 train_acc=0.4193 val_loss=8.6019 val_acc=0.0419 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 12/70: train_loss=1.8403 train_acc=0.4361 val_loss=8.8834 val_acc=0.0457 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 13/70: train_loss=1.7637 train_acc=0.4569 val_loss=8.3444 val_acc=0.0532 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 14/70: train_loss=1.7038 train_acc=0.4668 val_loss=9.4107 val_acc=0.0438 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 15/70: train_loss=1.6711 train_acc=0.4879 val_loss=10.1977 val_acc=0.0463 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 16/70: train_loss=1.6239 train_acc=0.4941 val_loss=9.4665 val_acc=0.0532 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 17/70: train_loss=1.5553 train_acc=0.5178 val_loss=9.9073 val_acc=0.0463 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 18/70: train_loss=1.5050 train_acc=0.5322 val_loss=10.7352 val_acc=0.0419 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 19/70: train_loss=1.4732 train_acc=0.5396 val_loss=10.6661 val_acc=0.0607 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 20/70: train_loss=1.4274 train_acc=0.5588 val_loss=10.9190 val_acc=0.0463 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 21/70: train_loss=1.3956 train_acc=0.5639 val_loss=11.1057 val_acc=0.0494 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 22/70: train_loss=1.3527 train_acc=0.5752 val_loss=12.6501 val_acc=0.0382 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 23/70: train_loss=1.3264 train_acc=0.5829 val_loss=12.0101 val_acc=0.0469 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 24/70: train_loss=1.2759 train_acc=0.5922 val_loss=12.6223 val_acc=0.0438 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 25/70: train_loss=1.2507 train_acc=0.6068 val_loss=12.9673 val_acc=0.0438 seconds=0.4
[CNN] 5 GHz/lovo fold=03 epoch 26/70: train_loss=1.2523 train_acc=0.5980 val_loss=12.6176 val_acc=0.0526 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 27/70: train_loss=1.2053 train_acc=0.6202 val_loss=12.4881 val_acc=0.0501 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 28/70: train_loss=1.1953 train_acc=0.6192 val_loss=13.4722 val_acc=0.0401 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 29/70: train_loss=1.1532 train_acc=0.6329 val_loss=13.8686 val_acc=0.0438 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 30/70: train_loss=1.1400 train_acc=0.6377 val_loss=13.5162 val_acc=0.0469 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 31/70: train_loss=1.1301 train_acc=0.6341 val_loss=13.7997 val_acc=0.0538 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 32/70: train_loss=1.0846 train_acc=0.6549 val_loss=14.9997 val_acc=0.0413 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 33/70: train_loss=1.0799 train_acc=0.6540 val_loss=14.6045 val_acc=0.0394 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 34/70: train_loss=1.0415 train_acc=0.6645 val_loss=14.6085 val_acc=0.0438 seconds=0.5
[CNN] early stopping at epoch 34; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__5ghz__lovo__ebl-session__s43__a89b5d__fold-03.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__5ghz__lovo__ebl-session__s43__a89b5d/training_curves__fold-03.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=04 validation_user=03 (entire user, deterministic rotation)
[CNN] 5 GHz/lovo fold=04 parameters=76308
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] 5 GHz/lovo fold=04 epoch 01/70: train_loss=3.8165 train_acc=0.0673 val_loss=3.8031 val_acc=0.0440 seconds=3.0
[CNN] 5 GHz/lovo fold=04 epoch 02/70: train_loss=3.3479 train_acc=0.1165 val_loss=3.8287 val_acc=0.0905 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 03/70: train_loss=3.0257 train_acc=0.1617 val_loss=4.2572 val_acc=0.0843 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 04/70: train_loss=2.8016 train_acc=0.2051 val_loss=4.1308 val_acc=0.1097 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 05/70: train_loss=2.6489 train_acc=0.2370 val_loss=4.6105 val_acc=0.0923 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 06/70: train_loss=2.5121 train_acc=0.2657 val_loss=4.4769 val_acc=0.1035 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 07/70: train_loss=2.3835 train_acc=0.2937 val_loss=4.9332 val_acc=0.0991 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 08/70: train_loss=2.2839 train_acc=0.3202 val_loss=5.1950 val_acc=0.1084 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 09/70: train_loss=2.2116 train_acc=0.3377 val_loss=4.9666 val_acc=0.1128 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 10/70: train_loss=2.1335 train_acc=0.3571 val_loss=5.0248 val_acc=0.1053 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 11/70: train_loss=2.0458 train_acc=0.3791 val_loss=5.3559 val_acc=0.1115 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 12/70: train_loss=1.9790 train_acc=0.3967 val_loss=5.4397 val_acc=0.1227 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 13/70: train_loss=1.9622 train_acc=0.4002 val_loss=5.5717 val_acc=0.1072 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 14/70: train_loss=1.8656 train_acc=0.4249 val_loss=5.4410 val_acc=0.1078 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 15/70: train_loss=1.8028 train_acc=0.4435 val_loss=5.8132 val_acc=0.1171 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 16/70: train_loss=1.7684 train_acc=0.4514 val_loss=5.4679 val_acc=0.1214 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 17/70: train_loss=1.7526 train_acc=0.4559 val_loss=5.7487 val_acc=0.1183 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 18/70: train_loss=1.6990 train_acc=0.4732 val_loss=6.0750 val_acc=0.1196 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 19/70: train_loss=1.6469 train_acc=0.4890 val_loss=6.3339 val_acc=0.1103 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 20/70: train_loss=1.6096 train_acc=0.5051 val_loss=5.8759 val_acc=0.1252 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 21/70: train_loss=1.5774 train_acc=0.5026 val_loss=6.2698 val_acc=0.1171 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 22/70: train_loss=1.5411 train_acc=0.5137 val_loss=6.2922 val_acc=0.1146 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 23/70: train_loss=1.4811 train_acc=0.5340 val_loss=6.0822 val_acc=0.1214 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 24/70: train_loss=1.4609 train_acc=0.5368 val_loss=6.3280 val_acc=0.1171 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 25/70: train_loss=1.4690 train_acc=0.5354 val_loss=6.6338 val_acc=0.1146 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 26/70: train_loss=1.4338 train_acc=0.5518 val_loss=6.3935 val_acc=0.1128 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 27/70: train_loss=1.3982 train_acc=0.5548 val_loss=7.0241 val_acc=0.1109 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 28/70: train_loss=1.3654 train_acc=0.5659 val_loss=6.7535 val_acc=0.1159 seconds=0.4
[CNN] 5 GHz/lovo fold=04 epoch 29/70: train_loss=1.3415 train_acc=0.5785 val_loss=7.0211 val_acc=0.1078 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 30/70: train_loss=1.3025 train_acc=0.5863 val_loss=7.0202 val_acc=0.1202 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 31/70: train_loss=1.2872 train_acc=0.5866 val_loss=7.4824 val_acc=0.1152 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 32/70: train_loss=1.2715 train_acc=0.5990 val_loss=7.1947 val_acc=0.1171 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 33/70: train_loss=1.2451 train_acc=0.6027 val_loss=7.4443 val_acc=0.1134 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 34/70: train_loss=1.2419 train_acc=0.6098 val_loss=7.5157 val_acc=0.1103 seconds=0.4
[CNN] 5 GHz/lovo fold=04 epoch 35/70: train_loss=1.2321 train_acc=0.6053 val_loss=7.6712 val_acc=0.1121 seconds=0.5
[CNN] early stopping at epoch 35; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__5ghz__lovo__ebl-session__s43__a89b5d__fold-04.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__5ghz__lovo__ebl-session__s43__a89b5d/training_curves__fold-04.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=05 validation_user=04 (entire user, deterministic rotation)
[CNN] 5 GHz/lovo fold=05 parameters=76308
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] 5 GHz/lovo fold=05 epoch 01/70: train_loss=3.7636 train_acc=0.0535 val_loss=3.8782 val_acc=0.0471 seconds=3.1
[CNN] 5 GHz/lovo fold=05 epoch 02/70: train_loss=3.2298 train_acc=0.1165 val_loss=3.9889 val_acc=0.0838 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 03/70: train_loss=2.9227 train_acc=0.1761 val_loss=4.2520 val_acc=0.0813 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 04/70: train_loss=2.7348 train_acc=0.2142 val_loss=4.4535 val_acc=0.0875 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 05/70: train_loss=2.5885 train_acc=0.2463 val_loss=4.7311 val_acc=0.0942 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 06/70: train_loss=2.4835 train_acc=0.2742 val_loss=4.7562 val_acc=0.0936 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 07/70: train_loss=2.3858 train_acc=0.2866 val_loss=4.8492 val_acc=0.0881 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 08/70: train_loss=2.3060 train_acc=0.3098 val_loss=5.0508 val_acc=0.0893 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 09/70: train_loss=2.2145 train_acc=0.3397 val_loss=5.1891 val_acc=0.0869 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 10/70: train_loss=2.1511 train_acc=0.3521 val_loss=5.0889 val_acc=0.1034 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 11/70: train_loss=2.1064 train_acc=0.3622 val_loss=5.1557 val_acc=0.0972 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 12/70: train_loss=2.0282 train_acc=0.3851 val_loss=5.2375 val_acc=0.1021 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 13/70: train_loss=1.9707 train_acc=0.3890 val_loss=5.5900 val_acc=0.1021 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 14/70: train_loss=1.9273 train_acc=0.4019 val_loss=5.7892 val_acc=0.1052 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 15/70: train_loss=1.8802 train_acc=0.4194 val_loss=5.8034 val_acc=0.0832 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 16/70: train_loss=1.8282 train_acc=0.4289 val_loss=6.0280 val_acc=0.0954 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 17/70: train_loss=1.8000 train_acc=0.4371 val_loss=5.6049 val_acc=0.0905 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 18/70: train_loss=1.7395 train_acc=0.4630 val_loss=6.1536 val_acc=0.0875 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 19/70: train_loss=1.7052 train_acc=0.4687 val_loss=5.8577 val_acc=0.0979 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 20/70: train_loss=1.6697 train_acc=0.4756 val_loss=6.4512 val_acc=0.1034 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 21/70: train_loss=1.6421 train_acc=0.4870 val_loss=6.3097 val_acc=0.0936 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 22/70: train_loss=1.6116 train_acc=0.4920 val_loss=6.0913 val_acc=0.0905 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 23/70: train_loss=1.5920 train_acc=0.4959 val_loss=6.1527 val_acc=0.0930 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 24/70: train_loss=1.5365 train_acc=0.5126 val_loss=6.5682 val_acc=0.0917 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 25/70: train_loss=1.5127 train_acc=0.5223 val_loss=6.5349 val_acc=0.0911 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 26/70: train_loss=1.4902 train_acc=0.5230 val_loss=6.6635 val_acc=0.0991 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 27/70: train_loss=1.4695 train_acc=0.5319 val_loss=6.5510 val_acc=0.1009 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 28/70: train_loss=1.4242 train_acc=0.5516 val_loss=6.7409 val_acc=0.0954 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 29/70: train_loss=1.4321 train_acc=0.5520 val_loss=7.2982 val_acc=0.0991 seconds=0.5
[CNN] early stopping at epoch 29; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__5ghz__lovo__ebl-session__s43__a89b5d__fold-05.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__5ghz__lovo__ebl-session__s43__a89b5d/training_curves__fold-05.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=06 validation_user=05 (entire user, deterministic rotation)
[CNN] 5 GHz/lovo fold=06 parameters=76308
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] 5 GHz/lovo fold=06 epoch 01/70: train_loss=3.7770 train_acc=0.0638 val_loss=4.0149 val_acc=0.0273 seconds=2.7
[CNN] 5 GHz/lovo fold=06 epoch 02/70: train_loss=3.2578 train_acc=0.1110 val_loss=4.6437 val_acc=0.0651 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 03/70: train_loss=2.9643 train_acc=0.1586 val_loss=4.5161 val_acc=0.0905 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 04/70: train_loss=2.7857 train_acc=0.1994 val_loss=4.6071 val_acc=0.0874 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 05/70: train_loss=2.6329 train_acc=0.2343 val_loss=4.6468 val_acc=0.0763 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 06/70: train_loss=2.5048 train_acc=0.2584 val_loss=5.1339 val_acc=0.0781 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 07/70: train_loss=2.4010 train_acc=0.2908 val_loss=5.1281 val_acc=0.0781 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 08/70: train_loss=2.3117 train_acc=0.3063 val_loss=4.9279 val_acc=0.0880 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 09/70: train_loss=2.2411 train_acc=0.3262 val_loss=5.1316 val_acc=0.0849 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 10/70: train_loss=2.1634 train_acc=0.3416 val_loss=5.3394 val_acc=0.0868 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 11/70: train_loss=2.1122 train_acc=0.3609 val_loss=5.3562 val_acc=0.0849 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 12/70: train_loss=2.0471 train_acc=0.3736 val_loss=4.9642 val_acc=0.0862 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 13/70: train_loss=2.0159 train_acc=0.3773 val_loss=5.6200 val_acc=0.0849 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 14/70: train_loss=1.9328 train_acc=0.4053 val_loss=5.5524 val_acc=0.0856 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 15/70: train_loss=1.8916 train_acc=0.4107 val_loss=5.2278 val_acc=0.0955 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 16/70: train_loss=1.8339 train_acc=0.4290 val_loss=5.3103 val_acc=0.0837 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 17/70: train_loss=1.8178 train_acc=0.4331 val_loss=5.4920 val_acc=0.0781 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 18/70: train_loss=1.7821 train_acc=0.4474 val_loss=5.6577 val_acc=0.0856 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 19/70: train_loss=1.7539 train_acc=0.4483 val_loss=6.5559 val_acc=0.0825 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 20/70: train_loss=1.7167 train_acc=0.4653 val_loss=5.9278 val_acc=0.0899 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 21/70: train_loss=1.6769 train_acc=0.4704 val_loss=6.2839 val_acc=0.0893 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 22/70: train_loss=1.6208 train_acc=0.4922 val_loss=6.3292 val_acc=0.0942 seconds=0.6
[CNN] 5 GHz/lovo fold=06 epoch 23/70: train_loss=1.6010 train_acc=0.4959 val_loss=6.5588 val_acc=0.0911 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 24/70: train_loss=1.5751 train_acc=0.5035 val_loss=6.3927 val_acc=0.0856 seconds=0.6
[CNN] 5 GHz/lovo fold=06 epoch 25/70: train_loss=1.5639 train_acc=0.5044 val_loss=6.3237 val_acc=0.0905 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 26/70: train_loss=1.5309 train_acc=0.5146 val_loss=6.6351 val_acc=0.0849 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 27/70: train_loss=1.4839 train_acc=0.5254 val_loss=6.6820 val_acc=0.0899 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 28/70: train_loss=1.4665 train_acc=0.5313 val_loss=7.1458 val_acc=0.0930 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 29/70: train_loss=1.4701 train_acc=0.5330 val_loss=7.2976 val_acc=0.0905 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 30/70: train_loss=1.4258 train_acc=0.5489 val_loss=6.4534 val_acc=0.0843 seconds=0.5
[CNN] early stopping at epoch 30; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__5ghz__lovo__ebl-session__s43__a89b5d__fold-06.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__5ghz__lovo__ebl-session__s43__a89b5d/training_curves__fold-06.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__5ghz__lovo__ebl-session__s43__a89b5d.parquet
[results upsert] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/runs_folds.csv: 30 row(s)
[DL LOVO] seed=43 fold mean position_accuracy=0.0853 +/- 0.0188; pooled=0.0854
[DL GPU] run_id=dl__cnn__5ghz__lovo__ebl-session__s43__a89b5d peak_cuda_memory_bytes=579083264
[results upsert] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/runs.csv: 29 row(s)
Seeds: random=44, numpy=44, torch=44
[trial filter] split=lovo trials=['01'] kept=9695/14478
[trial filter] split=lovo trials=['01'] kept=9695/9695
[protocol] split=lovo fold=01 trials_used=['01'] n_train=8067 n_test=1628 users=['01', '02', '03', '04', '05', '06'] train_users=['02', '03', '04', '05', '06'] test_users=['01']
[protocol] split=lovo fold=02 trials_used=['01'] n_train=8097 n_test=1598 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '03', '04', '05', '06'] test_users=['02']
[protocol] split=lovo fold=03 trials_used=['01'] n_train=8081 n_test=1614 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '04', '05', '06'] test_users=['03']
[protocol] split=lovo fold=04 trials_used=['01'] n_train=8060 n_test=1635 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '05', '06'] test_users=['04']
[protocol] split=lovo fold=05 trials_used=['01'] n_train=8082 n_test=1613 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '06'] test_users=['05']
[protocol] split=lovo fold=06 trials_used=['01'] n_train=8088 n_test=1607 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05'] test_users=['06']
[DL LOVO] held_out_user=01 validation_user=06 (entire user, deterministic rotation)
[CNN] 5 GHz/lovo fold=01 parameters=76308
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] 5 GHz/lovo fold=01 epoch 01/70: train_loss=3.8212 train_acc=0.0627 val_loss=3.8134 val_acc=0.0958 seconds=2.7
[CNN] 5 GHz/lovo fold=01 epoch 02/70: train_loss=3.3540 train_acc=0.1173 val_loss=3.9683 val_acc=0.0890 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 03/70: train_loss=2.9773 train_acc=0.1738 val_loss=4.5051 val_acc=0.0784 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 04/70: train_loss=2.7155 train_acc=0.2166 val_loss=5.1304 val_acc=0.0672 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 05/70: train_loss=2.5707 train_acc=0.2495 val_loss=5.0505 val_acc=0.0666 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 06/70: train_loss=2.4526 train_acc=0.2760 val_loss=5.2640 val_acc=0.0821 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 07/70: train_loss=2.3523 train_acc=0.3026 val_loss=5.6540 val_acc=0.0485 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 08/70: train_loss=2.2624 train_acc=0.3201 val_loss=5.4878 val_acc=0.0921 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 09/70: train_loss=2.1885 train_acc=0.3440 val_loss=5.7092 val_acc=0.0828 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 10/70: train_loss=2.1119 train_acc=0.3596 val_loss=6.2177 val_acc=0.0784 seconds=0.4
[CNN] 5 GHz/lovo fold=01 epoch 11/70: train_loss=2.0589 train_acc=0.3690 val_loss=6.2930 val_acc=0.0790 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 12/70: train_loss=2.0108 train_acc=0.3851 val_loss=6.0053 val_acc=0.0859 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 13/70: train_loss=1.9500 train_acc=0.4025 val_loss=6.1819 val_acc=0.0946 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 14/70: train_loss=1.8783 train_acc=0.4173 val_loss=6.5456 val_acc=0.0828 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 15/70: train_loss=1.8249 train_acc=0.4395 val_loss=6.5729 val_acc=0.0803 seconds=0.5
[CNN] 5 GHz/lovo fold=01 epoch 16/70: train_loss=1.7924 train_acc=0.4339 val_loss=6.6447 val_acc=0.0896 seconds=0.5
[CNN] early stopping at epoch 16; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__5ghz__lovo__ebl-session__s44__7b9bf2__fold-01.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__5ghz__lovo__ebl-session__s44__7b9bf2/training_curves__fold-01.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=02 validation_user=01 (entire user, deterministic rotation)
[CNN] 5 GHz/lovo fold=02 parameters=76308
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] 5 GHz/lovo fold=02 epoch 01/70: train_loss=3.8323 train_acc=0.0642 val_loss=3.7454 val_acc=0.0663 seconds=3.0
[CNN] 5 GHz/lovo fold=02 epoch 02/70: train_loss=3.3474 train_acc=0.1213 val_loss=4.6188 val_acc=0.0657 seconds=0.5
[CNN] 5 GHz/lovo fold=02 epoch 03/70: train_loss=2.9647 train_acc=0.1747 val_loss=5.2955 val_acc=0.0768 seconds=0.5
[CNN] 5 GHz/lovo fold=02 epoch 04/70: train_loss=2.6960 train_acc=0.2251 val_loss=6.4144 val_acc=0.0657 seconds=0.5
[CNN] 5 GHz/lovo fold=02 epoch 05/70: train_loss=2.5207 train_acc=0.2663 val_loss=6.5087 val_acc=0.0670 seconds=0.5
[CNN] 5 GHz/lovo fold=02 epoch 06/70: train_loss=2.3612 train_acc=0.3025 val_loss=7.1457 val_acc=0.0719 seconds=0.4
[CNN] 5 GHz/lovo fold=02 epoch 07/70: train_loss=2.2342 train_acc=0.3279 val_loss=7.3063 val_acc=0.0639 seconds=0.5
[CNN] 5 GHz/lovo fold=02 epoch 08/70: train_loss=2.1241 train_acc=0.3537 val_loss=8.3943 val_acc=0.0774 seconds=0.5
[CNN] 5 GHz/lovo fold=02 epoch 09/70: train_loss=2.0244 train_acc=0.3820 val_loss=9.1032 val_acc=0.0688 seconds=0.5
[CNN] 5 GHz/lovo fold=02 epoch 10/70: train_loss=1.9501 train_acc=0.4001 val_loss=8.3478 val_acc=0.0602 seconds=0.5
[CNN] 5 GHz/lovo fold=02 epoch 11/70: train_loss=1.8492 train_acc=0.4364 val_loss=8.8315 val_acc=0.0676 seconds=0.5
[CNN] 5 GHz/lovo fold=02 epoch 12/70: train_loss=1.7867 train_acc=0.4457 val_loss=9.1574 val_acc=0.0719 seconds=0.5
[CNN] 5 GHz/lovo fold=02 epoch 13/70: train_loss=1.7504 train_acc=0.4532 val_loss=9.9228 val_acc=0.0651 seconds=0.5
[CNN] 5 GHz/lovo fold=02 epoch 14/70: train_loss=1.6517 train_acc=0.4854 val_loss=10.3365 val_acc=0.0651 seconds=0.5
[CNN] 5 GHz/lovo fold=02 epoch 15/70: train_loss=1.6311 train_acc=0.4894 val_loss=10.1657 val_acc=0.0731 seconds=0.5
[CNN] 5 GHz/lovo fold=02 epoch 16/70: train_loss=1.5593 train_acc=0.5182 val_loss=10.3041 val_acc=0.0749 seconds=0.5
[CNN] 5 GHz/lovo fold=02 epoch 17/70: train_loss=1.5103 train_acc=0.5296 val_loss=11.6954 val_acc=0.0541 seconds=0.5
[CNN] 5 GHz/lovo fold=02 epoch 18/70: train_loss=1.4553 train_acc=0.5488 val_loss=12.0544 val_acc=0.0627 seconds=0.5
[CNN] 5 GHz/lovo fold=02 epoch 19/70: train_loss=1.4422 train_acc=0.5423 val_loss=11.3439 val_acc=0.0694 seconds=0.5
[CNN] 5 GHz/lovo fold=02 epoch 20/70: train_loss=1.3964 train_acc=0.5647 val_loss=11.8533 val_acc=0.0577 seconds=0.5
[CNN] 5 GHz/lovo fold=02 epoch 21/70: train_loss=1.3738 train_acc=0.5585 val_loss=12.0224 val_acc=0.0584 seconds=0.5
[CNN] 5 GHz/lovo fold=02 epoch 22/70: train_loss=1.3387 train_acc=0.5735 val_loss=12.3387 val_acc=0.0541 seconds=0.5
[CNN] 5 GHz/lovo fold=02 epoch 23/70: train_loss=1.2960 train_acc=0.5925 val_loss=12.2548 val_acc=0.0510 seconds=0.4
[CNN] early stopping at epoch 23; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__5ghz__lovo__ebl-session__s44__7b9bf2__fold-02.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__5ghz__lovo__ebl-session__s44__7b9bf2/training_curves__fold-02.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=03 validation_user=02 (entire user, deterministic rotation)
[CNN] 5 GHz/lovo fold=03 parameters=76308
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] 5 GHz/lovo fold=03 epoch 01/70: train_loss=3.7783 train_acc=0.0722 val_loss=3.7685 val_acc=0.0407 seconds=2.9
[CNN] 5 GHz/lovo fold=03 epoch 02/70: train_loss=3.2408 train_acc=0.1327 val_loss=4.4097 val_acc=0.0476 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 03/70: train_loss=2.9026 train_acc=0.1919 val_loss=4.9780 val_acc=0.0407 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 04/70: train_loss=2.6944 train_acc=0.2291 val_loss=5.3422 val_acc=0.0444 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 05/70: train_loss=2.5318 train_acc=0.2715 val_loss=5.4872 val_acc=0.0413 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 06/70: train_loss=2.3784 train_acc=0.2931 val_loss=6.2257 val_acc=0.0363 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 07/70: train_loss=2.2726 train_acc=0.3222 val_loss=6.8462 val_acc=0.0382 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 08/70: train_loss=2.1672 train_acc=0.3377 val_loss=6.6318 val_acc=0.0488 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 09/70: train_loss=2.0489 train_acc=0.3741 val_loss=7.1719 val_acc=0.0507 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 10/70: train_loss=1.9699 train_acc=0.3964 val_loss=7.6829 val_acc=0.0513 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 11/70: train_loss=1.8939 train_acc=0.4151 val_loss=7.9996 val_acc=0.0494 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 12/70: train_loss=1.8153 train_acc=0.4345 val_loss=8.3880 val_acc=0.0476 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 13/70: train_loss=1.7414 train_acc=0.4648 val_loss=8.8396 val_acc=0.0576 seconds=0.4
[CNN] 5 GHz/lovo fold=03 epoch 14/70: train_loss=1.6862 train_acc=0.4772 val_loss=8.8367 val_acc=0.0557 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 15/70: train_loss=1.6362 train_acc=0.4851 val_loss=9.8305 val_acc=0.0569 seconds=0.4
[CNN] 5 GHz/lovo fold=03 epoch 16/70: train_loss=1.5908 train_acc=0.5046 val_loss=9.5267 val_acc=0.0544 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 17/70: train_loss=1.5298 train_acc=0.5195 val_loss=9.5636 val_acc=0.0532 seconds=0.4
[CNN] 5 GHz/lovo fold=03 epoch 18/70: train_loss=1.5094 train_acc=0.5241 val_loss=10.7324 val_acc=0.0582 seconds=0.4
[CNN] 5 GHz/lovo fold=03 epoch 19/70: train_loss=1.4753 train_acc=0.5373 val_loss=10.1994 val_acc=0.0469 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 20/70: train_loss=1.4249 train_acc=0.5542 val_loss=11.2209 val_acc=0.0563 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 21/70: train_loss=1.3711 train_acc=0.5696 val_loss=10.5275 val_acc=0.0588 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 22/70: train_loss=1.3648 train_acc=0.5706 val_loss=11.3281 val_acc=0.0538 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 23/70: train_loss=1.3297 train_acc=0.5814 val_loss=10.9874 val_acc=0.0576 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 24/70: train_loss=1.2842 train_acc=0.5848 val_loss=11.8739 val_acc=0.0538 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 25/70: train_loss=1.2487 train_acc=0.6085 val_loss=12.0253 val_acc=0.0551 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 26/70: train_loss=1.2305 train_acc=0.6102 val_loss=11.8875 val_acc=0.0532 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 27/70: train_loss=1.1837 train_acc=0.6306 val_loss=11.7999 val_acc=0.0594 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 28/70: train_loss=1.1868 train_acc=0.6278 val_loss=13.1826 val_acc=0.0538 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 29/70: train_loss=1.1723 train_acc=0.6290 val_loss=12.6761 val_acc=0.0569 seconds=0.4
[CNN] 5 GHz/lovo fold=03 epoch 30/70: train_loss=1.1348 train_acc=0.6358 val_loss=13.3713 val_acc=0.0557 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 31/70: train_loss=1.1221 train_acc=0.6421 val_loss=13.5784 val_acc=0.0576 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 32/70: train_loss=1.0944 train_acc=0.6489 val_loss=13.5149 val_acc=0.0588 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 33/70: train_loss=1.0615 train_acc=0.6551 val_loss=14.0651 val_acc=0.0538 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 34/70: train_loss=1.0552 train_acc=0.6562 val_loss=13.6004 val_acc=0.0613 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 35/70: train_loss=1.0201 train_acc=0.6698 val_loss=14.4910 val_acc=0.0557 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 36/70: train_loss=1.0110 train_acc=0.6781 val_loss=13.9702 val_acc=0.0544 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 37/70: train_loss=1.0097 train_acc=0.6741 val_loss=14.2808 val_acc=0.0582 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 38/70: train_loss=0.9833 train_acc=0.6838 val_loss=14.4934 val_acc=0.0551 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 39/70: train_loss=0.9522 train_acc=0.6940 val_loss=14.8000 val_acc=0.0620 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 40/70: train_loss=0.9467 train_acc=0.6969 val_loss=15.1378 val_acc=0.0582 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 41/70: train_loss=0.9225 train_acc=0.7097 val_loss=15.3632 val_acc=0.0538 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 42/70: train_loss=0.9304 train_acc=0.6995 val_loss=15.8829 val_acc=0.0532 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 43/70: train_loss=0.9183 train_acc=0.6983 val_loss=15.5689 val_acc=0.0632 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 44/70: train_loss=0.9097 train_acc=0.7031 val_loss=16.1634 val_acc=0.0532 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 45/70: train_loss=0.8860 train_acc=0.7112 val_loss=15.7753 val_acc=0.0607 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 46/70: train_loss=0.8842 train_acc=0.7097 val_loss=16.2517 val_acc=0.0551 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 47/70: train_loss=0.8583 train_acc=0.7268 val_loss=16.5004 val_acc=0.0551 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 48/70: train_loss=0.8473 train_acc=0.7239 val_loss=15.3511 val_acc=0.0613 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 49/70: train_loss=0.8385 train_acc=0.7262 val_loss=17.2774 val_acc=0.0569 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 50/70: train_loss=0.8110 train_acc=0.7324 val_loss=17.2999 val_acc=0.0601 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 51/70: train_loss=0.8026 train_acc=0.7318 val_loss=17.1878 val_acc=0.0594 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 52/70: train_loss=0.7989 train_acc=0.7443 val_loss=17.3019 val_acc=0.0607 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 53/70: train_loss=0.7903 train_acc=0.7369 val_loss=17.6080 val_acc=0.0607 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 54/70: train_loss=0.7866 train_acc=0.7412 val_loss=17.3848 val_acc=0.0557 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 55/70: train_loss=0.7621 train_acc=0.7512 val_loss=17.9372 val_acc=0.0551 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 56/70: train_loss=0.7623 train_acc=0.7473 val_loss=18.4252 val_acc=0.0538 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 57/70: train_loss=0.7479 train_acc=0.7595 val_loss=18.2287 val_acc=0.0594 seconds=0.5
[CNN] 5 GHz/lovo fold=03 epoch 58/70: train_loss=0.7391 train_acc=0.7591 val_loss=18.5222 val_acc=0.0588 seconds=0.5
[CNN] early stopping at epoch 58; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__5ghz__lovo__ebl-session__s44__7b9bf2__fold-03.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__5ghz__lovo__ebl-session__s44__7b9bf2/training_curves__fold-03.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=04 validation_user=03 (entire user, deterministic rotation)
[CNN] 5 GHz/lovo fold=04 parameters=76308
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] 5 GHz/lovo fold=04 epoch 01/70: train_loss=3.8246 train_acc=0.0585 val_loss=3.8195 val_acc=0.0508 seconds=3.0
[CNN] 5 GHz/lovo fold=04 epoch 02/70: train_loss=3.3623 train_acc=0.1150 val_loss=3.9238 val_acc=0.0830 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 03/70: train_loss=3.0324 train_acc=0.1596 val_loss=4.1374 val_acc=0.0892 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 04/70: train_loss=2.8352 train_acc=0.1984 val_loss=4.1785 val_acc=0.0979 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 05/70: train_loss=2.6603 train_acc=0.2350 val_loss=4.1960 val_acc=0.0985 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 06/70: train_loss=2.5226 train_acc=0.2603 val_loss=4.3343 val_acc=0.1041 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 07/70: train_loss=2.4211 train_acc=0.2850 val_loss=4.6940 val_acc=0.1140 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 08/70: train_loss=2.3122 train_acc=0.3131 val_loss=4.5635 val_acc=0.1152 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 09/70: train_loss=2.2037 train_acc=0.3452 val_loss=4.7211 val_acc=0.1239 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 10/70: train_loss=2.1209 train_acc=0.3622 val_loss=4.7509 val_acc=0.1252 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 11/70: train_loss=2.0430 train_acc=0.3743 val_loss=4.9158 val_acc=0.1159 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 12/70: train_loss=1.9832 train_acc=0.4026 val_loss=5.0696 val_acc=0.1214 seconds=0.6
[CNN] 5 GHz/lovo fold=04 epoch 13/70: train_loss=1.9217 train_acc=0.4086 val_loss=5.2187 val_acc=0.1165 seconds=0.6
[CNN] 5 GHz/lovo fold=04 epoch 14/70: train_loss=1.8483 train_acc=0.4333 val_loss=5.3455 val_acc=0.1177 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 15/70: train_loss=1.8113 train_acc=0.4446 val_loss=5.2898 val_acc=0.1264 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 16/70: train_loss=1.7431 train_acc=0.4708 val_loss=5.3782 val_acc=0.1183 seconds=0.4
[CNN] 5 GHz/lovo fold=04 epoch 17/70: train_loss=1.6902 train_acc=0.4721 val_loss=5.3308 val_acc=0.1134 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 18/70: train_loss=1.6383 train_acc=0.4874 val_loss=5.7503 val_acc=0.1109 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 19/70: train_loss=1.6018 train_acc=0.5033 val_loss=5.9540 val_acc=0.1190 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 20/70: train_loss=1.5609 train_acc=0.5152 val_loss=5.8781 val_acc=0.1090 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 21/70: train_loss=1.5146 train_acc=0.5195 val_loss=5.7663 val_acc=0.1152 seconds=0.4
[CNN] 5 GHz/lovo fold=04 epoch 22/70: train_loss=1.5079 train_acc=0.5343 val_loss=6.1694 val_acc=0.1128 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 23/70: train_loss=1.4802 train_acc=0.5402 val_loss=6.0520 val_acc=0.1165 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 24/70: train_loss=1.4188 train_acc=0.5566 val_loss=6.1754 val_acc=0.1177 seconds=0.4
[CNN] 5 GHz/lovo fold=04 epoch 25/70: train_loss=1.4054 train_acc=0.5524 val_loss=6.5518 val_acc=0.1208 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 26/70: train_loss=1.4191 train_acc=0.5504 val_loss=6.2962 val_acc=0.1183 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 27/70: train_loss=1.3836 train_acc=0.5645 val_loss=6.4698 val_acc=0.1196 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 28/70: train_loss=1.3246 train_acc=0.5757 val_loss=6.6451 val_acc=0.1109 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 29/70: train_loss=1.2727 train_acc=0.5925 val_loss=6.6942 val_acc=0.1115 seconds=0.5
[CNN] 5 GHz/lovo fold=04 epoch 30/70: train_loss=1.2824 train_acc=0.5939 val_loss=6.4908 val_acc=0.1140 seconds=0.5
[CNN] early stopping at epoch 30; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__5ghz__lovo__ebl-session__s44__7b9bf2__fold-04.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__5ghz__lovo__ebl-session__s44__7b9bf2/training_curves__fold-04.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=05 validation_user=04 (entire user, deterministic rotation)
[CNN] 5 GHz/lovo fold=05 parameters=76308
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] 5 GHz/lovo fold=05 epoch 01/70: train_loss=3.7682 train_acc=0.0575 val_loss=3.8092 val_acc=0.0483 seconds=3.1
[CNN] 5 GHz/lovo fold=05 epoch 02/70: train_loss=3.2333 train_acc=0.1179 val_loss=3.8862 val_acc=0.0752 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 03/70: train_loss=2.9507 train_acc=0.1624 val_loss=4.1473 val_acc=0.0820 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 04/70: train_loss=2.7742 train_acc=0.1953 val_loss=4.4810 val_acc=0.0972 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 05/70: train_loss=2.6266 train_acc=0.2288 val_loss=4.4245 val_acc=0.1046 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 06/70: train_loss=2.5144 train_acc=0.2593 val_loss=4.6042 val_acc=0.1187 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 07/70: train_loss=2.4405 train_acc=0.2648 val_loss=4.6627 val_acc=0.1046 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 08/70: train_loss=2.3405 train_acc=0.2966 val_loss=4.7193 val_acc=0.1211 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 09/70: train_loss=2.2699 train_acc=0.3186 val_loss=4.7362 val_acc=0.1046 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 10/70: train_loss=2.2147 train_acc=0.3304 val_loss=4.8737 val_acc=0.1229 seconds=0.4
[CNN] 5 GHz/lovo fold=05 epoch 11/70: train_loss=2.1507 train_acc=0.3443 val_loss=5.0872 val_acc=0.1107 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 12/70: train_loss=2.0943 train_acc=0.3609 val_loss=5.0640 val_acc=0.1083 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 13/70: train_loss=2.0427 train_acc=0.3799 val_loss=5.1930 val_acc=0.1113 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 14/70: train_loss=1.9915 train_acc=0.3855 val_loss=5.3626 val_acc=0.1119 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 15/70: train_loss=1.9637 train_acc=0.4010 val_loss=5.1262 val_acc=0.1156 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 16/70: train_loss=1.9065 train_acc=0.4200 val_loss=5.7497 val_acc=0.1187 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 17/70: train_loss=1.8380 train_acc=0.4289 val_loss=5.4828 val_acc=0.1052 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 18/70: train_loss=1.8316 train_acc=0.4253 val_loss=5.6011 val_acc=0.1064 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 19/70: train_loss=1.7950 train_acc=0.4509 val_loss=5.7683 val_acc=0.1107 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 20/70: train_loss=1.7520 train_acc=0.4601 val_loss=5.8266 val_acc=0.1076 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 21/70: train_loss=1.7182 train_acc=0.4652 val_loss=6.0011 val_acc=0.1028 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 22/70: train_loss=1.6755 train_acc=0.4793 val_loss=5.8160 val_acc=0.1101 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 23/70: train_loss=1.6564 train_acc=0.4815 val_loss=6.4060 val_acc=0.0942 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 24/70: train_loss=1.6141 train_acc=0.4898 val_loss=6.3841 val_acc=0.1052 seconds=0.5
[CNN] 5 GHz/lovo fold=05 epoch 25/70: train_loss=1.5803 train_acc=0.5061 val_loss=6.6709 val_acc=0.0985 seconds=0.5
[CNN] early stopping at epoch 25; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__5ghz__lovo__ebl-session__s44__7b9bf2__fold-05.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__5ghz__lovo__ebl-session__s44__7b9bf2/training_curves__fold-05.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=06 validation_user=05 (entire user, deterministic rotation)
[CNN] 5 GHz/lovo fold=06 parameters=76308
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] 5 GHz/lovo fold=06 epoch 01/70: train_loss=3.7841 train_acc=0.0544 val_loss=4.0146 val_acc=0.0341 seconds=3.4
[CNN] 5 GHz/lovo fold=06 epoch 02/70: train_loss=3.2644 train_acc=0.1220 val_loss=4.5490 val_acc=0.0756 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 03/70: train_loss=2.9540 train_acc=0.1665 val_loss=4.9944 val_acc=0.0862 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 04/70: train_loss=2.7476 train_acc=0.2077 val_loss=4.4287 val_acc=0.0955 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 05/70: train_loss=2.6060 train_acc=0.2420 val_loss=4.8554 val_acc=0.0732 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 06/70: train_loss=2.4845 train_acc=0.2653 val_loss=4.9389 val_acc=0.0924 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 07/70: train_loss=2.3757 train_acc=0.2954 val_loss=5.2416 val_acc=0.0905 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 08/70: train_loss=2.3085 train_acc=0.3129 val_loss=5.5196 val_acc=0.0682 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 09/70: train_loss=2.2065 train_acc=0.3339 val_loss=5.5694 val_acc=0.0781 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 10/70: train_loss=2.1328 train_acc=0.3588 val_loss=5.1396 val_acc=0.0986 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 11/70: train_loss=2.0722 train_acc=0.3717 val_loss=5.5846 val_acc=0.0899 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 12/70: train_loss=2.0135 train_acc=0.3852 val_loss=5.4137 val_acc=0.0862 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 13/70: train_loss=1.9900 train_acc=0.3934 val_loss=5.6198 val_acc=0.0967 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 14/70: train_loss=1.9503 train_acc=0.4068 val_loss=5.5238 val_acc=0.0843 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 15/70: train_loss=1.9008 train_acc=0.4184 val_loss=5.4256 val_acc=0.0812 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 16/70: train_loss=1.8487 train_acc=0.4275 val_loss=5.3381 val_acc=0.0930 seconds=0.6
[CNN] 5 GHz/lovo fold=06 epoch 17/70: train_loss=1.8010 train_acc=0.4394 val_loss=5.6399 val_acc=0.0856 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 18/70: train_loss=1.7728 train_acc=0.4491 val_loss=6.0672 val_acc=0.0682 seconds=0.6
[CNN] 5 GHz/lovo fold=06 epoch 19/70: train_loss=1.7330 train_acc=0.4635 val_loss=5.6845 val_acc=0.0880 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 20/70: train_loss=1.7211 train_acc=0.4646 val_loss=5.7835 val_acc=0.0980 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 21/70: train_loss=1.6694 train_acc=0.4764 val_loss=5.7637 val_acc=0.0905 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 22/70: train_loss=1.6446 train_acc=0.4778 val_loss=5.9765 val_acc=0.0949 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 23/70: train_loss=1.6195 train_acc=0.4897 val_loss=6.1146 val_acc=0.0924 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 24/70: train_loss=1.5728 train_acc=0.5032 val_loss=5.9578 val_acc=0.0794 seconds=0.4
[CNN] 5 GHz/lovo fold=06 epoch 25/70: train_loss=1.5650 train_acc=0.5046 val_loss=5.7493 val_acc=0.1004 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 26/70: train_loss=1.5336 train_acc=0.5220 val_loss=6.6740 val_acc=0.0905 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 27/70: train_loss=1.4996 train_acc=0.5220 val_loss=6.3792 val_acc=0.0911 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 28/70: train_loss=1.5049 train_acc=0.5231 val_loss=6.3748 val_acc=0.0905 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 29/70: train_loss=1.4610 train_acc=0.5333 val_loss=6.1681 val_acc=0.0949 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 30/70: train_loss=1.4387 train_acc=0.5424 val_loss=6.8253 val_acc=0.0874 seconds=0.6
[CNN] 5 GHz/lovo fold=06 epoch 31/70: train_loss=1.4189 train_acc=0.5432 val_loss=6.4528 val_acc=0.0911 seconds=0.6
[CNN] 5 GHz/lovo fold=06 epoch 32/70: train_loss=1.3847 train_acc=0.5555 val_loss=6.5771 val_acc=0.0887 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 33/70: train_loss=1.3954 train_acc=0.5486 val_loss=6.7331 val_acc=0.0874 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 34/70: train_loss=1.3642 train_acc=0.5632 val_loss=6.8952 val_acc=0.0874 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 35/70: train_loss=1.3245 train_acc=0.5731 val_loss=6.7583 val_acc=0.0899 seconds=0.6
[CNN] 5 GHz/lovo fold=06 epoch 36/70: train_loss=1.3342 train_acc=0.5759 val_loss=6.7398 val_acc=0.0911 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 37/70: train_loss=1.3167 train_acc=0.5730 val_loss=6.3696 val_acc=0.0992 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 38/70: train_loss=1.2896 train_acc=0.5775 val_loss=7.3488 val_acc=0.0831 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 39/70: train_loss=1.2816 train_acc=0.5858 val_loss=7.4195 val_acc=0.0911 seconds=0.5
[CNN] 5 GHz/lovo fold=06 epoch 40/70: train_loss=1.2609 train_acc=0.5926 val_loss=7.1591 val_acc=0.0955 seconds=0.5
[CNN] early stopping at epoch 40; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__5ghz__lovo__ebl-session__s44__7b9bf2__fold-06.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__5ghz__lovo__ebl-session__s44__7b9bf2/training_curves__fold-06.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__5ghz__lovo__ebl-session__s44__7b9bf2.parquet
[results upsert] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/runs_folds.csv: 36 row(s)
[DL LOVO] seed=44 fold mean position_accuracy=0.0797 +/- 0.0309; pooled=0.0797
[DL GPU] run_id=dl__cnn__5ghz__lovo__ebl-session__s44__7b9bf2 peak_cuda_memory_bytes=579083264
[results upsert] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/runs.csv: 30 row(s)
[DL seeds] mean +/- std across seeds written to tables/seed_summary; LOVO uses each seed's fold mean and keeps within-seed fold std separate.

=== Fusion ===
[window arrays] cache path: /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/.cache/dataframes/preproc=norm-empty_baseline_scope-per_session/feat=win60-step0/window_arrays/fusion
[window arrays cache hit] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/.cache/dataframes/preproc=norm-empty_baseline_scope-per_session/feat=win60-step0/window_arrays/fusion
[window arrays] 2.4 GHz: shape=(13568, 9, 50, 60), dtype=float16
[window arrays] 2.4 GHz anchors: ['esp_01', 'esp_02', 'esp_03', 'esp_04', 'esp_05', 'esp_07', 'esp_08', 'esp_09', 'esp_10']
[window arrays] 5 GHz: shape=(13568, 10, 56, 60), dtype=float16
[window arrays] 5 GHz anchors: ['esp_11', 'esp_12', 'esp_13', 'esp_14', 'esp_15', 'esp_16', 'esp_17', 'esp_18', 'esp_19', 'esp_20']
2.4 GHz: anchors=9, subcarriers=50, windows=13568
5 GHz: anchors=10, subcarriers=56, windows=13568
Fusion N PASS: 13568 windows
WINDOW IDENTITY PASS: Fusion (13568 windows)
[trial filter] split=lovo trials=['01'] kept=8889/13568
[trial filter] split=lovo trials=['01'] kept=8889/8889
[protocol] split=lovo fold=01 trials_used=['01'] n_train=7331 n_test=1558 users=['01', '02', '03', '04', '05', '06'] train_users=['02', '03', '04', '05', '06'] test_users=['01']
[protocol] split=lovo fold=02 trials_used=['01'] n_train=7478 n_test=1411 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '03', '04', '05', '06'] test_users=['02']
[protocol] split=lovo fold=03 trials_used=['01'] n_train=7303 n_test=1586 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '04', '05', '06'] test_users=['03']
[protocol] split=lovo fold=04 trials_used=['01'] n_train=7330 n_test=1559 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '05', '06'] test_users=['04']
[protocol] split=lovo fold=05 trials_used=['01'] n_train=7403 n_test=1486 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '06'] test_users=['05']
[protocol] split=lovo fold=06 trials_used=['01'] n_train=7600 n_test=1289 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05'] test_users=['06']
[trial filter] split=lovo trials=['01'] kept=8889/13568
[trial filter] split=lovo trials=['01'] kept=8889/8889
[protocol] split=lovo fold=01 trials_used=['01'] n_train=7331 n_test=1558 users=['01', '02', '03', '04', '05', '06'] train_users=['02', '03', '04', '05', '06'] test_users=['01']
[protocol] split=lovo fold=02 trials_used=['01'] n_train=7478 n_test=1411 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '03', '04', '05', '06'] test_users=['02']
[protocol] split=lovo fold=03 trials_used=['01'] n_train=7303 n_test=1586 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '04', '05', '06'] test_users=['03']
[protocol] split=lovo fold=04 trials_used=['01'] n_train=7330 n_test=1559 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '05', '06'] test_users=['04']
[protocol] split=lovo fold=05 trials_used=['01'] n_train=7403 n_test=1486 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '06'] test_users=['05']
[protocol] split=lovo fold=06 trials_used=['01'] n_train=7600 n_test=1289 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05'] test_users=['06']
SPLIT IDENTITY PASS: Fusion/lovo fold=1 train=7331 test=1558
SPLIT IDENTITY PASS: Fusion/lovo fold=2 train=7478 test=1411
SPLIT IDENTITY PASS: Fusion/lovo fold=3 train=7303 test=1586
SPLIT IDENTITY PASS: Fusion/lovo fold=4 train=7330 test=1559
SPLIT IDENTITY PASS: Fusion/lovo fold=5 train=7403 test=1486
SPLIT IDENTITY PASS: Fusion/lovo fold=6 train=7600 test=1289
Seeds: random=42, numpy=42, torch=42
[trial filter] split=lovo trials=['01'] kept=8889/13568
[trial filter] split=lovo trials=['01'] kept=8889/8889
[protocol] split=lovo fold=01 trials_used=['01'] n_train=7331 n_test=1558 users=['01', '02', '03', '04', '05', '06'] train_users=['02', '03', '04', '05', '06'] test_users=['01']
[protocol] split=lovo fold=02 trials_used=['01'] n_train=7478 n_test=1411 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '03', '04', '05', '06'] test_users=['02']
[protocol] split=lovo fold=03 trials_used=['01'] n_train=7303 n_test=1586 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '04', '05', '06'] test_users=['03']
[protocol] split=lovo fold=04 trials_used=['01'] n_train=7330 n_test=1559 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '05', '06'] test_users=['04']
[protocol] split=lovo fold=05 trials_used=['01'] n_train=7403 n_test=1486 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '06'] test_users=['05']
[protocol] split=lovo fold=06 trials_used=['01'] n_train=7600 n_test=1289 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05'] test_users=['06']
[DL LOVO] held_out_user=01 validation_user=06 (entire user, deterministic rotation)
[CNN] Fusion/lovo fold=01 parameters=138708
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] Fusion/lovo fold=01 epoch 01/70: train_loss=3.8155 train_acc=0.0647 val_loss=3.8468 val_acc=0.0403 seconds=3.3
[CNN] Fusion/lovo fold=01 epoch 02/70: train_loss=3.1736 train_acc=0.1756 val_loss=3.7250 val_acc=0.0760 seconds=0.8
[CNN] Fusion/lovo fold=01 epoch 03/70: train_loss=2.5974 train_acc=0.2648 val_loss=4.0390 val_acc=0.0931 seconds=0.8
[CNN] Fusion/lovo fold=01 epoch 04/70: train_loss=2.2641 train_acc=0.3275 val_loss=4.8082 val_acc=0.0613 seconds=0.8
[CNN] Fusion/lovo fold=01 epoch 05/70: train_loss=2.0143 train_acc=0.3937 val_loss=4.6812 val_acc=0.0954 seconds=0.8
[CNN] Fusion/lovo fold=01 epoch 06/70: train_loss=1.8341 train_acc=0.4399 val_loss=5.4355 val_acc=0.0683 seconds=0.8
[CNN] Fusion/lovo fold=01 epoch 07/70: train_loss=1.6667 train_acc=0.4825 val_loss=5.6856 val_acc=0.0636 seconds=0.8
[CNN] Fusion/lovo fold=01 epoch 08/70: train_loss=1.5395 train_acc=0.5276 val_loss=5.8514 val_acc=0.0753 seconds=0.8
[CNN] Fusion/lovo fold=01 epoch 09/70: train_loss=1.4308 train_acc=0.5505 val_loss=5.4246 val_acc=0.0838 seconds=0.8
[CNN] Fusion/lovo fold=01 epoch 10/70: train_loss=1.3271 train_acc=0.5811 val_loss=6.5230 val_acc=0.0698 seconds=0.8
[CNN] Fusion/lovo fold=01 epoch 11/70: train_loss=1.2354 train_acc=0.6082 val_loss=6.1472 val_acc=0.0760 seconds=0.7
[CNN] Fusion/lovo fold=01 epoch 12/70: train_loss=1.1624 train_acc=0.6326 val_loss=6.0884 val_acc=0.0822 seconds=0.9
[CNN] Fusion/lovo fold=01 epoch 13/70: train_loss=1.0989 train_acc=0.6518 val_loss=6.3944 val_acc=0.0698 seconds=0.9
[CNN] Fusion/lovo fold=01 epoch 14/70: train_loss=1.0341 train_acc=0.6733 val_loss=6.1490 val_acc=0.0900 seconds=0.8
[CNN] Fusion/lovo fold=01 epoch 15/70: train_loss=0.9715 train_acc=0.6907 val_loss=6.6742 val_acc=0.0737 seconds=0.7
[CNN] Fusion/lovo fold=01 epoch 16/70: train_loss=0.9215 train_acc=0.7125 val_loss=7.3404 val_acc=0.0737 seconds=0.8
[CNN] Fusion/lovo fold=01 epoch 17/70: train_loss=0.8706 train_acc=0.7176 val_loss=6.9469 val_acc=0.0822 seconds=0.7
[CNN] Fusion/lovo fold=01 epoch 18/70: train_loss=0.8119 train_acc=0.7436 val_loss=6.7316 val_acc=0.0923 seconds=0.8
[CNN] Fusion/lovo fold=01 epoch 19/70: train_loss=0.7888 train_acc=0.7466 val_loss=7.0230 val_acc=0.0807 seconds=0.8
[CNN] Fusion/lovo fold=01 epoch 20/70: train_loss=0.7376 train_acc=0.7628 val_loss=7.7177 val_acc=0.0659 seconds=0.8
[CNN] early stopping at epoch 20; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__fusion__lovo__ebl-session__s42__9b1404__fold-01.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__fusion__lovo__ebl-session__s42__9b1404/training_curves__fold-01.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=02 validation_user=01 (entire user, deterministic rotation)
[CNN] Fusion/lovo fold=02 parameters=138708
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] Fusion/lovo fold=02 epoch 01/70: train_loss=3.7894 train_acc=0.0838 val_loss=3.8251 val_acc=0.0533 seconds=3.3
[CNN] Fusion/lovo fold=02 epoch 02/70: train_loss=3.1467 train_acc=0.1870 val_loss=3.7700 val_acc=0.0911 seconds=0.9
[CNN] Fusion/lovo fold=02 epoch 03/70: train_loss=2.5627 train_acc=0.2796 val_loss=4.5754 val_acc=0.1027 seconds=0.8
[CNN] Fusion/lovo fold=02 epoch 04/70: train_loss=2.1903 train_acc=0.3596 val_loss=4.9647 val_acc=0.1123 seconds=0.8
[CNN] Fusion/lovo fold=02 epoch 05/70: train_loss=1.9530 train_acc=0.4186 val_loss=5.4652 val_acc=0.1110 seconds=0.8
[CNN] Fusion/lovo fold=02 epoch 06/70: train_loss=1.7629 train_acc=0.4699 val_loss=5.4160 val_acc=0.1098 seconds=0.8
[CNN] Fusion/lovo fold=02 epoch 07/70: train_loss=1.6017 train_acc=0.5100 val_loss=6.2117 val_acc=0.1053 seconds=0.9
[CNN] Fusion/lovo fold=02 epoch 08/70: train_loss=1.4649 train_acc=0.5514 val_loss=7.1428 val_acc=0.1008 seconds=0.9
[CNN] Fusion/lovo fold=02 epoch 09/70: train_loss=1.3723 train_acc=0.5752 val_loss=7.1529 val_acc=0.0937 seconds=0.9
[CNN] Fusion/lovo fold=02 epoch 10/70: train_loss=1.2547 train_acc=0.6152 val_loss=7.3766 val_acc=0.1117 seconds=0.8
[CNN] Fusion/lovo fold=02 epoch 11/70: train_loss=1.2235 train_acc=0.6176 val_loss=7.8197 val_acc=0.0950 seconds=0.8
[CNN] Fusion/lovo fold=02 epoch 12/70: train_loss=1.1245 train_acc=0.6525 val_loss=7.7200 val_acc=0.0911 seconds=0.8
[CNN] Fusion/lovo fold=02 epoch 13/70: train_loss=1.0158 train_acc=0.6877 val_loss=8.1020 val_acc=0.1027 seconds=0.8
[CNN] Fusion/lovo fold=02 epoch 14/70: train_loss=0.9574 train_acc=0.7064 val_loss=7.6142 val_acc=0.1027 seconds=0.9
[CNN] Fusion/lovo fold=02 epoch 15/70: train_loss=0.8899 train_acc=0.7203 val_loss=7.1996 val_acc=0.1065 seconds=0.9
[CNN] Fusion/lovo fold=02 epoch 16/70: train_loss=0.8720 train_acc=0.7245 val_loss=7.3869 val_acc=0.1117 seconds=0.9
[CNN] Fusion/lovo fold=02 epoch 17/70: train_loss=0.8082 train_acc=0.7449 val_loss=7.2669 val_acc=0.1072 seconds=0.8
[CNN] Fusion/lovo fold=02 epoch 18/70: train_loss=0.7649 train_acc=0.7591 val_loss=8.5665 val_acc=0.0976 seconds=0.7
[CNN] Fusion/lovo fold=02 epoch 19/70: train_loss=0.7221 train_acc=0.7774 val_loss=8.3385 val_acc=0.0956 seconds=0.7
[CNN] early stopping at epoch 19; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__fusion__lovo__ebl-session__s42__9b1404__fold-02.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__fusion__lovo__ebl-session__s42__9b1404/training_curves__fold-02.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=03 validation_user=02 (entire user, deterministic rotation)
[CNN] Fusion/lovo fold=03 parameters=138708
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] Fusion/lovo fold=03 epoch 01/70: train_loss=3.7751 train_acc=0.0952 val_loss=3.7967 val_acc=0.0376 seconds=3.5
[CNN] Fusion/lovo fold=03 epoch 02/70: train_loss=3.1023 train_acc=0.1811 val_loss=4.3394 val_acc=0.0383 seconds=0.7
[CNN] Fusion/lovo fold=03 epoch 03/70: train_loss=2.6423 train_acc=0.2449 val_loss=4.6263 val_acc=0.0482 seconds=0.7
[CNN] Fusion/lovo fold=03 epoch 04/70: train_loss=2.3603 train_acc=0.3080 val_loss=5.0298 val_acc=0.0524 seconds=0.7
[CNN] Fusion/lovo fold=03 epoch 05/70: train_loss=2.1645 train_acc=0.3676 val_loss=5.2742 val_acc=0.0496 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 06/70: train_loss=1.9715 train_acc=0.4102 val_loss=5.5212 val_acc=0.0489 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 07/70: train_loss=1.8965 train_acc=0.4375 val_loss=5.4649 val_acc=0.0567 seconds=0.7
[CNN] Fusion/lovo fold=03 epoch 08/70: train_loss=1.8430 train_acc=0.4447 val_loss=6.3796 val_acc=0.0454 seconds=0.7
[CNN] Fusion/lovo fold=03 epoch 09/70: train_loss=1.7754 train_acc=0.4581 val_loss=6.0326 val_acc=0.0496 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 10/70: train_loss=1.6205 train_acc=0.5124 val_loss=5.9543 val_acc=0.0560 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 11/70: train_loss=1.5614 train_acc=0.5226 val_loss=6.1028 val_acc=0.0588 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 12/70: train_loss=1.5213 train_acc=0.5304 val_loss=6.5982 val_acc=0.0595 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 13/70: train_loss=1.3881 train_acc=0.5713 val_loss=6.4544 val_acc=0.0624 seconds=0.9
[CNN] Fusion/lovo fold=03 epoch 14/70: train_loss=1.2663 train_acc=0.6147 val_loss=6.6164 val_acc=0.0659 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 15/70: train_loss=1.2472 train_acc=0.6176 val_loss=6.8350 val_acc=0.0666 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 16/70: train_loss=1.2097 train_acc=0.6214 val_loss=8.1970 val_acc=0.0411 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 17/70: train_loss=1.0978 train_acc=0.6594 val_loss=7.6131 val_acc=0.0588 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 18/70: train_loss=1.1825 train_acc=0.6256 val_loss=7.4829 val_acc=0.0652 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 19/70: train_loss=1.1439 train_acc=0.6417 val_loss=7.2706 val_acc=0.0652 seconds=0.9
[CNN] Fusion/lovo fold=03 epoch 20/70: train_loss=1.0347 train_acc=0.6801 val_loss=7.3994 val_acc=0.0609 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 21/70: train_loss=1.0387 train_acc=0.6843 val_loss=7.2459 val_acc=0.0595 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 22/70: train_loss=0.8976 train_acc=0.7295 val_loss=8.2184 val_acc=0.0546 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 23/70: train_loss=0.8366 train_acc=0.7419 val_loss=7.9857 val_acc=0.0638 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 24/70: train_loss=0.8246 train_acc=0.7449 val_loss=8.1171 val_acc=0.0581 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 25/70: train_loss=0.9319 train_acc=0.7099 val_loss=8.4258 val_acc=0.0546 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 26/70: train_loss=0.7801 train_acc=0.7590 val_loss=8.2019 val_acc=0.0638 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 27/70: train_loss=0.7613 train_acc=0.7592 val_loss=8.6806 val_acc=0.0595 seconds=0.7
[CNN] Fusion/lovo fold=03 epoch 28/70: train_loss=0.7861 train_acc=0.7490 val_loss=8.8553 val_acc=0.0581 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 29/70: train_loss=0.8627 train_acc=0.7298 val_loss=8.8134 val_acc=0.0510 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 30/70: train_loss=0.7488 train_acc=0.7629 val_loss=9.2227 val_acc=0.0574 seconds=0.7
[CNN] early stopping at epoch 30; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__fusion__lovo__ebl-session__s42__9b1404__fold-03.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__fusion__lovo__ebl-session__s42__9b1404/training_curves__fold-03.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=04 validation_user=03 (entire user, deterministic rotation)
[CNN] Fusion/lovo fold=04 parameters=138708
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] Fusion/lovo fold=04 epoch 01/70: train_loss=3.8191 train_acc=0.0688 val_loss=3.9078 val_acc=0.0359 seconds=3.2
[CNN] Fusion/lovo fold=04 epoch 02/70: train_loss=3.2553 train_acc=0.1405 val_loss=4.1227 val_acc=0.0593 seconds=0.7
[CNN] Fusion/lovo fold=04 epoch 03/70: train_loss=2.7119 train_acc=0.2291 val_loss=4.2523 val_acc=0.0921 seconds=0.7
[CNN] Fusion/lovo fold=04 epoch 04/70: train_loss=2.3784 train_acc=0.3036 val_loss=4.3905 val_acc=0.0958 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 05/70: train_loss=2.1454 train_acc=0.3599 val_loss=4.7137 val_acc=0.1059 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 06/70: train_loss=1.9441 train_acc=0.4123 val_loss=4.6730 val_acc=0.1223 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 07/70: train_loss=1.7570 train_acc=0.4662 val_loss=4.9721 val_acc=0.1217 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 08/70: train_loss=1.6322 train_acc=0.4920 val_loss=5.5525 val_acc=0.1103 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 09/70: train_loss=1.4886 train_acc=0.5494 val_loss=5.9139 val_acc=0.1103 seconds=0.9
[CNN] Fusion/lovo fold=04 epoch 10/70: train_loss=1.3684 train_acc=0.5836 val_loss=5.6489 val_acc=0.1230 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 11/70: train_loss=1.2818 train_acc=0.6022 val_loss=5.9669 val_acc=0.1211 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 12/70: train_loss=1.1738 train_acc=0.6398 val_loss=6.4304 val_acc=0.1173 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 13/70: train_loss=1.0912 train_acc=0.6542 val_loss=6.3782 val_acc=0.1267 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 14/70: train_loss=1.0420 train_acc=0.6774 val_loss=6.3046 val_acc=0.1293 seconds=0.7
[CNN] Fusion/lovo fold=04 epoch 15/70: train_loss=0.9500 train_acc=0.7058 val_loss=7.1754 val_acc=0.1160 seconds=0.7
[CNN] Fusion/lovo fold=04 epoch 16/70: train_loss=0.8871 train_acc=0.7227 val_loss=7.5676 val_acc=0.1148 seconds=0.7
[CNN] Fusion/lovo fold=04 epoch 17/70: train_loss=0.8279 train_acc=0.7383 val_loss=7.2639 val_acc=0.1349 seconds=0.7
[CNN] Fusion/lovo fold=04 epoch 18/70: train_loss=0.7818 train_acc=0.7575 val_loss=7.2075 val_acc=0.1286 seconds=0.7
[CNN] Fusion/lovo fold=04 epoch 19/70: train_loss=0.7435 train_acc=0.7683 val_loss=8.2748 val_acc=0.1160 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 20/70: train_loss=0.7222 train_acc=0.7744 val_loss=7.7989 val_acc=0.1122 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 21/70: train_loss=0.6597 train_acc=0.7968 val_loss=7.9121 val_acc=0.1280 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 22/70: train_loss=0.6238 train_acc=0.8033 val_loss=7.7995 val_acc=0.1223 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 23/70: train_loss=0.5888 train_acc=0.8203 val_loss=8.1980 val_acc=0.1198 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 24/70: train_loss=0.5563 train_acc=0.8330 val_loss=8.7405 val_acc=0.1166 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 25/70: train_loss=0.5445 train_acc=0.8296 val_loss=8.5574 val_acc=0.1299 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 26/70: train_loss=0.5427 train_acc=0.8264 val_loss=8.2881 val_acc=0.1343 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 27/70: train_loss=0.5100 train_acc=0.8437 val_loss=8.5033 val_acc=0.1299 seconds=0.7
[CNN] Fusion/lovo fold=04 epoch 28/70: train_loss=0.4903 train_acc=0.8452 val_loss=8.7627 val_acc=0.1248 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 29/70: train_loss=0.4613 train_acc=0.8574 val_loss=9.5743 val_acc=0.1160 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 30/70: train_loss=0.4317 train_acc=0.8628 val_loss=8.5171 val_acc=0.1280 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 31/70: train_loss=0.4368 train_acc=0.8539 val_loss=9.4610 val_acc=0.1311 seconds=0.7
[CNN] Fusion/lovo fold=04 epoch 32/70: train_loss=0.4132 train_acc=0.8720 val_loss=9.7647 val_acc=0.1211 seconds=0.7
[CNN] early stopping at epoch 32; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__fusion__lovo__ebl-session__s42__9b1404__fold-04.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__fusion__lovo__ebl-session__s42__9b1404/training_curves__fold-04.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=05 validation_user=04 (entire user, deterministic rotation)
[CNN] Fusion/lovo fold=05 parameters=138708
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] Fusion/lovo fold=05 epoch 01/70: train_loss=3.7705 train_acc=0.0813 val_loss=3.9287 val_acc=0.0564 seconds=3.7
[CNN] Fusion/lovo fold=05 epoch 02/70: train_loss=3.1268 train_acc=0.1431 val_loss=4.3429 val_acc=0.0622 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 03/70: train_loss=2.6715 train_acc=0.2248 val_loss=4.1047 val_acc=0.0795 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 04/70: train_loss=2.3858 train_acc=0.2931 val_loss=4.5739 val_acc=0.0757 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 05/70: train_loss=2.1471 train_acc=0.3539 val_loss=4.6818 val_acc=0.0622 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 06/70: train_loss=1.9890 train_acc=0.3860 val_loss=4.9740 val_acc=0.0789 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 07/70: train_loss=1.8412 train_acc=0.4398 val_loss=4.8926 val_acc=0.0680 seconds=0.7
[CNN] Fusion/lovo fold=05 epoch 08/70: train_loss=1.6831 train_acc=0.4848 val_loss=5.0223 val_acc=0.0706 seconds=0.9
[CNN] Fusion/lovo fold=05 epoch 09/70: train_loss=1.5650 train_acc=0.5128 val_loss=5.4149 val_acc=0.0641 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 10/70: train_loss=1.4628 train_acc=0.5431 val_loss=5.9503 val_acc=0.0532 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 11/70: train_loss=1.3831 train_acc=0.5625 val_loss=5.3910 val_acc=0.0981 seconds=0.7
[CNN] Fusion/lovo fold=05 epoch 12/70: train_loss=1.2742 train_acc=0.6028 val_loss=5.4353 val_acc=0.0718 seconds=0.7
[CNN] Fusion/lovo fold=05 epoch 13/70: train_loss=1.1879 train_acc=0.6302 val_loss=5.8488 val_acc=0.0802 seconds=0.7
[CNN] Fusion/lovo fold=05 epoch 14/70: train_loss=1.1257 train_acc=0.6468 val_loss=5.9810 val_acc=0.0674 seconds=0.7
[CNN] Fusion/lovo fold=05 epoch 15/70: train_loss=1.0446 train_acc=0.6663 val_loss=5.9306 val_acc=0.0731 seconds=0.7
[CNN] Fusion/lovo fold=05 epoch 16/70: train_loss=0.9915 train_acc=0.6795 val_loss=6.1865 val_acc=0.0827 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 17/70: train_loss=0.9249 train_acc=0.7055 val_loss=5.8919 val_acc=0.0866 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 18/70: train_loss=0.8906 train_acc=0.7192 val_loss=6.3996 val_acc=0.0776 seconds=0.7
[CNN] Fusion/lovo fold=05 epoch 19/70: train_loss=0.8293 train_acc=0.7382 val_loss=6.2600 val_acc=0.0815 seconds=0.7
[CNN] Fusion/lovo fold=05 epoch 20/70: train_loss=0.7824 train_acc=0.7507 val_loss=6.3399 val_acc=0.0917 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 21/70: train_loss=0.7652 train_acc=0.7615 val_loss=6.1060 val_acc=0.1026 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 22/70: train_loss=0.7093 train_acc=0.7786 val_loss=6.9759 val_acc=0.0795 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 23/70: train_loss=0.6781 train_acc=0.7887 val_loss=7.3178 val_acc=0.0815 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 24/70: train_loss=0.6535 train_acc=0.7926 val_loss=7.7578 val_acc=0.0616 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 25/70: train_loss=0.6053 train_acc=0.8126 val_loss=7.1999 val_acc=0.0699 seconds=0.7
[CNN] Fusion/lovo fold=05 epoch 26/70: train_loss=0.5678 train_acc=0.8224 val_loss=6.7387 val_acc=0.1001 seconds=0.7
[CNN] Fusion/lovo fold=05 epoch 27/70: train_loss=0.5432 train_acc=0.8296 val_loss=7.3193 val_acc=0.0808 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 28/70: train_loss=0.5276 train_acc=0.8275 val_loss=7.4331 val_acc=0.0821 seconds=0.9
[CNN] Fusion/lovo fold=05 epoch 29/70: train_loss=0.5066 train_acc=0.8427 val_loss=7.4953 val_acc=0.0834 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 30/70: train_loss=0.4935 train_acc=0.8470 val_loss=7.9735 val_acc=0.0725 seconds=0.7
[CNN] Fusion/lovo fold=05 epoch 31/70: train_loss=0.4693 train_acc=0.8535 val_loss=8.4868 val_acc=0.0590 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 32/70: train_loss=0.4442 train_acc=0.8571 val_loss=7.6268 val_acc=0.0827 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 33/70: train_loss=0.4255 train_acc=0.8677 val_loss=7.6132 val_acc=0.0924 seconds=0.7
[CNN] Fusion/lovo fold=05 epoch 34/70: train_loss=0.4211 train_acc=0.8676 val_loss=8.3536 val_acc=0.0770 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 35/70: train_loss=0.3917 train_acc=0.8780 val_loss=7.8560 val_acc=0.0783 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 36/70: train_loss=0.3662 train_acc=0.8866 val_loss=8.8136 val_acc=0.0738 seconds=0.8
[CNN] early stopping at epoch 36; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__fusion__lovo__ebl-session__s42__9b1404__fold-05.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__fusion__lovo__ebl-session__s42__9b1404/training_curves__fold-05.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=06 validation_user=05 (entire user, deterministic rotation)
[CNN] Fusion/lovo fold=06 parameters=138708
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] Fusion/lovo fold=06 epoch 01/70: train_loss=3.8024 train_acc=0.0697 val_loss=3.9638 val_acc=0.0262 seconds=3.4
[CNN] Fusion/lovo fold=06 epoch 02/70: train_loss=3.2166 train_acc=0.1430 val_loss=4.1587 val_acc=0.0498 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 03/70: train_loss=2.7637 train_acc=0.2144 val_loss=4.1288 val_acc=0.0861 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 04/70: train_loss=2.4134 train_acc=0.2982 val_loss=4.2087 val_acc=0.0976 seconds=0.9
[CNN] Fusion/lovo fold=06 epoch 05/70: train_loss=2.1436 train_acc=0.3693 val_loss=4.4296 val_acc=0.0922 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 06/70: train_loss=1.9176 train_acc=0.4246 val_loss=4.7260 val_acc=0.0989 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 07/70: train_loss=1.7437 train_acc=0.4697 val_loss=4.7881 val_acc=0.1036 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 08/70: train_loss=1.5974 train_acc=0.5106 val_loss=4.7545 val_acc=0.1285 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 09/70: train_loss=1.4616 train_acc=0.5530 val_loss=5.4223 val_acc=0.0962 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 10/70: train_loss=1.3609 train_acc=0.5721 val_loss=5.2025 val_acc=0.1211 seconds=0.9
[CNN] Fusion/lovo fold=06 epoch 11/70: train_loss=1.2598 train_acc=0.6044 val_loss=5.7176 val_acc=0.1083 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 12/70: train_loss=1.1526 train_acc=0.6449 val_loss=5.8671 val_acc=0.0996 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 13/70: train_loss=1.1013 train_acc=0.6549 val_loss=5.7771 val_acc=0.1184 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 14/70: train_loss=1.0302 train_acc=0.6719 val_loss=5.8297 val_acc=0.1137 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 15/70: train_loss=0.9454 train_acc=0.7053 val_loss=5.8845 val_acc=0.1184 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 16/70: train_loss=0.8828 train_acc=0.7249 val_loss=6.4183 val_acc=0.1070 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 17/70: train_loss=0.8445 train_acc=0.7298 val_loss=6.1037 val_acc=0.1023 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 18/70: train_loss=0.7667 train_acc=0.7584 val_loss=6.3386 val_acc=0.1319 seconds=0.7
[CNN] Fusion/lovo fold=06 epoch 19/70: train_loss=0.7446 train_acc=0.7597 val_loss=7.1046 val_acc=0.0949 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 20/70: train_loss=0.7105 train_acc=0.7754 val_loss=6.9100 val_acc=0.1205 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 21/70: train_loss=0.6810 train_acc=0.7846 val_loss=6.5226 val_acc=0.1083 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 22/70: train_loss=0.6465 train_acc=0.7954 val_loss=6.6419 val_acc=0.1164 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 23/70: train_loss=0.6029 train_acc=0.8104 val_loss=6.8523 val_acc=0.1299 seconds=0.7
[CNN] Fusion/lovo fold=06 epoch 24/70: train_loss=0.5633 train_acc=0.8189 val_loss=7.2298 val_acc=0.0976 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 25/70: train_loss=0.5583 train_acc=0.8175 val_loss=7.2192 val_acc=0.1036 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 26/70: train_loss=0.5486 train_acc=0.8219 val_loss=6.8083 val_acc=0.1245 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 27/70: train_loss=0.5049 train_acc=0.8428 val_loss=7.4095 val_acc=0.1057 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 28/70: train_loss=0.4960 train_acc=0.8420 val_loss=7.2275 val_acc=0.1265 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 29/70: train_loss=0.4649 train_acc=0.8512 val_loss=7.5415 val_acc=0.1218 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 30/70: train_loss=0.4541 train_acc=0.8549 val_loss=7.6730 val_acc=0.1373 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 31/70: train_loss=0.4526 train_acc=0.8539 val_loss=7.4417 val_acc=0.1090 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 32/70: train_loss=0.4241 train_acc=0.8639 val_loss=7.6983 val_acc=0.1211 seconds=0.7
[CNN] Fusion/lovo fold=06 epoch 33/70: train_loss=0.4042 train_acc=0.8731 val_loss=8.1747 val_acc=0.1050 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 34/70: train_loss=0.3798 train_acc=0.8824 val_loss=7.8576 val_acc=0.1124 seconds=0.7
[CNN] Fusion/lovo fold=06 epoch 35/70: train_loss=0.3866 train_acc=0.8785 val_loss=8.0857 val_acc=0.1279 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 36/70: train_loss=0.3746 train_acc=0.8835 val_loss=8.0941 val_acc=0.1097 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 37/70: train_loss=0.3635 train_acc=0.8824 val_loss=8.2854 val_acc=0.1090 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 38/70: train_loss=0.3429 train_acc=0.8903 val_loss=8.4168 val_acc=0.1104 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 39/70: train_loss=0.3249 train_acc=0.8986 val_loss=7.8573 val_acc=0.1191 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 40/70: train_loss=0.3202 train_acc=0.8992 val_loss=8.8130 val_acc=0.1110 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 41/70: train_loss=0.3122 train_acc=0.9004 val_loss=9.1165 val_acc=0.0929 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 42/70: train_loss=0.2968 train_acc=0.9073 val_loss=9.0364 val_acc=0.1016 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 43/70: train_loss=0.2908 train_acc=0.9097 val_loss=8.5696 val_acc=0.1137 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 44/70: train_loss=0.2937 train_acc=0.9050 val_loss=8.7661 val_acc=0.1043 seconds=0.9
[CNN] Fusion/lovo fold=06 epoch 45/70: train_loss=0.2690 train_acc=0.9167 val_loss=9.0034 val_acc=0.1151 seconds=0.8
[CNN] early stopping at epoch 45; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__fusion__lovo__ebl-session__s42__9b1404__fold-06.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__fusion__lovo__ebl-session__s42__9b1404/training_curves__fold-06.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__fusion__lovo__ebl-session__s42__9b1404.parquet
[results upsert] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/runs_folds.csv: 42 row(s)
[DL LOVO] seed=42 fold mean position_accuracy=0.0886 +/- 0.0306; pooled=0.0902
[DL GPU] run_id=dl__cnn__fusion__lovo__ebl-session__s42__9b1404 peak_cuda_memory_bytes=978418688
[results upsert] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/runs.csv: 31 row(s)
Seeds: random=43, numpy=43, torch=43
[trial filter] split=lovo trials=['01'] kept=8889/13568
[trial filter] split=lovo trials=['01'] kept=8889/8889
[protocol] split=lovo fold=01 trials_used=['01'] n_train=7331 n_test=1558 users=['01', '02', '03', '04', '05', '06'] train_users=['02', '03', '04', '05', '06'] test_users=['01']
[protocol] split=lovo fold=02 trials_used=['01'] n_train=7478 n_test=1411 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '03', '04', '05', '06'] test_users=['02']
[protocol] split=lovo fold=03 trials_used=['01'] n_train=7303 n_test=1586 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '04', '05', '06'] test_users=['03']
[protocol] split=lovo fold=04 trials_used=['01'] n_train=7330 n_test=1559 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '05', '06'] test_users=['04']
[protocol] split=lovo fold=05 trials_used=['01'] n_train=7403 n_test=1486 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '06'] test_users=['05']
[protocol] split=lovo fold=06 trials_used=['01'] n_train=7600 n_test=1289 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05'] test_users=['06']
[DL LOVO] held_out_user=01 validation_user=06 (entire user, deterministic rotation)
[CNN] Fusion/lovo fold=01 parameters=138708
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] Fusion/lovo fold=01 epoch 01/70: train_loss=3.8073 train_acc=0.0727 val_loss=3.8685 val_acc=0.0450 seconds=3.3
[CNN] Fusion/lovo fold=01 epoch 02/70: train_loss=3.2028 train_acc=0.1658 val_loss=3.4919 val_acc=0.1040 seconds=0.9
[CNN] Fusion/lovo fold=01 epoch 03/70: train_loss=2.6358 train_acc=0.2547 val_loss=3.6654 val_acc=0.1148 seconds=0.8
[CNN] Fusion/lovo fold=01 epoch 04/70: train_loss=2.2663 train_acc=0.3393 val_loss=4.0848 val_acc=0.0915 seconds=0.8
[CNN] Fusion/lovo fold=01 epoch 05/70: train_loss=1.9988 train_acc=0.3995 val_loss=4.4316 val_acc=0.0993 seconds=0.8
[CNN] Fusion/lovo fold=01 epoch 06/70: train_loss=1.7747 train_acc=0.4542 val_loss=4.5852 val_acc=0.1078 seconds=0.9
[CNN] Fusion/lovo fold=01 epoch 07/70: train_loss=1.6235 train_acc=0.5025 val_loss=4.6648 val_acc=0.1117 seconds=0.8
[CNN] Fusion/lovo fold=01 epoch 08/70: train_loss=1.4859 train_acc=0.5314 val_loss=4.9866 val_acc=0.1265 seconds=0.8
[CNN] Fusion/lovo fold=01 epoch 09/70: train_loss=1.3715 train_acc=0.5715 val_loss=4.8213 val_acc=0.1404 seconds=0.8
[CNN] Fusion/lovo fold=01 epoch 10/70: train_loss=1.2617 train_acc=0.6044 val_loss=5.4693 val_acc=0.0900 seconds=0.7
[CNN] Fusion/lovo fold=01 epoch 11/70: train_loss=1.1693 train_acc=0.6319 val_loss=6.1423 val_acc=0.1063 seconds=0.8
[CNN] Fusion/lovo fold=01 epoch 12/70: train_loss=1.0995 train_acc=0.6514 val_loss=5.8594 val_acc=0.1133 seconds=0.8
[CNN] Fusion/lovo fold=01 epoch 13/70: train_loss=1.0130 train_acc=0.6840 val_loss=6.0000 val_acc=0.1086 seconds=0.8
[CNN] Fusion/lovo fold=01 epoch 14/70: train_loss=0.9713 train_acc=0.6879 val_loss=6.0026 val_acc=0.1226 seconds=0.8
[CNN] Fusion/lovo fold=01 epoch 15/70: train_loss=0.9031 train_acc=0.7167 val_loss=6.0023 val_acc=0.1342 seconds=0.9
[CNN] Fusion/lovo fold=01 epoch 16/70: train_loss=0.8745 train_acc=0.7259 val_loss=6.1778 val_acc=0.1241 seconds=0.8
[CNN] Fusion/lovo fold=01 epoch 17/70: train_loss=0.8258 train_acc=0.7352 val_loss=6.4331 val_acc=0.1334 seconds=0.8
[CNN] Fusion/lovo fold=01 epoch 18/70: train_loss=0.7684 train_acc=0.7572 val_loss=6.6549 val_acc=0.1094 seconds=0.8
[CNN] Fusion/lovo fold=01 epoch 19/70: train_loss=0.7424 train_acc=0.7627 val_loss=7.1567 val_acc=0.0884 seconds=0.8
[CNN] Fusion/lovo fold=01 epoch 20/70: train_loss=0.7174 train_acc=0.7655 val_loss=6.8636 val_acc=0.1032 seconds=0.7
[CNN] Fusion/lovo fold=01 epoch 21/70: train_loss=0.6555 train_acc=0.7944 val_loss=7.1631 val_acc=0.1086 seconds=0.7
[CNN] Fusion/lovo fold=01 epoch 22/70: train_loss=0.6307 train_acc=0.7954 val_loss=6.9793 val_acc=0.1280 seconds=0.8
[CNN] Fusion/lovo fold=01 epoch 23/70: train_loss=0.6125 train_acc=0.8032 val_loss=7.7195 val_acc=0.1179 seconds=0.8
[CNN] Fusion/lovo fold=01 epoch 24/70: train_loss=0.5830 train_acc=0.8125 val_loss=7.7330 val_acc=0.0970 seconds=0.7
[CNN] early stopping at epoch 24; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__fusion__lovo__ebl-session__s43__a89b5d__fold-01.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__fusion__lovo__ebl-session__s43__a89b5d/training_curves__fold-01.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=02 validation_user=01 (entire user, deterministic rotation)
[CNN] Fusion/lovo fold=02 parameters=138708
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] Fusion/lovo fold=02 epoch 01/70: train_loss=3.7933 train_acc=0.0738 val_loss=3.8139 val_acc=0.0712 seconds=3.1
[CNN] Fusion/lovo fold=02 epoch 02/70: train_loss=3.1471 train_acc=0.1726 val_loss=4.0758 val_acc=0.0918 seconds=0.8
[CNN] Fusion/lovo fold=02 epoch 03/70: train_loss=2.5959 train_acc=0.2622 val_loss=4.6623 val_acc=0.1117 seconds=0.8
[CNN] Fusion/lovo fold=02 epoch 04/70: train_loss=2.2498 train_acc=0.3397 val_loss=5.6237 val_acc=0.1046 seconds=0.8
[CNN] Fusion/lovo fold=02 epoch 05/70: train_loss=2.0004 train_acc=0.3965 val_loss=6.3349 val_acc=0.0963 seconds=0.7
[CNN] Fusion/lovo fold=02 epoch 06/70: train_loss=1.8132 train_acc=0.4473 val_loss=6.7286 val_acc=0.0899 seconds=0.8
[CNN] Fusion/lovo fold=02 epoch 07/70: train_loss=1.6421 train_acc=0.4892 val_loss=7.1743 val_acc=0.0988 seconds=0.7
[CNN] Fusion/lovo fold=02 epoch 08/70: train_loss=1.5070 train_acc=0.5311 val_loss=7.7188 val_acc=0.0873 seconds=0.8
[CNN] Fusion/lovo fold=02 epoch 09/70: train_loss=1.3735 train_acc=0.5660 val_loss=7.5530 val_acc=0.0841 seconds=0.8
[CNN] Fusion/lovo fold=02 epoch 10/70: train_loss=1.2788 train_acc=0.5944 val_loss=8.7459 val_acc=0.0828 seconds=0.8
[CNN] Fusion/lovo fold=02 epoch 11/70: train_loss=1.2068 train_acc=0.6193 val_loss=8.4040 val_acc=0.0931 seconds=0.8
[CNN] Fusion/lovo fold=02 epoch 12/70: train_loss=1.1220 train_acc=0.6493 val_loss=9.0729 val_acc=0.0886 seconds=0.8
[CNN] Fusion/lovo fold=02 epoch 13/70: train_loss=1.0440 train_acc=0.6686 val_loss=9.6981 val_acc=0.0828 seconds=0.8
[CNN] Fusion/lovo fold=02 epoch 14/70: train_loss=0.9756 train_acc=0.6924 val_loss=10.5382 val_acc=0.0886 seconds=0.8
[CNN] Fusion/lovo fold=02 epoch 15/70: train_loss=0.9184 train_acc=0.7159 val_loss=9.5158 val_acc=0.0892 seconds=0.8
[CNN] Fusion/lovo fold=02 epoch 16/70: train_loss=0.8691 train_acc=0.7274 val_loss=10.7206 val_acc=0.0847 seconds=0.8
[CNN] Fusion/lovo fold=02 epoch 17/70: train_loss=0.8101 train_acc=0.7453 val_loss=10.6827 val_acc=0.0789 seconds=0.8
[CNN] Fusion/lovo fold=02 epoch 18/70: train_loss=0.7766 train_acc=0.7586 val_loss=11.0900 val_acc=0.0738 seconds=0.7
[CNN] early stopping at epoch 18; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__fusion__lovo__ebl-session__s43__a89b5d__fold-02.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__fusion__lovo__ebl-session__s43__a89b5d/training_curves__fold-02.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=03 validation_user=02 (entire user, deterministic rotation)
[CNN] Fusion/lovo fold=03 parameters=138708
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] Fusion/lovo fold=03 epoch 01/70: train_loss=3.7901 train_acc=0.0832 val_loss=3.7620 val_acc=0.0439 seconds=3.1
[CNN] Fusion/lovo fold=03 epoch 02/70: train_loss=3.1425 train_acc=0.1662 val_loss=4.3131 val_acc=0.0446 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 03/70: train_loss=2.6665 train_acc=0.2512 val_loss=4.6446 val_acc=0.0425 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 04/70: train_loss=2.3538 train_acc=0.3091 val_loss=5.0662 val_acc=0.0411 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 05/70: train_loss=2.1354 train_acc=0.3671 val_loss=5.5512 val_acc=0.0595 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 06/70: train_loss=2.0288 train_acc=0.3943 val_loss=6.2210 val_acc=0.0567 seconds=0.7
[CNN] Fusion/lovo fold=03 epoch 07/70: train_loss=1.8834 train_acc=0.4336 val_loss=6.3476 val_acc=0.0503 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 08/70: train_loss=1.7682 train_acc=0.4662 val_loss=6.5250 val_acc=0.0496 seconds=0.9
[CNN] Fusion/lovo fold=03 epoch 09/70: train_loss=1.6787 train_acc=0.4879 val_loss=6.5762 val_acc=0.0609 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 10/70: train_loss=1.5553 train_acc=0.5239 val_loss=7.2981 val_acc=0.0517 seconds=0.7
[CNN] Fusion/lovo fold=03 epoch 11/70: train_loss=1.4587 train_acc=0.5479 val_loss=7.3562 val_acc=0.0454 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 12/70: train_loss=1.4283 train_acc=0.5696 val_loss=7.7537 val_acc=0.0390 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 13/70: train_loss=1.3498 train_acc=0.5806 val_loss=7.3989 val_acc=0.0461 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 14/70: train_loss=1.3064 train_acc=0.5939 val_loss=7.2012 val_acc=0.0574 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 15/70: train_loss=1.2188 train_acc=0.6158 val_loss=8.0289 val_acc=0.0446 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 16/70: train_loss=1.1675 train_acc=0.6365 val_loss=8.2755 val_acc=0.0503 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 17/70: train_loss=1.1363 train_acc=0.6451 val_loss=8.2415 val_acc=0.0468 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 18/70: train_loss=1.0587 train_acc=0.6694 val_loss=9.3297 val_acc=0.0369 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 19/70: train_loss=1.1812 train_acc=0.6342 val_loss=8.0533 val_acc=0.0503 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 20/70: train_loss=1.0785 train_acc=0.6682 val_loss=7.7623 val_acc=0.0609 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 21/70: train_loss=0.9611 train_acc=0.7072 val_loss=8.3309 val_acc=0.0475 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 22/70: train_loss=0.9107 train_acc=0.7210 val_loss=9.1688 val_acc=0.0383 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 23/70: train_loss=0.9476 train_acc=0.7043 val_loss=8.9421 val_acc=0.0425 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 24/70: train_loss=0.8592 train_acc=0.7252 val_loss=9.5505 val_acc=0.0418 seconds=0.8
[CNN] early stopping at epoch 24; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__fusion__lovo__ebl-session__s43__a89b5d__fold-03.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__fusion__lovo__ebl-session__s43__a89b5d/training_curves__fold-03.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=04 validation_user=03 (entire user, deterministic rotation)
[CNN] Fusion/lovo fold=04 parameters=138708
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] Fusion/lovo fold=04 epoch 01/70: train_loss=3.8042 train_acc=0.0731 val_loss=3.8706 val_acc=0.0347 seconds=3.4
[CNN] Fusion/lovo fold=04 epoch 02/70: train_loss=3.2445 train_acc=0.1475 val_loss=4.0384 val_acc=0.0643 seconds=0.9
[CNN] Fusion/lovo fold=04 epoch 03/70: train_loss=2.7528 train_acc=0.2206 val_loss=4.4246 val_acc=0.0908 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 04/70: train_loss=2.4328 train_acc=0.2932 val_loss=4.5990 val_acc=0.0769 seconds=0.9
[CNN] Fusion/lovo fold=04 epoch 05/70: train_loss=2.2120 train_acc=0.3489 val_loss=4.6519 val_acc=0.0977 seconds=0.9
[CNN] Fusion/lovo fold=04 epoch 06/70: train_loss=1.9768 train_acc=0.4076 val_loss=5.1456 val_acc=0.0946 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 07/70: train_loss=1.8177 train_acc=0.4474 val_loss=5.4002 val_acc=0.1072 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 08/70: train_loss=1.6577 train_acc=0.4981 val_loss=5.3542 val_acc=0.1135 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 09/70: train_loss=1.4985 train_acc=0.5385 val_loss=5.8434 val_acc=0.1078 seconds=0.7
[CNN] Fusion/lovo fold=04 epoch 10/70: train_loss=1.4040 train_acc=0.5721 val_loss=6.1496 val_acc=0.1078 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 11/70: train_loss=1.2839 train_acc=0.6076 val_loss=6.2404 val_acc=0.1078 seconds=0.7
[CNN] Fusion/lovo fold=04 epoch 12/70: train_loss=1.2122 train_acc=0.6208 val_loss=6.4658 val_acc=0.1091 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 13/70: train_loss=1.1117 train_acc=0.6562 val_loss=7.1727 val_acc=0.0958 seconds=0.7
[CNN] Fusion/lovo fold=04 epoch 14/70: train_loss=1.0506 train_acc=0.6737 val_loss=7.0134 val_acc=0.1091 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 15/70: train_loss=0.9919 train_acc=0.6939 val_loss=7.2370 val_acc=0.1021 seconds=0.7
[CNN] Fusion/lovo fold=04 epoch 16/70: train_loss=0.9327 train_acc=0.7120 val_loss=7.5168 val_acc=0.1028 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 17/70: train_loss=0.8708 train_acc=0.7349 val_loss=7.6072 val_acc=0.1173 seconds=0.9
[CNN] Fusion/lovo fold=04 epoch 18/70: train_loss=0.8167 train_acc=0.7451 val_loss=7.9014 val_acc=0.1078 seconds=0.7
[CNN] Fusion/lovo fold=04 epoch 19/70: train_loss=0.7539 train_acc=0.7679 val_loss=7.7905 val_acc=0.1091 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 20/70: train_loss=0.7157 train_acc=0.7782 val_loss=8.3979 val_acc=0.1185 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 21/70: train_loss=0.6895 train_acc=0.7841 val_loss=8.4750 val_acc=0.1185 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 22/70: train_loss=0.6375 train_acc=0.7987 val_loss=8.7410 val_acc=0.1179 seconds=0.7
[CNN] Fusion/lovo fold=04 epoch 23/70: train_loss=0.6142 train_acc=0.8081 val_loss=8.5905 val_acc=0.1148 seconds=0.7
[CNN] Fusion/lovo fold=04 epoch 24/70: train_loss=0.5968 train_acc=0.8175 val_loss=9.4516 val_acc=0.1034 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 25/70: train_loss=0.5468 train_acc=0.8334 val_loss=8.5027 val_acc=0.1217 seconds=0.7
[CNN] Fusion/lovo fold=04 epoch 26/70: train_loss=0.5437 train_acc=0.8282 val_loss=9.1293 val_acc=0.1267 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 27/70: train_loss=0.5135 train_acc=0.8343 val_loss=9.4878 val_acc=0.1122 seconds=0.7
[CNN] Fusion/lovo fold=04 epoch 28/70: train_loss=0.4720 train_acc=0.8524 val_loss=9.8696 val_acc=0.1230 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 29/70: train_loss=0.4669 train_acc=0.8564 val_loss=10.2369 val_acc=0.1179 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 30/70: train_loss=0.4352 train_acc=0.8606 val_loss=9.6958 val_acc=0.1103 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 31/70: train_loss=0.4257 train_acc=0.8647 val_loss=10.4479 val_acc=0.1141 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 32/70: train_loss=0.4290 train_acc=0.8637 val_loss=9.8398 val_acc=0.1160 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 33/70: train_loss=0.3950 train_acc=0.8757 val_loss=10.9128 val_acc=0.1154 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 34/70: train_loss=0.3827 train_acc=0.8753 val_loss=10.1713 val_acc=0.1242 seconds=0.7
[CNN] Fusion/lovo fold=04 epoch 35/70: train_loss=0.3625 train_acc=0.8874 val_loss=10.8955 val_acc=0.1129 seconds=0.7
[CNN] Fusion/lovo fold=04 epoch 36/70: train_loss=0.3667 train_acc=0.8818 val_loss=10.9341 val_acc=0.1141 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 37/70: train_loss=0.3436 train_acc=0.8893 val_loss=11.0753 val_acc=0.1084 seconds=0.9
[CNN] Fusion/lovo fold=04 epoch 38/70: train_loss=0.3289 train_acc=0.8961 val_loss=11.0341 val_acc=0.1154 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 39/70: train_loss=0.3258 train_acc=0.9001 val_loss=10.7431 val_acc=0.1230 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 40/70: train_loss=0.2985 train_acc=0.9067 val_loss=12.2054 val_acc=0.1059 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 41/70: train_loss=0.2990 train_acc=0.9076 val_loss=11.4076 val_acc=0.1084 seconds=0.7
[CNN] early stopping at epoch 41; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__fusion__lovo__ebl-session__s43__a89b5d__fold-04.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__fusion__lovo__ebl-session__s43__a89b5d/training_curves__fold-04.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=05 validation_user=04 (entire user, deterministic rotation)
[CNN] Fusion/lovo fold=05 parameters=138708
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] Fusion/lovo fold=05 epoch 01/70: train_loss=3.7926 train_acc=0.0773 val_loss=3.8689 val_acc=0.0417 seconds=3.7
[CNN] Fusion/lovo fold=05 epoch 02/70: train_loss=3.1419 train_acc=0.1569 val_loss=4.2297 val_acc=0.0641 seconds=0.9
[CNN] Fusion/lovo fold=05 epoch 03/70: train_loss=2.6391 train_acc=0.2361 val_loss=4.1284 val_acc=0.0802 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 04/70: train_loss=2.2999 train_acc=0.3184 val_loss=4.4519 val_acc=0.0770 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 05/70: train_loss=2.0636 train_acc=0.3761 val_loss=4.7033 val_acc=0.0827 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 06/70: train_loss=1.9021 train_acc=0.4155 val_loss=4.7908 val_acc=0.0847 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 07/70: train_loss=1.7373 train_acc=0.4707 val_loss=4.9838 val_acc=0.0738 seconds=0.9
[CNN] Fusion/lovo fold=05 epoch 08/70: train_loss=1.6151 train_acc=0.4978 val_loss=5.3624 val_acc=0.0898 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 09/70: train_loss=1.4868 train_acc=0.5459 val_loss=5.8687 val_acc=0.0731 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 10/70: train_loss=1.4009 train_acc=0.5568 val_loss=5.4814 val_acc=0.0879 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 11/70: train_loss=1.3029 train_acc=0.5951 val_loss=5.7808 val_acc=0.0840 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 12/70: train_loss=1.2278 train_acc=0.6198 val_loss=5.9444 val_acc=0.0930 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 13/70: train_loss=1.1502 train_acc=0.6287 val_loss=6.0083 val_acc=0.0904 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 14/70: train_loss=1.0787 train_acc=0.6581 val_loss=6.7040 val_acc=0.0847 seconds=0.7
[CNN] Fusion/lovo fold=05 epoch 15/70: train_loss=1.0168 train_acc=0.6792 val_loss=6.7198 val_acc=0.0898 seconds=0.7
[CNN] Fusion/lovo fold=05 epoch 16/70: train_loss=0.9343 train_acc=0.7050 val_loss=6.3770 val_acc=0.0975 seconds=0.7
[CNN] Fusion/lovo fold=05 epoch 17/70: train_loss=0.8702 train_acc=0.7240 val_loss=6.8729 val_acc=0.0962 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 18/70: train_loss=0.8432 train_acc=0.7320 val_loss=6.7192 val_acc=0.0949 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 19/70: train_loss=0.7921 train_acc=0.7447 val_loss=7.1280 val_acc=0.0911 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 20/70: train_loss=0.7479 train_acc=0.7625 val_loss=6.9581 val_acc=0.0994 seconds=0.7
[CNN] Fusion/lovo fold=05 epoch 21/70: train_loss=0.7077 train_acc=0.7752 val_loss=8.1798 val_acc=0.0783 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 22/70: train_loss=0.6814 train_acc=0.7791 val_loss=7.7458 val_acc=0.0892 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 23/70: train_loss=0.6332 train_acc=0.7948 val_loss=8.1609 val_acc=0.0795 seconds=0.7
[CNN] Fusion/lovo fold=05 epoch 24/70: train_loss=0.6131 train_acc=0.8048 val_loss=8.7152 val_acc=0.0815 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 25/70: train_loss=0.5894 train_acc=0.8104 val_loss=8.0671 val_acc=0.0898 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 26/70: train_loss=0.5615 train_acc=0.8210 val_loss=7.8601 val_acc=0.0885 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 27/70: train_loss=0.5414 train_acc=0.8212 val_loss=8.5008 val_acc=0.0892 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 28/70: train_loss=0.5248 train_acc=0.8369 val_loss=8.9114 val_acc=0.0911 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 29/70: train_loss=0.5040 train_acc=0.8398 val_loss=8.2975 val_acc=0.0943 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 30/70: train_loss=0.4863 train_acc=0.8451 val_loss=8.9329 val_acc=0.0898 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 31/70: train_loss=0.4713 train_acc=0.8530 val_loss=8.5441 val_acc=0.1020 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 32/70: train_loss=0.4340 train_acc=0.8595 val_loss=9.3445 val_acc=0.0815 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 33/70: train_loss=0.4480 train_acc=0.8595 val_loss=8.9489 val_acc=0.0911 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 34/70: train_loss=0.4076 train_acc=0.8676 val_loss=8.9641 val_acc=0.0892 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 35/70: train_loss=0.3968 train_acc=0.8741 val_loss=9.1508 val_acc=0.0924 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 36/70: train_loss=0.3924 train_acc=0.8787 val_loss=8.3648 val_acc=0.1026 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 37/70: train_loss=0.3591 train_acc=0.8895 val_loss=8.8076 val_acc=0.1110 seconds=0.7
[CNN] Fusion/lovo fold=05 epoch 38/70: train_loss=0.3633 train_acc=0.8824 val_loss=9.3582 val_acc=0.0866 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 39/70: train_loss=0.3556 train_acc=0.8835 val_loss=10.2376 val_acc=0.0879 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 40/70: train_loss=0.3318 train_acc=0.8997 val_loss=9.6461 val_acc=0.0994 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 41/70: train_loss=0.3196 train_acc=0.8992 val_loss=9.7160 val_acc=0.0866 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 42/70: train_loss=0.3158 train_acc=0.8999 val_loss=10.0606 val_acc=0.0802 seconds=0.9
[CNN] Fusion/lovo fold=05 epoch 43/70: train_loss=0.3078 train_acc=0.8989 val_loss=10.9628 val_acc=0.0879 seconds=0.9
[CNN] Fusion/lovo fold=05 epoch 44/70: train_loss=0.3007 train_acc=0.9030 val_loss=10.1909 val_acc=0.0943 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 45/70: train_loss=0.2786 train_acc=0.9146 val_loss=9.8585 val_acc=0.0892 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 46/70: train_loss=0.2869 train_acc=0.9108 val_loss=9.7872 val_acc=0.1090 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 47/70: train_loss=0.2794 train_acc=0.9110 val_loss=10.3069 val_acc=0.0911 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 48/70: train_loss=0.2727 train_acc=0.9139 val_loss=11.3239 val_acc=0.0789 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 49/70: train_loss=0.2659 train_acc=0.9162 val_loss=9.9500 val_acc=0.0981 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 50/70: train_loss=0.2387 train_acc=0.9242 val_loss=10.1958 val_acc=0.0917 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 51/70: train_loss=0.2453 train_acc=0.9213 val_loss=10.7841 val_acc=0.0802 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 52/70: train_loss=0.2418 train_acc=0.9185 val_loss=10.3314 val_acc=0.0924 seconds=0.7
[CNN] early stopping at epoch 52; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__fusion__lovo__ebl-session__s43__a89b5d__fold-05.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__fusion__lovo__ebl-session__s43__a89b5d/training_curves__fold-05.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=06 validation_user=05 (entire user, deterministic rotation)
[CNN] Fusion/lovo fold=06 parameters=138708
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] Fusion/lovo fold=06 epoch 01/70: train_loss=3.7969 train_acc=0.0772 val_loss=3.9589 val_acc=0.0505 seconds=3.1
[CNN] Fusion/lovo fold=06 epoch 02/70: train_loss=3.1774 train_acc=0.1511 val_loss=4.3483 val_acc=0.0693 seconds=0.9
[CNN] Fusion/lovo fold=06 epoch 03/70: train_loss=2.7111 train_acc=0.2288 val_loss=4.1094 val_acc=0.0774 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 04/70: train_loss=2.3613 train_acc=0.3113 val_loss=4.3008 val_acc=0.1319 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 05/70: train_loss=2.0842 train_acc=0.3726 val_loss=4.3230 val_acc=0.1359 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 06/70: train_loss=1.8401 train_acc=0.4459 val_loss=4.9575 val_acc=0.1285 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 07/70: train_loss=1.6802 train_acc=0.4845 val_loss=4.6304 val_acc=0.1191 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 08/70: train_loss=1.5599 train_acc=0.5144 val_loss=4.8481 val_acc=0.1211 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 09/70: train_loss=1.4348 train_acc=0.5533 val_loss=5.0049 val_acc=0.1366 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 10/70: train_loss=1.3451 train_acc=0.5873 val_loss=5.3295 val_acc=0.1339 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 11/70: train_loss=1.2561 train_acc=0.6114 val_loss=5.4896 val_acc=0.1137 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 12/70: train_loss=1.1853 train_acc=0.6241 val_loss=5.7837 val_acc=0.1279 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 13/70: train_loss=1.1066 train_acc=0.6511 val_loss=5.6550 val_acc=0.1380 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 14/70: train_loss=1.0430 train_acc=0.6747 val_loss=5.4659 val_acc=0.1400 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 15/70: train_loss=0.9874 train_acc=0.6873 val_loss=5.6842 val_acc=0.1406 seconds=0.7
[CNN] Fusion/lovo fold=06 epoch 16/70: train_loss=0.9307 train_acc=0.7010 val_loss=5.9817 val_acc=0.1406 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 17/70: train_loss=0.8879 train_acc=0.7190 val_loss=6.1353 val_acc=0.1373 seconds=0.7
[CNN] Fusion/lovo fold=06 epoch 18/70: train_loss=0.8228 train_acc=0.7377 val_loss=6.1444 val_acc=0.1447 seconds=0.7
[CNN] Fusion/lovo fold=06 epoch 19/70: train_loss=0.7869 train_acc=0.7468 val_loss=6.1047 val_acc=0.1427 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 20/70: train_loss=0.7396 train_acc=0.7673 val_loss=6.1424 val_acc=0.1534 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 21/70: train_loss=0.7052 train_acc=0.7736 val_loss=6.0689 val_acc=0.1602 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 22/70: train_loss=0.6828 train_acc=0.7781 val_loss=6.1680 val_acc=0.1514 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 23/70: train_loss=0.6417 train_acc=0.7913 val_loss=6.4378 val_acc=0.1568 seconds=0.9
[CNN] Fusion/lovo fold=06 epoch 24/70: train_loss=0.6253 train_acc=0.7974 val_loss=6.0360 val_acc=0.1642 seconds=0.9
[CNN] Fusion/lovo fold=06 epoch 25/70: train_loss=0.5965 train_acc=0.8104 val_loss=6.5166 val_acc=0.1528 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 26/70: train_loss=0.5624 train_acc=0.8204 val_loss=6.8676 val_acc=0.1380 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 27/70: train_loss=0.5405 train_acc=0.8281 val_loss=6.2731 val_acc=0.1575 seconds=0.7
[CNN] Fusion/lovo fold=06 epoch 28/70: train_loss=0.5236 train_acc=0.8317 val_loss=6.5663 val_acc=0.1507 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 29/70: train_loss=0.5105 train_acc=0.8317 val_loss=7.2340 val_acc=0.1373 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 30/70: train_loss=0.4933 train_acc=0.8410 val_loss=6.5746 val_acc=0.1588 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 31/70: train_loss=0.4585 train_acc=0.8525 val_loss=7.2402 val_acc=0.1561 seconds=0.9
[CNN] Fusion/lovo fold=06 epoch 32/70: train_loss=0.4449 train_acc=0.8587 val_loss=7.5552 val_acc=0.1454 seconds=0.9
[CNN] Fusion/lovo fold=06 epoch 33/70: train_loss=0.4466 train_acc=0.8495 val_loss=7.3612 val_acc=0.1608 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 34/70: train_loss=0.4443 train_acc=0.8564 val_loss=7.0184 val_acc=0.1615 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 35/70: train_loss=0.4141 train_acc=0.8664 val_loss=7.3554 val_acc=0.1608 seconds=0.9
[CNN] Fusion/lovo fold=06 epoch 36/70: train_loss=0.4054 train_acc=0.8657 val_loss=7.0919 val_acc=0.1615 seconds=0.9
[CNN] Fusion/lovo fold=06 epoch 37/70: train_loss=0.3891 train_acc=0.8770 val_loss=7.7638 val_acc=0.1380 seconds=0.9
[CNN] Fusion/lovo fold=06 epoch 38/70: train_loss=0.3749 train_acc=0.8741 val_loss=7.7745 val_acc=0.1501 seconds=0.9
[CNN] Fusion/lovo fold=06 epoch 39/70: train_loss=0.3618 train_acc=0.8827 val_loss=7.0435 val_acc=0.1642 seconds=0.8
[CNN] early stopping at epoch 39; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__fusion__lovo__ebl-session__s43__a89b5d__fold-06.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__fusion__lovo__ebl-session__s43__a89b5d/training_curves__fold-06.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__fusion__lovo__ebl-session__s43__a89b5d.parquet
[results upsert] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/runs_folds.csv: 48 row(s)
[DL LOVO] seed=43 fold mean position_accuracy=0.0979 +/- 0.0316; pooled=0.0998
[DL GPU] run_id=dl__cnn__fusion__lovo__ebl-session__s43__a89b5d peak_cuda_memory_bytes=978418688
[results upsert] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/runs.csv: 32 row(s)
Seeds: random=44, numpy=44, torch=44
[trial filter] split=lovo trials=['01'] kept=8889/13568
[trial filter] split=lovo trials=['01'] kept=8889/8889
[protocol] split=lovo fold=01 trials_used=['01'] n_train=7331 n_test=1558 users=['01', '02', '03', '04', '05', '06'] train_users=['02', '03', '04', '05', '06'] test_users=['01']
[protocol] split=lovo fold=02 trials_used=['01'] n_train=7478 n_test=1411 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '03', '04', '05', '06'] test_users=['02']
[protocol] split=lovo fold=03 trials_used=['01'] n_train=7303 n_test=1586 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '04', '05', '06'] test_users=['03']
[protocol] split=lovo fold=04 trials_used=['01'] n_train=7330 n_test=1559 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '05', '06'] test_users=['04']
[protocol] split=lovo fold=05 trials_used=['01'] n_train=7403 n_test=1486 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '06'] test_users=['05']
[protocol] split=lovo fold=06 trials_used=['01'] n_train=7600 n_test=1289 users=['01', '02', '03', '04', '05', '06'] train_users=['01', '02', '03', '04', '05'] test_users=['06']
[DL LOVO] held_out_user=01 validation_user=06 (entire user, deterministic rotation)
[CNN] Fusion/lovo fold=01 parameters=138708
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] Fusion/lovo fold=01 epoch 01/70: train_loss=3.7880 train_acc=0.0765 val_loss=3.8819 val_acc=0.0419 seconds=3.5
[CNN] Fusion/lovo fold=01 epoch 02/70: train_loss=3.1686 train_acc=0.1617 val_loss=3.4989 val_acc=0.0915 seconds=0.9
[CNN] Fusion/lovo fold=01 epoch 03/70: train_loss=2.6114 train_acc=0.2598 val_loss=4.2587 val_acc=0.0908 seconds=0.8
[CNN] Fusion/lovo fold=01 epoch 04/70: train_loss=2.2387 train_acc=0.3419 val_loss=4.5984 val_acc=0.0815 seconds=0.8
[CNN] Fusion/lovo fold=01 epoch 05/70: train_loss=1.9625 train_acc=0.4098 val_loss=4.3703 val_acc=0.1032 seconds=0.8
[CNN] Fusion/lovo fold=01 epoch 06/70: train_loss=1.7671 train_acc=0.4643 val_loss=5.0233 val_acc=0.1071 seconds=0.8
[CNN] Fusion/lovo fold=01 epoch 07/70: train_loss=1.6311 train_acc=0.4972 val_loss=5.6192 val_acc=0.0698 seconds=0.8
[CNN] Fusion/lovo fold=01 epoch 08/70: train_loss=1.5078 train_acc=0.5285 val_loss=5.6651 val_acc=0.0698 seconds=0.8
[CNN] Fusion/lovo fold=01 epoch 09/70: train_loss=1.3828 train_acc=0.5677 val_loss=5.6298 val_acc=0.1009 seconds=0.8
[CNN] Fusion/lovo fold=01 epoch 10/70: train_loss=1.3134 train_acc=0.5834 val_loss=5.7616 val_acc=0.0799 seconds=0.7
[CNN] Fusion/lovo fold=01 epoch 11/70: train_loss=1.2056 train_acc=0.6246 val_loss=6.3892 val_acc=0.0652 seconds=0.8
[CNN] Fusion/lovo fold=01 epoch 12/70: train_loss=1.1274 train_acc=0.6452 val_loss=6.5432 val_acc=0.0667 seconds=0.8
[CNN] Fusion/lovo fold=01 epoch 13/70: train_loss=1.0442 train_acc=0.6682 val_loss=6.3266 val_acc=0.0861 seconds=0.7
[CNN] Fusion/lovo fold=01 epoch 14/70: train_loss=1.0078 train_acc=0.6744 val_loss=6.1353 val_acc=0.1156 seconds=0.7
[CNN] Fusion/lovo fold=01 epoch 15/70: train_loss=0.9297 train_acc=0.6968 val_loss=5.9448 val_acc=0.1171 seconds=0.8
[CNN] Fusion/lovo fold=01 epoch 16/70: train_loss=0.8853 train_acc=0.7208 val_loss=7.0464 val_acc=0.0822 seconds=0.7
[CNN] Fusion/lovo fold=01 epoch 17/70: train_loss=0.8270 train_acc=0.7350 val_loss=6.2375 val_acc=0.1109 seconds=0.8
[CNN] Fusion/lovo fold=01 epoch 18/70: train_loss=0.7750 train_acc=0.7531 val_loss=6.9088 val_acc=0.1210 seconds=0.8
[CNN] Fusion/lovo fold=01 epoch 19/70: train_loss=0.7243 train_acc=0.7723 val_loss=7.2420 val_acc=0.0993 seconds=0.7
[CNN] Fusion/lovo fold=01 epoch 20/70: train_loss=0.7108 train_acc=0.7676 val_loss=7.0255 val_acc=0.1179 seconds=0.8
[CNN] Fusion/lovo fold=01 epoch 21/70: train_loss=0.6625 train_acc=0.7885 val_loss=8.0416 val_acc=0.0784 seconds=0.8
[CNN] Fusion/lovo fold=01 epoch 22/70: train_loss=0.6517 train_acc=0.7850 val_loss=7.5897 val_acc=0.0846 seconds=0.7
[CNN] Fusion/lovo fold=01 epoch 23/70: train_loss=0.6119 train_acc=0.7984 val_loss=7.2732 val_acc=0.0931 seconds=0.8
[CNN] Fusion/lovo fold=01 epoch 24/70: train_loss=0.5904 train_acc=0.8034 val_loss=7.2035 val_acc=0.0954 seconds=0.8
[CNN] Fusion/lovo fold=01 epoch 25/70: train_loss=0.5562 train_acc=0.8199 val_loss=8.7898 val_acc=0.0690 seconds=0.8
[CNN] Fusion/lovo fold=01 epoch 26/70: train_loss=0.5330 train_acc=0.8252 val_loss=7.7198 val_acc=0.0978 seconds=0.8
[CNN] Fusion/lovo fold=01 epoch 27/70: train_loss=0.5160 train_acc=0.8348 val_loss=8.5111 val_acc=0.0784 seconds=0.8
[CNN] Fusion/lovo fold=01 epoch 28/70: train_loss=0.4991 train_acc=0.8361 val_loss=8.1494 val_acc=0.1078 seconds=0.8
[CNN] Fusion/lovo fold=01 epoch 29/70: train_loss=0.4754 train_acc=0.8452 val_loss=8.0106 val_acc=0.1055 seconds=0.8
[CNN] Fusion/lovo fold=01 epoch 30/70: train_loss=0.4686 train_acc=0.8520 val_loss=8.5197 val_acc=0.1055 seconds=0.8
[CNN] Fusion/lovo fold=01 epoch 31/70: train_loss=0.4506 train_acc=0.8527 val_loss=8.6180 val_acc=0.0900 seconds=0.8
[CNN] Fusion/lovo fold=01 epoch 32/70: train_loss=0.4391 train_acc=0.8618 val_loss=8.8802 val_acc=0.0776 seconds=0.8
[CNN] Fusion/lovo fold=01 epoch 33/70: train_loss=0.4128 train_acc=0.8726 val_loss=8.0097 val_acc=0.0946 seconds=0.8
[CNN] early stopping at epoch 33; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__fusion__lovo__ebl-session__s44__7b9bf2__fold-01.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__fusion__lovo__ebl-session__s44__7b9bf2/training_curves__fold-01.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=02 validation_user=01 (entire user, deterministic rotation)
[CNN] Fusion/lovo fold=02 parameters=138708
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] Fusion/lovo fold=02 epoch 01/70: train_loss=3.8196 train_acc=0.0853 val_loss=3.8352 val_acc=0.0513 seconds=3.4
[CNN] Fusion/lovo fold=02 epoch 02/70: train_loss=3.1541 train_acc=0.1819 val_loss=3.9134 val_acc=0.0629 seconds=0.8
[CNN] Fusion/lovo fold=02 epoch 03/70: train_loss=2.5775 train_acc=0.2713 val_loss=4.7870 val_acc=0.0745 seconds=0.8
[CNN] Fusion/lovo fold=02 epoch 04/70: train_loss=2.2337 train_acc=0.3412 val_loss=5.4751 val_acc=0.0809 seconds=0.9
[CNN] Fusion/lovo fold=02 epoch 05/70: train_loss=1.9958 train_acc=0.3948 val_loss=6.2049 val_acc=0.0822 seconds=0.9
[CNN] Fusion/lovo fold=02 epoch 06/70: train_loss=1.7905 train_acc=0.4613 val_loss=6.0565 val_acc=0.0969 seconds=0.9
[CNN] Fusion/lovo fold=02 epoch 07/70: train_loss=1.6357 train_acc=0.4939 val_loss=7.0527 val_acc=0.0873 seconds=0.9
[CNN] Fusion/lovo fold=02 epoch 08/70: train_loss=1.5107 train_acc=0.5294 val_loss=8.0172 val_acc=0.0725 seconds=0.9
[CNN] Fusion/lovo fold=02 epoch 09/70: train_loss=1.3831 train_acc=0.5676 val_loss=8.1244 val_acc=0.0944 seconds=0.9
[CNN] Fusion/lovo fold=02 epoch 10/70: train_loss=1.2785 train_acc=0.6007 val_loss=7.9064 val_acc=0.0886 seconds=0.9
[CNN] Fusion/lovo fold=02 epoch 11/70: train_loss=1.1967 train_acc=0.6228 val_loss=7.6193 val_acc=0.0931 seconds=0.9
[CNN] Fusion/lovo fold=02 epoch 12/70: train_loss=1.1169 train_acc=0.6405 val_loss=8.9490 val_acc=0.0963 seconds=0.9
[CNN] Fusion/lovo fold=02 epoch 13/70: train_loss=1.0423 train_acc=0.6671 val_loss=7.8409 val_acc=0.0937 seconds=0.8
[CNN] Fusion/lovo fold=02 epoch 14/70: train_loss=0.9753 train_acc=0.6956 val_loss=9.0187 val_acc=0.0828 seconds=0.8
[CNN] Fusion/lovo fold=02 epoch 15/70: train_loss=0.9355 train_acc=0.7061 val_loss=9.0284 val_acc=0.0828 seconds=0.9
[CNN] Fusion/lovo fold=02 epoch 16/70: train_loss=0.8606 train_acc=0.7312 val_loss=9.8244 val_acc=0.0899 seconds=0.8
[CNN] Fusion/lovo fold=02 epoch 17/70: train_loss=0.8094 train_acc=0.7402 val_loss=9.1027 val_acc=0.0988 seconds=0.9
[CNN] Fusion/lovo fold=02 epoch 18/70: train_loss=0.7657 train_acc=0.7559 val_loss=9.1787 val_acc=0.1040 seconds=0.8
[CNN] Fusion/lovo fold=02 epoch 19/70: train_loss=0.7422 train_acc=0.7640 val_loss=9.4577 val_acc=0.0931 seconds=0.8
[CNN] Fusion/lovo fold=02 epoch 20/70: train_loss=0.7157 train_acc=0.7713 val_loss=9.2195 val_acc=0.0944 seconds=0.8
[CNN] Fusion/lovo fold=02 epoch 21/70: train_loss=0.6750 train_acc=0.7875 val_loss=9.4567 val_acc=0.0950 seconds=0.7
[CNN] Fusion/lovo fold=02 epoch 22/70: train_loss=0.6507 train_acc=0.7966 val_loss=9.0891 val_acc=0.0937 seconds=0.8
[CNN] Fusion/lovo fold=02 epoch 23/70: train_loss=0.5890 train_acc=0.8154 val_loss=9.8238 val_acc=0.0879 seconds=0.8
[CNN] Fusion/lovo fold=02 epoch 24/70: train_loss=0.5773 train_acc=0.8166 val_loss=9.8930 val_acc=0.0944 seconds=0.7
[CNN] Fusion/lovo fold=02 epoch 25/70: train_loss=0.5594 train_acc=0.8213 val_loss=9.6349 val_acc=0.0963 seconds=0.8
[CNN] Fusion/lovo fold=02 epoch 26/70: train_loss=0.5383 train_acc=0.8304 val_loss=10.1753 val_acc=0.0969 seconds=0.9
[CNN] Fusion/lovo fold=02 epoch 27/70: train_loss=0.5073 train_acc=0.8399 val_loss=10.0705 val_acc=0.1008 seconds=0.8
[CNN] Fusion/lovo fold=02 epoch 28/70: train_loss=0.4991 train_acc=0.8385 val_loss=10.5199 val_acc=0.0937 seconds=0.8
[CNN] Fusion/lovo fold=02 epoch 29/70: train_loss=0.4294 train_acc=0.8654 val_loss=10.4661 val_acc=0.1053 seconds=0.8
[CNN] Fusion/lovo fold=02 epoch 30/70: train_loss=0.4425 train_acc=0.8559 val_loss=10.7330 val_acc=0.1059 seconds=0.8
[CNN] Fusion/lovo fold=02 epoch 31/70: train_loss=0.4415 train_acc=0.8578 val_loss=10.5286 val_acc=0.1085 seconds=0.8
[CNN] Fusion/lovo fold=02 epoch 32/70: train_loss=0.4143 train_acc=0.8676 val_loss=11.0285 val_acc=0.0963 seconds=0.8
[CNN] Fusion/lovo fold=02 epoch 33/70: train_loss=0.3788 train_acc=0.8755 val_loss=12.0112 val_acc=0.0963 seconds=0.8
[CNN] Fusion/lovo fold=02 epoch 34/70: train_loss=0.4139 train_acc=0.8703 val_loss=11.7078 val_acc=0.0841 seconds=0.8
[CNN] Fusion/lovo fold=02 epoch 35/70: train_loss=0.3963 train_acc=0.8747 val_loss=12.0934 val_acc=0.1008 seconds=0.8
[CNN] Fusion/lovo fold=02 epoch 36/70: train_loss=0.3675 train_acc=0.8821 val_loss=12.3007 val_acc=0.0911 seconds=0.8
[CNN] Fusion/lovo fold=02 epoch 37/70: train_loss=0.3506 train_acc=0.8894 val_loss=11.5202 val_acc=0.0937 seconds=0.8
[CNN] Fusion/lovo fold=02 epoch 38/70: train_loss=0.3157 train_acc=0.9035 val_loss=12.5098 val_acc=0.0828 seconds=0.8
[CNN] Fusion/lovo fold=02 epoch 39/70: train_loss=0.3180 train_acc=0.9020 val_loss=12.7389 val_acc=0.0822 seconds=0.8
[CNN] Fusion/lovo fold=02 epoch 40/70: train_loss=0.3715 train_acc=0.8770 val_loss=12.2857 val_acc=0.0879 seconds=0.7
[CNN] Fusion/lovo fold=02 epoch 41/70: train_loss=0.3286 train_acc=0.8941 val_loss=11.8671 val_acc=0.0988 seconds=0.8
[CNN] Fusion/lovo fold=02 epoch 42/70: train_loss=0.2947 train_acc=0.9090 val_loss=12.5444 val_acc=0.0976 seconds=0.8
[CNN] Fusion/lovo fold=02 epoch 43/70: train_loss=0.2898 train_acc=0.9052 val_loss=12.7958 val_acc=0.1001 seconds=0.8
[CNN] Fusion/lovo fold=02 epoch 44/70: train_loss=0.2666 train_acc=0.9198 val_loss=12.9163 val_acc=0.0892 seconds=0.8
[CNN] Fusion/lovo fold=02 epoch 45/70: train_loss=0.2685 train_acc=0.9147 val_loss=12.2343 val_acc=0.0937 seconds=0.7
[CNN] Fusion/lovo fold=02 epoch 46/70: train_loss=0.2662 train_acc=0.9187 val_loss=13.9601 val_acc=0.0988 seconds=0.8
[CNN] early stopping at epoch 46; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__fusion__lovo__ebl-session__s44__7b9bf2__fold-02.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__fusion__lovo__ebl-session__s44__7b9bf2/training_curves__fold-02.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=03 validation_user=02 (entire user, deterministic rotation)
[CNN] Fusion/lovo fold=03 parameters=138708
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] Fusion/lovo fold=03 epoch 01/70: train_loss=3.7698 train_acc=0.0825 val_loss=3.7669 val_acc=0.0439 seconds=3.4
[CNN] Fusion/lovo fold=03 epoch 02/70: train_loss=3.1233 train_acc=0.1578 val_loss=4.4048 val_acc=0.0319 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 03/70: train_loss=2.7110 train_acc=0.2201 val_loss=4.8736 val_acc=0.0439 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 04/70: train_loss=2.4521 train_acc=0.2772 val_loss=4.9348 val_acc=0.0489 seconds=0.7
[CNN] Fusion/lovo fold=03 epoch 05/70: train_loss=2.2500 train_acc=0.3252 val_loss=5.5455 val_acc=0.0397 seconds=0.7
[CNN] Fusion/lovo fold=03 epoch 06/70: train_loss=2.0967 train_acc=0.3678 val_loss=5.8656 val_acc=0.0390 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 07/70: train_loss=1.9298 train_acc=0.4109 val_loss=6.1221 val_acc=0.0397 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 08/70: train_loss=1.8224 train_acc=0.4465 val_loss=6.2267 val_acc=0.0425 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 09/70: train_loss=1.7445 train_acc=0.4734 val_loss=6.2312 val_acc=0.0340 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 10/70: train_loss=1.6540 train_acc=0.4939 val_loss=7.0430 val_acc=0.0376 seconds=0.7
[CNN] Fusion/lovo fold=03 epoch 11/70: train_loss=1.5337 train_acc=0.5304 val_loss=6.5478 val_acc=0.0496 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 12/70: train_loss=1.4858 train_acc=0.5370 val_loss=7.0620 val_acc=0.0482 seconds=0.7
[CNN] Fusion/lovo fold=03 epoch 13/70: train_loss=1.4088 train_acc=0.5694 val_loss=7.0237 val_acc=0.0560 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 14/70: train_loss=1.3372 train_acc=0.5818 val_loss=7.8493 val_acc=0.0340 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 15/70: train_loss=1.2349 train_acc=0.6203 val_loss=7.8132 val_acc=0.0503 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 16/70: train_loss=1.2605 train_acc=0.6110 val_loss=7.8792 val_acc=0.0418 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 17/70: train_loss=1.1489 train_acc=0.6477 val_loss=8.5706 val_acc=0.0461 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 18/70: train_loss=1.2089 train_acc=0.6300 val_loss=8.1354 val_acc=0.0510 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 19/70: train_loss=1.0463 train_acc=0.6808 val_loss=9.1085 val_acc=0.0524 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 20/70: train_loss=1.0565 train_acc=0.6743 val_loss=8.7255 val_acc=0.0546 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 21/70: train_loss=1.0248 train_acc=0.6843 val_loss=8.8641 val_acc=0.0539 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 22/70: train_loss=0.9269 train_acc=0.7130 val_loss=9.1441 val_acc=0.0532 seconds=0.7
[CNN] Fusion/lovo fold=03 epoch 23/70: train_loss=1.0023 train_acc=0.6921 val_loss=9.1445 val_acc=0.0659 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 24/70: train_loss=0.8991 train_acc=0.7259 val_loss=9.2930 val_acc=0.0489 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 25/70: train_loss=1.0055 train_acc=0.6896 val_loss=9.1913 val_acc=0.0581 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 26/70: train_loss=0.8625 train_acc=0.7368 val_loss=9.2061 val_acc=0.0496 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 27/70: train_loss=0.7954 train_acc=0.7537 val_loss=8.9458 val_acc=0.0546 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 28/70: train_loss=0.7365 train_acc=0.7749 val_loss=9.2072 val_acc=0.0546 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 29/70: train_loss=0.8867 train_acc=0.7155 val_loss=9.3663 val_acc=0.0567 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 30/70: train_loss=0.7668 train_acc=0.7607 val_loss=9.2072 val_acc=0.0546 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 31/70: train_loss=0.8190 train_acc=0.7469 val_loss=9.4494 val_acc=0.0539 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 32/70: train_loss=0.6824 train_acc=0.7953 val_loss=9.7211 val_acc=0.0567 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 33/70: train_loss=0.7866 train_acc=0.7541 val_loss=9.2303 val_acc=0.0737 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 34/70: train_loss=0.7188 train_acc=0.7739 val_loss=10.0550 val_acc=0.0617 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 35/70: train_loss=0.6676 train_acc=0.7926 val_loss=10.7467 val_acc=0.0609 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 36/70: train_loss=0.6403 train_acc=0.8016 val_loss=9.9656 val_acc=0.0709 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 37/70: train_loss=0.6881 train_acc=0.7824 val_loss=10.3297 val_acc=0.0617 seconds=0.7
[CNN] Fusion/lovo fold=03 epoch 38/70: train_loss=0.7474 train_acc=0.7593 val_loss=10.4006 val_acc=0.0702 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 39/70: train_loss=0.5924 train_acc=0.8155 val_loss=10.5012 val_acc=0.0673 seconds=0.7
[CNN] Fusion/lovo fold=03 epoch 40/70: train_loss=0.5726 train_acc=0.8184 val_loss=10.6630 val_acc=0.0617 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 41/70: train_loss=0.6770 train_acc=0.7807 val_loss=10.9420 val_acc=0.0617 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 42/70: train_loss=0.5838 train_acc=0.8165 val_loss=10.7078 val_acc=0.0652 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 43/70: train_loss=0.6247 train_acc=0.7992 val_loss=11.0101 val_acc=0.0560 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 44/70: train_loss=0.6999 train_acc=0.7831 val_loss=10.0270 val_acc=0.0617 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 45/70: train_loss=0.5359 train_acc=0.8357 val_loss=10.5207 val_acc=0.0680 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 46/70: train_loss=0.5019 train_acc=0.8433 val_loss=10.7600 val_acc=0.0652 seconds=0.8
[CNN] Fusion/lovo fold=03 epoch 47/70: train_loss=0.6458 train_acc=0.7902 val_loss=10.5523 val_acc=0.0581 seconds=0.7
[CNN] Fusion/lovo fold=03 epoch 48/70: train_loss=0.5609 train_acc=0.8262 val_loss=10.7729 val_acc=0.0574 seconds=0.7
[CNN] early stopping at epoch 48; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__fusion__lovo__ebl-session__s44__7b9bf2__fold-03.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__fusion__lovo__ebl-session__s44__7b9bf2/training_curves__fold-03.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=04 validation_user=03 (entire user, deterministic rotation)
[CNN] Fusion/lovo fold=04 parameters=138708
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] Fusion/lovo fold=04 epoch 01/70: train_loss=3.8300 train_acc=0.0609 val_loss=3.8598 val_acc=0.0429 seconds=3.2
[CNN] Fusion/lovo fold=04 epoch 02/70: train_loss=3.2594 train_acc=0.1433 val_loss=4.1188 val_acc=0.0631 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 03/70: train_loss=2.7472 train_acc=0.2150 val_loss=4.2531 val_acc=0.1047 seconds=0.7
[CNN] Fusion/lovo fold=04 epoch 04/70: train_loss=2.4148 train_acc=0.2923 val_loss=4.3827 val_acc=0.1097 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 05/70: train_loss=2.1639 train_acc=0.3484 val_loss=4.3786 val_acc=0.1166 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 06/70: train_loss=1.9748 train_acc=0.3985 val_loss=4.9444 val_acc=0.1047 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 07/70: train_loss=1.8170 train_acc=0.4385 val_loss=4.8776 val_acc=0.1311 seconds=0.7
[CNN] Fusion/lovo fold=04 epoch 08/70: train_loss=1.6721 train_acc=0.4883 val_loss=5.1545 val_acc=0.1286 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 09/70: train_loss=1.5494 train_acc=0.5265 val_loss=5.3392 val_acc=0.1223 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 10/70: train_loss=1.4438 train_acc=0.5533 val_loss=5.5763 val_acc=0.1110 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 11/70: train_loss=1.3487 train_acc=0.5808 val_loss=5.7740 val_acc=0.1072 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 12/70: train_loss=1.2337 train_acc=0.6166 val_loss=5.8534 val_acc=0.1192 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 13/70: train_loss=1.1719 train_acc=0.6370 val_loss=6.1724 val_acc=0.1135 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 14/70: train_loss=1.0839 train_acc=0.6621 val_loss=6.5671 val_acc=0.1248 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 15/70: train_loss=1.0059 train_acc=0.6790 val_loss=6.4586 val_acc=0.1135 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 16/70: train_loss=0.9538 train_acc=0.7039 val_loss=6.8282 val_acc=0.1230 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 17/70: train_loss=0.8862 train_acc=0.7220 val_loss=6.7117 val_acc=0.1122 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 18/70: train_loss=0.8491 train_acc=0.7354 val_loss=6.8950 val_acc=0.1198 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 19/70: train_loss=0.8035 train_acc=0.7491 val_loss=7.1647 val_acc=0.1129 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 20/70: train_loss=0.7600 train_acc=0.7669 val_loss=7.5212 val_acc=0.0996 seconds=0.7
[CNN] Fusion/lovo fold=04 epoch 21/70: train_loss=0.7166 train_acc=0.7745 val_loss=7.8254 val_acc=0.0990 seconds=0.8
[CNN] Fusion/lovo fold=04 epoch 22/70: train_loss=0.6725 train_acc=0.7909 val_loss=7.7696 val_acc=0.1040 seconds=0.7
[CNN] early stopping at epoch 22; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__fusion__lovo__ebl-session__s44__7b9bf2__fold-04.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__fusion__lovo__ebl-session__s44__7b9bf2/training_curves__fold-04.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=05 validation_user=04 (entire user, deterministic rotation)
[CNN] Fusion/lovo fold=05 parameters=138708
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] Fusion/lovo fold=05 epoch 01/70: train_loss=3.7878 train_acc=0.0659 val_loss=3.9972 val_acc=0.0378 seconds=3.4
[CNN] Fusion/lovo fold=05 epoch 02/70: train_loss=3.1692 train_acc=0.1396 val_loss=4.0164 val_acc=0.0827 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 03/70: train_loss=2.6948 train_acc=0.2290 val_loss=3.9959 val_acc=0.0635 seconds=0.7
[CNN] Fusion/lovo fold=05 epoch 04/70: train_loss=2.3647 train_acc=0.3039 val_loss=4.4682 val_acc=0.0789 seconds=0.7
[CNN] Fusion/lovo fold=05 epoch 05/70: train_loss=2.1461 train_acc=0.3638 val_loss=4.7693 val_acc=0.0680 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 06/70: train_loss=1.9524 train_acc=0.4162 val_loss=4.9437 val_acc=0.0718 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 07/70: train_loss=1.7877 train_acc=0.4505 val_loss=5.2221 val_acc=0.0622 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 08/70: train_loss=1.6418 train_acc=0.4952 val_loss=5.5081 val_acc=0.0616 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 09/70: train_loss=1.5316 train_acc=0.5322 val_loss=5.5527 val_acc=0.0738 seconds=0.7
[CNN] Fusion/lovo fold=05 epoch 10/70: train_loss=1.4261 train_acc=0.5582 val_loss=5.6129 val_acc=0.0680 seconds=0.7
[CNN] Fusion/lovo fold=05 epoch 11/70: train_loss=1.3298 train_acc=0.5821 val_loss=5.8187 val_acc=0.0725 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 12/70: train_loss=1.2426 train_acc=0.6131 val_loss=6.0278 val_acc=0.0680 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 13/70: train_loss=1.1718 train_acc=0.6417 val_loss=6.0926 val_acc=0.0802 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 14/70: train_loss=1.1058 train_acc=0.6634 val_loss=6.8675 val_acc=0.0674 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 15/70: train_loss=1.0190 train_acc=0.6826 val_loss=6.5057 val_acc=0.0795 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 16/70: train_loss=0.9794 train_acc=0.6903 val_loss=6.7982 val_acc=0.0847 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 17/70: train_loss=0.9178 train_acc=0.7060 val_loss=6.8942 val_acc=0.0712 seconds=0.7
[CNN] Fusion/lovo fold=05 epoch 18/70: train_loss=0.8608 train_acc=0.7278 val_loss=7.0180 val_acc=0.0718 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 19/70: train_loss=0.8226 train_acc=0.7401 val_loss=6.8471 val_acc=0.0840 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 20/70: train_loss=0.7831 train_acc=0.7572 val_loss=7.2030 val_acc=0.0738 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 21/70: train_loss=0.7502 train_acc=0.7642 val_loss=6.8898 val_acc=0.0731 seconds=0.7
[CNN] Fusion/lovo fold=05 epoch 22/70: train_loss=0.6835 train_acc=0.7868 val_loss=7.4421 val_acc=0.0783 seconds=0.7
[CNN] Fusion/lovo fold=05 epoch 23/70: train_loss=0.6585 train_acc=0.7906 val_loss=8.1306 val_acc=0.0757 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 24/70: train_loss=0.6341 train_acc=0.7936 val_loss=7.3248 val_acc=0.0860 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 25/70: train_loss=0.6093 train_acc=0.8125 val_loss=7.6215 val_acc=0.0802 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 26/70: train_loss=0.5725 train_acc=0.8133 val_loss=8.1709 val_acc=0.0802 seconds=0.9
[CNN] Fusion/lovo fold=05 epoch 27/70: train_loss=0.5603 train_acc=0.8212 val_loss=7.5017 val_acc=0.0815 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 28/70: train_loss=0.5487 train_acc=0.8227 val_loss=8.5846 val_acc=0.0802 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 29/70: train_loss=0.5256 train_acc=0.8296 val_loss=7.9685 val_acc=0.0808 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 30/70: train_loss=0.4838 train_acc=0.8498 val_loss=8.1195 val_acc=0.0917 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 31/70: train_loss=0.4639 train_acc=0.8508 val_loss=8.3333 val_acc=0.0866 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 32/70: train_loss=0.4496 train_acc=0.8573 val_loss=9.4025 val_acc=0.0744 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 33/70: train_loss=0.4344 train_acc=0.8616 val_loss=8.6475 val_acc=0.0795 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 34/70: train_loss=0.4214 train_acc=0.8657 val_loss=8.5631 val_acc=0.0885 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 35/70: train_loss=0.4048 train_acc=0.8700 val_loss=8.8609 val_acc=0.0776 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 36/70: train_loss=0.4152 train_acc=0.8621 val_loss=9.7294 val_acc=0.0847 seconds=0.9
[CNN] Fusion/lovo fold=05 epoch 37/70: train_loss=0.3821 train_acc=0.8771 val_loss=8.8682 val_acc=0.0827 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 38/70: train_loss=0.3768 train_acc=0.8785 val_loss=8.6629 val_acc=0.0840 seconds=0.9
[CNN] Fusion/lovo fold=05 epoch 39/70: train_loss=0.3599 train_acc=0.8859 val_loss=9.2327 val_acc=0.0917 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 40/70: train_loss=0.3580 train_acc=0.8867 val_loss=8.5661 val_acc=0.0892 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 41/70: train_loss=0.3375 train_acc=0.8984 val_loss=8.6272 val_acc=0.0872 seconds=0.7
[CNN] Fusion/lovo fold=05 epoch 42/70: train_loss=0.3234 train_acc=0.8997 val_loss=9.3651 val_acc=0.0789 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 43/70: train_loss=0.3134 train_acc=0.9031 val_loss=9.0631 val_acc=0.0885 seconds=0.7
[CNN] Fusion/lovo fold=05 epoch 44/70: train_loss=0.2989 train_acc=0.9055 val_loss=9.4634 val_acc=0.0866 seconds=0.8
[CNN] Fusion/lovo fold=05 epoch 45/70: train_loss=0.3038 train_acc=0.9045 val_loss=10.1489 val_acc=0.0744 seconds=0.7
[CNN] early stopping at epoch 45; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__fusion__lovo__ebl-session__s44__7b9bf2__fold-05.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__fusion__lovo__ebl-session__s44__7b9bf2/training_curves__fold-05.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[DL LOVO] held_out_user=06 validation_user=05 (entire user, deterministic rotation)
[CNN] Fusion/lovo fold=06 parameters=138708
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}
[DataLoader] device=cuda settings={'batch_size': 256, 'num_workers': 8, 'pin_memory': True, 'persistent_workers': True, 'prefetch_factor': 4}

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[CNN] Fusion/lovo fold=06 epoch 01/70: train_loss=3.7853 train_acc=0.0734 val_loss=3.9942 val_acc=0.0363 seconds=3.6
[CNN] Fusion/lovo fold=06 epoch 02/70: train_loss=3.1747 train_acc=0.1392 val_loss=4.0586 val_acc=0.0720 seconds=0.7
[CNN] Fusion/lovo fold=06 epoch 03/70: train_loss=2.7596 train_acc=0.2116 val_loss=3.9908 val_acc=0.1009 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 04/70: train_loss=2.4469 train_acc=0.2861 val_loss=4.0235 val_acc=0.1252 seconds=0.9
[CNN] Fusion/lovo fold=06 epoch 05/70: train_loss=2.1893 train_acc=0.3539 val_loss=4.0260 val_acc=0.1218 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 06/70: train_loss=1.9732 train_acc=0.4089 val_loss=4.4952 val_acc=0.1104 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 07/70: train_loss=1.8013 train_acc=0.4601 val_loss=4.8791 val_acc=0.1231 seconds=0.9
[CNN] Fusion/lovo fold=06 epoch 08/70: train_loss=1.6537 train_acc=0.4925 val_loss=4.7076 val_acc=0.1285 seconds=0.9
[CNN] Fusion/lovo fold=06 epoch 09/70: train_loss=1.5261 train_acc=0.5263 val_loss=5.0196 val_acc=0.1245 seconds=0.9
[CNN] Fusion/lovo fold=06 epoch 10/70: train_loss=1.4348 train_acc=0.5494 val_loss=4.5418 val_acc=0.1406 seconds=0.9
[CNN] Fusion/lovo fold=06 epoch 11/70: train_loss=1.3198 train_acc=0.5942 val_loss=5.2473 val_acc=0.1400 seconds=0.9
[CNN] Fusion/lovo fold=06 epoch 12/70: train_loss=1.2181 train_acc=0.6187 val_loss=5.1538 val_acc=0.1339 seconds=0.9
[CNN] Fusion/lovo fold=06 epoch 13/70: train_loss=1.1476 train_acc=0.6392 val_loss=5.3599 val_acc=0.1057 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 14/70: train_loss=1.0835 train_acc=0.6645 val_loss=5.0900 val_acc=0.1413 seconds=0.9
[CNN] Fusion/lovo fold=06 epoch 15/70: train_loss=1.0022 train_acc=0.6868 val_loss=5.6989 val_acc=0.1137 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 16/70: train_loss=0.9464 train_acc=0.6968 val_loss=5.7617 val_acc=0.1231 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 17/70: train_loss=0.9147 train_acc=0.7157 val_loss=6.0444 val_acc=0.1258 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 18/70: train_loss=0.8560 train_acc=0.7354 val_loss=6.0454 val_acc=0.1191 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 19/70: train_loss=0.8090 train_acc=0.7534 val_loss=5.9853 val_acc=0.1339 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 20/70: train_loss=0.7661 train_acc=0.7579 val_loss=6.3810 val_acc=0.1359 seconds=0.9
[CNN] Fusion/lovo fold=06 epoch 21/70: train_loss=0.7066 train_acc=0.7843 val_loss=6.1441 val_acc=0.1366 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 22/70: train_loss=0.6853 train_acc=0.7818 val_loss=6.5259 val_acc=0.1366 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 23/70: train_loss=0.6595 train_acc=0.7879 val_loss=6.7970 val_acc=0.1373 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 24/70: train_loss=0.6152 train_acc=0.8101 val_loss=6.8273 val_acc=0.1312 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 25/70: train_loss=0.5953 train_acc=0.8116 val_loss=6.8744 val_acc=0.1312 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 26/70: train_loss=0.5766 train_acc=0.8168 val_loss=6.7919 val_acc=0.1413 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 27/70: train_loss=0.5465 train_acc=0.8247 val_loss=6.9953 val_acc=0.1454 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 28/70: train_loss=0.5295 train_acc=0.8286 val_loss=7.3984 val_acc=0.1380 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 29/70: train_loss=0.5023 train_acc=0.8430 val_loss=7.1854 val_acc=0.1406 seconds=0.9
[CNN] Fusion/lovo fold=06 epoch 30/70: train_loss=0.4769 train_acc=0.8502 val_loss=7.1382 val_acc=0.1393 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 31/70: train_loss=0.4602 train_acc=0.8497 val_loss=6.8211 val_acc=0.1366 seconds=0.9
[CNN] Fusion/lovo fold=06 epoch 32/70: train_loss=0.4490 train_acc=0.8553 val_loss=7.2965 val_acc=0.1339 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 33/70: train_loss=0.4268 train_acc=0.8690 val_loss=7.4080 val_acc=0.1339 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 34/70: train_loss=0.4266 train_acc=0.8587 val_loss=8.1491 val_acc=0.1359 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 35/70: train_loss=0.3967 train_acc=0.8729 val_loss=8.0599 val_acc=0.1413 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 36/70: train_loss=0.3952 train_acc=0.8746 val_loss=8.2537 val_acc=0.1359 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 37/70: train_loss=0.3864 train_acc=0.8770 val_loss=8.1620 val_acc=0.1326 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 38/70: train_loss=0.3862 train_acc=0.8746 val_loss=7.9568 val_acc=0.1507 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 39/70: train_loss=0.3559 train_acc=0.8842 val_loss=8.7290 val_acc=0.1332 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 40/70: train_loss=0.3398 train_acc=0.8912 val_loss=8.1534 val_acc=0.1380 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 41/70: train_loss=0.3216 train_acc=0.8981 val_loss=8.4395 val_acc=0.1400 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 42/70: train_loss=0.3107 train_acc=0.9053 val_loss=9.0932 val_acc=0.1393 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 43/70: train_loss=0.3038 train_acc=0.9037 val_loss=8.3656 val_acc=0.1440 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 44/70: train_loss=0.2981 train_acc=0.8999 val_loss=8.5402 val_acc=0.1312 seconds=0.7
[CNN] Fusion/lovo fold=06 epoch 45/70: train_loss=0.2941 train_acc=0.9068 val_loss=9.2532 val_acc=0.1528 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 46/70: train_loss=0.2925 train_acc=0.9071 val_loss=9.2172 val_acc=0.1306 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 47/70: train_loss=0.2728 train_acc=0.9115 val_loss=9.4896 val_acc=0.1353 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 48/70: train_loss=0.2692 train_acc=0.9176 val_loss=9.1040 val_acc=0.1265 seconds=0.9
[CNN] Fusion/lovo fold=06 epoch 49/70: train_loss=0.2704 train_acc=0.9141 val_loss=9.3267 val_acc=0.1474 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 50/70: train_loss=0.2640 train_acc=0.9149 val_loss=9.2983 val_acc=0.1312 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 51/70: train_loss=0.2403 train_acc=0.9231 val_loss=9.7025 val_acc=0.1373 seconds=0.9
[CNN] Fusion/lovo fold=06 epoch 52/70: train_loss=0.2305 train_acc=0.9279 val_loss=9.3565 val_acc=0.1480 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 53/70: train_loss=0.2334 train_acc=0.9239 val_loss=9.6678 val_acc=0.1279 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 54/70: train_loss=0.2239 train_acc=0.9272 val_loss=9.6905 val_acc=0.1359 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 55/70: train_loss=0.2221 train_acc=0.9293 val_loss=9.5527 val_acc=0.1319 seconds=0.9
[CNN] Fusion/lovo fold=06 epoch 56/70: train_loss=0.2107 train_acc=0.9357 val_loss=9.8526 val_acc=0.1433 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 57/70: train_loss=0.2167 train_acc=0.9333 val_loss=10.8964 val_acc=0.1353 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 58/70: train_loss=0.2117 train_acc=0.9297 val_loss=10.0741 val_acc=0.1366 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 59/70: train_loss=0.2034 train_acc=0.9400 val_loss=10.4633 val_acc=0.1380 seconds=0.8
[CNN] Fusion/lovo fold=06 epoch 60/70: train_loss=0.1859 train_acc=0.9459 val_loss=9.8684 val_acc=0.1366 seconds=0.8
[CNN] early stopping at epoch 60; no validation improvement for 15 epochs.

/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)
/home/pedro.monteiro@co.it.pt/Desktop/thesis-project/utils/DL/dl_pipeline.py:275: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  band: torch.as_tensor(array[array_index], dtype=torch.float32)

[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__fusion__lovo__ebl-session__s44__7b9bf2__fold-06.parquet
[plots] saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/plots/dl__cnn__fusion__lovo__ebl-session__s44__7b9bf2/training_curves__fold-06.png at dpi=200. PNG is raster; set PLOT_FORMAT='pdf' for a LaTeX vector figure without other code changes.
[predictions] Saved /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/predictions/dl__cnn__fusion__lovo__ebl-session__s44__7b9bf2.parquet
[results upsert] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/runs_folds.csv: 54 row(s)
[DL LOVO] seed=44 fold mean position_accuracy=0.1079 +/- 0.0304; pooled=0.1097
[DL GPU] run_id=dl__cnn__fusion__lovo__ebl-session__s44__7b9bf2 peak_cuda_memory_bytes=978418688
[results upsert] /home/pedro.monteiro@co.it.pt/Desktop/thesis-project/results/runs.csv: 33 row(s)
[DL seeds] mean +/- std across seeds written to tables/seed_summary; LOVO uses each seed's fold mean and keeps within-seed fold std separate.

In [8]:
cnn_summary, test_accuracy_comparison = show_dl_results(results_dir)
display(cnn_summary)

display(test_accuracy_comparison)

,run_id,timestamp,family,model,band,split,seed,normalization,baseline_scope,window_size,...,best_epoch_std,mean_seconds_per_epoch,mean_seconds_per_epoch_mean,mean_seconds_per_epoch_std,stopped_epoch,patience_triggered,peak_cuda_memory_bytes,device,sklearn_version,numpy_version
3,dl__cnn__2_4ghz__block__ebl-session__s42__df21ec,2026-07-22T18:36:31.182108+00:00,dl,cnn,2_4ghz,block,42,empty_baseline,session,60,...,NaN,0.282136,NaN,NaN,44.0,1.0,514714624.0,cuda,1.9.0,2.5.1
4,dl__cnn__2_4ghz__block__ebl-session__s43__210c56,2026-07-22T18:36:47.242239+00:00,dl,cnn,2_4ghz,block,43,empty_baseline,session,60,...,NaN,0.251184,NaN,NaN,50.0,0.0,514714624.0,cuda,1.9.0,2.5.1
5,dl__cnn__2_4ghz__block__ebl-session__s44__86f94f,2026-07-22T18:37:03.908150+00:00,dl,cnn,2_4ghz,block,44,empty_baseline,session,60,...,NaN,0.255270,NaN,NaN,50.0,0.0,514714624.0,cuda,1.9.0,2.5.1
6,dl__cnn__5ghz__block__ebl-session__s42__df21ec,2026-07-22T18:37:26.695344+00:00,dl,cnn,5ghz,block,42,empty_baseline,session,60,...,NaN,0.345880,NaN,NaN,40.0,1.0,579083264.0,cuda,1.9.0,2.5.1
7,dl__cnn__5ghz__block__ebl-session__s43__210c56,2026-07-22T18:37:44.903111+00:00,dl,cnn,5ghz,block,43,empty_baseline,session,60,...,NaN,0.327006,NaN,NaN,44.0,1.0,579083264.0,cuda,1.9.0,2.5.1
8,dl__cnn__5ghz__block__ebl-session__s44__86f94f,2026-07-22T18:38:04.402553+00:00,dl,cnn,5ghz,block,44,empty_baseline,session,60,...,NaN,0.312220,NaN,NaN,50.0,0.0,579083264.0,cuda,1.9.0,2.5.1
9,dl__cnn__fusion__block__ebl-session__s42__df21ec,2026-07-22T18:38:41.941273+00:00,dl,cnn,fusion,block,42,empty_baseline,session,60,...,NaN,0.463929,NaN,NaN,50.0,0.0,978418688.0,cuda,1.9.0,2.5.1
10,dl__cnn__fusion__block__ebl-session__s43__210c56,2026-07-22T18:39:07.169167+00:00,dl,cnn,fusion,block,43,empty_baseline,session,60,...,NaN,0.432133,NaN,NaN,50.0,0.0,978418688.0,cuda,1.9.0,2.5.1
11,dl__cnn__fusion__block__ebl-session__s44__86f94f,2026-07-22T18:39:27.186644+00:00,dl,cnn,fusion,block,44,empty_baseline,session,60,...,NaN,0.452285,NaN,NaN,36.0,1.0,978418688.0,cuda,1.9.0,2.5.1
12,dl__cnn__2_4ghz__block__ebl-session__s42__eb2083,2026-07-22T22:25:24.462285+00:00,dl,cnn,2_4ghz,block,42,empty_baseline,session,60,...,NaN,0.291731,NaN,NaN,50.0,0.0,514714624.0,cuda,1.9.0,2.5.1
13,dl__cnn__2_4ghz__block__ebl-session__s43__7d42d1,2026-07-22T22:25:41.299487+00:00,dl,cnn,2_4ghz,block,43,empty_baseline,session,60,...,NaN,0.271714,NaN,NaN,50.0,0.0,514714624.0,cuda,1.9.0,2.5.1
14,dl__cnn__2_4ghz__block__ebl-session__s44__3f1421,2026-07-22T22:25:57.650859+00:00,dl,cnn,2_4ghz,block,44,empty_baseline,session,60,...,NaN,0.271407,NaN,NaN,50.0,0.0,514714624.0,cuda,1.9.0,2.5.1
15,dl__cnn__5ghz__block__ebl-session__s42__eb2083,2026-07-22T22:26:18.424778+00:00,dl,cnn,5ghz,block,42,empty_baseline,session,60,...,NaN,0.351592,NaN,NaN,50.0,0.0,579083264.0,cuda,1.9.0,2.5.1
16,dl__cnn__5ghz__block__ebl-session__s43__7d42d1,2026-07-22T22:26:38.575420+00:00,dl,cnn,5ghz,block,43,empty_baseline,session,60,...,NaN,0.348412,NaN,NaN,50.0,0.0,579083264.0,cuda,1.9.0,2.5.1
17,dl__cnn__5ghz__block__ebl-session__s44__3f1421,2026-07-22T22:26:58.653328+00:00,dl,cnn,5ghz,block,44,empty_baseline,session,60,...,NaN,0.346380,NaN,NaN,50.0,0.0,579083264.0,cuda,1.9.0,2.5.1
18,dl__cnn__fusion__block__ebl-session__s42__eb2083,2026-07-22T22:27:28.062797+00:00,dl,cnn,fusion,block,42,empty_baseline,session,60,...,NaN,0.512262,NaN,NaN,50.0,0.0,978418688.0,cuda,1.9.0,2.5.1
19,dl__cnn__fusion__block__ebl-session__s43__7d42d1,2026-07-22T22:27:57.119251+00:00,dl,cnn,fusion,block,43,empty_baseline,session,60,...,NaN,0.520320,NaN,NaN,50.0,0.0,978418688.0,cuda,1.9.0,2.5.1
20,dl__cnn__fusion__block__ebl-session__s44__3f1421,2026-07-22T22:28:25.104041+00:00,dl,cnn,fusion,block,44,empty_baseline,session,60,...,NaN,0.498056,NaN,NaN,50.0,0.0,978418688.0,cuda,1.9.0,2.5.1
24,dl__cnn__2_4ghz__lovo__ebl-session__s42__9b1404,2026-07-23T13:48:02.786457+00:00,dl,cnn,2_4ghz,lovo,42,empty_baseline,session,60,...,12.956337,0.470346,0.470346,0.045645,NaN,NaN,514714624.0,cuda,1.9.0,2.5.1
25,dl__cnn__2_4ghz__lovo__ebl-session__s43__a89b5d,2026-07-23T13:49:57.671381+00:00,dl,cnn,2_4ghz,lovo,43,empty_baseline,session,60,...,15.587388,0.463850,0.463850,0.038593,NaN,NaN,514714624.0,cuda,1.9.0,2.5.1
26,dl__cnn__2_4ghz__lovo__ebl-session__s44__7b9bf2,2026-07-23T13:51:31.436316+00:00,dl,cnn,2_4ghz,lovo,44,empty_baseline,session,60,...,10.966616,0.498135,0.498135,0.034860,NaN,NaN,514714624.0,cuda,1.9.0,2.5.1
27,dl__cnn__5ghz__lovo__ebl-session__s42__9b1404,2026-07-23T13:53:57.387552+00:00,dl,cnn,5ghz,lovo,42,empty_baseline,session,60,...,22.618576,0.589029,0.589029,0.054417,NaN,NaN,579083264.0,cuda,1.9.0,2.5.1
28,dl__cnn__5ghz__lovo__ebl-session__s43__a89b5d,2026-07-23T13:55:51.186055+00:00,dl,cnn,5ghz,lovo,43,empty_baseline,session,60,...,7.685484,0.598899,0.598899,0.042237,NaN,NaN,579083264.0,cuda,1.9.0,2.5.1
29,dl__cnn__5ghz__lovo__ebl-session__s44__7b9bf2,2026-07-23T13:57:58.923697+00:00,dl,cnn,5ghz,lovo,44,empty_baseline,session,60,...,15.033296,0.583697,0.583697,0.031769,NaN,NaN,579083264.0,cuda,1.9.0,2.5.1
30,dl__cnn__fusion__lovo__ebl-session__s42__9b1404,2026-07-23T14:00:58.465944+00:00,dl,cnn,fusion,lovo,42,empty_baseline,session,60,...,9.852242,0.884760,0.884760,0.043593,NaN,NaN,978418688.0,cuda,1.9.0,2.5.1
31,dl__cnn__fusion__lovo__ebl-session__s43__a89b5d,2026-07-23T14:04:09.091103+00:00,dl,cnn,fusion,lovo,43,empty_baseline,session,60,...,13.023056,0.877289,0.877289,0.027092,NaN,NaN,978418688.0,cuda,1.9.0,2.5.1
32,dl__cnn__fusion__lovo__ebl-session__s44__7b9bf2,2026-07-23T14:08:05.305960+00:00,dl,cnn,fusion,lovo,44,empty_baseline,session,60,...,13.155480,0.859873,0.859873,0.020100,NaN,NaN,978418688.0,cuda,1.9.0,2.5.1

      band model  seed  position_accuracy  parameter_count
3   2_4ghz   cnn    42           0.248563          76020.0
12  2_4ghz   cnn    42           0.286101          76020.0
4   2_4ghz   cnn    43           0.316092          76020.0
13  2_4ghz   cnn    43           0.276036          76020.0
5   2_4ghz   cnn    44           0.320402          76020.0
14  2_4ghz   cnn    44           0.293457          76020.0
6     5ghz   cnn    42           0.290049          76308.0
15    5ghz   cnn    42           0.298067          76308.0
7     5ghz   cnn    43           0.307039          76308.0
16    5ghz   cnn    43           0.296661          76308.0
8     5ghz   cnn    44           0.324636          76308.0
17    5ghz   cnn    44           0.297012          76308.0
9   fusion   cnn    42           0.489193         138708.0
18  fusion   cnn    42           0.404965         138708.0
10  fusion   cnn    43           0.462536         138708.0
19  fusion   cnn    43           0.378588         138708.0
11  fusion   cnn    44           0.398415         138708.0
20  fusion   cnn    44           0.410396         138708.0