In [1]:
import numpy as np
import pandas as pd
from matplotlib import style
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from numpy import array
from sklearn.metrics import accuracy_score
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import confusion_matrix, classification_report, precision_score, recall_score, roc_curve, auc
from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing
from keras.utils import np_utils
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score


import pandas as pd
import tensorflow as tf
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import Conv1D, GlobalMaxPooling1D
from tensorflow.keras.datasets import imdb
import numpy as np
import pandas as pd
import os
import gc


#import libraries
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_curve, auc
from sklearn import metrics
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation,Dropout
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping, ReduceLROnPlateau
from tensorflow.keras.optimizers import SGD,Adam
import keras
# Conv1D + LSTM
from keras.layers.convolutional import Conv1D,MaxPooling1D
from tensorflow.keras.layers import Embedding, Dense, Concatenate, Conv1D, Bidirectional, LSTM, GlobalAveragePooling1D, GlobalMaxPooling1D
from keras.layers import LSTM
from keras.layers import Dense,Dropout
from keras.layers import Flatten
from keras.layers import Input
from keras import Input, Model
from keras.layers import concatenate


from sklearn.preprocessing import LabelEncoder
from sklearn import preprocessing
from keras.utils import np_utils
import numpy as np
import pandas as pd
import random
from itertools import chain
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn import metrics
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import KFold, cross_val_score
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()


from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from math import sqrt


import numpy as np
import pandas as pd
import os
import gc
#import matplotlib.pyplot as plt


#import libraries
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_curve, auc
from sklearn import metrics
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation,Dropout
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping, ReduceLROnPlateau
from tensorflow.keras.optimizers import SGD,Adam
import keras
# Conv1D + LSTM
from keras.layers.convolutional import Conv1D,MaxPooling1D,AveragePooling1D
from tensorflow.keras.layers import Embedding, Dense, Concatenate, Conv1D, Bidirectional, LSTM, GlobalAveragePooling1D, GlobalMaxPooling1D
from keras.layers import LSTM
from keras.layers import Dense,Dropout
from keras.layers import Flatten
from keras.layers import Input
from keras import Input, Model
from keras.layers import concatenate

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation,Dropout
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping, ReduceLROnPlateau
from tensorflow.keras.optimizers import SGD,Adam

import math

from keras import backend as K

#from keras import initializations
from keras import initializers, regularizers, constraints
from tensorflow.keras.layers import Layer

from tensorflow.keras import backend as K
from tensorflow.keras import initializers, regularizers, constraints
from tensorflow.keras.layers import Layer

pip install numpy==1.26.4

In [2]:
# Create an attention class

class attention(Layer):
    def __init__(self, step_dim,
                 W_regularizer=None, b_regularizer=None,
                 W_constraint=None, b_constraint=None,
                 bias=True, **kwargs):
        """
        Keras Layer that implements an Attention mechanism for temporal data.
        Supports Masking.
        Follows the work of Raffel et al. [https://arxiv.org/abs/1512.08756]
        # Input shape
            3D tensor with shape: `(samples, steps, features)`.
        # Output shape
            2D tensor with shape: `(samples, features)`.
        :param kwargs:
        Just put it on top of an RNN Layer (GRU/LSTM/SimpleRNN) with return_sequences=True.
        The dimensions are inferred based on the output shape of the RNN.
        Example:
            # 1
            model.add(LSTM(64, return_sequences=True))
            model.add(Attention())
            # next add a Dense layer (for classification/regression) or whatever...
            # 2
            hidden = LSTM(64, return_sequences=True)(words)
            sentence = Attention()(hidden)
            # next add a Dense layer (for classification/regression) or whatever...
        """
        self.supports_masking = True
        self.init = initializers.get('glorot_uniform')

        self.W_regularizer = regularizers.get(W_regularizer)
        self.b_regularizer = regularizers.get(b_regularizer)

        self.W_constraint = constraints.get(W_constraint)
        self.b_constraint = constraints.get(b_constraint)

        self.bias = bias
        self.step_dim = step_dim
        self.features_dim = 0

        super(attention, self).__init__(**kwargs)

    def build(self, input_shape):
        assert len(input_shape) == 3

        self.W = self.add_weight(name='{}_W'.format(self.name),
                                 shape=(input_shape[-1],),
                                 initializer=self.init,
                                 regularizer=self.W_regularizer,
                                 constraint=self.W_constraint)
        self.features_dim = input_shape[-1]

        if self.bias:
            self.b = self.add_weight(name='{}_b'.format(self.name),
                                     shape=(input_shape[1],),
                                     initializer='zero',
                                     regularizer=self.b_regularizer,
                                     constraint=self.b_constraint)
        else:
            self.b = None

        self.built = True

    def compute_mask(self, input, input_mask=None):
        # do not pass the mask to the next layers
        return None

    def call(self, x, mask=None):
        features_dim = self.features_dim
        step_dim = self.step_dim

        e = K.reshape(K.dot(K.reshape(x, (-1, features_dim)), K.reshape(self.W, (features_dim, 1))), (-1, step_dim))  # e = K.dot(x, self.W)
        if self.bias:
            e += self.b
        e = K.tanh(e)

        a = K.exp(e)
        # apply mask after the exp. will be re-normalized next
        if mask is not None:
            # cast the mask to floatX to avoid float64 upcasting in theano
            a *= K.cast(mask, K.floatx())
        # in some cases especially in the early stages of training the sum may be almost zero
        # and this results in NaN's. A workaround is to add a very small positive number ε to the sum.
        a /= K.cast(K.sum(a, axis=1, keepdims=True) + K.epsilon(), K.floatx())
        a = K.expand_dims(a)

        c = K.sum(a * x, axis=1)
        return c

    def compute_output_shape(self, input_shape):
        return input_shape[0], self.features_dim

In [3]:
# this function takes orginal values and predicted values, 
#and outputs floor accuracy, average final measure (consisting MAE(Ecoord, Ncoord) and Floor Accuracy), MAE,
#RMSE, ..% localization errors, 

def calculate_performances(pred,y_valx):
   
    y_pred= pd.DataFrame(pred, columns = ['ECoord', 'NCoord','FloorID'])
    y_pred['FloorID']= y_pred['FloorID'].round()
   
    #calculating floor accuracy (firstly round predicted floorID because it is a regression result, which can not be integer)
    count=0
    floor_dist=[0 for i in range(len(pred))]
    for i in range(0,len(y_pred)):
        if abs(y_pred.FloorID.loc[i])==abs(y_valx.FloorID.loc[i]):
            count=count+1
            floor_dist[i]=1
   
    floor_acc=count/len(pred)   
    #print('Floor accuracy', floor_acc)

    del y_pred['FloorID']
    del y_valx['FloorID']

    #calculating AFS and MAE, (((len(pred)-count)*4)/len(pred)) refers to the number of false decision for floor 
    #if floor prediction is incorrect, an error of 4 meters is incurred, 
    #considering that the distance between floors is assumed to be 4 meters.
    
    avg_final_score= mean_absolute_error(y_valx, y_pred)+ (((len(pred)-count)*4)/len(pred))
    maex=mean_absolute_error(y_valx, y_pred)
    
    
    predicted_values = np.array(y_valx)
    ground_truth_values = np.array(y_pred)
    tempp= np.linalg.norm(predicted_values- ground_truth_values, axis=1)
    
    # Calculate the average localization error
    average_le = np.mean(tempp)
    
    squared_differences = (predicted_values- ground_truth_values) ** 2
    
    # Calculate the mean of the squared differences
    mean_squared_error = np.mean(squared_differences)
    
    # Calculate the root of the mean squared error
    #calculting RMSE
    rmsex2 = np.sqrt(mean_squared_error)
    
    

    final_dist=[0 for i in range(len(pred))]
    for i in range(0,len(floor_dist)):
        final_dist[i]=(abs(y_pred['ECoord'].loc[i]-y_valx['ECoord'].loc[i])+abs(y_pred['NCoord'].loc[i]-y_valx['NCoord'].loc[i]))/2
        if floor_dist[i]==0:
            final_dist[i]=final_dist[i]+4
    
    final_dist.sort()
   
    #ldistx=final_dist
    
    perc_pos=math.floor((50/100)*(len(final_dist)))

    if perc_pos>math.floor((50/100)*(len(final_dist))):
        error50=final_dist[perc_pos] + (final_dist[perc_pos+1]-final_dist[perc_pos])*0.5
    else:
        error50=final_dist[perc_pos]


    perc_pos=math.floor((75/100)*(len(final_dist)))

    if perc_pos>math.floor((75/100)*(len(final_dist))):
        error75=final_dist[perc_pos] + (final_dist[perc_pos+1]-final_dist[perc_pos])*0.5
    else:
        error75=final_dist[perc_pos]
        
    
    perc_pos=math.floor((95/100)*(len(final_dist)))

    if perc_pos>math.floor((95/100)*(len(final_dist))):
        error95=final_dist[perc_pos] + (final_dist[perc_pos+1]-final_dist[perc_pos])*0.5
    else:
        error95=final_dist[perc_pos]
    
    
    for i in range(0,len(final_dist)):
        final_dist[i]=pow(final_dist[i],2)

    from math import sqrt
    rmsex=sqrt(np.mean(final_dist)/2)
        

    return floor_acc, avg_final_score, maex, rmsex, rmsex2, error50, error75, error95, average_le

In [4]:
#create functions for different deep learning models

#inputs: inputlength, number of output for outputlayer(Ecoord, Ncoord, Floor id)
########################################################################################################
#Deep Neural Network (MLP)
def model_dnnreg(length,output_num):
    clf = Sequential()
    clf.add(Dense(256, input_dim =length, activation = 'relu'))
    clf.add(Dense(128, activation = 'relu'))
    clf.add(Dense(output_num, activation = 'linear'))
    clf.compile(loss = 'mean_absolute_error', optimizer = 'adam', metrics = ['mean_absolute_error'])
    return clf

########################################################################################################
#Convolutional Neural Network with two convolutional layer and one pooling
def model_CNNreg(length,output_num):

    inputs = Input(shape=(length,1))
    conv = Conv1D(filters=32, kernel_size=3, activation='relu')(inputs)
    conv = Conv1D(filters=32, kernel_size=3, activation='relu')(conv)
    pool = MaxPooling1D()(conv)
    flat=Flatten()(pool)
  
    dense = Dense(256, activation='relu')(flat)
    dense = Dense(128, activation='relu')(dense)
    
    outputs = Dense(output_num, activation='linear')(dense)
    model = Model(inputs=[inputs], outputs=outputs)
    # compile
    model.compile(loss='mean_absolute_error', optimizer='adam', metrics = ['mean_absolute_error'])
    print(model.summary())
    return model


########################################################################################################
#LSTM Network with one pooling layer
def model_LSTMreg(length,output_num):

    inputs = Input(shape=(length,1))
    lstm_layer =  LSTM(32, return_sequences=True)(inputs)
    pool = MaxPooling1D()(lstm_layer)
    flat=Flatten()(pool)
    dense = Dense(256, activation='relu')(flat)
    dense = Dense(128, activation='relu')(dense)
    outputs = Dense(output_num, activation='linear')(dense)
    model = Model(inputs=[inputs], outputs=outputs)
    # compile
    model.compile(loss='mean_absolute_error', optimizer='adam', metrics = ['mean_absolute_error'])
    print(model.summary())
    return model

########################################################################################################

#Multi-channel CNN network with attention layer (MC-ACNNR)
#inputs: inputlengthforchannel1, inputlengthforchannel2, number of output for outputlayer(Ecoord, Ncoord, Floor id)
def model_CNN_Multichannel_att(length1,length2,output_num,maxx):
  # channel 1
    inputs1 = Input(shape=(length1,1))
    inputs2 = Input(shape=(length2,1))

    conv1 = Conv1D(filters=32, kernel_size=3, padding='same', activation='relu')(inputs1)
    conv1 = Conv1D(filters=32, kernel_size=3, padding='same', activation='relu')(conv1)

    att1=attention(maxx)(conv1)
   
    conv2 = Conv1D(filters=32, kernel_size=3, padding='same', activation='relu')(inputs2)
    conv2 = Conv1D(filters=32, kernel_size=3, padding='same', activation='relu')(conv2)

    att2=attention(maxx)(conv2)
    
    merged=concatenate([conv1,conv2])
    conv = Conv1D(filters=32, kernel_size=3, padding='same',  activation='relu')(merged)
    conv = Conv1D(filters=32, kernel_size=3, padding='same',  activation='relu')(conv)

    pool = MaxPooling1D()(conv)
    flat=Flatten()(pool)
    
    flat=concatenate([att1,flat,att2])
    
    dense = Dense(256, activation='relu')(flat)
    dense = Dense(128, activation='relu')(dense)
    outputs = Dense(output_num, activation='linear')(dense)
    model = Model(inputs=[inputs1, inputs2], outputs=outputs)
    # compile
    model.compile(loss='mean_absolute_error', optimizer='adam', metrics = ['mean_absolute_error'])   
    # summarize
    print(model.summary())
    return model

In [15]:
#SOD_SYL
#DNNR

#K.clear_session()
tf.keras.backend.clear_session()

learning_rate=0.001
batch_size=100
epochs=250

early_stop = EarlyStopping(monitor = 'val_loss', min_delta = 0.0001, 
                       patience = 8, mode = 'min', verbose = 1,
                       restore_best_weights = True)
reduce_lr = ReduceLROnPlateau(monitor = 'val_loss', factor = 0.6, 
                          patience = 5, min_delta = 0.0001, 
                          mode = 'min', verbose = 1)
    
columns= {'iter':[],
        'Model':[], 
        'ACC':[], 
        'AFS':[],
        'MAE':[], 
        'RMSE':[],
        'RMSE2':[],
        '50th%error':[],
        '75th%error':[],
        '95th%error':[],
        'avg_le':[]
       } 


df_comp= pd.DataFrame(columns)

filepath='C:/Users/user/Desktop/arzu_kodlar/indoor_diger/checkpoints/'


df=pd.read_csv('data/SYL_preprocessed/SOD_SYL_24_merged_normalized_dropped.csv')
df = df.astype(float)

df_train = df[df['datatype'] == 1]
df_train=df_train.reset_index(drop=True)
df_test = df[df['datatype'] == 2]
df_test=df_test.reset_index(drop=True)

y_train= df_train[['ECoord', 'NCoord','FloorID']]
y_val=df_test[['ECoord', 'NCoord','FloorID']]

x_train=df_train.drop(['datatype','ECoord', 'NCoord','FloorID'], axis=1)
x_val=df_test.drop(['datatype','ECoord', 'NCoord','FloorID'], axis=1)

x_trainx = tf.convert_to_tensor(x_train)
y_trainx = tf.convert_to_tensor(y_train)

x_valx = tf.convert_to_tensor(x_val)
y_valx = tf.convert_to_tensor(y_val)
    

model_name='DNNR_24GHz'

for iter in range(0,3):
    
    y_val=df_test[['ECoord', 'NCoord','FloorID']]
    y_valx = tf.convert_to_tensor(y_val)


    checkpoint_filepath = filepath +model_name+ str(iter)+ '2x24.hdf5'

    model_checkpoint_callback = ModelCheckpoint(
    filepath=checkpoint_filepath,
    save_weights_only=True,
    monitor='val_mean_absolute_error',
    mode='min',
    save_best_only=True)
    callbacks = [model_checkpoint_callback,early_stop,reduce_lr]
    
    
    deep_model=model_dnnreg(x_train.shape[1], y_train.shape[1])
    
    deep_model.fit(x_trainx, y_trainx, epochs=epochs, batch_size=batch_size, callbacks =callbacks, validation_data=(x_valx, y_valx))
    
    deep_model.load_weights(checkpoint_filepath)
    
    pred= deep_model.predict(x_val)

    floor_acc, avg_final_score, maex, rmsex, rmsex2, error50, error75, error95, average_le=calculate_performances(pred, y_val)   

    df_comp.loc[len(df_comp.index)] = [iter, model_name, floor_acc, avg_final_score, maex, rmsex, rmsex2, error50, error75, error95, average_le]  
    
    display(df_comp)


df_comp.to_csv("SOD_SYL_24_DNNR.csv",index=False)

Epoch 1/250
7/7 [==============================] - 1s 45ms/step - loss: 21.4033 - mean_absolute_error: 21.4033 - val_loss: 21.0204 - val_mean_absolute_error: 21.0204 - lr: 0.0010
Epoch 2/250
7/7 [==============================] - 0s 14ms/step - loss: 20.7187 - mean_absolute_error: 20.7187 - val_loss: 19.9874 - val_mean_absolute_error: 19.9874 - lr: 0.0010
Epoch 3/250
7/7 [==============================] - 0s 13ms/step - loss: 19.5748 - mean_absolute_error: 19.5748 - val_loss: 18.3100 - val_mean_absolute_error: 18.3100 - lr: 0.0010
Epoch 4/250
7/7 [==============================] - 0s 14ms/step - loss: 17.8093 - mean_absolute_error: 17.8093 - val_loss: 16.5085 - val_mean_absolute_error: 16.5085 - lr: 0.0010
Epoch 5/250
7/7 [==============================] - 0s 13ms/step - loss: 16.0439 - mean_absolute_error: 16.0439 - val_loss: 14.7647 - val_mean_absolute_error: 14.7647 - lr: 0.0010
Epoch 6/250
7/7 [==============================] - 0s 15ms/step - loss: 14.2033 - mean_absolute_error: 14.2033 - val_loss: 12.8432 - val_mean_absolute_error: 12.8432 - lr: 0.0010
Epoch 7/250
7/7 [==============================] - 0s 14ms/step - loss: 12.3217 - mean_absolute_error: 12.3217 - val_loss: 11.1940 - val_mean_absolute_error: 11.1940 - lr: 0.0010
Epoch 8/250
7/7 [==============================] - 0s 14ms/step - loss: 11.0345 - mean_absolute_error: 11.0345 - val_loss: 10.2285 - val_mean_absolute_error: 10.2285 - lr: 0.0010
Epoch 9/250
7/7 [==============================] - 0s 14ms/step - loss: 9.9943 - mean_absolute_error: 9.9943 - val_loss: 9.1306 - val_mean_absolute_error: 9.1306 - lr: 0.0010
Epoch 10/250
7/7 [==============================] - 0s 14ms/step - loss: 8.8452 - mean_absolute_error: 8.8452 - val_loss: 7.9696 - val_mean_absolute_error: 7.9696 - lr: 0.0010
Epoch 11/250
7/7 [==============================] - 0s 13ms/step - loss: 7.7892 - mean_absolute_error: 7.7892 - val_loss: 7.0630 - val_mean_absolute_error: 7.0630 - lr: 0.0010
Epoch 12/250
7/7 [==============================] - 0s 14ms/step - loss: 6.7288 - mean_absolute_error: 6.7288 - val_loss: 6.2292 - val_mean_absolute_error: 6.2292 - lr: 0.0010
Epoch 13/250
7/7 [==============================] - 0s 15ms/step - loss: 5.9874 - mean_absolute_error: 5.9874 - val_loss: 5.6833 - val_mean_absolute_error: 5.6833 - lr: 0.0010
Epoch 14/250
7/7 [==============================] - 0s 14ms/step - loss: 5.6184 - mean_absolute_error: 5.6184 - val_loss: 5.4088 - val_mean_absolute_error: 5.4088 - lr: 0.0010
Epoch 15/250
7/7 [==============================] - 0s 16ms/step - loss: 5.3114 - mean_absolute_error: 5.3114 - val_loss: 5.2134 - val_mean_absolute_error: 5.2134 - lr: 0.0010
Epoch 16/250
7/7 [==============================] - 0s 16ms/step - loss: 5.0291 - mean_absolute_error: 5.0291 - val_loss: 5.0036 - val_mean_absolute_error: 5.0036 - lr: 0.0010
Epoch 17/250
7/7 [==============================] - 0s 14ms/step - loss: 4.7458 - mean_absolute_error: 4.7458 - val_loss: 4.6921 - val_mean_absolute_error: 4.6921 - lr: 0.0010
Epoch 18/250
7/7 [==============================] - 0s 15ms/step - loss: 4.4809 - mean_absolute_error: 4.4809 - val_loss: 4.4522 - val_mean_absolute_error: 4.4522 - lr: 0.0010
Epoch 19/250
7/7 [==============================] - 0s 14ms/step - loss: 4.2140 - mean_absolute_error: 4.2140 - val_loss: 4.3012 - val_mean_absolute_error: 4.3012 - lr: 0.0010
Epoch 20/250
7/7 [==============================] - 0s 14ms/step - loss: 3.9530 - mean_absolute_error: 3.9530 - val_loss: 4.0172 - val_mean_absolute_error: 4.0172 - lr: 0.0010
Epoch 21/250
7/7 [==============================] - 0s 15ms/step - loss: 3.7443 - mean_absolute_error: 3.7443 - val_loss: 3.8268 - val_mean_absolute_error: 3.8268 - lr: 0.0010
Epoch 22/250
7/7 [==============================] - 0s 14ms/step - loss: 3.5525 - mean_absolute_error: 3.5525 - val_loss: 3.7387 - val_mean_absolute_error: 3.7387 - lr: 0.0010
Epoch 23/250
7/7 [==============================] - 0s 14ms/step - loss: 3.3843 - mean_absolute_error: 3.3843 - val_loss: 3.5689 - val_mean_absolute_error: 3.5689 - lr: 0.0010
Epoch 24/250
7/7 [==============================] - 0s 14ms/step - loss: 3.2442 - mean_absolute_error: 3.2442 - val_loss: 3.4276 - val_mean_absolute_error: 3.4276 - lr: 0.0010
Epoch 25/250
7/7 [==============================] - 0s 14ms/step - loss: 3.0840 - mean_absolute_error: 3.0840 - val_loss: 3.3277 - val_mean_absolute_error: 3.3277 - lr: 0.0010
Epoch 26/250
7/7 [==============================] - 0s 14ms/step - loss: 2.9660 - mean_absolute_error: 2.9660 - val_loss: 3.2612 - val_mean_absolute_error: 3.2612 - lr: 0.0010
Epoch 27/250
7/7 [==============================] - 0s 15ms/step - loss: 2.8561 - mean_absolute_error: 2.8561 - val_loss: 3.1972 - val_mean_absolute_error: 3.1972 - lr: 0.0010
Epoch 28/250
7/7 [==============================] - 0s 15ms/step - loss: 2.7763 - mean_absolute_error: 2.7763 - val_loss: 3.1477 - val_mean_absolute_error: 3.1477 - lr: 0.0010
Epoch 29/250
7/7 [==============================] - 0s 14ms/step - loss: 2.7012 - mean_absolute_error: 2.7012 - val_loss: 3.1012 - val_mean_absolute_error: 3.1012 - lr: 0.0010
Epoch 30/250
7/7 [==============================] - 0s 14ms/step - loss: 2.6490 - mean_absolute_error: 2.6490 - val_loss: 3.0683 - val_mean_absolute_error: 3.0683 - lr: 0.0010
Epoch 31/250
7/7 [==============================] - 0s 14ms/step - loss: 2.5863 - mean_absolute_error: 2.5863 - val_loss: 3.0377 - val_mean_absolute_error: 3.0377 - lr: 0.0010
Epoch 32/250
7/7 [==============================] - 0s 14ms/step - loss: 2.5458 - mean_absolute_error: 2.5458 - val_loss: 2.9969 - val_mean_absolute_error: 2.9969 - lr: 0.0010
Epoch 33/250
7/7 [==============================] - 0s 10ms/step - loss: 2.5045 - mean_absolute_error: 2.5045 - val_loss: 3.0273 - val_mean_absolute_error: 3.0273 - lr: 0.0010
Epoch 34/250
7/7 [==============================] - 0s 14ms/step - loss: 2.4774 - mean_absolute_error: 2.4774 - val_loss: 2.9754 - val_mean_absolute_error: 2.9754 - lr: 0.0010
Epoch 35/250
7/7 [==============================] - 0s 10ms/step - loss: 2.4481 - mean_absolute_error: 2.4481 - val_loss: 2.9787 - val_mean_absolute_error: 2.9787 - lr: 0.0010
Epoch 36/250
7/7 [==============================] - 0s 16ms/step - loss: 2.4011 - mean_absolute_error: 2.4011 - val_loss: 2.9320 - val_mean_absolute_error: 2.9320 - lr: 0.0010
Epoch 37/250
7/7 [==============================] - 0s 15ms/step - loss: 2.3775 - mean_absolute_error: 2.3775 - val_loss: 2.8742 - val_mean_absolute_error: 2.8742 - lr: 0.0010
Epoch 38/250
7/7 [==============================] - 0s 10ms/step - loss: 2.3924 - mean_absolute_error: 2.3924 - val_loss: 2.9377 - val_mean_absolute_error: 2.9377 - lr: 0.0010
Epoch 39/250
7/7 [==============================] - 0s 9ms/step - loss: 2.3461 - mean_absolute_error: 2.3461 - val_loss: 2.9304 - val_mean_absolute_error: 2.9304 - lr: 0.0010
Epoch 40/250
7/7 [==============================] - 0s 10ms/step - loss: 2.3472 - mean_absolute_error: 2.3472 - val_loss: 2.9637 - val_mean_absolute_error: 2.9637 - lr: 0.0010
Epoch 41/250
7/7 [==============================] - 0s 10ms/step - loss: 2.3066 - mean_absolute_error: 2.3066 - val_loss: 2.9002 - val_mean_absolute_error: 2.9002 - lr: 0.0010
Epoch 42/250
1/7 [===>..........................] - ETA: 0s - loss: 1.9758 - mean_absolute_error: 1.9758
Epoch 42: ReduceLROnPlateau reducing learning rate to 0.0006000000284984708.
7/7 [==============================] - 0s 9ms/step - loss: 2.2846 - mean_absolute_error: 2.2846 - val_loss: 2.9380 - val_mean_absolute_error: 2.9380 - lr: 0.0010
Epoch 43/250
7/7 [==============================] - 0s 9ms/step - loss: 2.2608 - mean_absolute_error: 2.2608 - val_loss: 2.8984 - val_mean_absolute_error: 2.8984 - lr: 6.0000e-04
Epoch 44/250
7/7 [==============================] - 0s 13ms/step - loss: 2.2467 - mean_absolute_error: 2.2467 - val_loss: 2.8711 - val_mean_absolute_error: 2.8711 - lr: 6.0000e-04
Epoch 45/250
7/7 [==============================] - 0s 14ms/step - loss: 2.2354 - mean_absolute_error: 2.2354 - val_loss: 2.8523 - val_mean_absolute_error: 2.8523 - lr: 6.0000e-04
Epoch 46/250

7/7 [==============================] - 0s 9ms/step - loss: 2.2253 - mean_absolute_error: 2.2253 - val_loss: 2.8839 - val_mean_absolute_error: 2.8839 - lr: 6.0000e-04
Epoch 47/250
7/7 [==============================] - 0s 10ms/step - loss: 2.2214 - mean_absolute_error: 2.2214 - val_loss: 2.8927 - val_mean_absolute_error: 2.8927 - lr: 6.0000e-04
Epoch 48/250
7/7 [==============================] - 0s 11ms/step - loss: 2.2097 - mean_absolute_error: 2.2097 - val_loss: 2.8732 - val_mean_absolute_error: 2.8732 - lr: 6.0000e-04
Epoch 49/250
7/7 [==============================] - 0s 10ms/step - loss: 2.1980 - mean_absolute_error: 2.1980 - val_loss: 2.8899 - val_mean_absolute_error: 2.8899 - lr: 6.0000e-04
Epoch 50/250
1/7 [===>..........................] - ETA: 0s - loss: 2.1795 - mean_absolute_error: 2.1795
Epoch 50: ReduceLROnPlateau reducing learning rate to 0.0003600000170990825.
7/7 [==============================] - 0s 11ms/step - loss: 2.1926 - mean_absolute_error: 2.1926 - val_loss: 2.8690 - val_mean_absolute_error: 2.8690 - lr: 6.0000e-04
Epoch 51/250
7/7 [==============================] - 0s 11ms/step - loss: 2.1799 - mean_absolute_error: 2.1799 - val_loss: 2.8526 - val_mean_absolute_error: 2.8526 - lr: 3.6000e-04
Epoch 52/250
7/7 [==============================] - 0s 14ms/step - loss: 2.1750 - mean_absolute_error: 2.1750 - val_loss: 2.8407 - val_mean_absolute_error: 2.8407 - lr: 3.6000e-04
Epoch 53/250
7/7 [==============================] - 0s 10ms/step - loss: 2.1681 - mean_absolute_error: 2.1681 - val_loss: 2.8587 - val_mean_absolute_error: 2.8587 - lr: 3.6000e-04
Epoch 54/250
7/7 [==============================] - 0s 9ms/step - loss: 2.1693 - mean_absolute_error: 2.1693 - val_loss: 2.8573 - val_mean_absolute_error: 2.8573 - lr: 3.6000e-04
Epoch 55/250
7/7 [==============================] - 0s 12ms/step - loss: 2.1575 - mean_absolute_error: 2.1575 - val_loss: 2.8327 - val_mean_absolute_error: 2.8327 - lr: 3.6000e-04
Epoch 56/250
7/7 [==============================] - 0s 9ms/step - loss: 2.1547 - mean_absolute_error: 2.1547 - val_loss: 2.8394 - val_mean_absolute_error: 2.8394 - lr: 3.6000e-04
Epoch 57/250
7/7 [==============================] - 0s 10ms/step - loss: 2.1477 - mean_absolute_error: 2.1477 - val_loss: 2.8433 - val_mean_absolute_error: 2.8433 - lr: 3.6000e-04
Epoch 58/250
7/7 [==============================] - 0s 13ms/step - loss: 2.1459 - mean_absolute_error: 2.1459 - val_loss: 2.8272 - val_mean_absolute_error: 2.8272 - lr: 3.6000e-04
Epoch 59/250
7/7 [==============================] - 0s 10ms/step - loss: 2.1373 - mean_absolute_error: 2.1373 - val_loss: 2.8353 - val_mean_absolute_error: 2.8353 - lr: 3.6000e-04
Epoch 60/250
7/7 [==============================] - 0s 13ms/step - loss: 2.1309 - mean_absolute_error: 2.1309 - val_loss: 2.8252 - val_mean_absolute_error: 2.8252 - lr: 3.6000e-04
Epoch 61/250
7/7 [==============================] - 0s 9ms/step - loss: 2.1281 - mean_absolute_error: 2.1281 - val_loss: 2.8302 - val_mean_absolute_error: 2.8302 - lr: 3.6000e-04
Epoch 62/250
7/7 [==============================] - 0s 9ms/step - loss: 2.1223 - mean_absolute_error: 2.1223 - val_loss: 2.8300 - val_mean_absolute_error: 2.8300 - lr: 3.6000e-04
Epoch 63/250
7/7 [==============================] - 0s 9ms/step - loss: 2.1191 - mean_absolute_error: 2.1191 - val_loss: 2.8304 - val_mean_absolute_error: 2.8304 - lr: 3.6000e-04
Epoch 64/250
7/7 [==============================] - 0s 14ms/step - loss: 2.1177 - mean_absolute_error: 2.1177 - val_loss: 2.8166 - val_mean_absolute_error: 2.8166 - lr: 3.6000e-04
Epoch 65/250
7/7 [==============================] - 0s 10ms/step - loss: 2.1095 - mean_absolute_error: 2.1095 - val_loss: 2.8246 - val_mean_absolute_error: 2.8246 - lr: 3.6000e-04
Epoch 66/250
7/7 [==============================] - 0s 10ms/step - loss: 2.1030 - mean_absolute_error: 2.1030 - val_loss: 2.8297 - val_mean_absolute_error: 2.8297 - lr: 3.6000e-04
Epoch 67/250
7/7 [==============================] - 0s 10ms/step - loss: 2.1037 - mean_absolute_error: 2.1037 - val_loss: 2.8395 - val_mean_absolute_error: 2.8395 - lr: 3.6000e-04
Epoch 68/250
7/7 [==============================] - 0s 13ms/step - loss: 2.1056 - mean_absolute_error: 2.1056 - val_loss: 2.8087 - val_mean_absolute_error: 2.8087 - lr: 3.6000e-04
Epoch 69/250
7/7 [==============================] - 0s 14ms/step - loss: 2.0996 - mean_absolute_error: 2.0996 - val_loss: 2.7842 - val_mean_absolute_error: 2.7842 - lr: 3.6000e-04
Epoch 70/250
7/7 [==============================] - 0s 10ms/step - loss: 2.0915 - mean_absolute_error: 2.0915 - val_loss: 2.8181 - val_mean_absolute_error: 2.8181 - lr: 3.6000e-04
Epoch 71/250
7/7 [==============================] - 0s 10ms/step - loss: 2.0872 - mean_absolute_error: 2.0872 - val_loss: 2.7916 - val_mean_absolute_error: 2.7916 - lr: 3.6000e-04
Epoch 72/250
7/7 [==============================] - 0s 10ms/step - loss: 2.0795 - mean_absolute_error: 2.0795 - val_loss: 2.8027 - val_mean_absolute_error: 2.8027 - lr: 3.6000e-04
Epoch 73/250
7/7 [==============================] - 0s 10ms/step - loss: 2.0746 - mean_absolute_error: 2.0746 - val_loss: 2.8067 - val_mean_absolute_error: 2.8067 - lr: 3.6000e-04
Epoch 74/250
1/7 [===>..........................] - ETA: 0s - loss: 1.8709 - mean_absolute_error: 1.8709
Epoch 74: ReduceLROnPlateau reducing learning rate to 0.00021600000327453016.
7/7 [==============================] - 0s 10ms/step - loss: 2.0740 - mean_absolute_error: 2.0740 - val_loss: 2.7996 - val_mean_absolute_error: 2.7996 - lr: 3.6000e-04
Epoch 75/250
7/7 [==============================] - 0s 13ms/step - loss: 2.0707 - mean_absolute_error: 2.0707 - val_loss: 2.7679 - val_mean_absolute_error: 2.7679 - lr: 2.1600e-04
Epoch 76/250
7/7 [==============================] - 0s 9ms/step - loss: 2.0633 - mean_absolute_error: 2.0633 - val_loss: 2.7983 - val_mean_absolute_error: 2.7983 - lr: 2.1600e-04
Epoch 77/250
7/7 [==============================] - 0s 10ms/step - loss: 2.0611 - mean_absolute_error: 2.0611 - val_loss: 2.7989 - val_mean_absolute_error: 2.7989 - lr: 2.1600e-04
Epoch 78/250
7/7 [==============================] - 0s 9ms/step - loss: 2.0582 - mean_absolute_error: 2.0582 - val_loss: 2.7829 - val_mean_absolute_error: 2.7829 - lr: 2.1600e-04
Epoch 79/250
7/7 [==============================] - 0s 9ms/step - loss: 2.0553 - mean_absolute_error: 2.0553 - val_loss: 2.7921 - val_mean_absolute_error: 2.7921 - lr: 2.1600e-04
Epoch 80/250
1/7 [===>..........................] - ETA: 0s - loss: 2.3233 - mean_absolute_error: 2.3233
Epoch 80: ReduceLROnPlateau reducing learning rate to 0.00012960000021848827.
7/7 [==============================] - 0s 9ms/step - loss: 2.0580 - mean_absolute_error: 2.0580 - val_loss: 2.7702 - val_mean_absolute_error: 2.7702 - lr: 2.1600e-04
Epoch 81/250
7/7 [==============================] - 0s 9ms/step - loss: 2.0513 - mean_absolute_error: 2.0513 - val_loss: 2.7818 - val_mean_absolute_error: 2.7818 - lr: 1.2960e-04
Epoch 82/250
7/7 [==============================] - 0s 11ms/step - loss: 2.0480 - mean_absolute_error: 2.0480 - val_loss: 2.7853 - val_mean_absolute_error: 2.7853 - lr: 1.2960e-04
Epoch 83/250
1/7 [===>..........................] - ETA: 0s - loss: 2.2008 - mean_absolute_error: 2.2008Restoring model weights from the end of the best epoch: 75.
7/7 [==============================] - 0s 10ms/step - loss: 2.0476 - mean_absolute_error: 2.0476 - val_loss: 2.7783 - val_mean_absolute_error: 2.7783 - lr: 1.2960e-04
Epoch 83: early stopping
4/4 [==============================] - 0s 2ms/step

,iter,Model,ACC,AFS,MAE,RMSE,RMSE2,50th%error,75th%error,95th%error,avg_le
0,0,DNNR_24GHz,1.0,4.122421,4.122421,4.033235,7.09753,3.539617,4.999208,8.284059,6.840364

Epoch 1/250
7/7 [==============================] - 1s 44ms/step - loss: 21.4028 - mean_absolute_error: 21.4028 - val_loss: 21.0382 - val_mean_absolute_error: 21.0382 - lr: 0.0010
Epoch 2/250
7/7 [==============================] - 0s 12ms/step - loss: 20.7267 - mean_absolute_error: 20.7267 - val_loss: 20.0015 - val_mean_absolute_error: 20.0015 - lr: 0.0010
Epoch 3/250
7/7 [==============================] - 0s 14ms/step - loss: 19.5335 - mean_absolute_error: 19.5335 - val_loss: 18.4268 - val_mean_absolute_error: 18.4268 - lr: 0.0010
Epoch 4/250
7/7 [==============================] - 0s 13ms/step - loss: 18.0315 - mean_absolute_error: 18.0315 - val_loss: 17.0593 - val_mean_absolute_error: 17.0593 - lr: 0.0010
Epoch 5/250
7/7 [==============================] - 0s 13ms/step - loss: 16.4517 - mean_absolute_error: 16.4517 - val_loss: 14.9817 - val_mean_absolute_error: 14.9817 - lr: 0.0010
Epoch 6/250
7/7 [==============================] - 0s 13ms/step - loss: 14.3362 - mean_absolute_error: 14.3362 - val_loss: 12.6205 - val_mean_absolute_error: 12.6205 - lr: 0.0010
Epoch 7/250
7/7 [==============================] - 0s 13ms/step - loss: 12.0904 - mean_absolute_error: 12.0904 - val_loss: 10.7691 - val_mean_absolute_error: 10.7691 - lr: 0.0010
Epoch 8/250
7/7 [==============================] - 0s 13ms/step - loss: 10.7576 - mean_absolute_error: 10.7576 - val_loss: 9.9871 - val_mean_absolute_error: 9.9871 - lr: 0.0010
Epoch 9/250
7/7 [==============================] - 0s 12ms/step - loss: 9.8507 - mean_absolute_error: 9.8507 - val_loss: 8.9435 - val_mean_absolute_error: 8.9435 - lr: 0.0010
Epoch 10/250
7/7 [==============================] - 0s 14ms/step - loss: 8.7027 - mean_absolute_error: 8.7027 - val_loss: 7.9471 - val_mean_absolute_error: 7.9471 - lr: 0.0010
Epoch 11/250
7/7 [==============================] - 0s 13ms/step - loss: 7.7675 - mean_absolute_error: 7.7675 - val_loss: 7.0893 - val_mean_absolute_error: 7.0893 - lr: 0.0010
Epoch 12/250
7/7 [==============================] - 0s 13ms/step - loss: 6.7924 - mean_absolute_error: 6.7924 - val_loss: 6.2629 - val_mean_absolute_error: 6.2629 - lr: 0.0010
Epoch 13/250
7/7 [==============================] - 0s 13ms/step - loss: 6.1341 - mean_absolute_error: 6.1341 - val_loss: 5.8141 - val_mean_absolute_error: 5.8141 - lr: 0.0010
Epoch 14/250
7/7 [==============================] - 0s 14ms/step - loss: 5.7165 - mean_absolute_error: 5.7165 - val_loss: 5.4715 - val_mean_absolute_error: 5.4715 - lr: 0.0010
Epoch 15/250
7/7 [==============================] - 0s 13ms/step - loss: 5.3655 - mean_absolute_error: 5.3655 - val_loss: 5.2310 - val_mean_absolute_error: 5.2310 - lr: 0.0010
Epoch 16/250
7/7 [==============================] - 0s 14ms/step - loss: 5.0657 - mean_absolute_error: 5.0657 - val_loss: 5.0247 - val_mean_absolute_error: 5.0247 - lr: 0.0010
Epoch 17/250
7/7 [==============================] - 0s 14ms/step - loss: 4.7557 - mean_absolute_error: 4.7557 - val_loss: 4.6388 - val_mean_absolute_error: 4.6388 - lr: 0.0010
Epoch 18/250
7/7 [==============================] - 0s 13ms/step - loss: 4.4703 - mean_absolute_error: 4.4703 - val_loss: 4.4428 - val_mean_absolute_error: 4.4428 - lr: 0.0010
Epoch 19/250
7/7 [==============================] - 0s 13ms/step - loss: 4.2148 - mean_absolute_error: 4.2148 - val_loss: 4.2178 - val_mean_absolute_error: 4.2178 - lr: 0.0010
Epoch 20/250
7/7 [==============================] - 0s 13ms/step - loss: 3.9777 - mean_absolute_error: 3.9777 - val_loss: 4.0509 - val_mean_absolute_error: 4.0509 - lr: 0.0010
Epoch 21/250
7/7 [==============================] - 0s 14ms/step - loss: 3.7677 - mean_absolute_error: 3.7677 - val_loss: 3.8892 - val_mean_absolute_error: 3.8892 - lr: 0.0010
Epoch 22/250
7/7 [==============================] - 0s 14ms/step - loss: 3.5951 - mean_absolute_error: 3.5951 - val_loss: 3.7348 - val_mean_absolute_error: 3.7348 - lr: 0.0010
Epoch 23/250
7/7 [==============================] - 0s 12ms/step - loss: 3.4328 - mean_absolute_error: 3.4328 - val_loss: 3.5806 - val_mean_absolute_error: 3.5806 - lr: 0.0010
Epoch 24/250
7/7 [==============================] - 0s 13ms/step - loss: 3.2792 - mean_absolute_error: 3.2792 - val_loss: 3.4688 - val_mean_absolute_error: 3.4688 - lr: 0.0010
Epoch 25/250
7/7 [==============================] - 0s 13ms/step - loss: 3.1366 - mean_absolute_error: 3.1366 - val_loss: 3.3520 - val_mean_absolute_error: 3.3520 - lr: 0.0010
Epoch 26/250
7/7 [==============================] - 0s 13ms/step - loss: 3.0265 - mean_absolute_error: 3.0265 - val_loss: 3.2555 - val_mean_absolute_error: 3.2555 - lr: 0.0010
Epoch 27/250
7/7 [==============================] - 0s 13ms/step - loss: 2.9296 - mean_absolute_error: 2.9296 - val_loss: 3.2290 - val_mean_absolute_error: 3.2290 - lr: 0.0010
Epoch 28/250
7/7 [==============================] - 0s 14ms/step - loss: 2.8412 - mean_absolute_error: 2.8412 - val_loss: 3.2058 - val_mean_absolute_error: 3.2058 - lr: 0.0010
Epoch 29/250
7/7 [==============================] - 0s 14ms/step - loss: 2.7664 - mean_absolute_error: 2.7664 - val_loss: 3.1285 - val_mean_absolute_error: 3.1285 - lr: 0.0010
Epoch 30/250
7/7 [==============================] - 0s 14ms/step - loss: 2.6971 - mean_absolute_error: 2.6971 - val_loss: 3.0600 - val_mean_absolute_error: 3.0600 - lr: 0.0010
Epoch 31/250
7/7 [==============================] - 0s 9ms/step - loss: 2.6373 - mean_absolute_error: 2.6373 - val_loss: 3.0671 - val_mean_absolute_error: 3.0671 - lr: 0.0010
Epoch 32/250
7/7 [==============================] - 0s 13ms/step - loss: 2.5905 - mean_absolute_error: 2.5905 - val_loss: 3.0387 - val_mean_absolute_error: 3.0387 - lr: 0.0010
Epoch 33/250
7/7 [==============================] - 0s 13ms/step - loss: 2.5420 - mean_absolute_error: 2.5420 - val_loss: 3.0273 - val_mean_absolute_error: 3.0273 - lr: 0.0010
Epoch 34/250
7/7 [==============================] - 0s 10ms/step - loss: 2.5024 - mean_absolute_error: 2.5024 - val_loss: 3.0289 - val_mean_absolute_error: 3.0289 - lr: 0.0010
Epoch 35/250
7/7 [==============================] - 0s 15ms/step - loss: 2.4824 - mean_absolute_error: 2.4824 - val_loss: 2.9679 - val_mean_absolute_error: 2.9679 - lr: 0.0010
Epoch 36/250
7/7 [==============================] - 0s 8ms/step - loss: 2.4573 - mean_absolute_error: 2.4573 - val_loss: 2.9877 - val_mean_absolute_error: 2.9877 - lr: 0.0010
Epoch 37/250
7/7 [==============================] - 0s 15ms/step - loss: 2.4095 - mean_absolute_error: 2.4095 - val_loss: 2.9423 - val_mean_absolute_error: 2.9423 - lr: 0.0010
Epoch 38/250
7/7 [==============================] - 0s 9ms/step - loss: 2.3811 - mean_absolute_error: 2.3811 - val_loss: 2.9623 - val_mean_absolute_error: 2.9623 - lr: 0.0010
Epoch 39/250
7/7 [==============================] - 0s 13ms/step - loss: 2.3501 - mean_absolute_error: 2.3501 - val_loss: 2.9081 - val_mean_absolute_error: 2.9081 - lr: 0.0010
Epoch 40/250
7/7 [==============================] - 0s 13ms/step - loss: 2.3213 - mean_absolute_error: 2.3213 - val_loss: 2.8921 - val_mean_absolute_error: 2.8921 - lr: 0.0010
Epoch 41/250
7/7 [==============================] - 0s 9ms/step - loss: 2.2974 - mean_absolute_error: 2.2974 - val_loss: 2.9220 - val_mean_absolute_error: 2.9220 - lr: 0.0010
Epoch 42/250
7/7 [==============================] - 0s 13ms/step - loss: 2.2799 - mean_absolute_error: 2.2799 - val_loss: 2.8762 - val_mean_absolute_error: 2.8762 - lr: 0.0010
Epoch 43/250
7/7 [==============================] - 0s 10ms/step - loss: 2.2615 - mean_absolute_error: 2.2615 - val_loss: 2.9061 - val_mean_absolute_error: 2.9061 - lr: 0.0010
Epoch 44/250
7/7 [==============================] - 0s 10ms/step - loss: 2.2513 - mean_absolute_error: 2.2513 - val_loss: 2.9277 - val_mean_absolute_error: 2.9277 - lr: 0.0010
Epoch 45/250
7/7 [==============================] - 0s 13ms/step - loss: 2.2264 - mean_absolute_error: 2.2264 - val_loss: 2.8323 - val_mean_absolute_error: 2.8323 - lr: 0.0010
Epoch 46/250
7/7 [==============================] - 0s 10ms/step - loss: 2.2108 - mean_absolute_error: 2.2108 - val_loss: 2.9246 - val_mean_absolute_error: 2.9246 - lr: 0.0010
Epoch 47/250

7/7 [==============================] - 0s 13ms/step - loss: 2.1970 - mean_absolute_error: 2.1970 - val_loss: 2.8316 - val_mean_absolute_error: 2.8316 - lr: 0.0010
Epoch 48/250
7/7 [==============================] - 0s 9ms/step - loss: 2.1754 - mean_absolute_error: 2.1754 - val_loss: 2.8569 - val_mean_absolute_error: 2.8569 - lr: 0.0010
Epoch 49/250
7/7 [==============================] - 0s 10ms/step - loss: 2.1538 - mean_absolute_error: 2.1538 - val_loss: 2.8735 - val_mean_absolute_error: 2.8735 - lr: 0.0010
Epoch 50/250
7/7 [==============================] - 0s 13ms/step - loss: 2.1494 - mean_absolute_error: 2.1494 - val_loss: 2.7716 - val_mean_absolute_error: 2.7716 - lr: 0.0010
Epoch 51/250
7/7 [==============================] - 0s 10ms/step - loss: 2.1496 - mean_absolute_error: 2.1496 - val_loss: 2.8442 - val_mean_absolute_error: 2.8442 - lr: 0.0010
Epoch 52/250
7/7 [==============================] - 0s 9ms/step - loss: 2.1274 - mean_absolute_error: 2.1274 - val_loss: 2.7952 - val_mean_absolute_error: 2.7952 - lr: 0.0010
Epoch 53/250
7/7 [==============================] - 0s 9ms/step - loss: 2.1144 - mean_absolute_error: 2.1144 - val_loss: 2.8548 - val_mean_absolute_error: 2.8548 - lr: 0.0010
Epoch 54/250
7/7 [==============================] - 0s 10ms/step - loss: 2.1022 - mean_absolute_error: 2.1022 - val_loss: 2.8068 - val_mean_absolute_error: 2.8068 - lr: 0.0010
Epoch 55/250
7/7 [==============================] - 0s 13ms/step - loss: 2.0828 - mean_absolute_error: 2.0828 - val_loss: 2.7642 - val_mean_absolute_error: 2.7642 - lr: 0.0010
Epoch 56/250
7/7 [==============================] - 0s 9ms/step - loss: 2.0748 - mean_absolute_error: 2.0748 - val_loss: 2.8313 - val_mean_absolute_error: 2.8313 - lr: 0.0010
Epoch 57/250
7/7 [==============================] - 0s 9ms/step - loss: 2.0596 - mean_absolute_error: 2.0596 - val_loss: 2.7877 - val_mean_absolute_error: 2.7877 - lr: 0.0010
Epoch 58/250
7/7 [==============================] - 0s 8ms/step - loss: 2.0559 - mean_absolute_error: 2.0559 - val_loss: 2.8248 - val_mean_absolute_error: 2.8248 - lr: 0.0010
Epoch 59/250
7/7 [==============================] - 0s 13ms/step - loss: 2.0567 - mean_absolute_error: 2.0567 - val_loss: 2.7520 - val_mean_absolute_error: 2.7520 - lr: 0.0010
Epoch 60/250
7/7 [==============================] - 0s 9ms/step - loss: 2.0502 - mean_absolute_error: 2.0502 - val_loss: 2.8772 - val_mean_absolute_error: 2.8772 - lr: 0.0010
Epoch 61/250
7/7 [==============================] - 0s 12ms/step - loss: 2.0566 - mean_absolute_error: 2.0566 - val_loss: 2.7193 - val_mean_absolute_error: 2.7193 - lr: 0.0010
Epoch 62/250
7/7 [==============================] - 0s 9ms/step - loss: 2.0358 - mean_absolute_error: 2.0358 - val_loss: 2.8287 - val_mean_absolute_error: 2.8287 - lr: 0.0010
Epoch 63/250
7/7 [==============================] - 0s 8ms/step - loss: 2.0203 - mean_absolute_error: 2.0203 - val_loss: 2.7214 - val_mean_absolute_error: 2.7214 - lr: 0.0010
Epoch 64/250
7/7 [==============================] - 0s 9ms/step - loss: 2.0200 - mean_absolute_error: 2.0200 - val_loss: 2.7357 - val_mean_absolute_error: 2.7357 - lr: 0.0010
Epoch 65/250
7/7 [==============================] - 0s 12ms/step - loss: 1.9862 - mean_absolute_error: 1.9862 - val_loss: 2.7095 - val_mean_absolute_error: 2.7095 - lr: 0.0010
Epoch 66/250
7/7 [==============================] - 0s 10ms/step - loss: 1.9850 - mean_absolute_error: 1.9850 - val_loss: 2.7752 - val_mean_absolute_error: 2.7752 - lr: 0.0010
Epoch 67/250
7/7 [==============================] - 0s 9ms/step - loss: 1.9753 - mean_absolute_error: 1.9753 - val_loss: 2.7167 - val_mean_absolute_error: 2.7167 - lr: 0.0010
Epoch 68/250
7/7 [==============================] - 0s 8ms/step - loss: 1.9646 - mean_absolute_error: 1.9646 - val_loss: 2.7179 - val_mean_absolute_error: 2.7179 - lr: 0.0010
Epoch 69/250
7/7 [==============================] - 0s 9ms/step - loss: 1.9543 - mean_absolute_error: 1.9543 - val_loss: 2.7171 - val_mean_absolute_error: 2.7171 - lr: 0.0010
Epoch 70/250
7/7 [==============================] - 0s 13ms/step - loss: 1.9482 - mean_absolute_error: 1.9482 - val_loss: 2.7011 - val_mean_absolute_error: 2.7011 - lr: 0.0010
Epoch 71/250
7/7 [==============================] - 0s 9ms/step - loss: 1.9406 - mean_absolute_error: 1.9406 - val_loss: 2.7806 - val_mean_absolute_error: 2.7806 - lr: 0.0010
Epoch 72/250
7/7 [==============================] - 0s 10ms/step - loss: 1.9407 - mean_absolute_error: 1.9407 - val_loss: 2.7291 - val_mean_absolute_error: 2.7291 - lr: 0.0010
Epoch 73/250
7/7 [==============================] - 0s 9ms/step - loss: 1.9362 - mean_absolute_error: 1.9362 - val_loss: 2.7106 - val_mean_absolute_error: 2.7106 - lr: 0.0010
Epoch 74/250
7/7 [==============================] - 0s 10ms/step - loss: 1.9233 - mean_absolute_error: 1.9233 - val_loss: 2.7807 - val_mean_absolute_error: 2.7807 - lr: 0.0010
Epoch 75/250
7/7 [==============================] - 0s 13ms/step - loss: 1.9324 - mean_absolute_error: 1.9324 - val_loss: 2.6932 - val_mean_absolute_error: 2.6932 - lr: 0.0010
Epoch 76/250
7/7 [==============================] - 0s 11ms/step - loss: 1.9093 - mean_absolute_error: 1.9093 - val_loss: 2.7354 - val_mean_absolute_error: 2.7354 - lr: 0.0010
Epoch 77/250
7/7 [==============================] - 0s 13ms/step - loss: 1.9006 - mean_absolute_error: 1.9006 - val_loss: 2.6384 - val_mean_absolute_error: 2.6384 - lr: 0.0010
Epoch 78/250
7/7 [==============================] - 0s 10ms/step - loss: 1.9071 - mean_absolute_error: 1.9071 - val_loss: 2.7416 - val_mean_absolute_error: 2.7416 - lr: 0.0010
Epoch 79/250
7/7 [==============================] - 0s 10ms/step - loss: 1.9006 - mean_absolute_error: 1.9006 - val_loss: 2.6937 - val_mean_absolute_error: 2.6937 - lr: 0.0010
Epoch 80/250
7/7 [==============================] - 0s 9ms/step - loss: 1.8954 - mean_absolute_error: 1.8954 - val_loss: 2.6915 - val_mean_absolute_error: 2.6915 - lr: 0.0010
Epoch 81/250
7/7 [==============================] - 0s 9ms/step - loss: 1.8775 - mean_absolute_error: 1.8775 - val_loss: 2.6964 - val_mean_absolute_error: 2.6964 - lr: 0.0010
Epoch 82/250
1/7 [===>..........................] - ETA: 0s - loss: 2.0259 - mean_absolute_error: 2.0259
Epoch 82: ReduceLROnPlateau reducing learning rate to 0.0006000000284984708.
7/7 [==============================] - 0s 9ms/step - loss: 1.8727 - mean_absolute_error: 1.8727 - val_loss: 2.6815 - val_mean_absolute_error: 2.6815 - lr: 0.0010
Epoch 83/250
7/7 [==============================] - 0s 9ms/step - loss: 1.8596 - mean_absolute_error: 1.8596 - val_loss: 2.6649 - val_mean_absolute_error: 2.6649 - lr: 6.0000e-04
Epoch 84/250
7/7 [==============================] - 0s 10ms/step - loss: 1.8654 - mean_absolute_error: 1.8654 - val_loss: 2.6921 - val_mean_absolute_error: 2.6921 - lr: 6.0000e-04
Epoch 85/250
1/7 [===>..........................] - ETA: 0s - loss: 1.8682 - mean_absolute_error: 1.8682Restoring model weights from the end of the best epoch: 77.
7/7 [==============================] - 0s 9ms/step - loss: 1.8535 - mean_absolute_error: 1.8535 - val_loss: 2.6864 - val_mean_absolute_error: 2.6864 - lr: 6.0000e-04
Epoch 85: early stopping
4/4 [==============================] - 0s 4ms/step

,iter,Model,ACC,AFS,MAE,RMSE,RMSE2,50th%error,75th%error,95th%error,avg_le
0,0,DNNR_24GHz,1.0,4.122421,4.122421,4.033235,7.097530,3.539617,4.999208,8.284059,6.840364
1,1,DNNR_24GHz,1.0,3.922138,3.922138,3.872349,6.869014,3.310868,4.458023,7.697840,6.575005

Epoch 1/250
7/7 [==============================] - 1s 45ms/step - loss: 21.3650 - mean_absolute_error: 21.3650 - val_loss: 20.9068 - val_mean_absolute_error: 20.9068 - lr: 0.0010
Epoch 2/250
7/7 [==============================] - 0s 13ms/step - loss: 20.5737 - mean_absolute_error: 20.5737 - val_loss: 19.7494 - val_mean_absolute_error: 19.7494 - lr: 0.0010
Epoch 3/250
7/7 [==============================] - 0s 13ms/step - loss: 19.3075 - mean_absolute_error: 19.3075 - val_loss: 18.3827 - val_mean_absolute_error: 18.3827 - lr: 0.0010
Epoch 4/250
7/7 [==============================] - 0s 12ms/step - loss: 17.9954 - mean_absolute_error: 17.9954 - val_loss: 16.9998 - val_mean_absolute_error: 16.9998 - lr: 0.0010
Epoch 5/250
7/7 [==============================] - 0s 14ms/step - loss: 16.4271 - mean_absolute_error: 16.4271 - val_loss: 15.0317 - val_mean_absolute_error: 15.0317 - lr: 0.0010
Epoch 6/250
7/7 [==============================] - 0s 13ms/step - loss: 14.4273 - mean_absolute_error: 14.4273 - val_loss: 12.8225 - val_mean_absolute_error: 12.8225 - lr: 0.0010
Epoch 7/250
7/7 [==============================] - 0s 13ms/step - loss: 12.3507 - mean_absolute_error: 12.3507 - val_loss: 11.0022 - val_mean_absolute_error: 11.0022 - lr: 0.0010
Epoch 8/250
7/7 [==============================] - 0s 13ms/step - loss: 10.8339 - mean_absolute_error: 10.8339 - val_loss: 10.0243 - val_mean_absolute_error: 10.0243 - lr: 0.0010
Epoch 9/250
7/7 [==============================] - 0s 12ms/step - loss: 9.7063 - mean_absolute_error: 9.7063 - val_loss: 8.8134 - val_mean_absolute_error: 8.8134 - lr: 0.0010
Epoch 10/250
7/7 [==============================] - 0s 14ms/step - loss: 8.5395 - mean_absolute_error: 8.5395 - val_loss: 7.7587 - val_mean_absolute_error: 7.7587 - lr: 0.0010
Epoch 11/250
7/7 [==============================] - 0s 14ms/step - loss: 7.4712 - mean_absolute_error: 7.4712 - val_loss: 6.7978 - val_mean_absolute_error: 6.7978 - lr: 0.0010
Epoch 12/250
7/7 [==============================] - 0s 13ms/step - loss: 6.4701 - mean_absolute_error: 6.4701 - val_loss: 6.0479 - val_mean_absolute_error: 6.0479 - lr: 0.0010
Epoch 13/250
7/7 [==============================] - 0s 13ms/step - loss: 5.9344 - mean_absolute_error: 5.9344 - val_loss: 5.7545 - val_mean_absolute_error: 5.7545 - lr: 0.0010
Epoch 14/250
7/7 [==============================] - 0s 14ms/step - loss: 5.6216 - mean_absolute_error: 5.6216 - val_loss: 5.5123 - val_mean_absolute_error: 5.5123 - lr: 0.0010
Epoch 15/250
7/7 [==============================] - 0s 14ms/step - loss: 5.3200 - mean_absolute_error: 5.3200 - val_loss: 5.1432 - val_mean_absolute_error: 5.1432 - lr: 0.0010
Epoch 16/250
7/7 [==============================] - 0s 13ms/step - loss: 5.0047 - mean_absolute_error: 5.0047 - val_loss: 4.9522 - val_mean_absolute_error: 4.9522 - lr: 0.0010
Epoch 17/250
7/7 [==============================] - 0s 14ms/step - loss: 4.7293 - mean_absolute_error: 4.7293 - val_loss: 4.6358 - val_mean_absolute_error: 4.6358 - lr: 0.0010
Epoch 18/250
7/7 [==============================] - 0s 13ms/step - loss: 4.4949 - mean_absolute_error: 4.4949 - val_loss: 4.4611 - val_mean_absolute_error: 4.4611 - lr: 0.0010
Epoch 19/250
7/7 [==============================] - 0s 14ms/step - loss: 4.2645 - mean_absolute_error: 4.2645 - val_loss: 4.2874 - val_mean_absolute_error: 4.2874 - lr: 0.0010
Epoch 20/250
7/7 [==============================] - 0s 14ms/step - loss: 4.0272 - mean_absolute_error: 4.0272 - val_loss: 4.0818 - val_mean_absolute_error: 4.0818 - lr: 0.0010
Epoch 21/250
7/7 [==============================] - 0s 12ms/step - loss: 3.8372 - mean_absolute_error: 3.8372 - val_loss: 3.8845 - val_mean_absolute_error: 3.8845 - lr: 0.0010
Epoch 22/250
7/7 [==============================] - 0s 12ms/step - loss: 3.6472 - mean_absolute_error: 3.6472 - val_loss: 3.7627 - val_mean_absolute_error: 3.7627 - lr: 0.0010
Epoch 23/250
7/7 [==============================] - 0s 12ms/step - loss: 3.4789 - mean_absolute_error: 3.4789 - val_loss: 3.5707 - val_mean_absolute_error: 3.5707 - lr: 0.0010
Epoch 24/250
7/7 [==============================] - 0s 13ms/step - loss: 3.3163 - mean_absolute_error: 3.3163 - val_loss: 3.4329 - val_mean_absolute_error: 3.4329 - lr: 0.0010
Epoch 25/250
7/7 [==============================] - 0s 13ms/step - loss: 3.1683 - mean_absolute_error: 3.1683 - val_loss: 3.3186 - val_mean_absolute_error: 3.3186 - lr: 0.0010
Epoch 26/250
7/7 [==============================] - 0s 14ms/step - loss: 3.0424 - mean_absolute_error: 3.0424 - val_loss: 3.2558 - val_mean_absolute_error: 3.2558 - lr: 0.0010
Epoch 27/250
7/7 [==============================] - 0s 14ms/step - loss: 2.9257 - mean_absolute_error: 2.9257 - val_loss: 3.2028 - val_mean_absolute_error: 3.2028 - lr: 0.0010
Epoch 28/250
7/7 [==============================] - 0s 13ms/step - loss: 2.8256 - mean_absolute_error: 2.8256 - val_loss: 3.1577 - val_mean_absolute_error: 3.1577 - lr: 0.0010
Epoch 29/250
7/7 [==============================] - 0s 13ms/step - loss: 2.7408 - mean_absolute_error: 2.7408 - val_loss: 3.1179 - val_mean_absolute_error: 3.1179 - lr: 0.0010
Epoch 30/250
7/7 [==============================] - 0s 13ms/step - loss: 2.6800 - mean_absolute_error: 2.6800 - val_loss: 3.0423 - val_mean_absolute_error: 3.0423 - lr: 0.0010
Epoch 31/250
7/7 [==============================] - 0s 9ms/step - loss: 2.6211 - mean_absolute_error: 2.6211 - val_loss: 3.0512 - val_mean_absolute_error: 3.0512 - lr: 0.0010
Epoch 32/250
7/7 [==============================] - 0s 14ms/step - loss: 2.5595 - mean_absolute_error: 2.5595 - val_loss: 3.0306 - val_mean_absolute_error: 3.0306 - lr: 0.0010
Epoch 33/250
7/7 [==============================] - 0s 14ms/step - loss: 2.5101 - mean_absolute_error: 2.5101 - val_loss: 3.0085 - val_mean_absolute_error: 3.0085 - lr: 0.0010
Epoch 34/250
7/7 [==============================] - 0s 9ms/step - loss: 2.4625 - mean_absolute_error: 2.4625 - val_loss: 3.0304 - val_mean_absolute_error: 3.0304 - lr: 0.0010
Epoch 35/250
7/7 [==============================] - 0s 13ms/step - loss: 2.4235 - mean_absolute_error: 2.4235 - val_loss: 2.9495 - val_mean_absolute_error: 2.9495 - lr: 0.0010
Epoch 36/250
7/7 [==============================] - 0s 13ms/step - loss: 2.3954 - mean_absolute_error: 2.3954 - val_loss: 2.9450 - val_mean_absolute_error: 2.9450 - lr: 0.0010
Epoch 37/250
7/7 [==============================] - 0s 13ms/step - loss: 2.3603 - mean_absolute_error: 2.3603 - val_loss: 2.9190 - val_mean_absolute_error: 2.9190 - lr: 0.0010
Epoch 38/250
7/7 [==============================] - 0s 10ms/step - loss: 2.3445 - mean_absolute_error: 2.3445 - val_loss: 2.9462 - val_mean_absolute_error: 2.9462 - lr: 0.0010
Epoch 39/250
7/7 [==============================] - 0s 13ms/step - loss: 2.2987 - mean_absolute_error: 2.2987 - val_loss: 2.8892 - val_mean_absolute_error: 2.8892 - lr: 0.0010
Epoch 40/250
7/7 [==============================] - 0s 10ms/step - loss: 2.2817 - mean_absolute_error: 2.2817 - val_loss: 2.8979 - val_mean_absolute_error: 2.8979 - lr: 0.0010
Epoch 41/250
7/7 [==============================] - 0s 9ms/step - loss: 2.2579 - mean_absolute_error: 2.2579 - val_loss: 2.9151 - val_mean_absolute_error: 2.9151 - lr: 0.0010
Epoch 42/250
7/7 [==============================] - 0s 12ms/step - loss: 2.2509 - mean_absolute_error: 2.2509 - val_loss: 2.8702 - val_mean_absolute_error: 2.8702 - lr: 0.0010
Epoch 43/250
7/7 [==============================] - 0s 10ms/step - loss: 2.2300 - mean_absolute_error: 2.2300 - val_loss: 2.8972 - val_mean_absolute_error: 2.8972 - lr: 0.0010
Epoch 44/250
7/7 [==============================] - 0s 10ms/step - loss: 2.1978 - mean_absolute_error: 2.1978 - val_loss: 2.8730 - val_mean_absolute_error: 2.8730 - lr: 0.0010
Epoch 45/250
7/7 [==============================] - 0s 14ms/step - loss: 2.1777 - mean_absolute_error: 2.1777 - val_loss: 2.8695 - val_mean_absolute_error: 2.8695 - lr: 0.0010
Epoch 46/250
7/7 [==============================] - 0s 13ms/step - loss: 2.1616 - mean_absolute_error: 2.1616 - val_loss: 2.8507 - val_mean_absolute_error: 2.8507 - lr: 0.0010
Epoch 47/250

7/7 [==============================] - 0s 9ms/step - loss: 2.1462 - mean_absolute_error: 2.1462 - val_loss: 2.8615 - val_mean_absolute_error: 2.8615 - lr: 0.0010
Epoch 48/250
7/7 [==============================] - 0s 14ms/step - loss: 2.1230 - mean_absolute_error: 2.1230 - val_loss: 2.8416 - val_mean_absolute_error: 2.8416 - lr: 0.0010
Epoch 49/250
7/7 [==============================] - 0s 13ms/step - loss: 2.1173 - mean_absolute_error: 2.1173 - val_loss: 2.8351 - val_mean_absolute_error: 2.8351 - lr: 0.0010
Epoch 50/250
7/7 [==============================] - 0s 13ms/step - loss: 2.1111 - mean_absolute_error: 2.1111 - val_loss: 2.8179 - val_mean_absolute_error: 2.8179 - lr: 0.0010
Epoch 51/250
7/7 [==============================] - 0s 10ms/step - loss: 2.0846 - mean_absolute_error: 2.0846 - val_loss: 2.8534 - val_mean_absolute_error: 2.8534 - lr: 0.0010
Epoch 52/250
7/7 [==============================] - 0s 13ms/step - loss: 2.0776 - mean_absolute_error: 2.0776 - val_loss: 2.7684 - val_mean_absolute_error: 2.7684 - lr: 0.0010
Epoch 53/250
7/7 [==============================] - 0s 9ms/step - loss: 2.0687 - mean_absolute_error: 2.0687 - val_loss: 2.8703 - val_mean_absolute_error: 2.8703 - lr: 0.0010
Epoch 54/250
7/7 [==============================] - 0s 9ms/step - loss: 2.0577 - mean_absolute_error: 2.0577 - val_loss: 2.8032 - val_mean_absolute_error: 2.8032 - lr: 0.0010
Epoch 55/250
7/7 [==============================] - 0s 9ms/step - loss: 2.0494 - mean_absolute_error: 2.0494 - val_loss: 2.7957 - val_mean_absolute_error: 2.7957 - lr: 0.0010
Epoch 56/250
7/7 [==============================] - 0s 9ms/step - loss: 2.0337 - mean_absolute_error: 2.0337 - val_loss: 2.8119 - val_mean_absolute_error: 2.8119 - lr: 0.0010
Epoch 57/250
7/7 [==============================] - 0s 12ms/step - loss: 2.0239 - mean_absolute_error: 2.0239 - val_loss: 2.7516 - val_mean_absolute_error: 2.7516 - lr: 0.0010
Epoch 58/250
7/7 [==============================] - 0s 9ms/step - loss: 2.0174 - mean_absolute_error: 2.0174 - val_loss: 2.7790 - val_mean_absolute_error: 2.7790 - lr: 0.0010
Epoch 59/250
7/7 [==============================] - 0s 10ms/step - loss: 1.9933 - mean_absolute_error: 1.9933 - val_loss: 2.7801 - val_mean_absolute_error: 2.7801 - lr: 0.0010
Epoch 60/250
7/7 [==============================] - 0s 9ms/step - loss: 1.9884 - mean_absolute_error: 1.9884 - val_loss: 2.7737 - val_mean_absolute_error: 2.7737 - lr: 0.0010
Epoch 61/250
7/7 [==============================] - 0s 10ms/step - loss: 1.9809 - mean_absolute_error: 1.9809 - val_loss: 2.7659 - val_mean_absolute_error: 2.7659 - lr: 0.0010
Epoch 62/250
7/7 [==============================] - 0s 13ms/step - loss: 1.9734 - mean_absolute_error: 1.9734 - val_loss: 2.7381 - val_mean_absolute_error: 2.7381 - lr: 0.0010
Epoch 63/250
7/7 [==============================] - 0s 10ms/step - loss: 1.9779 - mean_absolute_error: 1.9779 - val_loss: 2.8076 - val_mean_absolute_error: 2.8076 - lr: 0.0010
Epoch 64/250
7/7 [==============================] - 0s 10ms/step - loss: 1.9624 - mean_absolute_error: 1.9624 - val_loss: 2.7881 - val_mean_absolute_error: 2.7881 - lr: 0.0010
Epoch 65/250
7/7 [==============================] - 0s 10ms/step - loss: 1.9718 - mean_absolute_error: 1.9718 - val_loss: 2.7462 - val_mean_absolute_error: 2.7462 - lr: 0.0010
Epoch 66/250
7/7 [==============================] - 0s 10ms/step - loss: 1.9534 - mean_absolute_error: 1.9534 - val_loss: 2.7533 - val_mean_absolute_error: 2.7533 - lr: 0.0010
Epoch 67/250
1/7 [===>..........................] - ETA: 0s - loss: 1.7653 - mean_absolute_error: 1.7653
Epoch 67: ReduceLROnPlateau reducing learning rate to 0.0006000000284984708.
7/7 [==============================] - 0s 10ms/step - loss: 1.9226 - mean_absolute_error: 1.9226 - val_loss: 2.7668 - val_mean_absolute_error: 2.7668 - lr: 0.0010
Epoch 68/250
7/7 [==============================] - 0s 10ms/step - loss: 1.9159 - mean_absolute_error: 1.9159 - val_loss: 2.7446 - val_mean_absolute_error: 2.7446 - lr: 6.0000e-04
Epoch 69/250
7/7 [==============================] - 0s 10ms/step - loss: 1.9003 - mean_absolute_error: 1.9003 - val_loss: 2.7407 - val_mean_absolute_error: 2.7407 - lr: 6.0000e-04
Epoch 70/250
7/7 [==============================] - 0s 14ms/step - loss: 1.9011 - mean_absolute_error: 1.9011 - val_loss: 2.7105 - val_mean_absolute_error: 2.7105 - lr: 6.0000e-04
Epoch 71/250
7/7 [==============================] - 0s 10ms/step - loss: 1.9084 - mean_absolute_error: 1.9084 - val_loss: 2.7519 - val_mean_absolute_error: 2.7519 - lr: 6.0000e-04
Epoch 72/250
7/7 [==============================] - 0s 13ms/step - loss: 1.8952 - mean_absolute_error: 1.8952 - val_loss: 2.7091 - val_mean_absolute_error: 2.7091 - lr: 6.0000e-04
Epoch 73/250
7/7 [==============================] - 0s 8ms/step - loss: 1.8892 - mean_absolute_error: 1.8892 - val_loss: 2.7634 - val_mean_absolute_error: 2.7634 - lr: 6.0000e-04
Epoch 74/250
7/7 [==============================] - 0s 14ms/step - loss: 1.8891 - mean_absolute_error: 1.8891 - val_loss: 2.7088 - val_mean_absolute_error: 2.7088 - lr: 6.0000e-04
Epoch 75/250
7/7 [==============================] - 0s 9ms/step - loss: 1.8825 - mean_absolute_error: 1.8825 - val_loss: 2.7603 - val_mean_absolute_error: 2.7603 - lr: 6.0000e-04
Epoch 76/250
7/7 [==============================] - 0s 12ms/step - loss: 1.8800 - mean_absolute_error: 1.8800 - val_loss: 2.6958 - val_mean_absolute_error: 2.6958 - lr: 6.0000e-04
Epoch 77/250
7/7 [==============================] - 0s 10ms/step - loss: 1.8785 - mean_absolute_error: 1.8785 - val_loss: 2.7443 - val_mean_absolute_error: 2.7443 - lr: 6.0000e-04
Epoch 78/250
7/7 [==============================] - 0s 12ms/step - loss: 1.8691 - mean_absolute_error: 1.8691 - val_loss: 2.6899 - val_mean_absolute_error: 2.6899 - lr: 6.0000e-04
Epoch 79/250
7/7 [==============================] - 0s 10ms/step - loss: 1.8660 - mean_absolute_error: 1.8660 - val_loss: 2.7353 - val_mean_absolute_error: 2.7353 - lr: 6.0000e-04
Epoch 80/250
7/7 [==============================] - 0s 13ms/step - loss: 1.8603 - mean_absolute_error: 1.8603 - val_loss: 2.6846 - val_mean_absolute_error: 2.6846 - lr: 6.0000e-04
Epoch 81/250
7/7 [==============================] - 0s 9ms/step - loss: 1.8686 - mean_absolute_error: 1.8686 - val_loss: 2.7519 - val_mean_absolute_error: 2.7519 - lr: 6.0000e-04
Epoch 82/250
7/7 [==============================] - 0s 10ms/step - loss: 1.8607 - mean_absolute_error: 1.8607 - val_loss: 2.7099 - val_mean_absolute_error: 2.7099 - lr: 6.0000e-04
Epoch 83/250
7/7 [==============================] - 0s 10ms/step - loss: 1.8555 - mean_absolute_error: 1.8555 - val_loss: 2.7193 - val_mean_absolute_error: 2.7193 - lr: 6.0000e-04
Epoch 84/250
7/7 [==============================] - 0s 11ms/step - loss: 1.8563 - mean_absolute_error: 1.8563 - val_loss: 2.6912 - val_mean_absolute_error: 2.6912 - lr: 6.0000e-04
Epoch 85/250
1/7 [===>..........................] - ETA: 0s - loss: 1.8100 - mean_absolute_error: 1.8100
Epoch 85: ReduceLROnPlateau reducing learning rate to 0.0003600000170990825.
7/7 [==============================] - 0s 9ms/step - loss: 1.8513 - mean_absolute_error: 1.8513 - val_loss: 2.6932 - val_mean_absolute_error: 2.6932 - lr: 6.0000e-04
Epoch 86/250
7/7 [==============================] - 0s 10ms/step - loss: 1.8419 - mean_absolute_error: 1.8419 - val_loss: 2.7070 - val_mean_absolute_error: 2.7070 - lr: 3.6000e-04
Epoch 87/250
7/7 [==============================] - 0s 10ms/step - loss: 1.8378 - mean_absolute_error: 1.8378 - val_loss: 2.6861 - val_mean_absolute_error: 2.6861 - lr: 3.6000e-04
Epoch 88/250
1/7 [===>..........................] - ETA: 0s - loss: 1.9065 - mean_absolute_error: 1.9065Restoring model weights from the end of the best epoch: 80.
7/7 [==============================] - 0s 10ms/step - loss: 1.8315 - mean_absolute_error: 1.8315 - val_loss: 2.6877 - val_mean_absolute_error: 2.6877 - lr: 3.6000e-04
Epoch 88: early stopping
4/4 [==============================] - 0s 3ms/step

,iter,Model,ACC,AFS,MAE,RMSE,RMSE2,50th%error,75th%error,95th%error,avg_le
0,0,DNNR_24GHz,1.0,4.122421,4.122421,4.033235,7.097530,3.539617,4.999208,8.284059,6.840364
1,1,DNNR_24GHz,1.0,3.922138,3.922138,3.872349,6.869014,3.310868,4.458023,7.697840,6.575005
2,2,DNNR_24GHz,1.0,4.001253,4.001253,3.934640,6.972718,3.347883,4.981908,7.995031,6.683080

In [17]:
#SOD_SYL
#MC_ACNNR

learning_rate=0.001
batch_size=64
epochs=1000

early_stop = EarlyStopping(monitor = 'val_loss', min_delta = 0.0001, 
                       patience = 8, mode = 'min', verbose = 1,
                       restore_best_weights = True)
reduce_lr = ReduceLROnPlateau(monitor = 'val_loss', factor = 0.6, 
                          patience = 4, min_delta = 0.0001, 
                          mode = 'min', verbose = 1)
    
columns= {'iter':[],
        'Model':[], 
        'ACC':[], 
        'AFS':[],
        'MAE':[], 
        'RMSE':[],
        'RMSE2':[],
        '50th%error':[],
        '75th%error':[],
        '95th%error':[],
        'avg_le':[]
       } 

df_comp= pd.DataFrame(columns)

filepath='C:/Users/user/Desktop/arzu_kodlar/indoor_diger/checkpoints/'

df=pd.read_csv('data/SYL_preprocessed/SOD_SYL_dual_merged_normalized_nondropped_testsamples.csv')
df = df.astype(float)

df_train = df[df['datatype'] == 1]
df_train=df_train.reset_index(drop=True)
df_test = df[df['datatype'] == 2]
df_test=df_test.reset_index(drop=True)

y_train= df_train[['ECoord', 'NCoord','FloorID']]
y_val=df_test[['ECoord', 'NCoord','FloorID']]

x_train=df_train.drop(['datatype','ECoord', 'NCoord','FloorID'], axis=1)
x_val=df_test.drop(['datatype','ECoord', 'NCoord','FloorID'], axis=1)

x_trainx = tf.convert_to_tensor(x_train)
y_trainx = tf.convert_to_tensor(y_train)

x_valx = tf.convert_to_tensor(x_val)
y_valx = tf.convert_to_tensor(y_val)
    

#each GHz area consits of 23 macs
maxlen=23

#if the input length is not equal to each other, you need to do zero padding for making equal them
#x_trainx=np.pad(x_train, ((0, 0), (0, 16)))
#x_valx=np.pad(x_val, ((0, 0), (0, 16)))


model_name='MC-ACNNR_dual'

for iter in range(0,3):
    
    y_val=df_test[['ECoord', 'NCoord','FloorID']]
    y_valx = tf.convert_to_tensor(y_val)

    checkpoint_filepath = filepath +model_name+ str(iter)+ '2.hdf5'

    model_checkpoint_callback = ModelCheckpoint(
    filepath=checkpoint_filepath,
    save_weights_only=True,
    monitor='val_mean_absolute_error',
    mode='min',
    save_best_only=True)
    
    #callbacks = [model_checkpoint_callback,early_stop,reduce_lr]
    callbacks = [model_checkpoint_callback]

    deep_model=model_CNN_Multichannel_att(maxlen,maxlen,y_val.shape[1],maxlen)

    deep_model.fit([x_trainx[:,0:maxlen],x_trainx[:,maxlen:maxlen*2]], y_trainx, epochs=epochs, batch_size=batch_size, callbacks=callbacks, validation_data=([x_valx[:,0:maxlen],x_valx[:,maxlen:maxlen*2]], y_valx))

    deep_model.load_weights(checkpoint_filepath)
    
    pred=deep_model.predict([x_valx[:,0:maxlen],x_valx[:,maxlen:maxlen*2]])
 
    floor_acc, avg_final_score, maex, rmsex, rmsex2, error50, error75, error95, average_le=calculate_performances(pred, y_val)   

    df_comp.loc[len(df_comp.index)] = [iter, model_name, floor_acc, avg_final_score, maex, rmsex, rmsex2, error50, error75, error95, average_le]  
    
    display(df_comp)

df_comp.to_csv("SOD_SYL_MC-ACNNR_nondrop.csv",index=False)

Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to
==================================================================================================
 input_3 (InputLayer)           [(None, 23, 1)]      0           []

 input_4 (InputLayer)           [(None, 23, 1)]      0           []

 conv1d_6 (Conv1D)              (None, 23, 32)       128         ['input_3[0][0]']

 conv1d_8 (Conv1D)              (None, 23, 32)       128         ['input_4[0][0]']

 conv1d_7 (Conv1D)              (None, 23, 32)       3104        ['conv1d_6[0][0]']

 conv1d_9 (Conv1D)              (None, 23, 32)       3104        ['conv1d_8[0][0]']

 concatenate_2 (Concatenate)    (None, 23, 64)       0           ['conv1d_7[0][0]',
                                                                  'conv1d_9[0][0]']

 conv1d_10 (Conv1D)             (None, 23, 32)       6176        ['concatenate_2[0][0]']

 conv1d_11 (Conv1D)             (None, 23, 32)       3104        ['conv1d_10[0][0]']

 max_pooling1d_1 (MaxPooling1D)  (None, 11, 32)      0           ['conv1d_11[0][0]']

 attention_2 (attention)        (None, 32)           55          ['conv1d_7[0][0]']

 flatten_1 (Flatten)            (None, 352)          0           ['max_pooling1d_1[0][0]']

 attention_3 (attention)        (None, 32)           55          ['conv1d_9[0][0]']

 concatenate_3 (Concatenate)    (None, 416)          0           ['attention_2[0][0]',
                                                                  'flatten_1[0][0]',
                                                                  'attention_3[0][0]']

 dense_12 (Dense)               (None, 256)          106752      ['concatenate_3[0][0]']

 dense_13 (Dense)               (None, 128)          32896       ['dense_12[0][0]']

 dense_14 (Dense)               (None, 3)            387         ['dense_13[0][0]']

==================================================================================================
Total params: 155,889
Trainable params: 155,889
Non-trainable params: 0
__________________________________________________________________________________________________
None
Epoch 1/1000
11/11 [==============================] - 2s 52ms/step - loss: 20.6228 - mean_absolute_error: 20.6228 - val_loss: 17.1760 - val_mean_absolute_error: 17.1760
Epoch 2/1000
11/11 [==============================] - 0s 20ms/step - loss: 15.3409 - mean_absolute_error: 15.3409 - val_loss: 12.5564 - val_mean_absolute_error: 12.5564
Epoch 3/1000
11/11 [==============================] - 0s 22ms/step - loss: 10.9256 - mean_absolute_error: 10.9256 - val_loss: 9.2876 - val_mean_absolute_error: 9.2876
Epoch 4/1000
11/11 [==============================] - 0s 21ms/step - loss: 8.9124 - mean_absolute_error: 8.9124 - val_loss: 8.0531 - val_mean_absolute_error: 8.0531
Epoch 5/1000
11/11 [==============================] - 0s 28ms/step - loss: 7.7745 - mean_absolute_error: 7.7745 - val_loss: 7.0419 - val_mean_absolute_error: 7.0419
Epoch 6/1000
11/11 [==============================] - 0s 23ms/step - loss: 6.9537 - mean_absolute_error: 6.9537 - val_loss: 6.8192 - val_mean_absolute_error: 6.8192
Epoch 7/1000
11/11 [==============================] - 1s 59ms/step - loss: 6.4047 - mean_absolute_error: 6.4047 - val_loss: 6.2248 - val_mean_absolute_error: 6.2248
Epoch 8/1000
11/11 [==============================] - 0s 21ms/step - loss: 5.8063 - mean_absolute_error: 5.8063 - val_loss: 5.7778 - val_mean_absolute_error: 5.7778
Epoch 9/1000
11/11 [==============================] - 0s 35ms/step - loss: 5.0098 - mean_absolute_error: 5.0098 - val_loss: 4.8652 - val_mean_absolute_error: 4.8652
Epoch 10/1000
11/11 [==============================] - 0s 21ms/step - loss: 4.4243 - mean_absolute_error: 4.4243 - val_loss: 4.2405 - val_mean_absolute_error: 4.2405
Epoch 11/1000
11/11 [==============================] - 0s 16ms/step - loss: 4.0487 - mean_absolute_error: 4.0487 - val_loss: 4.3040 - val_mean_absolute_error: 4.3040
Epoch 12/1000
11/11 [==============================] - 0s 21ms/step - loss: 3.6988 - mean_absolute_error: 3.6988 - val_loss: 4.0459 - val_mean_absolute_error: 4.0459
Epoch 13/1000
11/11 [==============================] - 0s 20ms/step - loss: 3.4370 - mean_absolute_error: 3.4370 - val_loss: 3.6835 - val_mean_absolute_error: 3.6835
Epoch 14/1000
11/11 [==============================] - 0s 19ms/step - loss: 3.2390 - mean_absolute_error: 3.2390 - val_loss: 3.8077 - val_mean_absolute_error: 3.8077
Epoch 15/1000
11/11 [==============================] - 0s 21ms/step - loss: 3.0686 - mean_absolute_error: 3.0686 - val_loss: 3.2780 - val_mean_absolute_error: 3.2780
Epoch 16/1000
11/11 [==============================] - 0s 20ms/step - loss: 2.9495 - mean_absolute_error: 2.9495 - val_loss: 3.1578 - val_mean_absolute_error: 3.1578
Epoch 17/1000
11/11 [==============================] - 0s 28ms/step - loss: 2.8409 - mean_absolute_error: 2.8409 - val_loss: 3.1062 - val_mean_absolute_error: 3.1062
Epoch 18/1000
11/11 [==============================] - 0s 26ms/step - loss: 2.6327 - mean_absolute_error: 2.6327 - val_loss: 2.8990 - val_mean_absolute_error: 2.8990
Epoch 19/1000
11/11 [==============================] - 0s 19ms/step - loss: 2.5422 - mean_absolute_error: 2.5422 - val_loss: 2.9396 - val_mean_absolute_error: 2.9396
Epoch 20/1000
11/11 [==============================] - 0s 37ms/step - loss: 2.5364 - mean_absolute_error: 2.5364 - val_loss: 2.8698 - val_mean_absolute_error: 2.8698
Epoch 21/1000
11/11 [==============================] - 0s 17ms/step - loss: 2.4017 - mean_absolute_error: 2.4017 - val_loss: 3.2475 - val_mean_absolute_error: 3.2475
Epoch 22/1000
11/11 [==============================] - 0s 22ms/step - loss: 2.4755 - mean_absolute_error: 2.4755 - val_loss: 3.3615 - val_mean_absolute_error: 3.3615
Epoch 23/1000
11/11 [==============================] - 0s 28ms/step - loss: 2.4696 - mean_absolute_error: 2.4696 - val_loss: 2.5294 - val_mean_absolute_error: 2.5294
Epoch 24/1000
11/11 [==============================] - 1s 46ms/step - loss: 2.2422 - mean_absolute_error: 2.2422 - val_loss: 2.5491 - val_mean_absolute_error: 2.5491

Epoch 25/1000
11/11 [==============================] - 0s 36ms/step - loss: 2.1795 - mean_absolute_error: 2.1795 - val_loss: 2.5206 - val_mean_absolute_error: 2.5206
Epoch 26/1000
11/11 [==============================] - 0s 25ms/step - loss: 2.4864 - mean_absolute_error: 2.4864 - val_loss: 3.2070 - val_mean_absolute_error: 3.2070
Epoch 27/1000
11/11 [==============================] - 0s 20ms/step - loss: 2.2031 - mean_absolute_error: 2.2031 - val_loss: 2.5640 - val_mean_absolute_error: 2.5640
Epoch 28/1000
11/11 [==============================] - 0s 23ms/step - loss: 2.1763 - mean_absolute_error: 2.1763 - val_loss: 2.5709 - val_mean_absolute_error: 2.5709
Epoch 29/1000
11/11 [==============================] - 0s 31ms/step - loss: 2.0992 - mean_absolute_error: 2.0992 - val_loss: 2.6448 - val_mean_absolute_error: 2.6448
Epoch 30/1000
11/11 [==============================] - 0s 27ms/step - loss: 2.0485 - mean_absolute_error: 2.0485 - val_loss: 2.3776 - val_mean_absolute_error: 2.3776
Epoch 31/1000
11/11 [==============================] - 0s 39ms/step - loss: 2.1146 - mean_absolute_error: 2.1146 - val_loss: 2.3479 - val_mean_absolute_error: 2.3479
Epoch 32/1000
11/11 [==============================] - 0s 42ms/step - loss: 2.0821 - mean_absolute_error: 2.0821 - val_loss: 2.9389 - val_mean_absolute_error: 2.9389
Epoch 33/1000
11/11 [==============================] - 0s 19ms/step - loss: 2.0815 - mean_absolute_error: 2.0815 - val_loss: 2.5083 - val_mean_absolute_error: 2.5083
Epoch 34/1000
11/11 [==============================] - 0s 15ms/step - loss: 1.9821 - mean_absolute_error: 1.9821 - val_loss: 2.4753 - val_mean_absolute_error: 2.4753
Epoch 35/1000
11/11 [==============================] - 0s 23ms/step - loss: 1.9556 - mean_absolute_error: 1.9556 - val_loss: 2.3412 - val_mean_absolute_error: 2.3412
Epoch 36/1000
11/11 [==============================] - 0s 15ms/step - loss: 1.9277 - mean_absolute_error: 1.9277 - val_loss: 2.4361 - val_mean_absolute_error: 2.4361
Epoch 37/1000
11/11 [==============================] - 0s 19ms/step - loss: 1.9201 - mean_absolute_error: 1.9201 - val_loss: 2.2425 - val_mean_absolute_error: 2.2425
Epoch 38/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.9505 - mean_absolute_error: 1.9505 - val_loss: 2.3379 - val_mean_absolute_error: 2.3379
Epoch 39/1000
11/11 [==============================] - 0s 18ms/step - loss: 1.9168 - mean_absolute_error: 1.9168 - val_loss: 2.3055 - val_mean_absolute_error: 2.3055
Epoch 40/1000
11/11 [==============================] - 0s 18ms/step - loss: 2.0242 - mean_absolute_error: 2.0242 - val_loss: 3.3121 - val_mean_absolute_error: 3.3121
Epoch 41/1000
11/11 [==============================] - 0s 15ms/step - loss: 2.0839 - mean_absolute_error: 2.0839 - val_loss: 2.2479 - val_mean_absolute_error: 2.2479
Epoch 42/1000
11/11 [==============================] - 0s 20ms/step - loss: 1.8887 - mean_absolute_error: 1.8887 - val_loss: 2.2389 - val_mean_absolute_error: 2.2389
Epoch 43/1000
11/11 [==============================] - 0s 23ms/step - loss: 1.8974 - mean_absolute_error: 1.8974 - val_loss: 2.2197 - val_mean_absolute_error: 2.2197
Epoch 44/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.8344 - mean_absolute_error: 1.8344 - val_loss: 2.3510 - val_mean_absolute_error: 2.3510
Epoch 45/1000
11/11 [==============================] - 0s 19ms/step - loss: 1.7816 - mean_absolute_error: 1.7816 - val_loss: 2.5930 - val_mean_absolute_error: 2.5930
Epoch 46/1000
11/11 [==============================] - 0s 19ms/step - loss: 1.7631 - mean_absolute_error: 1.7631 - val_loss: 2.2607 - val_mean_absolute_error: 2.2607
Epoch 47/1000
11/11 [==============================] - 0s 20ms/step - loss: 1.7365 - mean_absolute_error: 1.7365 - val_loss: 2.1645 - val_mean_absolute_error: 2.1645
Epoch 48/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.9507 - mean_absolute_error: 1.9507 - val_loss: 2.4672 - val_mean_absolute_error: 2.4672
Epoch 49/1000
11/11 [==============================] - 0s 15ms/step - loss: 2.0716 - mean_absolute_error: 2.0716 - val_loss: 2.2002 - val_mean_absolute_error: 2.2002
Epoch 50/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.8045 - mean_absolute_error: 1.8045 - val_loss: 2.2339 - val_mean_absolute_error: 2.2339
Epoch 51/1000
11/11 [==============================] - 0s 15ms/step - loss: 1.7675 - mean_absolute_error: 1.7675 - val_loss: 2.4820 - val_mean_absolute_error: 2.4820
Epoch 52/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.7394 - mean_absolute_error: 1.7394 - val_loss: 2.2951 - val_mean_absolute_error: 2.2951
Epoch 53/1000
11/11 [==============================] - 0s 15ms/step - loss: 1.7060 - mean_absolute_error: 1.7060 - val_loss: 2.3268 - val_mean_absolute_error: 2.3268
Epoch 54/1000
11/11 [==============================] - 0s 15ms/step - loss: 1.6592 - mean_absolute_error: 1.6592 - val_loss: 2.2217 - val_mean_absolute_error: 2.2217
Epoch 55/1000
11/11 [==============================] - 0s 22ms/step - loss: 1.6167 - mean_absolute_error: 1.6167 - val_loss: 2.1441 - val_mean_absolute_error: 2.1441
Epoch 56/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.6773 - mean_absolute_error: 1.6773 - val_loss: 2.3019 - val_mean_absolute_error: 2.3019
Epoch 57/1000
11/11 [==============================] - 0s 19ms/step - loss: 1.6926 - mean_absolute_error: 1.6926 - val_loss: 2.5418 - val_mean_absolute_error: 2.5418
Epoch 58/1000
11/11 [==============================] - 0s 19ms/step - loss: 1.6825 - mean_absolute_error: 1.6825 - val_loss: 2.1792 - val_mean_absolute_error: 2.1792
Epoch 59/1000
11/11 [==============================] - 0s 20ms/step - loss: 1.7530 - mean_absolute_error: 1.7530 - val_loss: 2.1111 - val_mean_absolute_error: 2.1111
Epoch 60/1000
11/11 [==============================] - 0s 20ms/step - loss: 1.7007 - mean_absolute_error: 1.7007 - val_loss: 2.1457 - val_mean_absolute_error: 2.1457
Epoch 61/1000
11/11 [==============================] - 0s 24ms/step - loss: 1.5887 - mean_absolute_error: 1.5887 - val_loss: 2.1071 - val_mean_absolute_error: 2.1071
Epoch 62/1000
11/11 [==============================] - 0s 20ms/step - loss: 1.5893 - mean_absolute_error: 1.5893 - val_loss: 2.2016 - val_mean_absolute_error: 2.2016
Epoch 63/1000
11/11 [==============================] - 0s 20ms/step - loss: 1.6127 - mean_absolute_error: 1.6127 - val_loss: 2.2232 - val_mean_absolute_error: 2.2232
Epoch 64/1000
11/11 [==============================] - 0s 20ms/step - loss: 1.5082 - mean_absolute_error: 1.5082 - val_loss: 2.0950 - val_mean_absolute_error: 2.0950
Epoch 65/1000
11/11 [==============================] - 0s 24ms/step - loss: 1.5791 - mean_absolute_error: 1.5791 - val_loss: 2.0930 - val_mean_absolute_error: 2.0930
Epoch 66/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.5283 - mean_absolute_error: 1.5283 - val_loss: 2.1857 - val_mean_absolute_error: 2.1857
Epoch 67/1000
11/11 [==============================] - 0s 20ms/step - loss: 1.4618 - mean_absolute_error: 1.4618 - val_loss: 2.1501 - val_mean_absolute_error: 2.1501
Epoch 68/1000
11/11 [==============================] - 0s 27ms/step - loss: 1.4561 - mean_absolute_error: 1.4561 - val_loss: 2.0844 - val_mean_absolute_error: 2.0844
Epoch 69/1000
11/11 [==============================] - 0s 27ms/step - loss: 1.5081 - mean_absolute_error: 1.5081 - val_loss: 2.0607 - val_mean_absolute_error: 2.0607
Epoch 70/1000
11/11 [==============================] - 0s 20ms/step - loss: 1.5245 - mean_absolute_error: 1.5245 - val_loss: 1.9935 - val_mean_absolute_error: 1.9935
Epoch 71/1000
11/11 [==============================] - 0s 15ms/step - loss: 1.5597 - mean_absolute_error: 1.5597 - val_loss: 2.0113 - val_mean_absolute_error: 2.0113
Epoch 72/1000
11/11 [==============================] - 0s 19ms/step - loss: 1.5751 - mean_absolute_error: 1.5751 - val_loss: 2.1530 - val_mean_absolute_error: 2.1530
Epoch 73/1000
11/11 [==============================] - 0s 15ms/step - loss: 1.4368 - mean_absolute_error: 1.4368 - val_loss: 2.0301 - val_mean_absolute_error: 2.0301
Epoch 74/1000

11/11 [==============================] - 0s 16ms/step - loss: 1.4202 - mean_absolute_error: 1.4202 - val_loss: 2.0322 - val_mean_absolute_error: 2.0322
Epoch 75/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.3599 - mean_absolute_error: 1.3599 - val_loss: 2.1701 - val_mean_absolute_error: 2.1701
Epoch 76/1000
11/11 [==============================] - 0s 15ms/step - loss: 1.3544 - mean_absolute_error: 1.3544 - val_loss: 2.2785 - val_mean_absolute_error: 2.2785
Epoch 77/1000
11/11 [==============================] - 0s 17ms/step - loss: 1.4127 - mean_absolute_error: 1.4127 - val_loss: 2.0942 - val_mean_absolute_error: 2.0942
Epoch 78/1000
11/11 [==============================] - 0s 21ms/step - loss: 1.3838 - mean_absolute_error: 1.3838 - val_loss: 1.9925 - val_mean_absolute_error: 1.9925
Epoch 79/1000
11/11 [==============================] - 0s 15ms/step - loss: 1.3713 - mean_absolute_error: 1.3713 - val_loss: 2.1663 - val_mean_absolute_error: 2.1663
Epoch 80/1000
11/11 [==============================] - 0s 19ms/step - loss: 1.3401 - mean_absolute_error: 1.3401 - val_loss: 2.0654 - val_mean_absolute_error: 2.0654
Epoch 81/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.2823 - mean_absolute_error: 1.2823 - val_loss: 2.0368 - val_mean_absolute_error: 2.0368
Epoch 82/1000
11/11 [==============================] - 0s 20ms/step - loss: 1.3241 - mean_absolute_error: 1.3241 - val_loss: 1.9563 - val_mean_absolute_error: 1.9563
Epoch 83/1000
11/11 [==============================] - 0s 23ms/step - loss: 1.2795 - mean_absolute_error: 1.2795 - val_loss: 1.9077 - val_mean_absolute_error: 1.9077
Epoch 84/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.3523 - mean_absolute_error: 1.3523 - val_loss: 2.1882 - val_mean_absolute_error: 2.1882
Epoch 85/1000
11/11 [==============================] - 0s 15ms/step - loss: 1.3016 - mean_absolute_error: 1.3016 - val_loss: 2.2566 - val_mean_absolute_error: 2.2566
Epoch 86/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.3094 - mean_absolute_error: 1.3094 - val_loss: 1.9403 - val_mean_absolute_error: 1.9403
Epoch 87/1000
11/11 [==============================] - 0s 15ms/step - loss: 1.2479 - mean_absolute_error: 1.2479 - val_loss: 2.0068 - val_mean_absolute_error: 2.0068
Epoch 88/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.3445 - mean_absolute_error: 1.3445 - val_loss: 1.9781 - val_mean_absolute_error: 1.9781
Epoch 89/1000
11/11 [==============================] - 0s 15ms/step - loss: 1.3683 - mean_absolute_error: 1.3683 - val_loss: 2.2910 - val_mean_absolute_error: 2.2910
Epoch 90/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.3103 - mean_absolute_error: 1.3103 - val_loss: 1.9761 - val_mean_absolute_error: 1.9761
Epoch 91/1000
11/11 [==============================] - 0s 19ms/step - loss: 1.1631 - mean_absolute_error: 1.1631 - val_loss: 1.8555 - val_mean_absolute_error: 1.8555
Epoch 92/1000
11/11 [==============================] - 0s 15ms/step - loss: 1.3456 - mean_absolute_error: 1.3456 - val_loss: 1.9073 - val_mean_absolute_error: 1.9073
Epoch 93/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.2121 - mean_absolute_error: 1.2121 - val_loss: 1.9889 - val_mean_absolute_error: 1.9889
Epoch 94/1000
11/11 [==============================] - 0s 19ms/step - loss: 1.1748 - mean_absolute_error: 1.1748 - val_loss: 2.0526 - val_mean_absolute_error: 2.0526
Epoch 95/1000
11/11 [==============================] - 0s 20ms/step - loss: 1.1684 - mean_absolute_error: 1.1684 - val_loss: 1.9679 - val_mean_absolute_error: 1.9679
Epoch 96/1000
11/11 [==============================] - 0s 18ms/step - loss: 1.2868 - mean_absolute_error: 1.2868 - val_loss: 1.9452 - val_mean_absolute_error: 1.9452
Epoch 97/1000
11/11 [==============================] - 0s 27ms/step - loss: 1.2759 - mean_absolute_error: 1.2759 - val_loss: 1.8582 - val_mean_absolute_error: 1.8582
Epoch 98/1000
11/11 [==============================] - 0s 26ms/step - loss: 1.2010 - mean_absolute_error: 1.2010 - val_loss: 1.9939 - val_mean_absolute_error: 1.9939
Epoch 99/1000
11/11 [==============================] - 0s 30ms/step - loss: 1.1306 - mean_absolute_error: 1.1306 - val_loss: 1.8411 - val_mean_absolute_error: 1.8411
Epoch 100/1000
11/11 [==============================] - 1s 54ms/step - loss: 1.0870 - mean_absolute_error: 1.0870 - val_loss: 1.7883 - val_mean_absolute_error: 1.7883
Epoch 101/1000
11/11 [==============================] - 0s 25ms/step - loss: 1.1545 - mean_absolute_error: 1.1545 - val_loss: 1.7874 - val_mean_absolute_error: 1.7874
Epoch 102/1000
11/11 [==============================] - 0s 29ms/step - loss: 1.1081 - mean_absolute_error: 1.1081 - val_loss: 1.8847 - val_mean_absolute_error: 1.8847
Epoch 103/1000
11/11 [==============================] - 0s 28ms/step - loss: 1.0456 - mean_absolute_error: 1.0456 - val_loss: 1.9434 - val_mean_absolute_error: 1.9434
Epoch 104/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.0528 - mean_absolute_error: 1.0528 - val_loss: 1.8969 - val_mean_absolute_error: 1.8969
Epoch 105/1000
11/11 [==============================] - 0s 20ms/step - loss: 1.0733 - mean_absolute_error: 1.0733 - val_loss: 2.0293 - val_mean_absolute_error: 2.0293
Epoch 106/1000
11/11 [==============================] - 0s 22ms/step - loss: 1.0381 - mean_absolute_error: 1.0381 - val_loss: 1.8997 - val_mean_absolute_error: 1.8997
Epoch 107/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.9959 - mean_absolute_error: 0.9959 - val_loss: 1.9222 - val_mean_absolute_error: 1.9222
Epoch 108/1000
11/11 [==============================] - 0s 31ms/step - loss: 1.0332 - mean_absolute_error: 1.0332 - val_loss: 1.8027 - val_mean_absolute_error: 1.8027
Epoch 109/1000
11/11 [==============================] - 0s 15ms/step - loss: 1.1079 - mean_absolute_error: 1.1079 - val_loss: 1.8020 - val_mean_absolute_error: 1.8020
Epoch 110/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.0214 - mean_absolute_error: 1.0214 - val_loss: 2.0553 - val_mean_absolute_error: 2.0553
Epoch 111/1000
11/11 [==============================] - 0s 15ms/step - loss: 1.0157 - mean_absolute_error: 1.0157 - val_loss: 1.8292 - val_mean_absolute_error: 1.8292
Epoch 112/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.9722 - mean_absolute_error: 0.9722 - val_loss: 1.8829 - val_mean_absolute_error: 1.8829
Epoch 113/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.9589 - mean_absolute_error: 0.9589 - val_loss: 1.8447 - val_mean_absolute_error: 1.8447
Epoch 114/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.9517 - mean_absolute_error: 0.9517 - val_loss: 1.9040 - val_mean_absolute_error: 1.9040
Epoch 115/1000
11/11 [==============================] - 0s 15ms/step - loss: 1.0445 - mean_absolute_error: 1.0445 - val_loss: 1.8225 - val_mean_absolute_error: 1.8225
Epoch 116/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.0007 - mean_absolute_error: 1.0007 - val_loss: 1.9097 - val_mean_absolute_error: 1.9097
Epoch 117/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.9740 - mean_absolute_error: 0.9740 - val_loss: 1.8398 - val_mean_absolute_error: 1.8398
Epoch 118/1000
11/11 [==============================] - 0s 20ms/step - loss: 1.0291 - mean_absolute_error: 1.0291 - val_loss: 1.7621 - val_mean_absolute_error: 1.7621
Epoch 119/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.0519 - mean_absolute_error: 1.0519 - val_loss: 1.8391 - val_mean_absolute_error: 1.8391
Epoch 120/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.8891 - mean_absolute_error: 0.8891 - val_loss: 1.8412 - val_mean_absolute_error: 1.8412
Epoch 121/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.9425 - mean_absolute_error: 0.9425 - val_loss: 2.2264 - val_mean_absolute_error: 2.2264
Epoch 122/1000
11/11 [==============================] - 0s 15ms/step - loss: 1.0315 - mean_absolute_error: 1.0315 - val_loss: 1.8691 - val_mean_absolute_error: 1.8691
Epoch 123/1000

11/11 [==============================] - 0s 16ms/step - loss: 0.9056 - mean_absolute_error: 0.9056 - val_loss: 1.7916 - val_mean_absolute_error: 1.7916
Epoch 124/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.9079 - mean_absolute_error: 0.9079 - val_loss: 1.7905 - val_mean_absolute_error: 1.7905
Epoch 125/1000
11/11 [==============================] - 0s 23ms/step - loss: 1.1119 - mean_absolute_error: 1.1119 - val_loss: 1.7103 - val_mean_absolute_error: 1.7103
Epoch 126/1000
11/11 [==============================] - 0s 15ms/step - loss: 1.0347 - mean_absolute_error: 1.0347 - val_loss: 2.0365 - val_mean_absolute_error: 2.0365
Epoch 127/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.9285 - mean_absolute_error: 0.9285 - val_loss: 1.7974 - val_mean_absolute_error: 1.7974
Epoch 128/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.9175 - mean_absolute_error: 0.9175 - val_loss: 2.0120 - val_mean_absolute_error: 2.0120
Epoch 129/1000
11/11 [==============================] - 0s 15ms/step - loss: 1.0044 - mean_absolute_error: 1.0044 - val_loss: 2.0710 - val_mean_absolute_error: 2.0710
Epoch 130/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.9380 - mean_absolute_error: 0.9380 - val_loss: 2.0967 - val_mean_absolute_error: 2.0967
Epoch 131/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.9137 - mean_absolute_error: 0.9137 - val_loss: 1.9484 - val_mean_absolute_error: 1.9484
Epoch 132/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.9554 - mean_absolute_error: 0.9554 - val_loss: 1.8528 - val_mean_absolute_error: 1.8528
Epoch 133/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.8579 - mean_absolute_error: 0.8579 - val_loss: 1.8375 - val_mean_absolute_error: 1.8375
Epoch 134/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.9012 - mean_absolute_error: 0.9012 - val_loss: 1.7715 - val_mean_absolute_error: 1.7715
Epoch 135/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.9006 - mean_absolute_error: 0.9006 - val_loss: 1.7279 - val_mean_absolute_error: 1.7279
Epoch 136/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.9539 - mean_absolute_error: 0.9539 - val_loss: 1.8012 - val_mean_absolute_error: 1.8012
Epoch 137/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.8865 - mean_absolute_error: 0.8865 - val_loss: 2.0057 - val_mean_absolute_error: 2.0057
Epoch 138/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.9390 - mean_absolute_error: 0.9390 - val_loss: 1.8504 - val_mean_absolute_error: 1.8504
Epoch 139/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.8503 - mean_absolute_error: 0.8503 - val_loss: 1.7841 - val_mean_absolute_error: 1.7841
Epoch 140/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.8692 - mean_absolute_error: 0.8692 - val_loss: 2.2604 - val_mean_absolute_error: 2.2604
Epoch 141/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.9510 - mean_absolute_error: 0.9510 - val_loss: 1.8806 - val_mean_absolute_error: 1.8806
Epoch 142/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.8458 - mean_absolute_error: 0.8458 - val_loss: 1.7833 - val_mean_absolute_error: 1.7833
Epoch 143/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.7965 - mean_absolute_error: 0.7965 - val_loss: 2.0503 - val_mean_absolute_error: 2.0503
Epoch 144/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.9391 - mean_absolute_error: 0.9391 - val_loss: 1.6955 - val_mean_absolute_error: 1.6955
Epoch 145/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.9257 - mean_absolute_error: 0.9257 - val_loss: 1.8116 - val_mean_absolute_error: 1.8116
Epoch 146/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.8037 - mean_absolute_error: 0.8037 - val_loss: 2.0451 - val_mean_absolute_error: 2.0451
Epoch 147/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.8505 - mean_absolute_error: 0.8505 - val_loss: 1.9194 - val_mean_absolute_error: 1.9194
Epoch 148/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.8012 - mean_absolute_error: 0.8012 - val_loss: 1.7860 - val_mean_absolute_error: 1.7860
Epoch 149/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.7574 - mean_absolute_error: 0.7574 - val_loss: 1.8582 - val_mean_absolute_error: 1.8582
Epoch 150/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.7633 - mean_absolute_error: 0.7633 - val_loss: 1.9187 - val_mean_absolute_error: 1.9187
Epoch 151/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.7784 - mean_absolute_error: 0.7784 - val_loss: 1.8491 - val_mean_absolute_error: 1.8491
Epoch 152/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.7593 - mean_absolute_error: 0.7593 - val_loss: 1.9536 - val_mean_absolute_error: 1.9536
Epoch 153/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.7620 - mean_absolute_error: 0.7620 - val_loss: 1.7350 - val_mean_absolute_error: 1.7350
Epoch 154/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.7930 - mean_absolute_error: 0.7930 - val_loss: 1.8641 - val_mean_absolute_error: 1.8641
Epoch 155/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.7661 - mean_absolute_error: 0.7661 - val_loss: 1.9280 - val_mean_absolute_error: 1.9280
Epoch 156/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.7647 - mean_absolute_error: 0.7647 - val_loss: 2.0443 - val_mean_absolute_error: 2.0443
Epoch 157/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.8006 - mean_absolute_error: 0.8006 - val_loss: 2.0897 - val_mean_absolute_error: 2.0897
Epoch 158/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.9248 - mean_absolute_error: 0.9248 - val_loss: 1.8879 - val_mean_absolute_error: 1.8879
Epoch 159/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.8233 - mean_absolute_error: 0.8233 - val_loss: 1.7519 - val_mean_absolute_error: 1.7519
Epoch 160/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.7749 - mean_absolute_error: 0.7749 - val_loss: 1.9464 - val_mean_absolute_error: 1.9464
Epoch 161/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.7880 - mean_absolute_error: 0.7880 - val_loss: 2.1259 - val_mean_absolute_error: 2.1259
Epoch 162/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.9118 - mean_absolute_error: 0.9118 - val_loss: 1.9199 - val_mean_absolute_error: 1.9199
Epoch 163/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.7227 - mean_absolute_error: 0.7227 - val_loss: 1.8426 - val_mean_absolute_error: 1.8426
Epoch 164/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.7228 - mean_absolute_error: 0.7228 - val_loss: 1.9576 - val_mean_absolute_error: 1.9576
Epoch 165/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.6851 - mean_absolute_error: 0.6851 - val_loss: 1.8713 - val_mean_absolute_error: 1.8713
Epoch 166/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.7848 - mean_absolute_error: 0.7848 - val_loss: 1.7975 - val_mean_absolute_error: 1.7975
Epoch 167/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.7075 - mean_absolute_error: 0.7075 - val_loss: 1.8011 - val_mean_absolute_error: 1.8011
Epoch 168/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.6693 - mean_absolute_error: 0.6693 - val_loss: 1.7972 - val_mean_absolute_error: 1.7972
Epoch 169/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.7454 - mean_absolute_error: 0.7454 - val_loss: 1.9037 - val_mean_absolute_error: 1.9037
Epoch 170/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.7026 - mean_absolute_error: 0.7026 - val_loss: 1.7656 - val_mean_absolute_error: 1.7656
Epoch 171/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.8138 - mean_absolute_error: 0.8138 - val_loss: 1.8967 - val_mean_absolute_error: 1.8967
Epoch 172/1000

11/11 [==============================] - 0s 15ms/step - loss: 0.7489 - mean_absolute_error: 0.7489 - val_loss: 1.8612 - val_mean_absolute_error: 1.8612
Epoch 173/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.6618 - mean_absolute_error: 0.6618 - val_loss: 1.7252 - val_mean_absolute_error: 1.7252
Epoch 174/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.7253 - mean_absolute_error: 0.7253 - val_loss: 1.7974 - val_mean_absolute_error: 1.7974
Epoch 175/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.7487 - mean_absolute_error: 0.7487 - val_loss: 1.8161 - val_mean_absolute_error: 1.8161
Epoch 176/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.8011 - mean_absolute_error: 0.8011 - val_loss: 1.9043 - val_mean_absolute_error: 1.9043
Epoch 177/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.7032 - mean_absolute_error: 0.7032 - val_loss: 1.8177 - val_mean_absolute_error: 1.8177
Epoch 178/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.7761 - mean_absolute_error: 0.7761 - val_loss: 1.9815 - val_mean_absolute_error: 1.9815
Epoch 179/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.7728 - mean_absolute_error: 0.7728 - val_loss: 1.7696 - val_mean_absolute_error: 1.7696
Epoch 180/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.7603 - mean_absolute_error: 0.7603 - val_loss: 1.7165 - val_mean_absolute_error: 1.7165
Epoch 181/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.8102 - mean_absolute_error: 0.8102 - val_loss: 1.8466 - val_mean_absolute_error: 1.8466
Epoch 182/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.6525 - mean_absolute_error: 0.6525 - val_loss: 1.9305 - val_mean_absolute_error: 1.9305
Epoch 183/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.6577 - mean_absolute_error: 0.6577 - val_loss: 1.7537 - val_mean_absolute_error: 1.7537
Epoch 184/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.6610 - mean_absolute_error: 0.6610 - val_loss: 1.7440 - val_mean_absolute_error: 1.7440
Epoch 185/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.6482 - mean_absolute_error: 0.6482 - val_loss: 1.9829 - val_mean_absolute_error: 1.9829
Epoch 186/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.7109 - mean_absolute_error: 0.7109 - val_loss: 1.7693 - val_mean_absolute_error: 1.7693
Epoch 187/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.6366 - mean_absolute_error: 0.6366 - val_loss: 1.9231 - val_mean_absolute_error: 1.9231
Epoch 188/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.7052 - mean_absolute_error: 0.7052 - val_loss: 2.0852 - val_mean_absolute_error: 2.0852
Epoch 189/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.7466 - mean_absolute_error: 0.7466 - val_loss: 1.8342 - val_mean_absolute_error: 1.8342
Epoch 190/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.7622 - mean_absolute_error: 0.7622 - val_loss: 1.7412 - val_mean_absolute_error: 1.7412
Epoch 191/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.7418 - mean_absolute_error: 0.7418 - val_loss: 1.8464 - val_mean_absolute_error: 1.8464
Epoch 192/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.6785 - mean_absolute_error: 0.6785 - val_loss: 1.7979 - val_mean_absolute_error: 1.7979
Epoch 193/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.6201 - mean_absolute_error: 0.6201 - val_loss: 1.7367 - val_mean_absolute_error: 1.7367
Epoch 194/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.6788 - mean_absolute_error: 0.6788 - val_loss: 2.0517 - val_mean_absolute_error: 2.0517
Epoch 195/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.8169 - mean_absolute_error: 0.8169 - val_loss: 1.8383 - val_mean_absolute_error: 1.8383
Epoch 196/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.6878 - mean_absolute_error: 0.6878 - val_loss: 1.7343 - val_mean_absolute_error: 1.7343
Epoch 197/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.7418 - mean_absolute_error: 0.7418 - val_loss: 2.1846 - val_mean_absolute_error: 2.1846
Epoch 198/1000
11/11 [==============================] - 0s 28ms/step - loss: 0.8887 - mean_absolute_error: 0.8887 - val_loss: 1.8705 - val_mean_absolute_error: 1.8705
Epoch 199/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.6592 - mean_absolute_error: 0.6592 - val_loss: 1.7775 - val_mean_absolute_error: 1.7775
Epoch 200/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.6403 - mean_absolute_error: 0.6403 - val_loss: 1.8311 - val_mean_absolute_error: 1.8311
Epoch 201/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.6808 - mean_absolute_error: 0.6808 - val_loss: 1.9668 - val_mean_absolute_error: 1.9668
Epoch 202/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.7049 - mean_absolute_error: 0.7049 - val_loss: 1.7927 - val_mean_absolute_error: 1.7927
Epoch 203/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.6677 - mean_absolute_error: 0.6677 - val_loss: 1.9703 - val_mean_absolute_error: 1.9703
Epoch 204/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.6963 - mean_absolute_error: 0.6963 - val_loss: 1.7790 - val_mean_absolute_error: 1.7790
Epoch 205/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.6036 - mean_absolute_error: 0.6036 - val_loss: 1.8312 - val_mean_absolute_error: 1.8312
Epoch 206/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.5588 - mean_absolute_error: 0.5588 - val_loss: 1.7413 - val_mean_absolute_error: 1.7413
Epoch 207/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5572 - mean_absolute_error: 0.5572 - val_loss: 1.8308 - val_mean_absolute_error: 1.8308
Epoch 208/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.6123 - mean_absolute_error: 0.6123 - val_loss: 1.7445 - val_mean_absolute_error: 1.7445
Epoch 209/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.6056 - mean_absolute_error: 0.6056 - val_loss: 1.8067 - val_mean_absolute_error: 1.8067
Epoch 210/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5525 - mean_absolute_error: 0.5525 - val_loss: 1.8633 - val_mean_absolute_error: 1.8633
Epoch 211/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.6439 - mean_absolute_error: 0.6439 - val_loss: 1.8087 - val_mean_absolute_error: 1.8087
Epoch 212/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.6986 - mean_absolute_error: 0.6986 - val_loss: 1.7862 - val_mean_absolute_error: 1.7862
Epoch 213/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.5947 - mean_absolute_error: 0.5947 - val_loss: 1.8556 - val_mean_absolute_error: 1.8556
Epoch 214/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.6709 - mean_absolute_error: 0.6709 - val_loss: 1.7145 - val_mean_absolute_error: 1.7145
Epoch 215/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5653 - mean_absolute_error: 0.5653 - val_loss: 1.8384 - val_mean_absolute_error: 1.8384
Epoch 216/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.6448 - mean_absolute_error: 0.6448 - val_loss: 1.7867 - val_mean_absolute_error: 1.7867
Epoch 217/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.6216 - mean_absolute_error: 0.6216 - val_loss: 1.8437 - val_mean_absolute_error: 1.8437
Epoch 218/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5875 - mean_absolute_error: 0.5875 - val_loss: 1.9234 - val_mean_absolute_error: 1.9234
Epoch 219/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.6427 - mean_absolute_error: 0.6427 - val_loss: 1.8867 - val_mean_absolute_error: 1.8867
Epoch 220/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.6258 - mean_absolute_error: 0.6258 - val_loss: 1.7982 - val_mean_absolute_error: 1.7982
Epoch 221/1000

11/11 [==============================] - 0s 17ms/step - loss: 0.5495 - mean_absolute_error: 0.5495 - val_loss: 1.7938 - val_mean_absolute_error: 1.7938
Epoch 222/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.6103 - mean_absolute_error: 0.6103 - val_loss: 2.0037 - val_mean_absolute_error: 2.0037
Epoch 223/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.6656 - mean_absolute_error: 0.6656 - val_loss: 1.7827 - val_mean_absolute_error: 1.7827
Epoch 224/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.8319 - mean_absolute_error: 0.8319 - val_loss: 1.7707 - val_mean_absolute_error: 1.7707
Epoch 225/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5628 - mean_absolute_error: 0.5628 - val_loss: 1.9747 - val_mean_absolute_error: 1.9747
Epoch 226/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.6044 - mean_absolute_error: 0.6044 - val_loss: 1.7838 - val_mean_absolute_error: 1.7838
Epoch 227/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5430 - mean_absolute_error: 0.5430 - val_loss: 1.9037 - val_mean_absolute_error: 1.9037
Epoch 228/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5519 - mean_absolute_error: 0.5519 - val_loss: 1.8186 - val_mean_absolute_error: 1.8186
Epoch 229/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5481 - mean_absolute_error: 0.5481 - val_loss: 1.8299 - val_mean_absolute_error: 1.8299
Epoch 230/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.5191 - mean_absolute_error: 0.5191 - val_loss: 2.0135 - val_mean_absolute_error: 2.0135
Epoch 231/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.7373 - mean_absolute_error: 0.7373 - val_loss: 1.9911 - val_mean_absolute_error: 1.9911
Epoch 232/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.6412 - mean_absolute_error: 0.6412 - val_loss: 1.7982 - val_mean_absolute_error: 1.7982
Epoch 233/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.5719 - mean_absolute_error: 0.5719 - val_loss: 1.7794 - val_mean_absolute_error: 1.7794
Epoch 234/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5310 - mean_absolute_error: 0.5310 - val_loss: 1.7332 - val_mean_absolute_error: 1.7332
Epoch 235/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.5413 - mean_absolute_error: 0.5413 - val_loss: 1.8987 - val_mean_absolute_error: 1.8987
Epoch 236/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.5811 - mean_absolute_error: 0.5811 - val_loss: 1.8432 - val_mean_absolute_error: 1.8432
Epoch 237/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.6149 - mean_absolute_error: 0.6149 - val_loss: 1.8365 - val_mean_absolute_error: 1.8365
Epoch 238/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.5363 - mean_absolute_error: 0.5363 - val_loss: 1.7522 - val_mean_absolute_error: 1.7522
Epoch 239/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5311 - mean_absolute_error: 0.5311 - val_loss: 1.8753 - val_mean_absolute_error: 1.8753
Epoch 240/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.5167 - mean_absolute_error: 0.5167 - val_loss: 1.8065 - val_mean_absolute_error: 1.8065
Epoch 241/1000
11/11 [==============================] - 0s 21ms/step - loss: 0.4938 - mean_absolute_error: 0.4938 - val_loss: 1.8345 - val_mean_absolute_error: 1.8345
Epoch 242/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.5289 - mean_absolute_error: 0.5289 - val_loss: 1.7385 - val_mean_absolute_error: 1.7385
Epoch 243/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.5922 - mean_absolute_error: 0.5922 - val_loss: 1.9002 - val_mean_absolute_error: 1.9002
Epoch 244/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.5822 - mean_absolute_error: 0.5822 - val_loss: 1.7657 - val_mean_absolute_error: 1.7657
Epoch 245/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.6423 - mean_absolute_error: 0.6423 - val_loss: 2.0160 - val_mean_absolute_error: 2.0160
Epoch 246/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.6152 - mean_absolute_error: 0.6152 - val_loss: 1.7956 - val_mean_absolute_error: 1.7956
Epoch 247/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5480 - mean_absolute_error: 0.5480 - val_loss: 1.8473 - val_mean_absolute_error: 1.8473
Epoch 248/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5992 - mean_absolute_error: 0.5992 - val_loss: 1.8574 - val_mean_absolute_error: 1.8574
Epoch 249/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5335 - mean_absolute_error: 0.5335 - val_loss: 1.7316 - val_mean_absolute_error: 1.7316
Epoch 250/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5645 - mean_absolute_error: 0.5645 - val_loss: 1.9945 - val_mean_absolute_error: 1.9945
Epoch 251/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.5901 - mean_absolute_error: 0.5901 - val_loss: 1.7782 - val_mean_absolute_error: 1.7782
Epoch 252/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.5311 - mean_absolute_error: 0.5311 - val_loss: 1.7819 - val_mean_absolute_error: 1.7819
Epoch 253/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4913 - mean_absolute_error: 0.4913 - val_loss: 2.0008 - val_mean_absolute_error: 2.0008
Epoch 254/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5348 - mean_absolute_error: 0.5348 - val_loss: 1.7639 - val_mean_absolute_error: 1.7639
Epoch 255/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5196 - mean_absolute_error: 0.5196 - val_loss: 1.7277 - val_mean_absolute_error: 1.7277
Epoch 256/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5194 - mean_absolute_error: 0.5194 - val_loss: 1.8374 - val_mean_absolute_error: 1.8374
Epoch 257/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5766 - mean_absolute_error: 0.5766 - val_loss: 1.7427 - val_mean_absolute_error: 1.7427
Epoch 258/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.6797 - mean_absolute_error: 0.6797 - val_loss: 1.8290 - val_mean_absolute_error: 1.8290
Epoch 259/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.5482 - mean_absolute_error: 0.5482 - val_loss: 1.7873 - val_mean_absolute_error: 1.7873
Epoch 260/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5410 - mean_absolute_error: 0.5410 - val_loss: 1.9043 - val_mean_absolute_error: 1.9043
Epoch 261/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5461 - mean_absolute_error: 0.5461 - val_loss: 1.8403 - val_mean_absolute_error: 1.8403
Epoch 262/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.6473 - mean_absolute_error: 0.6473 - val_loss: 1.8144 - val_mean_absolute_error: 1.8144
Epoch 263/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.6805 - mean_absolute_error: 0.6805 - val_loss: 1.8082 - val_mean_absolute_error: 1.8082
Epoch 264/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.6145 - mean_absolute_error: 0.6145 - val_loss: 1.8309 - val_mean_absolute_error: 1.8309
Epoch 265/1000
11/11 [==============================] - 0s 21ms/step - loss: 0.4715 - mean_absolute_error: 0.4715 - val_loss: 1.8388 - val_mean_absolute_error: 1.8388
Epoch 266/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.5261 - mean_absolute_error: 0.5261 - val_loss: 1.8283 - val_mean_absolute_error: 1.8283
Epoch 267/1000
11/11 [==============================] - 0s 25ms/step - loss: 0.5197 - mean_absolute_error: 0.5197 - val_loss: 1.7836 - val_mean_absolute_error: 1.7836
Epoch 268/1000
11/11 [==============================] - 0s 26ms/step - loss: 0.5665 - mean_absolute_error: 0.5665 - val_loss: 1.7760 - val_mean_absolute_error: 1.7760
Epoch 269/1000
11/11 [==============================] - 0s 40ms/step - loss: 0.5256 - mean_absolute_error: 0.5256 - val_loss: 1.8134 - val_mean_absolute_error: 1.8134
Epoch 270/1000

11/11 [==============================] - 0s 28ms/step - loss: 0.5228 - mean_absolute_error: 0.5228 - val_loss: 1.8285 - val_mean_absolute_error: 1.8285
Epoch 271/1000
11/11 [==============================] - 0s 21ms/step - loss: 0.4996 - mean_absolute_error: 0.4996 - val_loss: 1.8128 - val_mean_absolute_error: 1.8128
Epoch 272/1000
11/11 [==============================] - 0s 27ms/step - loss: 0.5034 - mean_absolute_error: 0.5034 - val_loss: 1.7562 - val_mean_absolute_error: 1.7562
Epoch 273/1000
11/11 [==============================] - 0s 26ms/step - loss: 0.4805 - mean_absolute_error: 0.4805 - val_loss: 1.9277 - val_mean_absolute_error: 1.9277
Epoch 274/1000
11/11 [==============================] - 0s 27ms/step - loss: 0.5412 - mean_absolute_error: 0.5412 - val_loss: 1.7034 - val_mean_absolute_error: 1.7034
Epoch 275/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.5733 - mean_absolute_error: 0.5733 - val_loss: 1.9632 - val_mean_absolute_error: 1.9632
Epoch 276/1000
11/11 [==============================] - 0s 29ms/step - loss: 0.6255 - mean_absolute_error: 0.6255 - val_loss: 1.7558 - val_mean_absolute_error: 1.7558
Epoch 277/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.6488 - mean_absolute_error: 0.6488 - val_loss: 1.8134 - val_mean_absolute_error: 1.8134
Epoch 278/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.5938 - mean_absolute_error: 0.5938 - val_loss: 1.8946 - val_mean_absolute_error: 1.8946
Epoch 279/1000
11/11 [==============================] - 0s 24ms/step - loss: 0.5839 - mean_absolute_error: 0.5839 - val_loss: 1.7044 - val_mean_absolute_error: 1.7044
Epoch 280/1000
11/11 [==============================] - 0s 34ms/step - loss: 0.4860 - mean_absolute_error: 0.4860 - val_loss: 1.8777 - val_mean_absolute_error: 1.8777
Epoch 281/1000
11/11 [==============================] - 0s 27ms/step - loss: 0.4555 - mean_absolute_error: 0.4555 - val_loss: 1.8227 - val_mean_absolute_error: 1.8227
Epoch 282/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4765 - mean_absolute_error: 0.4765 - val_loss: 1.7783 - val_mean_absolute_error: 1.7783
Epoch 283/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5099 - mean_absolute_error: 0.5099 - val_loss: 1.7390 - val_mean_absolute_error: 1.7390
Epoch 284/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.6068 - mean_absolute_error: 0.6068 - val_loss: 2.0199 - val_mean_absolute_error: 2.0199
Epoch 285/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.6919 - mean_absolute_error: 0.6919 - val_loss: 1.9564 - val_mean_absolute_error: 1.9564
Epoch 286/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.5991 - mean_absolute_error: 0.5991 - val_loss: 1.8186 - val_mean_absolute_error: 1.8186
Epoch 287/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.5576 - mean_absolute_error: 0.5576 - val_loss: 1.7712 - val_mean_absolute_error: 1.7712
Epoch 288/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5324 - mean_absolute_error: 0.5324 - val_loss: 1.8646 - val_mean_absolute_error: 1.8646
Epoch 289/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4969 - mean_absolute_error: 0.4969 - val_loss: 1.8506 - val_mean_absolute_error: 1.8506
Epoch 290/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.5164 - mean_absolute_error: 0.5164 - val_loss: 1.7617 - val_mean_absolute_error: 1.7617
Epoch 291/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4685 - mean_absolute_error: 0.4685 - val_loss: 1.8374 - val_mean_absolute_error: 1.8374
Epoch 292/1000
11/11 [==============================] - 0s 27ms/step - loss: 0.5130 - mean_absolute_error: 0.5130 - val_loss: 1.7966 - val_mean_absolute_error: 1.7966
Epoch 293/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4977 - mean_absolute_error: 0.4977 - val_loss: 1.8225 - val_mean_absolute_error: 1.8225
Epoch 294/1000
11/11 [==============================] - 0s 33ms/step - loss: 0.4514 - mean_absolute_error: 0.4514 - val_loss: 1.8674 - val_mean_absolute_error: 1.8674
Epoch 295/1000
11/11 [==============================] - 0s 32ms/step - loss: 0.4709 - mean_absolute_error: 0.4709 - val_loss: 1.8245 - val_mean_absolute_error: 1.8245
Epoch 296/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4170 - mean_absolute_error: 0.4170 - val_loss: 1.8268 - val_mean_absolute_error: 1.8268
Epoch 297/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4330 - mean_absolute_error: 0.4330 - val_loss: 1.9584 - val_mean_absolute_error: 1.9584
Epoch 298/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.6356 - mean_absolute_error: 0.6356 - val_loss: 1.8309 - val_mean_absolute_error: 1.8309
Epoch 299/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.4977 - mean_absolute_error: 0.4977 - val_loss: 1.9612 - val_mean_absolute_error: 1.9612
Epoch 300/1000
11/11 [==============================] - 0s 30ms/step - loss: 0.6330 - mean_absolute_error: 0.6330 - val_loss: 1.9398 - val_mean_absolute_error: 1.9398
Epoch 301/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.5235 - mean_absolute_error: 0.5235 - val_loss: 1.6972 - val_mean_absolute_error: 1.6972
Epoch 302/1000
11/11 [==============================] - 0s 21ms/step - loss: 0.6015 - mean_absolute_error: 0.6015 - val_loss: 1.9152 - val_mean_absolute_error: 1.9152
Epoch 303/1000
11/11 [==============================] - 0s 32ms/step - loss: 0.5149 - mean_absolute_error: 0.5149 - val_loss: 1.8644 - val_mean_absolute_error: 1.8644
Epoch 304/1000
11/11 [==============================] - 0s 26ms/step - loss: 0.4451 - mean_absolute_error: 0.4451 - val_loss: 1.8457 - val_mean_absolute_error: 1.8457
Epoch 305/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4302 - mean_absolute_error: 0.4302 - val_loss: 1.9793 - val_mean_absolute_error: 1.9793
Epoch 306/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.5490 - mean_absolute_error: 0.5490 - val_loss: 1.8380 - val_mean_absolute_error: 1.8380
Epoch 307/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4707 - mean_absolute_error: 0.4707 - val_loss: 1.8028 - val_mean_absolute_error: 1.8028
Epoch 308/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4644 - mean_absolute_error: 0.4644 - val_loss: 1.7690 - val_mean_absolute_error: 1.7690
Epoch 309/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4449 - mean_absolute_error: 0.4449 - val_loss: 1.9227 - val_mean_absolute_error: 1.9227
Epoch 310/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.5165 - mean_absolute_error: 0.5165 - val_loss: 1.8300 - val_mean_absolute_error: 1.8300
Epoch 311/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.6088 - mean_absolute_error: 0.6088 - val_loss: 1.7407 - val_mean_absolute_error: 1.7407
Epoch 312/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.5891 - mean_absolute_error: 0.5891 - val_loss: 1.8384 - val_mean_absolute_error: 1.8384
Epoch 313/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5406 - mean_absolute_error: 0.5406 - val_loss: 1.8276 - val_mean_absolute_error: 1.8276
Epoch 314/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4119 - mean_absolute_error: 0.4119 - val_loss: 1.8564 - val_mean_absolute_error: 1.8564
Epoch 315/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4561 - mean_absolute_error: 0.4561 - val_loss: 1.8433 - val_mean_absolute_error: 1.8433
Epoch 316/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4974 - mean_absolute_error: 0.4974 - val_loss: 1.8130 - val_mean_absolute_error: 1.8130
Epoch 317/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.5304 - mean_absolute_error: 0.5304 - val_loss: 1.8014 - val_mean_absolute_error: 1.8014
Epoch 318/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4153 - mean_absolute_error: 0.4153 - val_loss: 1.7729 - val_mean_absolute_error: 1.7729
Epoch 319/1000

11/11 [==============================] - 0s 19ms/step - loss: 0.5111 - mean_absolute_error: 0.5111 - val_loss: 1.9309 - val_mean_absolute_error: 1.9309
Epoch 320/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.5119 - mean_absolute_error: 0.5119 - val_loss: 1.7489 - val_mean_absolute_error: 1.7489
Epoch 321/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4470 - mean_absolute_error: 0.4470 - val_loss: 1.9732 - val_mean_absolute_error: 1.9732
Epoch 322/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.6044 - mean_absolute_error: 0.6044 - val_loss: 1.8895 - val_mean_absolute_error: 1.8895
Epoch 323/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5897 - mean_absolute_error: 0.5897 - val_loss: 1.7694 - val_mean_absolute_error: 1.7694
Epoch 324/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.5968 - mean_absolute_error: 0.5968 - val_loss: 1.8288 - val_mean_absolute_error: 1.8288
Epoch 325/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4496 - mean_absolute_error: 0.4496 - val_loss: 1.7528 - val_mean_absolute_error: 1.7528
Epoch 326/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4939 - mean_absolute_error: 0.4939 - val_loss: 1.9055 - val_mean_absolute_error: 1.9055
Epoch 327/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5173 - mean_absolute_error: 0.5173 - val_loss: 1.7744 - val_mean_absolute_error: 1.7744
Epoch 328/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5308 - mean_absolute_error: 0.5308 - val_loss: 1.9725 - val_mean_absolute_error: 1.9725
Epoch 329/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4988 - mean_absolute_error: 0.4988 - val_loss: 1.8453 - val_mean_absolute_error: 1.8453
Epoch 330/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4051 - mean_absolute_error: 0.4051 - val_loss: 1.7780 - val_mean_absolute_error: 1.7780
Epoch 331/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3950 - mean_absolute_error: 0.3950 - val_loss: 1.8666 - val_mean_absolute_error: 1.8666
Epoch 332/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4628 - mean_absolute_error: 0.4628 - val_loss: 1.7896 - val_mean_absolute_error: 1.7896
Epoch 333/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4732 - mean_absolute_error: 0.4732 - val_loss: 1.8756 - val_mean_absolute_error: 1.8756
Epoch 334/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4334 - mean_absolute_error: 0.4334 - val_loss: 1.8568 - val_mean_absolute_error: 1.8568
Epoch 335/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4450 - mean_absolute_error: 0.4450 - val_loss: 1.8235 - val_mean_absolute_error: 1.8235
Epoch 336/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.5759 - mean_absolute_error: 0.5759 - val_loss: 1.8209 - val_mean_absolute_error: 1.8209
Epoch 337/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4411 - mean_absolute_error: 0.4411 - val_loss: 1.8039 - val_mean_absolute_error: 1.8039
Epoch 338/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4179 - mean_absolute_error: 0.4179 - val_loss: 1.8303 - val_mean_absolute_error: 1.8303
Epoch 339/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4367 - mean_absolute_error: 0.4367 - val_loss: 1.7940 - val_mean_absolute_error: 1.7940
Epoch 340/1000
11/11 [==============================] - 0s 24ms/step - loss: 0.4377 - mean_absolute_error: 0.4377 - val_loss: 1.8939 - val_mean_absolute_error: 1.8939
Epoch 341/1000
11/11 [==============================] - 0s 27ms/step - loss: 0.4434 - mean_absolute_error: 0.4434 - val_loss: 1.9006 - val_mean_absolute_error: 1.9006
Epoch 342/1000
11/11 [==============================] - 0s 35ms/step - loss: 0.4400 - mean_absolute_error: 0.4400 - val_loss: 1.8482 - val_mean_absolute_error: 1.8482
Epoch 343/1000
11/11 [==============================] - 0s 40ms/step - loss: 0.3891 - mean_absolute_error: 0.3891 - val_loss: 1.8271 - val_mean_absolute_error: 1.8271
Epoch 344/1000
11/11 [==============================] - 0s 43ms/step - loss: 0.3908 - mean_absolute_error: 0.3908 - val_loss: 1.7981 - val_mean_absolute_error: 1.7981
Epoch 345/1000
11/11 [==============================] - 0s 26ms/step - loss: 0.4216 - mean_absolute_error: 0.4216 - val_loss: 1.8655 - val_mean_absolute_error: 1.8655
Epoch 346/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4133 - mean_absolute_error: 0.4133 - val_loss: 1.8073 - val_mean_absolute_error: 1.8073
Epoch 347/1000
11/11 [==============================] - 0s 26ms/step - loss: 0.4535 - mean_absolute_error: 0.4535 - val_loss: 1.8656 - val_mean_absolute_error: 1.8656
Epoch 348/1000
11/11 [==============================] - 0s 24ms/step - loss: 0.4941 - mean_absolute_error: 0.4941 - val_loss: 1.7828 - val_mean_absolute_error: 1.7828
Epoch 349/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.4818 - mean_absolute_error: 0.4818 - val_loss: 1.7907 - val_mean_absolute_error: 1.7907
Epoch 350/1000
11/11 [==============================] - 1s 52ms/step - loss: 0.4762 - mean_absolute_error: 0.4762 - val_loss: 1.8317 - val_mean_absolute_error: 1.8317
Epoch 351/1000
11/11 [==============================] - 0s 32ms/step - loss: 0.4004 - mean_absolute_error: 0.4004 - val_loss: 1.8745 - val_mean_absolute_error: 1.8745
Epoch 352/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3656 - mean_absolute_error: 0.3656 - val_loss: 1.8593 - val_mean_absolute_error: 1.8593
Epoch 353/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4092 - mean_absolute_error: 0.4092 - val_loss: 1.7853 - val_mean_absolute_error: 1.7853
Epoch 354/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4111 - mean_absolute_error: 0.4111 - val_loss: 1.9363 - val_mean_absolute_error: 1.9363
Epoch 355/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4159 - mean_absolute_error: 0.4159 - val_loss: 1.7918 - val_mean_absolute_error: 1.7918
Epoch 356/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3990 - mean_absolute_error: 0.3990 - val_loss: 1.8280 - val_mean_absolute_error: 1.8280
Epoch 357/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4092 - mean_absolute_error: 0.4092 - val_loss: 1.8427 - val_mean_absolute_error: 1.8427
Epoch 358/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3961 - mean_absolute_error: 0.3961 - val_loss: 1.7912 - val_mean_absolute_error: 1.7912
Epoch 359/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4181 - mean_absolute_error: 0.4181 - val_loss: 1.8508 - val_mean_absolute_error: 1.8508
Epoch 360/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.4370 - mean_absolute_error: 0.4370 - val_loss: 1.8406 - val_mean_absolute_error: 1.8406
Epoch 361/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.4743 - mean_absolute_error: 0.4743 - val_loss: 1.8023 - val_mean_absolute_error: 1.8023
Epoch 362/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5386 - mean_absolute_error: 0.5386 - val_loss: 1.7561 - val_mean_absolute_error: 1.7561
Epoch 363/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4310 - mean_absolute_error: 0.4310 - val_loss: 1.8188 - val_mean_absolute_error: 1.8188
Epoch 364/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3941 - mean_absolute_error: 0.3941 - val_loss: 1.7887 - val_mean_absolute_error: 1.7887
Epoch 365/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4594 - mean_absolute_error: 0.4594 - val_loss: 1.8380 - val_mean_absolute_error: 1.8380
Epoch 366/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3721 - mean_absolute_error: 0.3721 - val_loss: 1.8273 - val_mean_absolute_error: 1.8273
Epoch 367/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.3640 - mean_absolute_error: 0.3640 - val_loss: 1.8488 - val_mean_absolute_error: 1.8488
Epoch 368/1000

11/11 [==============================] - 0s 16ms/step - loss: 0.3684 - mean_absolute_error: 0.3684 - val_loss: 1.9181 - val_mean_absolute_error: 1.9181
Epoch 369/1000
11/11 [==============================] - 0s 26ms/step - loss: 0.3939 - mean_absolute_error: 0.3939 - val_loss: 1.8822 - val_mean_absolute_error: 1.8822
Epoch 370/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4523 - mean_absolute_error: 0.4523 - val_loss: 1.7654 - val_mean_absolute_error: 1.7654
Epoch 371/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4332 - mean_absolute_error: 0.4332 - val_loss: 1.8806 - val_mean_absolute_error: 1.8806
Epoch 372/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4865 - mean_absolute_error: 0.4865 - val_loss: 1.7992 - val_mean_absolute_error: 1.7992
Epoch 373/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4344 - mean_absolute_error: 0.4344 - val_loss: 1.8161 - val_mean_absolute_error: 1.8161
Epoch 374/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4697 - mean_absolute_error: 0.4697 - val_loss: 1.8715 - val_mean_absolute_error: 1.8715
Epoch 375/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4533 - mean_absolute_error: 0.4533 - val_loss: 1.8184 - val_mean_absolute_error: 1.8184
Epoch 376/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4133 - mean_absolute_error: 0.4133 - val_loss: 1.7760 - val_mean_absolute_error: 1.7760
Epoch 377/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4855 - mean_absolute_error: 0.4855 - val_loss: 1.8734 - val_mean_absolute_error: 1.8734
Epoch 378/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3782 - mean_absolute_error: 0.3782 - val_loss: 1.7991 - val_mean_absolute_error: 1.7991
Epoch 379/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.4914 - mean_absolute_error: 0.4914 - val_loss: 1.9849 - val_mean_absolute_error: 1.9849
Epoch 380/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4476 - mean_absolute_error: 0.4476 - val_loss: 1.8103 - val_mean_absolute_error: 1.8103
Epoch 381/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4299 - mean_absolute_error: 0.4299 - val_loss: 1.7908 - val_mean_absolute_error: 1.7908
Epoch 382/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3974 - mean_absolute_error: 0.3974 - val_loss: 1.8151 - val_mean_absolute_error: 1.8151
Epoch 383/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4002 - mean_absolute_error: 0.4002 - val_loss: 1.7609 - val_mean_absolute_error: 1.7609
Epoch 384/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.4163 - mean_absolute_error: 0.4163 - val_loss: 1.7863 - val_mean_absolute_error: 1.7863
Epoch 385/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.5746 - mean_absolute_error: 0.5746 - val_loss: 1.7715 - val_mean_absolute_error: 1.7715
Epoch 386/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.5117 - mean_absolute_error: 0.5117 - val_loss: 1.9254 - val_mean_absolute_error: 1.9254
Epoch 387/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.5374 - mean_absolute_error: 0.5374 - val_loss: 1.8324 - val_mean_absolute_error: 1.8324
Epoch 388/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4535 - mean_absolute_error: 0.4535 - val_loss: 1.8622 - val_mean_absolute_error: 1.8622
Epoch 389/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4276 - mean_absolute_error: 0.4276 - val_loss: 1.8517 - val_mean_absolute_error: 1.8517
Epoch 390/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4470 - mean_absolute_error: 0.4470 - val_loss: 1.8125 - val_mean_absolute_error: 1.8125
Epoch 391/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3882 - mean_absolute_error: 0.3882 - val_loss: 1.7803 - val_mean_absolute_error: 1.7803
Epoch 392/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3642 - mean_absolute_error: 0.3642 - val_loss: 1.7907 - val_mean_absolute_error: 1.7907
Epoch 393/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4009 - mean_absolute_error: 0.4009 - val_loss: 1.8692 - val_mean_absolute_error: 1.8692
Epoch 394/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.5108 - mean_absolute_error: 0.5108 - val_loss: 1.7890 - val_mean_absolute_error: 1.7890
Epoch 395/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4280 - mean_absolute_error: 0.4280 - val_loss: 1.9075 - val_mean_absolute_error: 1.9075
Epoch 396/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4749 - mean_absolute_error: 0.4749 - val_loss: 1.7857 - val_mean_absolute_error: 1.7857
Epoch 397/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5350 - mean_absolute_error: 0.5350 - val_loss: 1.9436 - val_mean_absolute_error: 1.9436
Epoch 398/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5006 - mean_absolute_error: 0.5006 - val_loss: 1.7672 - val_mean_absolute_error: 1.7672
Epoch 399/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4467 - mean_absolute_error: 0.4467 - val_loss: 1.8792 - val_mean_absolute_error: 1.8792
Epoch 400/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4852 - mean_absolute_error: 0.4852 - val_loss: 2.0168 - val_mean_absolute_error: 2.0168
Epoch 401/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.5524 - mean_absolute_error: 0.5524 - val_loss: 1.9041 - val_mean_absolute_error: 1.9041
Epoch 402/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5119 - mean_absolute_error: 0.5119 - val_loss: 1.7829 - val_mean_absolute_error: 1.7829
Epoch 403/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4389 - mean_absolute_error: 0.4389 - val_loss: 1.9382 - val_mean_absolute_error: 1.9382
Epoch 404/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4166 - mean_absolute_error: 0.4166 - val_loss: 1.8110 - val_mean_absolute_error: 1.8110
Epoch 405/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3541 - mean_absolute_error: 0.3541 - val_loss: 1.8188 - val_mean_absolute_error: 1.8188
Epoch 406/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.3755 - mean_absolute_error: 0.3755 - val_loss: 1.8590 - val_mean_absolute_error: 1.8590
Epoch 407/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3493 - mean_absolute_error: 0.3493 - val_loss: 1.8336 - val_mean_absolute_error: 1.8336
Epoch 408/1000
11/11 [==============================] - 0s 26ms/step - loss: 0.4460 - mean_absolute_error: 0.4460 - val_loss: 1.8048 - val_mean_absolute_error: 1.8048
Epoch 409/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3860 - mean_absolute_error: 0.3860 - val_loss: 1.8259 - val_mean_absolute_error: 1.8259
Epoch 410/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4319 - mean_absolute_error: 0.4319 - val_loss: 1.8299 - val_mean_absolute_error: 1.8299
Epoch 411/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.3817 - mean_absolute_error: 0.3817 - val_loss: 1.7637 - val_mean_absolute_error: 1.7637
Epoch 412/1000
11/11 [==============================] - 0s 29ms/step - loss: 0.3678 - mean_absolute_error: 0.3678 - val_loss: 1.7636 - val_mean_absolute_error: 1.7636
Epoch 413/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4043 - mean_absolute_error: 0.4043 - val_loss: 1.8744 - val_mean_absolute_error: 1.8744
Epoch 414/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4362 - mean_absolute_error: 0.4362 - val_loss: 1.8182 - val_mean_absolute_error: 1.8182
Epoch 415/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4239 - mean_absolute_error: 0.4239 - val_loss: 1.8555 - val_mean_absolute_error: 1.8555
Epoch 416/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4184 - mean_absolute_error: 0.4184 - val_loss: 1.7809 - val_mean_absolute_error: 1.7809
Epoch 417/1000

11/11 [==============================] - 0s 22ms/step - loss: 0.4797 - mean_absolute_error: 0.4797 - val_loss: 1.9195 - val_mean_absolute_error: 1.9195
Epoch 418/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4850 - mean_absolute_error: 0.4850 - val_loss: 1.7894 - val_mean_absolute_error: 1.7894
Epoch 419/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4150 - mean_absolute_error: 0.4150 - val_loss: 1.7881 - val_mean_absolute_error: 1.7881
Epoch 420/1000
11/11 [==============================] - 0s 21ms/step - loss: 0.3494 - mean_absolute_error: 0.3494 - val_loss: 1.9011 - val_mean_absolute_error: 1.9011
Epoch 421/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4566 - mean_absolute_error: 0.4566 - val_loss: 1.7415 - val_mean_absolute_error: 1.7415
Epoch 422/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.4076 - mean_absolute_error: 0.4076 - val_loss: 1.8918 - val_mean_absolute_error: 1.8918
Epoch 423/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.4367 - mean_absolute_error: 0.4367 - val_loss: 1.8656 - val_mean_absolute_error: 1.8656
Epoch 424/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4228 - mean_absolute_error: 0.4228 - val_loss: 1.7434 - val_mean_absolute_error: 1.7434
Epoch 425/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4624 - mean_absolute_error: 0.4624 - val_loss: 1.8492 - val_mean_absolute_error: 1.8492
Epoch 426/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.3987 - mean_absolute_error: 0.3987 - val_loss: 1.8551 - val_mean_absolute_error: 1.8551
Epoch 427/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3525 - mean_absolute_error: 0.3525 - val_loss: 1.8371 - val_mean_absolute_error: 1.8371
Epoch 428/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3466 - mean_absolute_error: 0.3466 - val_loss: 1.8839 - val_mean_absolute_error: 1.8839
Epoch 429/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.3753 - mean_absolute_error: 0.3753 - val_loss: 1.8470 - val_mean_absolute_error: 1.8470
Epoch 430/1000
11/11 [==============================] - 0s 24ms/step - loss: 0.4299 - mean_absolute_error: 0.4299 - val_loss: 1.7846 - val_mean_absolute_error: 1.7846
Epoch 431/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4380 - mean_absolute_error: 0.4380 - val_loss: 1.8536 - val_mean_absolute_error: 1.8536
Epoch 432/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.4347 - mean_absolute_error: 0.4347 - val_loss: 1.7761 - val_mean_absolute_error: 1.7761
Epoch 433/1000
11/11 [==============================] - 0s 42ms/step - loss: 0.4562 - mean_absolute_error: 0.4562 - val_loss: 1.9414 - val_mean_absolute_error: 1.9414
Epoch 434/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.4311 - mean_absolute_error: 0.4311 - val_loss: 1.7685 - val_mean_absolute_error: 1.7685
Epoch 435/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4778 - mean_absolute_error: 0.4778 - val_loss: 1.7893 - val_mean_absolute_error: 1.7893
Epoch 436/1000
11/11 [==============================] - 0s 25ms/step - loss: 0.4211 - mean_absolute_error: 0.4211 - val_loss: 1.7975 - val_mean_absolute_error: 1.7975
Epoch 437/1000
11/11 [==============================] - 0s 31ms/step - loss: 0.3672 - mean_absolute_error: 0.3672 - val_loss: 1.8751 - val_mean_absolute_error: 1.8751
Epoch 438/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.4534 - mean_absolute_error: 0.4534 - val_loss: 1.8200 - val_mean_absolute_error: 1.8200
Epoch 439/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.3716 - mean_absolute_error: 0.3716 - val_loss: 1.7811 - val_mean_absolute_error: 1.7811
Epoch 440/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4399 - mean_absolute_error: 0.4399 - val_loss: 1.8528 - val_mean_absolute_error: 1.8528
Epoch 441/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.4118 - mean_absolute_error: 0.4118 - val_loss: 1.7620 - val_mean_absolute_error: 1.7620
Epoch 442/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4205 - mean_absolute_error: 0.4205 - val_loss: 1.9119 - val_mean_absolute_error: 1.9119
Epoch 443/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4318 - mean_absolute_error: 0.4318 - val_loss: 1.8197 - val_mean_absolute_error: 1.8197
Epoch 444/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4249 - mean_absolute_error: 0.4249 - val_loss: 1.7818 - val_mean_absolute_error: 1.7818
Epoch 445/1000
11/11 [==============================] - 0s 27ms/step - loss: 0.4290 - mean_absolute_error: 0.4290 - val_loss: 1.8883 - val_mean_absolute_error: 1.8883
Epoch 446/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4067 - mean_absolute_error: 0.4067 - val_loss: 1.8379 - val_mean_absolute_error: 1.8379
Epoch 447/1000
11/11 [==============================] - 0s 25ms/step - loss: 0.3627 - mean_absolute_error: 0.3627 - val_loss: 1.8899 - val_mean_absolute_error: 1.8899
Epoch 448/1000
11/11 [==============================] - 0s 42ms/step - loss: 0.3737 - mean_absolute_error: 0.3737 - val_loss: 1.8739 - val_mean_absolute_error: 1.8739
Epoch 449/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.3807 - mean_absolute_error: 0.3807 - val_loss: 1.7948 - val_mean_absolute_error: 1.7948
Epoch 450/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.3672 - mean_absolute_error: 0.3672 - val_loss: 1.8916 - val_mean_absolute_error: 1.8916
Epoch 451/1000
11/11 [==============================] - 0s 21ms/step - loss: 0.3587 - mean_absolute_error: 0.3587 - val_loss: 1.9724 - val_mean_absolute_error: 1.9724
Epoch 452/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.4615 - mean_absolute_error: 0.4615 - val_loss: 1.7890 - val_mean_absolute_error: 1.7890
Epoch 453/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.4495 - mean_absolute_error: 0.4495 - val_loss: 1.8295 - val_mean_absolute_error: 1.8295
Epoch 454/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3841 - mean_absolute_error: 0.3841 - val_loss: 1.7628 - val_mean_absolute_error: 1.7628
Epoch 455/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.5013 - mean_absolute_error: 0.5013 - val_loss: 1.8699 - val_mean_absolute_error: 1.8699
Epoch 456/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5185 - mean_absolute_error: 0.5185 - val_loss: 1.9746 - val_mean_absolute_error: 1.9746
Epoch 457/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.5014 - mean_absolute_error: 0.5014 - val_loss: 1.9371 - val_mean_absolute_error: 1.9371
Epoch 458/1000
11/11 [==============================] - 0s 24ms/step - loss: 0.4893 - mean_absolute_error: 0.4893 - val_loss: 1.8865 - val_mean_absolute_error: 1.8865
Epoch 459/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4574 - mean_absolute_error: 0.4574 - val_loss: 1.7649 - val_mean_absolute_error: 1.7649
Epoch 460/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3946 - mean_absolute_error: 0.3946 - val_loss: 1.8332 - val_mean_absolute_error: 1.8332
Epoch 461/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3362 - mean_absolute_error: 0.3362 - val_loss: 1.8061 - val_mean_absolute_error: 1.8061
Epoch 462/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3372 - mean_absolute_error: 0.3372 - val_loss: 1.7832 - val_mean_absolute_error: 1.7832
Epoch 463/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3352 - mean_absolute_error: 0.3352 - val_loss: 1.8042 - val_mean_absolute_error: 1.8042
Epoch 464/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3211 - mean_absolute_error: 0.3211 - val_loss: 1.7779 - val_mean_absolute_error: 1.7779
Epoch 465/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3193 - mean_absolute_error: 0.3193 - val_loss: 1.8603 - val_mean_absolute_error: 1.8603
Epoch 466/1000

11/11 [==============================] - 0s 20ms/step - loss: 0.3258 - mean_absolute_error: 0.3258 - val_loss: 1.8040 - val_mean_absolute_error: 1.8040
Epoch 467/1000
11/11 [==============================] - 0s 25ms/step - loss: 0.3148 - mean_absolute_error: 0.3148 - val_loss: 1.8993 - val_mean_absolute_error: 1.8993
Epoch 468/1000
11/11 [==============================] - 0s 24ms/step - loss: 0.4193 - mean_absolute_error: 0.4193 - val_loss: 1.7672 - val_mean_absolute_error: 1.7672
Epoch 469/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4356 - mean_absolute_error: 0.4356 - val_loss: 1.7980 - val_mean_absolute_error: 1.7980
Epoch 470/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4126 - mean_absolute_error: 0.4126 - val_loss: 1.8427 - val_mean_absolute_error: 1.8427
Epoch 471/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3475 - mean_absolute_error: 0.3475 - val_loss: 1.8727 - val_mean_absolute_error: 1.8727
Epoch 472/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3939 - mean_absolute_error: 0.3939 - val_loss: 1.8294 - val_mean_absolute_error: 1.8294
Epoch 473/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4097 - mean_absolute_error: 0.4097 - val_loss: 1.8067 - val_mean_absolute_error: 1.8067
Epoch 474/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4554 - mean_absolute_error: 0.4554 - val_loss: 1.7917 - val_mean_absolute_error: 1.7917
Epoch 475/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4010 - mean_absolute_error: 0.4010 - val_loss: 1.8753 - val_mean_absolute_error: 1.8753
Epoch 476/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4300 - mean_absolute_error: 0.4300 - val_loss: 1.7992 - val_mean_absolute_error: 1.7992
Epoch 477/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.3817 - mean_absolute_error: 0.3817 - val_loss: 1.8555 - val_mean_absolute_error: 1.8555
Epoch 478/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3838 - mean_absolute_error: 0.3838 - val_loss: 1.8632 - val_mean_absolute_error: 1.8632
Epoch 479/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3695 - mean_absolute_error: 0.3695 - val_loss: 1.7493 - val_mean_absolute_error: 1.7493
Epoch 480/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5201 - mean_absolute_error: 0.5201 - val_loss: 1.8178 - val_mean_absolute_error: 1.8178
Epoch 481/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4534 - mean_absolute_error: 0.4534 - val_loss: 1.8048 - val_mean_absolute_error: 1.8048
Epoch 482/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3516 - mean_absolute_error: 0.3516 - val_loss: 1.8034 - val_mean_absolute_error: 1.8034
Epoch 483/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3526 - mean_absolute_error: 0.3526 - val_loss: 1.8228 - val_mean_absolute_error: 1.8228
Epoch 484/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3940 - mean_absolute_error: 0.3940 - val_loss: 1.8168 - val_mean_absolute_error: 1.8168
Epoch 485/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3494 - mean_absolute_error: 0.3494 - val_loss: 1.8341 - val_mean_absolute_error: 1.8341
Epoch 486/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3491 - mean_absolute_error: 0.3491 - val_loss: 1.8369 - val_mean_absolute_error: 1.8369
Epoch 487/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3495 - mean_absolute_error: 0.3495 - val_loss: 1.8023 - val_mean_absolute_error: 1.8023
Epoch 488/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.3220 - mean_absolute_error: 0.3220 - val_loss: 1.8470 - val_mean_absolute_error: 1.8470
Epoch 489/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.3564 - mean_absolute_error: 0.3564 - val_loss: 1.9537 - val_mean_absolute_error: 1.9537
Epoch 490/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3975 - mean_absolute_error: 0.3975 - val_loss: 1.7986 - val_mean_absolute_error: 1.7986
Epoch 491/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.3522 - mean_absolute_error: 0.3522 - val_loss: 1.8004 - val_mean_absolute_error: 1.8004
Epoch 492/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3680 - mean_absolute_error: 0.3680 - val_loss: 1.8057 - val_mean_absolute_error: 1.8057
Epoch 493/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3693 - mean_absolute_error: 0.3693 - val_loss: 1.8604 - val_mean_absolute_error: 1.8604
Epoch 494/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.3230 - mean_absolute_error: 0.3230 - val_loss: 1.7731 - val_mean_absolute_error: 1.7731
Epoch 495/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.3146 - mean_absolute_error: 0.3146 - val_loss: 1.8200 - val_mean_absolute_error: 1.8200
Epoch 496/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3165 - mean_absolute_error: 0.3165 - val_loss: 1.8098 - val_mean_absolute_error: 1.8098
Epoch 497/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3686 - mean_absolute_error: 0.3686 - val_loss: 1.8652 - val_mean_absolute_error: 1.8652
Epoch 498/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.3290 - mean_absolute_error: 0.3290 - val_loss: 1.7746 - val_mean_absolute_error: 1.7746
Epoch 499/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3357 - mean_absolute_error: 0.3357 - val_loss: 1.8255 - val_mean_absolute_error: 1.8255
Epoch 500/1000
11/11 [==============================] - 0s 24ms/step - loss: 0.3514 - mean_absolute_error: 0.3514 - val_loss: 1.8552 - val_mean_absolute_error: 1.8552
Epoch 501/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.3135 - mean_absolute_error: 0.3135 - val_loss: 1.7867 - val_mean_absolute_error: 1.7867
Epoch 502/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2910 - mean_absolute_error: 0.2910 - val_loss: 1.7947 - val_mean_absolute_error: 1.7947
Epoch 503/1000
11/11 [==============================] - 0s 21ms/step - loss: 0.3648 - mean_absolute_error: 0.3648 - val_loss: 1.9033 - val_mean_absolute_error: 1.9033
Epoch 504/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.3539 - mean_absolute_error: 0.3539 - val_loss: 1.7923 - val_mean_absolute_error: 1.7923
Epoch 505/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.3202 - mean_absolute_error: 0.3202 - val_loss: 1.8281 - val_mean_absolute_error: 1.8281
Epoch 506/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3223 - mean_absolute_error: 0.3223 - val_loss: 1.8399 - val_mean_absolute_error: 1.8399
Epoch 507/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3609 - mean_absolute_error: 0.3609 - val_loss: 1.8661 - val_mean_absolute_error: 1.8661
Epoch 508/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3631 - mean_absolute_error: 0.3631 - val_loss: 1.9650 - val_mean_absolute_error: 1.9650
Epoch 509/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.5214 - mean_absolute_error: 0.5214 - val_loss: 1.9803 - val_mean_absolute_error: 1.9803
Epoch 510/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.4194 - mean_absolute_error: 0.4194 - val_loss: 1.8717 - val_mean_absolute_error: 1.8717
Epoch 511/1000
11/11 [==============================] - 0s 27ms/step - loss: 0.3892 - mean_absolute_error: 0.3892 - val_loss: 1.7872 - val_mean_absolute_error: 1.7872
Epoch 512/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3633 - mean_absolute_error: 0.3633 - val_loss: 1.7474 - val_mean_absolute_error: 1.7474
Epoch 513/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3385 - mean_absolute_error: 0.3385 - val_loss: 1.7751 - val_mean_absolute_error: 1.7751
Epoch 514/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.3532 - mean_absolute_error: 0.3532 - val_loss: 1.8209 - val_mean_absolute_error: 1.8209
Epoch 515/1000

11/11 [==============================] - 0s 24ms/step - loss: 0.4666 - mean_absolute_error: 0.4666 - val_loss: 1.8552 - val_mean_absolute_error: 1.8552
Epoch 516/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4238 - mean_absolute_error: 0.4238 - val_loss: 1.7844 - val_mean_absolute_error: 1.7844
Epoch 517/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3800 - mean_absolute_error: 0.3800 - val_loss: 2.0087 - val_mean_absolute_error: 2.0087
Epoch 518/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.5814 - mean_absolute_error: 0.5814 - val_loss: 1.8433 - val_mean_absolute_error: 1.8433
Epoch 519/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.3535 - mean_absolute_error: 0.3535 - val_loss: 1.8429 - val_mean_absolute_error: 1.8429
Epoch 520/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.3004 - mean_absolute_error: 0.3004 - val_loss: 1.8729 - val_mean_absolute_error: 1.8729
Epoch 521/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2970 - mean_absolute_error: 0.2970 - val_loss: 1.7820 - val_mean_absolute_error: 1.7820
Epoch 522/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3096 - mean_absolute_error: 0.3096 - val_loss: 1.7655 - val_mean_absolute_error: 1.7655
Epoch 523/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.3087 - mean_absolute_error: 0.3087 - val_loss: 1.7670 - val_mean_absolute_error: 1.7670
Epoch 524/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3603 - mean_absolute_error: 0.3603 - val_loss: 1.8332 - val_mean_absolute_error: 1.8332
Epoch 525/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3170 - mean_absolute_error: 0.3170 - val_loss: 1.8461 - val_mean_absolute_error: 1.8461
Epoch 526/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.2883 - mean_absolute_error: 0.2883 - val_loss: 1.8216 - val_mean_absolute_error: 1.8216
Epoch 527/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.2720 - mean_absolute_error: 0.2720 - val_loss: 1.7555 - val_mean_absolute_error: 1.7555
Epoch 528/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.4040 - mean_absolute_error: 0.4040 - val_loss: 1.9594 - val_mean_absolute_error: 1.9594
Epoch 529/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3970 - mean_absolute_error: 0.3970 - val_loss: 1.8252 - val_mean_absolute_error: 1.8252
Epoch 530/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.6501 - mean_absolute_error: 0.6501 - val_loss: 1.8045 - val_mean_absolute_error: 1.8045
Epoch 531/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4442 - mean_absolute_error: 0.4442 - val_loss: 1.7951 - val_mean_absolute_error: 1.7951
Epoch 532/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4034 - mean_absolute_error: 0.4034 - val_loss: 2.0252 - val_mean_absolute_error: 2.0252
Epoch 533/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4542 - mean_absolute_error: 0.4542 - val_loss: 1.7449 - val_mean_absolute_error: 1.7449
Epoch 534/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3574 - mean_absolute_error: 0.3574 - val_loss: 1.8915 - val_mean_absolute_error: 1.8915
Epoch 535/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3646 - mean_absolute_error: 0.3646 - val_loss: 1.8935 - val_mean_absolute_error: 1.8935
Epoch 536/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3344 - mean_absolute_error: 0.3344 - val_loss: 1.8649 - val_mean_absolute_error: 1.8649
Epoch 537/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3691 - mean_absolute_error: 0.3691 - val_loss: 1.7949 - val_mean_absolute_error: 1.7949
Epoch 538/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.3613 - mean_absolute_error: 0.3613 - val_loss: 1.8448 - val_mean_absolute_error: 1.8448
Epoch 539/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.2943 - mean_absolute_error: 0.2943 - val_loss: 1.8106 - val_mean_absolute_error: 1.8106
Epoch 540/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3056 - mean_absolute_error: 0.3056 - val_loss: 1.8461 - val_mean_absolute_error: 1.8461
Epoch 541/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3550 - mean_absolute_error: 0.3550 - val_loss: 1.7723 - val_mean_absolute_error: 1.7723
Epoch 542/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3182 - mean_absolute_error: 0.3182 - val_loss: 1.8183 - val_mean_absolute_error: 1.8183
Epoch 543/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3139 - mean_absolute_error: 0.3139 - val_loss: 1.9916 - val_mean_absolute_error: 1.9916
Epoch 544/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4753 - mean_absolute_error: 0.4753 - val_loss: 1.8218 - val_mean_absolute_error: 1.8218
Epoch 545/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3035 - mean_absolute_error: 0.3035 - val_loss: 1.8669 - val_mean_absolute_error: 1.8669
Epoch 546/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.3401 - mean_absolute_error: 0.3401 - val_loss: 1.8621 - val_mean_absolute_error: 1.8621
Epoch 547/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3598 - mean_absolute_error: 0.3598 - val_loss: 1.8111 - val_mean_absolute_error: 1.8111
Epoch 548/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.4909 - mean_absolute_error: 0.4909 - val_loss: 1.8386 - val_mean_absolute_error: 1.8386
Epoch 549/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3706 - mean_absolute_error: 0.3706 - val_loss: 1.8867 - val_mean_absolute_error: 1.8867
Epoch 550/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3505 - mean_absolute_error: 0.3505 - val_loss: 1.8068 - val_mean_absolute_error: 1.8068
Epoch 551/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3401 - mean_absolute_error: 0.3401 - val_loss: 1.8104 - val_mean_absolute_error: 1.8104
Epoch 552/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3415 - mean_absolute_error: 0.3415 - val_loss: 1.8198 - val_mean_absolute_error: 1.8198
Epoch 553/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2927 - mean_absolute_error: 0.2927 - val_loss: 1.8747 - val_mean_absolute_error: 1.8747
Epoch 554/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.3943 - mean_absolute_error: 0.3943 - val_loss: 1.7973 - val_mean_absolute_error: 1.7973
Epoch 555/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4091 - mean_absolute_error: 0.4091 - val_loss: 1.9873 - val_mean_absolute_error: 1.9873
Epoch 556/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4080 - mean_absolute_error: 0.4080 - val_loss: 1.7699 - val_mean_absolute_error: 1.7699
Epoch 557/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3048 - mean_absolute_error: 0.3048 - val_loss: 1.8429 - val_mean_absolute_error: 1.8429
Epoch 558/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2915 - mean_absolute_error: 0.2915 - val_loss: 1.8084 - val_mean_absolute_error: 1.8084
Epoch 559/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4154 - mean_absolute_error: 0.4154 - val_loss: 1.9035 - val_mean_absolute_error: 1.9035
Epoch 560/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3073 - mean_absolute_error: 0.3073 - val_loss: 1.8641 - val_mean_absolute_error: 1.8641
Epoch 561/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3062 - mean_absolute_error: 0.3062 - val_loss: 1.7818 - val_mean_absolute_error: 1.7818
Epoch 562/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2918 - mean_absolute_error: 0.2918 - val_loss: 1.7727 - val_mean_absolute_error: 1.7727
Epoch 563/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2760 - mean_absolute_error: 0.2760 - val_loss: 1.7958 - val_mean_absolute_error: 1.7958
Epoch 564/1000

11/11 [==============================] - 0s 15ms/step - loss: 0.2846 - mean_absolute_error: 0.2846 - val_loss: 1.8282 - val_mean_absolute_error: 1.8282
Epoch 565/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2857 - mean_absolute_error: 0.2857 - val_loss: 1.8605 - val_mean_absolute_error: 1.8605
Epoch 566/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2983 - mean_absolute_error: 0.2983 - val_loss: 1.8434 - val_mean_absolute_error: 1.8434
Epoch 567/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2809 - mean_absolute_error: 0.2809 - val_loss: 1.8653 - val_mean_absolute_error: 1.8653
Epoch 568/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2950 - mean_absolute_error: 0.2950 - val_loss: 1.8344 - val_mean_absolute_error: 1.8344
Epoch 569/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2892 - mean_absolute_error: 0.2892 - val_loss: 1.7874 - val_mean_absolute_error: 1.7874
Epoch 570/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3999 - mean_absolute_error: 0.3999 - val_loss: 1.8381 - val_mean_absolute_error: 1.8381
Epoch 571/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3352 - mean_absolute_error: 0.3352 - val_loss: 1.8601 - val_mean_absolute_error: 1.8601
Epoch 572/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.3059 - mean_absolute_error: 0.3059 - val_loss: 1.8995 - val_mean_absolute_error: 1.8995
Epoch 573/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4247 - mean_absolute_error: 0.4247 - val_loss: 1.8590 - val_mean_absolute_error: 1.8590
Epoch 574/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3491 - mean_absolute_error: 0.3491 - val_loss: 1.8534 - val_mean_absolute_error: 1.8534
Epoch 575/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3289 - mean_absolute_error: 0.3289 - val_loss: 1.8392 - val_mean_absolute_error: 1.8392
Epoch 576/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.3192 - mean_absolute_error: 0.3192 - val_loss: 1.7962 - val_mean_absolute_error: 1.7962
Epoch 577/1000
11/11 [==============================] - 0s 28ms/step - loss: 0.3490 - mean_absolute_error: 0.3490 - val_loss: 1.8081 - val_mean_absolute_error: 1.8081
Epoch 578/1000
11/11 [==============================] - 0s 29ms/step - loss: 0.3214 - mean_absolute_error: 0.3214 - val_loss: 1.8664 - val_mean_absolute_error: 1.8664
Epoch 579/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.3344 - mean_absolute_error: 0.3344 - val_loss: 1.8576 - val_mean_absolute_error: 1.8576
Epoch 580/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.3297 - mean_absolute_error: 0.3297 - val_loss: 1.8135 - val_mean_absolute_error: 1.8135
Epoch 581/1000
11/11 [==============================] - 0s 31ms/step - loss: 0.3237 - mean_absolute_error: 0.3237 - val_loss: 1.8638 - val_mean_absolute_error: 1.8638
Epoch 582/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.3507 - mean_absolute_error: 0.3507 - val_loss: 1.8074 - val_mean_absolute_error: 1.8074
Epoch 583/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.3457 - mean_absolute_error: 0.3457 - val_loss: 1.8299 - val_mean_absolute_error: 1.8299
Epoch 584/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.3450 - mean_absolute_error: 0.3450 - val_loss: 1.8806 - val_mean_absolute_error: 1.8806
Epoch 585/1000
11/11 [==============================] - 0s 27ms/step - loss: 0.3277 - mean_absolute_error: 0.3277 - val_loss: 1.8151 - val_mean_absolute_error: 1.8151
Epoch 586/1000
11/11 [==============================] - 0s 28ms/step - loss: 0.3899 - mean_absolute_error: 0.3899 - val_loss: 1.8384 - val_mean_absolute_error: 1.8384
Epoch 587/1000
11/11 [==============================] - 0s 21ms/step - loss: 0.3549 - mean_absolute_error: 0.3549 - val_loss: 1.8057 - val_mean_absolute_error: 1.8057
Epoch 588/1000
11/11 [==============================] - 0s 32ms/step - loss: 0.3044 - mean_absolute_error: 0.3044 - val_loss: 1.8610 - val_mean_absolute_error: 1.8610
Epoch 589/1000
11/11 [==============================] - 0s 35ms/step - loss: 0.3364 - mean_absolute_error: 0.3364 - val_loss: 1.8210 - val_mean_absolute_error: 1.8210
Epoch 590/1000
11/11 [==============================] - 0s 29ms/step - loss: 0.3024 - mean_absolute_error: 0.3024 - val_loss: 1.8022 - val_mean_absolute_error: 1.8022
Epoch 591/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2949 - mean_absolute_error: 0.2949 - val_loss: 1.7979 - val_mean_absolute_error: 1.7979
Epoch 592/1000
11/11 [==============================] - 0s 27ms/step - loss: 0.2718 - mean_absolute_error: 0.2718 - val_loss: 1.8210 - val_mean_absolute_error: 1.8210
Epoch 593/1000
11/11 [==============================] - 0s 28ms/step - loss: 0.2972 - mean_absolute_error: 0.2972 - val_loss: 1.8025 - val_mean_absolute_error: 1.8025
Epoch 594/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3513 - mean_absolute_error: 0.3513 - val_loss: 1.9098 - val_mean_absolute_error: 1.9098
Epoch 595/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3978 - mean_absolute_error: 0.3978 - val_loss: 1.8086 - val_mean_absolute_error: 1.8086
Epoch 596/1000
11/11 [==============================] - 0s 27ms/step - loss: 0.3343 - mean_absolute_error: 0.3343 - val_loss: 1.8136 - val_mean_absolute_error: 1.8136
Epoch 597/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3485 - mean_absolute_error: 0.3485 - val_loss: 1.9460 - val_mean_absolute_error: 1.9460
Epoch 598/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4468 - mean_absolute_error: 0.4468 - val_loss: 1.9282 - val_mean_absolute_error: 1.9282
Epoch 599/1000
11/11 [==============================] - 0s 28ms/step - loss: 0.4236 - mean_absolute_error: 0.4236 - val_loss: 1.8320 - val_mean_absolute_error: 1.8320
Epoch 600/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3582 - mean_absolute_error: 0.3582 - val_loss: 1.9449 - val_mean_absolute_error: 1.9449
Epoch 601/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4210 - mean_absolute_error: 0.4210 - val_loss: 1.7744 - val_mean_absolute_error: 1.7744
Epoch 602/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4194 - mean_absolute_error: 0.4194 - val_loss: 1.7680 - val_mean_absolute_error: 1.7680
Epoch 603/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4034 - mean_absolute_error: 0.4034 - val_loss: 1.8539 - val_mean_absolute_error: 1.8539
Epoch 604/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3168 - mean_absolute_error: 0.3168 - val_loss: 1.8448 - val_mean_absolute_error: 1.8448
Epoch 605/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3310 - mean_absolute_error: 0.3310 - val_loss: 1.8012 - val_mean_absolute_error: 1.8012
Epoch 606/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2827 - mean_absolute_error: 0.2827 - val_loss: 1.7659 - val_mean_absolute_error: 1.7659
Epoch 607/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2995 - mean_absolute_error: 0.2995 - val_loss: 1.8194 - val_mean_absolute_error: 1.8194
Epoch 608/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3161 - mean_absolute_error: 0.3161 - val_loss: 1.8149 - val_mean_absolute_error: 1.8149
Epoch 609/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3710 - mean_absolute_error: 0.3710 - val_loss: 1.7774 - val_mean_absolute_error: 1.7774
Epoch 610/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3209 - mean_absolute_error: 0.3209 - val_loss: 1.9144 - val_mean_absolute_error: 1.9144
Epoch 611/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3665 - mean_absolute_error: 0.3665 - val_loss: 1.8231 - val_mean_absolute_error: 1.8231
Epoch 612/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3996 - mean_absolute_error: 0.3996 - val_loss: 1.9530 - val_mean_absolute_error: 1.9530
Epoch 613/1000

11/11 [==============================] - 0s 15ms/step - loss: 0.4348 - mean_absolute_error: 0.4348 - val_loss: 2.0230 - val_mean_absolute_error: 2.0230
Epoch 614/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4434 - mean_absolute_error: 0.4434 - val_loss: 1.7802 - val_mean_absolute_error: 1.7802
Epoch 615/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4024 - mean_absolute_error: 0.4024 - val_loss: 1.7910 - val_mean_absolute_error: 1.7910
Epoch 616/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3881 - mean_absolute_error: 0.3881 - val_loss: 1.8593 - val_mean_absolute_error: 1.8593
Epoch 617/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3161 - mean_absolute_error: 0.3161 - val_loss: 1.9295 - val_mean_absolute_error: 1.9295
Epoch 618/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3913 - mean_absolute_error: 0.3913 - val_loss: 1.7850 - val_mean_absolute_error: 1.7850
Epoch 619/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3371 - mean_absolute_error: 0.3371 - val_loss: 1.7741 - val_mean_absolute_error: 1.7741
Epoch 620/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3670 - mean_absolute_error: 0.3670 - val_loss: 1.8438 - val_mean_absolute_error: 1.8438
Epoch 621/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3128 - mean_absolute_error: 0.3128 - val_loss: 1.8510 - val_mean_absolute_error: 1.8510
Epoch 622/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3035 - mean_absolute_error: 0.3035 - val_loss: 1.7972 - val_mean_absolute_error: 1.7972
Epoch 623/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3047 - mean_absolute_error: 0.3047 - val_loss: 1.8609 - val_mean_absolute_error: 1.8609
Epoch 624/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2747 - mean_absolute_error: 0.2747 - val_loss: 1.8574 - val_mean_absolute_error: 1.8574
Epoch 625/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2753 - mean_absolute_error: 0.2753 - val_loss: 1.8490 - val_mean_absolute_error: 1.8490
Epoch 626/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2897 - mean_absolute_error: 0.2897 - val_loss: 1.7848 - val_mean_absolute_error: 1.7848
Epoch 627/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3712 - mean_absolute_error: 0.3712 - val_loss: 1.8387 - val_mean_absolute_error: 1.8387
Epoch 628/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3035 - mean_absolute_error: 0.3035 - val_loss: 1.8790 - val_mean_absolute_error: 1.8790
Epoch 629/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2859 - mean_absolute_error: 0.2859 - val_loss: 1.7933 - val_mean_absolute_error: 1.7933
Epoch 630/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3141 - mean_absolute_error: 0.3141 - val_loss: 1.7758 - val_mean_absolute_error: 1.7758
Epoch 631/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2721 - mean_absolute_error: 0.2721 - val_loss: 1.7849 - val_mean_absolute_error: 1.7849
Epoch 632/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2899 - mean_absolute_error: 0.2899 - val_loss: 1.7876 - val_mean_absolute_error: 1.7876
Epoch 633/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2929 - mean_absolute_error: 0.2929 - val_loss: 1.8323 - val_mean_absolute_error: 1.8323
Epoch 634/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3512 - mean_absolute_error: 0.3512 - val_loss: 1.8161 - val_mean_absolute_error: 1.8161
Epoch 635/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3838 - mean_absolute_error: 0.3838 - val_loss: 1.8425 - val_mean_absolute_error: 1.8425
Epoch 636/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2810 - mean_absolute_error: 0.2810 - val_loss: 1.9572 - val_mean_absolute_error: 1.9572
Epoch 637/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.4044 - mean_absolute_error: 0.4044 - val_loss: 1.7862 - val_mean_absolute_error: 1.7862
Epoch 638/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3953 - mean_absolute_error: 0.3953 - val_loss: 1.7689 - val_mean_absolute_error: 1.7689
Epoch 639/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4956 - mean_absolute_error: 0.4956 - val_loss: 1.8423 - val_mean_absolute_error: 1.8423
Epoch 640/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3844 - mean_absolute_error: 0.3844 - val_loss: 1.8955 - val_mean_absolute_error: 1.8955
Epoch 641/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.3255 - mean_absolute_error: 0.3255 - val_loss: 1.8360 - val_mean_absolute_error: 1.8360
Epoch 642/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2673 - mean_absolute_error: 0.2673 - val_loss: 1.8222 - val_mean_absolute_error: 1.8222
Epoch 643/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2900 - mean_absolute_error: 0.2900 - val_loss: 1.8377 - val_mean_absolute_error: 1.8377
Epoch 644/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3132 - mean_absolute_error: 0.3132 - val_loss: 1.9542 - val_mean_absolute_error: 1.9542
Epoch 645/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3032 - mean_absolute_error: 0.3032 - val_loss: 1.8959 - val_mean_absolute_error: 1.8959
Epoch 646/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2658 - mean_absolute_error: 0.2658 - val_loss: 1.8424 - val_mean_absolute_error: 1.8424
Epoch 647/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2628 - mean_absolute_error: 0.2628 - val_loss: 1.7955 - val_mean_absolute_error: 1.7955
Epoch 648/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2597 - mean_absolute_error: 0.2597 - val_loss: 1.7963 - val_mean_absolute_error: 1.7963
Epoch 649/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2661 - mean_absolute_error: 0.2661 - val_loss: 1.8026 - val_mean_absolute_error: 1.8026
Epoch 650/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2403 - mean_absolute_error: 0.2403 - val_loss: 1.8409 - val_mean_absolute_error: 1.8409
Epoch 651/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.2900 - mean_absolute_error: 0.2900 - val_loss: 1.8531 - val_mean_absolute_error: 1.8531
Epoch 652/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.3629 - mean_absolute_error: 0.3629 - val_loss: 1.8399 - val_mean_absolute_error: 1.8399
Epoch 653/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.4175 - mean_absolute_error: 0.4175 - val_loss: 1.8331 - val_mean_absolute_error: 1.8331
Epoch 654/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5028 - mean_absolute_error: 0.5028 - val_loss: 1.8817 - val_mean_absolute_error: 1.8817
Epoch 655/1000
11/11 [==============================] - 0s 28ms/step - loss: 0.3446 - mean_absolute_error: 0.3446 - val_loss: 1.7678 - val_mean_absolute_error: 1.7678
Epoch 656/1000
11/11 [==============================] - 0s 32ms/step - loss: 0.2999 - mean_absolute_error: 0.2999 - val_loss: 1.7661 - val_mean_absolute_error: 1.7661
Epoch 657/1000
11/11 [==============================] - 0s 38ms/step - loss: 0.3843 - mean_absolute_error: 0.3843 - val_loss: 1.9590 - val_mean_absolute_error: 1.9590
Epoch 658/1000
11/11 [==============================] - 1s 60ms/step - loss: 0.3573 - mean_absolute_error: 0.3573 - val_loss: 1.8475 - val_mean_absolute_error: 1.8475
Epoch 659/1000
11/11 [==============================] - 1s 53ms/step - loss: 0.3914 - mean_absolute_error: 0.3914 - val_loss: 1.8220 - val_mean_absolute_error: 1.8220
Epoch 660/1000
11/11 [==============================] - 0s 36ms/step - loss: 0.4020 - mean_absolute_error: 0.4020 - val_loss: 1.8626 - val_mean_absolute_error: 1.8626
Epoch 661/1000
11/11 [==============================] - 0s 26ms/step - loss: 0.3520 - mean_absolute_error: 0.3520 - val_loss: 1.8810 - val_mean_absolute_error: 1.8810
Epoch 662/1000

11/11 [==============================] - 0s 31ms/step - loss: 0.3790 - mean_absolute_error: 0.3790 - val_loss: 1.8561 - val_mean_absolute_error: 1.8561
Epoch 663/1000
11/11 [==============================] - 0s 32ms/step - loss: 0.3126 - mean_absolute_error: 0.3126 - val_loss: 1.7692 - val_mean_absolute_error: 1.7692
Epoch 664/1000
11/11 [==============================] - 0s 36ms/step - loss: 0.2790 - mean_absolute_error: 0.2790 - val_loss: 1.8833 - val_mean_absolute_error: 1.8833
Epoch 665/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.2904 - mean_absolute_error: 0.2904 - val_loss: 1.8464 - val_mean_absolute_error: 1.8464
Epoch 666/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2902 - mean_absolute_error: 0.2902 - val_loss: 1.8318 - val_mean_absolute_error: 1.8318
Epoch 667/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2692 - mean_absolute_error: 0.2692 - val_loss: 1.8523 - val_mean_absolute_error: 1.8523
Epoch 668/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2974 - mean_absolute_error: 0.2974 - val_loss: 1.9159 - val_mean_absolute_error: 1.9159
Epoch 669/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.3770 - mean_absolute_error: 0.3770 - val_loss: 1.8347 - val_mean_absolute_error: 1.8347
Epoch 670/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.3325 - mean_absolute_error: 0.3325 - val_loss: 1.9144 - val_mean_absolute_error: 1.9144
Epoch 671/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3430 - mean_absolute_error: 0.3430 - val_loss: 1.7872 - val_mean_absolute_error: 1.7872
Epoch 672/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2832 - mean_absolute_error: 0.2832 - val_loss: 1.8037 - val_mean_absolute_error: 1.8037
Epoch 673/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3106 - mean_absolute_error: 0.3106 - val_loss: 1.8817 - val_mean_absolute_error: 1.8817
Epoch 674/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3228 - mean_absolute_error: 0.3228 - val_loss: 1.8536 - val_mean_absolute_error: 1.8536
Epoch 675/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2908 - mean_absolute_error: 0.2908 - val_loss: 1.8641 - val_mean_absolute_error: 1.8641
Epoch 676/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2778 - mean_absolute_error: 0.2778 - val_loss: 1.8970 - val_mean_absolute_error: 1.8970
Epoch 677/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3053 - mean_absolute_error: 0.3053 - val_loss: 1.8804 - val_mean_absolute_error: 1.8804
Epoch 678/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3236 - mean_absolute_error: 0.3236 - val_loss: 1.8483 - val_mean_absolute_error: 1.8483
Epoch 679/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3651 - mean_absolute_error: 0.3651 - val_loss: 1.8348 - val_mean_absolute_error: 1.8348
Epoch 680/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3287 - mean_absolute_error: 0.3287 - val_loss: 1.8458 - val_mean_absolute_error: 1.8458
Epoch 681/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3677 - mean_absolute_error: 0.3677 - val_loss: 1.8047 - val_mean_absolute_error: 1.8047
Epoch 682/1000
11/11 [==============================] - 0s 30ms/step - loss: 0.3006 - mean_absolute_error: 0.3006 - val_loss: 1.8300 - val_mean_absolute_error: 1.8300
Epoch 683/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.2901 - mean_absolute_error: 0.2901 - val_loss: 1.8014 - val_mean_absolute_error: 1.8014
Epoch 684/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3419 - mean_absolute_error: 0.3419 - val_loss: 1.7787 - val_mean_absolute_error: 1.7787
Epoch 685/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2972 - mean_absolute_error: 0.2972 - val_loss: 1.8279 - val_mean_absolute_error: 1.8279
Epoch 686/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2845 - mean_absolute_error: 0.2845 - val_loss: 1.8265 - val_mean_absolute_error: 1.8265
Epoch 687/1000
11/11 [==============================] - 0s 24ms/step - loss: 0.3227 - mean_absolute_error: 0.3227 - val_loss: 1.8530 - val_mean_absolute_error: 1.8530
Epoch 688/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3087 - mean_absolute_error: 0.3087 - val_loss: 1.8808 - val_mean_absolute_error: 1.8808
Epoch 689/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2837 - mean_absolute_error: 0.2837 - val_loss: 1.8583 - val_mean_absolute_error: 1.8583
Epoch 690/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2357 - mean_absolute_error: 0.2357 - val_loss: 1.8140 - val_mean_absolute_error: 1.8140
Epoch 691/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2602 - mean_absolute_error: 0.2602 - val_loss: 1.9106 - val_mean_absolute_error: 1.9106
Epoch 692/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3436 - mean_absolute_error: 0.3436 - val_loss: 1.8038 - val_mean_absolute_error: 1.8038
Epoch 693/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3236 - mean_absolute_error: 0.3236 - val_loss: 1.8160 - val_mean_absolute_error: 1.8160
Epoch 694/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2585 - mean_absolute_error: 0.2585 - val_loss: 1.8060 - val_mean_absolute_error: 1.8060
Epoch 695/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2843 - mean_absolute_error: 0.2843 - val_loss: 1.8154 - val_mean_absolute_error: 1.8154
Epoch 696/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2938 - mean_absolute_error: 0.2938 - val_loss: 1.7981 - val_mean_absolute_error: 1.7981
Epoch 697/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3402 - mean_absolute_error: 0.3402 - val_loss: 1.8055 - val_mean_absolute_error: 1.8055
Epoch 698/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3745 - mean_absolute_error: 0.3745 - val_loss: 1.9059 - val_mean_absolute_error: 1.9059
Epoch 699/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2802 - mean_absolute_error: 0.2802 - val_loss: 1.8141 - val_mean_absolute_error: 1.8141
Epoch 700/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.3110 - mean_absolute_error: 0.3110 - val_loss: 1.7866 - val_mean_absolute_error: 1.7866
Epoch 701/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3058 - mean_absolute_error: 0.3058 - val_loss: 1.8149 - val_mean_absolute_error: 1.8149
Epoch 702/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.3017 - mean_absolute_error: 0.3017 - val_loss: 1.9231 - val_mean_absolute_error: 1.9231
Epoch 703/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.4495 - mean_absolute_error: 0.4495 - val_loss: 1.9419 - val_mean_absolute_error: 1.9419
Epoch 704/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4598 - mean_absolute_error: 0.4598 - val_loss: 1.9641 - val_mean_absolute_error: 1.9641
Epoch 705/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3851 - mean_absolute_error: 0.3851 - val_loss: 1.9270 - val_mean_absolute_error: 1.9270
Epoch 706/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4600 - mean_absolute_error: 0.4600 - val_loss: 1.9386 - val_mean_absolute_error: 1.9386
Epoch 707/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3705 - mean_absolute_error: 0.3705 - val_loss: 1.8693 - val_mean_absolute_error: 1.8693
Epoch 708/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3169 - mean_absolute_error: 0.3169 - val_loss: 1.8310 - val_mean_absolute_error: 1.8310
Epoch 709/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3385 - mean_absolute_error: 0.3385 - val_loss: 1.8215 - val_mean_absolute_error: 1.8215
Epoch 710/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3095 - mean_absolute_error: 0.3095 - val_loss: 1.8058 - val_mean_absolute_error: 1.8058
Epoch 711/1000

11/11 [==============================] - 0s 15ms/step - loss: 0.2836 - mean_absolute_error: 0.2836 - val_loss: 1.8791 - val_mean_absolute_error: 1.8791
Epoch 712/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2525 - mean_absolute_error: 0.2525 - val_loss: 1.9147 - val_mean_absolute_error: 1.9147
Epoch 713/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2715 - mean_absolute_error: 0.2715 - val_loss: 1.8118 - val_mean_absolute_error: 1.8118
Epoch 714/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2540 - mean_absolute_error: 0.2540 - val_loss: 1.8532 - val_mean_absolute_error: 1.8532
Epoch 715/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2338 - mean_absolute_error: 0.2338 - val_loss: 1.8702 - val_mean_absolute_error: 1.8702
Epoch 716/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2435 - mean_absolute_error: 0.2435 - val_loss: 1.8631 - val_mean_absolute_error: 1.8631
Epoch 717/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2545 - mean_absolute_error: 0.2545 - val_loss: 1.8219 - val_mean_absolute_error: 1.8219
Epoch 718/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2354 - mean_absolute_error: 0.2354 - val_loss: 1.8551 - val_mean_absolute_error: 1.8551
Epoch 719/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2403 - mean_absolute_error: 0.2403 - val_loss: 1.8101 - val_mean_absolute_error: 1.8101
Epoch 720/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.2638 - mean_absolute_error: 0.2638 - val_loss: 1.8569 - val_mean_absolute_error: 1.8569
Epoch 721/1000
11/11 [==============================] - 0s 14ms/step - loss: 0.2445 - mean_absolute_error: 0.2445 - val_loss: 1.8249 - val_mean_absolute_error: 1.8249
Epoch 722/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2755 - mean_absolute_error: 0.2755 - val_loss: 1.9125 - val_mean_absolute_error: 1.9125
Epoch 723/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3453 - mean_absolute_error: 0.3453 - val_loss: 1.7805 - val_mean_absolute_error: 1.7805
Epoch 724/1000
11/11 [==============================] - 0s 26ms/step - loss: 0.3459 - mean_absolute_error: 0.3459 - val_loss: 1.8934 - val_mean_absolute_error: 1.8934
Epoch 725/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3183 - mean_absolute_error: 0.3183 - val_loss: 1.9095 - val_mean_absolute_error: 1.9095
Epoch 726/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2877 - mean_absolute_error: 0.2877 - val_loss: 1.8583 - val_mean_absolute_error: 1.8583
Epoch 727/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3562 - mean_absolute_error: 0.3562 - val_loss: 1.8252 - val_mean_absolute_error: 1.8252
Epoch 728/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2795 - mean_absolute_error: 0.2795 - val_loss: 1.7652 - val_mean_absolute_error: 1.7652
Epoch 729/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3236 - mean_absolute_error: 0.3236 - val_loss: 1.8918 - val_mean_absolute_error: 1.8918
Epoch 730/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3122 - mean_absolute_error: 0.3122 - val_loss: 1.9454 - val_mean_absolute_error: 1.9454
Epoch 731/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3225 - mean_absolute_error: 0.3225 - val_loss: 1.8605 - val_mean_absolute_error: 1.8605
Epoch 732/1000
11/11 [==============================] - 0s 33ms/step - loss: 0.3258 - mean_absolute_error: 0.3258 - val_loss: 1.8378 - val_mean_absolute_error: 1.8378
Epoch 733/1000
11/11 [==============================] - 0s 33ms/step - loss: 0.3674 - mean_absolute_error: 0.3674 - val_loss: 1.9075 - val_mean_absolute_error: 1.9075
Epoch 734/1000
11/11 [==============================] - 1s 52ms/step - loss: 0.3089 - mean_absolute_error: 0.3089 - val_loss: 1.8738 - val_mean_absolute_error: 1.8738
Epoch 735/1000
11/11 [==============================] - 1s 55ms/step - loss: 0.2896 - mean_absolute_error: 0.2896 - val_loss: 1.9250 - val_mean_absolute_error: 1.9250
Epoch 736/1000
11/11 [==============================] - 0s 37ms/step - loss: 0.3939 - mean_absolute_error: 0.3939 - val_loss: 1.8081 - val_mean_absolute_error: 1.8081
Epoch 737/1000
11/11 [==============================] - 0s 41ms/step - loss: 0.2726 - mean_absolute_error: 0.2726 - val_loss: 1.8491 - val_mean_absolute_error: 1.8491
Epoch 738/1000
11/11 [==============================] - 0s 33ms/step - loss: 0.3645 - mean_absolute_error: 0.3645 - val_loss: 1.8126 - val_mean_absolute_error: 1.8126
Epoch 739/1000
11/11 [==============================] - 0s 37ms/step - loss: 0.3171 - mean_absolute_error: 0.3171 - val_loss: 1.9739 - val_mean_absolute_error: 1.9739
Epoch 740/1000
11/11 [==============================] - 1s 68ms/step - loss: 0.4457 - mean_absolute_error: 0.4457 - val_loss: 2.0112 - val_mean_absolute_error: 2.0112
Epoch 741/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.3965 - mean_absolute_error: 0.3965 - val_loss: 1.8570 - val_mean_absolute_error: 1.8570
Epoch 742/1000
11/11 [==============================] - 0s 29ms/step - loss: 0.3415 - mean_absolute_error: 0.3415 - val_loss: 1.9501 - val_mean_absolute_error: 1.9501
Epoch 743/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4115 - mean_absolute_error: 0.4115 - val_loss: 1.8985 - val_mean_absolute_error: 1.8985
Epoch 744/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3469 - mean_absolute_error: 0.3469 - val_loss: 1.8292 - val_mean_absolute_error: 1.8292
Epoch 745/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3604 - mean_absolute_error: 0.3604 - val_loss: 1.8380 - val_mean_absolute_error: 1.8380
Epoch 746/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2840 - mean_absolute_error: 0.2840 - val_loss: 1.8080 - val_mean_absolute_error: 1.8080
Epoch 747/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3611 - mean_absolute_error: 0.3611 - val_loss: 1.9185 - val_mean_absolute_error: 1.9185
Epoch 748/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3983 - mean_absolute_error: 0.3983 - val_loss: 2.0016 - val_mean_absolute_error: 2.0016
Epoch 749/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4000 - mean_absolute_error: 0.4000 - val_loss: 1.8556 - val_mean_absolute_error: 1.8556
Epoch 750/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3206 - mean_absolute_error: 0.3206 - val_loss: 1.9349 - val_mean_absolute_error: 1.9349
Epoch 751/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3612 - mean_absolute_error: 0.3612 - val_loss: 1.8109 - val_mean_absolute_error: 1.8109
Epoch 752/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3283 - mean_absolute_error: 0.3283 - val_loss: 1.9304 - val_mean_absolute_error: 1.9304
Epoch 753/1000
11/11 [==============================] - 0s 24ms/step - loss: 0.3513 - mean_absolute_error: 0.3513 - val_loss: 1.7948 - val_mean_absolute_error: 1.7948
Epoch 754/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2473 - mean_absolute_error: 0.2473 - val_loss: 1.8076 - val_mean_absolute_error: 1.8076
Epoch 755/1000
11/11 [==============================] - 0s 24ms/step - loss: 0.2629 - mean_absolute_error: 0.2629 - val_loss: 1.8878 - val_mean_absolute_error: 1.8878
Epoch 756/1000
11/11 [==============================] - 0s 33ms/step - loss: 0.3288 - mean_absolute_error: 0.3288 - val_loss: 1.8047 - val_mean_absolute_error: 1.8047
Epoch 757/1000
11/11 [==============================] - 0s 25ms/step - loss: 0.3370 - mean_absolute_error: 0.3370 - val_loss: 1.8884 - val_mean_absolute_error: 1.8884
Epoch 758/1000
11/11 [==============================] - 0s 35ms/step - loss: 0.2780 - mean_absolute_error: 0.2780 - val_loss: 1.8339 - val_mean_absolute_error: 1.8339
Epoch 759/1000
11/11 [==============================] - 0s 32ms/step - loss: 0.3180 - mean_absolute_error: 0.3180 - val_loss: 1.8443 - val_mean_absolute_error: 1.8443
Epoch 760/1000

11/11 [==============================] - 0s 29ms/step - loss: 0.3722 - mean_absolute_error: 0.3722 - val_loss: 1.8820 - val_mean_absolute_error: 1.8820
Epoch 761/1000
11/11 [==============================] - 0s 31ms/step - loss: 0.3659 - mean_absolute_error: 0.3659 - val_loss: 1.8362 - val_mean_absolute_error: 1.8362
Epoch 762/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.3032 - mean_absolute_error: 0.3032 - val_loss: 1.9039 - val_mean_absolute_error: 1.9039
Epoch 763/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3075 - mean_absolute_error: 0.3075 - val_loss: 1.7918 - val_mean_absolute_error: 1.7918
Epoch 764/1000
11/11 [==============================] - 0s 45ms/step - loss: 0.3910 - mean_absolute_error: 0.3910 - val_loss: 1.8824 - val_mean_absolute_error: 1.8824
Epoch 765/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.3914 - mean_absolute_error: 0.3914 - val_loss: 1.9714 - val_mean_absolute_error: 1.9714
Epoch 766/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3306 - mean_absolute_error: 0.3306 - val_loss: 1.8207 - val_mean_absolute_error: 1.8207
Epoch 767/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2918 - mean_absolute_error: 0.2918 - val_loss: 1.7971 - val_mean_absolute_error: 1.7971
Epoch 768/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3324 - mean_absolute_error: 0.3324 - val_loss: 1.9718 - val_mean_absolute_error: 1.9718
Epoch 769/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3560 - mean_absolute_error: 0.3560 - val_loss: 1.7942 - val_mean_absolute_error: 1.7942
Epoch 770/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.2770 - mean_absolute_error: 0.2770 - val_loss: 1.8345 - val_mean_absolute_error: 1.8345
Epoch 771/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3375 - mean_absolute_error: 0.3375 - val_loss: 1.8433 - val_mean_absolute_error: 1.8433
Epoch 772/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3006 - mean_absolute_error: 0.3006 - val_loss: 1.9446 - val_mean_absolute_error: 1.9446
Epoch 773/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3181 - mean_absolute_error: 0.3181 - val_loss: 1.8150 - val_mean_absolute_error: 1.8150
Epoch 774/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2412 - mean_absolute_error: 0.2412 - val_loss: 1.8408 - val_mean_absolute_error: 1.8408
Epoch 775/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.2733 - mean_absolute_error: 0.2733 - val_loss: 1.9215 - val_mean_absolute_error: 1.9215
Epoch 776/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.3255 - mean_absolute_error: 0.3255 - val_loss: 1.8482 - val_mean_absolute_error: 1.8482
Epoch 777/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2920 - mean_absolute_error: 0.2920 - val_loss: 1.8224 - val_mean_absolute_error: 1.8224
Epoch 778/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2952 - mean_absolute_error: 0.2952 - val_loss: 1.8550 - val_mean_absolute_error: 1.8550
Epoch 779/1000
11/11 [==============================] - 0s 25ms/step - loss: 0.3213 - mean_absolute_error: 0.3213 - val_loss: 1.9329 - val_mean_absolute_error: 1.9329
Epoch 780/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3507 - mean_absolute_error: 0.3507 - val_loss: 1.8342 - val_mean_absolute_error: 1.8342
Epoch 781/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2827 - mean_absolute_error: 0.2827 - val_loss: 1.7942 - val_mean_absolute_error: 1.7942
Epoch 782/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2614 - mean_absolute_error: 0.2614 - val_loss: 1.8521 - val_mean_absolute_error: 1.8521
Epoch 783/1000
11/11 [==============================] - 1s 76ms/step - loss: 0.3214 - mean_absolute_error: 0.3214 - val_loss: 1.8197 - val_mean_absolute_error: 1.8197
Epoch 784/1000
11/11 [==============================] - 0s 31ms/step - loss: 0.3362 - mean_absolute_error: 0.3362 - val_loss: 1.8431 - val_mean_absolute_error: 1.8431
Epoch 785/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2624 - mean_absolute_error: 0.2624 - val_loss: 1.8639 - val_mean_absolute_error: 1.8639
Epoch 786/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3305 - mean_absolute_error: 0.3305 - val_loss: 1.8241 - val_mean_absolute_error: 1.8241
Epoch 787/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.3019 - mean_absolute_error: 0.3019 - val_loss: 1.8250 - val_mean_absolute_error: 1.8250
Epoch 788/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2599 - mean_absolute_error: 0.2599 - val_loss: 1.8221 - val_mean_absolute_error: 1.8221
Epoch 789/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.3551 - mean_absolute_error: 0.3551 - val_loss: 1.9197 - val_mean_absolute_error: 1.9197
Epoch 790/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.2875 - mean_absolute_error: 0.2875 - val_loss: 1.8195 - val_mean_absolute_error: 1.8195
Epoch 791/1000
11/11 [==============================] - 1s 65ms/step - loss: 0.2281 - mean_absolute_error: 0.2281 - val_loss: 1.8458 - val_mean_absolute_error: 1.8458
Epoch 792/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2322 - mean_absolute_error: 0.2322 - val_loss: 1.8613 - val_mean_absolute_error: 1.8613
Epoch 793/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2543 - mean_absolute_error: 0.2543 - val_loss: 1.8424 - val_mean_absolute_error: 1.8424
Epoch 794/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.2660 - mean_absolute_error: 0.2660 - val_loss: 1.8549 - val_mean_absolute_error: 1.8549
Epoch 795/1000
11/11 [==============================] - 0s 28ms/step - loss: 0.2729 - mean_absolute_error: 0.2729 - val_loss: 1.8584 - val_mean_absolute_error: 1.8584
Epoch 796/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.3329 - mean_absolute_error: 0.3329 - val_loss: 1.8404 - val_mean_absolute_error: 1.8404
Epoch 797/1000
11/11 [==============================] - 0s 27ms/step - loss: 0.3011 - mean_absolute_error: 0.3011 - val_loss: 1.8382 - val_mean_absolute_error: 1.8382
Epoch 798/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3695 - mean_absolute_error: 0.3695 - val_loss: 1.8135 - val_mean_absolute_error: 1.8135
Epoch 799/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.3123 - mean_absolute_error: 0.3123 - val_loss: 1.8805 - val_mean_absolute_error: 1.8805
Epoch 800/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2451 - mean_absolute_error: 0.2451 - val_loss: 1.8726 - val_mean_absolute_error: 1.8726
Epoch 801/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.2462 - mean_absolute_error: 0.2462 - val_loss: 1.7994 - val_mean_absolute_error: 1.7994
Epoch 802/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2924 - mean_absolute_error: 0.2924 - val_loss: 1.9014 - val_mean_absolute_error: 1.9014
Epoch 803/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.3055 - mean_absolute_error: 0.3055 - val_loss: 1.9428 - val_mean_absolute_error: 1.9428
Epoch 804/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3678 - mean_absolute_error: 0.3678 - val_loss: 1.7980 - val_mean_absolute_error: 1.7980
Epoch 805/1000
11/11 [==============================] - 0s 27ms/step - loss: 0.2726 - mean_absolute_error: 0.2726 - val_loss: 1.8330 - val_mean_absolute_error: 1.8330
Epoch 806/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2591 - mean_absolute_error: 0.2591 - val_loss: 1.8731 - val_mean_absolute_error: 1.8731
Epoch 807/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2416 - mean_absolute_error: 0.2416 - val_loss: 1.8003 - val_mean_absolute_error: 1.8003
Epoch 808/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3077 - mean_absolute_error: 0.3077 - val_loss: 1.8255 - val_mean_absolute_error: 1.8255
Epoch 809/1000

11/11 [==============================] - 0s 15ms/step - loss: 0.3094 - mean_absolute_error: 0.3094 - val_loss: 1.8890 - val_mean_absolute_error: 1.8890
Epoch 810/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2668 - mean_absolute_error: 0.2668 - val_loss: 1.9243 - val_mean_absolute_error: 1.9243
Epoch 811/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3678 - mean_absolute_error: 0.3678 - val_loss: 1.8242 - val_mean_absolute_error: 1.8242
Epoch 812/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5958 - mean_absolute_error: 0.5958 - val_loss: 2.0059 - val_mean_absolute_error: 2.0059
Epoch 813/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5655 - mean_absolute_error: 0.5655 - val_loss: 1.9629 - val_mean_absolute_error: 1.9629
Epoch 814/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3833 - mean_absolute_error: 0.3833 - val_loss: 1.7864 - val_mean_absolute_error: 1.7864
Epoch 815/1000
11/11 [==============================] - 0s 25ms/step - loss: 0.3758 - mean_absolute_error: 0.3758 - val_loss: 1.8158 - val_mean_absolute_error: 1.8158
Epoch 816/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2599 - mean_absolute_error: 0.2599 - val_loss: 1.8651 - val_mean_absolute_error: 1.8651
Epoch 817/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2982 - mean_absolute_error: 0.2982 - val_loss: 1.8357 - val_mean_absolute_error: 1.8357
Epoch 818/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2661 - mean_absolute_error: 0.2661 - val_loss: 1.8545 - val_mean_absolute_error: 1.8545
Epoch 819/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2901 - mean_absolute_error: 0.2901 - val_loss: 1.9036 - val_mean_absolute_error: 1.9036
Epoch 820/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.2809 - mean_absolute_error: 0.2809 - val_loss: 1.8610 - val_mean_absolute_error: 1.8610
Epoch 821/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2478 - mean_absolute_error: 0.2478 - val_loss: 1.8416 - val_mean_absolute_error: 1.8416
Epoch 822/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2279 - mean_absolute_error: 0.2279 - val_loss: 1.8428 - val_mean_absolute_error: 1.8428
Epoch 823/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2481 - mean_absolute_error: 0.2481 - val_loss: 1.8616 - val_mean_absolute_error: 1.8616
Epoch 824/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3081 - mean_absolute_error: 0.3081 - val_loss: 1.8585 - val_mean_absolute_error: 1.8585
Epoch 825/1000
11/11 [==============================] - 0s 25ms/step - loss: 0.2966 - mean_absolute_error: 0.2966 - val_loss: 1.8758 - val_mean_absolute_error: 1.8758
Epoch 826/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2841 - mean_absolute_error: 0.2841 - val_loss: 1.9136 - val_mean_absolute_error: 1.9136
Epoch 827/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.3517 - mean_absolute_error: 0.3517 - val_loss: 1.8673 - val_mean_absolute_error: 1.8673
Epoch 828/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2746 - mean_absolute_error: 0.2746 - val_loss: 1.8806 - val_mean_absolute_error: 1.8806
Epoch 829/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2340 - mean_absolute_error: 0.2340 - val_loss: 1.8188 - val_mean_absolute_error: 1.8188
Epoch 830/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2265 - mean_absolute_error: 0.2265 - val_loss: 1.8143 - val_mean_absolute_error: 1.8143
Epoch 831/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.2258 - mean_absolute_error: 0.2258 - val_loss: 1.8673 - val_mean_absolute_error: 1.8673
Epoch 832/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2544 - mean_absolute_error: 0.2544 - val_loss: 1.8756 - val_mean_absolute_error: 1.8756
Epoch 833/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.3223 - mean_absolute_error: 0.3223 - val_loss: 1.7826 - val_mean_absolute_error: 1.7826
Epoch 834/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3542 - mean_absolute_error: 0.3542 - val_loss: 1.8993 - val_mean_absolute_error: 1.8993
Epoch 835/1000
11/11 [==============================] - 1s 73ms/step - loss: 0.2720 - mean_absolute_error: 0.2720 - val_loss: 1.8647 - val_mean_absolute_error: 1.8647
Epoch 836/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2511 - mean_absolute_error: 0.2511 - val_loss: 1.8132 - val_mean_absolute_error: 1.8132
Epoch 837/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3504 - mean_absolute_error: 0.3504 - val_loss: 1.8270 - val_mean_absolute_error: 1.8270
Epoch 838/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2509 - mean_absolute_error: 0.2509 - val_loss: 1.8319 - val_mean_absolute_error: 1.8319
Epoch 839/1000
11/11 [==============================] - 0s 28ms/step - loss: 0.2771 - mean_absolute_error: 0.2771 - val_loss: 1.8501 - val_mean_absolute_error: 1.8501
Epoch 840/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2381 - mean_absolute_error: 0.2381 - val_loss: 1.8107 - val_mean_absolute_error: 1.8107
Epoch 841/1000
11/11 [==============================] - 0s 27ms/step - loss: 0.2562 - mean_absolute_error: 0.2562 - val_loss: 1.9098 - val_mean_absolute_error: 1.9098
Epoch 842/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.3807 - mean_absolute_error: 0.3807 - val_loss: 1.7908 - val_mean_absolute_error: 1.7908
Epoch 843/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.3325 - mean_absolute_error: 0.3325 - val_loss: 1.8422 - val_mean_absolute_error: 1.8422
Epoch 844/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.2944 - mean_absolute_error: 0.2944 - val_loss: 1.8100 - val_mean_absolute_error: 1.8100
Epoch 845/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2744 - mean_absolute_error: 0.2744 - val_loss: 1.8384 - val_mean_absolute_error: 1.8384
Epoch 846/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2481 - mean_absolute_error: 0.2481 - val_loss: 1.8963 - val_mean_absolute_error: 1.8963
Epoch 847/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.2592 - mean_absolute_error: 0.2592 - val_loss: 1.8826 - val_mean_absolute_error: 1.8826
Epoch 848/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2666 - mean_absolute_error: 0.2666 - val_loss: 1.7696 - val_mean_absolute_error: 1.7696
Epoch 849/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3109 - mean_absolute_error: 0.3109 - val_loss: 1.9494 - val_mean_absolute_error: 1.9494
Epoch 850/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3639 - mean_absolute_error: 0.3639 - val_loss: 1.8404 - val_mean_absolute_error: 1.8404
Epoch 851/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4044 - mean_absolute_error: 0.4044 - val_loss: 1.7714 - val_mean_absolute_error: 1.7714
Epoch 852/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3144 - mean_absolute_error: 0.3144 - val_loss: 1.8902 - val_mean_absolute_error: 1.8902
Epoch 853/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2873 - mean_absolute_error: 0.2873 - val_loss: 1.7640 - val_mean_absolute_error: 1.7640
Epoch 854/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3178 - mean_absolute_error: 0.3178 - val_loss: 1.9262 - val_mean_absolute_error: 1.9262
Epoch 855/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3115 - mean_absolute_error: 0.3115 - val_loss: 1.8190 - val_mean_absolute_error: 1.8190
Epoch 856/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2432 - mean_absolute_error: 0.2432 - val_loss: 1.7954 - val_mean_absolute_error: 1.7954
Epoch 857/1000
11/11 [==============================] - 0s 24ms/step - loss: 0.2711 - mean_absolute_error: 0.2711 - val_loss: 1.8209 - val_mean_absolute_error: 1.8209
Epoch 858/1000

11/11 [==============================] - 0s 15ms/step - loss: 0.2545 - mean_absolute_error: 0.2545 - val_loss: 1.8547 - val_mean_absolute_error: 1.8547
Epoch 859/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2818 - mean_absolute_error: 0.2818 - val_loss: 1.8022 - val_mean_absolute_error: 1.8022
Epoch 860/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2993 - mean_absolute_error: 0.2993 - val_loss: 1.8185 - val_mean_absolute_error: 1.8185
Epoch 861/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2809 - mean_absolute_error: 0.2809 - val_loss: 1.7967 - val_mean_absolute_error: 1.7967
Epoch 862/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2696 - mean_absolute_error: 0.2696 - val_loss: 1.9350 - val_mean_absolute_error: 1.9350
Epoch 863/1000
11/11 [==============================] - 1s 83ms/step - loss: 0.3425 - mean_absolute_error: 0.3425 - val_loss: 1.8215 - val_mean_absolute_error: 1.8215
Epoch 864/1000
11/11 [==============================] - 0s 34ms/step - loss: 0.2495 - mean_absolute_error: 0.2495 - val_loss: 1.8062 - val_mean_absolute_error: 1.8062
Epoch 865/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.2844 - mean_absolute_error: 0.2844 - val_loss: 1.8758 - val_mean_absolute_error: 1.8758
Epoch 866/1000
11/11 [==============================] - 1s 54ms/step - loss: 0.2649 - mean_absolute_error: 0.2649 - val_loss: 1.8877 - val_mean_absolute_error: 1.8877
Epoch 867/1000
11/11 [==============================] - 0s 31ms/step - loss: 0.2448 - mean_absolute_error: 0.2448 - val_loss: 1.8434 - val_mean_absolute_error: 1.8434
Epoch 868/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.2676 - mean_absolute_error: 0.2676 - val_loss: 1.8481 - val_mean_absolute_error: 1.8481
Epoch 869/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.3591 - mean_absolute_error: 0.3591 - val_loss: 1.8280 - val_mean_absolute_error: 1.8280
Epoch 870/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.4038 - mean_absolute_error: 0.4038 - val_loss: 1.8016 - val_mean_absolute_error: 1.8016
Epoch 871/1000
11/11 [==============================] - 0s 39ms/step - loss: 0.3119 - mean_absolute_error: 0.3119 - val_loss: 1.8793 - val_mean_absolute_error: 1.8793
Epoch 872/1000
11/11 [==============================] - 0s 38ms/step - loss: 0.2963 - mean_absolute_error: 0.2963 - val_loss: 1.8808 - val_mean_absolute_error: 1.8808
Epoch 873/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.2215 - mean_absolute_error: 0.2215 - val_loss: 1.8212 - val_mean_absolute_error: 1.8212
Epoch 874/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2441 - mean_absolute_error: 0.2441 - val_loss: 1.9109 - val_mean_absolute_error: 1.9109
Epoch 875/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2979 - mean_absolute_error: 0.2979 - val_loss: 1.8246 - val_mean_absolute_error: 1.8246
Epoch 876/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3022 - mean_absolute_error: 0.3022 - val_loss: 1.8031 - val_mean_absolute_error: 1.8031
Epoch 877/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2415 - mean_absolute_error: 0.2415 - val_loss: 1.8793 - val_mean_absolute_error: 1.8793
Epoch 878/1000
11/11 [==============================] - 0s 29ms/step - loss: 0.3055 - mean_absolute_error: 0.3055 - val_loss: 1.8497 - val_mean_absolute_error: 1.8497
Epoch 879/1000
11/11 [==============================] - 0s 31ms/step - loss: 0.2749 - mean_absolute_error: 0.2749 - val_loss: 1.7729 - val_mean_absolute_error: 1.7729
Epoch 880/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2364 - mean_absolute_error: 0.2364 - val_loss: 1.9316 - val_mean_absolute_error: 1.9316
Epoch 881/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.3006 - mean_absolute_error: 0.3006 - val_loss: 1.8005 - val_mean_absolute_error: 1.8005
Epoch 882/1000
11/11 [==============================] - 0s 27ms/step - loss: 0.2907 - mean_absolute_error: 0.2907 - val_loss: 1.8478 - val_mean_absolute_error: 1.8478
Epoch 883/1000
11/11 [==============================] - 0s 37ms/step - loss: 0.3458 - mean_absolute_error: 0.3458 - val_loss: 1.7924 - val_mean_absolute_error: 1.7924
Epoch 884/1000
11/11 [==============================] - 0s 35ms/step - loss: 0.3245 - mean_absolute_error: 0.3245 - val_loss: 1.8419 - val_mean_absolute_error: 1.8419
Epoch 885/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3305 - mean_absolute_error: 0.3305 - val_loss: 1.8899 - val_mean_absolute_error: 1.8899
Epoch 886/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2552 - mean_absolute_error: 0.2552 - val_loss: 1.8682 - val_mean_absolute_error: 1.8682
Epoch 887/1000
11/11 [==============================] - 1s 69ms/step - loss: 0.2258 - mean_absolute_error: 0.2258 - val_loss: 1.8710 - val_mean_absolute_error: 1.8710
Epoch 888/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2557 - mean_absolute_error: 0.2557 - val_loss: 1.8192 - val_mean_absolute_error: 1.8192
Epoch 889/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3611 - mean_absolute_error: 0.3611 - val_loss: 1.8757 - val_mean_absolute_error: 1.8757
Epoch 890/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2676 - mean_absolute_error: 0.2676 - val_loss: 1.8578 - val_mean_absolute_error: 1.8578
Epoch 891/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2332 - mean_absolute_error: 0.2332 - val_loss: 1.8011 - val_mean_absolute_error: 1.8011
Epoch 892/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2377 - mean_absolute_error: 0.2377 - val_loss: 1.8615 - val_mean_absolute_error: 1.8615
Epoch 893/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2434 - mean_absolute_error: 0.2434 - val_loss: 1.8811 - val_mean_absolute_error: 1.8811
Epoch 894/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2412 - mean_absolute_error: 0.2412 - val_loss: 1.8496 - val_mean_absolute_error: 1.8496
Epoch 895/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.2256 - mean_absolute_error: 0.2256 - val_loss: 1.8116 - val_mean_absolute_error: 1.8116
Epoch 896/1000
11/11 [==============================] - 0s 34ms/step - loss: 0.2519 - mean_absolute_error: 0.2519 - val_loss: 1.8499 - val_mean_absolute_error: 1.8499
Epoch 897/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2577 - mean_absolute_error: 0.2577 - val_loss: 1.8319 - val_mean_absolute_error: 1.8319
Epoch 898/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2888 - mean_absolute_error: 0.2888 - val_loss: 1.8473 - val_mean_absolute_error: 1.8473
Epoch 899/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2490 - mean_absolute_error: 0.2490 - val_loss: 1.8287 - val_mean_absolute_error: 1.8287
Epoch 900/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2257 - mean_absolute_error: 0.2257 - val_loss: 1.8479 - val_mean_absolute_error: 1.8479
Epoch 901/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2785 - mean_absolute_error: 0.2785 - val_loss: 1.9383 - val_mean_absolute_error: 1.9383
Epoch 902/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3568 - mean_absolute_error: 0.3568 - val_loss: 1.8209 - val_mean_absolute_error: 1.8209
Epoch 903/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2427 - mean_absolute_error: 0.2427 - val_loss: 1.8009 - val_mean_absolute_error: 1.8009
Epoch 904/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2553 - mean_absolute_error: 0.2553 - val_loss: 1.8249 - val_mean_absolute_error: 1.8249
Epoch 905/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2504 - mean_absolute_error: 0.2504 - val_loss: 1.8090 - val_mean_absolute_error: 1.8090
Epoch 906/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2441 - mean_absolute_error: 0.2441 - val_loss: 1.7880 - val_mean_absolute_error: 1.7880
Epoch 907/1000

11/11 [==============================] - 0s 28ms/step - loss: 0.2540 - mean_absolute_error: 0.2540 - val_loss: 1.8184 - val_mean_absolute_error: 1.8184
Epoch 908/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.2353 - mean_absolute_error: 0.2353 - val_loss: 1.7805 - val_mean_absolute_error: 1.7805
Epoch 909/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.3181 - mean_absolute_error: 0.3181 - val_loss: 1.9106 - val_mean_absolute_error: 1.9106
Epoch 910/1000
11/11 [==============================] - 0s 31ms/step - loss: 0.2721 - mean_absolute_error: 0.2721 - val_loss: 1.8694 - val_mean_absolute_error: 1.8694
Epoch 911/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.2718 - mean_absolute_error: 0.2718 - val_loss: 1.9215 - val_mean_absolute_error: 1.9215
Epoch 912/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2612 - mean_absolute_error: 0.2612 - val_loss: 1.8550 - val_mean_absolute_error: 1.8550
Epoch 913/1000
11/11 [==============================] - 0s 31ms/step - loss: 0.2491 - mean_absolute_error: 0.2491 - val_loss: 1.8943 - val_mean_absolute_error: 1.8943
Epoch 914/1000
11/11 [==============================] - 0s 27ms/step - loss: 0.2811 - mean_absolute_error: 0.2811 - val_loss: 1.8761 - val_mean_absolute_error: 1.8761
Epoch 915/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.3290 - mean_absolute_error: 0.3290 - val_loss: 1.8673 - val_mean_absolute_error: 1.8673
Epoch 916/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2587 - mean_absolute_error: 0.2587 - val_loss: 1.8354 - val_mean_absolute_error: 1.8354
Epoch 917/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2564 - mean_absolute_error: 0.2564 - val_loss: 1.8807 - val_mean_absolute_error: 1.8807
Epoch 918/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.2738 - mean_absolute_error: 0.2738 - val_loss: 1.8573 - val_mean_absolute_error: 1.8573
Epoch 919/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2742 - mean_absolute_error: 0.2742 - val_loss: 1.8598 - val_mean_absolute_error: 1.8598
Epoch 920/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2652 - mean_absolute_error: 0.2652 - val_loss: 1.7997 - val_mean_absolute_error: 1.7997
Epoch 921/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2284 - mean_absolute_error: 0.2284 - val_loss: 1.8002 - val_mean_absolute_error: 1.8002
Epoch 922/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2828 - mean_absolute_error: 0.2828 - val_loss: 1.9062 - val_mean_absolute_error: 1.9062
Epoch 923/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3066 - mean_absolute_error: 0.3066 - val_loss: 1.8050 - val_mean_absolute_error: 1.8050
Epoch 924/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3013 - mean_absolute_error: 0.3013 - val_loss: 1.8750 - val_mean_absolute_error: 1.8750
Epoch 925/1000
11/11 [==============================] - 0s 21ms/step - loss: 0.2437 - mean_absolute_error: 0.2437 - val_loss: 1.8408 - val_mean_absolute_error: 1.8408
Epoch 926/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2545 - mean_absolute_error: 0.2545 - val_loss: 1.7849 - val_mean_absolute_error: 1.7849
Epoch 927/1000
11/11 [==============================] - 0s 27ms/step - loss: 0.2836 - mean_absolute_error: 0.2836 - val_loss: 1.8595 - val_mean_absolute_error: 1.8595
Epoch 928/1000
11/11 [==============================] - 0s 33ms/step - loss: 0.2642 - mean_absolute_error: 0.2642 - val_loss: 1.8476 - val_mean_absolute_error: 1.8476
Epoch 929/1000
11/11 [==============================] - 1s 56ms/step - loss: 0.2930 - mean_absolute_error: 0.2930 - val_loss: 1.8835 - val_mean_absolute_error: 1.8835
Epoch 930/1000
11/11 [==============================] - 1s 64ms/step - loss: 0.3549 - mean_absolute_error: 0.3549 - val_loss: 1.8737 - val_mean_absolute_error: 1.8737
Epoch 931/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.3801 - mean_absolute_error: 0.3801 - val_loss: 1.8235 - val_mean_absolute_error: 1.8235
Epoch 932/1000
11/11 [==============================] - 0s 44ms/step - loss: 0.2333 - mean_absolute_error: 0.2333 - val_loss: 1.8190 - val_mean_absolute_error: 1.8190
Epoch 933/1000
11/11 [==============================] - 0s 37ms/step - loss: 0.2557 - mean_absolute_error: 0.2557 - val_loss: 1.8467 - val_mean_absolute_error: 1.8467
Epoch 934/1000
11/11 [==============================] - 0s 37ms/step - loss: 0.2222 - mean_absolute_error: 0.2222 - val_loss: 1.8121 - val_mean_absolute_error: 1.8121
Epoch 935/1000
11/11 [==============================] - 1s 69ms/step - loss: 0.2254 - mean_absolute_error: 0.2254 - val_loss: 1.8341 - val_mean_absolute_error: 1.8341
Epoch 936/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2072 - mean_absolute_error: 0.2072 - val_loss: 1.8390 - val_mean_absolute_error: 1.8390
Epoch 937/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.2619 - mean_absolute_error: 0.2619 - val_loss: 1.9729 - val_mean_absolute_error: 1.9729
Epoch 938/1000
11/11 [==============================] - 0s 26ms/step - loss: 0.4055 - mean_absolute_error: 0.4055 - val_loss: 1.8882 - val_mean_absolute_error: 1.8882
Epoch 939/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2429 - mean_absolute_error: 0.2429 - val_loss: 1.8896 - val_mean_absolute_error: 1.8896
Epoch 940/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3088 - mean_absolute_error: 0.3088 - val_loss: 1.8072 - val_mean_absolute_error: 1.8072
Epoch 941/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3661 - mean_absolute_error: 0.3661 - val_loss: 1.9039 - val_mean_absolute_error: 1.9039
Epoch 942/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2988 - mean_absolute_error: 0.2988 - val_loss: 1.8199 - val_mean_absolute_error: 1.8199
Epoch 943/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2483 - mean_absolute_error: 0.2483 - val_loss: 1.8494 - val_mean_absolute_error: 1.8494
Epoch 944/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.2711 - mean_absolute_error: 0.2711 - val_loss: 1.8651 - val_mean_absolute_error: 1.8651
Epoch 945/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2683 - mean_absolute_error: 0.2683 - val_loss: 1.8472 - val_mean_absolute_error: 1.8472
Epoch 946/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2473 - mean_absolute_error: 0.2473 - val_loss: 1.8398 - val_mean_absolute_error: 1.8398
Epoch 947/1000
11/11 [==============================] - 1s 77ms/step - loss: 0.2482 - mean_absolute_error: 0.2482 - val_loss: 1.8712 - val_mean_absolute_error: 1.8712
Epoch 948/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2434 - mean_absolute_error: 0.2434 - val_loss: 1.8747 - val_mean_absolute_error: 1.8747
Epoch 949/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2779 - mean_absolute_error: 0.2779 - val_loss: 1.7930 - val_mean_absolute_error: 1.7930
Epoch 950/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2538 - mean_absolute_error: 0.2538 - val_loss: 1.8503 - val_mean_absolute_error: 1.8503
Epoch 951/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2517 - mean_absolute_error: 0.2517 - val_loss: 1.8589 - val_mean_absolute_error: 1.8589
Epoch 952/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2099 - mean_absolute_error: 0.2099 - val_loss: 1.8029 - val_mean_absolute_error: 1.8029
Epoch 953/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3208 - mean_absolute_error: 0.3208 - val_loss: 1.9169 - val_mean_absolute_error: 1.9169
Epoch 954/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3727 - mean_absolute_error: 0.3727 - val_loss: 1.8042 - val_mean_absolute_error: 1.8042
Epoch 955/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4316 - mean_absolute_error: 0.4316 - val_loss: 1.7408 - val_mean_absolute_error: 1.7408
Epoch 956/1000

11/11 [==============================] - 0s 16ms/step - loss: 0.3484 - mean_absolute_error: 0.3484 - val_loss: 1.9038 - val_mean_absolute_error: 1.9038
Epoch 957/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2917 - mean_absolute_error: 0.2917 - val_loss: 1.8990 - val_mean_absolute_error: 1.8990
Epoch 958/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2687 - mean_absolute_error: 0.2687 - val_loss: 1.8649 - val_mean_absolute_error: 1.8649
Epoch 959/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2536 - mean_absolute_error: 0.2536 - val_loss: 1.8057 - val_mean_absolute_error: 1.8057
Epoch 960/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2746 - mean_absolute_error: 0.2746 - val_loss: 1.9585 - val_mean_absolute_error: 1.9585
Epoch 961/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.2997 - mean_absolute_error: 0.2997 - val_loss: 1.8350 - val_mean_absolute_error: 1.8350
Epoch 962/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3298 - mean_absolute_error: 0.3298 - val_loss: 1.8916 - val_mean_absolute_error: 1.8916
Epoch 963/1000
11/11 [==============================] - 0s 39ms/step - loss: 0.2909 - mean_absolute_error: 0.2909 - val_loss: 1.8260 - val_mean_absolute_error: 1.8260
Epoch 964/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2639 - mean_absolute_error: 0.2639 - val_loss: 1.8692 - val_mean_absolute_error: 1.8692
Epoch 965/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2861 - mean_absolute_error: 0.2861 - val_loss: 1.8555 - val_mean_absolute_error: 1.8555
Epoch 966/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2452 - mean_absolute_error: 0.2452 - val_loss: 1.8704 - val_mean_absolute_error: 1.8704
Epoch 967/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.2995 - mean_absolute_error: 0.2995 - val_loss: 1.8892 - val_mean_absolute_error: 1.8892
Epoch 968/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.2765 - mean_absolute_error: 0.2765 - val_loss: 1.8505 - val_mean_absolute_error: 1.8505
Epoch 969/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2493 - mean_absolute_error: 0.2493 - val_loss: 1.8294 - val_mean_absolute_error: 1.8294
Epoch 970/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2551 - mean_absolute_error: 0.2551 - val_loss: 1.8787 - val_mean_absolute_error: 1.8787
Epoch 971/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2360 - mean_absolute_error: 0.2360 - val_loss: 1.9346 - val_mean_absolute_error: 1.9346
Epoch 972/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3087 - mean_absolute_error: 0.3087 - val_loss: 1.7980 - val_mean_absolute_error: 1.7980
Epoch 973/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2841 - mean_absolute_error: 0.2841 - val_loss: 1.8417 - val_mean_absolute_error: 1.8417
Epoch 974/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2098 - mean_absolute_error: 0.2098 - val_loss: 1.8652 - val_mean_absolute_error: 1.8652
Epoch 975/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2087 - mean_absolute_error: 0.2087 - val_loss: 1.8303 - val_mean_absolute_error: 1.8303
Epoch 976/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2202 - mean_absolute_error: 0.2202 - val_loss: 1.8057 - val_mean_absolute_error: 1.8057
Epoch 977/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2052 - mean_absolute_error: 0.2052 - val_loss: 1.9070 - val_mean_absolute_error: 1.9070
Epoch 978/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2659 - mean_absolute_error: 0.2659 - val_loss: 1.8623 - val_mean_absolute_error: 1.8623
Epoch 979/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2642 - mean_absolute_error: 0.2642 - val_loss: 1.8171 - val_mean_absolute_error: 1.8171
Epoch 980/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3550 - mean_absolute_error: 0.3550 - val_loss: 1.8777 - val_mean_absolute_error: 1.8777
Epoch 981/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2761 - mean_absolute_error: 0.2761 - val_loss: 1.8624 - val_mean_absolute_error: 1.8624
Epoch 982/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2338 - mean_absolute_error: 0.2338 - val_loss: 1.8235 - val_mean_absolute_error: 1.8235
Epoch 983/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2412 - mean_absolute_error: 0.2412 - val_loss: 1.8558 - val_mean_absolute_error: 1.8558
Epoch 984/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2567 - mean_absolute_error: 0.2567 - val_loss: 1.8082 - val_mean_absolute_error: 1.8082
Epoch 985/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2237 - mean_absolute_error: 0.2237 - val_loss: 1.8330 - val_mean_absolute_error: 1.8330
Epoch 986/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2229 - mean_absolute_error: 0.2229 - val_loss: 1.8572 - val_mean_absolute_error: 1.8572
Epoch 987/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2869 - mean_absolute_error: 0.2869 - val_loss: 1.9094 - val_mean_absolute_error: 1.9094
Epoch 988/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.2244 - mean_absolute_error: 0.2244 - val_loss: 1.8008 - val_mean_absolute_error: 1.8008
Epoch 989/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.2229 - mean_absolute_error: 0.2229 - val_loss: 1.8058 - val_mean_absolute_error: 1.8058
Epoch 990/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2160 - mean_absolute_error: 0.2160 - val_loss: 1.8227 - val_mean_absolute_error: 1.8227
Epoch 991/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2121 - mean_absolute_error: 0.2121 - val_loss: 1.8893 - val_mean_absolute_error: 1.8893
Epoch 992/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2372 - mean_absolute_error: 0.2372 - val_loss: 1.8740 - val_mean_absolute_error: 1.8740
Epoch 993/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2262 - mean_absolute_error: 0.2262 - val_loss: 1.8875 - val_mean_absolute_error: 1.8875
Epoch 994/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.2441 - mean_absolute_error: 0.2441 - val_loss: 1.9034 - val_mean_absolute_error: 1.9034
Epoch 995/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2548 - mean_absolute_error: 0.2548 - val_loss: 1.8245 - val_mean_absolute_error: 1.8245
Epoch 996/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2805 - mean_absolute_error: 0.2805 - val_loss: 1.8658 - val_mean_absolute_error: 1.8658
Epoch 997/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.2129 - mean_absolute_error: 0.2129 - val_loss: 1.8537 - val_mean_absolute_error: 1.8537
Epoch 998/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.2619 - mean_absolute_error: 0.2619 - val_loss: 1.9906 - val_mean_absolute_error: 1.9906
Epoch 999/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3738 - mean_absolute_error: 0.3738 - val_loss: 1.8922 - val_mean_absolute_error: 1.8922
Epoch 1000/1000
11/11 [==============================] - 0s 28ms/step - loss: 0.3105 - mean_absolute_error: 0.3105 - val_loss: 1.8391 - val_mean_absolute_error: 1.8391
32/32 [==============================] - 0s 3ms/step

,iter,Model,ACC,AFS,MAE,RMSE,RMSE2,50th%error,75th%error,95th%error,avg_le
0,0,MC-ACNNR_dual,1.0,2.499237,2.499237,2.539453,4.460683,2.097947,3.446978,4.812274,4.09471

Model: "model_2"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to
==================================================================================================
 input_5 (InputLayer)           [(None, 23, 1)]      0           []

 input_6 (InputLayer)           [(None, 23, 1)]      0           []

 conv1d_12 (Conv1D)             (None, 23, 32)       128         ['input_5[0][0]']

 conv1d_14 (Conv1D)             (None, 23, 32)       128         ['input_6[0][0]']

 conv1d_13 (Conv1D)             (None, 23, 32)       3104        ['conv1d_12[0][0]']

 conv1d_15 (Conv1D)             (None, 23, 32)       3104        ['conv1d_14[0][0]']

 concatenate_4 (Concatenate)    (None, 23, 64)       0           ['conv1d_13[0][0]',
                                                                  'conv1d_15[0][0]']

 conv1d_16 (Conv1D)             (None, 23, 32)       6176        ['concatenate_4[0][0]']

 conv1d_17 (Conv1D)             (None, 23, 32)       3104        ['conv1d_16[0][0]']

 max_pooling1d_2 (MaxPooling1D)  (None, 11, 32)      0           ['conv1d_17[0][0]']

 attention_4 (attention)        (None, 32)           55          ['conv1d_13[0][0]']

 flatten_2 (Flatten)            (None, 352)          0           ['max_pooling1d_2[0][0]']

 attention_5 (attention)        (None, 32)           55          ['conv1d_15[0][0]']

 concatenate_5 (Concatenate)    (None, 416)          0           ['attention_4[0][0]',
                                                                  'flatten_2[0][0]',
                                                                  'attention_5[0][0]']

 dense_15 (Dense)               (None, 256)          106752      ['concatenate_5[0][0]']

 dense_16 (Dense)               (None, 128)          32896       ['dense_15[0][0]']

 dense_17 (Dense)               (None, 3)            387         ['dense_16[0][0]']

==================================================================================================
Total params: 155,889
Trainable params: 155,889
Non-trainable params: 0
__________________________________________________________________________________________________
None
Epoch 1/1000
11/11 [==============================] - 2s 52ms/step - loss: 20.1687 - mean_absolute_error: 20.1687 - val_loss: 16.2263 - val_mean_absolute_error: 16.2263
Epoch 2/1000
11/11 [==============================] - 0s 23ms/step - loss: 13.0875 - mean_absolute_error: 13.0875 - val_loss: 10.0871 - val_mean_absolute_error: 10.0871
Epoch 3/1000
11/11 [==============================] - 0s 20ms/step - loss: 9.3772 - mean_absolute_error: 9.3772 - val_loss: 8.3077 - val_mean_absolute_error: 8.3077
Epoch 4/1000
11/11 [==============================] - 0s 25ms/step - loss: 8.2939 - mean_absolute_error: 8.2939 - val_loss: 7.5979 - val_mean_absolute_error: 7.5979
Epoch 5/1000
11/11 [==============================] - 0s 19ms/step - loss: 7.4435 - mean_absolute_error: 7.4435 - val_loss: 6.8659 - val_mean_absolute_error: 6.8659
Epoch 6/1000
11/11 [==============================] - 0s 21ms/step - loss: 6.7582 - mean_absolute_error: 6.7582 - val_loss: 6.4614 - val_mean_absolute_error: 6.4614
Epoch 7/1000
11/11 [==============================] - 0s 20ms/step - loss: 6.0340 - mean_absolute_error: 6.0340 - val_loss: 5.7165 - val_mean_absolute_error: 5.7165
Epoch 8/1000
11/11 [==============================] - 0s 20ms/step - loss: 5.2348 - mean_absolute_error: 5.2348 - val_loss: 5.3151 - val_mean_absolute_error: 5.3151
Epoch 9/1000
11/11 [==============================] - 0s 19ms/step - loss: 4.3383 - mean_absolute_error: 4.3383 - val_loss: 4.4706 - val_mean_absolute_error: 4.4706
Epoch 10/1000
11/11 [==============================] - 0s 20ms/step - loss: 3.7686 - mean_absolute_error: 3.7686 - val_loss: 3.9068 - val_mean_absolute_error: 3.9068
Epoch 11/1000
11/11 [==============================] - 0s 20ms/step - loss: 3.5699 - mean_absolute_error: 3.5699 - val_loss: 3.7472 - val_mean_absolute_error: 3.7472
Epoch 12/1000
11/11 [==============================] - 0s 20ms/step - loss: 3.1637 - mean_absolute_error: 3.1637 - val_loss: 3.2613 - val_mean_absolute_error: 3.2613
Epoch 13/1000
11/11 [==============================] - 0s 15ms/step - loss: 2.9562 - mean_absolute_error: 2.9562 - val_loss: 3.3014 - val_mean_absolute_error: 3.3014
Epoch 14/1000
11/11 [==============================] - 0s 21ms/step - loss: 2.7285 - mean_absolute_error: 2.7285 - val_loss: 3.1197 - val_mean_absolute_error: 3.1197
Epoch 15/1000
11/11 [==============================] - 0s 23ms/step - loss: 2.6485 - mean_absolute_error: 2.6485 - val_loss: 3.0000 - val_mean_absolute_error: 3.0000
Epoch 16/1000
11/11 [==============================] - 0s 16ms/step - loss: 2.5753 - mean_absolute_error: 2.5753 - val_loss: 3.1548 - val_mean_absolute_error: 3.1548
Epoch 17/1000
11/11 [==============================] - 0s 19ms/step - loss: 2.4334 - mean_absolute_error: 2.4334 - val_loss: 3.1133 - val_mean_absolute_error: 3.1133
Epoch 18/1000
11/11 [==============================] - 0s 20ms/step - loss: 2.3492 - mean_absolute_error: 2.3492 - val_loss: 2.6632 - val_mean_absolute_error: 2.6632
Epoch 19/1000
11/11 [==============================] - 0s 20ms/step - loss: 2.3044 - mean_absolute_error: 2.3044 - val_loss: 3.0830 - val_mean_absolute_error: 3.0830
Epoch 20/1000
11/11 [==============================] - 0s 24ms/step - loss: 2.2945 - mean_absolute_error: 2.2945 - val_loss: 2.5648 - val_mean_absolute_error: 2.5648
Epoch 21/1000
11/11 [==============================] - 0s 16ms/step - loss: 2.2096 - mean_absolute_error: 2.2096 - val_loss: 2.5745 - val_mean_absolute_error: 2.5745
Epoch 22/1000
11/11 [==============================] - 0s 16ms/step - loss: 2.1769 - mean_absolute_error: 2.1769 - val_loss: 2.6840 - val_mean_absolute_error: 2.6840
Epoch 23/1000
11/11 [==============================] - 0s 20ms/step - loss: 2.0871 - mean_absolute_error: 2.0871 - val_loss: 2.5038 - val_mean_absolute_error: 2.5038
Epoch 24/1000
11/11 [==============================] - 0s 19ms/step - loss: 2.0964 - mean_absolute_error: 2.0964 - val_loss: 2.5785 - val_mean_absolute_error: 2.5785

Epoch 25/1000
11/11 [==============================] - 0s 21ms/step - loss: 2.1527 - mean_absolute_error: 2.1527 - val_loss: 2.4905 - val_mean_absolute_error: 2.4905
Epoch 26/1000
11/11 [==============================] - 0s 16ms/step - loss: 2.1560 - mean_absolute_error: 2.1560 - val_loss: 3.1563 - val_mean_absolute_error: 3.1563
Epoch 27/1000
11/11 [==============================] - 0s 18ms/step - loss: 2.2322 - mean_absolute_error: 2.2322 - val_loss: 2.5904 - val_mean_absolute_error: 2.5904
Epoch 28/1000
11/11 [==============================] - 0s 20ms/step - loss: 2.1367 - mean_absolute_error: 2.1367 - val_loss: 2.4710 - val_mean_absolute_error: 2.4710
Epoch 29/1000
11/11 [==============================] - 0s 21ms/step - loss: 1.9655 - mean_absolute_error: 1.9655 - val_loss: 2.4487 - val_mean_absolute_error: 2.4487
Epoch 30/1000
11/11 [==============================] - 0s 15ms/step - loss: 1.9625 - mean_absolute_error: 1.9625 - val_loss: 2.5314 - val_mean_absolute_error: 2.5314
Epoch 31/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.8928 - mean_absolute_error: 1.8928 - val_loss: 2.9503 - val_mean_absolute_error: 2.9503
Epoch 32/1000
11/11 [==============================] - 0s 20ms/step - loss: 2.0722 - mean_absolute_error: 2.0722 - val_loss: 2.4215 - val_mean_absolute_error: 2.4215
Epoch 33/1000
11/11 [==============================] - 0s 27ms/step - loss: 1.9208 - mean_absolute_error: 1.9208 - val_loss: 2.3355 - val_mean_absolute_error: 2.3355
Epoch 34/1000
11/11 [==============================] - 0s 20ms/step - loss: 1.9127 - mean_absolute_error: 1.9127 - val_loss: 2.2890 - val_mean_absolute_error: 2.2890
Epoch 35/1000
11/11 [==============================] - 0s 16ms/step - loss: 2.0001 - mean_absolute_error: 2.0001 - val_loss: 2.3073 - val_mean_absolute_error: 2.3073
Epoch 36/1000
11/11 [==============================] - 0s 15ms/step - loss: 2.0197 - mean_absolute_error: 2.0197 - val_loss: 2.5498 - val_mean_absolute_error: 2.5498
Epoch 37/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.8039 - mean_absolute_error: 1.8039 - val_loss: 2.4727 - val_mean_absolute_error: 2.4727
Epoch 38/1000
11/11 [==============================] - 0s 15ms/step - loss: 1.7579 - mean_absolute_error: 1.7579 - val_loss: 2.4484 - val_mean_absolute_error: 2.4484
Epoch 39/1000
11/11 [==============================] - 0s 20ms/step - loss: 1.7807 - mean_absolute_error: 1.7807 - val_loss: 2.2655 - val_mean_absolute_error: 2.2655
Epoch 40/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.7920 - mean_absolute_error: 1.7920 - val_loss: 2.6324 - val_mean_absolute_error: 2.6324
Epoch 41/1000
11/11 [==============================] - 0s 15ms/step - loss: 1.8004 - mean_absolute_error: 1.8004 - val_loss: 2.2740 - val_mean_absolute_error: 2.2740
Epoch 42/1000
11/11 [==============================] - 0s 23ms/step - loss: 1.7279 - mean_absolute_error: 1.7279 - val_loss: 2.3475 - val_mean_absolute_error: 2.3475
Epoch 43/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.7075 - mean_absolute_error: 1.7075 - val_loss: 2.3512 - val_mean_absolute_error: 2.3512
Epoch 44/1000
11/11 [==============================] - 0s 19ms/step - loss: 1.6859 - mean_absolute_error: 1.6859 - val_loss: 2.3391 - val_mean_absolute_error: 2.3391
Epoch 45/1000
11/11 [==============================] - 0s 19ms/step - loss: 1.7142 - mean_absolute_error: 1.7142 - val_loss: 2.2820 - val_mean_absolute_error: 2.2820
Epoch 46/1000
11/11 [==============================] - 0s 24ms/step - loss: 1.9434 - mean_absolute_error: 1.9434 - val_loss: 2.2299 - val_mean_absolute_error: 2.2299
Epoch 47/1000
11/11 [==============================] - 0s 15ms/step - loss: 1.8291 - mean_absolute_error: 1.8291 - val_loss: 2.5359 - val_mean_absolute_error: 2.5359
Epoch 48/1000
11/11 [==============================] - 0s 19ms/step - loss: 1.6330 - mean_absolute_error: 1.6330 - val_loss: 2.6755 - val_mean_absolute_error: 2.6755
Epoch 49/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.6921 - mean_absolute_error: 1.6921 - val_loss: 2.5194 - val_mean_absolute_error: 2.5194
Epoch 50/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.6051 - mean_absolute_error: 1.6051 - val_loss: 2.4243 - val_mean_absolute_error: 2.4243
Epoch 51/1000
11/11 [==============================] - 0s 21ms/step - loss: 1.5931 - mean_absolute_error: 1.5931 - val_loss: 2.2199 - val_mean_absolute_error: 2.2199
Epoch 52/1000
11/11 [==============================] - 0s 15ms/step - loss: 1.5766 - mean_absolute_error: 1.5766 - val_loss: 2.2966 - val_mean_absolute_error: 2.2966
Epoch 53/1000
11/11 [==============================] - 0s 15ms/step - loss: 1.6229 - mean_absolute_error: 1.6229 - val_loss: 2.2321 - val_mean_absolute_error: 2.2321
Epoch 54/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.5556 - mean_absolute_error: 1.5556 - val_loss: 2.3030 - val_mean_absolute_error: 2.3030
Epoch 55/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.5640 - mean_absolute_error: 1.5640 - val_loss: 2.8029 - val_mean_absolute_error: 2.8029
Epoch 56/1000
11/11 [==============================] - 0s 19ms/step - loss: 1.8296 - mean_absolute_error: 1.8296 - val_loss: 2.2192 - val_mean_absolute_error: 2.2192
Epoch 57/1000
11/11 [==============================] - 0s 20ms/step - loss: 1.6263 - mean_absolute_error: 1.6263 - val_loss: 2.1371 - val_mean_absolute_error: 2.1371
Epoch 58/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.5023 - mean_absolute_error: 1.5023 - val_loss: 2.1697 - val_mean_absolute_error: 2.1697
Epoch 59/1000
11/11 [==============================] - 0s 15ms/step - loss: 1.5379 - mean_absolute_error: 1.5379 - val_loss: 2.1921 - val_mean_absolute_error: 2.1921
Epoch 60/1000
11/11 [==============================] - 0s 20ms/step - loss: 1.5711 - mean_absolute_error: 1.5711 - val_loss: 2.2757 - val_mean_absolute_error: 2.2757
Epoch 61/1000
11/11 [==============================] - 0s 24ms/step - loss: 1.5329 - mean_absolute_error: 1.5329 - val_loss: 2.4479 - val_mean_absolute_error: 2.4479
Epoch 62/1000
11/11 [==============================] - 0s 20ms/step - loss: 1.5153 - mean_absolute_error: 1.5153 - val_loss: 2.3467 - val_mean_absolute_error: 2.3467
Epoch 63/1000
11/11 [==============================] - 0s 21ms/step - loss: 1.4961 - mean_absolute_error: 1.4961 - val_loss: 2.1840 - val_mean_absolute_error: 2.1840
Epoch 64/1000
11/11 [==============================] - 0s 31ms/step - loss: 1.4512 - mean_absolute_error: 1.4512 - val_loss: 2.0554 - val_mean_absolute_error: 2.0554
Epoch 65/1000
11/11 [==============================] - 0s 40ms/step - loss: 1.5680 - mean_absolute_error: 1.5680 - val_loss: 2.1147 - val_mean_absolute_error: 2.1147
Epoch 66/1000
11/11 [==============================] - 0s 25ms/step - loss: 1.3915 - mean_absolute_error: 1.3915 - val_loss: 2.1492 - val_mean_absolute_error: 2.1492
Epoch 67/1000
11/11 [==============================] - 0s 33ms/step - loss: 1.3451 - mean_absolute_error: 1.3451 - val_loss: 2.0619 - val_mean_absolute_error: 2.0619
Epoch 68/1000
11/11 [==============================] - 0s 28ms/step - loss: 1.3943 - mean_absolute_error: 1.3943 - val_loss: 2.0763 - val_mean_absolute_error: 2.0763
Epoch 69/1000
11/11 [==============================] - 0s 27ms/step - loss: 1.3913 - mean_absolute_error: 1.3913 - val_loss: 2.0428 - val_mean_absolute_error: 2.0428
Epoch 70/1000
11/11 [==============================] - 0s 30ms/step - loss: 1.3472 - mean_absolute_error: 1.3472 - val_loss: 2.0860 - val_mean_absolute_error: 2.0860
Epoch 71/1000
11/11 [==============================] - 0s 39ms/step - loss: 1.3493 - mean_absolute_error: 1.3493 - val_loss: 2.1078 - val_mean_absolute_error: 2.1078
Epoch 72/1000
11/11 [==============================] - 0s 27ms/step - loss: 1.3441 - mean_absolute_error: 1.3441 - val_loss: 2.1047 - val_mean_absolute_error: 2.1047
Epoch 73/1000
11/11 [==============================] - 0s 15ms/step - loss: 1.2859 - mean_absolute_error: 1.2859 - val_loss: 2.0480 - val_mean_absolute_error: 2.0480
Epoch 74/1000

11/11 [==============================] - 0s 16ms/step - loss: 1.3889 - mean_absolute_error: 1.3889 - val_loss: 2.1432 - val_mean_absolute_error: 2.1432
Epoch 75/1000
11/11 [==============================] - 0s 31ms/step - loss: 1.3500 - mean_absolute_error: 1.3500 - val_loss: 2.0166 - val_mean_absolute_error: 2.0166
Epoch 76/1000
11/11 [==============================] - 0s 26ms/step - loss: 1.4169 - mean_absolute_error: 1.4169 - val_loss: 2.0079 - val_mean_absolute_error: 2.0079
Epoch 77/1000
11/11 [==============================] - 0s 24ms/step - loss: 1.3327 - mean_absolute_error: 1.3327 - val_loss: 1.9997 - val_mean_absolute_error: 1.9997
Epoch 78/1000
11/11 [==============================] - 0s 23ms/step - loss: 1.2456 - mean_absolute_error: 1.2456 - val_loss: 1.9858 - val_mean_absolute_error: 1.9858
Epoch 79/1000
11/11 [==============================] - 0s 15ms/step - loss: 1.2379 - mean_absolute_error: 1.2379 - val_loss: 2.0482 - val_mean_absolute_error: 2.0482
Epoch 80/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.3220 - mean_absolute_error: 1.3220 - val_loss: 1.9904 - val_mean_absolute_error: 1.9904
Epoch 81/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.2222 - mean_absolute_error: 1.2222 - val_loss: 2.1421 - val_mean_absolute_error: 2.1421
Epoch 82/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.3351 - mean_absolute_error: 1.3351 - val_loss: 2.0256 - val_mean_absolute_error: 2.0256
Epoch 83/1000
11/11 [==============================] - 0s 15ms/step - loss: 1.2557 - mean_absolute_error: 1.2557 - val_loss: 2.1556 - val_mean_absolute_error: 2.1556
Epoch 84/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.2255 - mean_absolute_error: 1.2255 - val_loss: 2.2689 - val_mean_absolute_error: 2.2689
Epoch 85/1000
11/11 [==============================] - 0s 20ms/step - loss: 1.2311 - mean_absolute_error: 1.2311 - val_loss: 1.9724 - val_mean_absolute_error: 1.9724
Epoch 86/1000
11/11 [==============================] - 0s 15ms/step - loss: 1.1742 - mean_absolute_error: 1.1742 - val_loss: 2.0094 - val_mean_absolute_error: 2.0094
Epoch 87/1000
11/11 [==============================] - 0s 20ms/step - loss: 1.1564 - mean_absolute_error: 1.1564 - val_loss: 1.9570 - val_mean_absolute_error: 1.9570
Epoch 88/1000
11/11 [==============================] - 0s 15ms/step - loss: 1.1408 - mean_absolute_error: 1.1408 - val_loss: 2.0452 - val_mean_absolute_error: 2.0452
Epoch 89/1000
11/11 [==============================] - 0s 19ms/step - loss: 1.1284 - mean_absolute_error: 1.1284 - val_loss: 2.1639 - val_mean_absolute_error: 2.1639
Epoch 90/1000
11/11 [==============================] - 0s 15ms/step - loss: 1.1827 - mean_absolute_error: 1.1827 - val_loss: 1.9835 - val_mean_absolute_error: 1.9835
Epoch 91/1000
11/11 [==============================] - 0s 23ms/step - loss: 1.1979 - mean_absolute_error: 1.1979 - val_loss: 1.9340 - val_mean_absolute_error: 1.9340
Epoch 92/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.1064 - mean_absolute_error: 1.1064 - val_loss: 1.9740 - val_mean_absolute_error: 1.9740
Epoch 93/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.0903 - mean_absolute_error: 1.0903 - val_loss: 2.1777 - val_mean_absolute_error: 2.1777
Epoch 94/1000
11/11 [==============================] - 0s 26ms/step - loss: 1.1396 - mean_absolute_error: 1.1396 - val_loss: 1.9345 - val_mean_absolute_error: 1.9345
Epoch 95/1000
11/11 [==============================] - 0s 23ms/step - loss: 1.1411 - mean_absolute_error: 1.1411 - val_loss: 1.9255 - val_mean_absolute_error: 1.9255
Epoch 96/1000
11/11 [==============================] - 0s 19ms/step - loss: 1.0849 - mean_absolute_error: 1.0849 - val_loss: 2.1073 - val_mean_absolute_error: 2.1073
Epoch 97/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.0750 - mean_absolute_error: 1.0750 - val_loss: 1.9630 - val_mean_absolute_error: 1.9630
Epoch 98/1000
11/11 [==============================] - 0s 19ms/step - loss: 1.1297 - mean_absolute_error: 1.1297 - val_loss: 1.9600 - val_mean_absolute_error: 1.9600
Epoch 99/1000
11/11 [==============================] - 0s 23ms/step - loss: 1.1052 - mean_absolute_error: 1.1052 - val_loss: 1.9969 - val_mean_absolute_error: 1.9969
Epoch 100/1000
11/11 [==============================] - 0s 15ms/step - loss: 1.0980 - mean_absolute_error: 1.0980 - val_loss: 2.2627 - val_mean_absolute_error: 2.2627
Epoch 101/1000
11/11 [==============================] - 0s 23ms/step - loss: 1.1432 - mean_absolute_error: 1.1432 - val_loss: 1.9175 - val_mean_absolute_error: 1.9175
Epoch 102/1000
11/11 [==============================] - 0s 19ms/step - loss: 1.1001 - mean_absolute_error: 1.1001 - val_loss: 1.9444 - val_mean_absolute_error: 1.9444
Epoch 103/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.0580 - mean_absolute_error: 1.0580 - val_loss: 2.1290 - val_mean_absolute_error: 2.1290
Epoch 104/1000
11/11 [==============================] - 0s 22ms/step - loss: 1.1344 - mean_absolute_error: 1.1344 - val_loss: 2.0715 - val_mean_absolute_error: 2.0715
Epoch 105/1000
11/11 [==============================] - 0s 30ms/step - loss: 1.0649 - mean_absolute_error: 1.0649 - val_loss: 1.9040 - val_mean_absolute_error: 1.9040
Epoch 106/1000
11/11 [==============================] - 0s 27ms/step - loss: 1.1443 - mean_absolute_error: 1.1443 - val_loss: 2.0180 - val_mean_absolute_error: 2.0180
Epoch 107/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.0142 - mean_absolute_error: 1.0142 - val_loss: 1.9061 - val_mean_absolute_error: 1.9061
Epoch 108/1000
11/11 [==============================] - 0s 34ms/step - loss: 0.9683 - mean_absolute_error: 0.9683 - val_loss: 2.0653 - val_mean_absolute_error: 2.0653
Epoch 109/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.9932 - mean_absolute_error: 0.9932 - val_loss: 1.9468 - val_mean_absolute_error: 1.9468
Epoch 110/1000
11/11 [==============================] - 0s 37ms/step - loss: 1.0166 - mean_absolute_error: 1.0166 - val_loss: 1.8906 - val_mean_absolute_error: 1.8906
Epoch 111/1000
11/11 [==============================] - 0s 23ms/step - loss: 1.0009 - mean_absolute_error: 1.0009 - val_loss: 2.2320 - val_mean_absolute_error: 2.2320
Epoch 112/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.1505 - mean_absolute_error: 1.1505 - val_loss: 2.2504 - val_mean_absolute_error: 2.2504
Epoch 113/1000
11/11 [==============================] - 0s 26ms/step - loss: 1.1724 - mean_absolute_error: 1.1724 - val_loss: 2.1872 - val_mean_absolute_error: 2.1872
Epoch 114/1000
11/11 [==============================] - 0s 38ms/step - loss: 1.1573 - mean_absolute_error: 1.1573 - val_loss: 2.0509 - val_mean_absolute_error: 2.0509
Epoch 115/1000
11/11 [==============================] - 1s 69ms/step - loss: 1.1060 - mean_absolute_error: 1.1060 - val_loss: 1.9116 - val_mean_absolute_error: 1.9116
Epoch 116/1000
11/11 [==============================] - 0s 17ms/step - loss: 1.1813 - mean_absolute_error: 1.1813 - val_loss: 2.1928 - val_mean_absolute_error: 2.1928
Epoch 117/1000
11/11 [==============================] - 0s 22ms/step - loss: 1.0767 - mean_absolute_error: 1.0767 - val_loss: 2.0190 - val_mean_absolute_error: 2.0190
Epoch 118/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.9704 - mean_absolute_error: 0.9704 - val_loss: 1.9499 - val_mean_absolute_error: 1.9499
Epoch 119/1000
11/11 [==============================] - 1s 59ms/step - loss: 1.0109 - mean_absolute_error: 1.0109 - val_loss: 1.9061 - val_mean_absolute_error: 1.9061
Epoch 120/1000
11/11 [==============================] - 0s 32ms/step - loss: 0.9676 - mean_absolute_error: 0.9676 - val_loss: 1.9740 - val_mean_absolute_error: 1.9740
Epoch 121/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.9909 - mean_absolute_error: 0.9909 - val_loss: 1.9151 - val_mean_absolute_error: 1.9151
Epoch 122/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.9615 - mean_absolute_error: 0.9615 - val_loss: 1.8687 - val_mean_absolute_error: 1.8687
Epoch 123/1000

11/11 [==============================] - 0s 16ms/step - loss: 0.8927 - mean_absolute_error: 0.8927 - val_loss: 1.8714 - val_mean_absolute_error: 1.8714
Epoch 124/1000
11/11 [==============================] - 0s 35ms/step - loss: 0.9517 - mean_absolute_error: 0.9517 - val_loss: 1.8972 - val_mean_absolute_error: 1.8972
Epoch 125/1000
11/11 [==============================] - 0s 34ms/step - loss: 0.9877 - mean_absolute_error: 0.9877 - val_loss: 1.8425 - val_mean_absolute_error: 1.8425
Epoch 126/1000
11/11 [==============================] - 0s 33ms/step - loss: 0.9416 - mean_absolute_error: 0.9416 - val_loss: 2.1321 - val_mean_absolute_error: 2.1321
Epoch 127/1000
11/11 [==============================] - 0s 41ms/step - loss: 0.9359 - mean_absolute_error: 0.9359 - val_loss: 1.9828 - val_mean_absolute_error: 1.9828
Epoch 128/1000
11/11 [==============================] - 0s 30ms/step - loss: 0.9456 - mean_absolute_error: 0.9456 - val_loss: 1.8074 - val_mean_absolute_error: 1.8074
Epoch 129/1000
11/11 [==============================] - 0s 26ms/step - loss: 0.9205 - mean_absolute_error: 0.9205 - val_loss: 1.9233 - val_mean_absolute_error: 1.9233
Epoch 130/1000
11/11 [==============================] - 0s 29ms/step - loss: 0.9170 - mean_absolute_error: 0.9170 - val_loss: 2.3336 - val_mean_absolute_error: 2.3336
Epoch 131/1000
11/11 [==============================] - 0s 24ms/step - loss: 1.0988 - mean_absolute_error: 1.0988 - val_loss: 1.9256 - val_mean_absolute_error: 1.9256
Epoch 132/1000
11/11 [==============================] - 0s 31ms/step - loss: 0.8702 - mean_absolute_error: 0.8702 - val_loss: 2.0804 - val_mean_absolute_error: 2.0804
Epoch 133/1000
11/11 [==============================] - 0s 42ms/step - loss: 0.9577 - mean_absolute_error: 0.9577 - val_loss: 1.8039 - val_mean_absolute_error: 1.8039
Epoch 134/1000
11/11 [==============================] - 0s 27ms/step - loss: 0.8497 - mean_absolute_error: 0.8497 - val_loss: 2.0166 - val_mean_absolute_error: 2.0166
Epoch 135/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.9330 - mean_absolute_error: 0.9330 - val_loss: 2.0382 - val_mean_absolute_error: 2.0382
Epoch 136/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.9983 - mean_absolute_error: 0.9983 - val_loss: 2.0834 - val_mean_absolute_error: 2.0834
Epoch 137/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.0410 - mean_absolute_error: 1.0410 - val_loss: 2.3662 - val_mean_absolute_error: 2.3662
Epoch 138/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.0525 - mean_absolute_error: 1.0525 - val_loss: 2.0691 - val_mean_absolute_error: 2.0691
Epoch 139/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.9377 - mean_absolute_error: 0.9377 - val_loss: 1.9235 - val_mean_absolute_error: 1.9235
Epoch 140/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.9435 - mean_absolute_error: 0.9435 - val_loss: 1.8165 - val_mean_absolute_error: 1.8165
Epoch 141/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.8736 - mean_absolute_error: 0.8736 - val_loss: 1.8220 - val_mean_absolute_error: 1.8220
Epoch 142/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.7999 - mean_absolute_error: 0.7999 - val_loss: 1.8163 - val_mean_absolute_error: 1.8163
Epoch 143/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.7856 - mean_absolute_error: 0.7856 - val_loss: 1.8399 - val_mean_absolute_error: 1.8399
Epoch 144/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.7866 - mean_absolute_error: 0.7866 - val_loss: 1.8247 - val_mean_absolute_error: 1.8247
Epoch 145/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.8161 - mean_absolute_error: 0.8161 - val_loss: 1.8657 - val_mean_absolute_error: 1.8657
Epoch 146/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.8112 - mean_absolute_error: 0.8112 - val_loss: 1.8408 - val_mean_absolute_error: 1.8408
Epoch 147/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.8458 - mean_absolute_error: 0.8458 - val_loss: 1.8584 - val_mean_absolute_error: 1.8584
Epoch 148/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.7999 - mean_absolute_error: 0.7999 - val_loss: 1.8048 - val_mean_absolute_error: 1.8048
Epoch 149/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.7931 - mean_absolute_error: 0.7931 - val_loss: 2.0128 - val_mean_absolute_error: 2.0128
Epoch 150/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.8296 - mean_absolute_error: 0.8296 - val_loss: 1.8432 - val_mean_absolute_error: 1.8432
Epoch 151/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.8626 - mean_absolute_error: 0.8626 - val_loss: 1.8157 - val_mean_absolute_error: 1.8157
Epoch 152/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.7873 - mean_absolute_error: 0.7873 - val_loss: 1.8567 - val_mean_absolute_error: 1.8567
Epoch 153/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.8098 - mean_absolute_error: 0.8098 - val_loss: 2.0666 - val_mean_absolute_error: 2.0666
Epoch 154/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.8812 - mean_absolute_error: 0.8812 - val_loss: 1.9170 - val_mean_absolute_error: 1.9170
Epoch 155/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.8025 - mean_absolute_error: 0.8025 - val_loss: 1.8256 - val_mean_absolute_error: 1.8256
Epoch 156/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.7609 - mean_absolute_error: 0.7609 - val_loss: 1.9275 - val_mean_absolute_error: 1.9275
Epoch 157/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.7908 - mean_absolute_error: 0.7908 - val_loss: 1.8655 - val_mean_absolute_error: 1.8655
Epoch 158/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.7999 - mean_absolute_error: 0.7999 - val_loss: 1.7797 - val_mean_absolute_error: 1.7797
Epoch 159/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.7726 - mean_absolute_error: 0.7726 - val_loss: 1.7841 - val_mean_absolute_error: 1.7841
Epoch 160/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.7139 - mean_absolute_error: 0.7139 - val_loss: 1.8044 - val_mean_absolute_error: 1.8044
Epoch 161/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.7900 - mean_absolute_error: 0.7900 - val_loss: 1.8186 - val_mean_absolute_error: 1.8186
Epoch 162/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.7362 - mean_absolute_error: 0.7362 - val_loss: 1.8351 - val_mean_absolute_error: 1.8351
Epoch 163/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.7312 - mean_absolute_error: 0.7312 - val_loss: 1.8130 - val_mean_absolute_error: 1.8130
Epoch 164/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.7270 - mean_absolute_error: 0.7270 - val_loss: 1.9981 - val_mean_absolute_error: 1.9981
Epoch 165/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.8134 - mean_absolute_error: 0.8134 - val_loss: 1.8138 - val_mean_absolute_error: 1.8138
Epoch 166/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.7745 - mean_absolute_error: 0.7745 - val_loss: 1.7913 - val_mean_absolute_error: 1.7913
Epoch 167/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.7239 - mean_absolute_error: 0.7239 - val_loss: 1.8009 - val_mean_absolute_error: 1.8009
Epoch 168/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.7243 - mean_absolute_error: 0.7243 - val_loss: 1.9413 - val_mean_absolute_error: 1.9413
Epoch 169/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.7959 - mean_absolute_error: 0.7959 - val_loss: 1.7742 - val_mean_absolute_error: 1.7742
Epoch 170/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.7413 - mean_absolute_error: 0.7413 - val_loss: 1.8232 - val_mean_absolute_error: 1.8232
Epoch 171/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.7004 - mean_absolute_error: 0.7004 - val_loss: 1.7615 - val_mean_absolute_error: 1.7615
Epoch 172/1000

11/11 [==============================] - 0s 19ms/step - loss: 0.7318 - mean_absolute_error: 0.7318 - val_loss: 1.8112 - val_mean_absolute_error: 1.8112
Epoch 173/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.6933 - mean_absolute_error: 0.6933 - val_loss: 1.9528 - val_mean_absolute_error: 1.9528
Epoch 174/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.7583 - mean_absolute_error: 0.7583 - val_loss: 1.9046 - val_mean_absolute_error: 1.9046
Epoch 175/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.7344 - mean_absolute_error: 0.7344 - val_loss: 1.7789 - val_mean_absolute_error: 1.7789
Epoch 176/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.7735 - mean_absolute_error: 0.7735 - val_loss: 1.7562 - val_mean_absolute_error: 1.7562
Epoch 177/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.8072 - mean_absolute_error: 0.8072 - val_loss: 1.9224 - val_mean_absolute_error: 1.9224
Epoch 178/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.8384 - mean_absolute_error: 0.8384 - val_loss: 2.0328 - val_mean_absolute_error: 2.0328
Epoch 179/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.7679 - mean_absolute_error: 0.7679 - val_loss: 1.7931 - val_mean_absolute_error: 1.7931
Epoch 180/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.7328 - mean_absolute_error: 0.7328 - val_loss: 1.8813 - val_mean_absolute_error: 1.8813
Epoch 181/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.7052 - mean_absolute_error: 0.7052 - val_loss: 1.8769 - val_mean_absolute_error: 1.8769
Epoch 182/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.6579 - mean_absolute_error: 0.6579 - val_loss: 1.8441 - val_mean_absolute_error: 1.8441
Epoch 183/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.6285 - mean_absolute_error: 0.6285 - val_loss: 1.8610 - val_mean_absolute_error: 1.8610
Epoch 184/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.6633 - mean_absolute_error: 0.6633 - val_loss: 1.8273 - val_mean_absolute_error: 1.8273
Epoch 185/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.6320 - mean_absolute_error: 0.6320 - val_loss: 2.0550 - val_mean_absolute_error: 2.0550
Epoch 186/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.7389 - mean_absolute_error: 0.7389 - val_loss: 1.9365 - val_mean_absolute_error: 1.9365
Epoch 187/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.7029 - mean_absolute_error: 0.7029 - val_loss: 1.7809 - val_mean_absolute_error: 1.7809
Epoch 188/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.8241 - mean_absolute_error: 0.8241 - val_loss: 1.8601 - val_mean_absolute_error: 1.8601
Epoch 189/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.7555 - mean_absolute_error: 0.7555 - val_loss: 1.7798 - val_mean_absolute_error: 1.7798
Epoch 190/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.6454 - mean_absolute_error: 0.6454 - val_loss: 1.9568 - val_mean_absolute_error: 1.9568
Epoch 191/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.7062 - mean_absolute_error: 0.7062 - val_loss: 1.8534 - val_mean_absolute_error: 1.8534
Epoch 192/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.6623 - mean_absolute_error: 0.6623 - val_loss: 1.7757 - val_mean_absolute_error: 1.7757
Epoch 193/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.6853 - mean_absolute_error: 0.6853 - val_loss: 1.7367 - val_mean_absolute_error: 1.7367
Epoch 194/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.6543 - mean_absolute_error: 0.6543 - val_loss: 1.8151 - val_mean_absolute_error: 1.8151
Epoch 195/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.6422 - mean_absolute_error: 0.6422 - val_loss: 1.8782 - val_mean_absolute_error: 1.8782
Epoch 196/1000
11/11 [==============================] - 0s 25ms/step - loss: 0.7330 - mean_absolute_error: 0.7330 - val_loss: 1.8048 - val_mean_absolute_error: 1.8048
Epoch 197/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.7486 - mean_absolute_error: 0.7486 - val_loss: 1.7148 - val_mean_absolute_error: 1.7148
Epoch 198/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.7196 - mean_absolute_error: 0.7196 - val_loss: 1.9664 - val_mean_absolute_error: 1.9664
Epoch 199/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.7319 - mean_absolute_error: 0.7319 - val_loss: 1.8837 - val_mean_absolute_error: 1.8837
Epoch 200/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.7326 - mean_absolute_error: 0.7326 - val_loss: 1.8095 - val_mean_absolute_error: 1.8095
Epoch 201/1000
11/11 [==============================] - 0s 33ms/step - loss: 0.7110 - mean_absolute_error: 0.7110 - val_loss: 1.7938 - val_mean_absolute_error: 1.7938
Epoch 202/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.6284 - mean_absolute_error: 0.6284 - val_loss: 1.7976 - val_mean_absolute_error: 1.7976
Epoch 203/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.6178 - mean_absolute_error: 0.6178 - val_loss: 1.7773 - val_mean_absolute_error: 1.7773
Epoch 204/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.6700 - mean_absolute_error: 0.6700 - val_loss: 2.0028 - val_mean_absolute_error: 2.0028
Epoch 205/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.7210 - mean_absolute_error: 0.7210 - val_loss: 1.9977 - val_mean_absolute_error: 1.9977
Epoch 206/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.7906 - mean_absolute_error: 0.7906 - val_loss: 1.8310 - val_mean_absolute_error: 1.8310
Epoch 207/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.6684 - mean_absolute_error: 0.6684 - val_loss: 1.8194 - val_mean_absolute_error: 1.8194
Epoch 208/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.6494 - mean_absolute_error: 0.6494 - val_loss: 1.8030 - val_mean_absolute_error: 1.8030
Epoch 209/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.5746 - mean_absolute_error: 0.5746 - val_loss: 1.8300 - val_mean_absolute_error: 1.8300
Epoch 210/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.6601 - mean_absolute_error: 0.6601 - val_loss: 1.8549 - val_mean_absolute_error: 1.8549
Epoch 211/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.5988 - mean_absolute_error: 0.5988 - val_loss: 1.8477 - val_mean_absolute_error: 1.8477
Epoch 212/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.5968 - mean_absolute_error: 0.5968 - val_loss: 1.9177 - val_mean_absolute_error: 1.9177
Epoch 213/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.6349 - mean_absolute_error: 0.6349 - val_loss: 1.8045 - val_mean_absolute_error: 1.8045
Epoch 214/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.5856 - mean_absolute_error: 0.5856 - val_loss: 1.9054 - val_mean_absolute_error: 1.9054
Epoch 215/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.5883 - mean_absolute_error: 0.5883 - val_loss: 1.7797 - val_mean_absolute_error: 1.7797
Epoch 216/1000
11/11 [==============================] - 0s 25ms/step - loss: 0.6215 - mean_absolute_error: 0.6215 - val_loss: 1.7881 - val_mean_absolute_error: 1.7881
Epoch 217/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.6164 - mean_absolute_error: 0.6164 - val_loss: 1.7918 - val_mean_absolute_error: 1.7918
Epoch 218/1000
11/11 [==============================] - 0s 32ms/step - loss: 0.7060 - mean_absolute_error: 0.7060 - val_loss: 1.8175 - val_mean_absolute_error: 1.8175
Epoch 219/1000
11/11 [==============================] - 0s 30ms/step - loss: 0.6700 - mean_absolute_error: 0.6700 - val_loss: 1.8852 - val_mean_absolute_error: 1.8852
Epoch 220/1000
11/11 [==============================] - 0s 28ms/step - loss: 0.5924 - mean_absolute_error: 0.5924 - val_loss: 1.8751 - val_mean_absolute_error: 1.8751
Epoch 221/1000

11/11 [==============================] - 0s 28ms/step - loss: 0.5530 - mean_absolute_error: 0.5530 - val_loss: 1.8099 - val_mean_absolute_error: 1.8099
Epoch 222/1000
11/11 [==============================] - 0s 31ms/step - loss: 0.5685 - mean_absolute_error: 0.5685 - val_loss: 1.7627 - val_mean_absolute_error: 1.7627
Epoch 223/1000
11/11 [==============================] - 1s 45ms/step - loss: 0.6728 - mean_absolute_error: 0.6728 - val_loss: 1.8568 - val_mean_absolute_error: 1.8568
Epoch 224/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.5738 - mean_absolute_error: 0.5738 - val_loss: 1.8784 - val_mean_absolute_error: 1.8784
Epoch 225/1000
11/11 [==============================] - 0s 28ms/step - loss: 0.5673 - mean_absolute_error: 0.5673 - val_loss: 1.8248 - val_mean_absolute_error: 1.8248
Epoch 226/1000
11/11 [==============================] - 0s 34ms/step - loss: 0.5941 - mean_absolute_error: 0.5941 - val_loss: 2.0074 - val_mean_absolute_error: 2.0074
Epoch 227/1000
11/11 [==============================] - 0s 36ms/step - loss: 0.6538 - mean_absolute_error: 0.6538 - val_loss: 1.8264 - val_mean_absolute_error: 1.8264
Epoch 228/1000
11/11 [==============================] - 0s 26ms/step - loss: 0.5355 - mean_absolute_error: 0.5355 - val_loss: 1.8292 - val_mean_absolute_error: 1.8292
Epoch 229/1000
11/11 [==============================] - 0s 21ms/step - loss: 0.5403 - mean_absolute_error: 0.5403 - val_loss: 1.9165 - val_mean_absolute_error: 1.9165
Epoch 230/1000
11/11 [==============================] - 0s 29ms/step - loss: 0.5972 - mean_absolute_error: 0.5972 - val_loss: 1.8898 - val_mean_absolute_error: 1.8898
Epoch 231/1000
11/11 [==============================] - 0s 34ms/step - loss: 0.5994 - mean_absolute_error: 0.5994 - val_loss: 1.8416 - val_mean_absolute_error: 1.8416
Epoch 232/1000
11/11 [==============================] - 0s 31ms/step - loss: 0.5633 - mean_absolute_error: 0.5633 - val_loss: 1.7877 - val_mean_absolute_error: 1.7877
Epoch 233/1000
11/11 [==============================] - 0s 32ms/step - loss: 0.6102 - mean_absolute_error: 0.6102 - val_loss: 1.8013 - val_mean_absolute_error: 1.8013
Epoch 234/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.6288 - mean_absolute_error: 0.6288 - val_loss: 1.7903 - val_mean_absolute_error: 1.7903
Epoch 235/1000
11/11 [==============================] - 0s 25ms/step - loss: 0.6682 - mean_absolute_error: 0.6682 - val_loss: 1.8214 - val_mean_absolute_error: 1.8214
Epoch 236/1000
11/11 [==============================] - 0s 33ms/step - loss: 0.5732 - mean_absolute_error: 0.5732 - val_loss: 1.7660 - val_mean_absolute_error: 1.7660
Epoch 237/1000
11/11 [==============================] - 0s 34ms/step - loss: 0.5719 - mean_absolute_error: 0.5719 - val_loss: 1.7597 - val_mean_absolute_error: 1.7597
Epoch 238/1000
11/11 [==============================] - 1s 58ms/step - loss: 0.5527 - mean_absolute_error: 0.5527 - val_loss: 1.8478 - val_mean_absolute_error: 1.8478
Epoch 239/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.5607 - mean_absolute_error: 0.5607 - val_loss: 1.8407 - val_mean_absolute_error: 1.8407
Epoch 240/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5811 - mean_absolute_error: 0.5811 - val_loss: 1.7562 - val_mean_absolute_error: 1.7562
Epoch 241/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.5469 - mean_absolute_error: 0.5469 - val_loss: 1.7829 - val_mean_absolute_error: 1.7829
Epoch 242/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5309 - mean_absolute_error: 0.5309 - val_loss: 1.8175 - val_mean_absolute_error: 1.8175
Epoch 243/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.5342 - mean_absolute_error: 0.5342 - val_loss: 1.8967 - val_mean_absolute_error: 1.8967
Epoch 244/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5570 - mean_absolute_error: 0.5570 - val_loss: 1.8554 - val_mean_absolute_error: 1.8554
Epoch 245/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.5260 - mean_absolute_error: 0.5260 - val_loss: 1.7838 - val_mean_absolute_error: 1.7838
Epoch 246/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.5593 - mean_absolute_error: 0.5593 - val_loss: 1.8446 - val_mean_absolute_error: 1.8446
Epoch 247/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5766 - mean_absolute_error: 0.5766 - val_loss: 1.7505 - val_mean_absolute_error: 1.7505
Epoch 248/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.5358 - mean_absolute_error: 0.5358 - val_loss: 1.7707 - val_mean_absolute_error: 1.7707
Epoch 249/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.4987 - mean_absolute_error: 0.4987 - val_loss: 1.8003 - val_mean_absolute_error: 1.8003
Epoch 250/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4933 - mean_absolute_error: 0.4933 - val_loss: 1.8814 - val_mean_absolute_error: 1.8814
Epoch 251/1000
11/11 [==============================] - 0s 29ms/step - loss: 0.4979 - mean_absolute_error: 0.4979 - val_loss: 1.8302 - val_mean_absolute_error: 1.8302
Epoch 252/1000
11/11 [==============================] - 0s 40ms/step - loss: 0.5066 - mean_absolute_error: 0.5066 - val_loss: 1.7881 - val_mean_absolute_error: 1.7881
Epoch 253/1000
11/11 [==============================] - 0s 27ms/step - loss: 0.5186 - mean_absolute_error: 0.5186 - val_loss: 1.9952 - val_mean_absolute_error: 1.9952
Epoch 254/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.7194 - mean_absolute_error: 0.7194 - val_loss: 1.8918 - val_mean_absolute_error: 1.8918
Epoch 255/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.7523 - mean_absolute_error: 0.7523 - val_loss: 1.8259 - val_mean_absolute_error: 1.8259
Epoch 256/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.6785 - mean_absolute_error: 0.6785 - val_loss: 1.7863 - val_mean_absolute_error: 1.7863
Epoch 257/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.6791 - mean_absolute_error: 0.6791 - val_loss: 1.8300 - val_mean_absolute_error: 1.8300
Epoch 258/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.6404 - mean_absolute_error: 0.6404 - val_loss: 1.8513 - val_mean_absolute_error: 1.8513
Epoch 259/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.5201 - mean_absolute_error: 0.5201 - val_loss: 1.8113 - val_mean_absolute_error: 1.8113
Epoch 260/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5287 - mean_absolute_error: 0.5287 - val_loss: 1.7813 - val_mean_absolute_error: 1.7813
Epoch 261/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.5552 - mean_absolute_error: 0.5552 - val_loss: 2.0103 - val_mean_absolute_error: 2.0103
Epoch 262/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.7066 - mean_absolute_error: 0.7066 - val_loss: 1.9706 - val_mean_absolute_error: 1.9706
Epoch 263/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.5825 - mean_absolute_error: 0.5825 - val_loss: 1.8591 - val_mean_absolute_error: 1.8591
Epoch 264/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4928 - mean_absolute_error: 0.4928 - val_loss: 1.7628 - val_mean_absolute_error: 1.7628
Epoch 265/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5052 - mean_absolute_error: 0.5052 - val_loss: 1.8644 - val_mean_absolute_error: 1.8644
Epoch 266/1000
11/11 [==============================] - 0s 25ms/step - loss: 0.4586 - mean_absolute_error: 0.4586 - val_loss: 1.8357 - val_mean_absolute_error: 1.8357
Epoch 267/1000
11/11 [==============================] - 0s 30ms/step - loss: 0.5569 - mean_absolute_error: 0.5569 - val_loss: 1.8199 - val_mean_absolute_error: 1.8199
Epoch 268/1000
11/11 [==============================] - 0s 45ms/step - loss: 0.5161 - mean_absolute_error: 0.5161 - val_loss: 1.8328 - val_mean_absolute_error: 1.8328
Epoch 269/1000
11/11 [==============================] - 1s 53ms/step - loss: 0.4795 - mean_absolute_error: 0.4795 - val_loss: 1.8554 - val_mean_absolute_error: 1.8554
Epoch 270/1000

11/11 [==============================] - 0s 21ms/step - loss: 0.4620 - mean_absolute_error: 0.4620 - val_loss: 1.8057 - val_mean_absolute_error: 1.8057
Epoch 271/1000
11/11 [==============================] - 0s 25ms/step - loss: 0.4477 - mean_absolute_error: 0.4477 - val_loss: 1.8862 - val_mean_absolute_error: 1.8862
Epoch 272/1000
11/11 [==============================] - 0s 41ms/step - loss: 0.4734 - mean_absolute_error: 0.4734 - val_loss: 1.7997 - val_mean_absolute_error: 1.7997
Epoch 273/1000
11/11 [==============================] - 0s 40ms/step - loss: 0.4902 - mean_absolute_error: 0.4902 - val_loss: 1.8236 - val_mean_absolute_error: 1.8236
Epoch 274/1000
11/11 [==============================] - 1s 50ms/step - loss: 0.6028 - mean_absolute_error: 0.6028 - val_loss: 1.9331 - val_mean_absolute_error: 1.9331
Epoch 275/1000
11/11 [==============================] - 0s 28ms/step - loss: 0.5273 - mean_absolute_error: 0.5273 - val_loss: 1.8822 - val_mean_absolute_error: 1.8822
Epoch 276/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.5004 - mean_absolute_error: 0.5004 - val_loss: 1.7982 - val_mean_absolute_error: 1.7982
Epoch 277/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.4754 - mean_absolute_error: 0.4754 - val_loss: 1.8657 - val_mean_absolute_error: 1.8657
Epoch 278/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4710 - mean_absolute_error: 0.4710 - val_loss: 1.9461 - val_mean_absolute_error: 1.9461
Epoch 279/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.5586 - mean_absolute_error: 0.5586 - val_loss: 1.7917 - val_mean_absolute_error: 1.7917
Epoch 280/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.5618 - mean_absolute_error: 0.5618 - val_loss: 1.8371 - val_mean_absolute_error: 1.8371
Epoch 281/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.4595 - mean_absolute_error: 0.4595 - val_loss: 1.8035 - val_mean_absolute_error: 1.8035
Epoch 282/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4217 - mean_absolute_error: 0.4217 - val_loss: 1.8994 - val_mean_absolute_error: 1.8994
Epoch 283/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.5779 - mean_absolute_error: 0.5779 - val_loss: 1.8505 - val_mean_absolute_error: 1.8505
Epoch 284/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.4655 - mean_absolute_error: 0.4655 - val_loss: 1.8354 - val_mean_absolute_error: 1.8354
Epoch 285/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.5688 - mean_absolute_error: 0.5688 - val_loss: 1.8839 - val_mean_absolute_error: 1.8839
Epoch 286/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5322 - mean_absolute_error: 0.5322 - val_loss: 1.8427 - val_mean_absolute_error: 1.8427
Epoch 287/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4974 - mean_absolute_error: 0.4974 - val_loss: 1.8142 - val_mean_absolute_error: 1.8142
Epoch 288/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4556 - mean_absolute_error: 0.4556 - val_loss: 1.8606 - val_mean_absolute_error: 1.8606
Epoch 289/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4404 - mean_absolute_error: 0.4404 - val_loss: 1.8947 - val_mean_absolute_error: 1.8947
Epoch 290/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.4414 - mean_absolute_error: 0.4414 - val_loss: 1.8436 - val_mean_absolute_error: 1.8436
Epoch 291/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4301 - mean_absolute_error: 0.4301 - val_loss: 1.9468 - val_mean_absolute_error: 1.9468
Epoch 292/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5311 - mean_absolute_error: 0.5311 - val_loss: 1.8861 - val_mean_absolute_error: 1.8861
Epoch 293/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4728 - mean_absolute_error: 0.4728 - val_loss: 1.8161 - val_mean_absolute_error: 1.8161
Epoch 294/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4503 - mean_absolute_error: 0.4503 - val_loss: 1.8008 - val_mean_absolute_error: 1.8008
Epoch 295/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4271 - mean_absolute_error: 0.4271 - val_loss: 1.8260 - val_mean_absolute_error: 1.8260
Epoch 296/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4436 - mean_absolute_error: 0.4436 - val_loss: 1.9251 - val_mean_absolute_error: 1.9251
Epoch 297/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5546 - mean_absolute_error: 0.5546 - val_loss: 1.8211 - val_mean_absolute_error: 1.8211
Epoch 298/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5045 - mean_absolute_error: 0.5045 - val_loss: 1.9483 - val_mean_absolute_error: 1.9483
Epoch 299/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.4851 - mean_absolute_error: 0.4851 - val_loss: 1.8292 - val_mean_absolute_error: 1.8292
Epoch 300/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.4880 - mean_absolute_error: 0.4880 - val_loss: 1.8000 - val_mean_absolute_error: 1.8000
Epoch 301/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4606 - mean_absolute_error: 0.4606 - val_loss: 1.8154 - val_mean_absolute_error: 1.8154
Epoch 302/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4595 - mean_absolute_error: 0.4595 - val_loss: 1.7928 - val_mean_absolute_error: 1.7928
Epoch 303/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4550 - mean_absolute_error: 0.4550 - val_loss: 1.8384 - val_mean_absolute_error: 1.8384
Epoch 304/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4805 - mean_absolute_error: 0.4805 - val_loss: 1.8250 - val_mean_absolute_error: 1.8250
Epoch 305/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.5690 - mean_absolute_error: 0.5690 - val_loss: 1.8239 - val_mean_absolute_error: 1.8239
Epoch 306/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5878 - mean_absolute_error: 0.5878 - val_loss: 1.9843 - val_mean_absolute_error: 1.9843
Epoch 307/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5951 - mean_absolute_error: 0.5951 - val_loss: 1.7891 - val_mean_absolute_error: 1.7891
Epoch 308/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5180 - mean_absolute_error: 0.5180 - val_loss: 1.8331 - val_mean_absolute_error: 1.8331
Epoch 309/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.5070 - mean_absolute_error: 0.5070 - val_loss: 1.9040 - val_mean_absolute_error: 1.9040
Epoch 310/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.5213 - mean_absolute_error: 0.5213 - val_loss: 1.9912 - val_mean_absolute_error: 1.9912
Epoch 311/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5671 - mean_absolute_error: 0.5671 - val_loss: 1.8033 - val_mean_absolute_error: 1.8033
Epoch 312/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5684 - mean_absolute_error: 0.5684 - val_loss: 1.8162 - val_mean_absolute_error: 1.8162
Epoch 313/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.5846 - mean_absolute_error: 0.5846 - val_loss: 1.9296 - val_mean_absolute_error: 1.9296
Epoch 314/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4874 - mean_absolute_error: 0.4874 - val_loss: 1.8387 - val_mean_absolute_error: 1.8387
Epoch 315/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4202 - mean_absolute_error: 0.4202 - val_loss: 1.8895 - val_mean_absolute_error: 1.8895
Epoch 316/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4089 - mean_absolute_error: 0.4089 - val_loss: 1.8219 - val_mean_absolute_error: 1.8219
Epoch 317/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4316 - mean_absolute_error: 0.4316 - val_loss: 1.9462 - val_mean_absolute_error: 1.9462
Epoch 318/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.5212 - mean_absolute_error: 0.5212 - val_loss: 1.8183 - val_mean_absolute_error: 1.8183
Epoch 319/1000

11/11 [==============================] - 0s 24ms/step - loss: 0.5169 - mean_absolute_error: 0.5169 - val_loss: 1.9122 - val_mean_absolute_error: 1.9122
Epoch 320/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.5085 - mean_absolute_error: 0.5085 - val_loss: 1.7767 - val_mean_absolute_error: 1.7767
Epoch 321/1000
11/11 [==============================] - 0s 29ms/step - loss: 0.4889 - mean_absolute_error: 0.4889 - val_loss: 1.8516 - val_mean_absolute_error: 1.8516
Epoch 322/1000
11/11 [==============================] - 0s 27ms/step - loss: 0.4764 - mean_absolute_error: 0.4764 - val_loss: 1.9288 - val_mean_absolute_error: 1.9288
Epoch 323/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4159 - mean_absolute_error: 0.4159 - val_loss: 1.8102 - val_mean_absolute_error: 1.8102
Epoch 324/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4558 - mean_absolute_error: 0.4558 - val_loss: 1.8138 - val_mean_absolute_error: 1.8138
Epoch 325/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.4790 - mean_absolute_error: 0.4790 - val_loss: 1.8974 - val_mean_absolute_error: 1.8974
Epoch 326/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4293 - mean_absolute_error: 0.4293 - val_loss: 1.8578 - val_mean_absolute_error: 1.8578
Epoch 327/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4532 - mean_absolute_error: 0.4532 - val_loss: 1.8949 - val_mean_absolute_error: 1.8949
Epoch 328/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.4122 - mean_absolute_error: 0.4122 - val_loss: 1.8746 - val_mean_absolute_error: 1.8746
Epoch 329/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.3777 - mean_absolute_error: 0.3777 - val_loss: 1.8044 - val_mean_absolute_error: 1.8044
Epoch 330/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3688 - mean_absolute_error: 0.3688 - val_loss: 1.8759 - val_mean_absolute_error: 1.8759
Epoch 331/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4538 - mean_absolute_error: 0.4538 - val_loss: 1.8653 - val_mean_absolute_error: 1.8653
Epoch 332/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.4248 - mean_absolute_error: 0.4248 - val_loss: 1.8381 - val_mean_absolute_error: 1.8381
Epoch 333/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4425 - mean_absolute_error: 0.4425 - val_loss: 1.8084 - val_mean_absolute_error: 1.8084
Epoch 334/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4527 - mean_absolute_error: 0.4527 - val_loss: 1.8468 - val_mean_absolute_error: 1.8468
Epoch 335/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4900 - mean_absolute_error: 0.4900 - val_loss: 1.8679 - val_mean_absolute_error: 1.8679
Epoch 336/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.5925 - mean_absolute_error: 0.5925 - val_loss: 1.8461 - val_mean_absolute_error: 1.8461
Epoch 337/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.6530 - mean_absolute_error: 0.6530 - val_loss: 1.8713 - val_mean_absolute_error: 1.8713
Epoch 338/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.4896 - mean_absolute_error: 0.4896 - val_loss: 1.8502 - val_mean_absolute_error: 1.8502
Epoch 339/1000
11/11 [==============================] - 0s 26ms/step - loss: 0.4350 - mean_absolute_error: 0.4350 - val_loss: 1.8870 - val_mean_absolute_error: 1.8870
Epoch 340/1000
11/11 [==============================] - 0s 38ms/step - loss: 0.4325 - mean_absolute_error: 0.4325 - val_loss: 1.9394 - val_mean_absolute_error: 1.9394
Epoch 341/1000
11/11 [==============================] - 0s 35ms/step - loss: 0.4023 - mean_absolute_error: 0.4023 - val_loss: 1.8585 - val_mean_absolute_error: 1.8585
Epoch 342/1000
11/11 [==============================] - 0s 46ms/step - loss: 0.3841 - mean_absolute_error: 0.3841 - val_loss: 1.8440 - val_mean_absolute_error: 1.8440
Epoch 343/1000
11/11 [==============================] - 0s 31ms/step - loss: 0.3839 - mean_absolute_error: 0.3839 - val_loss: 1.8550 - val_mean_absolute_error: 1.8550
Epoch 344/1000
11/11 [==============================] - 0s 45ms/step - loss: 0.4205 - mean_absolute_error: 0.4205 - val_loss: 1.8921 - val_mean_absolute_error: 1.8921
Epoch 345/1000
11/11 [==============================] - 0s 38ms/step - loss: 0.4124 - mean_absolute_error: 0.4124 - val_loss: 1.9147 - val_mean_absolute_error: 1.9147
Epoch 346/1000
11/11 [==============================] - 1s 51ms/step - loss: 0.4150 - mean_absolute_error: 0.4150 - val_loss: 1.8626 - val_mean_absolute_error: 1.8626
Epoch 347/1000
11/11 [==============================] - 1s 52ms/step - loss: 0.3904 - mean_absolute_error: 0.3904 - val_loss: 1.8499 - val_mean_absolute_error: 1.8499
Epoch 348/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.4714 - mean_absolute_error: 0.4714 - val_loss: 1.8323 - val_mean_absolute_error: 1.8323
Epoch 349/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4667 - mean_absolute_error: 0.4667 - val_loss: 1.9708 - val_mean_absolute_error: 1.9708
Epoch 350/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4780 - mean_absolute_error: 0.4780 - val_loss: 1.9068 - val_mean_absolute_error: 1.9068
Epoch 351/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5631 - mean_absolute_error: 0.5631 - val_loss: 1.9114 - val_mean_absolute_error: 1.9114
Epoch 352/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4615 - mean_absolute_error: 0.4615 - val_loss: 1.7794 - val_mean_absolute_error: 1.7794
Epoch 353/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4543 - mean_absolute_error: 0.4543 - val_loss: 1.8992 - val_mean_absolute_error: 1.8992
Epoch 354/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4494 - mean_absolute_error: 0.4494 - val_loss: 1.8266 - val_mean_absolute_error: 1.8266
Epoch 355/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4435 - mean_absolute_error: 0.4435 - val_loss: 1.8811 - val_mean_absolute_error: 1.8811
Epoch 356/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4875 - mean_absolute_error: 0.4875 - val_loss: 1.8932 - val_mean_absolute_error: 1.8932
Epoch 357/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4352 - mean_absolute_error: 0.4352 - val_loss: 1.8343 - val_mean_absolute_error: 1.8343
Epoch 358/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4448 - mean_absolute_error: 0.4448 - val_loss: 1.8670 - val_mean_absolute_error: 1.8670
Epoch 359/1000
11/11 [==============================] - 0s 37ms/step - loss: 0.4080 - mean_absolute_error: 0.4080 - val_loss: 1.8586 - val_mean_absolute_error: 1.8586
Epoch 360/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.4322 - mean_absolute_error: 0.4322 - val_loss: 1.8772 - val_mean_absolute_error: 1.8772
Epoch 361/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4600 - mean_absolute_error: 0.4600 - val_loss: 1.8952 - val_mean_absolute_error: 1.8952
Epoch 362/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4215 - mean_absolute_error: 0.4215 - val_loss: 1.8912 - val_mean_absolute_error: 1.8912
Epoch 363/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.4076 - mean_absolute_error: 0.4076 - val_loss: 1.8320 - val_mean_absolute_error: 1.8320
Epoch 364/1000
11/11 [==============================] - 0s 29ms/step - loss: 0.5233 - mean_absolute_error: 0.5233 - val_loss: 1.9777 - val_mean_absolute_error: 1.9777
Epoch 365/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5654 - mean_absolute_error: 0.5654 - val_loss: 1.8427 - val_mean_absolute_error: 1.8427
Epoch 366/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.6591 - mean_absolute_error: 0.6591 - val_loss: 1.8480 - val_mean_absolute_error: 1.8480
Epoch 367/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4656 - mean_absolute_error: 0.4656 - val_loss: 1.8199 - val_mean_absolute_error: 1.8199
Epoch 368/1000

11/11 [==============================] - 0s 19ms/step - loss: 0.4526 - mean_absolute_error: 0.4526 - val_loss: 1.9793 - val_mean_absolute_error: 1.9793
Epoch 369/1000
11/11 [==============================] - 0s 27ms/step - loss: 0.4169 - mean_absolute_error: 0.4169 - val_loss: 1.8658 - val_mean_absolute_error: 1.8658
Epoch 370/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4594 - mean_absolute_error: 0.4594 - val_loss: 1.9924 - val_mean_absolute_error: 1.9924
Epoch 371/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5190 - mean_absolute_error: 0.5190 - val_loss: 1.8469 - val_mean_absolute_error: 1.8469
Epoch 372/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.5445 - mean_absolute_error: 0.5445 - val_loss: 2.0124 - val_mean_absolute_error: 2.0124
Epoch 373/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.6299 - mean_absolute_error: 0.6299 - val_loss: 1.9076 - val_mean_absolute_error: 1.9076
Epoch 374/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.7099 - mean_absolute_error: 0.7099 - val_loss: 1.8610 - val_mean_absolute_error: 1.8610
Epoch 375/1000
11/11 [==============================] - 0s 24ms/step - loss: 0.4422 - mean_absolute_error: 0.4422 - val_loss: 1.8654 - val_mean_absolute_error: 1.8654
Epoch 376/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4246 - mean_absolute_error: 0.4246 - val_loss: 1.9158 - val_mean_absolute_error: 1.9158
Epoch 377/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.4502 - mean_absolute_error: 0.4502 - val_loss: 1.8429 - val_mean_absolute_error: 1.8429
Epoch 378/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4092 - mean_absolute_error: 0.4092 - val_loss: 1.9230 - val_mean_absolute_error: 1.9230
Epoch 379/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4406 - mean_absolute_error: 0.4406 - val_loss: 1.8204 - val_mean_absolute_error: 1.8204
Epoch 380/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4887 - mean_absolute_error: 0.4887 - val_loss: 1.9005 - val_mean_absolute_error: 1.9005
Epoch 381/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3995 - mean_absolute_error: 0.3995 - val_loss: 1.8314 - val_mean_absolute_error: 1.8314
Epoch 382/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5452 - mean_absolute_error: 0.5452 - val_loss: 1.8799 - val_mean_absolute_error: 1.8799
Epoch 383/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.5278 - mean_absolute_error: 0.5278 - val_loss: 1.8741 - val_mean_absolute_error: 1.8741
Epoch 384/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3861 - mean_absolute_error: 0.3861 - val_loss: 1.8231 - val_mean_absolute_error: 1.8231
Epoch 385/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.5154 - mean_absolute_error: 0.5154 - val_loss: 1.8554 - val_mean_absolute_error: 1.8554
Epoch 386/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4351 - mean_absolute_error: 0.4351 - val_loss: 1.8777 - val_mean_absolute_error: 1.8777
Epoch 387/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.3719 - mean_absolute_error: 0.3719 - val_loss: 1.8138 - val_mean_absolute_error: 1.8138
Epoch 388/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.3565 - mean_absolute_error: 0.3565 - val_loss: 1.8657 - val_mean_absolute_error: 1.8657
Epoch 389/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4021 - mean_absolute_error: 0.4021 - val_loss: 1.9354 - val_mean_absolute_error: 1.9354
Epoch 390/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.3615 - mean_absolute_error: 0.3615 - val_loss: 1.8023 - val_mean_absolute_error: 1.8023
Epoch 391/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4852 - mean_absolute_error: 0.4852 - val_loss: 1.9636 - val_mean_absolute_error: 1.9636
Epoch 392/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4261 - mean_absolute_error: 0.4261 - val_loss: 1.9179 - val_mean_absolute_error: 1.9179
Epoch 393/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3629 - mean_absolute_error: 0.3629 - val_loss: 1.9477 - val_mean_absolute_error: 1.9477
Epoch 394/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4520 - mean_absolute_error: 0.4520 - val_loss: 1.8365 - val_mean_absolute_error: 1.8365
Epoch 395/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4584 - mean_absolute_error: 0.4584 - val_loss: 1.9077 - val_mean_absolute_error: 1.9077
Epoch 396/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4156 - mean_absolute_error: 0.4156 - val_loss: 1.8579 - val_mean_absolute_error: 1.8579
Epoch 397/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3840 - mean_absolute_error: 0.3840 - val_loss: 1.8318 - val_mean_absolute_error: 1.8318
Epoch 398/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3428 - mean_absolute_error: 0.3428 - val_loss: 1.9044 - val_mean_absolute_error: 1.9044
Epoch 399/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.3594 - mean_absolute_error: 0.3594 - val_loss: 1.9581 - val_mean_absolute_error: 1.9581
Epoch 400/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4252 - mean_absolute_error: 0.4252 - val_loss: 1.8557 - val_mean_absolute_error: 1.8557
Epoch 401/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3928 - mean_absolute_error: 0.3928 - val_loss: 1.9034 - val_mean_absolute_error: 1.9034
Epoch 402/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3532 - mean_absolute_error: 0.3532 - val_loss: 1.8405 - val_mean_absolute_error: 1.8405
Epoch 403/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3636 - mean_absolute_error: 0.3636 - val_loss: 1.8680 - val_mean_absolute_error: 1.8680
Epoch 404/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3831 - mean_absolute_error: 0.3831 - val_loss: 1.8646 - val_mean_absolute_error: 1.8646
Epoch 405/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.3497 - mean_absolute_error: 0.3497 - val_loss: 1.8682 - val_mean_absolute_error: 1.8682
Epoch 406/1000
11/11 [==============================] - 0s 25ms/step - loss: 0.3383 - mean_absolute_error: 0.3383 - val_loss: 1.8522 - val_mean_absolute_error: 1.8522
Epoch 407/1000
11/11 [==============================] - 1s 64ms/step - loss: 0.3272 - mean_absolute_error: 0.3272 - val_loss: 1.8683 - val_mean_absolute_error: 1.8683
Epoch 408/1000
11/11 [==============================] - 0s 32ms/step - loss: 0.3240 - mean_absolute_error: 0.3240 - val_loss: 1.9241 - val_mean_absolute_error: 1.9241
Epoch 409/1000
11/11 [==============================] - 0s 29ms/step - loss: 0.4541 - mean_absolute_error: 0.4541 - val_loss: 1.8767 - val_mean_absolute_error: 1.8767
Epoch 410/1000
11/11 [==============================] - 0s 26ms/step - loss: 0.3728 - mean_absolute_error: 0.3728 - val_loss: 1.8571 - val_mean_absolute_error: 1.8571
Epoch 411/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.3613 - mean_absolute_error: 0.3613 - val_loss: 1.8483 - val_mean_absolute_error: 1.8483
Epoch 412/1000
11/11 [==============================] - 0s 35ms/step - loss: 0.3384 - mean_absolute_error: 0.3384 - val_loss: 1.8499 - val_mean_absolute_error: 1.8499
Epoch 413/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.3629 - mean_absolute_error: 0.3629 - val_loss: 1.9193 - val_mean_absolute_error: 1.9193
Epoch 414/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.3760 - mean_absolute_error: 0.3760 - val_loss: 1.9322 - val_mean_absolute_error: 1.9322
Epoch 415/1000
11/11 [==============================] - 0s 26ms/step - loss: 0.4225 - mean_absolute_error: 0.4225 - val_loss: 1.8826 - val_mean_absolute_error: 1.8826
Epoch 416/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.3511 - mean_absolute_error: 0.3511 - val_loss: 1.9229 - val_mean_absolute_error: 1.9229
Epoch 417/1000

11/11 [==============================] - 0s 26ms/step - loss: 0.3695 - mean_absolute_error: 0.3695 - val_loss: 1.8382 - val_mean_absolute_error: 1.8382
Epoch 418/1000
11/11 [==============================] - 0s 27ms/step - loss: 0.4233 - mean_absolute_error: 0.4233 - val_loss: 1.8922 - val_mean_absolute_error: 1.8922
Epoch 419/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3541 - mean_absolute_error: 0.3541 - val_loss: 1.8572 - val_mean_absolute_error: 1.8572
Epoch 420/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5325 - mean_absolute_error: 0.5325 - val_loss: 1.8191 - val_mean_absolute_error: 1.8191
Epoch 421/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4134 - mean_absolute_error: 0.4134 - val_loss: 1.8881 - val_mean_absolute_error: 1.8881
Epoch 422/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4957 - mean_absolute_error: 0.4957 - val_loss: 1.9190 - val_mean_absolute_error: 1.9190
Epoch 423/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4457 - mean_absolute_error: 0.4457 - val_loss: 1.8708 - val_mean_absolute_error: 1.8708
Epoch 424/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3656 - mean_absolute_error: 0.3656 - val_loss: 1.8579 - val_mean_absolute_error: 1.8579
Epoch 425/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4156 - mean_absolute_error: 0.4156 - val_loss: 1.9121 - val_mean_absolute_error: 1.9121
Epoch 426/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4027 - mean_absolute_error: 0.4027 - val_loss: 1.8725 - val_mean_absolute_error: 1.8725
Epoch 427/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4674 - mean_absolute_error: 0.4674 - val_loss: 1.9602 - val_mean_absolute_error: 1.9602
Epoch 428/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.3607 - mean_absolute_error: 0.3607 - val_loss: 1.9533 - val_mean_absolute_error: 1.9533
Epoch 429/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3941 - mean_absolute_error: 0.3941 - val_loss: 1.8755 - val_mean_absolute_error: 1.8755
Epoch 430/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.3249 - mean_absolute_error: 0.3249 - val_loss: 1.9263 - val_mean_absolute_error: 1.9263
Epoch 431/1000
11/11 [==============================] - 0s 27ms/step - loss: 0.4192 - mean_absolute_error: 0.4192 - val_loss: 1.8443 - val_mean_absolute_error: 1.8443
Epoch 432/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4140 - mean_absolute_error: 0.4140 - val_loss: 1.9092 - val_mean_absolute_error: 1.9092
Epoch 433/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5022 - mean_absolute_error: 0.5022 - val_loss: 1.8642 - val_mean_absolute_error: 1.8642
Epoch 434/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4255 - mean_absolute_error: 0.4255 - val_loss: 1.9351 - val_mean_absolute_error: 1.9351
Epoch 435/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3826 - mean_absolute_error: 0.3826 - val_loss: 1.8908 - val_mean_absolute_error: 1.8908
Epoch 436/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.3601 - mean_absolute_error: 0.3601 - val_loss: 1.8668 - val_mean_absolute_error: 1.8668
Epoch 437/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4010 - mean_absolute_error: 0.4010 - val_loss: 1.8758 - val_mean_absolute_error: 1.8758
Epoch 438/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3288 - mean_absolute_error: 0.3288 - val_loss: 1.8482 - val_mean_absolute_error: 1.8482
Epoch 439/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3538 - mean_absolute_error: 0.3538 - val_loss: 1.8621 - val_mean_absolute_error: 1.8621
Epoch 440/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3530 - mean_absolute_error: 0.3530 - val_loss: 1.9047 - val_mean_absolute_error: 1.9047
Epoch 441/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3643 - mean_absolute_error: 0.3643 - val_loss: 1.8988 - val_mean_absolute_error: 1.8988
Epoch 442/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.3111 - mean_absolute_error: 0.3111 - val_loss: 1.8874 - val_mean_absolute_error: 1.8874
Epoch 443/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3013 - mean_absolute_error: 0.3013 - val_loss: 1.8323 - val_mean_absolute_error: 1.8323
Epoch 444/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.3845 - mean_absolute_error: 0.3845 - val_loss: 1.9236 - val_mean_absolute_error: 1.9236
Epoch 445/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.4078 - mean_absolute_error: 0.4078 - val_loss: 1.9334 - val_mean_absolute_error: 1.9334
Epoch 446/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4354 - mean_absolute_error: 0.4354 - val_loss: 1.8886 - val_mean_absolute_error: 1.8886
Epoch 447/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4305 - mean_absolute_error: 0.4305 - val_loss: 1.8845 - val_mean_absolute_error: 1.8845
Epoch 448/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.3516 - mean_absolute_error: 0.3516 - val_loss: 1.9074 - val_mean_absolute_error: 1.9074
Epoch 449/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3753 - mean_absolute_error: 0.3753 - val_loss: 1.8254 - val_mean_absolute_error: 1.8254
Epoch 450/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3310 - mean_absolute_error: 0.3310 - val_loss: 1.8421 - val_mean_absolute_error: 1.8421
Epoch 451/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3319 - mean_absolute_error: 0.3319 - val_loss: 1.9033 - val_mean_absolute_error: 1.9033
Epoch 452/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3393 - mean_absolute_error: 0.3393 - val_loss: 1.8880 - val_mean_absolute_error: 1.8880
Epoch 453/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4565 - mean_absolute_error: 0.4565 - val_loss: 1.8540 - val_mean_absolute_error: 1.8540
Epoch 454/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4418 - mean_absolute_error: 0.4418 - val_loss: 1.9112 - val_mean_absolute_error: 1.9112
Epoch 455/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3646 - mean_absolute_error: 0.3646 - val_loss: 2.0318 - val_mean_absolute_error: 2.0318
Epoch 456/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5024 - mean_absolute_error: 0.5024 - val_loss: 1.9425 - val_mean_absolute_error: 1.9425
Epoch 457/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3616 - mean_absolute_error: 0.3616 - val_loss: 1.9227 - val_mean_absolute_error: 1.9227
Epoch 458/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3199 - mean_absolute_error: 0.3199 - val_loss: 1.8502 - val_mean_absolute_error: 1.8502
Epoch 459/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3137 - mean_absolute_error: 0.3137 - val_loss: 1.8434 - val_mean_absolute_error: 1.8434
Epoch 460/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3784 - mean_absolute_error: 0.3784 - val_loss: 1.9190 - val_mean_absolute_error: 1.9190
Epoch 461/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4220 - mean_absolute_error: 0.4220 - val_loss: 1.8691 - val_mean_absolute_error: 1.8691
Epoch 462/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3385 - mean_absolute_error: 0.3385 - val_loss: 1.8723 - val_mean_absolute_error: 1.8723
Epoch 463/1000
11/11 [==============================] - 0s 21ms/step - loss: 0.3703 - mean_absolute_error: 0.3703 - val_loss: 1.8967 - val_mean_absolute_error: 1.8967
Epoch 464/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3195 - mean_absolute_error: 0.3195 - val_loss: 1.8855 - val_mean_absolute_error: 1.8855
Epoch 465/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3119 - mean_absolute_error: 0.3119 - val_loss: 1.9140 - val_mean_absolute_error: 1.9140
Epoch 466/1000

11/11 [==============================] - 0s 16ms/step - loss: 0.4282 - mean_absolute_error: 0.4282 - val_loss: 1.8530 - val_mean_absolute_error: 1.8530
Epoch 467/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3579 - mean_absolute_error: 0.3579 - val_loss: 1.9214 - val_mean_absolute_error: 1.9214
Epoch 468/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3781 - mean_absolute_error: 0.3781 - val_loss: 2.0649 - val_mean_absolute_error: 2.0649
Epoch 469/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4193 - mean_absolute_error: 0.4193 - val_loss: 1.8505 - val_mean_absolute_error: 1.8505
Epoch 470/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.3331 - mean_absolute_error: 0.3331 - val_loss: 1.8660 - val_mean_absolute_error: 1.8660
Epoch 471/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3088 - mean_absolute_error: 0.3088 - val_loss: 1.8332 - val_mean_absolute_error: 1.8332
Epoch 472/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3125 - mean_absolute_error: 0.3125 - val_loss: 1.8676 - val_mean_absolute_error: 1.8676
Epoch 473/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.3794 - mean_absolute_error: 0.3794 - val_loss: 1.9940 - val_mean_absolute_error: 1.9940
Epoch 474/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4436 - mean_absolute_error: 0.4436 - val_loss: 1.8518 - val_mean_absolute_error: 1.8518
Epoch 475/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3577 - mean_absolute_error: 0.3577 - val_loss: 1.8724 - val_mean_absolute_error: 1.8724
Epoch 476/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3211 - mean_absolute_error: 0.3211 - val_loss: 1.8909 - val_mean_absolute_error: 1.8909
Epoch 477/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3271 - mean_absolute_error: 0.3271 - val_loss: 1.8966 - val_mean_absolute_error: 1.8966
Epoch 478/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3519 - mean_absolute_error: 0.3519 - val_loss: 1.8759 - val_mean_absolute_error: 1.8759
Epoch 479/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3479 - mean_absolute_error: 0.3479 - val_loss: 1.8599 - val_mean_absolute_error: 1.8599
Epoch 480/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.2985 - mean_absolute_error: 0.2985 - val_loss: 1.8928 - val_mean_absolute_error: 1.8928
Epoch 481/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3735 - mean_absolute_error: 0.3735 - val_loss: 1.8824 - val_mean_absolute_error: 1.8824
Epoch 482/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3378 - mean_absolute_error: 0.3378 - val_loss: 1.8570 - val_mean_absolute_error: 1.8570
Epoch 483/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3079 - mean_absolute_error: 0.3079 - val_loss: 1.8430 - val_mean_absolute_error: 1.8430
Epoch 484/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2802 - mean_absolute_error: 0.2802 - val_loss: 1.8824 - val_mean_absolute_error: 1.8824
Epoch 485/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3253 - mean_absolute_error: 0.3253 - val_loss: 1.8203 - val_mean_absolute_error: 1.8203
Epoch 486/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.3617 - mean_absolute_error: 0.3617 - val_loss: 1.8612 - val_mean_absolute_error: 1.8612
Epoch 487/1000
11/11 [==============================] - 0s 30ms/step - loss: 0.3343 - mean_absolute_error: 0.3343 - val_loss: 1.9080 - val_mean_absolute_error: 1.9080
Epoch 488/1000
11/11 [==============================] - 0s 24ms/step - loss: 0.3351 - mean_absolute_error: 0.3351 - val_loss: 1.8989 - val_mean_absolute_error: 1.8989
Epoch 489/1000
11/11 [==============================] - 0s 41ms/step - loss: 0.3699 - mean_absolute_error: 0.3699 - val_loss: 1.9229 - val_mean_absolute_error: 1.9229
Epoch 490/1000
11/11 [==============================] - 1s 56ms/step - loss: 0.3164 - mean_absolute_error: 0.3164 - val_loss: 1.8889 - val_mean_absolute_error: 1.8889
Epoch 491/1000
11/11 [==============================] - 0s 25ms/step - loss: 0.2909 - mean_absolute_error: 0.2909 - val_loss: 1.8863 - val_mean_absolute_error: 1.8863
Epoch 492/1000
11/11 [==============================] - 0s 43ms/step - loss: 0.3864 - mean_absolute_error: 0.3864 - val_loss: 1.9380 - val_mean_absolute_error: 1.9380
Epoch 493/1000
11/11 [==============================] - 0s 28ms/step - loss: 0.4140 - mean_absolute_error: 0.4140 - val_loss: 1.8771 - val_mean_absolute_error: 1.8771
Epoch 494/1000
11/11 [==============================] - 0s 40ms/step - loss: 0.3764 - mean_absolute_error: 0.3764 - val_loss: 1.9156 - val_mean_absolute_error: 1.9156
Epoch 495/1000
11/11 [==============================] - 1s 52ms/step - loss: 0.3609 - mean_absolute_error: 0.3609 - val_loss: 1.8572 - val_mean_absolute_error: 1.8572
Epoch 496/1000
11/11 [==============================] - 0s 31ms/step - loss: 0.3518 - mean_absolute_error: 0.3518 - val_loss: 1.8808 - val_mean_absolute_error: 1.8808
Epoch 497/1000
11/11 [==============================] - 0s 31ms/step - loss: 0.3243 - mean_absolute_error: 0.3243 - val_loss: 1.8922 - val_mean_absolute_error: 1.8922
Epoch 498/1000
11/11 [==============================] - 0s 27ms/step - loss: 0.3025 - mean_absolute_error: 0.3025 - val_loss: 1.9277 - val_mean_absolute_error: 1.9277
Epoch 499/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.3839 - mean_absolute_error: 0.3839 - val_loss: 1.9242 - val_mean_absolute_error: 1.9242
Epoch 500/1000
11/11 [==============================] - 0s 24ms/step - loss: 0.3708 - mean_absolute_error: 0.3708 - val_loss: 1.9375 - val_mean_absolute_error: 1.9375
Epoch 501/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.3293 - mean_absolute_error: 0.3293 - val_loss: 1.8912 - val_mean_absolute_error: 1.8912
Epoch 502/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3276 - mean_absolute_error: 0.3276 - val_loss: 1.9004 - val_mean_absolute_error: 1.9004
Epoch 503/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2904 - mean_absolute_error: 0.2904 - val_loss: 1.8984 - val_mean_absolute_error: 1.8984
Epoch 504/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2951 - mean_absolute_error: 0.2951 - val_loss: 1.8578 - val_mean_absolute_error: 1.8578
Epoch 505/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4234 - mean_absolute_error: 0.4234 - val_loss: 2.0346 - val_mean_absolute_error: 2.0346
Epoch 506/1000
11/11 [==============================] - 0s 26ms/step - loss: 0.5697 - mean_absolute_error: 0.5697 - val_loss: 2.0277 - val_mean_absolute_error: 2.0277
Epoch 507/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4989 - mean_absolute_error: 0.4989 - val_loss: 2.0037 - val_mean_absolute_error: 2.0037
Epoch 508/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4621 - mean_absolute_error: 0.4621 - val_loss: 1.8860 - val_mean_absolute_error: 1.8860
Epoch 509/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4531 - mean_absolute_error: 0.4531 - val_loss: 1.9245 - val_mean_absolute_error: 1.9245
Epoch 510/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4304 - mean_absolute_error: 0.4304 - val_loss: 1.9300 - val_mean_absolute_error: 1.9300
Epoch 511/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3354 - mean_absolute_error: 0.3354 - val_loss: 1.8810 - val_mean_absolute_error: 1.8810
Epoch 512/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3090 - mean_absolute_error: 0.3090 - val_loss: 1.8407 - val_mean_absolute_error: 1.8407
Epoch 513/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3235 - mean_absolute_error: 0.3235 - val_loss: 1.9074 - val_mean_absolute_error: 1.9074
Epoch 514/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2975 - mean_absolute_error: 0.2975 - val_loss: 1.8602 - val_mean_absolute_error: 1.8602
Epoch 515/1000

11/11 [==============================] - 0s 16ms/step - loss: 0.3003 - mean_absolute_error: 0.3003 - val_loss: 1.8363 - val_mean_absolute_error: 1.8363
Epoch 516/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3442 - mean_absolute_error: 0.3442 - val_loss: 1.8647 - val_mean_absolute_error: 1.8647
Epoch 517/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.3489 - mean_absolute_error: 0.3489 - val_loss: 1.9500 - val_mean_absolute_error: 1.9500
Epoch 518/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4215 - mean_absolute_error: 0.4215 - val_loss: 1.8528 - val_mean_absolute_error: 1.8528
Epoch 519/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3608 - mean_absolute_error: 0.3608 - val_loss: 1.8865 - val_mean_absolute_error: 1.8865
Epoch 520/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.3598 - mean_absolute_error: 0.3598 - val_loss: 1.9093 - val_mean_absolute_error: 1.9093
Epoch 521/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2939 - mean_absolute_error: 0.2939 - val_loss: 1.8645 - val_mean_absolute_error: 1.8645
Epoch 522/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.3684 - mean_absolute_error: 0.3684 - val_loss: 2.0165 - val_mean_absolute_error: 2.0165
Epoch 523/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4451 - mean_absolute_error: 0.4451 - val_loss: 1.8117 - val_mean_absolute_error: 1.8117
Epoch 524/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4611 - mean_absolute_error: 0.4611 - val_loss: 1.9218 - val_mean_absolute_error: 1.9218
Epoch 525/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3369 - mean_absolute_error: 0.3369 - val_loss: 1.8812 - val_mean_absolute_error: 1.8812
Epoch 526/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4254 - mean_absolute_error: 0.4254 - val_loss: 1.8525 - val_mean_absolute_error: 1.8525
Epoch 527/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4432 - mean_absolute_error: 0.4432 - val_loss: 1.9573 - val_mean_absolute_error: 1.9573
Epoch 528/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3250 - mean_absolute_error: 0.3250 - val_loss: 1.8995 - val_mean_absolute_error: 1.8995
Epoch 529/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3456 - mean_absolute_error: 0.3456 - val_loss: 1.8721 - val_mean_absolute_error: 1.8721
Epoch 530/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.3724 - mean_absolute_error: 0.3724 - val_loss: 1.9253 - val_mean_absolute_error: 1.9253
Epoch 531/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3090 - mean_absolute_error: 0.3090 - val_loss: 1.9132 - val_mean_absolute_error: 1.9132
Epoch 532/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3134 - mean_absolute_error: 0.3134 - val_loss: 1.8703 - val_mean_absolute_error: 1.8703
Epoch 533/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2955 - mean_absolute_error: 0.2955 - val_loss: 1.8879 - val_mean_absolute_error: 1.8879
Epoch 534/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3274 - mean_absolute_error: 0.3274 - val_loss: 1.9106 - val_mean_absolute_error: 1.9106
Epoch 535/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3047 - mean_absolute_error: 0.3047 - val_loss: 1.9725 - val_mean_absolute_error: 1.9725
Epoch 536/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3429 - mean_absolute_error: 0.3429 - val_loss: 1.9308 - val_mean_absolute_error: 1.9308
Epoch 537/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3544 - mean_absolute_error: 0.3544 - val_loss: 1.8623 - val_mean_absolute_error: 1.8623
Epoch 538/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3080 - mean_absolute_error: 0.3080 - val_loss: 1.8656 - val_mean_absolute_error: 1.8656
Epoch 539/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3243 - mean_absolute_error: 0.3243 - val_loss: 1.8793 - val_mean_absolute_error: 1.8793
Epoch 540/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3364 - mean_absolute_error: 0.3364 - val_loss: 1.9268 - val_mean_absolute_error: 1.9268
Epoch 541/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3032 - mean_absolute_error: 0.3032 - val_loss: 1.9076 - val_mean_absolute_error: 1.9076
Epoch 542/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.3148 - mean_absolute_error: 0.3148 - val_loss: 1.9051 - val_mean_absolute_error: 1.9051
Epoch 543/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2862 - mean_absolute_error: 0.2862 - val_loss: 1.8663 - val_mean_absolute_error: 1.8663
Epoch 544/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4203 - mean_absolute_error: 0.4203 - val_loss: 1.9096 - val_mean_absolute_error: 1.9096
Epoch 545/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3384 - mean_absolute_error: 0.3384 - val_loss: 1.8863 - val_mean_absolute_error: 1.8863
Epoch 546/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3176 - mean_absolute_error: 0.3176 - val_loss: 1.8592 - val_mean_absolute_error: 1.8592
Epoch 547/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3390 - mean_absolute_error: 0.3390 - val_loss: 1.8729 - val_mean_absolute_error: 1.8729
Epoch 548/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3465 - mean_absolute_error: 0.3465 - val_loss: 1.8889 - val_mean_absolute_error: 1.8889
Epoch 549/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3733 - mean_absolute_error: 0.3733 - val_loss: 1.9334 - val_mean_absolute_error: 1.9334
Epoch 550/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3051 - mean_absolute_error: 0.3051 - val_loss: 1.8792 - val_mean_absolute_error: 1.8792
Epoch 551/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3017 - mean_absolute_error: 0.3017 - val_loss: 1.9470 - val_mean_absolute_error: 1.9470
Epoch 552/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3491 - mean_absolute_error: 0.3491 - val_loss: 1.8854 - val_mean_absolute_error: 1.8854
Epoch 553/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3153 - mean_absolute_error: 0.3153 - val_loss: 1.8817 - val_mean_absolute_error: 1.8817
Epoch 554/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2869 - mean_absolute_error: 0.2869 - val_loss: 1.8772 - val_mean_absolute_error: 1.8772
Epoch 555/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2647 - mean_absolute_error: 0.2647 - val_loss: 1.9736 - val_mean_absolute_error: 1.9736
Epoch 556/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3569 - mean_absolute_error: 0.3569 - val_loss: 1.8417 - val_mean_absolute_error: 1.8417
Epoch 557/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2786 - mean_absolute_error: 0.2786 - val_loss: 1.9564 - val_mean_absolute_error: 1.9564
Epoch 558/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3091 - mean_absolute_error: 0.3091 - val_loss: 1.9014 - val_mean_absolute_error: 1.9014
Epoch 559/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3151 - mean_absolute_error: 0.3151 - val_loss: 1.9091 - val_mean_absolute_error: 1.9091
Epoch 560/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3082 - mean_absolute_error: 0.3082 - val_loss: 1.8751 - val_mean_absolute_error: 1.8751
Epoch 561/1000
11/11 [==============================] - 0s 27ms/step - loss: 0.3075 - mean_absolute_error: 0.3075 - val_loss: 1.8903 - val_mean_absolute_error: 1.8903
Epoch 562/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.2816 - mean_absolute_error: 0.2816 - val_loss: 1.9114 - val_mean_absolute_error: 1.9114
Epoch 563/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2828 - mean_absolute_error: 0.2828 - val_loss: 1.8431 - val_mean_absolute_error: 1.8431
Epoch 564/1000

11/11 [==============================] - 0s 19ms/step - loss: 0.2953 - mean_absolute_error: 0.2953 - val_loss: 1.9014 - val_mean_absolute_error: 1.9014
Epoch 565/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.3317 - mean_absolute_error: 0.3317 - val_loss: 1.8704 - val_mean_absolute_error: 1.8704
Epoch 566/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3671 - mean_absolute_error: 0.3671 - val_loss: 1.9593 - val_mean_absolute_error: 1.9593
Epoch 567/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3984 - mean_absolute_error: 0.3984 - val_loss: 1.8605 - val_mean_absolute_error: 1.8605
Epoch 568/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3615 - mean_absolute_error: 0.3615 - val_loss: 1.8994 - val_mean_absolute_error: 1.8994
Epoch 569/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3167 - mean_absolute_error: 0.3167 - val_loss: 1.9782 - val_mean_absolute_error: 1.9782
Epoch 570/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.4297 - mean_absolute_error: 0.4297 - val_loss: 1.9050 - val_mean_absolute_error: 1.9050
Epoch 571/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3128 - mean_absolute_error: 0.3128 - val_loss: 1.8886 - val_mean_absolute_error: 1.8886
Epoch 572/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.3407 - mean_absolute_error: 0.3407 - val_loss: 1.8511 - val_mean_absolute_error: 1.8511
Epoch 573/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3725 - mean_absolute_error: 0.3725 - val_loss: 2.0475 - val_mean_absolute_error: 2.0475
Epoch 574/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5008 - mean_absolute_error: 0.5008 - val_loss: 1.9393 - val_mean_absolute_error: 1.9393
Epoch 575/1000
11/11 [==============================] - 0s 24ms/step - loss: 0.3426 - mean_absolute_error: 0.3426 - val_loss: 1.9039 - val_mean_absolute_error: 1.9039
Epoch 576/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.2903 - mean_absolute_error: 0.2903 - val_loss: 1.9036 - val_mean_absolute_error: 1.9036
Epoch 577/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3613 - mean_absolute_error: 0.3613 - val_loss: 1.9074 - val_mean_absolute_error: 1.9074
Epoch 578/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.3743 - mean_absolute_error: 0.3743 - val_loss: 1.9111 - val_mean_absolute_error: 1.9111
Epoch 579/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2953 - mean_absolute_error: 0.2953 - val_loss: 1.8630 - val_mean_absolute_error: 1.8630
Epoch 580/1000
11/11 [==============================] - 0s 30ms/step - loss: 0.3047 - mean_absolute_error: 0.3047 - val_loss: 1.9103 - val_mean_absolute_error: 1.9103
Epoch 581/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3266 - mean_absolute_error: 0.3266 - val_loss: 1.8919 - val_mean_absolute_error: 1.8919
Epoch 582/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3034 - mean_absolute_error: 0.3034 - val_loss: 1.8866 - val_mean_absolute_error: 1.8866
Epoch 583/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2972 - mean_absolute_error: 0.2972 - val_loss: 1.8545 - val_mean_absolute_error: 1.8545
Epoch 584/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4002 - mean_absolute_error: 0.4002 - val_loss: 1.9754 - val_mean_absolute_error: 1.9754
Epoch 585/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3684 - mean_absolute_error: 0.3684 - val_loss: 1.9119 - val_mean_absolute_error: 1.9119
Epoch 586/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3335 - mean_absolute_error: 0.3335 - val_loss: 1.8670 - val_mean_absolute_error: 1.8670
Epoch 587/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3428 - mean_absolute_error: 0.3428 - val_loss: 1.9075 - val_mean_absolute_error: 1.9075
Epoch 588/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3838 - mean_absolute_error: 0.3838 - val_loss: 1.9409 - val_mean_absolute_error: 1.9409
Epoch 589/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3844 - mean_absolute_error: 0.3844 - val_loss: 1.8977 - val_mean_absolute_error: 1.8977
Epoch 590/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3459 - mean_absolute_error: 0.3459 - val_loss: 1.9101 - val_mean_absolute_error: 1.9101
Epoch 591/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2789 - mean_absolute_error: 0.2789 - val_loss: 1.9443 - val_mean_absolute_error: 1.9443
Epoch 592/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3324 - mean_absolute_error: 0.3324 - val_loss: 1.9901 - val_mean_absolute_error: 1.9901
Epoch 593/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3926 - mean_absolute_error: 0.3926 - val_loss: 1.8804 - val_mean_absolute_error: 1.8804
Epoch 594/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.3509 - mean_absolute_error: 0.3509 - val_loss: 1.8838 - val_mean_absolute_error: 1.8838
Epoch 595/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3049 - mean_absolute_error: 0.3049 - val_loss: 1.8758 - val_mean_absolute_error: 1.8758
Epoch 596/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2903 - mean_absolute_error: 0.2903 - val_loss: 1.8626 - val_mean_absolute_error: 1.8626
Epoch 597/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2775 - mean_absolute_error: 0.2775 - val_loss: 1.8881 - val_mean_absolute_error: 1.8881
Epoch 598/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3171 - mean_absolute_error: 0.3171 - val_loss: 1.9128 - val_mean_absolute_error: 1.9128
Epoch 599/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.3344 - mean_absolute_error: 0.3344 - val_loss: 1.8742 - val_mean_absolute_error: 1.8742
Epoch 600/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2829 - mean_absolute_error: 0.2829 - val_loss: 1.9347 - val_mean_absolute_error: 1.9347
Epoch 601/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2945 - mean_absolute_error: 0.2945 - val_loss: 1.9359 - val_mean_absolute_error: 1.9359
Epoch 602/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2979 - mean_absolute_error: 0.2979 - val_loss: 1.8682 - val_mean_absolute_error: 1.8682
Epoch 603/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3228 - mean_absolute_error: 0.3228 - val_loss: 1.9387 - val_mean_absolute_error: 1.9387
Epoch 604/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.3066 - mean_absolute_error: 0.3066 - val_loss: 1.8762 - val_mean_absolute_error: 1.8762
Epoch 605/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2851 - mean_absolute_error: 0.2851 - val_loss: 1.8793 - val_mean_absolute_error: 1.8793
Epoch 606/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3061 - mean_absolute_error: 0.3061 - val_loss: 1.9186 - val_mean_absolute_error: 1.9186
Epoch 607/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.3064 - mean_absolute_error: 0.3064 - val_loss: 1.9043 - val_mean_absolute_error: 1.9043
Epoch 608/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3072 - mean_absolute_error: 0.3072 - val_loss: 1.9002 - val_mean_absolute_error: 1.9002
Epoch 609/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.3960 - mean_absolute_error: 0.3960 - val_loss: 1.8526 - val_mean_absolute_error: 1.8526
Epoch 610/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3184 - mean_absolute_error: 0.3184 - val_loss: 1.8542 - val_mean_absolute_error: 1.8542
Epoch 611/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3067 - mean_absolute_error: 0.3067 - val_loss: 1.9166 - val_mean_absolute_error: 1.9166
Epoch 612/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3592 - mean_absolute_error: 0.3592 - val_loss: 1.9145 - val_mean_absolute_error: 1.9145
Epoch 613/1000

11/11 [==============================] - 0s 19ms/step - loss: 0.3660 - mean_absolute_error: 0.3660 - val_loss: 1.9115 - val_mean_absolute_error: 1.9115
Epoch 614/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3237 - mean_absolute_error: 0.3237 - val_loss: 1.8801 - val_mean_absolute_error: 1.8801
Epoch 615/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2947 - mean_absolute_error: 0.2947 - val_loss: 1.9014 - val_mean_absolute_error: 1.9014
Epoch 616/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2837 - mean_absolute_error: 0.2837 - val_loss: 1.9613 - val_mean_absolute_error: 1.9613
Epoch 617/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2998 - mean_absolute_error: 0.2998 - val_loss: 1.8915 - val_mean_absolute_error: 1.8915
Epoch 618/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2619 - mean_absolute_error: 0.2619 - val_loss: 1.9134 - val_mean_absolute_error: 1.9134
Epoch 619/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.2723 - mean_absolute_error: 0.2723 - val_loss: 1.8813 - val_mean_absolute_error: 1.8813
Epoch 620/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2934 - mean_absolute_error: 0.2934 - val_loss: 1.8956 - val_mean_absolute_error: 1.8956
Epoch 621/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3288 - mean_absolute_error: 0.3288 - val_loss: 1.8442 - val_mean_absolute_error: 1.8442
Epoch 622/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2968 - mean_absolute_error: 0.2968 - val_loss: 1.8991 - val_mean_absolute_error: 1.8991
Epoch 623/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2995 - mean_absolute_error: 0.2995 - val_loss: 1.8815 - val_mean_absolute_error: 1.8815
Epoch 624/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3008 - mean_absolute_error: 0.3008 - val_loss: 1.8835 - val_mean_absolute_error: 1.8835
Epoch 625/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2885 - mean_absolute_error: 0.2885 - val_loss: 1.8956 - val_mean_absolute_error: 1.8956
Epoch 626/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3433 - mean_absolute_error: 0.3433 - val_loss: 1.9246 - val_mean_absolute_error: 1.9246
Epoch 627/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3188 - mean_absolute_error: 0.3188 - val_loss: 1.9345 - val_mean_absolute_error: 1.9345
Epoch 628/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3356 - mean_absolute_error: 0.3356 - val_loss: 1.9050 - val_mean_absolute_error: 1.9050
Epoch 629/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2797 - mean_absolute_error: 0.2797 - val_loss: 1.8822 - val_mean_absolute_error: 1.8822
Epoch 630/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2903 - mean_absolute_error: 0.2903 - val_loss: 1.8903 - val_mean_absolute_error: 1.8903
Epoch 631/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3161 - mean_absolute_error: 0.3161 - val_loss: 1.8967 - val_mean_absolute_error: 1.8967
Epoch 632/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2986 - mean_absolute_error: 0.2986 - val_loss: 1.8633 - val_mean_absolute_error: 1.8633
Epoch 633/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3173 - mean_absolute_error: 0.3173 - val_loss: 1.8910 - val_mean_absolute_error: 1.8910
Epoch 634/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2849 - mean_absolute_error: 0.2849 - val_loss: 1.9480 - val_mean_absolute_error: 1.9480
Epoch 635/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3549 - mean_absolute_error: 0.3549 - val_loss: 1.8675 - val_mean_absolute_error: 1.8675
Epoch 636/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2944 - mean_absolute_error: 0.2944 - val_loss: 1.8645 - val_mean_absolute_error: 1.8645
Epoch 637/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3257 - mean_absolute_error: 0.3257 - val_loss: 1.9574 - val_mean_absolute_error: 1.9574
Epoch 638/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3138 - mean_absolute_error: 0.3138 - val_loss: 1.9081 - val_mean_absolute_error: 1.9081
Epoch 639/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3210 - mean_absolute_error: 0.3210 - val_loss: 1.9176 - val_mean_absolute_error: 1.9176
Epoch 640/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3686 - mean_absolute_error: 0.3686 - val_loss: 1.9768 - val_mean_absolute_error: 1.9768
Epoch 641/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4002 - mean_absolute_error: 0.4002 - val_loss: 1.8592 - val_mean_absolute_error: 1.8592
Epoch 642/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3325 - mean_absolute_error: 0.3325 - val_loss: 1.9189 - val_mean_absolute_error: 1.9189
Epoch 643/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2943 - mean_absolute_error: 0.2943 - val_loss: 1.8824 - val_mean_absolute_error: 1.8824
Epoch 644/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3756 - mean_absolute_error: 0.3756 - val_loss: 1.8785 - val_mean_absolute_error: 1.8785
Epoch 645/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3328 - mean_absolute_error: 0.3328 - val_loss: 1.8973 - val_mean_absolute_error: 1.8973
Epoch 646/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2938 - mean_absolute_error: 0.2938 - val_loss: 1.8505 - val_mean_absolute_error: 1.8505
Epoch 647/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3351 - mean_absolute_error: 0.3351 - val_loss: 1.9763 - val_mean_absolute_error: 1.9763
Epoch 648/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4873 - mean_absolute_error: 0.4873 - val_loss: 1.9051 - val_mean_absolute_error: 1.9051
Epoch 649/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3479 - mean_absolute_error: 0.3479 - val_loss: 1.9437 - val_mean_absolute_error: 1.9437
Epoch 650/1000
11/11 [==============================] - 0s 24ms/step - loss: 0.2905 - mean_absolute_error: 0.2905 - val_loss: 1.9788 - val_mean_absolute_error: 1.9788
Epoch 651/1000
11/11 [==============================] - 0s 21ms/step - loss: 0.2835 - mean_absolute_error: 0.2835 - val_loss: 1.9152 - val_mean_absolute_error: 1.9152
Epoch 652/1000
11/11 [==============================] - 0s 24ms/step - loss: 0.2849 - mean_absolute_error: 0.2849 - val_loss: 1.9017 - val_mean_absolute_error: 1.9017
Epoch 653/1000
11/11 [==============================] - 0s 27ms/step - loss: 0.3157 - mean_absolute_error: 0.3157 - val_loss: 1.9123 - val_mean_absolute_error: 1.9123
Epoch 654/1000
11/11 [==============================] - 0s 29ms/step - loss: 0.3109 - mean_absolute_error: 0.3109 - val_loss: 1.9239 - val_mean_absolute_error: 1.9239
Epoch 655/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.3510 - mean_absolute_error: 0.3510 - val_loss: 1.9118 - val_mean_absolute_error: 1.9118
Epoch 656/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3992 - mean_absolute_error: 0.3992 - val_loss: 1.9858 - val_mean_absolute_error: 1.9858
Epoch 657/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3387 - mean_absolute_error: 0.3387 - val_loss: 1.9213 - val_mean_absolute_error: 1.9213
Epoch 658/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.2963 - mean_absolute_error: 0.2963 - val_loss: 1.9304 - val_mean_absolute_error: 1.9304
Epoch 659/1000
11/11 [==============================] - 0s 21ms/step - loss: 0.2888 - mean_absolute_error: 0.2888 - val_loss: 1.8766 - val_mean_absolute_error: 1.8766
Epoch 660/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3515 - mean_absolute_error: 0.3515 - val_loss: 1.9463 - val_mean_absolute_error: 1.9463
Epoch 661/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3117 - mean_absolute_error: 0.3117 - val_loss: 1.9603 - val_mean_absolute_error: 1.9603
Epoch 662/1000

11/11 [==============================] - 0s 26ms/step - loss: 0.3839 - mean_absolute_error: 0.3839 - val_loss: 1.8768 - val_mean_absolute_error: 1.8768
Epoch 663/1000
11/11 [==============================] - 0s 30ms/step - loss: 0.4292 - mean_absolute_error: 0.4292 - val_loss: 1.9906 - val_mean_absolute_error: 1.9906
Epoch 664/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.3408 - mean_absolute_error: 0.3408 - val_loss: 1.9159 - val_mean_absolute_error: 1.9159
Epoch 665/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3089 - mean_absolute_error: 0.3089 - val_loss: 1.8985 - val_mean_absolute_error: 1.8985
Epoch 666/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2804 - mean_absolute_error: 0.2804 - val_loss: 1.9457 - val_mean_absolute_error: 1.9457
Epoch 667/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2518 - mean_absolute_error: 0.2518 - val_loss: 1.9640 - val_mean_absolute_error: 1.9640
Epoch 668/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2744 - mean_absolute_error: 0.2744 - val_loss: 1.9301 - val_mean_absolute_error: 1.9301
Epoch 669/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2723 - mean_absolute_error: 0.2723 - val_loss: 1.9044 - val_mean_absolute_error: 1.9044
Epoch 670/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3578 - mean_absolute_error: 0.3578 - val_loss: 1.8915 - val_mean_absolute_error: 1.8915
Epoch 671/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3351 - mean_absolute_error: 0.3351 - val_loss: 1.9249 - val_mean_absolute_error: 1.9249
Epoch 672/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2914 - mean_absolute_error: 0.2914 - val_loss: 1.9250 - val_mean_absolute_error: 1.9250
Epoch 673/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2574 - mean_absolute_error: 0.2574 - val_loss: 1.9200 - val_mean_absolute_error: 1.9200
Epoch 674/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2530 - mean_absolute_error: 0.2530 - val_loss: 1.9548 - val_mean_absolute_error: 1.9548
Epoch 675/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3121 - mean_absolute_error: 0.3121 - val_loss: 1.8288 - val_mean_absolute_error: 1.8288
Epoch 676/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3527 - mean_absolute_error: 0.3527 - val_loss: 1.8591 - val_mean_absolute_error: 1.8591
Epoch 677/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2870 - mean_absolute_error: 0.2870 - val_loss: 1.9458 - val_mean_absolute_error: 1.9458
Epoch 678/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3131 - mean_absolute_error: 0.3131 - val_loss: 1.9649 - val_mean_absolute_error: 1.9649
Epoch 679/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3360 - mean_absolute_error: 0.3360 - val_loss: 1.8848 - val_mean_absolute_error: 1.8848
Epoch 680/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3069 - mean_absolute_error: 0.3069 - val_loss: 1.9000 - val_mean_absolute_error: 1.9000
Epoch 681/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3048 - mean_absolute_error: 0.3048 - val_loss: 1.8805 - val_mean_absolute_error: 1.8805
Epoch 682/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2843 - mean_absolute_error: 0.2843 - val_loss: 1.8754 - val_mean_absolute_error: 1.8754
Epoch 683/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3175 - mean_absolute_error: 0.3175 - val_loss: 1.9483 - val_mean_absolute_error: 1.9483
Epoch 684/1000
11/11 [==============================] - 0s 27ms/step - loss: 0.3155 - mean_absolute_error: 0.3155 - val_loss: 1.8989 - val_mean_absolute_error: 1.8989
Epoch 685/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.3304 - mean_absolute_error: 0.3304 - val_loss: 1.9135 - val_mean_absolute_error: 1.9135
Epoch 686/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3155 - mean_absolute_error: 0.3155 - val_loss: 1.9205 - val_mean_absolute_error: 1.9205
Epoch 687/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.2883 - mean_absolute_error: 0.2883 - val_loss: 1.8986 - val_mean_absolute_error: 1.8986
Epoch 688/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2510 - mean_absolute_error: 0.2510 - val_loss: 1.9103 - val_mean_absolute_error: 1.9103
Epoch 689/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3088 - mean_absolute_error: 0.3088 - val_loss: 1.9583 - val_mean_absolute_error: 1.9583
Epoch 690/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.3032 - mean_absolute_error: 0.3032 - val_loss: 1.9471 - val_mean_absolute_error: 1.9471
Epoch 691/1000
11/11 [==============================] - 0s 26ms/step - loss: 0.2519 - mean_absolute_error: 0.2519 - val_loss: 1.9366 - val_mean_absolute_error: 1.9366
Epoch 692/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2813 - mean_absolute_error: 0.2813 - val_loss: 1.9010 - val_mean_absolute_error: 1.9010
Epoch 693/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2502 - mean_absolute_error: 0.2502 - val_loss: 1.8874 - val_mean_absolute_error: 1.8874
Epoch 694/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2979 - mean_absolute_error: 0.2979 - val_loss: 1.8667 - val_mean_absolute_error: 1.8667
Epoch 695/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4062 - mean_absolute_error: 0.4062 - val_loss: 1.9335 - val_mean_absolute_error: 1.9335
Epoch 696/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3990 - mean_absolute_error: 0.3990 - val_loss: 1.9697 - val_mean_absolute_error: 1.9697
Epoch 697/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2729 - mean_absolute_error: 0.2729 - val_loss: 1.9421 - val_mean_absolute_error: 1.9421
Epoch 698/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2763 - mean_absolute_error: 0.2763 - val_loss: 1.9380 - val_mean_absolute_error: 1.9380
Epoch 699/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.3037 - mean_absolute_error: 0.3037 - val_loss: 1.9516 - val_mean_absolute_error: 1.9516
Epoch 700/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2952 - mean_absolute_error: 0.2952 - val_loss: 1.8641 - val_mean_absolute_error: 1.8641
Epoch 701/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2849 - mean_absolute_error: 0.2849 - val_loss: 1.9568 - val_mean_absolute_error: 1.9568
Epoch 702/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2926 - mean_absolute_error: 0.2926 - val_loss: 1.8450 - val_mean_absolute_error: 1.8450
Epoch 703/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3017 - mean_absolute_error: 0.3017 - val_loss: 1.8893 - val_mean_absolute_error: 1.8893
Epoch 704/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2858 - mean_absolute_error: 0.2858 - val_loss: 1.9337 - val_mean_absolute_error: 1.9337
Epoch 705/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2450 - mean_absolute_error: 0.2450 - val_loss: 1.9041 - val_mean_absolute_error: 1.9041
Epoch 706/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2400 - mean_absolute_error: 0.2400 - val_loss: 1.8948 - val_mean_absolute_error: 1.8948
Epoch 707/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3712 - mean_absolute_error: 0.3712 - val_loss: 2.0029 - val_mean_absolute_error: 2.0029
Epoch 708/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3500 - mean_absolute_error: 0.3500 - val_loss: 1.9559 - val_mean_absolute_error: 1.9559
Epoch 709/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4305 - mean_absolute_error: 0.4305 - val_loss: 2.1409 - val_mean_absolute_error: 2.1409
Epoch 710/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.4904 - mean_absolute_error: 0.4904 - val_loss: 2.0426 - val_mean_absolute_error: 2.0426
Epoch 711/1000

11/11 [==============================] - 0s 16ms/step - loss: 0.3773 - mean_absolute_error: 0.3773 - val_loss: 1.9019 - val_mean_absolute_error: 1.9019
Epoch 712/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2724 - mean_absolute_error: 0.2724 - val_loss: 1.9123 - val_mean_absolute_error: 1.9123
Epoch 713/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3094 - mean_absolute_error: 0.3094 - val_loss: 2.0012 - val_mean_absolute_error: 2.0012
Epoch 714/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3323 - mean_absolute_error: 0.3323 - val_loss: 1.9483 - val_mean_absolute_error: 1.9483
Epoch 715/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3599 - mean_absolute_error: 0.3599 - val_loss: 1.9018 - val_mean_absolute_error: 1.9018
Epoch 716/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3246 - mean_absolute_error: 0.3246 - val_loss: 1.9712 - val_mean_absolute_error: 1.9712
Epoch 717/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3488 - mean_absolute_error: 0.3488 - val_loss: 1.9112 - val_mean_absolute_error: 1.9112
Epoch 718/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2999 - mean_absolute_error: 0.2999 - val_loss: 1.9914 - val_mean_absolute_error: 1.9914
Epoch 719/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3242 - mean_absolute_error: 0.3242 - val_loss: 1.9216 - val_mean_absolute_error: 1.9216
Epoch 720/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3219 - mean_absolute_error: 0.3219 - val_loss: 1.8922 - val_mean_absolute_error: 1.8922
Epoch 721/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.3598 - mean_absolute_error: 0.3598 - val_loss: 1.9113 - val_mean_absolute_error: 1.9113
Epoch 722/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2982 - mean_absolute_error: 0.2982 - val_loss: 1.8625 - val_mean_absolute_error: 1.8625
Epoch 723/1000
11/11 [==============================] - 0s 38ms/step - loss: 0.2939 - mean_absolute_error: 0.2939 - val_loss: 1.9026 - val_mean_absolute_error: 1.9026
Epoch 724/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2664 - mean_absolute_error: 0.2664 - val_loss: 1.9765 - val_mean_absolute_error: 1.9765
Epoch 725/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3657 - mean_absolute_error: 0.3657 - val_loss: 1.8889 - val_mean_absolute_error: 1.8889
Epoch 726/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.3686 - mean_absolute_error: 0.3686 - val_loss: 1.9132 - val_mean_absolute_error: 1.9132
Epoch 727/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.3144 - mean_absolute_error: 0.3144 - val_loss: 1.8974 - val_mean_absolute_error: 1.8974
Epoch 728/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2827 - mean_absolute_error: 0.2827 - val_loss: 1.9516 - val_mean_absolute_error: 1.9516
Epoch 729/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2629 - mean_absolute_error: 0.2629 - val_loss: 1.9560 - val_mean_absolute_error: 1.9560
Epoch 730/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3270 - mean_absolute_error: 0.3270 - val_loss: 1.9015 - val_mean_absolute_error: 1.9015
Epoch 731/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4437 - mean_absolute_error: 0.4437 - val_loss: 1.8769 - val_mean_absolute_error: 1.8769
Epoch 732/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.3297 - mean_absolute_error: 0.3297 - val_loss: 1.8797 - val_mean_absolute_error: 1.8797
Epoch 733/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.3851 - mean_absolute_error: 0.3851 - val_loss: 1.9182 - val_mean_absolute_error: 1.9182
Epoch 734/1000
11/11 [==============================] - 0s 45ms/step - loss: 0.2639 - mean_absolute_error: 0.2639 - val_loss: 1.9124 - val_mean_absolute_error: 1.9124
Epoch 735/1000
11/11 [==============================] - 0s 47ms/step - loss: 0.2744 - mean_absolute_error: 0.2744 - val_loss: 1.8691 - val_mean_absolute_error: 1.8691
Epoch 736/1000
11/11 [==============================] - 0s 47ms/step - loss: 0.3252 - mean_absolute_error: 0.3252 - val_loss: 1.8750 - val_mean_absolute_error: 1.8750
Epoch 737/1000
11/11 [==============================] - 0s 27ms/step - loss: 0.3173 - mean_absolute_error: 0.3173 - val_loss: 1.9568 - val_mean_absolute_error: 1.9568
Epoch 738/1000
11/11 [==============================] - 0s 27ms/step - loss: 0.2956 - mean_absolute_error: 0.2956 - val_loss: 1.9165 - val_mean_absolute_error: 1.9165
Epoch 739/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.2747 - mean_absolute_error: 0.2747 - val_loss: 1.9513 - val_mean_absolute_error: 1.9513
Epoch 740/1000
11/11 [==============================] - 0s 26ms/step - loss: 0.3459 - mean_absolute_error: 0.3459 - val_loss: 1.9280 - val_mean_absolute_error: 1.9280
Epoch 741/1000
11/11 [==============================] - 0s 31ms/step - loss: 0.4214 - mean_absolute_error: 0.4214 - val_loss: 1.8579 - val_mean_absolute_error: 1.8579
Epoch 742/1000
11/11 [==============================] - 1s 47ms/step - loss: 0.4096 - mean_absolute_error: 0.4096 - val_loss: 1.8726 - val_mean_absolute_error: 1.8726
Epoch 743/1000
11/11 [==============================] - 0s 26ms/step - loss: 0.3282 - mean_absolute_error: 0.3282 - val_loss: 1.9858 - val_mean_absolute_error: 1.9858
Epoch 744/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2819 - mean_absolute_error: 0.2819 - val_loss: 1.8866 - val_mean_absolute_error: 1.8866
Epoch 745/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.3313 - mean_absolute_error: 0.3313 - val_loss: 1.8650 - val_mean_absolute_error: 1.8650
Epoch 746/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3205 - mean_absolute_error: 0.3205 - val_loss: 2.0043 - val_mean_absolute_error: 2.0043
Epoch 747/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2906 - mean_absolute_error: 0.2906 - val_loss: 1.9679 - val_mean_absolute_error: 1.9679
Epoch 748/1000
11/11 [==============================] - 0s 21ms/step - loss: 0.2615 - mean_absolute_error: 0.2615 - val_loss: 1.9361 - val_mean_absolute_error: 1.9361
Epoch 749/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.2957 - mean_absolute_error: 0.2957 - val_loss: 1.9376 - val_mean_absolute_error: 1.9376
Epoch 750/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2486 - mean_absolute_error: 0.2486 - val_loss: 1.9303 - val_mean_absolute_error: 1.9303
Epoch 751/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2503 - mean_absolute_error: 0.2503 - val_loss: 2.0611 - val_mean_absolute_error: 2.0611
Epoch 752/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3855 - mean_absolute_error: 0.3855 - val_loss: 1.8782 - val_mean_absolute_error: 1.8782
Epoch 753/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4676 - mean_absolute_error: 0.4676 - val_loss: 1.8903 - val_mean_absolute_error: 1.8903
Epoch 754/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3555 - mean_absolute_error: 0.3555 - val_loss: 1.9192 - val_mean_absolute_error: 1.9192
Epoch 755/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2713 - mean_absolute_error: 0.2713 - val_loss: 1.9165 - val_mean_absolute_error: 1.9165
Epoch 756/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3291 - mean_absolute_error: 0.3291 - val_loss: 1.8837 - val_mean_absolute_error: 1.8837
Epoch 757/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3235 - mean_absolute_error: 0.3235 - val_loss: 1.8591 - val_mean_absolute_error: 1.8591
Epoch 758/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2761 - mean_absolute_error: 0.2761 - val_loss: 1.9561 - val_mean_absolute_error: 1.9561
Epoch 759/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3185 - mean_absolute_error: 0.3185 - val_loss: 2.0064 - val_mean_absolute_error: 2.0064
Epoch 760/1000

11/11 [==============================] - 0s 24ms/step - loss: 0.3566 - mean_absolute_error: 0.3566 - val_loss: 1.9308 - val_mean_absolute_error: 1.9308
Epoch 761/1000
11/11 [==============================] - 0s 24ms/step - loss: 0.3239 - mean_absolute_error: 0.3239 - val_loss: 1.9677 - val_mean_absolute_error: 1.9677
Epoch 762/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2570 - mean_absolute_error: 0.2570 - val_loss: 1.9267 - val_mean_absolute_error: 1.9267
Epoch 763/1000
11/11 [==============================] - 0s 38ms/step - loss: 0.2494 - mean_absolute_error: 0.2494 - val_loss: 1.9409 - val_mean_absolute_error: 1.9409
Epoch 764/1000
11/11 [==============================] - 0s 25ms/step - loss: 0.3329 - mean_absolute_error: 0.3329 - val_loss: 1.9625 - val_mean_absolute_error: 1.9625
Epoch 765/1000
11/11 [==============================] - 0s 44ms/step - loss: 0.2802 - mean_absolute_error: 0.2802 - val_loss: 1.9531 - val_mean_absolute_error: 1.9531
Epoch 766/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2741 - mean_absolute_error: 0.2741 - val_loss: 1.9271 - val_mean_absolute_error: 1.9271
Epoch 767/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2917 - mean_absolute_error: 0.2917 - val_loss: 1.9117 - val_mean_absolute_error: 1.9117
Epoch 768/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2749 - mean_absolute_error: 0.2749 - val_loss: 1.9702 - val_mean_absolute_error: 1.9702
Epoch 769/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2553 - mean_absolute_error: 0.2553 - val_loss: 1.9226 - val_mean_absolute_error: 1.9226
Epoch 770/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3391 - mean_absolute_error: 0.3391 - val_loss: 1.9977 - val_mean_absolute_error: 1.9977
Epoch 771/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3064 - mean_absolute_error: 0.3064 - val_loss: 1.9920 - val_mean_absolute_error: 1.9920
Epoch 772/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3181 - mean_absolute_error: 0.3181 - val_loss: 1.9243 - val_mean_absolute_error: 1.9243
Epoch 773/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3436 - mean_absolute_error: 0.3436 - val_loss: 1.9551 - val_mean_absolute_error: 1.9551
Epoch 774/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.2920 - mean_absolute_error: 0.2920 - val_loss: 1.9226 - val_mean_absolute_error: 1.9226
Epoch 775/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2723 - mean_absolute_error: 0.2723 - val_loss: 1.9604 - val_mean_absolute_error: 1.9604
Epoch 776/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.2609 - mean_absolute_error: 0.2609 - val_loss: 1.9267 - val_mean_absolute_error: 1.9267
Epoch 777/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2951 - mean_absolute_error: 0.2951 - val_loss: 1.9064 - val_mean_absolute_error: 1.9064
Epoch 778/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.2559 - mean_absolute_error: 0.2559 - val_loss: 1.9326 - val_mean_absolute_error: 1.9326
Epoch 779/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2449 - mean_absolute_error: 0.2449 - val_loss: 1.9313 - val_mean_absolute_error: 1.9313
Epoch 780/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2652 - mean_absolute_error: 0.2652 - val_loss: 1.9772 - val_mean_absolute_error: 1.9772
Epoch 781/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3057 - mean_absolute_error: 0.3057 - val_loss: 1.8999 - val_mean_absolute_error: 1.8999
Epoch 782/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3612 - mean_absolute_error: 0.3612 - val_loss: 1.9355 - val_mean_absolute_error: 1.9355
Epoch 783/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.2630 - mean_absolute_error: 0.2630 - val_loss: 1.9135 - val_mean_absolute_error: 1.9135
Epoch 784/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.2459 - mean_absolute_error: 0.2459 - val_loss: 1.8965 - val_mean_absolute_error: 1.8965
Epoch 785/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.3547 - mean_absolute_error: 0.3547 - val_loss: 1.9692 - val_mean_absolute_error: 1.9692
Epoch 786/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3463 - mean_absolute_error: 0.3463 - val_loss: 1.8790 - val_mean_absolute_error: 1.8790
Epoch 787/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2754 - mean_absolute_error: 0.2754 - val_loss: 1.9164 - val_mean_absolute_error: 1.9164
Epoch 788/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2417 - mean_absolute_error: 0.2417 - val_loss: 1.9104 - val_mean_absolute_error: 1.9104
Epoch 789/1000
11/11 [==============================] - 0s 21ms/step - loss: 0.3326 - mean_absolute_error: 0.3326 - val_loss: 1.8970 - val_mean_absolute_error: 1.8970
Epoch 790/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3518 - mean_absolute_error: 0.3518 - val_loss: 1.9225 - val_mean_absolute_error: 1.9225
Epoch 791/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2643 - mean_absolute_error: 0.2643 - val_loss: 1.9327 - val_mean_absolute_error: 1.9327
Epoch 792/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2454 - mean_absolute_error: 0.2454 - val_loss: 1.9087 - val_mean_absolute_error: 1.9087
Epoch 793/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.2431 - mean_absolute_error: 0.2431 - val_loss: 1.8945 - val_mean_absolute_error: 1.8945
Epoch 794/1000
11/11 [==============================] - 0s 21ms/step - loss: 0.2779 - mean_absolute_error: 0.2779 - val_loss: 1.8743 - val_mean_absolute_error: 1.8743
Epoch 795/1000
11/11 [==============================] - 0s 25ms/step - loss: 0.3417 - mean_absolute_error: 0.3417 - val_loss: 2.0208 - val_mean_absolute_error: 2.0208
Epoch 796/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3693 - mean_absolute_error: 0.3693 - val_loss: 1.9606 - val_mean_absolute_error: 1.9606
Epoch 797/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3593 - mean_absolute_error: 0.3593 - val_loss: 1.8592 - val_mean_absolute_error: 1.8592
Epoch 798/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3427 - mean_absolute_error: 0.3427 - val_loss: 1.9303 - val_mean_absolute_error: 1.9303
Epoch 799/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2846 - mean_absolute_error: 0.2846 - val_loss: 1.9465 - val_mean_absolute_error: 1.9465
Epoch 800/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2950 - mean_absolute_error: 0.2950 - val_loss: 1.9074 - val_mean_absolute_error: 1.9074
Epoch 801/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2850 - mean_absolute_error: 0.2850 - val_loss: 1.9556 - val_mean_absolute_error: 1.9556
Epoch 802/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3070 - mean_absolute_error: 0.3070 - val_loss: 1.8773 - val_mean_absolute_error: 1.8773
Epoch 803/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3007 - mean_absolute_error: 0.3007 - val_loss: 1.8913 - val_mean_absolute_error: 1.8913
Epoch 804/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3073 - mean_absolute_error: 0.3073 - val_loss: 1.9795 - val_mean_absolute_error: 1.9795
Epoch 805/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4034 - mean_absolute_error: 0.4034 - val_loss: 1.9815 - val_mean_absolute_error: 1.9815
Epoch 806/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3800 - mean_absolute_error: 0.3800 - val_loss: 1.9623 - val_mean_absolute_error: 1.9623
Epoch 807/1000
11/11 [==============================] - 0s 21ms/step - loss: 0.3537 - mean_absolute_error: 0.3537 - val_loss: 1.9420 - val_mean_absolute_error: 1.9420
Epoch 808/1000
11/11 [==============================] - 0s 24ms/step - loss: 0.3363 - mean_absolute_error: 0.3363 - val_loss: 2.0044 - val_mean_absolute_error: 2.0044
Epoch 809/1000

11/11 [==============================] - 0s 19ms/step - loss: 0.3058 - mean_absolute_error: 0.3058 - val_loss: 2.0022 - val_mean_absolute_error: 2.0022
Epoch 810/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3354 - mean_absolute_error: 0.3354 - val_loss: 1.8928 - val_mean_absolute_error: 1.8928
Epoch 811/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.3603 - mean_absolute_error: 0.3603 - val_loss: 1.8859 - val_mean_absolute_error: 1.8859
Epoch 812/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3466 - mean_absolute_error: 0.3466 - val_loss: 2.0054 - val_mean_absolute_error: 2.0054
Epoch 813/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.3002 - mean_absolute_error: 0.3002 - val_loss: 1.9308 - val_mean_absolute_error: 1.9308
Epoch 814/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.2287 - mean_absolute_error: 0.2287 - val_loss: 1.9207 - val_mean_absolute_error: 1.9207
Epoch 815/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.2520 - mean_absolute_error: 0.2520 - val_loss: 1.9044 - val_mean_absolute_error: 1.9044
Epoch 816/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.3222 - mean_absolute_error: 0.3222 - val_loss: 1.9113 - val_mean_absolute_error: 1.9113
Epoch 817/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2640 - mean_absolute_error: 0.2640 - val_loss: 1.9050 - val_mean_absolute_error: 1.9050
Epoch 818/1000
11/11 [==============================] - 0s 29ms/step - loss: 0.3231 - mean_absolute_error: 0.3231 - val_loss: 1.8838 - val_mean_absolute_error: 1.8838
Epoch 819/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3527 - mean_absolute_error: 0.3527 - val_loss: 1.8712 - val_mean_absolute_error: 1.8712
Epoch 820/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.3783 - mean_absolute_error: 0.3783 - val_loss: 1.9112 - val_mean_absolute_error: 1.9112
Epoch 821/1000
11/11 [==============================] - 0s 36ms/step - loss: 0.3039 - mean_absolute_error: 0.3039 - val_loss: 1.8510 - val_mean_absolute_error: 1.8510
Epoch 822/1000
11/11 [==============================] - 0s 25ms/step - loss: 0.2655 - mean_absolute_error: 0.2655 - val_loss: 1.8856 - val_mean_absolute_error: 1.8856
Epoch 823/1000
11/11 [==============================] - 0s 43ms/step - loss: 0.3133 - mean_absolute_error: 0.3133 - val_loss: 1.8938 - val_mean_absolute_error: 1.8938
Epoch 824/1000
11/11 [==============================] - 0s 29ms/step - loss: 0.2884 - mean_absolute_error: 0.2884 - val_loss: 1.9353 - val_mean_absolute_error: 1.9353
Epoch 825/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.3318 - mean_absolute_error: 0.3318 - val_loss: 1.8959 - val_mean_absolute_error: 1.8959
Epoch 826/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.3302 - mean_absolute_error: 0.3302 - val_loss: 1.9178 - val_mean_absolute_error: 1.9178
Epoch 827/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3523 - mean_absolute_error: 0.3523 - val_loss: 1.9219 - val_mean_absolute_error: 1.9219
Epoch 828/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2931 - mean_absolute_error: 0.2931 - val_loss: 1.8960 - val_mean_absolute_error: 1.8960
Epoch 829/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2725 - mean_absolute_error: 0.2725 - val_loss: 1.8699 - val_mean_absolute_error: 1.8699
Epoch 830/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3651 - mean_absolute_error: 0.3651 - val_loss: 1.9482 - val_mean_absolute_error: 1.9482
Epoch 831/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3533 - mean_absolute_error: 0.3533 - val_loss: 1.9458 - val_mean_absolute_error: 1.9458
Epoch 832/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.2715 - mean_absolute_error: 0.2715 - val_loss: 1.9076 - val_mean_absolute_error: 1.9076
Epoch 833/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2996 - mean_absolute_error: 0.2996 - val_loss: 1.8875 - val_mean_absolute_error: 1.8875
Epoch 834/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2615 - mean_absolute_error: 0.2615 - val_loss: 1.9347 - val_mean_absolute_error: 1.9347
Epoch 835/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.2720 - mean_absolute_error: 0.2720 - val_loss: 1.9090 - val_mean_absolute_error: 1.9090
Epoch 836/1000
11/11 [==============================] - 0s 30ms/step - loss: 0.2848 - mean_absolute_error: 0.2848 - val_loss: 1.8480 - val_mean_absolute_error: 1.8480
Epoch 837/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3656 - mean_absolute_error: 0.3656 - val_loss: 1.8990 - val_mean_absolute_error: 1.8990
Epoch 838/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3605 - mean_absolute_error: 0.3605 - val_loss: 1.9286 - val_mean_absolute_error: 1.9286
Epoch 839/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2832 - mean_absolute_error: 0.2832 - val_loss: 1.9000 - val_mean_absolute_error: 1.9000
Epoch 840/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2337 - mean_absolute_error: 0.2337 - val_loss: 1.8982 - val_mean_absolute_error: 1.8982
Epoch 841/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3256 - mean_absolute_error: 0.3256 - val_loss: 1.8877 - val_mean_absolute_error: 1.8877
Epoch 842/1000
11/11 [==============================] - 0s 25ms/step - loss: 0.3306 - mean_absolute_error: 0.3306 - val_loss: 1.9114 - val_mean_absolute_error: 1.9114
Epoch 843/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2611 - mean_absolute_error: 0.2611 - val_loss: 1.8778 - val_mean_absolute_error: 1.8778
Epoch 844/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2973 - mean_absolute_error: 0.2973 - val_loss: 1.8960 - val_mean_absolute_error: 1.8960
Epoch 845/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2989 - mean_absolute_error: 0.2989 - val_loss: 1.9687 - val_mean_absolute_error: 1.9687
Epoch 846/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3005 - mean_absolute_error: 0.3005 - val_loss: 1.8966 - val_mean_absolute_error: 1.8966
Epoch 847/1000
11/11 [==============================] - 0s 27ms/step - loss: 0.2876 - mean_absolute_error: 0.2876 - val_loss: 1.9018 - val_mean_absolute_error: 1.9018
Epoch 848/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2507 - mean_absolute_error: 0.2507 - val_loss: 1.9403 - val_mean_absolute_error: 1.9403
Epoch 849/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2764 - mean_absolute_error: 0.2764 - val_loss: 1.9790 - val_mean_absolute_error: 1.9790
Epoch 850/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2873 - mean_absolute_error: 0.2873 - val_loss: 1.9442 - val_mean_absolute_error: 1.9442
Epoch 851/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2318 - mean_absolute_error: 0.2318 - val_loss: 1.9447 - val_mean_absolute_error: 1.9447
Epoch 852/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2331 - mean_absolute_error: 0.2331 - val_loss: 1.8785 - val_mean_absolute_error: 1.8785
Epoch 853/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2463 - mean_absolute_error: 0.2463 - val_loss: 1.9184 - val_mean_absolute_error: 1.9184
Epoch 854/1000
11/11 [==============================] - 0s 39ms/step - loss: 0.2412 - mean_absolute_error: 0.2412 - val_loss: 1.9364 - val_mean_absolute_error: 1.9364
Epoch 855/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2699 - mean_absolute_error: 0.2699 - val_loss: 1.9343 - val_mean_absolute_error: 1.9343
Epoch 856/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2484 - mean_absolute_error: 0.2484 - val_loss: 1.9205 - val_mean_absolute_error: 1.9205
Epoch 857/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2426 - mean_absolute_error: 0.2426 - val_loss: 1.9448 - val_mean_absolute_error: 1.9448
Epoch 858/1000

11/11 [==============================] - 0s 16ms/step - loss: 0.2574 - mean_absolute_error: 0.2574 - val_loss: 1.9195 - val_mean_absolute_error: 1.9195
Epoch 859/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2244 - mean_absolute_error: 0.2244 - val_loss: 1.9102 - val_mean_absolute_error: 1.9102
Epoch 860/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2388 - mean_absolute_error: 0.2388 - val_loss: 1.9296 - val_mean_absolute_error: 1.9296
Epoch 861/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2662 - mean_absolute_error: 0.2662 - val_loss: 1.9056 - val_mean_absolute_error: 1.9056
Epoch 862/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.2229 - mean_absolute_error: 0.2229 - val_loss: 1.8894 - val_mean_absolute_error: 1.8894
Epoch 863/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2191 - mean_absolute_error: 0.2191 - val_loss: 1.8875 - val_mean_absolute_error: 1.8875
Epoch 864/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2679 - mean_absolute_error: 0.2679 - val_loss: 1.9032 - val_mean_absolute_error: 1.9032
Epoch 865/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2370 - mean_absolute_error: 0.2370 - val_loss: 1.9160 - val_mean_absolute_error: 1.9160
Epoch 866/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2763 - mean_absolute_error: 0.2763 - val_loss: 1.8928 - val_mean_absolute_error: 1.8928
Epoch 867/1000
11/11 [==============================] - 0s 21ms/step - loss: 0.3812 - mean_absolute_error: 0.3812 - val_loss: 1.9227 - val_mean_absolute_error: 1.9227
Epoch 868/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3441 - mean_absolute_error: 0.3441 - val_loss: 1.9659 - val_mean_absolute_error: 1.9659
Epoch 869/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.3037 - mean_absolute_error: 0.3037 - val_loss: 1.8742 - val_mean_absolute_error: 1.8742
Epoch 870/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3719 - mean_absolute_error: 0.3719 - val_loss: 2.0096 - val_mean_absolute_error: 2.0096
Epoch 871/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2940 - mean_absolute_error: 0.2940 - val_loss: 1.8972 - val_mean_absolute_error: 1.8972
Epoch 872/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.3065 - mean_absolute_error: 0.3065 - val_loss: 1.9164 - val_mean_absolute_error: 1.9164
Epoch 873/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2918 - mean_absolute_error: 0.2918 - val_loss: 1.9275 - val_mean_absolute_error: 1.9275
Epoch 874/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3153 - mean_absolute_error: 0.3153 - val_loss: 1.8554 - val_mean_absolute_error: 1.8554
Epoch 875/1000
11/11 [==============================] - 0s 25ms/step - loss: 0.3444 - mean_absolute_error: 0.3444 - val_loss: 1.9620 - val_mean_absolute_error: 1.9620
Epoch 876/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.2922 - mean_absolute_error: 0.2922 - val_loss: 1.8776 - val_mean_absolute_error: 1.8776
Epoch 877/1000
11/11 [==============================] - 0s 33ms/step - loss: 0.2651 - mean_absolute_error: 0.2651 - val_loss: 1.8779 - val_mean_absolute_error: 1.8779
Epoch 878/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2645 - mean_absolute_error: 0.2645 - val_loss: 1.8877 - val_mean_absolute_error: 1.8877
Epoch 879/1000
11/11 [==============================] - 1s 49ms/step - loss: 0.2559 - mean_absolute_error: 0.2559 - val_loss: 1.9324 - val_mean_absolute_error: 1.9324
Epoch 880/1000
11/11 [==============================] - 0s 45ms/step - loss: 0.2883 - mean_absolute_error: 0.2883 - val_loss: 1.8572 - val_mean_absolute_error: 1.8572
Epoch 881/1000
11/11 [==============================] - 0s 29ms/step - loss: 0.3296 - mean_absolute_error: 0.3296 - val_loss: 1.9443 - val_mean_absolute_error: 1.9443
Epoch 882/1000
11/11 [==============================] - 0s 43ms/step - loss: 0.2974 - mean_absolute_error: 0.2974 - val_loss: 1.9600 - val_mean_absolute_error: 1.9600
Epoch 883/1000
11/11 [==============================] - 0s 28ms/step - loss: 0.2617 - mean_absolute_error: 0.2617 - val_loss: 1.9081 - val_mean_absolute_error: 1.9081
Epoch 884/1000
11/11 [==============================] - 0s 33ms/step - loss: 0.2870 - mean_absolute_error: 0.2870 - val_loss: 1.8930 - val_mean_absolute_error: 1.8930
Epoch 885/1000
11/11 [==============================] - 0s 40ms/step - loss: 0.2555 - mean_absolute_error: 0.2555 - val_loss: 1.8882 - val_mean_absolute_error: 1.8882
Epoch 886/1000
11/11 [==============================] - 0s 30ms/step - loss: 0.2773 - mean_absolute_error: 0.2773 - val_loss: 1.9247 - val_mean_absolute_error: 1.9247
Epoch 887/1000
11/11 [==============================] - 0s 42ms/step - loss: 0.2659 - mean_absolute_error: 0.2659 - val_loss: 1.8961 - val_mean_absolute_error: 1.8961
Epoch 888/1000
11/11 [==============================] - 0s 34ms/step - loss: 0.2906 - mean_absolute_error: 0.2906 - val_loss: 1.9417 - val_mean_absolute_error: 1.9417
Epoch 889/1000
11/11 [==============================] - 0s 27ms/step - loss: 0.3158 - mean_absolute_error: 0.3158 - val_loss: 1.8486 - val_mean_absolute_error: 1.8486
Epoch 890/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2972 - mean_absolute_error: 0.2972 - val_loss: 1.9178 - val_mean_absolute_error: 1.9178
Epoch 891/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2736 - mean_absolute_error: 0.2736 - val_loss: 1.9095 - val_mean_absolute_error: 1.9095
Epoch 892/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2898 - mean_absolute_error: 0.2898 - val_loss: 1.9875 - val_mean_absolute_error: 1.9875
Epoch 893/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.2535 - mean_absolute_error: 0.2535 - val_loss: 1.9053 - val_mean_absolute_error: 1.9053
Epoch 894/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2569 - mean_absolute_error: 0.2569 - val_loss: 1.8644 - val_mean_absolute_error: 1.8644
Epoch 895/1000
11/11 [==============================] - 0s 24ms/step - loss: 0.2661 - mean_absolute_error: 0.2661 - val_loss: 1.9245 - val_mean_absolute_error: 1.9245
Epoch 896/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.2553 - mean_absolute_error: 0.2553 - val_loss: 1.8844 - val_mean_absolute_error: 1.8844
Epoch 897/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3576 - mean_absolute_error: 0.3576 - val_loss: 1.9407 - val_mean_absolute_error: 1.9407
Epoch 898/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2672 - mean_absolute_error: 0.2672 - val_loss: 1.9285 - val_mean_absolute_error: 1.9285
Epoch 899/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.2382 - mean_absolute_error: 0.2382 - val_loss: 1.9027 - val_mean_absolute_error: 1.9027
Epoch 900/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2188 - mean_absolute_error: 0.2188 - val_loss: 1.9155 - val_mean_absolute_error: 1.9155
Epoch 901/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2526 - mean_absolute_error: 0.2526 - val_loss: 1.8963 - val_mean_absolute_error: 1.8963
Epoch 902/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2893 - mean_absolute_error: 0.2893 - val_loss: 1.9521 - val_mean_absolute_error: 1.9521
Epoch 903/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2644 - mean_absolute_error: 0.2644 - val_loss: 1.9630 - val_mean_absolute_error: 1.9630
Epoch 904/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.3402 - mean_absolute_error: 0.3402 - val_loss: 1.9021 - val_mean_absolute_error: 1.9021
Epoch 905/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2413 - mean_absolute_error: 0.2413 - val_loss: 1.9154 - val_mean_absolute_error: 1.9154
Epoch 906/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2567 - mean_absolute_error: 0.2567 - val_loss: 1.9450 - val_mean_absolute_error: 1.9450
Epoch 907/1000

11/11 [==============================] - 0s 20ms/step - loss: 0.2573 - mean_absolute_error: 0.2573 - val_loss: 1.9387 - val_mean_absolute_error: 1.9387
Epoch 908/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2855 - mean_absolute_error: 0.2855 - val_loss: 1.8899 - val_mean_absolute_error: 1.8899
Epoch 909/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2187 - mean_absolute_error: 0.2187 - val_loss: 1.9309 - val_mean_absolute_error: 1.9309
Epoch 910/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2129 - mean_absolute_error: 0.2129 - val_loss: 1.9195 - val_mean_absolute_error: 1.9195
Epoch 911/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2326 - mean_absolute_error: 0.2326 - val_loss: 1.9052 - val_mean_absolute_error: 1.9052
Epoch 912/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.2452 - mean_absolute_error: 0.2452 - val_loss: 1.9647 - val_mean_absolute_error: 1.9647
Epoch 913/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2799 - mean_absolute_error: 0.2799 - val_loss: 1.9278 - val_mean_absolute_error: 1.9278
Epoch 914/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2958 - mean_absolute_error: 0.2958 - val_loss: 1.8838 - val_mean_absolute_error: 1.8838
Epoch 915/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3989 - mean_absolute_error: 0.3989 - val_loss: 1.8820 - val_mean_absolute_error: 1.8820
Epoch 916/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3738 - mean_absolute_error: 0.3738 - val_loss: 1.9476 - val_mean_absolute_error: 1.9476
Epoch 917/1000
11/11 [==============================] - 0s 45ms/step - loss: 0.2613 - mean_absolute_error: 0.2613 - val_loss: 1.9075 - val_mean_absolute_error: 1.9075
Epoch 918/1000
11/11 [==============================] - 0s 44ms/step - loss: 0.2582 - mean_absolute_error: 0.2582 - val_loss: 1.9150 - val_mean_absolute_error: 1.9150
Epoch 919/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2478 - mean_absolute_error: 0.2478 - val_loss: 1.9672 - val_mean_absolute_error: 1.9672
Epoch 920/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3131 - mean_absolute_error: 0.3131 - val_loss: 1.9373 - val_mean_absolute_error: 1.9373
Epoch 921/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2322 - mean_absolute_error: 0.2322 - val_loss: 1.9206 - val_mean_absolute_error: 1.9206
Epoch 922/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2430 - mean_absolute_error: 0.2430 - val_loss: 1.8749 - val_mean_absolute_error: 1.8749
Epoch 923/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.3040 - mean_absolute_error: 0.3040 - val_loss: 1.9949 - val_mean_absolute_error: 1.9949
Epoch 924/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3592 - mean_absolute_error: 0.3592 - val_loss: 1.8904 - val_mean_absolute_error: 1.8904
Epoch 925/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2831 - mean_absolute_error: 0.2831 - val_loss: 1.9273 - val_mean_absolute_error: 1.9273
Epoch 926/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2909 - mean_absolute_error: 0.2909 - val_loss: 1.9428 - val_mean_absolute_error: 1.9428
Epoch 927/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2527 - mean_absolute_error: 0.2527 - val_loss: 1.9111 - val_mean_absolute_error: 1.9111
Epoch 928/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.2084 - mean_absolute_error: 0.2084 - val_loss: 1.9227 - val_mean_absolute_error: 1.9227
Epoch 929/1000
11/11 [==============================] - 0s 25ms/step - loss: 0.2296 - mean_absolute_error: 0.2296 - val_loss: 1.8513 - val_mean_absolute_error: 1.8513
Epoch 930/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2694 - mean_absolute_error: 0.2694 - val_loss: 1.9023 - val_mean_absolute_error: 1.9023
Epoch 931/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.2480 - mean_absolute_error: 0.2480 - val_loss: 1.9041 - val_mean_absolute_error: 1.9041
Epoch 932/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3280 - mean_absolute_error: 0.3280 - val_loss: 1.9669 - val_mean_absolute_error: 1.9669
Epoch 933/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2355 - mean_absolute_error: 0.2355 - val_loss: 1.9035 - val_mean_absolute_error: 1.9035
Epoch 934/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.2820 - mean_absolute_error: 0.2820 - val_loss: 2.0254 - val_mean_absolute_error: 2.0254
Epoch 935/1000
11/11 [==============================] - 0s 26ms/step - loss: 0.3516 - mean_absolute_error: 0.3516 - val_loss: 1.9847 - val_mean_absolute_error: 1.9847
Epoch 936/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3360 - mean_absolute_error: 0.3360 - val_loss: 1.9003 - val_mean_absolute_error: 1.9003
Epoch 937/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3516 - mean_absolute_error: 0.3516 - val_loss: 1.9065 - val_mean_absolute_error: 1.9065
Epoch 938/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2406 - mean_absolute_error: 0.2406 - val_loss: 1.8677 - val_mean_absolute_error: 1.8677
Epoch 939/1000
11/11 [==============================] - 1s 51ms/step - loss: 0.3090 - mean_absolute_error: 0.3090 - val_loss: 1.9192 - val_mean_absolute_error: 1.9192
Epoch 940/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.3036 - mean_absolute_error: 0.3036 - val_loss: 1.8771 - val_mean_absolute_error: 1.8771
Epoch 941/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.2922 - mean_absolute_error: 0.2922 - val_loss: 1.9184 - val_mean_absolute_error: 1.9184
Epoch 942/1000
11/11 [==============================] - 0s 21ms/step - loss: 0.2531 - mean_absolute_error: 0.2531 - val_loss: 1.9224 - val_mean_absolute_error: 1.9224
Epoch 943/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2605 - mean_absolute_error: 0.2605 - val_loss: 1.9210 - val_mean_absolute_error: 1.9210
Epoch 944/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.2681 - mean_absolute_error: 0.2681 - val_loss: 1.9621 - val_mean_absolute_error: 1.9621
Epoch 945/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3324 - mean_absolute_error: 0.3324 - val_loss: 1.9300 - val_mean_absolute_error: 1.9300
Epoch 946/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2959 - mean_absolute_error: 0.2959 - val_loss: 1.8717 - val_mean_absolute_error: 1.8717
Epoch 947/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.3157 - mean_absolute_error: 0.3157 - val_loss: 1.9136 - val_mean_absolute_error: 1.9136
Epoch 948/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2464 - mean_absolute_error: 0.2464 - val_loss: 1.9132 - val_mean_absolute_error: 1.9132
Epoch 949/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2293 - mean_absolute_error: 0.2293 - val_loss: 1.9163 - val_mean_absolute_error: 1.9163
Epoch 950/1000
11/11 [==============================] - 0s 24ms/step - loss: 0.2653 - mean_absolute_error: 0.2653 - val_loss: 1.9296 - val_mean_absolute_error: 1.9296
Epoch 951/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.2767 - mean_absolute_error: 0.2767 - val_loss: 1.9221 - val_mean_absolute_error: 1.9221
Epoch 952/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2502 - mean_absolute_error: 0.2502 - val_loss: 1.9084 - val_mean_absolute_error: 1.9084
Epoch 953/1000
11/11 [==============================] - 0s 21ms/step - loss: 0.2363 - mean_absolute_error: 0.2363 - val_loss: 1.9207 - val_mean_absolute_error: 1.9207
Epoch 954/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2161 - mean_absolute_error: 0.2161 - val_loss: 1.8694 - val_mean_absolute_error: 1.8694
Epoch 955/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3272 - mean_absolute_error: 0.3272 - val_loss: 1.9192 - val_mean_absolute_error: 1.9192
Epoch 956/1000

11/11 [==============================] - 0s 15ms/step - loss: 0.3198 - mean_absolute_error: 0.3198 - val_loss: 1.9621 - val_mean_absolute_error: 1.9621
Epoch 957/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2466 - mean_absolute_error: 0.2466 - val_loss: 1.9118 - val_mean_absolute_error: 1.9118
Epoch 958/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.2221 - mean_absolute_error: 0.2221 - val_loss: 1.8585 - val_mean_absolute_error: 1.8585
Epoch 959/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.2558 - mean_absolute_error: 0.2558 - val_loss: 1.9541 - val_mean_absolute_error: 1.9541
Epoch 960/1000
11/11 [==============================] - 0s 43ms/step - loss: 0.2605 - mean_absolute_error: 0.2605 - val_loss: 1.9877 - val_mean_absolute_error: 1.9877
Epoch 961/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.3159 - mean_absolute_error: 0.3159 - val_loss: 1.9168 - val_mean_absolute_error: 1.9168
Epoch 962/1000
11/11 [==============================] - 0s 24ms/step - loss: 0.2901 - mean_absolute_error: 0.2901 - val_loss: 1.8652 - val_mean_absolute_error: 1.8652
Epoch 963/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2656 - mean_absolute_error: 0.2656 - val_loss: 1.9766 - val_mean_absolute_error: 1.9766
Epoch 964/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3089 - mean_absolute_error: 0.3089 - val_loss: 1.9134 - val_mean_absolute_error: 1.9134
Epoch 965/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2434 - mean_absolute_error: 0.2434 - val_loss: 1.9848 - val_mean_absolute_error: 1.9848
Epoch 966/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3216 - mean_absolute_error: 0.3216 - val_loss: 1.8825 - val_mean_absolute_error: 1.8825
Epoch 967/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3470 - mean_absolute_error: 0.3470 - val_loss: 1.9868 - val_mean_absolute_error: 1.9868
Epoch 968/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3265 - mean_absolute_error: 0.3265 - val_loss: 1.8865 - val_mean_absolute_error: 1.8865
Epoch 969/1000
11/11 [==============================] - 0s 27ms/step - loss: 0.3599 - mean_absolute_error: 0.3599 - val_loss: 1.8864 - val_mean_absolute_error: 1.8864
Epoch 970/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.3675 - mean_absolute_error: 0.3675 - val_loss: 2.0001 - val_mean_absolute_error: 2.0001
Epoch 971/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3156 - mean_absolute_error: 0.3156 - val_loss: 1.8989 - val_mean_absolute_error: 1.8989
Epoch 972/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3064 - mean_absolute_error: 0.3064 - val_loss: 1.8534 - val_mean_absolute_error: 1.8534
Epoch 973/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.3170 - mean_absolute_error: 0.3170 - val_loss: 1.9107 - val_mean_absolute_error: 1.9107
Epoch 974/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3108 - mean_absolute_error: 0.3108 - val_loss: 1.9270 - val_mean_absolute_error: 1.9270
Epoch 975/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2971 - mean_absolute_error: 0.2971 - val_loss: 1.8666 - val_mean_absolute_error: 1.8666
Epoch 976/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2664 - mean_absolute_error: 0.2664 - val_loss: 1.9733 - val_mean_absolute_error: 1.9733
Epoch 977/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2510 - mean_absolute_error: 0.2510 - val_loss: 1.9241 - val_mean_absolute_error: 1.9241
Epoch 978/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2226 - mean_absolute_error: 0.2226 - val_loss: 1.8920 - val_mean_absolute_error: 1.8920
Epoch 979/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.1975 - mean_absolute_error: 0.1975 - val_loss: 1.9236 - val_mean_absolute_error: 1.9236
Epoch 980/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2004 - mean_absolute_error: 0.2004 - val_loss: 1.9517 - val_mean_absolute_error: 1.9517
Epoch 981/1000
11/11 [==============================] - 0s 26ms/step - loss: 0.2674 - mean_absolute_error: 0.2674 - val_loss: 1.8878 - val_mean_absolute_error: 1.8878
Epoch 982/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2806 - mean_absolute_error: 0.2806 - val_loss: 1.8695 - val_mean_absolute_error: 1.8695
Epoch 983/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.2579 - mean_absolute_error: 0.2579 - val_loss: 1.8525 - val_mean_absolute_error: 1.8525
Epoch 984/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.2918 - mean_absolute_error: 0.2918 - val_loss: 2.0013 - val_mean_absolute_error: 2.0013
Epoch 985/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3359 - mean_absolute_error: 0.3359 - val_loss: 1.9033 - val_mean_absolute_error: 1.9033
Epoch 986/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2676 - mean_absolute_error: 0.2676 - val_loss: 1.9015 - val_mean_absolute_error: 1.9015
Epoch 987/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2564 - mean_absolute_error: 0.2564 - val_loss: 1.9276 - val_mean_absolute_error: 1.9276
Epoch 988/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3248 - mean_absolute_error: 0.3248 - val_loss: 1.8891 - val_mean_absolute_error: 1.8891
Epoch 989/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2699 - mean_absolute_error: 0.2699 - val_loss: 1.8833 - val_mean_absolute_error: 1.8833
Epoch 990/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2345 - mean_absolute_error: 0.2345 - val_loss: 1.8803 - val_mean_absolute_error: 1.8803
Epoch 991/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3483 - mean_absolute_error: 0.3483 - val_loss: 1.9000 - val_mean_absolute_error: 1.9000
Epoch 992/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3044 - mean_absolute_error: 0.3044 - val_loss: 1.8986 - val_mean_absolute_error: 1.8986
Epoch 993/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2518 - mean_absolute_error: 0.2518 - val_loss: 1.8920 - val_mean_absolute_error: 1.8920
Epoch 994/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2358 - mean_absolute_error: 0.2358 - val_loss: 1.8878 - val_mean_absolute_error: 1.8878
Epoch 995/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2302 - mean_absolute_error: 0.2302 - val_loss: 1.9165 - val_mean_absolute_error: 1.9165
Epoch 996/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2316 - mean_absolute_error: 0.2316 - val_loss: 1.9032 - val_mean_absolute_error: 1.9032
Epoch 997/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2380 - mean_absolute_error: 0.2380 - val_loss: 1.9129 - val_mean_absolute_error: 1.9129
Epoch 998/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2620 - mean_absolute_error: 0.2620 - val_loss: 1.8792 - val_mean_absolute_error: 1.8792
Epoch 999/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2711 - mean_absolute_error: 0.2711 - val_loss: 1.9291 - val_mean_absolute_error: 1.9291
Epoch 1000/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2925 - mean_absolute_error: 0.2925 - val_loss: 1.9438 - val_mean_absolute_error: 1.9438
32/32 [==============================] - 0s 2ms/step

,iter,Model,ACC,AFS,MAE,RMSE,RMSE2,50th%error,75th%error,95th%error,avg_le
0,0,MC-ACNNR_dual,1.0,2.499237,2.499237,2.539453,4.460683,2.097947,3.446978,4.812274,4.094710
1,1,MC-ACNNR_dual,1.0,2.526197,2.526197,2.567692,4.501695,1.998325,3.113951,5.415851,4.159268

Model: "model_3"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to
==================================================================================================
 input_7 (InputLayer)           [(None, 23, 1)]      0           []

 input_8 (InputLayer)           [(None, 23, 1)]      0           []

 conv1d_18 (Conv1D)             (None, 23, 32)       128         ['input_7[0][0]']

 conv1d_20 (Conv1D)             (None, 23, 32)       128         ['input_8[0][0]']

 conv1d_19 (Conv1D)             (None, 23, 32)       3104        ['conv1d_18[0][0]']

 conv1d_21 (Conv1D)             (None, 23, 32)       3104        ['conv1d_20[0][0]']

 concatenate_6 (Concatenate)    (None, 23, 64)       0           ['conv1d_19[0][0]',
                                                                  'conv1d_21[0][0]']

 conv1d_22 (Conv1D)             (None, 23, 32)       6176        ['concatenate_6[0][0]']

 conv1d_23 (Conv1D)             (None, 23, 32)       3104        ['conv1d_22[0][0]']

 max_pooling1d_3 (MaxPooling1D)  (None, 11, 32)      0           ['conv1d_23[0][0]']

 attention_6 (attention)        (None, 32)           55          ['conv1d_19[0][0]']

 flatten_3 (Flatten)            (None, 352)          0           ['max_pooling1d_3[0][0]']

 attention_7 (attention)        (None, 32)           55          ['conv1d_21[0][0]']

 concatenate_7 (Concatenate)    (None, 416)          0           ['attention_6[0][0]',
                                                                  'flatten_3[0][0]',
                                                                  'attention_7[0][0]']

 dense_18 (Dense)               (None, 256)          106752      ['concatenate_7[0][0]']

 dense_19 (Dense)               (None, 128)          32896       ['dense_18[0][0]']

 dense_20 (Dense)               (None, 3)            387         ['dense_19[0][0]']

==================================================================================================
Total params: 155,889
Trainable params: 155,889
Non-trainable params: 0
__________________________________________________________________________________________________
None
Epoch 1/1000
11/11 [==============================] - 2s 51ms/step - loss: 20.8699 - mean_absolute_error: 20.8699 - val_loss: 17.4647 - val_mean_absolute_error: 17.4647
Epoch 2/1000
11/11 [==============================] - 0s 19ms/step - loss: 14.3678 - mean_absolute_error: 14.3678 - val_loss: 9.7171 - val_mean_absolute_error: 9.7171
Epoch 3/1000
11/11 [==============================] - 0s 20ms/step - loss: 9.5888 - mean_absolute_error: 9.5888 - val_loss: 8.7780 - val_mean_absolute_error: 8.7780
Epoch 4/1000
11/11 [==============================] - 0s 25ms/step - loss: 8.4177 - mean_absolute_error: 8.4177 - val_loss: 8.0968 - val_mean_absolute_error: 8.0968
Epoch 5/1000
11/11 [==============================] - 0s 20ms/step - loss: 7.7437 - mean_absolute_error: 7.7437 - val_loss: 7.2942 - val_mean_absolute_error: 7.2942
Epoch 6/1000
11/11 [==============================] - 0s 20ms/step - loss: 7.0224 - mean_absolute_error: 7.0224 - val_loss: 6.6688 - val_mean_absolute_error: 6.6688
Epoch 7/1000
11/11 [==============================] - 0s 19ms/step - loss: 6.4871 - mean_absolute_error: 6.4871 - val_loss: 6.2191 - val_mean_absolute_error: 6.2191
Epoch 8/1000
11/11 [==============================] - 0s 20ms/step - loss: 5.9078 - mean_absolute_error: 5.9078 - val_loss: 5.6357 - val_mean_absolute_error: 5.6357
Epoch 9/1000
11/11 [==============================] - 0s 28ms/step - loss: 4.9995 - mean_absolute_error: 4.9995 - val_loss: 4.7456 - val_mean_absolute_error: 4.7456
Epoch 10/1000
11/11 [==============================] - 0s 19ms/step - loss: 4.0296 - mean_absolute_error: 4.0296 - val_loss: 4.1109 - val_mean_absolute_error: 4.1109
Epoch 11/1000
11/11 [==============================] - 0s 30ms/step - loss: 3.6917 - mean_absolute_error: 3.6917 - val_loss: 3.7055 - val_mean_absolute_error: 3.7055
Epoch 12/1000
11/11 [==============================] - 0s 24ms/step - loss: 3.3427 - mean_absolute_error: 3.3427 - val_loss: 3.4235 - val_mean_absolute_error: 3.4235
Epoch 13/1000
11/11 [==============================] - 0s 23ms/step - loss: 3.0446 - mean_absolute_error: 3.0446 - val_loss: 3.4786 - val_mean_absolute_error: 3.4786
Epoch 14/1000
11/11 [==============================] - 0s 25ms/step - loss: 2.7636 - mean_absolute_error: 2.7636 - val_loss: 3.1762 - val_mean_absolute_error: 3.1762
Epoch 15/1000
11/11 [==============================] - 0s 25ms/step - loss: 2.6142 - mean_absolute_error: 2.6142 - val_loss: 3.3513 - val_mean_absolute_error: 3.3513
Epoch 16/1000
11/11 [==============================] - 0s 37ms/step - loss: 2.6031 - mean_absolute_error: 2.6031 - val_loss: 2.8649 - val_mean_absolute_error: 2.8649
Epoch 17/1000
11/11 [==============================] - 0s 31ms/step - loss: 2.5796 - mean_absolute_error: 2.5796 - val_loss: 2.8731 - val_mean_absolute_error: 2.8731
Epoch 18/1000
11/11 [==============================] - 0s 22ms/step - loss: 2.5267 - mean_absolute_error: 2.5267 - val_loss: 3.1341 - val_mean_absolute_error: 3.1341
Epoch 19/1000
11/11 [==============================] - 0s 27ms/step - loss: 2.2985 - mean_absolute_error: 2.2985 - val_loss: 2.6563 - val_mean_absolute_error: 2.6563
Epoch 20/1000
11/11 [==============================] - 0s 21ms/step - loss: 2.1662 - mean_absolute_error: 2.1662 - val_loss: 3.0347 - val_mean_absolute_error: 3.0347
Epoch 21/1000
11/11 [==============================] - 0s 29ms/step - loss: 2.1708 - mean_absolute_error: 2.1708 - val_loss: 2.4317 - val_mean_absolute_error: 2.4317
Epoch 22/1000
11/11 [==============================] - 0s 19ms/step - loss: 2.0699 - mean_absolute_error: 2.0699 - val_loss: 2.7255 - val_mean_absolute_error: 2.7255
Epoch 23/1000
11/11 [==============================] - 0s 16ms/step - loss: 2.0364 - mean_absolute_error: 2.0364 - val_loss: 2.4760 - val_mean_absolute_error: 2.4760
Epoch 24/1000
11/11 [==============================] - 0s 24ms/step - loss: 1.9865 - mean_absolute_error: 1.9865 - val_loss: 2.6805 - val_mean_absolute_error: 2.6805

Epoch 25/1000
11/11 [==============================] - 0s 20ms/step - loss: 2.0318 - mean_absolute_error: 2.0318 - val_loss: 2.5769 - val_mean_absolute_error: 2.5769
Epoch 26/1000
11/11 [==============================] - 0s 31ms/step - loss: 2.0990 - mean_absolute_error: 2.0990 - val_loss: 2.6208 - val_mean_absolute_error: 2.6208
Epoch 27/1000
11/11 [==============================] - 0s 15ms/step - loss: 2.3480 - mean_absolute_error: 2.3480 - val_loss: 3.4126 - val_mean_absolute_error: 3.4126
Epoch 28/1000
11/11 [==============================] - 0s 24ms/step - loss: 2.2455 - mean_absolute_error: 2.2455 - val_loss: 2.4024 - val_mean_absolute_error: 2.4024
Epoch 29/1000
11/11 [==============================] - 0s 15ms/step - loss: 2.1197 - mean_absolute_error: 2.1197 - val_loss: 2.9036 - val_mean_absolute_error: 2.9036
Epoch 30/1000
11/11 [==============================] - 0s 21ms/step - loss: 1.9518 - mean_absolute_error: 1.9518 - val_loss: 2.3861 - val_mean_absolute_error: 2.3861
Epoch 31/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.9103 - mean_absolute_error: 1.9103 - val_loss: 2.4414 - val_mean_absolute_error: 2.4414
Epoch 32/1000
11/11 [==============================] - 0s 34ms/step - loss: 1.8670 - mean_absolute_error: 1.8670 - val_loss: 2.3788 - val_mean_absolute_error: 2.3788
Epoch 33/1000
11/11 [==============================] - 0s 24ms/step - loss: 1.8862 - mean_absolute_error: 1.8862 - val_loss: 2.3527 - val_mean_absolute_error: 2.3527
Epoch 34/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.8878 - mean_absolute_error: 1.8878 - val_loss: 2.5731 - val_mean_absolute_error: 2.5731
Epoch 35/1000
11/11 [==============================] - 0s 15ms/step - loss: 1.8841 - mean_absolute_error: 1.8841 - val_loss: 2.5668 - val_mean_absolute_error: 2.5668
Epoch 36/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.8192 - mean_absolute_error: 1.8192 - val_loss: 2.7209 - val_mean_absolute_error: 2.7209
Epoch 37/1000
11/11 [==============================] - 0s 19ms/step - loss: 1.9003 - mean_absolute_error: 1.9003 - val_loss: 2.5524 - val_mean_absolute_error: 2.5524
Epoch 38/1000
11/11 [==============================] - 0s 20ms/step - loss: 1.8142 - mean_absolute_error: 1.8142 - val_loss: 2.3318 - val_mean_absolute_error: 2.3318
Epoch 39/1000
11/11 [==============================] - 0s 15ms/step - loss: 1.8449 - mean_absolute_error: 1.8449 - val_loss: 2.4550 - val_mean_absolute_error: 2.4550
Epoch 40/1000
11/11 [==============================] - 0s 15ms/step - loss: 1.7417 - mean_absolute_error: 1.7417 - val_loss: 2.3656 - val_mean_absolute_error: 2.3656
Epoch 41/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.7508 - mean_absolute_error: 1.7508 - val_loss: 2.4212 - val_mean_absolute_error: 2.4212
Epoch 42/1000
11/11 [==============================] - 0s 19ms/step - loss: 1.7313 - mean_absolute_error: 1.7313 - val_loss: 2.4082 - val_mean_absolute_error: 2.4082
Epoch 43/1000
11/11 [==============================] - 0s 19ms/step - loss: 1.7879 - mean_absolute_error: 1.7879 - val_loss: 2.5034 - val_mean_absolute_error: 2.5034
Epoch 44/1000
11/11 [==============================] - 0s 19ms/step - loss: 1.7732 - mean_absolute_error: 1.7732 - val_loss: 2.7612 - val_mean_absolute_error: 2.7612
Epoch 45/1000
11/11 [==============================] - 0s 15ms/step - loss: 1.7475 - mean_absolute_error: 1.7475 - val_loss: 2.4030 - val_mean_absolute_error: 2.4030
Epoch 46/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.6940 - mean_absolute_error: 1.6940 - val_loss: 2.4412 - val_mean_absolute_error: 2.4412
Epoch 47/1000
11/11 [==============================] - 0s 15ms/step - loss: 1.6841 - mean_absolute_error: 1.6841 - val_loss: 2.4627 - val_mean_absolute_error: 2.4627
Epoch 48/1000
11/11 [==============================] - 0s 19ms/step - loss: 1.6698 - mean_absolute_error: 1.6698 - val_loss: 2.4171 - val_mean_absolute_error: 2.4171
Epoch 49/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.7326 - mean_absolute_error: 1.7326 - val_loss: 2.5420 - val_mean_absolute_error: 2.5420
Epoch 50/1000
11/11 [==============================] - 0s 23ms/step - loss: 1.7162 - mean_absolute_error: 1.7162 - val_loss: 2.3208 - val_mean_absolute_error: 2.3208
Epoch 51/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.6305 - mean_absolute_error: 1.6305 - val_loss: 2.4964 - val_mean_absolute_error: 2.4964
Epoch 52/1000
11/11 [==============================] - 0s 21ms/step - loss: 1.6180 - mean_absolute_error: 1.6180 - val_loss: 2.3385 - val_mean_absolute_error: 2.3385
Epoch 53/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.6029 - mean_absolute_error: 1.6029 - val_loss: 2.4683 - val_mean_absolute_error: 2.4683
Epoch 54/1000
11/11 [==============================] - 0s 19ms/step - loss: 1.5913 - mean_absolute_error: 1.5913 - val_loss: 2.6136 - val_mean_absolute_error: 2.6136
Epoch 55/1000
11/11 [==============================] - 0s 23ms/step - loss: 1.6157 - mean_absolute_error: 1.6157 - val_loss: 2.3103 - val_mean_absolute_error: 2.3103
Epoch 56/1000
11/11 [==============================] - 0s 23ms/step - loss: 1.5560 - mean_absolute_error: 1.5560 - val_loss: 2.2407 - val_mean_absolute_error: 2.2407
Epoch 57/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.5534 - mean_absolute_error: 1.5534 - val_loss: 2.3532 - val_mean_absolute_error: 2.3532
Epoch 58/1000
11/11 [==============================] - 0s 20ms/step - loss: 1.5546 - mean_absolute_error: 1.5546 - val_loss: 2.3201 - val_mean_absolute_error: 2.3201
Epoch 59/1000
11/11 [==============================] - 0s 15ms/step - loss: 1.5330 - mean_absolute_error: 1.5330 - val_loss: 2.3426 - val_mean_absolute_error: 2.3426
Epoch 60/1000
11/11 [==============================] - 0s 25ms/step - loss: 1.5480 - mean_absolute_error: 1.5480 - val_loss: 2.1754 - val_mean_absolute_error: 2.1754
Epoch 61/1000
11/11 [==============================] - 0s 19ms/step - loss: 1.5670 - mean_absolute_error: 1.5670 - val_loss: 2.3221 - val_mean_absolute_error: 2.3221
Epoch 62/1000
11/11 [==============================] - 0s 18ms/step - loss: 1.5713 - mean_absolute_error: 1.5713 - val_loss: 2.4080 - val_mean_absolute_error: 2.4080
Epoch 63/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.6129 - mean_absolute_error: 1.6129 - val_loss: 2.3469 - val_mean_absolute_error: 2.3469
Epoch 64/1000
11/11 [==============================] - 0s 20ms/step - loss: 1.4787 - mean_absolute_error: 1.4787 - val_loss: 2.3068 - val_mean_absolute_error: 2.3068
Epoch 65/1000
11/11 [==============================] - 0s 19ms/step - loss: 1.4695 - mean_absolute_error: 1.4695 - val_loss: 2.2295 - val_mean_absolute_error: 2.2295
Epoch 66/1000
11/11 [==============================] - 0s 17ms/step - loss: 1.4672 - mean_absolute_error: 1.4672 - val_loss: 2.1780 - val_mean_absolute_error: 2.1780
Epoch 67/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.4638 - mean_absolute_error: 1.4638 - val_loss: 2.3353 - val_mean_absolute_error: 2.3353
Epoch 68/1000
11/11 [==============================] - 0s 17ms/step - loss: 1.4536 - mean_absolute_error: 1.4536 - val_loss: 2.2215 - val_mean_absolute_error: 2.2215
Epoch 69/1000
11/11 [==============================] - 0s 26ms/step - loss: 1.4398 - mean_absolute_error: 1.4398 - val_loss: 2.3258 - val_mean_absolute_error: 2.3258
Epoch 70/1000
11/11 [==============================] - 0s 30ms/step - loss: 1.4623 - mean_absolute_error: 1.4623 - val_loss: 2.1605 - val_mean_absolute_error: 2.1605
Epoch 71/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.4366 - mean_absolute_error: 1.4366 - val_loss: 2.1720 - val_mean_absolute_error: 2.1720
Epoch 72/1000
11/11 [==============================] - 0s 34ms/step - loss: 1.4013 - mean_absolute_error: 1.4013 - val_loss: 2.0690 - val_mean_absolute_error: 2.0690
Epoch 73/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.5097 - mean_absolute_error: 1.5097 - val_loss: 2.1804 - val_mean_absolute_error: 2.1804
Epoch 74/1000

11/11 [==============================] - 0s 19ms/step - loss: 1.4672 - mean_absolute_error: 1.4672 - val_loss: 2.1920 - val_mean_absolute_error: 2.1920
Epoch 75/1000
11/11 [==============================] - 0s 19ms/step - loss: 1.4135 - mean_absolute_error: 1.4135 - val_loss: 2.3487 - val_mean_absolute_error: 2.3487
Epoch 76/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.4048 - mean_absolute_error: 1.4048 - val_loss: 2.4148 - val_mean_absolute_error: 2.4148
Epoch 77/1000
11/11 [==============================] - 0s 19ms/step - loss: 1.4640 - mean_absolute_error: 1.4640 - val_loss: 2.1044 - val_mean_absolute_error: 2.1044
Epoch 78/1000
11/11 [==============================] - 0s 21ms/step - loss: 1.3938 - mean_absolute_error: 1.3938 - val_loss: 2.1017 - val_mean_absolute_error: 2.1017
Epoch 79/1000
11/11 [==============================] - 0s 19ms/step - loss: 1.3801 - mean_absolute_error: 1.3801 - val_loss: 2.3703 - val_mean_absolute_error: 2.3703
Epoch 80/1000
11/11 [==============================] - 1s 51ms/step - loss: 1.3891 - mean_absolute_error: 1.3891 - val_loss: 2.0422 - val_mean_absolute_error: 2.0422
Epoch 81/1000
11/11 [==============================] - 0s 45ms/step - loss: 1.3387 - mean_absolute_error: 1.3387 - val_loss: 2.5438 - val_mean_absolute_error: 2.5438
Epoch 82/1000
11/11 [==============================] - 0s 20ms/step - loss: 1.4126 - mean_absolute_error: 1.4126 - val_loss: 2.0730 - val_mean_absolute_error: 2.0730
Epoch 83/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.4607 - mean_absolute_error: 1.4607 - val_loss: 2.2160 - val_mean_absolute_error: 2.2160
Epoch 84/1000
11/11 [==============================] - 0s 20ms/step - loss: 1.4192 - mean_absolute_error: 1.4192 - val_loss: 2.2577 - val_mean_absolute_error: 2.2577
Epoch 85/1000
11/11 [==============================] - 0s 17ms/step - loss: 1.3763 - mean_absolute_error: 1.3763 - val_loss: 2.0826 - val_mean_absolute_error: 2.0826
Epoch 86/1000
11/11 [==============================] - 0s 43ms/step - loss: 1.3304 - mean_absolute_error: 1.3304 - val_loss: 2.1508 - val_mean_absolute_error: 2.1508
Epoch 87/1000
11/11 [==============================] - 0s 45ms/step - loss: 1.3420 - mean_absolute_error: 1.3420 - val_loss: 1.9967 - val_mean_absolute_error: 1.9967
Epoch 88/1000
11/11 [==============================] - 0s 44ms/step - loss: 1.4166 - mean_absolute_error: 1.4166 - val_loss: 2.0143 - val_mean_absolute_error: 2.0143
Epoch 89/1000
11/11 [==============================] - 1s 46ms/step - loss: 1.3453 - mean_absolute_error: 1.3453 - val_loss: 2.0613 - val_mean_absolute_error: 2.0613
Epoch 90/1000
11/11 [==============================] - 0s 30ms/step - loss: 1.5056 - mean_absolute_error: 1.5056 - val_loss: 2.0698 - val_mean_absolute_error: 2.0698
Epoch 91/1000
11/11 [==============================] - 0s 38ms/step - loss: 1.4224 - mean_absolute_error: 1.4224 - val_loss: 2.0607 - val_mean_absolute_error: 2.0607
Epoch 92/1000
11/11 [==============================] - 0s 38ms/step - loss: 1.2709 - mean_absolute_error: 1.2709 - val_loss: 1.9803 - val_mean_absolute_error: 1.9803
Epoch 93/1000
11/11 [==============================] - 0s 39ms/step - loss: 1.2502 - mean_absolute_error: 1.2502 - val_loss: 1.9780 - val_mean_absolute_error: 1.9780
Epoch 94/1000
11/11 [==============================] - 1s 49ms/step - loss: 1.2368 - mean_absolute_error: 1.2368 - val_loss: 2.1255 - val_mean_absolute_error: 2.1255
Epoch 95/1000
11/11 [==============================] - 0s 35ms/step - loss: 1.2122 - mean_absolute_error: 1.2122 - val_loss: 1.9645 - val_mean_absolute_error: 1.9645
Epoch 96/1000
11/11 [==============================] - 0s 19ms/step - loss: 1.2159 - mean_absolute_error: 1.2159 - val_loss: 2.0048 - val_mean_absolute_error: 2.0048
Epoch 97/1000
11/11 [==============================] - 0s 19ms/step - loss: 1.2387 - mean_absolute_error: 1.2387 - val_loss: 1.9712 - val_mean_absolute_error: 1.9712
Epoch 98/1000
11/11 [==============================] - 0s 27ms/step - loss: 1.1885 - mean_absolute_error: 1.1885 - val_loss: 2.0537 - val_mean_absolute_error: 2.0537
Epoch 99/1000
11/11 [==============================] - 0s 19ms/step - loss: 1.2312 - mean_absolute_error: 1.2312 - val_loss: 2.0103 - val_mean_absolute_error: 2.0103
Epoch 100/1000
11/11 [==============================] - 0s 15ms/step - loss: 1.1654 - mean_absolute_error: 1.1654 - val_loss: 1.9860 - val_mean_absolute_error: 1.9860
Epoch 101/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.1361 - mean_absolute_error: 1.1361 - val_loss: 2.1472 - val_mean_absolute_error: 2.1472
Epoch 102/1000
11/11 [==============================] - 0s 19ms/step - loss: 1.2126 - mean_absolute_error: 1.2126 - val_loss: 2.0633 - val_mean_absolute_error: 2.0633
Epoch 103/1000
11/11 [==============================] - 0s 19ms/step - loss: 1.1202 - mean_absolute_error: 1.1202 - val_loss: 1.9753 - val_mean_absolute_error: 1.9753
Epoch 104/1000
11/11 [==============================] - 0s 20ms/step - loss: 1.1513 - mean_absolute_error: 1.1513 - val_loss: 1.9819 - val_mean_absolute_error: 1.9819
Epoch 105/1000
11/11 [==============================] - 0s 15ms/step - loss: 1.1086 - mean_absolute_error: 1.1086 - val_loss: 2.1058 - val_mean_absolute_error: 2.1058
Epoch 106/1000
11/11 [==============================] - 0s 15ms/step - loss: 1.1753 - mean_absolute_error: 1.1753 - val_loss: 1.9937 - val_mean_absolute_error: 1.9937
Epoch 107/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.1008 - mean_absolute_error: 1.1008 - val_loss: 2.1282 - val_mean_absolute_error: 2.1282
Epoch 108/1000
11/11 [==============================] - 0s 15ms/step - loss: 1.1643 - mean_absolute_error: 1.1643 - val_loss: 2.1484 - val_mean_absolute_error: 2.1484
Epoch 109/1000
11/11 [==============================] - 0s 19ms/step - loss: 1.1269 - mean_absolute_error: 1.1269 - val_loss: 1.9457 - val_mean_absolute_error: 1.9457
Epoch 110/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.0793 - mean_absolute_error: 1.0793 - val_loss: 2.0346 - val_mean_absolute_error: 2.0346
Epoch 111/1000
11/11 [==============================] - 0s 15ms/step - loss: 1.0799 - mean_absolute_error: 1.0799 - val_loss: 2.2724 - val_mean_absolute_error: 2.2724
Epoch 112/1000
11/11 [==============================] - 0s 19ms/step - loss: 1.2019 - mean_absolute_error: 1.2019 - val_loss: 2.0568 - val_mean_absolute_error: 2.0568
Epoch 113/1000
11/11 [==============================] - 0s 15ms/step - loss: 1.0600 - mean_absolute_error: 1.0600 - val_loss: 1.9845 - val_mean_absolute_error: 1.9845
Epoch 114/1000
11/11 [==============================] - 0s 19ms/step - loss: 1.0566 - mean_absolute_error: 1.0566 - val_loss: 1.9400 - val_mean_absolute_error: 1.9400
Epoch 115/1000
11/11 [==============================] - 0s 15ms/step - loss: 1.0861 - mean_absolute_error: 1.0861 - val_loss: 1.9844 - val_mean_absolute_error: 1.9844
Epoch 116/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.1038 - mean_absolute_error: 1.1038 - val_loss: 2.0609 - val_mean_absolute_error: 2.0609
Epoch 117/1000
11/11 [==============================] - 0s 15ms/step - loss: 1.2000 - mean_absolute_error: 1.2000 - val_loss: 2.4101 - val_mean_absolute_error: 2.4101
Epoch 118/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.1607 - mean_absolute_error: 1.1607 - val_loss: 2.0311 - val_mean_absolute_error: 2.0311
Epoch 119/1000
11/11 [==============================] - 0s 20ms/step - loss: 1.1044 - mean_absolute_error: 1.1044 - val_loss: 1.9179 - val_mean_absolute_error: 1.9179
Epoch 120/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.0763 - mean_absolute_error: 1.0763 - val_loss: 1.9386 - val_mean_absolute_error: 1.9386
Epoch 121/1000
11/11 [==============================] - 0s 20ms/step - loss: 1.0705 - mean_absolute_error: 1.0705 - val_loss: 1.9155 - val_mean_absolute_error: 1.9155
Epoch 122/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.9973 - mean_absolute_error: 0.9973 - val_loss: 1.8721 - val_mean_absolute_error: 1.8721
Epoch 123/1000

11/11 [==============================] - 0s 15ms/step - loss: 1.0106 - mean_absolute_error: 1.0106 - val_loss: 1.8760 - val_mean_absolute_error: 1.8760
Epoch 124/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.0995 - mean_absolute_error: 1.0995 - val_loss: 1.9310 - val_mean_absolute_error: 1.9310
Epoch 125/1000
11/11 [==============================] - 0s 15ms/step - loss: 1.1840 - mean_absolute_error: 1.1840 - val_loss: 2.0956 - val_mean_absolute_error: 2.0956
Epoch 126/1000
11/11 [==============================] - 0s 15ms/step - loss: 1.0776 - mean_absolute_error: 1.0776 - val_loss: 2.0395 - val_mean_absolute_error: 2.0395
Epoch 127/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.0092 - mean_absolute_error: 1.0092 - val_loss: 1.9151 - val_mean_absolute_error: 1.9151
Epoch 128/1000
11/11 [==============================] - 0s 15ms/step - loss: 1.1137 - mean_absolute_error: 1.1137 - val_loss: 1.8942 - val_mean_absolute_error: 1.8942
Epoch 129/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.0869 - mean_absolute_error: 1.0869 - val_loss: 1.9226 - val_mean_absolute_error: 1.9226
Epoch 130/1000
11/11 [==============================] - 0s 39ms/step - loss: 1.3056 - mean_absolute_error: 1.3056 - val_loss: 1.9340 - val_mean_absolute_error: 1.9340
Epoch 131/1000
11/11 [==============================] - 0s 20ms/step - loss: 1.0795 - mean_absolute_error: 1.0795 - val_loss: 1.9185 - val_mean_absolute_error: 1.9185
Epoch 132/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.9808 - mean_absolute_error: 0.9808 - val_loss: 2.0355 - val_mean_absolute_error: 2.0355
Epoch 133/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.9669 - mean_absolute_error: 0.9669 - val_loss: 1.9131 - val_mean_absolute_error: 1.9131
Epoch 134/1000
11/11 [==============================] - 0s 19ms/step - loss: 1.0080 - mean_absolute_error: 1.0080 - val_loss: 2.0300 - val_mean_absolute_error: 2.0300
Epoch 135/1000
11/11 [==============================] - 0s 16ms/step - loss: 1.0322 - mean_absolute_error: 1.0322 - val_loss: 1.9715 - val_mean_absolute_error: 1.9715
Epoch 136/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.9175 - mean_absolute_error: 0.9175 - val_loss: 1.9549 - val_mean_absolute_error: 1.9549
Epoch 137/1000
11/11 [==============================] - 0s 31ms/step - loss: 0.9086 - mean_absolute_error: 0.9086 - val_loss: 1.9250 - val_mean_absolute_error: 1.9250
Epoch 138/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.9198 - mean_absolute_error: 0.9198 - val_loss: 1.8879 - val_mean_absolute_error: 1.8879
Epoch 139/1000
11/11 [==============================] - 0s 19ms/step - loss: 1.0301 - mean_absolute_error: 1.0301 - val_loss: 2.0088 - val_mean_absolute_error: 2.0088
Epoch 140/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.9489 - mean_absolute_error: 0.9489 - val_loss: 1.8594 - val_mean_absolute_error: 1.8594
Epoch 141/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.9333 - mean_absolute_error: 0.9333 - val_loss: 1.9823 - val_mean_absolute_error: 1.9823
Epoch 142/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.9877 - mean_absolute_error: 0.9877 - val_loss: 2.1532 - val_mean_absolute_error: 2.1532
Epoch 143/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.9730 - mean_absolute_error: 0.9730 - val_loss: 1.9380 - val_mean_absolute_error: 1.9380
Epoch 144/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.8885 - mean_absolute_error: 0.8885 - val_loss: 1.9184 - val_mean_absolute_error: 1.9184
Epoch 145/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.8970 - mean_absolute_error: 0.8970 - val_loss: 2.0551 - val_mean_absolute_error: 2.0551
Epoch 146/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.9317 - mean_absolute_error: 0.9317 - val_loss: 1.9296 - val_mean_absolute_error: 1.9296
Epoch 147/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.8954 - mean_absolute_error: 0.8954 - val_loss: 2.0014 - val_mean_absolute_error: 2.0014
Epoch 148/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.8977 - mean_absolute_error: 0.8977 - val_loss: 2.1213 - val_mean_absolute_error: 2.1213
Epoch 149/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.9408 - mean_absolute_error: 0.9408 - val_loss: 2.1634 - val_mean_absolute_error: 2.1634
Epoch 150/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.8867 - mean_absolute_error: 0.8867 - val_loss: 2.0479 - val_mean_absolute_error: 2.0479
Epoch 151/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.9263 - mean_absolute_error: 0.9263 - val_loss: 2.1382 - val_mean_absolute_error: 2.1382
Epoch 152/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.9636 - mean_absolute_error: 0.9636 - val_loss: 1.8717 - val_mean_absolute_error: 1.8717
Epoch 153/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.8602 - mean_absolute_error: 0.8602 - val_loss: 1.8858 - val_mean_absolute_error: 1.8858
Epoch 154/1000
11/11 [==============================] - 0s 30ms/step - loss: 0.8531 - mean_absolute_error: 0.8531 - val_loss: 1.9974 - val_mean_absolute_error: 1.9974
Epoch 155/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.8351 - mean_absolute_error: 0.8351 - val_loss: 1.9783 - val_mean_absolute_error: 1.9783
Epoch 156/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.8997 - mean_absolute_error: 0.8997 - val_loss: 1.9947 - val_mean_absolute_error: 1.9947
Epoch 157/1000
11/11 [==============================] - 0s 33ms/step - loss: 0.8314 - mean_absolute_error: 0.8314 - val_loss: 1.8347 - val_mean_absolute_error: 1.8347
Epoch 158/1000
11/11 [==============================] - 0s 32ms/step - loss: 0.8122 - mean_absolute_error: 0.8122 - val_loss: 1.8938 - val_mean_absolute_error: 1.8938
Epoch 159/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.8456 - mean_absolute_error: 0.8456 - val_loss: 1.9623 - val_mean_absolute_error: 1.9623
Epoch 160/1000
11/11 [==============================] - 0s 26ms/step - loss: 0.8399 - mean_absolute_error: 0.8399 - val_loss: 1.9067 - val_mean_absolute_error: 1.9067
Epoch 161/1000
11/11 [==============================] - 0s 24ms/step - loss: 0.8672 - mean_absolute_error: 0.8672 - val_loss: 2.2034 - val_mean_absolute_error: 2.2034
Epoch 162/1000
11/11 [==============================] - 0s 27ms/step - loss: 0.9412 - mean_absolute_error: 0.9412 - val_loss: 1.9506 - val_mean_absolute_error: 1.9506
Epoch 163/1000
11/11 [==============================] - 0s 27ms/step - loss: 0.8174 - mean_absolute_error: 0.8174 - val_loss: 1.9969 - val_mean_absolute_error: 1.9969
Epoch 164/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.8205 - mean_absolute_error: 0.8205 - val_loss: 1.9872 - val_mean_absolute_error: 1.9872
Epoch 165/1000
11/11 [==============================] - 0s 24ms/step - loss: 0.8260 - mean_absolute_error: 0.8260 - val_loss: 1.8875 - val_mean_absolute_error: 1.8875
Epoch 166/1000
11/11 [==============================] - 1s 49ms/step - loss: 0.7979 - mean_absolute_error: 0.7979 - val_loss: 2.1529 - val_mean_absolute_error: 2.1529
Epoch 167/1000
11/11 [==============================] - 0s 31ms/step - loss: 0.8705 - mean_absolute_error: 0.8705 - val_loss: 1.8407 - val_mean_absolute_error: 1.8407
Epoch 168/1000
11/11 [==============================] - 0s 25ms/step - loss: 0.8619 - mean_absolute_error: 0.8619 - val_loss: 1.8233 - val_mean_absolute_error: 1.8233
Epoch 169/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.8498 - mean_absolute_error: 0.8498 - val_loss: 2.0358 - val_mean_absolute_error: 2.0358
Epoch 170/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.8354 - mean_absolute_error: 0.8354 - val_loss: 1.8575 - val_mean_absolute_error: 1.8575
Epoch 171/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.7762 - mean_absolute_error: 0.7762 - val_loss: 2.0391 - val_mean_absolute_error: 2.0391
Epoch 172/1000

11/11 [==============================] - 0s 16ms/step - loss: 0.8217 - mean_absolute_error: 0.8217 - val_loss: 1.9211 - val_mean_absolute_error: 1.9211
Epoch 173/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.8477 - mean_absolute_error: 0.8477 - val_loss: 1.8418 - val_mean_absolute_error: 1.8418
Epoch 174/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.7741 - mean_absolute_error: 0.7741 - val_loss: 1.9218 - val_mean_absolute_error: 1.9218
Epoch 175/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.7551 - mean_absolute_error: 0.7551 - val_loss: 1.8684 - val_mean_absolute_error: 1.8684
Epoch 176/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.7652 - mean_absolute_error: 0.7652 - val_loss: 1.9477 - val_mean_absolute_error: 1.9477
Epoch 177/1000
11/11 [==============================] - 0s 25ms/step - loss: 0.7063 - mean_absolute_error: 0.7063 - val_loss: 1.9353 - val_mean_absolute_error: 1.9353
Epoch 178/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.7331 - mean_absolute_error: 0.7331 - val_loss: 1.9180 - val_mean_absolute_error: 1.9180
Epoch 179/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.8489 - mean_absolute_error: 0.8489 - val_loss: 2.3095 - val_mean_absolute_error: 2.3095
Epoch 180/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.9576 - mean_absolute_error: 0.9576 - val_loss: 1.9110 - val_mean_absolute_error: 1.9110
Epoch 181/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.7855 - mean_absolute_error: 0.7855 - val_loss: 1.9480 - val_mean_absolute_error: 1.9480
Epoch 182/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.6912 - mean_absolute_error: 0.6912 - val_loss: 2.0082 - val_mean_absolute_error: 2.0082
Epoch 183/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.7287 - mean_absolute_error: 0.7287 - val_loss: 1.9195 - val_mean_absolute_error: 1.9195
Epoch 184/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.6862 - mean_absolute_error: 0.6862 - val_loss: 1.8635 - val_mean_absolute_error: 1.8635
Epoch 185/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.7508 - mean_absolute_error: 0.7508 - val_loss: 1.9155 - val_mean_absolute_error: 1.9155
Epoch 186/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.7293 - mean_absolute_error: 0.7293 - val_loss: 2.0080 - val_mean_absolute_error: 2.0080
Epoch 187/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.7381 - mean_absolute_error: 0.7381 - val_loss: 1.9263 - val_mean_absolute_error: 1.9263
Epoch 188/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.7192 - mean_absolute_error: 0.7192 - val_loss: 1.9374 - val_mean_absolute_error: 1.9374
Epoch 189/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.6984 - mean_absolute_error: 0.6984 - val_loss: 1.8840 - val_mean_absolute_error: 1.8840
Epoch 190/1000
11/11 [==============================] - 0s 36ms/step - loss: 0.6966 - mean_absolute_error: 0.6966 - val_loss: 1.9579 - val_mean_absolute_error: 1.9579
Epoch 191/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.7136 - mean_absolute_error: 0.7136 - val_loss: 2.0600 - val_mean_absolute_error: 2.0600
Epoch 192/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.7038 - mean_absolute_error: 0.7038 - val_loss: 1.8365 - val_mean_absolute_error: 1.8365
Epoch 193/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.7096 - mean_absolute_error: 0.7096 - val_loss: 1.8663 - val_mean_absolute_error: 1.8663
Epoch 194/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.7015 - mean_absolute_error: 0.7015 - val_loss: 2.0918 - val_mean_absolute_error: 2.0918
Epoch 195/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.7076 - mean_absolute_error: 0.7076 - val_loss: 1.9483 - val_mean_absolute_error: 1.9483
Epoch 196/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.7363 - mean_absolute_error: 0.7363 - val_loss: 1.8757 - val_mean_absolute_error: 1.8757
Epoch 197/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.7176 - mean_absolute_error: 0.7176 - val_loss: 2.0944 - val_mean_absolute_error: 2.0944
Epoch 198/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.7141 - mean_absolute_error: 0.7141 - val_loss: 1.8704 - val_mean_absolute_error: 1.8704
Epoch 199/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.7880 - mean_absolute_error: 0.7880 - val_loss: 1.9296 - val_mean_absolute_error: 1.9296
Epoch 200/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.6440 - mean_absolute_error: 0.6440 - val_loss: 1.8662 - val_mean_absolute_error: 1.8662
Epoch 201/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.6199 - mean_absolute_error: 0.6199 - val_loss: 2.0491 - val_mean_absolute_error: 2.0491
Epoch 202/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.7291 - mean_absolute_error: 0.7291 - val_loss: 1.8603 - val_mean_absolute_error: 1.8603
Epoch 203/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.7402 - mean_absolute_error: 0.7402 - val_loss: 2.0869 - val_mean_absolute_error: 2.0869
Epoch 204/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.8721 - mean_absolute_error: 0.8721 - val_loss: 1.9123 - val_mean_absolute_error: 1.9123
Epoch 205/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.6893 - mean_absolute_error: 0.6893 - val_loss: 1.9489 - val_mean_absolute_error: 1.9489
Epoch 206/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.6473 - mean_absolute_error: 0.6473 - val_loss: 1.8434 - val_mean_absolute_error: 1.8434
Epoch 207/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.6076 - mean_absolute_error: 0.6076 - val_loss: 1.9710 - val_mean_absolute_error: 1.9710
Epoch 208/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.6375 - mean_absolute_error: 0.6375 - val_loss: 2.2792 - val_mean_absolute_error: 2.2792
Epoch 209/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.9595 - mean_absolute_error: 0.9595 - val_loss: 2.2046 - val_mean_absolute_error: 2.2046
Epoch 210/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.9045 - mean_absolute_error: 0.9045 - val_loss: 2.1536 - val_mean_absolute_error: 2.1536
Epoch 211/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.7424 - mean_absolute_error: 0.7424 - val_loss: 1.9653 - val_mean_absolute_error: 1.9653
Epoch 212/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.6610 - mean_absolute_error: 0.6610 - val_loss: 1.9504 - val_mean_absolute_error: 1.9504
Epoch 213/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.6929 - mean_absolute_error: 0.6929 - val_loss: 1.9589 - val_mean_absolute_error: 1.9589
Epoch 214/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.6721 - mean_absolute_error: 0.6721 - val_loss: 1.8556 - val_mean_absolute_error: 1.8556
Epoch 215/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.7436 - mean_absolute_error: 0.7436 - val_loss: 2.0297 - val_mean_absolute_error: 2.0297
Epoch 216/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.6314 - mean_absolute_error: 0.6314 - val_loss: 1.8846 - val_mean_absolute_error: 1.8846
Epoch 217/1000
11/11 [==============================] - 0s 21ms/step - loss: 0.6816 - mean_absolute_error: 0.6816 - val_loss: 1.9681 - val_mean_absolute_error: 1.9681
Epoch 218/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.6717 - mean_absolute_error: 0.6717 - val_loss: 1.8055 - val_mean_absolute_error: 1.8055
Epoch 219/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.6966 - mean_absolute_error: 0.6966 - val_loss: 1.9492 - val_mean_absolute_error: 1.9492
Epoch 220/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.6141 - mean_absolute_error: 0.6141 - val_loss: 1.8959 - val_mean_absolute_error: 1.8959
Epoch 221/1000

11/11 [==============================] - 0s 15ms/step - loss: 0.5801 - mean_absolute_error: 0.5801 - val_loss: 1.8147 - val_mean_absolute_error: 1.8147
Epoch 222/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.6490 - mean_absolute_error: 0.6490 - val_loss: 1.9416 - val_mean_absolute_error: 1.9416
Epoch 223/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.6496 - mean_absolute_error: 0.6496 - val_loss: 1.8592 - val_mean_absolute_error: 1.8592
Epoch 224/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.6813 - mean_absolute_error: 0.6813 - val_loss: 1.9249 - val_mean_absolute_error: 1.9249
Epoch 225/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.6394 - mean_absolute_error: 0.6394 - val_loss: 1.9302 - val_mean_absolute_error: 1.9302
Epoch 226/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.6449 - mean_absolute_error: 0.6449 - val_loss: 1.9165 - val_mean_absolute_error: 1.9165
Epoch 227/1000
11/11 [==============================] - 1s 52ms/step - loss: 0.6182 - mean_absolute_error: 0.6182 - val_loss: 1.8732 - val_mean_absolute_error: 1.8732
Epoch 228/1000
11/11 [==============================] - 0s 26ms/step - loss: 0.6266 - mean_absolute_error: 0.6266 - val_loss: 1.9652 - val_mean_absolute_error: 1.9652
Epoch 229/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.6750 - mean_absolute_error: 0.6750 - val_loss: 1.8433 - val_mean_absolute_error: 1.8433
Epoch 230/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.6777 - mean_absolute_error: 0.6777 - val_loss: 2.0398 - val_mean_absolute_error: 2.0398
Epoch 231/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.8003 - mean_absolute_error: 0.8003 - val_loss: 1.9602 - val_mean_absolute_error: 1.9602
Epoch 232/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.6365 - mean_absolute_error: 0.6365 - val_loss: 1.8184 - val_mean_absolute_error: 1.8184
Epoch 233/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.6232 - mean_absolute_error: 0.6232 - val_loss: 1.9502 - val_mean_absolute_error: 1.9502
Epoch 234/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5614 - mean_absolute_error: 0.5614 - val_loss: 1.8892 - val_mean_absolute_error: 1.8892
Epoch 235/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.5737 - mean_absolute_error: 0.5737 - val_loss: 1.9479 - val_mean_absolute_error: 1.9479
Epoch 236/1000
11/11 [==============================] - 0s 27ms/step - loss: 0.5612 - mean_absolute_error: 0.5612 - val_loss: 1.8867 - val_mean_absolute_error: 1.8867
Epoch 237/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.6117 - mean_absolute_error: 0.6117 - val_loss: 1.9183 - val_mean_absolute_error: 1.9183
Epoch 238/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.6225 - mean_absolute_error: 0.6225 - val_loss: 1.9000 - val_mean_absolute_error: 1.9000
Epoch 239/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.6455 - mean_absolute_error: 0.6455 - val_loss: 1.8899 - val_mean_absolute_error: 1.8899
Epoch 240/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.5882 - mean_absolute_error: 0.5882 - val_loss: 1.9679 - val_mean_absolute_error: 1.9679
Epoch 241/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.6529 - mean_absolute_error: 0.6529 - val_loss: 1.8948 - val_mean_absolute_error: 1.8948
Epoch 242/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.7549 - mean_absolute_error: 0.7549 - val_loss: 1.9040 - val_mean_absolute_error: 1.9040
Epoch 243/1000
11/11 [==============================] - 0s 26ms/step - loss: 0.7379 - mean_absolute_error: 0.7379 - val_loss: 1.9800 - val_mean_absolute_error: 1.9800
Epoch 244/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.6419 - mean_absolute_error: 0.6419 - val_loss: 1.9091 - val_mean_absolute_error: 1.9091
Epoch 245/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.6334 - mean_absolute_error: 0.6334 - val_loss: 1.8629 - val_mean_absolute_error: 1.8629
Epoch 246/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.6044 - mean_absolute_error: 0.6044 - val_loss: 1.8713 - val_mean_absolute_error: 1.8713
Epoch 247/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.6104 - mean_absolute_error: 0.6104 - val_loss: 1.8469 - val_mean_absolute_error: 1.8469
Epoch 248/1000
11/11 [==============================] - 0s 28ms/step - loss: 0.6285 - mean_absolute_error: 0.6285 - val_loss: 1.9628 - val_mean_absolute_error: 1.9628
Epoch 249/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.5914 - mean_absolute_error: 0.5914 - val_loss: 1.8455 - val_mean_absolute_error: 1.8455
Epoch 250/1000
11/11 [==============================] - 0s 21ms/step - loss: 0.5553 - mean_absolute_error: 0.5553 - val_loss: 1.9946 - val_mean_absolute_error: 1.9946
Epoch 251/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.6072 - mean_absolute_error: 0.6072 - val_loss: 1.8067 - val_mean_absolute_error: 1.8067
Epoch 252/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.6617 - mean_absolute_error: 0.6617 - val_loss: 1.9660 - val_mean_absolute_error: 1.9660
Epoch 253/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.6073 - mean_absolute_error: 0.6073 - val_loss: 1.9435 - val_mean_absolute_error: 1.9435
Epoch 254/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.6106 - mean_absolute_error: 0.6106 - val_loss: 1.8182 - val_mean_absolute_error: 1.8182
Epoch 255/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.5935 - mean_absolute_error: 0.5935 - val_loss: 1.9560 - val_mean_absolute_error: 1.9560
Epoch 256/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.6262 - mean_absolute_error: 0.6262 - val_loss: 2.0411 - val_mean_absolute_error: 2.0411
Epoch 257/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.6690 - mean_absolute_error: 0.6690 - val_loss: 1.8977 - val_mean_absolute_error: 1.8977
Epoch 258/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5624 - mean_absolute_error: 0.5624 - val_loss: 1.9643 - val_mean_absolute_error: 1.9643
Epoch 259/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5604 - mean_absolute_error: 0.5604 - val_loss: 1.8913 - val_mean_absolute_error: 1.8913
Epoch 260/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.5296 - mean_absolute_error: 0.5296 - val_loss: 1.9024 - val_mean_absolute_error: 1.9024
Epoch 261/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5271 - mean_absolute_error: 0.5271 - val_loss: 1.8677 - val_mean_absolute_error: 1.8677
Epoch 262/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.5472 - mean_absolute_error: 0.5472 - val_loss: 1.8371 - val_mean_absolute_error: 1.8371
Epoch 263/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.5155 - mean_absolute_error: 0.5155 - val_loss: 1.9048 - val_mean_absolute_error: 1.9048
Epoch 264/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5158 - mean_absolute_error: 0.5158 - val_loss: 1.9215 - val_mean_absolute_error: 1.9215
Epoch 265/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4758 - mean_absolute_error: 0.4758 - val_loss: 1.8946 - val_mean_absolute_error: 1.8946
Epoch 266/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.5167 - mean_absolute_error: 0.5167 - val_loss: 1.8918 - val_mean_absolute_error: 1.8918
Epoch 267/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5261 - mean_absolute_error: 0.5261 - val_loss: 1.9319 - val_mean_absolute_error: 1.9319
Epoch 268/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.6094 - mean_absolute_error: 0.6094 - val_loss: 1.8327 - val_mean_absolute_error: 1.8327
Epoch 269/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.5176 - mean_absolute_error: 0.5176 - val_loss: 1.9228 - val_mean_absolute_error: 1.9228
Epoch 270/1000

11/11 [==============================] - 0s 16ms/step - loss: 0.5551 - mean_absolute_error: 0.5551 - val_loss: 1.9160 - val_mean_absolute_error: 1.9160
Epoch 271/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.5109 - mean_absolute_error: 0.5109 - val_loss: 1.8303 - val_mean_absolute_error: 1.8303
Epoch 272/1000
11/11 [==============================] - 0s 24ms/step - loss: 0.5004 - mean_absolute_error: 0.5004 - val_loss: 1.8422 - val_mean_absolute_error: 1.8422
Epoch 273/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.5057 - mean_absolute_error: 0.5057 - val_loss: 1.9723 - val_mean_absolute_error: 1.9723
Epoch 274/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5851 - mean_absolute_error: 0.5851 - val_loss: 1.8730 - val_mean_absolute_error: 1.8730
Epoch 275/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5894 - mean_absolute_error: 0.5894 - val_loss: 2.0306 - val_mean_absolute_error: 2.0306
Epoch 276/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.5586 - mean_absolute_error: 0.5586 - val_loss: 1.8736 - val_mean_absolute_error: 1.8736
Epoch 277/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.5113 - mean_absolute_error: 0.5113 - val_loss: 2.0549 - val_mean_absolute_error: 2.0549
Epoch 278/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.6425 - mean_absolute_error: 0.6425 - val_loss: 1.9329 - val_mean_absolute_error: 1.9329
Epoch 279/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.5835 - mean_absolute_error: 0.5835 - val_loss: 1.8480 - val_mean_absolute_error: 1.8480
Epoch 280/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.5363 - mean_absolute_error: 0.5363 - val_loss: 1.8790 - val_mean_absolute_error: 1.8790
Epoch 281/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.5376 - mean_absolute_error: 0.5376 - val_loss: 1.9483 - val_mean_absolute_error: 1.9483
Epoch 282/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5272 - mean_absolute_error: 0.5272 - val_loss: 1.8574 - val_mean_absolute_error: 1.8574
Epoch 283/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.6131 - mean_absolute_error: 0.6131 - val_loss: 1.9260 - val_mean_absolute_error: 1.9260
Epoch 284/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5456 - mean_absolute_error: 0.5456 - val_loss: 1.8476 - val_mean_absolute_error: 1.8476
Epoch 285/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4706 - mean_absolute_error: 0.4706 - val_loss: 1.8735 - val_mean_absolute_error: 1.8735
Epoch 286/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.5519 - mean_absolute_error: 0.5519 - val_loss: 2.0527 - val_mean_absolute_error: 2.0527
Epoch 287/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5436 - mean_absolute_error: 0.5436 - val_loss: 1.8578 - val_mean_absolute_error: 1.8578
Epoch 288/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5195 - mean_absolute_error: 0.5195 - val_loss: 1.8898 - val_mean_absolute_error: 1.8898
Epoch 289/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4492 - mean_absolute_error: 0.4492 - val_loss: 1.8987 - val_mean_absolute_error: 1.8987
Epoch 290/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4831 - mean_absolute_error: 0.4831 - val_loss: 2.0177 - val_mean_absolute_error: 2.0177
Epoch 291/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5033 - mean_absolute_error: 0.5033 - val_loss: 1.9086 - val_mean_absolute_error: 1.9086
Epoch 292/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.5421 - mean_absolute_error: 0.5421 - val_loss: 1.9493 - val_mean_absolute_error: 1.9493
Epoch 293/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.5228 - mean_absolute_error: 0.5228 - val_loss: 1.9110 - val_mean_absolute_error: 1.9110
Epoch 294/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4746 - mean_absolute_error: 0.4746 - val_loss: 1.9566 - val_mean_absolute_error: 1.9566
Epoch 295/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4763 - mean_absolute_error: 0.4763 - val_loss: 1.8546 - val_mean_absolute_error: 1.8546
Epoch 296/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4543 - mean_absolute_error: 0.4543 - val_loss: 1.9088 - val_mean_absolute_error: 1.9088
Epoch 297/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.5388 - mean_absolute_error: 0.5388 - val_loss: 1.8604 - val_mean_absolute_error: 1.8604
Epoch 298/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4862 - mean_absolute_error: 0.4862 - val_loss: 1.9614 - val_mean_absolute_error: 1.9614
Epoch 299/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4795 - mean_absolute_error: 0.4795 - val_loss: 1.8370 - val_mean_absolute_error: 1.8370
Epoch 300/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5358 - mean_absolute_error: 0.5358 - val_loss: 1.8805 - val_mean_absolute_error: 1.8805
Epoch 301/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4808 - mean_absolute_error: 0.4808 - val_loss: 1.8438 - val_mean_absolute_error: 1.8438
Epoch 302/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4643 - mean_absolute_error: 0.4643 - val_loss: 1.8568 - val_mean_absolute_error: 1.8568
Epoch 303/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5292 - mean_absolute_error: 0.5292 - val_loss: 2.0339 - val_mean_absolute_error: 2.0339
Epoch 304/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4864 - mean_absolute_error: 0.4864 - val_loss: 1.8972 - val_mean_absolute_error: 1.8972
Epoch 305/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.4807 - mean_absolute_error: 0.4807 - val_loss: 1.8927 - val_mean_absolute_error: 1.8927
Epoch 306/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4647 - mean_absolute_error: 0.4647 - val_loss: 1.9231 - val_mean_absolute_error: 1.9231
Epoch 307/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4411 - mean_absolute_error: 0.4411 - val_loss: 1.9341 - val_mean_absolute_error: 1.9341
Epoch 308/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4796 - mean_absolute_error: 0.4796 - val_loss: 1.9223 - val_mean_absolute_error: 1.9223
Epoch 309/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5511 - mean_absolute_error: 0.5511 - val_loss: 1.8631 - val_mean_absolute_error: 1.8631
Epoch 310/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5084 - mean_absolute_error: 0.5084 - val_loss: 1.9375 - val_mean_absolute_error: 1.9375
Epoch 311/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4891 - mean_absolute_error: 0.4891 - val_loss: 1.8573 - val_mean_absolute_error: 1.8573
Epoch 312/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4768 - mean_absolute_error: 0.4768 - val_loss: 1.9630 - val_mean_absolute_error: 1.9630
Epoch 313/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5159 - mean_absolute_error: 0.5159 - val_loss: 1.8909 - val_mean_absolute_error: 1.8909
Epoch 314/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.4995 - mean_absolute_error: 0.4995 - val_loss: 1.9024 - val_mean_absolute_error: 1.9024
Epoch 315/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4748 - mean_absolute_error: 0.4748 - val_loss: 1.9099 - val_mean_absolute_error: 1.9099
Epoch 316/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4914 - mean_absolute_error: 0.4914 - val_loss: 1.8582 - val_mean_absolute_error: 1.8582
Epoch 317/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.4712 - mean_absolute_error: 0.4712 - val_loss: 1.8960 - val_mean_absolute_error: 1.8960
Epoch 318/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4766 - mean_absolute_error: 0.4766 - val_loss: 1.8722 - val_mean_absolute_error: 1.8722
Epoch 319/1000

11/11 [==============================] - 0s 25ms/step - loss: 0.4462 - mean_absolute_error: 0.4462 - val_loss: 1.8888 - val_mean_absolute_error: 1.8888
Epoch 320/1000
11/11 [==============================] - 0s 36ms/step - loss: 0.4691 - mean_absolute_error: 0.4691 - val_loss: 1.9337 - val_mean_absolute_error: 1.9337
Epoch 321/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4776 - mean_absolute_error: 0.4776 - val_loss: 1.9328 - val_mean_absolute_error: 1.9328
Epoch 322/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4984 - mean_absolute_error: 0.4984 - val_loss: 1.8735 - val_mean_absolute_error: 1.8735
Epoch 323/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.4429 - mean_absolute_error: 0.4429 - val_loss: 1.8737 - val_mean_absolute_error: 1.8737
Epoch 324/1000
11/11 [==============================] - 0s 29ms/step - loss: 0.4324 - mean_absolute_error: 0.4324 - val_loss: 1.8295 - val_mean_absolute_error: 1.8295
Epoch 325/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.4742 - mean_absolute_error: 0.4742 - val_loss: 1.9742 - val_mean_absolute_error: 1.9742
Epoch 326/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4650 - mean_absolute_error: 0.4650 - val_loss: 1.9888 - val_mean_absolute_error: 1.9888
Epoch 327/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.4860 - mean_absolute_error: 0.4860 - val_loss: 1.8436 - val_mean_absolute_error: 1.8436
Epoch 328/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.4309 - mean_absolute_error: 0.4309 - val_loss: 1.9872 - val_mean_absolute_error: 1.9872
Epoch 329/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4436 - mean_absolute_error: 0.4436 - val_loss: 1.8400 - val_mean_absolute_error: 1.8400
Epoch 330/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.4254 - mean_absolute_error: 0.4254 - val_loss: 1.8056 - val_mean_absolute_error: 1.8056
Epoch 331/1000
11/11 [==============================] - 0s 34ms/step - loss: 0.4930 - mean_absolute_error: 0.4930 - val_loss: 1.9693 - val_mean_absolute_error: 1.9693
Epoch 332/1000
11/11 [==============================] - 0s 35ms/step - loss: 0.5377 - mean_absolute_error: 0.5377 - val_loss: 1.9343 - val_mean_absolute_error: 1.9343
Epoch 333/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4670 - mean_absolute_error: 0.4670 - val_loss: 1.9153 - val_mean_absolute_error: 1.9153
Epoch 334/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4382 - mean_absolute_error: 0.4382 - val_loss: 1.9847 - val_mean_absolute_error: 1.9847
Epoch 335/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4186 - mean_absolute_error: 0.4186 - val_loss: 1.8824 - val_mean_absolute_error: 1.8824
Epoch 336/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4895 - mean_absolute_error: 0.4895 - val_loss: 1.8250 - val_mean_absolute_error: 1.8250
Epoch 337/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.6406 - mean_absolute_error: 0.6406 - val_loss: 1.9470 - val_mean_absolute_error: 1.9470
Epoch 338/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.6144 - mean_absolute_error: 0.6144 - val_loss: 2.0393 - val_mean_absolute_error: 2.0393
Epoch 339/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5386 - mean_absolute_error: 0.5386 - val_loss: 1.9183 - val_mean_absolute_error: 1.9183
Epoch 340/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.4821 - mean_absolute_error: 0.4821 - val_loss: 1.8400 - val_mean_absolute_error: 1.8400
Epoch 341/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4053 - mean_absolute_error: 0.4053 - val_loss: 1.9165 - val_mean_absolute_error: 1.9165
Epoch 342/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4514 - mean_absolute_error: 0.4514 - val_loss: 1.9900 - val_mean_absolute_error: 1.9900
Epoch 343/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.5261 - mean_absolute_error: 0.5261 - val_loss: 1.8873 - val_mean_absolute_error: 1.8873
Epoch 344/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4461 - mean_absolute_error: 0.4461 - val_loss: 1.9214 - val_mean_absolute_error: 1.9214
Epoch 345/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4298 - mean_absolute_error: 0.4298 - val_loss: 1.9583 - val_mean_absolute_error: 1.9583
Epoch 346/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.5036 - mean_absolute_error: 0.5036 - val_loss: 1.9263 - val_mean_absolute_error: 1.9263
Epoch 347/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.4673 - mean_absolute_error: 0.4673 - val_loss: 2.0113 - val_mean_absolute_error: 2.0113
Epoch 348/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4559 - mean_absolute_error: 0.4559 - val_loss: 1.8554 - val_mean_absolute_error: 1.8554
Epoch 349/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.5125 - mean_absolute_error: 0.5125 - val_loss: 2.0221 - val_mean_absolute_error: 2.0221
Epoch 350/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5516 - mean_absolute_error: 0.5516 - val_loss: 1.8848 - val_mean_absolute_error: 1.8848
Epoch 351/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4168 - mean_absolute_error: 0.4168 - val_loss: 1.9088 - val_mean_absolute_error: 1.9088
Epoch 352/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3990 - mean_absolute_error: 0.3990 - val_loss: 1.8769 - val_mean_absolute_error: 1.8769
Epoch 353/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3666 - mean_absolute_error: 0.3666 - val_loss: 1.8397 - val_mean_absolute_error: 1.8397
Epoch 354/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3915 - mean_absolute_error: 0.3915 - val_loss: 1.8084 - val_mean_absolute_error: 1.8084
Epoch 355/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.5565 - mean_absolute_error: 0.5565 - val_loss: 1.8846 - val_mean_absolute_error: 1.8846
Epoch 356/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5358 - mean_absolute_error: 0.5358 - val_loss: 1.9735 - val_mean_absolute_error: 1.9735
Epoch 357/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.5085 - mean_absolute_error: 0.5085 - val_loss: 1.8279 - val_mean_absolute_error: 1.8279
Epoch 358/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4490 - mean_absolute_error: 0.4490 - val_loss: 1.8441 - val_mean_absolute_error: 1.8441
Epoch 359/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4108 - mean_absolute_error: 0.4108 - val_loss: 1.8612 - val_mean_absolute_error: 1.8612
Epoch 360/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.4016 - mean_absolute_error: 0.4016 - val_loss: 1.9823 - val_mean_absolute_error: 1.9823
Epoch 361/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.5090 - mean_absolute_error: 0.5090 - val_loss: 1.7738 - val_mean_absolute_error: 1.7738
Epoch 362/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4888 - mean_absolute_error: 0.4888 - val_loss: 1.9815 - val_mean_absolute_error: 1.9815
Epoch 363/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4554 - mean_absolute_error: 0.4554 - val_loss: 1.8998 - val_mean_absolute_error: 1.8998
Epoch 364/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4104 - mean_absolute_error: 0.4104 - val_loss: 1.8541 - val_mean_absolute_error: 1.8541
Epoch 365/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4031 - mean_absolute_error: 0.4031 - val_loss: 1.9520 - val_mean_absolute_error: 1.9520
Epoch 366/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.4505 - mean_absolute_error: 0.4505 - val_loss: 1.9395 - val_mean_absolute_error: 1.9395
Epoch 367/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3764 - mean_absolute_error: 0.3764 - val_loss: 1.9035 - val_mean_absolute_error: 1.9035
Epoch 368/1000

11/11 [==============================] - 0s 15ms/step - loss: 0.3633 - mean_absolute_error: 0.3633 - val_loss: 1.8533 - val_mean_absolute_error: 1.8533
Epoch 369/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3777 - mean_absolute_error: 0.3777 - val_loss: 2.1220 - val_mean_absolute_error: 2.1220
Epoch 370/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.5236 - mean_absolute_error: 0.5236 - val_loss: 1.8863 - val_mean_absolute_error: 1.8863
Epoch 371/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4180 - mean_absolute_error: 0.4180 - val_loss: 1.8541 - val_mean_absolute_error: 1.8541
Epoch 372/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5272 - mean_absolute_error: 0.5272 - val_loss: 1.8534 - val_mean_absolute_error: 1.8534
Epoch 373/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4674 - mean_absolute_error: 0.4674 - val_loss: 1.9155 - val_mean_absolute_error: 1.9155
Epoch 374/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4144 - mean_absolute_error: 0.4144 - val_loss: 1.8660 - val_mean_absolute_error: 1.8660
Epoch 375/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4253 - mean_absolute_error: 0.4253 - val_loss: 1.8861 - val_mean_absolute_error: 1.8861
Epoch 376/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3882 - mean_absolute_error: 0.3882 - val_loss: 1.8451 - val_mean_absolute_error: 1.8451
Epoch 377/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3840 - mean_absolute_error: 0.3840 - val_loss: 1.8835 - val_mean_absolute_error: 1.8835
Epoch 378/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3814 - mean_absolute_error: 0.3814 - val_loss: 1.9155 - val_mean_absolute_error: 1.9155
Epoch 379/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4094 - mean_absolute_error: 0.4094 - val_loss: 1.8830 - val_mean_absolute_error: 1.8830
Epoch 380/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4340 - mean_absolute_error: 0.4340 - val_loss: 1.8876 - val_mean_absolute_error: 1.8876
Epoch 381/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4227 - mean_absolute_error: 0.4227 - val_loss: 1.8674 - val_mean_absolute_error: 1.8674
Epoch 382/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4265 - mean_absolute_error: 0.4265 - val_loss: 1.9554 - val_mean_absolute_error: 1.9554
Epoch 383/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4855 - mean_absolute_error: 0.4855 - val_loss: 1.8313 - val_mean_absolute_error: 1.8313
Epoch 384/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4779 - mean_absolute_error: 0.4779 - val_loss: 1.8886 - val_mean_absolute_error: 1.8886
Epoch 385/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.3875 - mean_absolute_error: 0.3875 - val_loss: 1.8135 - val_mean_absolute_error: 1.8135
Epoch 386/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4464 - mean_absolute_error: 0.4464 - val_loss: 1.8993 - val_mean_absolute_error: 1.8993
Epoch 387/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3948 - mean_absolute_error: 0.3948 - val_loss: 1.9223 - val_mean_absolute_error: 1.9223
Epoch 388/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3703 - mean_absolute_error: 0.3703 - val_loss: 1.8877 - val_mean_absolute_error: 1.8877
Epoch 389/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3909 - mean_absolute_error: 0.3909 - val_loss: 1.8724 - val_mean_absolute_error: 1.8724
Epoch 390/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3845 - mean_absolute_error: 0.3845 - val_loss: 1.8738 - val_mean_absolute_error: 1.8738
Epoch 391/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3899 - mean_absolute_error: 0.3899 - val_loss: 1.8743 - val_mean_absolute_error: 1.8743
Epoch 392/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.3891 - mean_absolute_error: 0.3891 - val_loss: 1.9339 - val_mean_absolute_error: 1.9339
Epoch 393/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3935 - mean_absolute_error: 0.3935 - val_loss: 1.8415 - val_mean_absolute_error: 1.8415
Epoch 394/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.4122 - mean_absolute_error: 0.4122 - val_loss: 1.8554 - val_mean_absolute_error: 1.8554
Epoch 395/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5047 - mean_absolute_error: 0.5047 - val_loss: 2.0154 - val_mean_absolute_error: 2.0154
Epoch 396/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.4570 - mean_absolute_error: 0.4570 - val_loss: 1.8540 - val_mean_absolute_error: 1.8540
Epoch 397/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3755 - mean_absolute_error: 0.3755 - val_loss: 1.8182 - val_mean_absolute_error: 1.8182
Epoch 398/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4656 - mean_absolute_error: 0.4656 - val_loss: 2.0501 - val_mean_absolute_error: 2.0501
Epoch 399/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5091 - mean_absolute_error: 0.5091 - val_loss: 1.9028 - val_mean_absolute_error: 1.9028
Epoch 400/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4170 - mean_absolute_error: 0.4170 - val_loss: 1.9892 - val_mean_absolute_error: 1.9892
Epoch 401/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4077 - mean_absolute_error: 0.4077 - val_loss: 1.9276 - val_mean_absolute_error: 1.9276
Epoch 402/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.3810 - mean_absolute_error: 0.3810 - val_loss: 1.8778 - val_mean_absolute_error: 1.8778
Epoch 403/1000
11/11 [==============================] - 0s 35ms/step - loss: 0.4821 - mean_absolute_error: 0.4821 - val_loss: 1.9409 - val_mean_absolute_error: 1.9409
Epoch 404/1000
11/11 [==============================] - 0s 29ms/step - loss: 0.4878 - mean_absolute_error: 0.4878 - val_loss: 1.8630 - val_mean_absolute_error: 1.8630
Epoch 405/1000
11/11 [==============================] - 0s 28ms/step - loss: 0.4769 - mean_absolute_error: 0.4769 - val_loss: 1.9908 - val_mean_absolute_error: 1.9908
Epoch 406/1000
11/11 [==============================] - 1s 41ms/step - loss: 0.4112 - mean_absolute_error: 0.4112 - val_loss: 1.9612 - val_mean_absolute_error: 1.9612
Epoch 407/1000
11/11 [==============================] - 0s 24ms/step - loss: 0.3875 - mean_absolute_error: 0.3875 - val_loss: 1.9710 - val_mean_absolute_error: 1.9710
Epoch 408/1000
11/11 [==============================] - 0s 39ms/step - loss: 0.3836 - mean_absolute_error: 0.3836 - val_loss: 1.9982 - val_mean_absolute_error: 1.9982
Epoch 409/1000
11/11 [==============================] - 0s 41ms/step - loss: 0.6030 - mean_absolute_error: 0.6030 - val_loss: 1.9290 - val_mean_absolute_error: 1.9290
Epoch 410/1000
11/11 [==============================] - 0s 27ms/step - loss: 0.4280 - mean_absolute_error: 0.4280 - val_loss: 1.9247 - val_mean_absolute_error: 1.9247
Epoch 411/1000
11/11 [==============================] - 1s 52ms/step - loss: 0.4149 - mean_absolute_error: 0.4149 - val_loss: 1.8605 - val_mean_absolute_error: 1.8605
Epoch 412/1000
11/11 [==============================] - 0s 21ms/step - loss: 0.3785 - mean_absolute_error: 0.3785 - val_loss: 2.0041 - val_mean_absolute_error: 2.0041
Epoch 413/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4512 - mean_absolute_error: 0.4512 - val_loss: 1.8937 - val_mean_absolute_error: 1.8937
Epoch 414/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.4128 - mean_absolute_error: 0.4128 - val_loss: 1.8868 - val_mean_absolute_error: 1.8868
Epoch 415/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3966 - mean_absolute_error: 0.3966 - val_loss: 1.8193 - val_mean_absolute_error: 1.8193
Epoch 416/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4586 - mean_absolute_error: 0.4586 - val_loss: 1.9338 - val_mean_absolute_error: 1.9338
Epoch 417/1000

11/11 [==============================] - 0s 15ms/step - loss: 0.3637 - mean_absolute_error: 0.3637 - val_loss: 1.9185 - val_mean_absolute_error: 1.9185
Epoch 418/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4645 - mean_absolute_error: 0.4645 - val_loss: 1.8282 - val_mean_absolute_error: 1.8282
Epoch 419/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4262 - mean_absolute_error: 0.4262 - val_loss: 1.8850 - val_mean_absolute_error: 1.8850
Epoch 420/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4040 - mean_absolute_error: 0.4040 - val_loss: 1.9602 - val_mean_absolute_error: 1.9602
Epoch 421/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4158 - mean_absolute_error: 0.4158 - val_loss: 1.7989 - val_mean_absolute_error: 1.7989
Epoch 422/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4626 - mean_absolute_error: 0.4626 - val_loss: 1.9700 - val_mean_absolute_error: 1.9700
Epoch 423/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.4366 - mean_absolute_error: 0.4366 - val_loss: 1.9104 - val_mean_absolute_error: 1.9104
Epoch 424/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3730 - mean_absolute_error: 0.3730 - val_loss: 1.9334 - val_mean_absolute_error: 1.9334
Epoch 425/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4344 - mean_absolute_error: 0.4344 - val_loss: 2.0258 - val_mean_absolute_error: 2.0258
Epoch 426/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.5074 - mean_absolute_error: 0.5074 - val_loss: 1.8188 - val_mean_absolute_error: 1.8188
Epoch 427/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4512 - mean_absolute_error: 0.4512 - val_loss: 1.9028 - val_mean_absolute_error: 1.9028
Epoch 428/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3739 - mean_absolute_error: 0.3739 - val_loss: 1.9796 - val_mean_absolute_error: 1.9796
Epoch 429/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4237 - mean_absolute_error: 0.4237 - val_loss: 1.9175 - val_mean_absolute_error: 1.9175
Epoch 430/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3641 - mean_absolute_error: 0.3641 - val_loss: 1.8458 - val_mean_absolute_error: 1.8458
Epoch 431/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3476 - mean_absolute_error: 0.3476 - val_loss: 1.8320 - val_mean_absolute_error: 1.8320
Epoch 432/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3679 - mean_absolute_error: 0.3679 - val_loss: 1.9976 - val_mean_absolute_error: 1.9976
Epoch 433/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4295 - mean_absolute_error: 0.4295 - val_loss: 1.8015 - val_mean_absolute_error: 1.8015
Epoch 434/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4924 - mean_absolute_error: 0.4924 - val_loss: 1.9563 - val_mean_absolute_error: 1.9563
Epoch 435/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.4261 - mean_absolute_error: 0.4261 - val_loss: 1.9116 - val_mean_absolute_error: 1.9116
Epoch 436/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3742 - mean_absolute_error: 0.3742 - val_loss: 1.8623 - val_mean_absolute_error: 1.8623
Epoch 437/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3534 - mean_absolute_error: 0.3534 - val_loss: 1.8604 - val_mean_absolute_error: 1.8604
Epoch 438/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3204 - mean_absolute_error: 0.3204 - val_loss: 1.9179 - val_mean_absolute_error: 1.9179
Epoch 439/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3224 - mean_absolute_error: 0.3224 - val_loss: 1.8728 - val_mean_absolute_error: 1.8728
Epoch 440/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.3555 - mean_absolute_error: 0.3555 - val_loss: 1.8323 - val_mean_absolute_error: 1.8323
Epoch 441/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3864 - mean_absolute_error: 0.3864 - val_loss: 1.8984 - val_mean_absolute_error: 1.8984
Epoch 442/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3767 - mean_absolute_error: 0.3767 - val_loss: 1.9333 - val_mean_absolute_error: 1.9333
Epoch 443/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4014 - mean_absolute_error: 0.4014 - val_loss: 1.9014 - val_mean_absolute_error: 1.9014
Epoch 444/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3488 - mean_absolute_error: 0.3488 - val_loss: 1.8484 - val_mean_absolute_error: 1.8484
Epoch 445/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3075 - mean_absolute_error: 0.3075 - val_loss: 1.9992 - val_mean_absolute_error: 1.9992
Epoch 446/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4694 - mean_absolute_error: 0.4694 - val_loss: 1.8772 - val_mean_absolute_error: 1.8772
Epoch 447/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4907 - mean_absolute_error: 0.4907 - val_loss: 1.8812 - val_mean_absolute_error: 1.8812
Epoch 448/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3955 - mean_absolute_error: 0.3955 - val_loss: 1.8415 - val_mean_absolute_error: 1.8415
Epoch 449/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3635 - mean_absolute_error: 0.3635 - val_loss: 1.8087 - val_mean_absolute_error: 1.8087
Epoch 450/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3299 - mean_absolute_error: 0.3299 - val_loss: 1.9104 - val_mean_absolute_error: 1.9104
Epoch 451/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3577 - mean_absolute_error: 0.3577 - val_loss: 1.8210 - val_mean_absolute_error: 1.8210
Epoch 452/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3919 - mean_absolute_error: 0.3919 - val_loss: 1.8678 - val_mean_absolute_error: 1.8678
Epoch 453/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.3589 - mean_absolute_error: 0.3589 - val_loss: 1.9369 - val_mean_absolute_error: 1.9369
Epoch 454/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4051 - mean_absolute_error: 0.4051 - val_loss: 1.9878 - val_mean_absolute_error: 1.9878
Epoch 455/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4698 - mean_absolute_error: 0.4698 - val_loss: 1.8256 - val_mean_absolute_error: 1.8256
Epoch 456/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3483 - mean_absolute_error: 0.3483 - val_loss: 1.8808 - val_mean_absolute_error: 1.8808
Epoch 457/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3564 - mean_absolute_error: 0.3564 - val_loss: 1.8714 - val_mean_absolute_error: 1.8714
Epoch 458/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3229 - mean_absolute_error: 0.3229 - val_loss: 1.8683 - val_mean_absolute_error: 1.8683
Epoch 459/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.4013 - mean_absolute_error: 0.4013 - val_loss: 1.8849 - val_mean_absolute_error: 1.8849
Epoch 460/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4512 - mean_absolute_error: 0.4512 - val_loss: 1.8956 - val_mean_absolute_error: 1.8956
Epoch 461/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3897 - mean_absolute_error: 0.3897 - val_loss: 1.8589 - val_mean_absolute_error: 1.8589
Epoch 462/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3642 - mean_absolute_error: 0.3642 - val_loss: 1.8757 - val_mean_absolute_error: 1.8757
Epoch 463/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3562 - mean_absolute_error: 0.3562 - val_loss: 1.8383 - val_mean_absolute_error: 1.8383
Epoch 464/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3746 - mean_absolute_error: 0.3746 - val_loss: 1.8425 - val_mean_absolute_error: 1.8425
Epoch 465/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3979 - mean_absolute_error: 0.3979 - val_loss: 1.8900 - val_mean_absolute_error: 1.8900
Epoch 466/1000

11/11 [==============================] - 0s 15ms/step - loss: 0.3816 - mean_absolute_error: 0.3816 - val_loss: 1.8640 - val_mean_absolute_error: 1.8640
Epoch 467/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.4058 - mean_absolute_error: 0.4058 - val_loss: 1.8351 - val_mean_absolute_error: 1.8351
Epoch 468/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.4839 - mean_absolute_error: 0.4839 - val_loss: 1.9913 - val_mean_absolute_error: 1.9913
Epoch 469/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3848 - mean_absolute_error: 0.3848 - val_loss: 1.7999 - val_mean_absolute_error: 1.7999
Epoch 470/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4450 - mean_absolute_error: 0.4450 - val_loss: 1.9464 - val_mean_absolute_error: 1.9464
Epoch 471/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3689 - mean_absolute_error: 0.3689 - val_loss: 1.8162 - val_mean_absolute_error: 1.8162
Epoch 472/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3579 - mean_absolute_error: 0.3579 - val_loss: 1.8249 - val_mean_absolute_error: 1.8249
Epoch 473/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3703 - mean_absolute_error: 0.3703 - val_loss: 1.8680 - val_mean_absolute_error: 1.8680
Epoch 474/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4891 - mean_absolute_error: 0.4891 - val_loss: 1.8309 - val_mean_absolute_error: 1.8309
Epoch 475/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3827 - mean_absolute_error: 0.3827 - val_loss: 1.8058 - val_mean_absolute_error: 1.8058
Epoch 476/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3721 - mean_absolute_error: 0.3721 - val_loss: 1.8879 - val_mean_absolute_error: 1.8879
Epoch 477/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4125 - mean_absolute_error: 0.4125 - val_loss: 1.9697 - val_mean_absolute_error: 1.9697
Epoch 478/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3655 - mean_absolute_error: 0.3655 - val_loss: 1.8506 - val_mean_absolute_error: 1.8506
Epoch 479/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3797 - mean_absolute_error: 0.3797 - val_loss: 1.8099 - val_mean_absolute_error: 1.8099
Epoch 480/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.3505 - mean_absolute_error: 0.3505 - val_loss: 1.9447 - val_mean_absolute_error: 1.9447
Epoch 481/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4370 - mean_absolute_error: 0.4370 - val_loss: 1.8350 - val_mean_absolute_error: 1.8350
Epoch 482/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4768 - mean_absolute_error: 0.4768 - val_loss: 1.8127 - val_mean_absolute_error: 1.8127
Epoch 483/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4322 - mean_absolute_error: 0.4322 - val_loss: 1.9289 - val_mean_absolute_error: 1.9289
Epoch 484/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3809 - mean_absolute_error: 0.3809 - val_loss: 1.8960 - val_mean_absolute_error: 1.8960
Epoch 485/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3378 - mean_absolute_error: 0.3378 - val_loss: 1.8175 - val_mean_absolute_error: 1.8175
Epoch 486/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3437 - mean_absolute_error: 0.3437 - val_loss: 1.8585 - val_mean_absolute_error: 1.8585
Epoch 487/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3490 - mean_absolute_error: 0.3490 - val_loss: 1.8623 - val_mean_absolute_error: 1.8623
Epoch 488/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3611 - mean_absolute_error: 0.3611 - val_loss: 1.8046 - val_mean_absolute_error: 1.8046
Epoch 489/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4034 - mean_absolute_error: 0.4034 - val_loss: 2.0325 - val_mean_absolute_error: 2.0325
Epoch 490/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4413 - mean_absolute_error: 0.4413 - val_loss: 1.8491 - val_mean_absolute_error: 1.8491
Epoch 491/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.3288 - mean_absolute_error: 0.3288 - val_loss: 1.8845 - val_mean_absolute_error: 1.8845
Epoch 492/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2942 - mean_absolute_error: 0.2942 - val_loss: 1.8177 - val_mean_absolute_error: 1.8177
Epoch 493/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3392 - mean_absolute_error: 0.3392 - val_loss: 1.8817 - val_mean_absolute_error: 1.8817
Epoch 494/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.3398 - mean_absolute_error: 0.3398 - val_loss: 1.8761 - val_mean_absolute_error: 1.8761
Epoch 495/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3404 - mean_absolute_error: 0.3404 - val_loss: 1.9101 - val_mean_absolute_error: 1.9101
Epoch 496/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3617 - mean_absolute_error: 0.3617 - val_loss: 1.8176 - val_mean_absolute_error: 1.8176
Epoch 497/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.3923 - mean_absolute_error: 0.3923 - val_loss: 1.8625 - val_mean_absolute_error: 1.8625
Epoch 498/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.4843 - mean_absolute_error: 0.4843 - val_loss: 1.8386 - val_mean_absolute_error: 1.8386
Epoch 499/1000
11/11 [==============================] - 0s 34ms/step - loss: 0.4514 - mean_absolute_error: 0.4514 - val_loss: 1.9293 - val_mean_absolute_error: 1.9293
Epoch 500/1000
11/11 [==============================] - 0s 35ms/step - loss: 0.3767 - mean_absolute_error: 0.3767 - val_loss: 1.8225 - val_mean_absolute_error: 1.8225
Epoch 501/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3948 - mean_absolute_error: 0.3948 - val_loss: 1.9946 - val_mean_absolute_error: 1.9946
Epoch 502/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.5056 - mean_absolute_error: 0.5056 - val_loss: 1.8799 - val_mean_absolute_error: 1.8799
Epoch 503/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.4490 - mean_absolute_error: 0.4490 - val_loss: 1.8196 - val_mean_absolute_error: 1.8196
Epoch 504/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4641 - mean_absolute_error: 0.4641 - val_loss: 1.8919 - val_mean_absolute_error: 1.8919
Epoch 505/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3662 - mean_absolute_error: 0.3662 - val_loss: 1.8217 - val_mean_absolute_error: 1.8217
Epoch 506/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3121 - mean_absolute_error: 0.3121 - val_loss: 1.8234 - val_mean_absolute_error: 1.8234
Epoch 507/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3374 - mean_absolute_error: 0.3374 - val_loss: 1.8166 - val_mean_absolute_error: 1.8166
Epoch 508/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3238 - mean_absolute_error: 0.3238 - val_loss: 1.8503 - val_mean_absolute_error: 1.8503
Epoch 509/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3564 - mean_absolute_error: 0.3564 - val_loss: 1.9186 - val_mean_absolute_error: 1.9186
Epoch 510/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3773 - mean_absolute_error: 0.3773 - val_loss: 1.8654 - val_mean_absolute_error: 1.8654
Epoch 511/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3085 - mean_absolute_error: 0.3085 - val_loss: 1.8489 - val_mean_absolute_error: 1.8489
Epoch 512/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3071 - mean_absolute_error: 0.3071 - val_loss: 1.8064 - val_mean_absolute_error: 1.8064
Epoch 513/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3354 - mean_absolute_error: 0.3354 - val_loss: 1.8393 - val_mean_absolute_error: 1.8393
Epoch 514/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3155 - mean_absolute_error: 0.3155 - val_loss: 1.8157 - val_mean_absolute_error: 1.8157
Epoch 515/1000

11/11 [==============================] - 0s 15ms/step - loss: 0.3564 - mean_absolute_error: 0.3564 - val_loss: 1.8353 - val_mean_absolute_error: 1.8353
Epoch 516/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4453 - mean_absolute_error: 0.4453 - val_loss: 1.8779 - val_mean_absolute_error: 1.8779
Epoch 517/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3636 - mean_absolute_error: 0.3636 - val_loss: 1.9537 - val_mean_absolute_error: 1.9537
Epoch 518/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3816 - mean_absolute_error: 0.3816 - val_loss: 1.8380 - val_mean_absolute_error: 1.8380
Epoch 519/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3245 - mean_absolute_error: 0.3245 - val_loss: 1.8063 - val_mean_absolute_error: 1.8063
Epoch 520/1000
11/11 [==============================] - 0s 21ms/step - loss: 0.3282 - mean_absolute_error: 0.3282 - val_loss: 1.8660 - val_mean_absolute_error: 1.8660
Epoch 521/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3145 - mean_absolute_error: 0.3145 - val_loss: 1.8192 - val_mean_absolute_error: 1.8192
Epoch 522/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3031 - mean_absolute_error: 0.3031 - val_loss: 1.8328 - val_mean_absolute_error: 1.8328
Epoch 523/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3874 - mean_absolute_error: 0.3874 - val_loss: 1.8280 - val_mean_absolute_error: 1.8280
Epoch 524/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4367 - mean_absolute_error: 0.4367 - val_loss: 1.8993 - val_mean_absolute_error: 1.8993
Epoch 525/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3305 - mean_absolute_error: 0.3305 - val_loss: 1.8453 - val_mean_absolute_error: 1.8453
Epoch 526/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3480 - mean_absolute_error: 0.3480 - val_loss: 1.8772 - val_mean_absolute_error: 1.8772
Epoch 527/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3259 - mean_absolute_error: 0.3259 - val_loss: 1.9092 - val_mean_absolute_error: 1.9092
Epoch 528/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2864 - mean_absolute_error: 0.2864 - val_loss: 1.8164 - val_mean_absolute_error: 1.8164
Epoch 529/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3292 - mean_absolute_error: 0.3292 - val_loss: 1.8041 - val_mean_absolute_error: 1.8041
Epoch 530/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4060 - mean_absolute_error: 0.4060 - val_loss: 1.8718 - val_mean_absolute_error: 1.8718
Epoch 531/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3264 - mean_absolute_error: 0.3264 - val_loss: 1.8735 - val_mean_absolute_error: 1.8735
Epoch 532/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3502 - mean_absolute_error: 0.3502 - val_loss: 1.8290 - val_mean_absolute_error: 1.8290
Epoch 533/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3117 - mean_absolute_error: 0.3117 - val_loss: 1.8210 - val_mean_absolute_error: 1.8210
Epoch 534/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3417 - mean_absolute_error: 0.3417 - val_loss: 1.8203 - val_mean_absolute_error: 1.8203
Epoch 535/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.3585 - mean_absolute_error: 0.3585 - val_loss: 1.8012 - val_mean_absolute_error: 1.8012
Epoch 536/1000
11/11 [==============================] - 0s 14ms/step - loss: 0.3789 - mean_absolute_error: 0.3789 - val_loss: 1.9358 - val_mean_absolute_error: 1.9358
Epoch 537/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4501 - mean_absolute_error: 0.4501 - val_loss: 1.8250 - val_mean_absolute_error: 1.8250
Epoch 538/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3386 - mean_absolute_error: 0.3386 - val_loss: 1.8760 - val_mean_absolute_error: 1.8760
Epoch 539/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.3724 - mean_absolute_error: 0.3724 - val_loss: 1.9630 - val_mean_absolute_error: 1.9630
Epoch 540/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.4313 - mean_absolute_error: 0.4313 - val_loss: 1.8015 - val_mean_absolute_error: 1.8015
Epoch 541/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3830 - mean_absolute_error: 0.3830 - val_loss: 1.8655 - val_mean_absolute_error: 1.8655
Epoch 542/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3246 - mean_absolute_error: 0.3246 - val_loss: 1.8482 - val_mean_absolute_error: 1.8482
Epoch 543/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3045 - mean_absolute_error: 0.3045 - val_loss: 1.9126 - val_mean_absolute_error: 1.9126
Epoch 544/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3410 - mean_absolute_error: 0.3410 - val_loss: 1.8795 - val_mean_absolute_error: 1.8795
Epoch 545/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3987 - mean_absolute_error: 0.3987 - val_loss: 1.8256 - val_mean_absolute_error: 1.8256
Epoch 546/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4014 - mean_absolute_error: 0.4014 - val_loss: 1.9754 - val_mean_absolute_error: 1.9754
Epoch 547/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3847 - mean_absolute_error: 0.3847 - val_loss: 1.8130 - val_mean_absolute_error: 1.8130
Epoch 548/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4287 - mean_absolute_error: 0.4287 - val_loss: 1.9872 - val_mean_absolute_error: 1.9872
Epoch 549/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3682 - mean_absolute_error: 0.3682 - val_loss: 1.8424 - val_mean_absolute_error: 1.8424
Epoch 550/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.3024 - mean_absolute_error: 0.3024 - val_loss: 1.8575 - val_mean_absolute_error: 1.8575
Epoch 551/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3536 - mean_absolute_error: 0.3536 - val_loss: 1.9462 - val_mean_absolute_error: 1.9462
Epoch 552/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4163 - mean_absolute_error: 0.4163 - val_loss: 1.7976 - val_mean_absolute_error: 1.7976
Epoch 553/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3091 - mean_absolute_error: 0.3091 - val_loss: 1.8397 - val_mean_absolute_error: 1.8397
Epoch 554/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3039 - mean_absolute_error: 0.3039 - val_loss: 1.8892 - val_mean_absolute_error: 1.8892
Epoch 555/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.3005 - mean_absolute_error: 0.3005 - val_loss: 1.8370 - val_mean_absolute_error: 1.8370
Epoch 556/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3093 - mean_absolute_error: 0.3093 - val_loss: 1.8935 - val_mean_absolute_error: 1.8935
Epoch 557/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3201 - mean_absolute_error: 0.3201 - val_loss: 1.9034 - val_mean_absolute_error: 1.9034
Epoch 558/1000
11/11 [==============================] - 0s 27ms/step - loss: 0.3120 - mean_absolute_error: 0.3120 - val_loss: 1.8901 - val_mean_absolute_error: 1.8901
Epoch 559/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3302 - mean_absolute_error: 0.3302 - val_loss: 1.8880 - val_mean_absolute_error: 1.8880
Epoch 560/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.3174 - mean_absolute_error: 0.3174 - val_loss: 1.8198 - val_mean_absolute_error: 1.8198
Epoch 561/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3262 - mean_absolute_error: 0.3262 - val_loss: 1.8315 - val_mean_absolute_error: 1.8315
Epoch 562/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3776 - mean_absolute_error: 0.3776 - val_loss: 1.8914 - val_mean_absolute_error: 1.8914
Epoch 563/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.3637 - mean_absolute_error: 0.3637 - val_loss: 1.8768 - val_mean_absolute_error: 1.8768
Epoch 564/1000

11/11 [==============================] - 0s 16ms/step - loss: 0.3923 - mean_absolute_error: 0.3923 - val_loss: 1.8367 - val_mean_absolute_error: 1.8367
Epoch 565/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3444 - mean_absolute_error: 0.3444 - val_loss: 1.9905 - val_mean_absolute_error: 1.9905
Epoch 566/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4384 - mean_absolute_error: 0.4384 - val_loss: 1.8439 - val_mean_absolute_error: 1.8439
Epoch 567/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3551 - mean_absolute_error: 0.3551 - val_loss: 1.9043 - val_mean_absolute_error: 1.9043
Epoch 568/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3125 - mean_absolute_error: 0.3125 - val_loss: 1.8573 - val_mean_absolute_error: 1.8573
Epoch 569/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3680 - mean_absolute_error: 0.3680 - val_loss: 1.8109 - val_mean_absolute_error: 1.8109
Epoch 570/1000
11/11 [==============================] - 0s 24ms/step - loss: 0.4092 - mean_absolute_error: 0.4092 - val_loss: 1.9109 - val_mean_absolute_error: 1.9109
Epoch 571/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.3507 - mean_absolute_error: 0.3507 - val_loss: 1.8200 - val_mean_absolute_error: 1.8200
Epoch 572/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3809 - mean_absolute_error: 0.3809 - val_loss: 1.9100 - val_mean_absolute_error: 1.9100
Epoch 573/1000
11/11 [==============================] - 0s 21ms/step - loss: 0.3145 - mean_absolute_error: 0.3145 - val_loss: 1.8595 - val_mean_absolute_error: 1.8595
Epoch 574/1000
11/11 [==============================] - 0s 36ms/step - loss: 0.3083 - mean_absolute_error: 0.3083 - val_loss: 1.8737 - val_mean_absolute_error: 1.8737
Epoch 575/1000
11/11 [==============================] - 0s 26ms/step - loss: 0.3349 - mean_absolute_error: 0.3349 - val_loss: 1.8080 - val_mean_absolute_error: 1.8080
Epoch 576/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4152 - mean_absolute_error: 0.4152 - val_loss: 1.9135 - val_mean_absolute_error: 1.9135
Epoch 577/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.4258 - mean_absolute_error: 0.4258 - val_loss: 1.9227 - val_mean_absolute_error: 1.9227
Epoch 578/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.3802 - mean_absolute_error: 0.3802 - val_loss: 1.8921 - val_mean_absolute_error: 1.8921
Epoch 579/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.3670 - mean_absolute_error: 0.3670 - val_loss: 1.8441 - val_mean_absolute_error: 1.8441
Epoch 580/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3111 - mean_absolute_error: 0.3111 - val_loss: 1.9105 - val_mean_absolute_error: 1.9105
Epoch 581/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.4187 - mean_absolute_error: 0.4187 - val_loss: 1.8963 - val_mean_absolute_error: 1.8963
Epoch 582/1000
11/11 [==============================] - 0s 32ms/step - loss: 0.4253 - mean_absolute_error: 0.4253 - val_loss: 1.8413 - val_mean_absolute_error: 1.8413
Epoch 583/1000
11/11 [==============================] - 0s 28ms/step - loss: 0.2879 - mean_absolute_error: 0.2879 - val_loss: 1.8743 - val_mean_absolute_error: 1.8743
Epoch 584/1000
11/11 [==============================] - 0s 21ms/step - loss: 0.2865 - mean_absolute_error: 0.2865 - val_loss: 1.8893 - val_mean_absolute_error: 1.8893
Epoch 585/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4189 - mean_absolute_error: 0.4189 - val_loss: 1.8359 - val_mean_absolute_error: 1.8359
Epoch 586/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3765 - mean_absolute_error: 0.3765 - val_loss: 1.8825 - val_mean_absolute_error: 1.8825
Epoch 587/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3124 - mean_absolute_error: 0.3124 - val_loss: 1.8467 - val_mean_absolute_error: 1.8467
Epoch 588/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3056 - mean_absolute_error: 0.3056 - val_loss: 1.8364 - val_mean_absolute_error: 1.8364
Epoch 589/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3888 - mean_absolute_error: 0.3888 - val_loss: 1.9584 - val_mean_absolute_error: 1.9584
Epoch 590/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4244 - mean_absolute_error: 0.4244 - val_loss: 1.9097 - val_mean_absolute_error: 1.9097
Epoch 591/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.4631 - mean_absolute_error: 0.4631 - val_loss: 1.8464 - val_mean_absolute_error: 1.8464
Epoch 592/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.4092 - mean_absolute_error: 0.4092 - val_loss: 1.9048 - val_mean_absolute_error: 1.9048
Epoch 593/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3238 - mean_absolute_error: 0.3238 - val_loss: 1.8073 - val_mean_absolute_error: 1.8073
Epoch 594/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.4087 - mean_absolute_error: 0.4087 - val_loss: 1.9084 - val_mean_absolute_error: 1.9084
Epoch 595/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4332 - mean_absolute_error: 0.4332 - val_loss: 1.8541 - val_mean_absolute_error: 1.8541
Epoch 596/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3368 - mean_absolute_error: 0.3368 - val_loss: 1.8602 - val_mean_absolute_error: 1.8602
Epoch 597/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3000 - mean_absolute_error: 0.3000 - val_loss: 1.8430 - val_mean_absolute_error: 1.8430
Epoch 598/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2650 - mean_absolute_error: 0.2650 - val_loss: 1.8585 - val_mean_absolute_error: 1.8585
Epoch 599/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2831 - mean_absolute_error: 0.2831 - val_loss: 1.8261 - val_mean_absolute_error: 1.8261
Epoch 600/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3261 - mean_absolute_error: 0.3261 - val_loss: 2.0280 - val_mean_absolute_error: 2.0280
Epoch 601/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.4977 - mean_absolute_error: 0.4977 - val_loss: 1.8805 - val_mean_absolute_error: 1.8805
Epoch 602/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3467 - mean_absolute_error: 0.3467 - val_loss: 1.8674 - val_mean_absolute_error: 1.8674
Epoch 603/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3099 - mean_absolute_error: 0.3099 - val_loss: 1.8270 - val_mean_absolute_error: 1.8270
Epoch 604/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2790 - mean_absolute_error: 0.2790 - val_loss: 1.8597 - val_mean_absolute_error: 1.8597
Epoch 605/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.3105 - mean_absolute_error: 0.3105 - val_loss: 1.9359 - val_mean_absolute_error: 1.9359
Epoch 606/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3253 - mean_absolute_error: 0.3253 - val_loss: 1.8408 - val_mean_absolute_error: 1.8408
Epoch 607/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3052 - mean_absolute_error: 0.3052 - val_loss: 1.8455 - val_mean_absolute_error: 1.8455
Epoch 608/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2858 - mean_absolute_error: 0.2858 - val_loss: 1.8423 - val_mean_absolute_error: 1.8423
Epoch 609/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2754 - mean_absolute_error: 0.2754 - val_loss: 1.8326 - val_mean_absolute_error: 1.8326
Epoch 610/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2980 - mean_absolute_error: 0.2980 - val_loss: 1.8954 - val_mean_absolute_error: 1.8954
Epoch 611/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2830 - mean_absolute_error: 0.2830 - val_loss: 1.8589 - val_mean_absolute_error: 1.8589
Epoch 612/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2962 - mean_absolute_error: 0.2962 - val_loss: 1.9185 - val_mean_absolute_error: 1.9185
Epoch 613/1000

11/11 [==============================] - 0s 20ms/step - loss: 0.2854 - mean_absolute_error: 0.2854 - val_loss: 1.8882 - val_mean_absolute_error: 1.8882
Epoch 614/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2718 - mean_absolute_error: 0.2718 - val_loss: 1.8881 - val_mean_absolute_error: 1.8881
Epoch 615/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4419 - mean_absolute_error: 0.4419 - val_loss: 1.8543 - val_mean_absolute_error: 1.8543
Epoch 616/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4503 - mean_absolute_error: 0.4503 - val_loss: 1.8599 - val_mean_absolute_error: 1.8599
Epoch 617/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3700 - mean_absolute_error: 0.3700 - val_loss: 1.7994 - val_mean_absolute_error: 1.7994
Epoch 618/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3260 - mean_absolute_error: 0.3260 - val_loss: 1.9313 - val_mean_absolute_error: 1.9313
Epoch 619/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3622 - mean_absolute_error: 0.3622 - val_loss: 1.8480 - val_mean_absolute_error: 1.8480
Epoch 620/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3564 - mean_absolute_error: 0.3564 - val_loss: 1.8594 - val_mean_absolute_error: 1.8594
Epoch 621/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3048 - mean_absolute_error: 0.3048 - val_loss: 1.8828 - val_mean_absolute_error: 1.8828
Epoch 622/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.3530 - mean_absolute_error: 0.3530 - val_loss: 1.9016 - val_mean_absolute_error: 1.9016
Epoch 623/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3225 - mean_absolute_error: 0.3225 - val_loss: 1.9228 - val_mean_absolute_error: 1.9228
Epoch 624/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2962 - mean_absolute_error: 0.2962 - val_loss: 1.8513 - val_mean_absolute_error: 1.8513
Epoch 625/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3348 - mean_absolute_error: 0.3348 - val_loss: 1.8618 - val_mean_absolute_error: 1.8618
Epoch 626/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.3249 - mean_absolute_error: 0.3249 - val_loss: 1.8919 - val_mean_absolute_error: 1.8919
Epoch 627/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3484 - mean_absolute_error: 0.3484 - val_loss: 1.8715 - val_mean_absolute_error: 1.8715
Epoch 628/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3884 - mean_absolute_error: 0.3884 - val_loss: 2.0233 - val_mean_absolute_error: 2.0233
Epoch 629/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.5069 - mean_absolute_error: 0.5069 - val_loss: 1.8908 - val_mean_absolute_error: 1.8908
Epoch 630/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3907 - mean_absolute_error: 0.3907 - val_loss: 1.8275 - val_mean_absolute_error: 1.8275
Epoch 631/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3092 - mean_absolute_error: 0.3092 - val_loss: 1.8221 - val_mean_absolute_error: 1.8221
Epoch 632/1000
11/11 [==============================] - 0s 33ms/step - loss: 0.3579 - mean_absolute_error: 0.3579 - val_loss: 1.8511 - val_mean_absolute_error: 1.8511
Epoch 633/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3137 - mean_absolute_error: 0.3137 - val_loss: 1.8786 - val_mean_absolute_error: 1.8786
Epoch 634/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2839 - mean_absolute_error: 0.2839 - val_loss: 1.8570 - val_mean_absolute_error: 1.8570
Epoch 635/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2847 - mean_absolute_error: 0.2847 - val_loss: 1.9133 - val_mean_absolute_error: 1.9133
Epoch 636/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3397 - mean_absolute_error: 0.3397 - val_loss: 1.8404 - val_mean_absolute_error: 1.8404
Epoch 637/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2995 - mean_absolute_error: 0.2995 - val_loss: 1.8730 - val_mean_absolute_error: 1.8730
Epoch 638/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3148 - mean_absolute_error: 0.3148 - val_loss: 1.8571 - val_mean_absolute_error: 1.8571
Epoch 639/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3714 - mean_absolute_error: 0.3714 - val_loss: 1.9731 - val_mean_absolute_error: 1.9731
Epoch 640/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.4048 - mean_absolute_error: 0.4048 - val_loss: 1.8819 - val_mean_absolute_error: 1.8819
Epoch 641/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3453 - mean_absolute_error: 0.3453 - val_loss: 1.8301 - val_mean_absolute_error: 1.8301
Epoch 642/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3032 - mean_absolute_error: 0.3032 - val_loss: 1.8632 - val_mean_absolute_error: 1.8632
Epoch 643/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2897 - mean_absolute_error: 0.2897 - val_loss: 1.8192 - val_mean_absolute_error: 1.8192
Epoch 644/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3003 - mean_absolute_error: 0.3003 - val_loss: 1.8122 - val_mean_absolute_error: 1.8122
Epoch 645/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2930 - mean_absolute_error: 0.2930 - val_loss: 1.9201 - val_mean_absolute_error: 1.9201
Epoch 646/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3331 - mean_absolute_error: 0.3331 - val_loss: 1.8616 - val_mean_absolute_error: 1.8616
Epoch 647/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2847 - mean_absolute_error: 0.2847 - val_loss: 1.8566 - val_mean_absolute_error: 1.8566
Epoch 648/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3147 - mean_absolute_error: 0.3147 - val_loss: 1.7918 - val_mean_absolute_error: 1.7918
Epoch 649/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3117 - mean_absolute_error: 0.3117 - val_loss: 1.8654 - val_mean_absolute_error: 1.8654
Epoch 650/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2797 - mean_absolute_error: 0.2797 - val_loss: 1.8593 - val_mean_absolute_error: 1.8593
Epoch 651/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2987 - mean_absolute_error: 0.2987 - val_loss: 1.9152 - val_mean_absolute_error: 1.9152
Epoch 652/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3827 - mean_absolute_error: 0.3827 - val_loss: 1.8083 - val_mean_absolute_error: 1.8083
Epoch 653/1000
11/11 [==============================] - 0s 27ms/step - loss: 0.3136 - mean_absolute_error: 0.3136 - val_loss: 1.9300 - val_mean_absolute_error: 1.9300
Epoch 654/1000
11/11 [==============================] - 0s 29ms/step - loss: 0.3254 - mean_absolute_error: 0.3254 - val_loss: 1.8689 - val_mean_absolute_error: 1.8689
Epoch 655/1000
11/11 [==============================] - 0s 29ms/step - loss: 0.2811 - mean_absolute_error: 0.2811 - val_loss: 1.8995 - val_mean_absolute_error: 1.8995
Epoch 656/1000
11/11 [==============================] - 0s 41ms/step - loss: 0.3046 - mean_absolute_error: 0.3046 - val_loss: 1.8758 - val_mean_absolute_error: 1.8758
Epoch 657/1000
11/11 [==============================] - 1s 56ms/step - loss: 0.3287 - mean_absolute_error: 0.3287 - val_loss: 1.8582 - val_mean_absolute_error: 1.8582
Epoch 658/1000
11/11 [==============================] - 0s 36ms/step - loss: 0.3459 - mean_absolute_error: 0.3459 - val_loss: 1.8700 - val_mean_absolute_error: 1.8700
Epoch 659/1000
11/11 [==============================] - 0s 34ms/step - loss: 0.3036 - mean_absolute_error: 0.3036 - val_loss: 1.8546 - val_mean_absolute_error: 1.8546
Epoch 660/1000
11/11 [==============================] - 0s 35ms/step - loss: 0.2710 - mean_absolute_error: 0.2710 - val_loss: 1.8475 - val_mean_absolute_error: 1.8475
Epoch 661/1000
11/11 [==============================] - 0s 35ms/step - loss: 0.2549 - mean_absolute_error: 0.2549 - val_loss: 1.8710 - val_mean_absolute_error: 1.8710
Epoch 662/1000

11/11 [==============================] - 0s 46ms/step - loss: 0.2747 - mean_absolute_error: 0.2747 - val_loss: 1.8293 - val_mean_absolute_error: 1.8293
Epoch 663/1000
11/11 [==============================] - 0s 41ms/step - loss: 0.2718 - mean_absolute_error: 0.2718 - val_loss: 1.8527 - val_mean_absolute_error: 1.8527
Epoch 664/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3822 - mean_absolute_error: 0.3822 - val_loss: 1.9025 - val_mean_absolute_error: 1.9025
Epoch 665/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2844 - mean_absolute_error: 0.2844 - val_loss: 1.8365 - val_mean_absolute_error: 1.8365
Epoch 666/1000
11/11 [==============================] - 0s 36ms/step - loss: 0.3057 - mean_absolute_error: 0.3057 - val_loss: 1.8271 - val_mean_absolute_error: 1.8271
Epoch 667/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.3100 - mean_absolute_error: 0.3100 - val_loss: 1.8953 - val_mean_absolute_error: 1.8953
Epoch 668/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2898 - mean_absolute_error: 0.2898 - val_loss: 1.8408 - val_mean_absolute_error: 1.8408
Epoch 669/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3145 - mean_absolute_error: 0.3145 - val_loss: 1.8397 - val_mean_absolute_error: 1.8397
Epoch 670/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3464 - mean_absolute_error: 0.3464 - val_loss: 1.9047 - val_mean_absolute_error: 1.9047
Epoch 671/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3619 - mean_absolute_error: 0.3619 - val_loss: 1.8199 - val_mean_absolute_error: 1.8199
Epoch 672/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3735 - mean_absolute_error: 0.3735 - val_loss: 1.8794 - val_mean_absolute_error: 1.8794
Epoch 673/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3234 - mean_absolute_error: 0.3234 - val_loss: 1.9523 - val_mean_absolute_error: 1.9523
Epoch 674/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3551 - mean_absolute_error: 0.3551 - val_loss: 1.8811 - val_mean_absolute_error: 1.8811
Epoch 675/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2889 - mean_absolute_error: 0.2889 - val_loss: 1.8590 - val_mean_absolute_error: 1.8590
Epoch 676/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3008 - mean_absolute_error: 0.3008 - val_loss: 1.8580 - val_mean_absolute_error: 1.8580
Epoch 677/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2723 - mean_absolute_error: 0.2723 - val_loss: 1.8284 - val_mean_absolute_error: 1.8284
Epoch 678/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3327 - mean_absolute_error: 0.3327 - val_loss: 1.9575 - val_mean_absolute_error: 1.9575
Epoch 679/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3907 - mean_absolute_error: 0.3907 - val_loss: 1.8612 - val_mean_absolute_error: 1.8612
Epoch 680/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3115 - mean_absolute_error: 0.3115 - val_loss: 1.8399 - val_mean_absolute_error: 1.8399
Epoch 681/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3209 - mean_absolute_error: 0.3209 - val_loss: 1.8582 - val_mean_absolute_error: 1.8582
Epoch 682/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3143 - mean_absolute_error: 0.3143 - val_loss: 1.8896 - val_mean_absolute_error: 1.8896
Epoch 683/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2606 - mean_absolute_error: 0.2606 - val_loss: 1.7999 - val_mean_absolute_error: 1.7999
Epoch 684/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3346 - mean_absolute_error: 0.3346 - val_loss: 1.8815 - val_mean_absolute_error: 1.8815
Epoch 685/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2842 - mean_absolute_error: 0.2842 - val_loss: 1.8669 - val_mean_absolute_error: 1.8669
Epoch 686/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2651 - mean_absolute_error: 0.2651 - val_loss: 1.8373 - val_mean_absolute_error: 1.8373
Epoch 687/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3118 - mean_absolute_error: 0.3118 - val_loss: 1.8563 - val_mean_absolute_error: 1.8563
Epoch 688/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3929 - mean_absolute_error: 0.3929 - val_loss: 1.9046 - val_mean_absolute_error: 1.9046
Epoch 689/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3983 - mean_absolute_error: 0.3983 - val_loss: 1.8353 - val_mean_absolute_error: 1.8353
Epoch 690/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3332 - mean_absolute_error: 0.3332 - val_loss: 1.8501 - val_mean_absolute_error: 1.8501
Epoch 691/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3189 - mean_absolute_error: 0.3189 - val_loss: 1.8043 - val_mean_absolute_error: 1.8043
Epoch 692/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2906 - mean_absolute_error: 0.2906 - val_loss: 1.8331 - val_mean_absolute_error: 1.8331
Epoch 693/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2661 - mean_absolute_error: 0.2661 - val_loss: 1.8465 - val_mean_absolute_error: 1.8465
Epoch 694/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2607 - mean_absolute_error: 0.2607 - val_loss: 1.8531 - val_mean_absolute_error: 1.8531
Epoch 695/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2863 - mean_absolute_error: 0.2863 - val_loss: 1.9005 - val_mean_absolute_error: 1.9005
Epoch 696/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2864 - mean_absolute_error: 0.2864 - val_loss: 1.8808 - val_mean_absolute_error: 1.8808
Epoch 697/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2728 - mean_absolute_error: 0.2728 - val_loss: 1.8974 - val_mean_absolute_error: 1.8974
Epoch 698/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2743 - mean_absolute_error: 0.2743 - val_loss: 1.8908 - val_mean_absolute_error: 1.8908
Epoch 699/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3311 - mean_absolute_error: 0.3311 - val_loss: 1.8332 - val_mean_absolute_error: 1.8332
Epoch 700/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2798 - mean_absolute_error: 0.2798 - val_loss: 1.8182 - val_mean_absolute_error: 1.8182
Epoch 701/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3634 - mean_absolute_error: 0.3634 - val_loss: 1.8704 - val_mean_absolute_error: 1.8704
Epoch 702/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3289 - mean_absolute_error: 0.3289 - val_loss: 1.9697 - val_mean_absolute_error: 1.9697
Epoch 703/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3961 - mean_absolute_error: 0.3961 - val_loss: 1.8675 - val_mean_absolute_error: 1.8675
Epoch 704/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3685 - mean_absolute_error: 0.3685 - val_loss: 1.8640 - val_mean_absolute_error: 1.8640
Epoch 705/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3567 - mean_absolute_error: 0.3567 - val_loss: 1.8078 - val_mean_absolute_error: 1.8078
Epoch 706/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4051 - mean_absolute_error: 0.4051 - val_loss: 1.9024 - val_mean_absolute_error: 1.9024
Epoch 707/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3093 - mean_absolute_error: 0.3093 - val_loss: 1.8185 - val_mean_absolute_error: 1.8185
Epoch 708/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2915 - mean_absolute_error: 0.2915 - val_loss: 1.8467 - val_mean_absolute_error: 1.8467
Epoch 709/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2803 - mean_absolute_error: 0.2803 - val_loss: 1.9033 - val_mean_absolute_error: 1.9033
Epoch 710/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3164 - mean_absolute_error: 0.3164 - val_loss: 1.8508 - val_mean_absolute_error: 1.8508
Epoch 711/1000

11/11 [==============================] - 0s 16ms/step - loss: 0.2826 - mean_absolute_error: 0.2826 - val_loss: 1.8517 - val_mean_absolute_error: 1.8517
Epoch 712/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2712 - mean_absolute_error: 0.2712 - val_loss: 1.8743 - val_mean_absolute_error: 1.8743
Epoch 713/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2695 - mean_absolute_error: 0.2695 - val_loss: 1.8621 - val_mean_absolute_error: 1.8621
Epoch 714/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2762 - mean_absolute_error: 0.2762 - val_loss: 1.8587 - val_mean_absolute_error: 1.8587
Epoch 715/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2536 - mean_absolute_error: 0.2536 - val_loss: 1.8350 - val_mean_absolute_error: 1.8350
Epoch 716/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2911 - mean_absolute_error: 0.2911 - val_loss: 1.8846 - val_mean_absolute_error: 1.8846
Epoch 717/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3351 - mean_absolute_error: 0.3351 - val_loss: 1.9449 - val_mean_absolute_error: 1.9449
Epoch 718/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3868 - mean_absolute_error: 0.3868 - val_loss: 1.8591 - val_mean_absolute_error: 1.8591
Epoch 719/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3022 - mean_absolute_error: 0.3022 - val_loss: 1.8159 - val_mean_absolute_error: 1.8159
Epoch 720/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3519 - mean_absolute_error: 0.3519 - val_loss: 1.8739 - val_mean_absolute_error: 1.8739
Epoch 721/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2903 - mean_absolute_error: 0.2903 - val_loss: 1.8118 - val_mean_absolute_error: 1.8118
Epoch 722/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2704 - mean_absolute_error: 0.2704 - val_loss: 1.8684 - val_mean_absolute_error: 1.8684
Epoch 723/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.2655 - mean_absolute_error: 0.2655 - val_loss: 1.8553 - val_mean_absolute_error: 1.8553
Epoch 724/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3115 - mean_absolute_error: 0.3115 - val_loss: 1.8682 - val_mean_absolute_error: 1.8682
Epoch 725/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2882 - mean_absolute_error: 0.2882 - val_loss: 1.9351 - val_mean_absolute_error: 1.9351
Epoch 726/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4287 - mean_absolute_error: 0.4287 - val_loss: 2.0280 - val_mean_absolute_error: 2.0280
Epoch 727/1000
11/11 [==============================] - 0s 25ms/step - loss: 0.4069 - mean_absolute_error: 0.4069 - val_loss: 1.8528 - val_mean_absolute_error: 1.8528
Epoch 728/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3599 - mean_absolute_error: 0.3599 - val_loss: 1.8726 - val_mean_absolute_error: 1.8726
Epoch 729/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3314 - mean_absolute_error: 0.3314 - val_loss: 1.8693 - val_mean_absolute_error: 1.8693
Epoch 730/1000
11/11 [==============================] - 0s 25ms/step - loss: 0.3658 - mean_absolute_error: 0.3658 - val_loss: 1.9070 - val_mean_absolute_error: 1.9070
Epoch 731/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.3603 - mean_absolute_error: 0.3603 - val_loss: 1.8463 - val_mean_absolute_error: 1.8463
Epoch 732/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3079 - mean_absolute_error: 0.3079 - val_loss: 1.8787 - val_mean_absolute_error: 1.8787
Epoch 733/1000
11/11 [==============================] - 0s 25ms/step - loss: 0.2731 - mean_absolute_error: 0.2731 - val_loss: 1.8811 - val_mean_absolute_error: 1.8811
Epoch 734/1000
11/11 [==============================] - 0s 40ms/step - loss: 0.3552 - mean_absolute_error: 0.3552 - val_loss: 1.9037 - val_mean_absolute_error: 1.9037
Epoch 735/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.2889 - mean_absolute_error: 0.2889 - val_loss: 1.7996 - val_mean_absolute_error: 1.7996
Epoch 736/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3263 - mean_absolute_error: 0.3263 - val_loss: 1.9165 - val_mean_absolute_error: 1.9165
Epoch 737/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.3766 - mean_absolute_error: 0.3766 - val_loss: 1.8556 - val_mean_absolute_error: 1.8556
Epoch 738/1000
11/11 [==============================] - 0s 25ms/step - loss: 0.2646 - mean_absolute_error: 0.2646 - val_loss: 1.8118 - val_mean_absolute_error: 1.8118
Epoch 739/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2973 - mean_absolute_error: 0.2973 - val_loss: 1.8107 - val_mean_absolute_error: 1.8107
Epoch 740/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.2805 - mean_absolute_error: 0.2805 - val_loss: 1.8517 - val_mean_absolute_error: 1.8517
Epoch 741/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2511 - mean_absolute_error: 0.2511 - val_loss: 1.8717 - val_mean_absolute_error: 1.8717
Epoch 742/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2858 - mean_absolute_error: 0.2858 - val_loss: 1.7976 - val_mean_absolute_error: 1.7976
Epoch 743/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.2800 - mean_absolute_error: 0.2800 - val_loss: 1.8355 - val_mean_absolute_error: 1.8355
Epoch 744/1000
11/11 [==============================] - 0s 27ms/step - loss: 0.2646 - mean_absolute_error: 0.2646 - val_loss: 1.8394 - val_mean_absolute_error: 1.8394
Epoch 745/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2696 - mean_absolute_error: 0.2696 - val_loss: 1.8213 - val_mean_absolute_error: 1.8213
Epoch 746/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2704 - mean_absolute_error: 0.2704 - val_loss: 1.8304 - val_mean_absolute_error: 1.8304
Epoch 747/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2657 - mean_absolute_error: 0.2657 - val_loss: 1.8491 - val_mean_absolute_error: 1.8491
Epoch 748/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2531 - mean_absolute_error: 0.2531 - val_loss: 1.8788 - val_mean_absolute_error: 1.8788
Epoch 749/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2639 - mean_absolute_error: 0.2639 - val_loss: 1.8668 - val_mean_absolute_error: 1.8668
Epoch 750/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2740 - mean_absolute_error: 0.2740 - val_loss: 1.8920 - val_mean_absolute_error: 1.8920
Epoch 751/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3246 - mean_absolute_error: 0.3246 - val_loss: 1.8322 - val_mean_absolute_error: 1.8322
Epoch 752/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2747 - mean_absolute_error: 0.2747 - val_loss: 1.8115 - val_mean_absolute_error: 1.8115
Epoch 753/1000
11/11 [==============================] - 0s 21ms/step - loss: 0.2718 - mean_absolute_error: 0.2718 - val_loss: 1.8122 - val_mean_absolute_error: 1.8122
Epoch 754/1000
11/11 [==============================] - 0s 30ms/step - loss: 0.2537 - mean_absolute_error: 0.2537 - val_loss: 1.9096 - val_mean_absolute_error: 1.9096
Epoch 755/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3770 - mean_absolute_error: 0.3770 - val_loss: 1.8441 - val_mean_absolute_error: 1.8441
Epoch 756/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.4090 - mean_absolute_error: 0.4090 - val_loss: 1.8322 - val_mean_absolute_error: 1.8322
Epoch 757/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.4031 - mean_absolute_error: 0.4031 - val_loss: 1.8751 - val_mean_absolute_error: 1.8751
Epoch 758/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2885 - mean_absolute_error: 0.2885 - val_loss: 1.8481 - val_mean_absolute_error: 1.8481
Epoch 759/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3036 - mean_absolute_error: 0.3036 - val_loss: 1.8820 - val_mean_absolute_error: 1.8820
Epoch 760/1000

11/11 [==============================] - 0s 16ms/step - loss: 0.3052 - mean_absolute_error: 0.3052 - val_loss: 1.8179 - val_mean_absolute_error: 1.8179
Epoch 761/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2470 - mean_absolute_error: 0.2470 - val_loss: 1.8455 - val_mean_absolute_error: 1.8455
Epoch 762/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2391 - mean_absolute_error: 0.2391 - val_loss: 1.8158 - val_mean_absolute_error: 1.8158
Epoch 763/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.2761 - mean_absolute_error: 0.2761 - val_loss: 1.8561 - val_mean_absolute_error: 1.8561
Epoch 764/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2685 - mean_absolute_error: 0.2685 - val_loss: 1.8822 - val_mean_absolute_error: 1.8822
Epoch 765/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.2636 - mean_absolute_error: 0.2636 - val_loss: 1.8769 - val_mean_absolute_error: 1.8769
Epoch 766/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2556 - mean_absolute_error: 0.2556 - val_loss: 1.8885 - val_mean_absolute_error: 1.8885
Epoch 767/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.2538 - mean_absolute_error: 0.2538 - val_loss: 1.8181 - val_mean_absolute_error: 1.8181
Epoch 768/1000
11/11 [==============================] - 0s 26ms/step - loss: 0.2515 - mean_absolute_error: 0.2515 - val_loss: 1.8785 - val_mean_absolute_error: 1.8785
Epoch 769/1000
11/11 [==============================] - 0s 30ms/step - loss: 0.2852 - mean_absolute_error: 0.2852 - val_loss: 1.8831 - val_mean_absolute_error: 1.8831
Epoch 770/1000
11/11 [==============================] - 0s 25ms/step - loss: 0.2443 - mean_absolute_error: 0.2443 - val_loss: 1.8652 - val_mean_absolute_error: 1.8652
Epoch 771/1000
11/11 [==============================] - 0s 42ms/step - loss: 0.2788 - mean_absolute_error: 0.2788 - val_loss: 1.8564 - val_mean_absolute_error: 1.8564
Epoch 772/1000
11/11 [==============================] - 0s 33ms/step - loss: 0.3067 - mean_absolute_error: 0.3067 - val_loss: 1.8517 - val_mean_absolute_error: 1.8517
Epoch 773/1000
11/11 [==============================] - 0s 21ms/step - loss: 0.3881 - mean_absolute_error: 0.3881 - val_loss: 1.8489 - val_mean_absolute_error: 1.8489
Epoch 774/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2700 - mean_absolute_error: 0.2700 - val_loss: 1.8048 - val_mean_absolute_error: 1.8048
Epoch 775/1000
11/11 [==============================] - 0s 25ms/step - loss: 0.2832 - mean_absolute_error: 0.2832 - val_loss: 1.8223 - val_mean_absolute_error: 1.8223
Epoch 776/1000
11/11 [==============================] - 0s 25ms/step - loss: 0.3464 - mean_absolute_error: 0.3464 - val_loss: 1.9516 - val_mean_absolute_error: 1.9516
Epoch 777/1000
11/11 [==============================] - 0s 24ms/step - loss: 0.3108 - mean_absolute_error: 0.3108 - val_loss: 1.8810 - val_mean_absolute_error: 1.8810
Epoch 778/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2801 - mean_absolute_error: 0.2801 - val_loss: 1.8656 - val_mean_absolute_error: 1.8656
Epoch 779/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.2613 - mean_absolute_error: 0.2613 - val_loss: 1.8018 - val_mean_absolute_error: 1.8018
Epoch 780/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2825 - mean_absolute_error: 0.2825 - val_loss: 1.8626 - val_mean_absolute_error: 1.8626
Epoch 781/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3720 - mean_absolute_error: 0.3720 - val_loss: 1.8558 - val_mean_absolute_error: 1.8558
Epoch 782/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4385 - mean_absolute_error: 0.4385 - val_loss: 1.8174 - val_mean_absolute_error: 1.8174
Epoch 783/1000
11/11 [==============================] - 0s 25ms/step - loss: 0.3442 - mean_absolute_error: 0.3442 - val_loss: 1.9143 - val_mean_absolute_error: 1.9143
Epoch 784/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3143 - mean_absolute_error: 0.3143 - val_loss: 1.8254 - val_mean_absolute_error: 1.8254
Epoch 785/1000
11/11 [==============================] - 0s 21ms/step - loss: 0.2802 - mean_absolute_error: 0.2802 - val_loss: 1.8200 - val_mean_absolute_error: 1.8200
Epoch 786/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.2484 - mean_absolute_error: 0.2484 - val_loss: 1.8515 - val_mean_absolute_error: 1.8515
Epoch 787/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.2551 - mean_absolute_error: 0.2551 - val_loss: 1.8928 - val_mean_absolute_error: 1.8928
Epoch 788/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.2440 - mean_absolute_error: 0.2440 - val_loss: 1.8890 - val_mean_absolute_error: 1.8890
Epoch 789/1000
11/11 [==============================] - 0s 26ms/step - loss: 0.2899 - mean_absolute_error: 0.2899 - val_loss: 1.8406 - val_mean_absolute_error: 1.8406
Epoch 790/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.4034 - mean_absolute_error: 0.4034 - val_loss: 2.0136 - val_mean_absolute_error: 2.0136
Epoch 791/1000
11/11 [==============================] - 0s 21ms/step - loss: 0.4433 - mean_absolute_error: 0.4433 - val_loss: 1.8761 - val_mean_absolute_error: 1.8761
Epoch 792/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.2820 - mean_absolute_error: 0.2820 - val_loss: 1.9642 - val_mean_absolute_error: 1.9642
Epoch 793/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.3242 - mean_absolute_error: 0.3242 - val_loss: 1.8905 - val_mean_absolute_error: 1.8905
Epoch 794/1000
11/11 [==============================] - 0s 24ms/step - loss: 0.3343 - mean_absolute_error: 0.3343 - val_loss: 1.8183 - val_mean_absolute_error: 1.8183
Epoch 795/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2950 - mean_absolute_error: 0.2950 - val_loss: 1.8205 - val_mean_absolute_error: 1.8205
Epoch 796/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3095 - mean_absolute_error: 0.3095 - val_loss: 1.9488 - val_mean_absolute_error: 1.9488
Epoch 797/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2971 - mean_absolute_error: 0.2971 - val_loss: 1.8792 - val_mean_absolute_error: 1.8792
Epoch 798/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.3313 - mean_absolute_error: 0.3313 - val_loss: 1.8225 - val_mean_absolute_error: 1.8225
Epoch 799/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.3256 - mean_absolute_error: 0.3256 - val_loss: 1.8356 - val_mean_absolute_error: 1.8356
Epoch 800/1000
11/11 [==============================] - 0s 38ms/step - loss: 0.3782 - mean_absolute_error: 0.3782 - val_loss: 1.8620 - val_mean_absolute_error: 1.8620
Epoch 801/1000
11/11 [==============================] - 0s 29ms/step - loss: 0.3939 - mean_absolute_error: 0.3939 - val_loss: 2.0133 - val_mean_absolute_error: 2.0133
Epoch 802/1000
11/11 [==============================] - 0s 25ms/step - loss: 0.4540 - mean_absolute_error: 0.4540 - val_loss: 1.8795 - val_mean_absolute_error: 1.8795
Epoch 803/1000
11/11 [==============================] - 0s 36ms/step - loss: 0.2992 - mean_absolute_error: 0.2992 - val_loss: 1.8639 - val_mean_absolute_error: 1.8639
Epoch 804/1000
11/11 [==============================] - 0s 38ms/step - loss: 0.3626 - mean_absolute_error: 0.3626 - val_loss: 1.9387 - val_mean_absolute_error: 1.9387
Epoch 805/1000
11/11 [==============================] - 0s 27ms/step - loss: 0.3684 - mean_absolute_error: 0.3684 - val_loss: 1.8734 - val_mean_absolute_error: 1.8734
Epoch 806/1000
11/11 [==============================] - 0s 37ms/step - loss: 0.3884 - mean_absolute_error: 0.3884 - val_loss: 1.8636 - val_mean_absolute_error: 1.8636
Epoch 807/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3265 - mean_absolute_error: 0.3265 - val_loss: 1.8843 - val_mean_absolute_error: 1.8843
Epoch 808/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2482 - mean_absolute_error: 0.2482 - val_loss: 1.8660 - val_mean_absolute_error: 1.8660
Epoch 809/1000

11/11 [==============================] - 0s 33ms/step - loss: 0.2469 - mean_absolute_error: 0.2469 - val_loss: 1.8750 - val_mean_absolute_error: 1.8750
Epoch 810/1000
11/11 [==============================] - 0s 32ms/step - loss: 0.2601 - mean_absolute_error: 0.2601 - val_loss: 1.8386 - val_mean_absolute_error: 1.8386
Epoch 811/1000
11/11 [==============================] - 0s 32ms/step - loss: 0.2426 - mean_absolute_error: 0.2426 - val_loss: 1.8734 - val_mean_absolute_error: 1.8734
Epoch 812/1000
11/11 [==============================] - 0s 27ms/step - loss: 0.2871 - mean_absolute_error: 0.2871 - val_loss: 1.8536 - val_mean_absolute_error: 1.8536
Epoch 813/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.3176 - mean_absolute_error: 0.3176 - val_loss: 1.8186 - val_mean_absolute_error: 1.8186
Epoch 814/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.3673 - mean_absolute_error: 0.3673 - val_loss: 1.9347 - val_mean_absolute_error: 1.9347
Epoch 815/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2734 - mean_absolute_error: 0.2734 - val_loss: 1.8725 - val_mean_absolute_error: 1.8725
Epoch 816/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.2472 - mean_absolute_error: 0.2472 - val_loss: 1.8716 - val_mean_absolute_error: 1.8716
Epoch 817/1000
11/11 [==============================] - 0s 21ms/step - loss: 0.2570 - mean_absolute_error: 0.2570 - val_loss: 1.8539 - val_mean_absolute_error: 1.8539
Epoch 818/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.2967 - mean_absolute_error: 0.2967 - val_loss: 1.9192 - val_mean_absolute_error: 1.9192
Epoch 819/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.3423 - mean_absolute_error: 0.3423 - val_loss: 1.8397 - val_mean_absolute_error: 1.8397
Epoch 820/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.4612 - mean_absolute_error: 0.4612 - val_loss: 1.8903 - val_mean_absolute_error: 1.8903
Epoch 821/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3150 - mean_absolute_error: 0.3150 - val_loss: 1.9223 - val_mean_absolute_error: 1.9223
Epoch 822/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.3213 - mean_absolute_error: 0.3213 - val_loss: 1.8325 - val_mean_absolute_error: 1.8325
Epoch 823/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.3151 - mean_absolute_error: 0.3151 - val_loss: 1.8579 - val_mean_absolute_error: 1.8579
Epoch 824/1000
11/11 [==============================] - 0s 21ms/step - loss: 0.3271 - mean_absolute_error: 0.3271 - val_loss: 1.8681 - val_mean_absolute_error: 1.8681
Epoch 825/1000
11/11 [==============================] - 0s 24ms/step - loss: 0.3745 - mean_absolute_error: 0.3745 - val_loss: 1.9364 - val_mean_absolute_error: 1.9364
Epoch 826/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.3343 - mean_absolute_error: 0.3343 - val_loss: 1.8508 - val_mean_absolute_error: 1.8508
Epoch 827/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2664 - mean_absolute_error: 0.2664 - val_loss: 1.8149 - val_mean_absolute_error: 1.8149
Epoch 828/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.3067 - mean_absolute_error: 0.3067 - val_loss: 1.8470 - val_mean_absolute_error: 1.8470
Epoch 829/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2713 - mean_absolute_error: 0.2713 - val_loss: 1.8668 - val_mean_absolute_error: 1.8668
Epoch 830/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.2634 - mean_absolute_error: 0.2634 - val_loss: 1.8274 - val_mean_absolute_error: 1.8274
Epoch 831/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.2814 - mean_absolute_error: 0.2814 - val_loss: 1.8833 - val_mean_absolute_error: 1.8833
Epoch 832/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2884 - mean_absolute_error: 0.2884 - val_loss: 1.9276 - val_mean_absolute_error: 1.9276
Epoch 833/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3466 - mean_absolute_error: 0.3466 - val_loss: 1.8148 - val_mean_absolute_error: 1.8148
Epoch 834/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.2557 - mean_absolute_error: 0.2557 - val_loss: 1.9080 - val_mean_absolute_error: 1.9080
Epoch 835/1000
11/11 [==============================] - 0s 21ms/step - loss: 0.3320 - mean_absolute_error: 0.3320 - val_loss: 1.8484 - val_mean_absolute_error: 1.8484
Epoch 836/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.3001 - mean_absolute_error: 0.3001 - val_loss: 1.8056 - val_mean_absolute_error: 1.8056
Epoch 837/1000
11/11 [==============================] - 0s 15ms/step - loss: 0.3194 - mean_absolute_error: 0.3194 - val_loss: 1.9543 - val_mean_absolute_error: 1.9543
Epoch 838/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3305 - mean_absolute_error: 0.3305 - val_loss: 1.8196 - val_mean_absolute_error: 1.8196
Epoch 839/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3569 - mean_absolute_error: 0.3569 - val_loss: 1.9930 - val_mean_absolute_error: 1.9930
Epoch 840/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4637 - mean_absolute_error: 0.4637 - val_loss: 2.0142 - val_mean_absolute_error: 2.0142
Epoch 841/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.4436 - mean_absolute_error: 0.4436 - val_loss: 1.8709 - val_mean_absolute_error: 1.8709
Epoch 842/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3349 - mean_absolute_error: 0.3349 - val_loss: 1.8544 - val_mean_absolute_error: 1.8544
Epoch 843/1000
11/11 [==============================] - 0s 26ms/step - loss: 0.2895 - mean_absolute_error: 0.2895 - val_loss: 1.8034 - val_mean_absolute_error: 1.8034
Epoch 844/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2632 - mean_absolute_error: 0.2632 - val_loss: 1.8638 - val_mean_absolute_error: 1.8638
Epoch 845/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2276 - mean_absolute_error: 0.2276 - val_loss: 1.8128 - val_mean_absolute_error: 1.8128
Epoch 846/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2263 - mean_absolute_error: 0.2263 - val_loss: 1.8177 - val_mean_absolute_error: 1.8177
Epoch 847/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2384 - mean_absolute_error: 0.2384 - val_loss: 1.8414 - val_mean_absolute_error: 1.8414
Epoch 848/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2844 - mean_absolute_error: 0.2844 - val_loss: 1.8037 - val_mean_absolute_error: 1.8037
Epoch 849/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2584 - mean_absolute_error: 0.2584 - val_loss: 1.8401 - val_mean_absolute_error: 1.8401
Epoch 850/1000
11/11 [==============================] - 0s 21ms/step - loss: 0.2552 - mean_absolute_error: 0.2552 - val_loss: 1.8720 - val_mean_absolute_error: 1.8720
Epoch 851/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2761 - mean_absolute_error: 0.2761 - val_loss: 1.8700 - val_mean_absolute_error: 1.8700
Epoch 852/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.3154 - mean_absolute_error: 0.3154 - val_loss: 1.8749 - val_mean_absolute_error: 1.8749
Epoch 853/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.2791 - mean_absolute_error: 0.2791 - val_loss: 1.8265 - val_mean_absolute_error: 1.8265
Epoch 854/1000
11/11 [==============================] - 0s 30ms/step - loss: 0.2366 - mean_absolute_error: 0.2366 - val_loss: 1.8363 - val_mean_absolute_error: 1.8363
Epoch 855/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2770 - mean_absolute_error: 0.2770 - val_loss: 1.8464 - val_mean_absolute_error: 1.8464
Epoch 856/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3285 - mean_absolute_error: 0.3285 - val_loss: 1.9367 - val_mean_absolute_error: 1.9367
Epoch 857/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.2874 - mean_absolute_error: 0.2874 - val_loss: 1.9298 - val_mean_absolute_error: 1.9298
Epoch 858/1000

11/11 [==============================] - 0s 22ms/step - loss: 0.2954 - mean_absolute_error: 0.2954 - val_loss: 1.8972 - val_mean_absolute_error: 1.8972
Epoch 859/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2539 - mean_absolute_error: 0.2539 - val_loss: 1.9341 - val_mean_absolute_error: 1.9341
Epoch 860/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3469 - mean_absolute_error: 0.3469 - val_loss: 1.8170 - val_mean_absolute_error: 1.8170
Epoch 861/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2894 - mean_absolute_error: 0.2894 - val_loss: 1.8610 - val_mean_absolute_error: 1.8610
Epoch 862/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2684 - mean_absolute_error: 0.2684 - val_loss: 1.8622 - val_mean_absolute_error: 1.8622
Epoch 863/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.2573 - mean_absolute_error: 0.2573 - val_loss: 1.8524 - val_mean_absolute_error: 1.8524
Epoch 864/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2277 - mean_absolute_error: 0.2277 - val_loss: 1.8794 - val_mean_absolute_error: 1.8794
Epoch 865/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2740 - mean_absolute_error: 0.2740 - val_loss: 1.8719 - val_mean_absolute_error: 1.8719
Epoch 866/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2825 - mean_absolute_error: 0.2825 - val_loss: 1.8895 - val_mean_absolute_error: 1.8895
Epoch 867/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3041 - mean_absolute_error: 0.3041 - val_loss: 1.7868 - val_mean_absolute_error: 1.7868
Epoch 868/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2681 - mean_absolute_error: 0.2681 - val_loss: 1.8188 - val_mean_absolute_error: 1.8188
Epoch 869/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2551 - mean_absolute_error: 0.2551 - val_loss: 1.7904 - val_mean_absolute_error: 1.7904
Epoch 870/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.4026 - mean_absolute_error: 0.4026 - val_loss: 1.7978 - val_mean_absolute_error: 1.7978
Epoch 871/1000
11/11 [==============================] - 0s 24ms/step - loss: 0.3124 - mean_absolute_error: 0.3124 - val_loss: 1.8302 - val_mean_absolute_error: 1.8302
Epoch 872/1000
11/11 [==============================] - 0s 21ms/step - loss: 0.3137 - mean_absolute_error: 0.3137 - val_loss: 1.8263 - val_mean_absolute_error: 1.8263
Epoch 873/1000
11/11 [==============================] - 0s 27ms/step - loss: 0.2745 - mean_absolute_error: 0.2745 - val_loss: 1.8218 - val_mean_absolute_error: 1.8218
Epoch 874/1000
11/11 [==============================] - 0s 38ms/step - loss: 0.2469 - mean_absolute_error: 0.2469 - val_loss: 1.8305 - val_mean_absolute_error: 1.8305
Epoch 875/1000
11/11 [==============================] - 1s 50ms/step - loss: 0.2541 - mean_absolute_error: 0.2541 - val_loss: 1.8975 - val_mean_absolute_error: 1.8975
Epoch 876/1000
11/11 [==============================] - 0s 34ms/step - loss: 0.2576 - mean_absolute_error: 0.2576 - val_loss: 1.8385 - val_mean_absolute_error: 1.8385
Epoch 877/1000
11/11 [==============================] - 0s 38ms/step - loss: 0.3023 - mean_absolute_error: 0.3023 - val_loss: 1.8447 - val_mean_absolute_error: 1.8447
Epoch 878/1000
11/11 [==============================] - 0s 33ms/step - loss: 0.3398 - mean_absolute_error: 0.3398 - val_loss: 1.8728 - val_mean_absolute_error: 1.8728
Epoch 879/1000
11/11 [==============================] - 0s 38ms/step - loss: 0.2561 - mean_absolute_error: 0.2561 - val_loss: 1.8456 - val_mean_absolute_error: 1.8456
Epoch 880/1000
11/11 [==============================] - 1s 49ms/step - loss: 0.2577 - mean_absolute_error: 0.2577 - val_loss: 1.8057 - val_mean_absolute_error: 1.8057
Epoch 881/1000
11/11 [==============================] - 0s 29ms/step - loss: 0.2662 - mean_absolute_error: 0.2662 - val_loss: 1.9061 - val_mean_absolute_error: 1.9061
Epoch 882/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.3251 - mean_absolute_error: 0.3251 - val_loss: 1.8347 - val_mean_absolute_error: 1.8347
Epoch 883/1000
11/11 [==============================] - 0s 21ms/step - loss: 0.2552 - mean_absolute_error: 0.2552 - val_loss: 1.8586 - val_mean_absolute_error: 1.8586
Epoch 884/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2732 - mean_absolute_error: 0.2732 - val_loss: 1.8977 - val_mean_absolute_error: 1.8977
Epoch 885/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3276 - mean_absolute_error: 0.3276 - val_loss: 1.9453 - val_mean_absolute_error: 1.9453
Epoch 886/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3262 - mean_absolute_error: 0.3262 - val_loss: 1.8517 - val_mean_absolute_error: 1.8517
Epoch 887/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2592 - mean_absolute_error: 0.2592 - val_loss: 1.8730 - val_mean_absolute_error: 1.8730
Epoch 888/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2549 - mean_absolute_error: 0.2549 - val_loss: 1.8698 - val_mean_absolute_error: 1.8698
Epoch 889/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.3379 - mean_absolute_error: 0.3379 - val_loss: 1.8631 - val_mean_absolute_error: 1.8631
Epoch 890/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2532 - mean_absolute_error: 0.2532 - val_loss: 1.8179 - val_mean_absolute_error: 1.8179
Epoch 891/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2533 - mean_absolute_error: 0.2533 - val_loss: 1.8287 - val_mean_absolute_error: 1.8287
Epoch 892/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3717 - mean_absolute_error: 0.3717 - val_loss: 1.9242 - val_mean_absolute_error: 1.9242
Epoch 893/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3221 - mean_absolute_error: 0.3221 - val_loss: 1.8674 - val_mean_absolute_error: 1.8674
Epoch 894/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2434 - mean_absolute_error: 0.2434 - val_loss: 1.9197 - val_mean_absolute_error: 1.9197
Epoch 895/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2673 - mean_absolute_error: 0.2673 - val_loss: 1.8788 - val_mean_absolute_error: 1.8788
Epoch 896/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.2753 - mean_absolute_error: 0.2753 - val_loss: 1.7929 - val_mean_absolute_error: 1.7929
Epoch 897/1000
11/11 [==============================] - 0s 25ms/step - loss: 0.2708 - mean_absolute_error: 0.2708 - val_loss: 1.8422 - val_mean_absolute_error: 1.8422
Epoch 898/1000
11/11 [==============================] - 0s 21ms/step - loss: 0.2760 - mean_absolute_error: 0.2760 - val_loss: 1.8509 - val_mean_absolute_error: 1.8509
Epoch 899/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.2728 - mean_absolute_error: 0.2728 - val_loss: 1.8783 - val_mean_absolute_error: 1.8783
Epoch 900/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2889 - mean_absolute_error: 0.2889 - val_loss: 1.8867 - val_mean_absolute_error: 1.8867
Epoch 901/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2395 - mean_absolute_error: 0.2395 - val_loss: 1.8566 - val_mean_absolute_error: 1.8566
Epoch 902/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2707 - mean_absolute_error: 0.2707 - val_loss: 1.8250 - val_mean_absolute_error: 1.8250
Epoch 903/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.2618 - mean_absolute_error: 0.2618 - val_loss: 1.9150 - val_mean_absolute_error: 1.9150
Epoch 904/1000
11/11 [==============================] - 0s 30ms/step - loss: 0.2434 - mean_absolute_error: 0.2434 - val_loss: 1.8524 - val_mean_absolute_error: 1.8524
Epoch 905/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2353 - mean_absolute_error: 0.2353 - val_loss: 1.8085 - val_mean_absolute_error: 1.8085
Epoch 906/1000
11/11 [==============================] - 0s 24ms/step - loss: 0.2642 - mean_absolute_error: 0.2642 - val_loss: 1.8396 - val_mean_absolute_error: 1.8396
Epoch 907/1000

11/11 [==============================] - 0s 19ms/step - loss: 0.2601 - mean_absolute_error: 0.2601 - val_loss: 1.8318 - val_mean_absolute_error: 1.8318
Epoch 908/1000
11/11 [==============================] - 0s 24ms/step - loss: 0.2290 - mean_absolute_error: 0.2290 - val_loss: 1.8560 - val_mean_absolute_error: 1.8560
Epoch 909/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.2121 - mean_absolute_error: 0.2121 - val_loss: 1.8625 - val_mean_absolute_error: 1.8625
Epoch 910/1000
11/11 [==============================] - 0s 21ms/step - loss: 0.2538 - mean_absolute_error: 0.2538 - val_loss: 1.8601 - val_mean_absolute_error: 1.8601
Epoch 911/1000
11/11 [==============================] - 0s 31ms/step - loss: 0.2667 - mean_absolute_error: 0.2667 - val_loss: 1.8284 - val_mean_absolute_error: 1.8284
Epoch 912/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2570 - mean_absolute_error: 0.2570 - val_loss: 1.8484 - val_mean_absolute_error: 1.8484
Epoch 913/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2415 - mean_absolute_error: 0.2415 - val_loss: 1.8196 - val_mean_absolute_error: 1.8196
Epoch 914/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2394 - mean_absolute_error: 0.2394 - val_loss: 1.8492 - val_mean_absolute_error: 1.8492
Epoch 915/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.2216 - mean_absolute_error: 0.2216 - val_loss: 1.8737 - val_mean_absolute_error: 1.8737
Epoch 916/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2662 - mean_absolute_error: 0.2662 - val_loss: 2.0007 - val_mean_absolute_error: 2.0007
Epoch 917/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.3586 - mean_absolute_error: 0.3586 - val_loss: 1.8384 - val_mean_absolute_error: 1.8384
Epoch 918/1000
11/11 [==============================] - 0s 21ms/step - loss: 0.3575 - mean_absolute_error: 0.3575 - val_loss: 1.8245 - val_mean_absolute_error: 1.8245
Epoch 919/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3719 - mean_absolute_error: 0.3719 - val_loss: 1.9788 - val_mean_absolute_error: 1.9788
Epoch 920/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.4045 - mean_absolute_error: 0.4045 - val_loss: 1.8744 - val_mean_absolute_error: 1.8744
Epoch 921/1000
11/11 [==============================] - 0s 24ms/step - loss: 0.3682 - mean_absolute_error: 0.3682 - val_loss: 1.8889 - val_mean_absolute_error: 1.8889
Epoch 922/1000
11/11 [==============================] - 0s 21ms/step - loss: 0.3540 - mean_absolute_error: 0.3540 - val_loss: 1.8398 - val_mean_absolute_error: 1.8398
Epoch 923/1000
11/11 [==============================] - 0s 21ms/step - loss: 0.2606 - mean_absolute_error: 0.2606 - val_loss: 1.9063 - val_mean_absolute_error: 1.9063
Epoch 924/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.2631 - mean_absolute_error: 0.2631 - val_loss: 1.8705 - val_mean_absolute_error: 1.8705
Epoch 925/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.3061 - mean_absolute_error: 0.3061 - val_loss: 1.8790 - val_mean_absolute_error: 1.8790
Epoch 926/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.2549 - mean_absolute_error: 0.2549 - val_loss: 1.8586 - val_mean_absolute_error: 1.8586
Epoch 927/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2485 - mean_absolute_error: 0.2485 - val_loss: 1.8406 - val_mean_absolute_error: 1.8406
Epoch 928/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2760 - mean_absolute_error: 0.2760 - val_loss: 1.8135 - val_mean_absolute_error: 1.8135
Epoch 929/1000
11/11 [==============================] - 0s 21ms/step - loss: 0.3608 - mean_absolute_error: 0.3608 - val_loss: 1.9603 - val_mean_absolute_error: 1.9603
Epoch 930/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.4401 - mean_absolute_error: 0.4401 - val_loss: 1.9393 - val_mean_absolute_error: 1.9393
Epoch 931/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.3893 - mean_absolute_error: 0.3893 - val_loss: 1.7998 - val_mean_absolute_error: 1.7998
Epoch 932/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2931 - mean_absolute_error: 0.2931 - val_loss: 1.9723 - val_mean_absolute_error: 1.9723
Epoch 933/1000
11/11 [==============================] - 0s 21ms/step - loss: 0.3520 - mean_absolute_error: 0.3520 - val_loss: 1.8243 - val_mean_absolute_error: 1.8243
Epoch 934/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2820 - mean_absolute_error: 0.2820 - val_loss: 1.9306 - val_mean_absolute_error: 1.9306
Epoch 935/1000
11/11 [==============================] - 0s 21ms/step - loss: 0.3140 - mean_absolute_error: 0.3140 - val_loss: 1.8732 - val_mean_absolute_error: 1.8732
Epoch 936/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.2647 - mean_absolute_error: 0.2647 - val_loss: 1.8745 - val_mean_absolute_error: 1.8745
Epoch 937/1000
11/11 [==============================] - 0s 26ms/step - loss: 0.2394 - mean_absolute_error: 0.2394 - val_loss: 1.8204 - val_mean_absolute_error: 1.8204
Epoch 938/1000
11/11 [==============================] - 0s 25ms/step - loss: 0.2351 - mean_absolute_error: 0.2351 - val_loss: 1.8630 - val_mean_absolute_error: 1.8630
Epoch 939/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3353 - mean_absolute_error: 0.3353 - val_loss: 1.8283 - val_mean_absolute_error: 1.8283
Epoch 940/1000
11/11 [==============================] - 0s 25ms/step - loss: 0.3389 - mean_absolute_error: 0.3389 - val_loss: 1.8234 - val_mean_absolute_error: 1.8234
Epoch 941/1000
11/11 [==============================] - 0s 30ms/step - loss: 0.3264 - mean_absolute_error: 0.3264 - val_loss: 1.8632 - val_mean_absolute_error: 1.8632
Epoch 942/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3300 - mean_absolute_error: 0.3300 - val_loss: 1.8537 - val_mean_absolute_error: 1.8537
Epoch 943/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.3057 - mean_absolute_error: 0.3057 - val_loss: 1.8142 - val_mean_absolute_error: 1.8142
Epoch 944/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.2842 - mean_absolute_error: 0.2842 - val_loss: 1.8565 - val_mean_absolute_error: 1.8565
Epoch 945/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.2116 - mean_absolute_error: 0.2116 - val_loss: 1.9020 - val_mean_absolute_error: 1.9020
Epoch 946/1000
11/11 [==============================] - 0s 30ms/step - loss: 0.3292 - mean_absolute_error: 0.3292 - val_loss: 1.8313 - val_mean_absolute_error: 1.8313
Epoch 947/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3387 - mean_absolute_error: 0.3387 - val_loss: 1.8751 - val_mean_absolute_error: 1.8751
Epoch 948/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.3881 - mean_absolute_error: 0.3881 - val_loss: 1.8444 - val_mean_absolute_error: 1.8444
Epoch 949/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.2778 - mean_absolute_error: 0.2778 - val_loss: 1.8577 - val_mean_absolute_error: 1.8577
Epoch 950/1000
11/11 [==============================] - 0s 24ms/step - loss: 0.3184 - mean_absolute_error: 0.3184 - val_loss: 1.8376 - val_mean_absolute_error: 1.8376
Epoch 951/1000
11/11 [==============================] - 0s 28ms/step - loss: 0.2382 - mean_absolute_error: 0.2382 - val_loss: 1.9006 - val_mean_absolute_error: 1.9006
Epoch 952/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.2330 - mean_absolute_error: 0.2330 - val_loss: 1.8684 - val_mean_absolute_error: 1.8684
Epoch 953/1000
11/11 [==============================] - 0s 26ms/step - loss: 0.2357 - mean_absolute_error: 0.2357 - val_loss: 1.8210 - val_mean_absolute_error: 1.8210
Epoch 954/1000
11/11 [==============================] - 0s 21ms/step - loss: 0.2242 - mean_absolute_error: 0.2242 - val_loss: 1.9570 - val_mean_absolute_error: 1.9570
Epoch 955/1000
11/11 [==============================] - 0s 26ms/step - loss: 0.3410 - mean_absolute_error: 0.3410 - val_loss: 1.8226 - val_mean_absolute_error: 1.8226
Epoch 956/1000

11/11 [==============================] - 0s 17ms/step - loss: 0.3256 - mean_absolute_error: 0.3256 - val_loss: 1.8904 - val_mean_absolute_error: 1.8904
Epoch 957/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.2623 - mean_absolute_error: 0.2623 - val_loss: 1.8110 - val_mean_absolute_error: 1.8110
Epoch 958/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2571 - mean_absolute_error: 0.2571 - val_loss: 1.8356 - val_mean_absolute_error: 1.8356
Epoch 959/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2676 - mean_absolute_error: 0.2676 - val_loss: 1.9081 - val_mean_absolute_error: 1.9081
Epoch 960/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2227 - mean_absolute_error: 0.2227 - val_loss: 1.8580 - val_mean_absolute_error: 1.8580
Epoch 961/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2454 - mean_absolute_error: 0.2454 - val_loss: 1.9113 - val_mean_absolute_error: 1.9113
Epoch 962/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2727 - mean_absolute_error: 0.2727 - val_loss: 1.8450 - val_mean_absolute_error: 1.8450
Epoch 963/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.3217 - mean_absolute_error: 0.3217 - val_loss: 1.8382 - val_mean_absolute_error: 1.8382
Epoch 964/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2685 - mean_absolute_error: 0.2685 - val_loss: 1.8895 - val_mean_absolute_error: 1.8895
Epoch 965/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2877 - mean_absolute_error: 0.2877 - val_loss: 1.8294 - val_mean_absolute_error: 1.8294
Epoch 966/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2557 - mean_absolute_error: 0.2557 - val_loss: 1.9436 - val_mean_absolute_error: 1.9436
Epoch 967/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.3254 - mean_absolute_error: 0.3254 - val_loss: 1.8558 - val_mean_absolute_error: 1.8558
Epoch 968/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.2541 - mean_absolute_error: 0.2541 - val_loss: 1.8906 - val_mean_absolute_error: 1.8906
Epoch 969/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.3246 - mean_absolute_error: 0.3246 - val_loss: 1.8644 - val_mean_absolute_error: 1.8644
Epoch 970/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.2427 - mean_absolute_error: 0.2427 - val_loss: 1.8858 - val_mean_absolute_error: 1.8858
Epoch 971/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2744 - mean_absolute_error: 0.2744 - val_loss: 1.9356 - val_mean_absolute_error: 1.9356
Epoch 972/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.2690 - mean_absolute_error: 0.2690 - val_loss: 1.8688 - val_mean_absolute_error: 1.8688
Epoch 973/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.2391 - mean_absolute_error: 0.2391 - val_loss: 1.9277 - val_mean_absolute_error: 1.9277
Epoch 974/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.2962 - mean_absolute_error: 0.2962 - val_loss: 1.8449 - val_mean_absolute_error: 1.8449
Epoch 975/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.2461 - mean_absolute_error: 0.2461 - val_loss: 1.8429 - val_mean_absolute_error: 1.8429
Epoch 976/1000
11/11 [==============================] - 0s 29ms/step - loss: 0.2165 - mean_absolute_error: 0.2165 - val_loss: 1.8700 - val_mean_absolute_error: 1.8700
Epoch 977/1000
11/11 [==============================] - 0s 24ms/step - loss: 0.2466 - mean_absolute_error: 0.2466 - val_loss: 1.8496 - val_mean_absolute_error: 1.8496
Epoch 978/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2229 - mean_absolute_error: 0.2229 - val_loss: 1.8058 - val_mean_absolute_error: 1.8058
Epoch 979/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3092 - mean_absolute_error: 0.3092 - val_loss: 1.9176 - val_mean_absolute_error: 1.9176
Epoch 980/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2875 - mean_absolute_error: 0.2875 - val_loss: 1.8648 - val_mean_absolute_error: 1.8648
Epoch 981/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2791 - mean_absolute_error: 0.2791 - val_loss: 1.8193 - val_mean_absolute_error: 1.8193
Epoch 982/1000
11/11 [==============================] - 0s 22ms/step - loss: 0.2464 - mean_absolute_error: 0.2464 - val_loss: 1.7983 - val_mean_absolute_error: 1.7983
Epoch 983/1000
11/11 [==============================] - 0s 21ms/step - loss: 0.2970 - mean_absolute_error: 0.2970 - val_loss: 1.8722 - val_mean_absolute_error: 1.8722
Epoch 984/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2931 - mean_absolute_error: 0.2931 - val_loss: 1.8675 - val_mean_absolute_error: 1.8675
Epoch 985/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2217 - mean_absolute_error: 0.2217 - val_loss: 1.8603 - val_mean_absolute_error: 1.8603
Epoch 986/1000
11/11 [==============================] - 0s 19ms/step - loss: 0.2271 - mean_absolute_error: 0.2271 - val_loss: 1.8720 - val_mean_absolute_error: 1.8720
Epoch 987/1000
11/11 [==============================] - 0s 21ms/step - loss: 0.2967 - mean_absolute_error: 0.2967 - val_loss: 1.7959 - val_mean_absolute_error: 1.7959
Epoch 988/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3011 - mean_absolute_error: 0.3011 - val_loss: 1.9280 - val_mean_absolute_error: 1.9280
Epoch 989/1000
11/11 [==============================] - 0s 23ms/step - loss: 0.2765 - mean_absolute_error: 0.2765 - val_loss: 1.8617 - val_mean_absolute_error: 1.8617
Epoch 990/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.2380 - mean_absolute_error: 0.2380 - val_loss: 1.8409 - val_mean_absolute_error: 1.8409
Epoch 991/1000
11/11 [==============================] - 0s 24ms/step - loss: 0.2493 - mean_absolute_error: 0.2493 - val_loss: 1.8827 - val_mean_absolute_error: 1.8827
Epoch 992/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2613 - mean_absolute_error: 0.2613 - val_loss: 1.9859 - val_mean_absolute_error: 1.9859
Epoch 993/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.3524 - mean_absolute_error: 0.3524 - val_loss: 1.8358 - val_mean_absolute_error: 1.8358
Epoch 994/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.3533 - mean_absolute_error: 0.3533 - val_loss: 1.8476 - val_mean_absolute_error: 1.8476
Epoch 995/1000
11/11 [==============================] - 0s 27ms/step - loss: 0.2557 - mean_absolute_error: 0.2557 - val_loss: 1.8176 - val_mean_absolute_error: 1.8176
Epoch 996/1000
11/11 [==============================] - 0s 16ms/step - loss: 0.2745 - mean_absolute_error: 0.2745 - val_loss: 1.8135 - val_mean_absolute_error: 1.8135
Epoch 997/1000
11/11 [==============================] - 0s 17ms/step - loss: 0.2401 - mean_absolute_error: 0.2401 - val_loss: 1.8167 - val_mean_absolute_error: 1.8167
Epoch 998/1000
11/11 [==============================] - 0s 21ms/step - loss: 0.3091 - mean_absolute_error: 0.3091 - val_loss: 1.8440 - val_mean_absolute_error: 1.8440
Epoch 999/1000
11/11 [==============================] - 0s 18ms/step - loss: 0.3491 - mean_absolute_error: 0.3491 - val_loss: 1.9753 - val_mean_absolute_error: 1.9753
Epoch 1000/1000
11/11 [==============================] - 0s 20ms/step - loss: 0.3435 - mean_absolute_error: 0.3435 - val_loss: 1.8265 - val_mean_absolute_error: 1.8265
32/32 [==============================] - 0s 3ms/step

,iter,Model,ACC,AFS,MAE,RMSE,RMSE2,50th%error,75th%error,95th%error,avg_le
0,0,MC-ACNNR_dual,1.0,2.499237,2.499237,2.539453,4.460683,2.097947,3.446978,4.812274,4.094710
1,1,MC-ACNNR_dual,1.0,2.526197,2.526197,2.567692,4.501695,1.998325,3.113951,5.415851,4.159268
2,2,MC-ACNNR_dual,1.0,2.610890,2.610890,2.664917,4.747486,2.301337,3.189365,5.103476,4.355452